using Microsoft.AspNetCore.Mvc;
using TransportERP.Api.Authorization;
using TransportERP.Application.Org;
using TransportERP.Contracts.Core;
using TransportERP.Contracts.Geo;
using TransportERP.Contracts.Org;

namespace TransportERP.Api.Controllers;

/// <summary>Server-enforced GEN-008..015 API. Clients receive only DTOs and capabilities; permissions are never trusted from the desktop.</summary>
[ApiController]
public abstract class OrgControllerBase(IOrgService service) : ControllerBase
{
    protected async Task<ActionResult<PagedResponse<OrgDto>>> List(OrgResource r,string permission,[FromQuery] PagedQueryRequest q,CancellationToken ct) => Authorize(permission,out var c) ? Ok(await service.ListAsync(r,q,c,ct)) : Denied<PagedResponse<OrgDto>>(c);
    protected async Task<ActionResult<OrgDto>> Get(OrgResource r,string permission,Guid id,CancellationToken ct) { if(!Authorize(permission,out var c))return Denied<OrgDto>(c); return await service.GetAsync(r,id,c,ct) is { } row ? Ok(row) : NotFound<OrgDto>(c); }
    protected async Task<ActionResult<OrgDto>> Create(OrgResource r,string permission,OrgWriteRequest request,CancellationToken ct) { if(!Authorize(permission,out var c))return Denied<OrgDto>(c); return Ok(await service.CreateAsync(r,request,c,ct)); }
    protected async Task<ActionResult<OrgDto>> Update(OrgResource r,string permission,Guid id,OrgWriteRequest request,CancellationToken ct) { if(!Authorize(permission,out var c))return Denied<OrgDto>(c); return await service.UpdateAsync(r,id,request,c,ct) is { } row ? Ok(row) : NotFound<OrgDto>(c); }
    protected async Task<ActionResult<OrgDto>> Disable(OrgResource r,string permission,Guid id,OrgLifecycleRequest request,CancellationToken ct) { if(!Authorize(permission,out var c))return Denied<OrgDto>(c); return await service.DisableAsync(r,id,request,c,ct) is { } row ? Ok(row) : NotFound<OrgDto>(c); }
    protected bool Authorize(string permission,out OperationContext c){if(!User.TryGetOperationContext(Request,out c))return false;return User.HasPermission(permission);}
    protected ActionResult<T> Denied<T>(OperationContext c) => StatusCode(StatusCodes.Status403Forbidden,new TransportError(TransportErrorCode.PermissionDenied,c?.CorrelationId??Guid.CreateVersion7(),"error.permissionDenied"));
    protected ActionResult<T> NotFound<T>(OperationContext c) => StatusCode(StatusCodes.Status404NotFound,new TransportError(TransportErrorCode.NotFound,c.CorrelationId,"error.notFound"));
}
[Route("api/v1/general/currencies")] public sealed class CurrenciesController(IOrgService s):OrgControllerBase(s){[HttpGet]public Task<ActionResult<PagedResponse<OrgDto>>> List([FromQuery]PagedQueryRequest q,CancellationToken c)=>base.List(OrgResource.Currencies,OrgPermissions.CurrencyView,q,c);[HttpGet("{id:guid}")]public Task<ActionResult<OrgDto>> Get(Guid id,CancellationToken c)=>base.Get(OrgResource.Currencies,OrgPermissions.CurrencyView,id,c);[HttpPost]public Task<ActionResult<OrgDto>> Create(OrgWriteRequest q,CancellationToken c)=>base.Create(OrgResource.Currencies,OrgPermissions.CurrencyManage,q,c);[HttpPut("{id:guid}")]public Task<ActionResult<OrgDto>> Update(Guid id,OrgWriteRequest q,CancellationToken c)=>base.Update(OrgResource.Currencies,OrgPermissions.CurrencyManage,id,q,c);[HttpPost("{id:guid}/disable")]public Task<ActionResult<OrgDto>> Disable(Guid id,OrgLifecycleRequest q,CancellationToken c)=>base.Disable(OrgResource.Currencies,OrgPermissions.CurrencyManage,id,q,c);}
[Route("api/v1/general/exchange-rates")] public sealed class ExchangeRatesController(IOrgService s):OrgControllerBase(s){[HttpGet]public Task<ActionResult<PagedResponse<OrgDto>>> List([FromQuery]PagedQueryRequest q,CancellationToken c)=>base.List(OrgResource.ExchangeRates,OrgPermissions.ExchangeRateView,q,c);[HttpPost]public Task<ActionResult<OrgDto>> Create(OrgWriteRequest q,CancellationToken c)=>base.Create(OrgResource.ExchangeRates,OrgPermissions.ExchangeRateManage,q,c);[HttpPut("{id:guid}")]public Task<ActionResult<OrgDto>> Update(Guid id,OrgWriteRequest q,CancellationToken c)=>base.Update(OrgResource.ExchangeRates,OrgPermissions.ExchangeRateManage,id,q,c);}
[Route("api/v1/general/companies")] public sealed class CompaniesController(IOrgService s):OrgControllerBase(s){[HttpGet]public Task<ActionResult<PagedResponse<OrgDto>>> List([FromQuery]PagedQueryRequest q,CancellationToken c)=>base.List(OrgResource.Companies,OrgPermissions.CompanyView,q,c);[HttpPost]public Task<ActionResult<OrgDto>> Create(OrgWriteRequest q,CancellationToken c)=>base.Create(OrgResource.Companies,OrgPermissions.CompanyManage,q,c);[HttpPut("{id:guid}")]public Task<ActionResult<OrgDto>> Update(Guid id,OrgWriteRequest q,CancellationToken c)=>base.Update(OrgResource.Companies,OrgPermissions.CompanyManage,id,q,c);}
[Route("api/v1/general/branches")] public sealed class BranchesController(IOrgService s):OrgControllerBase(s){[HttpGet]public Task<ActionResult<PagedResponse<OrgDto>>> List([FromQuery]PagedQueryRequest q,CancellationToken c)=>base.List(OrgResource.Branches,OrgPermissions.BranchView,q,c);[HttpPost]public Task<ActionResult<OrgDto>> Create(OrgWriteRequest q,CancellationToken c)=>base.Create(OrgResource.Branches,OrgPermissions.BranchManage,q,c);[HttpPut("{id:guid}")]public Task<ActionResult<OrgDto>> Update(Guid id,OrgWriteRequest q,CancellationToken c)=>base.Update(OrgResource.Branches,OrgPermissions.BranchManage,id,q,c);}
[Route("api/v1/general/fiscal-years")] public sealed class FiscalYearsController(IOrgService s):OrgControllerBase(s){[HttpGet]public Task<ActionResult<PagedResponse<OrgDto>>> List([FromQuery]PagedQueryRequest q,CancellationToken c)=>base.List(OrgResource.FiscalYears,OrgPermissions.FiscalYearView,q,c);[HttpPost]public Task<ActionResult<OrgDto>> Create(OrgWriteRequest q,CancellationToken c)=>base.Create(OrgResource.FiscalYears,OrgPermissions.FiscalYearManage,q,c);[HttpPost("{id:guid}/{transition:regex(^open$|^close$)}")]public async Task<ActionResult<OrgDto>> Transition(Guid id,string transition,FiscalYearTransitionRequest q,CancellationToken ct){if(!Authorize(OrgPermissions.FiscalYearManage,out var c))return Denied<OrgDto>(c);return await s.TransitionFiscalYearAsync(id,transition,q,c,ct) is {}row?Ok(row):NotFound<OrgDto>(c);}}
[Route("api/v1/general/number-sequences")] public sealed class NumberSequencesController(IOrgService s):OrgControllerBase(s){[HttpGet]public Task<ActionResult<PagedResponse<OrgDto>>> List([FromQuery]PagedQueryRequest q,CancellationToken c)=>base.List(OrgResource.NumberSequences,OrgPermissions.NumberingView,q,c);[HttpPost]public Task<ActionResult<OrgDto>> Create(OrgWriteRequest q,CancellationToken c)=>base.Create(OrgResource.NumberSequences,OrgPermissions.NumberingManage,q,c);[HttpPost("reserve")]public async Task<ActionResult<NumberReservationDto>> Reserve(NumberReservationRequest q,CancellationToken ct){if(!Authorize(OrgPermissions.NumberingReserve,out var c))return Denied<NumberReservationDto>(c);return Ok(await s.ReserveNumberAsync(q,c,ct));}}
[Route("api/v1/general/languages")] public sealed class LanguagesController(IOrgService s):OrgControllerBase(s){[HttpGet]public Task<ActionResult<PagedResponse<OrgDto>>> List([FromQuery]PagedQueryRequest q,CancellationToken c)=>base.List(OrgResource.Languages,OrgPermissions.LanguageView,q,c);[HttpPost]public Task<ActionResult<OrgDto>> Create(OrgWriteRequest q,CancellationToken c)=>base.Create(OrgResource.Languages,OrgPermissions.LanguageManage,q,c);}
[Route("api/v1/general/operational-settings")] public sealed class OperationalSettingsController(IOrgService s):OrgControllerBase(s){[HttpGet]public Task<ActionResult<PagedResponse<OrgDto>>> List([FromQuery]PagedQueryRequest q,CancellationToken c)=>base.List(OrgResource.SettingOverrides,OrgPermissions.SettingsView,q,c);[HttpPost("overrides")]public Task<ActionResult<OrgDto>> Create(OrgWriteRequest q,CancellationToken c)=>base.Create(OrgResource.SettingOverrides,OrgPermissions.SettingsManage,q,c);[HttpPut("overrides/{id:guid}")]public Task<ActionResult<OrgDto>> Update(Guid id,OrgWriteRequest q,CancellationToken c)=>base.Update(OrgResource.SettingOverrides,OrgPermissions.SettingsManage,id,q,c);}
