#nullable enable
using System.Drawing;
using System.Windows.Forms;
namespace TransportERP.EmptyForms;
partial class UcOnyxSCREEN0103
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private FlowLayoutPanel flpActions = null!;
    private Button btnView = null!;
    private Button btnSave = null!;
    private Button btnClear = null!;
    private Button btnClose = null!;
    private TabControl tabs = null!;
    private Label lblStatus = null!;
    private TabPage tp0 = null!;
    private TableLayoutPanel layout0 = null!;
    private ComboBox field_bankRef = null!;
    private Label lbl_bankRef = null!;
    private DateTimePicker field_fromDate = null!;
    private Label lbl_fromDate = null!;
    private DateTimePicker field_toDate = null!;
    private Label lbl_toDate = null!;
    private TabPage tp1 = null!;
    private TableLayoutPanel layout1 = null!;
    private DataGridView dgvLines = null!;
    private DataGridViewTextBoxColumn col_rowNo = null!;
    private DataGridViewTextBoxColumn col_chequeNumber = null!;
    private DataGridViewTextBoxColumn col_bankName = null!;
    private DataGridViewTextBoxColumn col_dueDate = null!;
    private DataGridViewTextBoxColumn col_amount = null!;
    private DataGridViewTextBoxColumn col_currency = null!;
    private DataGridViewCheckBoxColumn col_mature = null!;
    private TableLayoutPanel linesHost = null!;
    private System.ComponentModel.IContainer? components;
    private ErrorProvider validationErrors = null!;
    protected override void Dispose(bool disposing) { if(disposing) components?.Dispose(); base.Dispose(disposing); }
    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandPrint = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        components = new System.ComponentModel.Container();
        validationErrors = new ErrorProvider(components);
        validationErrors.ContainerControl = this;
        validationErrors.BlinkStyle = ErrorBlinkStyle.NeverBlink;
        mainLayout = new TableLayoutPanel();
        lblTitle = new Label();
        flpActions = new FlowLayoutPanel();
        btnView = new Button();
        btnSave = new Button();
        btnClear = new Button();
        btnClose = new Button();
        tabs = new TabControl();
        lblStatus = new Label();
        tp0 = new TabPage();
        layout0 = new TableLayoutPanel();
        field_bankRef = new ComboBox();
        lbl_bankRef = new Label();
        field_fromDate = new DateTimePicker();
        lbl_fromDate = new Label();
        field_toDate = new DateTimePicker();
        lbl_toDate = new Label();
        tp1 = new TabPage();
        layout1 = new TableLayoutPanel();
        dgvLines = new DataGridView();
        col_rowNo = new DataGridViewTextBoxColumn();
        col_chequeNumber = new DataGridViewTextBoxColumn();
        col_bankName = new DataGridViewTextBoxColumn();
        col_dueDate = new DataGridViewTextBoxColumn();
        col_amount = new DataGridViewTextBoxColumn();
        col_currency = new DataGridViewTextBoxColumn();
        col_mature = new DataGridViewCheckBoxColumn();
        linesHost = new TableLayoutPanel();
        SuspendLayout();
        mainLayout.Name = "mainLayout";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "الشيكات المستحقة للسداد – آليًا";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Padding = new Padding(8);
        lblTitle.TabStop = false;
        mainLayout.Controls.Add(lblTitle, 0, 0);
        flpActions.Name = "flpActions";
        flpActions.AutoSize = true;
        flpActions.Dock = DockStyle.Fill;
        flpActions.WrapContents = true;
        flpActions.FlowDirection = FlowDirection.LeftToRight;
        flpActions.RightToLeft = RightToLeft.Yes;
        mainLayout.Controls.Add(designerCommandBar, 0, 1);
        btnView.Name = "btnView";
        btnView.Text = "عرض / إعادة تحميل";
        btnView.AutoSize = true;
        btnView.MinimumSize = new Size(100,32);
        btnView.TabIndex = 0;
        btnView.AccessibleName = "عرض / إعادة تحميل";

        btnView.Enabled = false;
        btnSave.Name = "btnSave";
        btnSave.Text = "حفظ";
        btnSave.AutoSize = true;
        btnSave.MinimumSize = new Size(100,32);
        btnSave.TabIndex = 1;
        btnSave.AccessibleName = "حفظ";

        btnSave.Enabled = false;
        btnClear.Name = "btnClear";
        btnClear.Text = "تفريغ المسودة";
        btnClear.AutoSize = true;
        btnClear.MinimumSize = new Size(100,32);
        btnClear.TabIndex = 2;
        btnClear.AccessibleName = "تفريغ المسودة";
        flpActions.Controls.Add(btnClear);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.AutoSize = true;
        btnClose.MinimumSize = new Size(100,32);
        btnClose.TabIndex = 3;
        btnClose.AccessibleName = "إغلاق";

        tabs.Name = "tabs";
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeftLayout = true;
        tabs.Multiline = true;
        tabs.TabIndex = 1;
        mainLayout.Controls.Add(tabs, 0, 2);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "مسودة واجهة غير محفوظة — الخدمات غير موصولة";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.Padding = new Padding(6);
        mainLayout.Controls.Add(lblStatus, 0, 3);
        tp0.Name = "tp0";
        tp0.Text = "معايير العرض";
        tp0.AutoScroll = true;
        tp0.TabIndex = 0;
        tabs.Controls.Add(tp0);
        layout0.Name = "layout0";
        layout0.Dock = DockStyle.Top;
        layout0.AutoSize = true;
        layout0.ColumnCount = 2;
        layout0.MinimumSize = new Size(650,0);
        layout0.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp0.Controls.Add(layout0);
        field_bankRef.Name = "field_bankRef";
        lbl_bankRef.Name = "lbl_bankRef";
        field_bankRef.AccessibleName = "البنك";
        field_bankRef.Tag = "LOCAL:filter";
        field_bankRef.Dock = DockStyle.Fill;
        field_bankRef.TabIndex = 0;
        lbl_bankRef.Text = "البنك";
        lbl_bankRef.AutoSize = true;
        lbl_bankRef.Dock = DockStyle.Fill;
        lbl_bankRef.TextAlign = ContentAlignment.MiddleRight;
        lbl_bankRef.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_bankRef, 0, 0);
        layout0.Controls.Add(field_bankRef, 1, 0);
        field_bankRef.DropDownStyle = ComboBoxStyle.DropDownList;
        field_bankRef.DropDownWidth = 420;
        field_fromDate.Name = "field_fromDate";
        lbl_fromDate.Name = "lbl_fromDate";
        field_fromDate.AccessibleName = "من تاريخ";
        field_fromDate.Tag = "LOCAL:filter";
        field_fromDate.Dock = DockStyle.Fill;
        field_fromDate.TabIndex = 1;
        lbl_fromDate.Text = "من تاريخ";
        lbl_fromDate.AutoSize = true;
        lbl_fromDate.Dock = DockStyle.Fill;
        lbl_fromDate.TextAlign = ContentAlignment.MiddleRight;
        lbl_fromDate.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_fromDate, 0, 1);
        layout0.Controls.Add(field_fromDate, 1, 1);
        field_fromDate.Format = DateTimePickerFormat.Custom;
        field_fromDate.CustomFormat = "yyyy-MM-dd";
        field_fromDate.ShowCheckBox = true;
        field_fromDate.Checked = false;
        field_toDate.Name = "field_toDate";
        lbl_toDate.Name = "lbl_toDate";
        field_toDate.AccessibleName = "إلى تاريخ";
        field_toDate.Tag = "LOCAL:filter";
        field_toDate.Dock = DockStyle.Fill;
        field_toDate.TabIndex = 2;
        lbl_toDate.Text = "إلى تاريخ";
        lbl_toDate.AutoSize = true;
        lbl_toDate.Dock = DockStyle.Fill;
        lbl_toDate.TextAlign = ContentAlignment.MiddleRight;
        lbl_toDate.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_toDate, 0, 2);
        layout0.Controls.Add(field_toDate, 1, 2);
        field_toDate.Format = DateTimePickerFormat.Custom;
        field_toDate.CustomFormat = "yyyy-MM-dd";
        field_toDate.ShowCheckBox = true;
        field_toDate.Checked = false;
        layout0.RowCount = 3;
        tp1.Name = "tp1";
        tp1.Text = "البيانات التفصيلية";
        tp1.AutoScroll = true;
        tp1.TabIndex = 1;
        tabs.Controls.Add(tp1);
        layout1.Name = "layout1";
        layout1.Dock = DockStyle.Top;
        layout1.AutoSize = true;
        layout1.ColumnCount = 2;
        layout1.MinimumSize = new Size(650,0);
        layout1.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp1.Controls.Add(layout1);
        layout1.RowCount = 0;
        dgvLines.Name = "dgvLines";
        dgvLines.Dock = DockStyle.Fill;
        dgvLines.MinimumSize = new Size(650,260);
        dgvLines.AutoGenerateColumns = false;
        dgvLines.AllowUserToAddRows = false;
        dgvLines.AllowUserToDeleteRows = false;
        dgvLines.AllowUserToOrderColumns = false;
        dgvLines.RowHeadersVisible = false;
        dgvLines.MultiSelect = false;
        dgvLines.SelectionMode = DataGridViewSelectionMode.CellSelect;
        dgvLines.AccessibleName = "البيانات التفصيلية";
        dgvLines.TabIndex = 1;
        col_rowNo.Name = "col_rowNo";
        col_rowNo.Name = "rowNo";
        col_rowNo.HeaderText = "#";
        col_rowNo.ReadOnly = true;
        col_rowNo.Tag = "text";
        col_rowNo.MinimumWidth = 90;
        col_rowNo.Width = 140;
        col_rowNo.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_rowNo);
        col_chequeNumber.Name = "col_chequeNumber";
        col_chequeNumber.Name = "chequeNumber";
        col_chequeNumber.HeaderText = "رقم الشيك";
        col_chequeNumber.ReadOnly = true;
        col_chequeNumber.Tag = "text";
        col_chequeNumber.MinimumWidth = 90;
        col_chequeNumber.Width = 140;
        col_chequeNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_chequeNumber);
        col_bankName.Name = "col_bankName";
        col_bankName.Name = "bankName";
        col_bankName.HeaderText = "البنك";
        col_bankName.ReadOnly = true;
        col_bankName.Tag = "text";
        col_bankName.MinimumWidth = 90;
        col_bankName.Width = 140;
        col_bankName.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_bankName);
        col_dueDate.Name = "col_dueDate";
        col_dueDate.Name = "dueDate";
        col_dueDate.HeaderText = "تاريخ الاستحقاق";
        col_dueDate.ReadOnly = true;
        col_dueDate.Tag = "text";
        col_dueDate.MinimumWidth = 90;
        col_dueDate.Width = 140;
        col_dueDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_dueDate);
        col_amount.Name = "col_amount";
        col_amount.Name = "amount";
        col_amount.HeaderText = "المبلغ";
        col_amount.ReadOnly = true;
        col_amount.Tag = "decimal";
        col_amount.MinimumWidth = 90;
        col_amount.Width = 140;
        col_amount.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_amount.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_amount);
        col_currency.Name = "col_currency";
        col_currency.Name = "currency";
        col_currency.HeaderText = "العملة";
        col_currency.ReadOnly = true;
        col_currency.Tag = "text";
        col_currency.MinimumWidth = 90;
        col_currency.Width = 140;
        col_currency.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_currency);
        col_mature.Name = "col_mature";
        col_mature.Name = "mature";
        col_mature.HeaderText = "الاستحقاق";
        col_mature.ReadOnly = false;
        col_mature.Tag = "check";
        col_mature.MinimumWidth = 90;
        col_mature.Width = 140;
        col_mature.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_mature);
        linesHost.Name = "linesHost";
        linesHost.Dock = DockStyle.Fill;
        linesHost.ColumnCount = 1;
        linesHost.RowCount = 3;
        linesHost.MinimumSize = new Size(680,380);
        linesHost.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        linesHost.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        linesHost.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        linesHost.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        tp1.Controls.Remove(layout1);
        linesHost.Controls.Add(layout1, 0, 0);
        tp1.Controls.Add(linesHost);
        linesHost.Controls.Add(dgvLines, 0, 2);
        AutoScaleDimensions = new SizeF(96F,96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Name = "UcOnyxSCREEN0103";
        Text = "الشيكات المستحقة للسداد – آليًا";
        Tag = "ONYX:SCREEN-0103";
        Size = new Size(1100,720);
        Controls.Add(mainLayout);
        ResumeLayout(false);
        PerformLayout();
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Fill;
        designerCommandBar.RightToLeft = RightToLeft.Yes;
        designerCommandBar.Controls.Add(flpActions);
        flpActions.Dock = DockStyle.Fill;
        flpActions.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        flpActions.Name = "flpActions";
        flpActions.Dock = DockStyle.Fill;
        flpActions.AutoSize = false;
        flpActions.WrapContents = false;
        flpActions.FlowDirection = FlowDirection.RightToLeft;
        flpActions.RightToLeft = RightToLeft.No;
        flpActions.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 44;
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = true;
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = true;
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandAdd.AutoSize = false;
        standardCommandAdd.Dock = DockStyle.None;
        standardCommandAdd.MinimumSize = Size.Empty;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandAdd.Text = "";
        flpActions.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.AutoSize = false;
        standardCommandEdit.Dock = DockStyle.None;
        standardCommandEdit.MinimumSize = Size.Empty;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandEdit.Text = "";
        flpActions.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        flpActions.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.AutoSize = false;
        standardCommandCancel.Dock = DockStyle.None;
        standardCommandCancel.MinimumSize = Size.Empty;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandCancel.Text = "";
        flpActions.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        btnView.AutoSize = false;
        btnView.Dock = DockStyle.None;
        btnView.MinimumSize = Size.Empty;
        btnView.Size = new Size(26, 24);
        btnView.Margin = new Padding(1);
        btnView.FlatStyle = FlatStyle.Flat;
        btnView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        btnView.Text = "";
        flpActions.Controls.Add(btnView);
        designerCommandBar.SetCommandRole(btnView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        flpActions.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        flpActions.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        flpActions.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        flpActions.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        btnSave.AutoSize = false;
        btnSave.Dock = DockStyle.None;
        btnSave.MinimumSize = Size.Empty;
        btnSave.Size = new Size(26, 24);
        btnSave.Margin = new Padding(1);
        btnSave.FlatStyle = FlatStyle.Flat;
        btnSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        btnSave.Text = "";
        flpActions.Controls.Add(btnSave);
        designerCommandBar.SetCommandRole(btnSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        flpActions.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        btnClose.AutoSize = false;
        btnClose.Dock = DockStyle.None;
        btnClose.MinimumSize = Size.Empty;
        btnClose.Size = new Size(26, 24);
        btnClose.Margin = new Padding(1);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        btnClose.Text = "";
        designerCloseHost.Controls.Add(btnClose);
        btnClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        flpActions.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        flpActions.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        flpActions.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        flpActions.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}
}
