using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcOnyxSCREEN0111
{
    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private TabControl tabs = null!;
    private TabPage tabMain = null!;
    private TableLayoutPanel documentLayout = null!;
    private TableLayoutPanel headerLayout = null!;
    private Label lblSourceDocumentNumber = null!;
    private TextBox fieldSourceDocumentNumber = null!;
    private DataGridView gridLines = null!;
    private TableLayoutPanel totalsLayout = null!;
    private Label lblTotal = null!;
    private TextBox fieldTotal = null!;
    private Label lblDifference = null!;
    private TextBox fieldDifference = null!;
    private FlowLayoutPanel flagsLayout = null!;
    private CheckBox chkPosted = null!;
    private Panel auditFooter = null!;
    private AuditMetadataControl standardAuditMetadata = null!;
    private Label lblBranch = null!;
    private ComboBox fieldBranch = null!;
    private Label lblDocumentNumber = null!;
    private TextBox fieldDocumentNumber = null!;
    private Label lblDate = null!;
    private TextBox fieldDate = null!;
    private Label lblAccountType = null!;
    private ComboBox fieldAccountType = null!;
    private Label lblAccountNumber = null!;
    private ComboBox fieldAccountNumber = null!;
    private Label lblAccountName = null!;
    private TextBox fieldAccountName = null!;
    private Label lblCurrency = null!;
    private ComboBox fieldCurrency = null!;
    private Label lblExchangeRate = null!;
    private TextBox fieldExchangeRate = null!;
    private Label lblLocalAmount = null!;
    private TextBox fieldLocalAmount = null!;
    private Label lblForeignAmount = null!;
    private TextBox fieldForeignAmount = null!;
    private Label lblDescription = null!;
    private TextBox fieldDescription = null!;
    private Label lblVoucherType = null!;
    private ComboBox fieldVoucherType = null!;
    private Label lblTargetCurrency = null!;
    private ComboBox fieldTargetCurrency = null!;
    private Label lblReference = null!;
    private TextBox fieldReference = null!;
    private Label lblCostCenter = null!;
    private ComboBox fieldCostCenter = null!;
    private Label lblAttachmentCount = null!;
    private TextBox fieldAttachmentCount = null!;
    private Label lblDownloadSource = null!;
    private ComboBox fieldDownloadSource = null!;
    private DataGridViewTextBoxColumn colSequence = null!;
    private DataGridViewTextBoxColumn colAccountNumber = null!;
    private DataGridViewTextBoxColumn colAnalyticalAccount = null!;
    private DataGridViewTextBoxColumn colAccountName = null!;
    private DataGridViewTextBoxColumn colDescription = null!;
    private DataGridViewTextBoxColumn colCurrency = null!;
    private DataGridViewTextBoxColumn colExchangeRate = null!;
    private DataGridViewTextBoxColumn colDebit = null!;
    private DataGridViewTextBoxColumn colForeignDebit = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        tabs = new TabControl();
        tabs.Name = "tabs";
        tabMain = new TabPage();
        tabMain.Name = "tabMain";
        documentLayout = new TableLayoutPanel();
        documentLayout.Name = "documentLayout";
        headerLayout = new TableLayoutPanel();
        headerLayout.Name = "headerLayout";
        lblSourceDocumentNumber = new Label();
        lblSourceDocumentNumber.Name = "lblSourceDocumentNumber";
        fieldSourceDocumentNumber = new TextBox();
        fieldSourceDocumentNumber.Name = "fieldSourceDocumentNumber";
        gridLines = new DataGridView();
        gridLines.Name = "gridLines";
        totalsLayout = new TableLayoutPanel();
        totalsLayout.Name = "totalsLayout";
        lblTotal = new Label();
        lblTotal.Name = "lblTotal";
        fieldTotal = new TextBox();
        fieldTotal.Name = "fieldTotal";
        lblDifference = new Label();
        lblDifference.Name = "lblDifference";
        fieldDifference = new TextBox();
        fieldDifference.Name = "fieldDifference";
        flagsLayout = new FlowLayoutPanel();
        flagsLayout.Name = "flagsLayout";
        chkPosted = new CheckBox();
        chkPosted.Name = "chkPosted";
        auditFooter = new Panel();
        auditFooter.Name = "auditFooter";
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        lblBranch = new Label();
        lblBranch.Name = "lblBranch";
        fieldBranch = new ComboBox();
        fieldBranch.Name = "fieldBranch";
        lblDocumentNumber = new Label();
        lblDocumentNumber.Name = "lblDocumentNumber";
        fieldDocumentNumber = new TextBox();
        fieldDocumentNumber.Name = "fieldDocumentNumber";
        lblDate = new Label();
        lblDate.Name = "lblDate";
        fieldDate = new TextBox();
        fieldDate.Name = "fieldDate";
        lblAccountType = new Label();
        lblAccountType.Name = "lblAccountType";
        fieldAccountType = new ComboBox();
        fieldAccountType.Name = "fieldAccountType";
        lblAccountNumber = new Label();
        lblAccountNumber.Name = "lblAccountNumber";
        fieldAccountNumber = new ComboBox();
        fieldAccountNumber.Name = "fieldAccountNumber";
        lblAccountName = new Label();
        lblAccountName.Name = "lblAccountName";
        fieldAccountName = new TextBox();
        fieldAccountName.Name = "fieldAccountName";
        lblCurrency = new Label();
        lblCurrency.Name = "lblCurrency";
        fieldCurrency = new ComboBox();
        fieldCurrency.Name = "fieldCurrency";
        lblExchangeRate = new Label();
        lblExchangeRate.Name = "lblExchangeRate";
        fieldExchangeRate = new TextBox();
        fieldExchangeRate.Name = "fieldExchangeRate";
        lblLocalAmount = new Label();
        lblLocalAmount.Name = "lblLocalAmount";
        fieldLocalAmount = new TextBox();
        fieldLocalAmount.Name = "fieldLocalAmount";
        lblForeignAmount = new Label();
        lblForeignAmount.Name = "lblForeignAmount";
        fieldForeignAmount = new TextBox();
        fieldForeignAmount.Name = "fieldForeignAmount";
        lblDescription = new Label();
        lblDescription.Name = "lblDescription";
        fieldDescription = new TextBox();
        fieldDescription.Name = "fieldDescription";
        lblVoucherType = new Label();
        lblVoucherType.Name = "lblVoucherType";
        fieldVoucherType = new ComboBox();
        fieldVoucherType.Name = "fieldVoucherType";
        lblTargetCurrency = new Label();
        lblTargetCurrency.Name = "lblTargetCurrency";
        fieldTargetCurrency = new ComboBox();
        fieldTargetCurrency.Name = "fieldTargetCurrency";
        lblReference = new Label();
        lblReference.Name = "lblReference";
        fieldReference = new TextBox();
        fieldReference.Name = "fieldReference";
        lblCostCenter = new Label();
        lblCostCenter.Name = "lblCostCenter";
        fieldCostCenter = new ComboBox();
        fieldCostCenter.Name = "fieldCostCenter";
        lblAttachmentCount = new Label();
        lblAttachmentCount.Name = "lblAttachmentCount";
        fieldAttachmentCount = new TextBox();
        fieldAttachmentCount.Name = "fieldAttachmentCount";
        lblDownloadSource = new Label();
        lblDownloadSource.Name = "lblDownloadSource";
        fieldDownloadSource = new ComboBox();
        fieldDownloadSource.Name = "fieldDownloadSource";
        colSequence = new DataGridViewTextBoxColumn();
        colSequence.Name = "colSequence";
        colAccountNumber = new DataGridViewTextBoxColumn();
        colAccountNumber.Name = "colAccountNumber";
        colAnalyticalAccount = new DataGridViewTextBoxColumn();
        colAnalyticalAccount.Name = "colAnalyticalAccount";
        colAccountName = new DataGridViewTextBoxColumn();
        colAccountName.Name = "colAccountName";
        colDescription = new DataGridViewTextBoxColumn();
        colDescription.Name = "colDescription";
        colCurrency = new DataGridViewTextBoxColumn();
        colCurrency.Name = "colCurrency";
        colExchangeRate = new DataGridViewTextBoxColumn();
        colExchangeRate.Name = "colExchangeRate";
        colDebit = new DataGridViewTextBoxColumn();
        colDebit.Name = "colDebit";
        colForeignDebit = new DataGridViewTextBoxColumn();
        colForeignDebit.Name = "colForeignDebit";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = Padding.Empty;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        lblTitle.Text = "صرف عملة";
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.BackColor = Color.FromArgb(23, 50, 78);
        lblTitle.ForeColor = Color.White;
        commandBar.Dock = DockStyle.Fill;
        commandBar.Margin = Padding.Empty;
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeftLayout = true;
        tabMain.Text = "البيانات الرئيسية";
        tabMain.Padding = Padding.Empty;
        tabs.Controls.Add(tabMain);
        documentLayout.Dock = DockStyle.Fill;
        documentLayout.ColumnCount = 1;
        documentLayout.RowCount = 3;
        documentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 236F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        tabMain.Controls.Add(documentLayout);
        headerLayout.Dock = DockStyle.Fill;
        headerLayout.Padding = new Padding(8, 6, 8, 6);
        headerLayout.Margin = Padding.Empty;
        headerLayout.ColumnCount = 6;
        headerLayout.RowCount = 7;
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 118F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 118F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 118F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        lblBranch.Text = "رقم الفرع";
        lblBranch.Dock = DockStyle.Fill;
        lblBranch.TextAlign = ContentAlignment.MiddleLeft;
        fieldBranch.AccessibleName = "رقم الفرع";
        fieldBranch.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblBranch, 0, 0);
        headerLayout.Controls.Add(fieldBranch, 1, 0);
        fieldBranch.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldBranch.Enabled = false;
        lblDocumentNumber.Text = "رقم السند";
        lblDocumentNumber.Dock = DockStyle.Fill;
        lblDocumentNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldDocumentNumber.AccessibleName = "رقم السند";
        fieldDocumentNumber.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDocumentNumber, 2, 0);
        headerLayout.Controls.Add(fieldDocumentNumber, 3, 0);
        fieldDocumentNumber.ReadOnly = true;
        lblDate.Text = "التاريخ";
        lblDate.Dock = DockStyle.Fill;
        lblDate.TextAlign = ContentAlignment.MiddleLeft;
        fieldDate.AccessibleName = "التاريخ";
        fieldDate.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDate, 4, 0);
        headerLayout.Controls.Add(fieldDate, 5, 0);
        fieldDate.ReadOnly = true;
        lblAccountType.Text = "الحساب التحليلي";
        lblAccountType.Dock = DockStyle.Fill;
        lblAccountType.TextAlign = ContentAlignment.MiddleLeft;
        fieldAccountType.AccessibleName = "الحساب التحليلي";
        fieldAccountType.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblAccountType, 0, 1);
        headerLayout.Controls.Add(fieldAccountType, 1, 1);
        fieldAccountType.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldAccountType.Enabled = false;
        lblAccountNumber.Text = "رقم الحساب التحليلي";
        lblAccountNumber.Dock = DockStyle.Fill;
        lblAccountNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldAccountNumber.AccessibleName = "رقم الحساب التحليلي";
        fieldAccountNumber.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblAccountNumber, 2, 1);
        headerLayout.Controls.Add(fieldAccountNumber, 3, 1);
        fieldAccountNumber.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldAccountNumber.Enabled = false;
        lblAccountName.Text = "اسم الحساب التحليلي";
        lblAccountName.Dock = DockStyle.Fill;
        lblAccountName.TextAlign = ContentAlignment.MiddleLeft;
        fieldAccountName.AccessibleName = "اسم الحساب التحليلي";
        fieldAccountName.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblAccountName, 4, 1);
        headerLayout.Controls.Add(fieldAccountName, 5, 1);
        fieldAccountName.ReadOnly = true;
        lblCurrency.Text = "العملة";
        lblCurrency.Dock = DockStyle.Fill;
        lblCurrency.TextAlign = ContentAlignment.MiddleLeft;
        fieldCurrency.AccessibleName = "العملة";
        fieldCurrency.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblCurrency, 0, 2);
        headerLayout.Controls.Add(fieldCurrency, 1, 2);
        fieldCurrency.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldCurrency.Enabled = false;
        lblExchangeRate.Text = "سعر التحويل";
        lblExchangeRate.Dock = DockStyle.Fill;
        lblExchangeRate.TextAlign = ContentAlignment.MiddleLeft;
        fieldExchangeRate.AccessibleName = "سعر التحويل";
        fieldExchangeRate.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblExchangeRate, 2, 2);
        headerLayout.Controls.Add(fieldExchangeRate, 3, 2);
        fieldExchangeRate.ReadOnly = true;
        lblLocalAmount.Text = "المبلغ المحلي";
        lblLocalAmount.Dock = DockStyle.Fill;
        lblLocalAmount.TextAlign = ContentAlignment.MiddleLeft;
        fieldLocalAmount.AccessibleName = "المبلغ المحلي";
        fieldLocalAmount.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblLocalAmount, 4, 2);
        headerLayout.Controls.Add(fieldLocalAmount, 5, 2);
        fieldLocalAmount.ReadOnly = true;
        lblForeignAmount.Text = "المبلغ الأجنبي";
        lblForeignAmount.Dock = DockStyle.Fill;
        lblForeignAmount.TextAlign = ContentAlignment.MiddleLeft;
        fieldForeignAmount.AccessibleName = "المبلغ الأجنبي";
        fieldForeignAmount.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblForeignAmount, 0, 3);
        headerLayout.Controls.Add(fieldForeignAmount, 1, 3);
        fieldForeignAmount.ReadOnly = true;
        lblDescription.Text = "بيان الصندوق / البنك";
        lblDescription.Dock = DockStyle.Fill;
        lblDescription.TextAlign = ContentAlignment.MiddleLeft;
        fieldDescription.AccessibleName = "بيان الصندوق / البنك";
        fieldDescription.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDescription, 2, 3);
        headerLayout.Controls.Add(fieldDescription, 3, 3);
        fieldDescription.ReadOnly = true;
        lblVoucherType.Text = "نوع السند";
        lblVoucherType.Dock = DockStyle.Fill;
        lblVoucherType.TextAlign = ContentAlignment.MiddleLeft;
        fieldVoucherType.AccessibleName = "نوع السند";
        fieldVoucherType.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblVoucherType, 4, 3);
        headerLayout.Controls.Add(fieldVoucherType, 5, 3);
        fieldVoucherType.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldVoucherType.Enabled = false;
        lblTargetCurrency.Text = "العملة المصروف إليها";
        lblTargetCurrency.Dock = DockStyle.Fill;
        lblTargetCurrency.TextAlign = ContentAlignment.MiddleLeft;
        fieldTargetCurrency.AccessibleName = "العملة المصروف إليها";
        fieldTargetCurrency.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblTargetCurrency, 0, 4);
        headerLayout.Controls.Add(fieldTargetCurrency, 1, 4);
        fieldTargetCurrency.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldTargetCurrency.Enabled = false;
        lblReference.Text = "رقم المرجع";
        lblReference.Dock = DockStyle.Fill;
        lblReference.TextAlign = ContentAlignment.MiddleLeft;
        fieldReference.AccessibleName = "رقم المرجع";
        fieldReference.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblReference, 2, 4);
        headerLayout.Controls.Add(fieldReference, 3, 4);
        fieldReference.ReadOnly = true;
        lblCostCenter.Text = "رقم المركز";
        lblCostCenter.Dock = DockStyle.Fill;
        lblCostCenter.TextAlign = ContentAlignment.MiddleLeft;
        fieldCostCenter.AccessibleName = "رقم المركز";
        fieldCostCenter.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblCostCenter, 4, 4);
        headerLayout.Controls.Add(fieldCostCenter, 5, 4);
        fieldCostCenter.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldCostCenter.Enabled = false;
        lblAttachmentCount.Text = "عدد المرفقات";
        lblAttachmentCount.Dock = DockStyle.Fill;
        lblAttachmentCount.TextAlign = ContentAlignment.MiddleLeft;
        fieldAttachmentCount.AccessibleName = "عدد المرفقات";
        fieldAttachmentCount.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblAttachmentCount, 0, 5);
        headerLayout.Controls.Add(fieldAttachmentCount, 1, 5);
        fieldAttachmentCount.ReadOnly = true;
        lblDownloadSource.Text = "إنزال البيانات من";
        lblDownloadSource.Dock = DockStyle.Fill;
        lblDownloadSource.TextAlign = ContentAlignment.MiddleLeft;
        fieldDownloadSource.AccessibleName = "إنزال البيانات من";
        fieldDownloadSource.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDownloadSource, 2, 5);
        headerLayout.Controls.Add(fieldDownloadSource, 3, 5);
        fieldDownloadSource.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldDownloadSource.Enabled = false;
        flagsLayout.Dock = DockStyle.Fill;
        flagsLayout.FlowDirection = FlowDirection.RightToLeft;
        flagsLayout.WrapContents = false;
        flagsLayout.Margin = Padding.Empty;
        headerLayout.Controls.Add(flagsLayout, 0, 6);
        headerLayout.SetColumnSpan(flagsLayout, 6);
        chkPosted.Text = "مرحل";
        chkPosted.AccessibleName = "مرحل";
        chkPosted.AutoSize = true;
        chkPosted.Enabled = false;
        flagsLayout.Controls.Add(chkPosted);
        lblSourceDocumentNumber.Text = "رقم الوثيقة";
        lblSourceDocumentNumber.Dock = DockStyle.Fill;
        lblSourceDocumentNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldSourceDocumentNumber.AccessibleName = "رقم الوثيقة المصدر";
        fieldSourceDocumentNumber.Dock = DockStyle.Fill;
        fieldSourceDocumentNumber.ReadOnly = true;
        headerLayout.Controls.Add(lblSourceDocumentNumber, 4, 5);
        headerLayout.Controls.Add(fieldSourceDocumentNumber, 5, 5);
        fieldAccountType.Items.AddRange(new object[] { "صندوق", "بنك", "عميل", "مورد" });
        gridLines.Dock = DockStyle.Fill;
        gridLines.AccessibleName = "تفاصيل طلب صرف العملة";
        gridLines.ReadOnly = true;
        gridLines.AllowUserToAddRows = false;
        gridLines.AllowUserToDeleteRows = false;
        gridLines.AutoGenerateColumns = false;
        gridLines.RowHeadersVisible = false;
        gridLines.BackgroundColor = Color.White;
        gridLines.ColumnHeadersHeight = 34;
        gridLines.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridLines.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        colSequence.HeaderText = "م";
        colSequence.Width = 45;
        colSequence.ReadOnly = true;
        colSequence.SortMode = DataGridViewColumnSortMode.NotSortable;
        colAccountNumber.HeaderText = "رقم الحساب";
        colAccountNumber.Width = 125;
        colAccountNumber.ReadOnly = true;
        colAccountNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colAnalyticalAccount.HeaderText = "الحساب التحليلي";
        colAnalyticalAccount.Width = 125;
        colAnalyticalAccount.ReadOnly = true;
        colAnalyticalAccount.SortMode = DataGridViewColumnSortMode.NotSortable;
        colAccountName.HeaderText = "الاسم";
        colAccountName.Width = 190;
        colAccountName.ReadOnly = true;
        colAccountName.SortMode = DataGridViewColumnSortMode.NotSortable;
        colDescription.HeaderText = "البيان";
        colDescription.Width = 220;
        colDescription.ReadOnly = true;
        colDescription.SortMode = DataGridViewColumnSortMode.NotSortable;
        colCurrency.HeaderText = "العملة";
        colCurrency.Width = 80;
        colCurrency.ReadOnly = true;
        colCurrency.SortMode = DataGridViewColumnSortMode.NotSortable;
        colExchangeRate.HeaderText = "سعر التحويل";
        colExchangeRate.Width = 105;
        colExchangeRate.ReadOnly = true;
        colExchangeRate.SortMode = DataGridViewColumnSortMode.NotSortable;
        colDebit.HeaderText = "مدين";
        colDebit.Width = 115;
        colDebit.ReadOnly = true;
        colDebit.SortMode = DataGridViewColumnSortMode.NotSortable;
        colForeignDebit.HeaderText = "مدين أجنبي";
        colForeignDebit.Width = 115;
        colForeignDebit.ReadOnly = true;
        colForeignDebit.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridLines.Columns.AddRange(new DataGridViewColumn[] { colSequence, colAccountNumber, colAnalyticalAccount, colAccountName, colDescription, colCurrency, colExchangeRate, colDebit, colForeignDebit });
        totalsLayout.Dock = DockStyle.Fill;
        totalsLayout.ColumnCount = 4;
        totalsLayout.RowCount = 1;
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 95F));
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 95F));
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        totalsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        lblTotal.Text = "المجموع";
        lblTotal.Dock = DockStyle.Fill;
        lblTotal.TextAlign = ContentAlignment.MiddleLeft;
        fieldTotal.Dock = DockStyle.Fill;
        fieldTotal.ReadOnly = true;
        lblDifference.Text = "الفارق";
        lblDifference.Dock = DockStyle.Fill;
        lblDifference.TextAlign = ContentAlignment.MiddleLeft;
        fieldDifference.Dock = DockStyle.Fill;
        fieldDifference.ReadOnly = true;
        totalsLayout.Controls.Add(lblTotal, 0, 0);
        totalsLayout.Controls.Add(fieldTotal, 1, 0);
        totalsLayout.Controls.Add(lblDifference, 2, 0);
        totalsLayout.Controls.Add(fieldDifference, 3, 0);
        documentLayout.Controls.Add(headerLayout, 0, 0);
        documentLayout.Controls.Add(gridLines, 0, 1);
        documentLayout.Controls.Add(totalsLayout, 0, 2);
        auditFooter.Dock = DockStyle.Fill;
        auditFooter.Margin = Padding.Empty;
        standardAuditMetadata.Dock = DockStyle.Fill;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.Profile = AuditMetadataProfile.Standard;
        auditFooter.Controls.Add(standardAuditMetadata);
        mainLayout.Controls.Add(lblTitle, 0, 0);
        mainLayout.Controls.Add(commandBar, 0, 1);
        mainLayout.Controls.Add(tabs, 0, 2);
        mainLayout.Controls.Add(auditFooter, 0, 3);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 9F);
        RightToLeft = RightToLeft.Yes;
        Name = "UcOnyxSCREEN0111";
        Text = "صرف عملة";
        Tag = "ONYX:SCREEN-0111";
        Size = new Size(1180, 720);
        MinimumSize = new Size(1000, 600);
        Controls.Add(mainLayout);
        ResumeLayout(false);
    }
}
