#nullable enable
using System.Drawing;
using System.Windows.Forms;
namespace TransportERP.EmptyForms;
partial class UcOnyxSCREEN0098
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandView = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private FlowLayoutPanel flpActions = null!;
    private Button btnSave = null!;
    private Button btnApprove = null!;
    private Button btnClear = null!;
    private Button btnClose = null!;
    private TabControl tabs = null!;
    private Label lblStatus = null!;
    private TabPage tp0 = null!;
    private TableLayoutPanel layout0 = null!;
    private ComboBox field_ReceiptRequest_T04_EV_0111 = null!;
    private Label lbl_ReceiptRequest_T04_EV_0111 = null!;
    private ComboBox field_ReceiptRequest_T04_EV_0112 = null!;
    private Label lbl_ReceiptRequest_T04_EV_0112 = null!;
    private ComboBox field_ReceiptRequest_T04_EV_0115 = null!;
    private Label lbl_ReceiptRequest_T04_EV_0115 = null!;
    private TextBox field_ReceiptRequest_T04_EV_0116 = null!;
    private Label lbl_ReceiptRequest_T04_EV_0116 = null!;
    private ComboBox field_ReceiptRequest_T04_EV_0117 = null!;
    private Label lbl_ReceiptRequest_T04_EV_0117 = null!;
    private TextBox field_ReceiptRequest_T04_EV_0118 = null!;
    private Label lbl_ReceiptRequest_T04_EV_0118 = null!;
    private DateTimePicker field_ReceiptRequest_T04_EV_0119 = null!;
    private Label lbl_ReceiptRequest_T04_EV_0119 = null!;
    private TextBox field_ReceiptRequest_T04_EV_0122 = null!;
    private Label lbl_ReceiptRequest_T04_EV_0122 = null!;
    private TextBox field_ReceiptRequest_T04_EV_0123 = null!;
    private Label lbl_ReceiptRequest_T04_EV_0123 = null!;
    private TextBox field_ReceiptRequest_T04_EV_0439 = null!;
    private Label lbl_ReceiptRequest_T04_EV_0439 = null!;
    private TextBox field_ReceiptRequest_T04_EV_0440 = null!;
    private Label lbl_ReceiptRequest_T04_EV_0440 = null!;
    private ComboBox field_ReceiptRequest_T04_EV_0441 = null!;
    private Label lbl_ReceiptRequest_T04_EV_0441 = null!;
    private ComboBox field_ReceiptRequest_T04_EV_0442 = null!;
    private Label lbl_ReceiptRequest_T04_EV_0442 = null!;
    private ComboBox field_ReceiptRequest_T04_EV_0443 = null!;
    private Label lbl_ReceiptRequest_T04_EV_0443 = null!;
    private ComboBox field_ReceiptRequest_R05_AT_0272 = null!;
    private Label lbl_ReceiptRequest_R05_AT_0272 = null!;
    private TextBox field_ReceiptRequest_R05_AT_0273 = null!;
    private Label lbl_ReceiptRequest_R05_AT_0273 = null!;
    private ComboBox field_ReceiptRequest_R05_AT_0274 = null!;
    private Label lbl_ReceiptRequest_R05_AT_0274 = null!;
    private TextBox field_ReceiptRequest_R05_AT_0275 = null!;
    private Label lbl_ReceiptRequest_R05_AT_0275 = null!;
    private TextBox field_ReceiptRequest_T04_EV_0124 = null!;
    private Label lbl_ReceiptRequest_T04_EV_0124 = null!;
    private TextBox field_ReceiptRequest_T04_EV_0125 = null!;
    private Label lbl_ReceiptRequest_T04_EV_0125 = null!;
    private TabPage tp1 = null!;
    private TableLayoutPanel layout1 = null!;
    private DataGridView dgvLines = null!;
    private DataGridViewTextBoxColumn col_rowNo = null!;
    private DataGridViewComboBoxColumn col_ReceiptRequest_T04_EV_0129 = null!;
    private DataGridViewComboBoxColumn col_ReceiptRequest_T04_EV_0447 = null!;
    private DataGridViewTextBoxColumn col_ReceiptRequest_T04_EV_0448 = null!;
    private DataGridViewTextBoxColumn col_ReceiptRequest_T04_EV_0449 = null!;
    private DataGridViewTextBoxColumn col_ReceiptRequest_T04_EV_0450 = null!;
    private DataGridViewComboBoxColumn col_ReceiptRequest_R05_AT_0276 = null!;
    private DataGridViewTextBoxColumn col_ReceiptRequest_R05_AT_0277 = null!;
    private TableLayoutPanel linesHost = null!;
    private FlowLayoutPanel lineActions = null!;
    private Button btnAddRow = null!;
    private Button btnRemoveRow = null!;
    private TabPage tp2 = null!;
    private TableLayoutPanel layout2 = null!;
    private RichTextBox context2 = null!;
    private TabPage tp3 = null!;
    private TableLayoutPanel layout3 = null!;
    private TextBox field_localNotes = null!;
    private Label lbl_localNotes = null!;
    private TabPage tp4 = null!;
    private TableLayoutPanel layout4 = null!;
    private RichTextBox context4 = null!;
    private TabPage tp5 = null!;
    private TableLayoutPanel layout5 = null!;
    private TextBox txtCsvPath = null!;
    private FlowLayoutPanel csvActions = null!;
    private Button btnChooseCsv = null!;
    private Button btnImportCsv = null!;
    private TextBox txtCsvSchema = null!;
    private DataGridView dgvImport = null!;
    private System.ComponentModel.IContainer? components;
    private ErrorProvider validationErrors = null!;
    protected override void Dispose(bool disposing) { if(disposing) components?.Dispose(); base.Dispose(disposing); }
    private TableLayoutPanel referenceHeader = null!;
    private Label lblReferencePaymentMode = null!;
    private FlowLayoutPanel referencePaymentModeLayout = null!;
    private RadioButton radioReferenceCash = null!;
    private RadioButton radioReferenceBank = null!;
    private Label lblReferenceOperationType = null!;
    private ComboBox cboReferenceOperationType = null!;
    private Label lblReferenceRecipient = null!;
    private TextBox txtReferenceRecipient = null!;
    private Label lblReferenceRequestState = null!;
    private TableLayoutPanel referenceRequestStateLayout = null!;
    private ComboBox cboReferenceRequestState = null!;
    private CheckBox chkReferenceRequestStopped = null!;
    private TabPage referenceExtra = null!;
    private Label referenceAudit = null!;
    private Label referenceTotals = null!;
    private Label referenceLabel11 = null!;
    private TextBox referenceField11 = null!;
    private Label referenceLabel12 = null!;
    private TextBox referenceField12 = null!;
    private Label referenceLabel14 = null!;
    private TextBox referenceField14 = null!;
    private Label referenceLabel15 = null!;
    private TextBox referenceField15 = null!;
    private DataGridViewTextBoxColumn referenceCol2 = null!;
    private Button referencePrint = null!;
    private TabPage documentAdditional = null!;
    private TabControl documentAdditionalSections = null!;
    private TabPage documentDefaults = null!;
    private TableLayoutPanel documentDefaultsLayout = null!;
    private Label lblDefaultCurrency = null!;
    private ComboBox cboDefaultCurrency = null!;
    private Label lblDefaultCostCenter = null!;
    private ComboBox cboDefaultCostCenter = null!;
    private TabPage documentAccounts = null!;
    private DataGridView documentAccountsGrid = null!;
    private DataGridViewTextBoxColumn documentAccountsGridColumn0 = null!;
    private DataGridViewTextBoxColumn documentAccountsGridColumn1 = null!;
    private DataGridViewTextBoxColumn documentAccountsGridColumn2 = null!;
    private DataGridViewTextBoxColumn documentAccountsGridColumn3 = null!;
    private DataGridViewTextBoxColumn documentAccountsGridColumn4 = null!;
    private DataGridViewTextBoxColumn documentAccountsGridColumn5 = null!;
    private DataGridViewTextBoxColumn documentAccountsGridColumn6 = null!;
    private DataGridViewTextBoxColumn documentAccountsGridColumn7 = null!;
    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandView = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        documentAdditional = new TabPage();
        documentAdditionalSections = new TabControl();
        documentDefaults = new TabPage();
        documentDefaultsLayout = new TableLayoutPanel();
        lblDefaultCurrency = new Label();
        cboDefaultCurrency = new ComboBox();
        lblDefaultCostCenter = new Label();
        cboDefaultCostCenter = new ComboBox();
        documentAccounts = new TabPage();
        documentAccountsGrid = new DataGridView();
        documentAccountsGridColumn0 = new DataGridViewTextBoxColumn();
        documentAccountsGridColumn1 = new DataGridViewTextBoxColumn();
        documentAccountsGridColumn2 = new DataGridViewTextBoxColumn();
        documentAccountsGridColumn3 = new DataGridViewTextBoxColumn();
        documentAccountsGridColumn4 = new DataGridViewTextBoxColumn();
        documentAccountsGridColumn5 = new DataGridViewTextBoxColumn();
        documentAccountsGridColumn6 = new DataGridViewTextBoxColumn();
        documentAccountsGridColumn7 = new DataGridViewTextBoxColumn();
        referenceHeader = new TableLayoutPanel();
        lblReferencePaymentMode = new Label();
        referencePaymentModeLayout = new FlowLayoutPanel();
        radioReferenceCash = new RadioButton();
        radioReferenceBank = new RadioButton();
        lblReferenceOperationType = new Label();
        cboReferenceOperationType = new ComboBox();
        lblReferenceRecipient = new Label();
        txtReferenceRecipient = new TextBox();
        lblReferenceRequestState = new Label();
        referenceRequestStateLayout = new TableLayoutPanel();
        cboReferenceRequestState = new ComboBox();
        chkReferenceRequestStopped = new CheckBox();
        referenceExtra = new TabPage();
        referenceAudit = new Label();
        referenceTotals = new Label();
        referenceLabel11 = new Label();
        referenceField11 = new TextBox();
        referenceLabel12 = new Label();
        referenceField12 = new TextBox();
        referenceLabel14 = new Label();
        referenceField14 = new TextBox();
        referenceLabel15 = new Label();
        referenceField15 = new TextBox();
        referenceCol2 = new DataGridViewTextBoxColumn();
        referencePrint = new Button();
        components = new System.ComponentModel.Container();
        validationErrors = new ErrorProvider(components);
        validationErrors.ContainerControl = this;
        validationErrors.BlinkStyle = ErrorBlinkStyle.NeverBlink;
        mainLayout = new TableLayoutPanel();
        lblTitle = new Label();
        flpActions = new FlowLayoutPanel();
        btnSave = new Button();
        btnApprove = new Button();
        btnClear = new Button();
        btnClose = new Button();
        tabs = new TabControl();
        lblStatus = new Label();
        tp0 = new TabPage();
        layout0 = new TableLayoutPanel();
        field_ReceiptRequest_T04_EV_0111 = new ComboBox();
        lbl_ReceiptRequest_T04_EV_0111 = new Label();
        field_ReceiptRequest_T04_EV_0112 = new ComboBox();
        lbl_ReceiptRequest_T04_EV_0112 = new Label();
        field_ReceiptRequest_T04_EV_0115 = new ComboBox();
        lbl_ReceiptRequest_T04_EV_0115 = new Label();
        field_ReceiptRequest_T04_EV_0116 = new TextBox();
        lbl_ReceiptRequest_T04_EV_0116 = new Label();
        field_ReceiptRequest_T04_EV_0117 = new ComboBox();
        lbl_ReceiptRequest_T04_EV_0117 = new Label();
        field_ReceiptRequest_T04_EV_0118 = new TextBox();
        lbl_ReceiptRequest_T04_EV_0118 = new Label();
        field_ReceiptRequest_T04_EV_0119 = new DateTimePicker();
        lbl_ReceiptRequest_T04_EV_0119 = new Label();
        field_ReceiptRequest_T04_EV_0122 = new TextBox();
        lbl_ReceiptRequest_T04_EV_0122 = new Label();
        field_ReceiptRequest_T04_EV_0123 = new TextBox();
        lbl_ReceiptRequest_T04_EV_0123 = new Label();
        field_ReceiptRequest_T04_EV_0439 = new TextBox();
        lbl_ReceiptRequest_T04_EV_0439 = new Label();
        field_ReceiptRequest_T04_EV_0440 = new TextBox();
        lbl_ReceiptRequest_T04_EV_0440 = new Label();
        field_ReceiptRequest_T04_EV_0441 = new ComboBox();
        lbl_ReceiptRequest_T04_EV_0441 = new Label();
        field_ReceiptRequest_T04_EV_0442 = new ComboBox();
        lbl_ReceiptRequest_T04_EV_0442 = new Label();
        field_ReceiptRequest_T04_EV_0443 = new ComboBox();
        lbl_ReceiptRequest_T04_EV_0443 = new Label();
        field_ReceiptRequest_R05_AT_0272 = new ComboBox();
        lbl_ReceiptRequest_R05_AT_0272 = new Label();
        field_ReceiptRequest_R05_AT_0273 = new TextBox();
        lbl_ReceiptRequest_R05_AT_0273 = new Label();
        field_ReceiptRequest_R05_AT_0274 = new ComboBox();
        lbl_ReceiptRequest_R05_AT_0274 = new Label();
        field_ReceiptRequest_R05_AT_0275 = new TextBox();
        lbl_ReceiptRequest_R05_AT_0275 = new Label();
        field_ReceiptRequest_T04_EV_0124 = new TextBox();
        lbl_ReceiptRequest_T04_EV_0124 = new Label();
        field_ReceiptRequest_T04_EV_0125 = new TextBox();
        lbl_ReceiptRequest_T04_EV_0125 = new Label();
        tp1 = new TabPage();
        layout1 = new TableLayoutPanel();
        dgvLines = new DataGridView();
        col_rowNo = new DataGridViewTextBoxColumn();
        col_ReceiptRequest_T04_EV_0129 = new DataGridViewComboBoxColumn();
        col_ReceiptRequest_T04_EV_0447 = new DataGridViewComboBoxColumn();
        col_ReceiptRequest_T04_EV_0448 = new DataGridViewTextBoxColumn();
        col_ReceiptRequest_T04_EV_0449 = new DataGridViewTextBoxColumn();
        col_ReceiptRequest_T04_EV_0450 = new DataGridViewTextBoxColumn();
        col_ReceiptRequest_R05_AT_0276 = new DataGridViewComboBoxColumn();
        col_ReceiptRequest_R05_AT_0277 = new DataGridViewTextBoxColumn();
        linesHost = new TableLayoutPanel();
        lineActions = new FlowLayoutPanel();
        btnAddRow = new Button();
        btnRemoveRow = new Button();
        tp2 = new TabPage();
        layout2 = new TableLayoutPanel();
        context2 = new RichTextBox();
        tp3 = new TabPage();
        layout3 = new TableLayoutPanel();
        field_localNotes = new TextBox();
        lbl_localNotes = new Label();
        tp4 = new TabPage();
        layout4 = new TableLayoutPanel();
        context4 = new RichTextBox();
        tp5 = new TabPage();
        layout5 = new TableLayoutPanel();
        txtCsvPath = new TextBox();
        csvActions = new FlowLayoutPanel();
        btnChooseCsv = new Button();
        btnImportCsv = new Button();
        txtCsvSchema = new TextBox();
        dgvImport = new DataGridView();
        SuspendLayout();
        mainLayout.Name = "mainLayout";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "طلبات سندات القبض";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Padding = new Padding(8);
        lblTitle.TabStop = false;
        mainLayout.Controls.Add(lblTitle, 0, 0);
        flpActions.Name = "flpActions";
        flpActions.AutoSize = true;
        flpActions.Dock = DockStyle.Fill;
        flpActions.WrapContents = true;
        flpActions.FlowDirection = FlowDirection.LeftToRight;
        flpActions.RightToLeft = RightToLeft.Yes;
        mainLayout.Controls.Add(designerCommandBar, 0, 1);
        btnSave.Name = "btnSave";
        btnSave.Text = "حفظ";
        btnSave.AutoSize = true;
        btnSave.MinimumSize = new Size(100,32);
        btnSave.TabIndex = 0;
        btnSave.AccessibleName = "حفظ";

        btnSave.Enabled = false;
        btnApprove.Name = "btnApprove";
        btnApprove.Text = "اعتماد";
        btnApprove.AutoSize = true;
        btnApprove.MinimumSize = new Size(100,32);
        btnApprove.TabIndex = 1;
        btnApprove.AccessibleName = "اعتماد";
        flpActions.Controls.Add(btnApprove);
        btnApprove.Enabled = false;
        btnClear.Name = "btnClear";
        btnClear.Text = "تفريغ المسودة";
        btnClear.AutoSize = true;
        btnClear.MinimumSize = new Size(100,32);
        btnClear.TabIndex = 2;
        btnClear.AccessibleName = "تفريغ المسودة";
        flpActions.Controls.Add(btnClear);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.AutoSize = true;
        btnClose.MinimumSize = new Size(100,32);
        btnClose.TabIndex = 3;
        btnClose.AccessibleName = "إغلاق";

        tabs.Name = "tabs";
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeftLayout = true;
        tabs.Multiline = true;
        tabs.TabIndex = 1;
        mainLayout.Controls.Add(tabs, 0, 2);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "مسودة واجهة غير محفوظة — الخدمات غير موصولة";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.Padding = new Padding(6);
        mainLayout.Controls.Add(lblStatus, 0, 3);
        tp0.Name = "tp0";
        tp0.Text = "البيانات الرئيسية";
        tp0.AutoScroll = true;
        tp0.TabIndex = 0;
        tabs.Controls.Add(tp0);
        layout0.Name = "layout0";
        layout0.Dock = DockStyle.Top;
        layout0.AutoSize = true;
        layout0.ColumnCount = 2;
        layout0.MinimumSize = new Size(650,0);
        layout0.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp0.Controls.Add(layout0);
        field_ReceiptRequest_T04_EV_0111.Name = "field_ReceiptRequest_T04_EV_0111";
        lbl_ReceiptRequest_T04_EV_0111.Name = "lbl_ReceiptRequest_T04_EV_0111";
        field_ReceiptRequest_T04_EV_0111.AccessibleName = "رقم الفرع";
        field_ReceiptRequest_T04_EV_0111.Tag = "T04-EV-0111";
        field_ReceiptRequest_T04_EV_0111.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0111.TabIndex = 0;
        lbl_ReceiptRequest_T04_EV_0111.Text = "رقم الفرع";
        lbl_ReceiptRequest_T04_EV_0111.AutoSize = true;
        lbl_ReceiptRequest_T04_EV_0111.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0111.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0111.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_ReceiptRequest_T04_EV_0111.DropDownStyle = ComboBoxStyle.DropDownList;
        field_ReceiptRequest_T04_EV_0111.DropDownWidth = 420;
        field_ReceiptRequest_T04_EV_0112.Name = "field_ReceiptRequest_T04_EV_0112";
        lbl_ReceiptRequest_T04_EV_0112.Name = "lbl_ReceiptRequest_T04_EV_0112";
        field_ReceiptRequest_T04_EV_0112.AccessibleName = "نوع القبض";
        field_ReceiptRequest_T04_EV_0112.Tag = "T04-EV-0112";
        field_ReceiptRequest_T04_EV_0112.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0112.TabIndex = 1;
        lbl_ReceiptRequest_T04_EV_0112.Text = "نوع القبض";
        lbl_ReceiptRequest_T04_EV_0112.AutoSize = true;
        lbl_ReceiptRequest_T04_EV_0112.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0112.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0112.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_ReceiptRequest_T04_EV_0112.DropDownStyle = ComboBoxStyle.DropDownList;
        field_ReceiptRequest_T04_EV_0112.DropDownWidth = 420;
        field_ReceiptRequest_T04_EV_0115.Name = "field_ReceiptRequest_T04_EV_0115";
        lbl_ReceiptRequest_T04_EV_0115.Name = "lbl_ReceiptRequest_T04_EV_0115";
        field_ReceiptRequest_T04_EV_0115.AccessibleName = "العملة";
        field_ReceiptRequest_T04_EV_0115.Tag = "T04-EV-0115";
        field_ReceiptRequest_T04_EV_0115.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0115.TabIndex = 2;
        lbl_ReceiptRequest_T04_EV_0115.Text = "العملة";
        lbl_ReceiptRequest_T04_EV_0115.AutoSize = true;
        lbl_ReceiptRequest_T04_EV_0115.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0115.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0115.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_ReceiptRequest_T04_EV_0115.DropDownStyle = ComboBoxStyle.DropDownList;
        field_ReceiptRequest_T04_EV_0115.DropDownWidth = 420;
        field_ReceiptRequest_T04_EV_0116.Name = "field_ReceiptRequest_T04_EV_0116";
        lbl_ReceiptRequest_T04_EV_0116.Name = "lbl_ReceiptRequest_T04_EV_0116";
        field_ReceiptRequest_T04_EV_0116.AccessibleName = "سعر التحويل";
        field_ReceiptRequest_T04_EV_0116.Tag = "T04-EV-0116";
        field_ReceiptRequest_T04_EV_0116.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0116.TabIndex = 3;
        lbl_ReceiptRequest_T04_EV_0116.Text = "سعر التحويل";
        lbl_ReceiptRequest_T04_EV_0116.AutoSize = true;
        lbl_ReceiptRequest_T04_EV_0116.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0116.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0116.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_ReceiptRequest_T04_EV_0116.RightToLeft = RightToLeft.No;
        field_ReceiptRequest_T04_EV_0116.TextAlign = HorizontalAlignment.Right;
        field_ReceiptRequest_T04_EV_0117.Name = "field_ReceiptRequest_T04_EV_0117";
        lbl_ReceiptRequest_T04_EV_0117.Name = "lbl_ReceiptRequest_T04_EV_0117";
        field_ReceiptRequest_T04_EV_0117.AccessibleName = "نوع المستند";
        field_ReceiptRequest_T04_EV_0117.Tag = "T04-EV-0117";
        field_ReceiptRequest_T04_EV_0117.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0117.TabIndex = 4;
        lbl_ReceiptRequest_T04_EV_0117.Text = "نوع المستند";
        lbl_ReceiptRequest_T04_EV_0117.AutoSize = true;
        lbl_ReceiptRequest_T04_EV_0117.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0117.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0117.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_ReceiptRequest_T04_EV_0117.DropDownStyle = ComboBoxStyle.DropDownList;
        field_ReceiptRequest_T04_EV_0117.DropDownWidth = 420;
        field_ReceiptRequest_T04_EV_0118.Name = "field_ReceiptRequest_T04_EV_0118";
        lbl_ReceiptRequest_T04_EV_0118.Name = "lbl_ReceiptRequest_T04_EV_0118";
        field_ReceiptRequest_T04_EV_0118.AccessibleName = "رقم السند";
        field_ReceiptRequest_T04_EV_0118.Tag = "T04-EV-0118";
        field_ReceiptRequest_T04_EV_0118.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0118.TabIndex = 5;
        lbl_ReceiptRequest_T04_EV_0118.Text = "رقم السند";
        lbl_ReceiptRequest_T04_EV_0118.AutoSize = true;
        lbl_ReceiptRequest_T04_EV_0118.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0118.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0118.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_ReceiptRequest_T04_EV_0118.ReadOnly = true;
        field_ReceiptRequest_T04_EV_0118.TabStop = false;
        field_ReceiptRequest_T04_EV_0119.Name = "field_ReceiptRequest_T04_EV_0119";
        lbl_ReceiptRequest_T04_EV_0119.Name = "lbl_ReceiptRequest_T04_EV_0119";
        field_ReceiptRequest_T04_EV_0119.AccessibleName = "التاريخ";
        field_ReceiptRequest_T04_EV_0119.Tag = "T04-EV-0119";
        field_ReceiptRequest_T04_EV_0119.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0119.TabIndex = 6;
        lbl_ReceiptRequest_T04_EV_0119.Text = "التاريخ";
        lbl_ReceiptRequest_T04_EV_0119.AutoSize = true;
        lbl_ReceiptRequest_T04_EV_0119.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0119.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0119.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_ReceiptRequest_T04_EV_0119.Format = DateTimePickerFormat.Custom;
        field_ReceiptRequest_T04_EV_0119.CustomFormat = "yyyy-MM-dd";
        field_ReceiptRequest_T04_EV_0119.ShowCheckBox = true;
        field_ReceiptRequest_T04_EV_0119.Checked = false;
        field_ReceiptRequest_T04_EV_0122.Name = "field_ReceiptRequest_T04_EV_0122";
        lbl_ReceiptRequest_T04_EV_0122.Name = "lbl_ReceiptRequest_T04_EV_0122";
        field_ReceiptRequest_T04_EV_0122.AccessibleName = "البيان";
        field_ReceiptRequest_T04_EV_0122.Tag = "T04-EV-0122";
        field_ReceiptRequest_T04_EV_0122.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0122.TabIndex = 7;
        lbl_ReceiptRequest_T04_EV_0122.Text = "البيان";
        lbl_ReceiptRequest_T04_EV_0122.AutoSize = true;
        lbl_ReceiptRequest_T04_EV_0122.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0122.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0122.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_ReceiptRequest_T04_EV_0122.Multiline = true;
        field_ReceiptRequest_T04_EV_0122.Height = 70;
        field_ReceiptRequest_T04_EV_0122.ScrollBars = ScrollBars.Vertical;
        field_ReceiptRequest_T04_EV_0123.Name = "field_ReceiptRequest_T04_EV_0123";
        lbl_ReceiptRequest_T04_EV_0123.Name = "lbl_ReceiptRequest_T04_EV_0123";
        field_ReceiptRequest_T04_EV_0123.AccessibleName = "رقم المرجع";
        field_ReceiptRequest_T04_EV_0123.Tag = "T04-EV-0123";
        field_ReceiptRequest_T04_EV_0123.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0123.TabIndex = 8;
        lbl_ReceiptRequest_T04_EV_0123.Text = "رقم المرجع";
        lbl_ReceiptRequest_T04_EV_0123.AutoSize = true;
        lbl_ReceiptRequest_T04_EV_0123.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0123.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0123.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_ReceiptRequest_T04_EV_0439.Name = "field_ReceiptRequest_T04_EV_0439";
        lbl_ReceiptRequest_T04_EV_0439.Name = "lbl_ReceiptRequest_T04_EV_0439";
        field_ReceiptRequest_T04_EV_0439.AccessibleName = "المبلغ المحلي";
        field_ReceiptRequest_T04_EV_0439.Tag = "T04-EV-0439";
        field_ReceiptRequest_T04_EV_0439.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0439.TabIndex = 9;
        lbl_ReceiptRequest_T04_EV_0439.Text = "المبلغ المحلي";
        lbl_ReceiptRequest_T04_EV_0439.AutoSize = true;
        lbl_ReceiptRequest_T04_EV_0439.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0439.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0439.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_ReceiptRequest_T04_EV_0439.RightToLeft = RightToLeft.No;
        field_ReceiptRequest_T04_EV_0439.TextAlign = HorizontalAlignment.Right;
        field_ReceiptRequest_T04_EV_0440.Name = "field_ReceiptRequest_T04_EV_0440";
        lbl_ReceiptRequest_T04_EV_0440.Name = "lbl_ReceiptRequest_T04_EV_0440";
        field_ReceiptRequest_T04_EV_0440.AccessibleName = "المبلغ الأجنبي";
        field_ReceiptRequest_T04_EV_0440.Tag = "T04-EV-0440";
        field_ReceiptRequest_T04_EV_0440.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0440.TabIndex = 10;
        lbl_ReceiptRequest_T04_EV_0440.Text = "المبلغ الأجنبي";
        lbl_ReceiptRequest_T04_EV_0440.AutoSize = true;
        lbl_ReceiptRequest_T04_EV_0440.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0440.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0440.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_ReceiptRequest_T04_EV_0440.RightToLeft = RightToLeft.No;
        field_ReceiptRequest_T04_EV_0440.TextAlign = HorizontalAlignment.Right;
        field_ReceiptRequest_T04_EV_0441.Name = "field_ReceiptRequest_T04_EV_0441";
        lbl_ReceiptRequest_T04_EV_0441.Name = "lbl_ReceiptRequest_T04_EV_0441";
        field_ReceiptRequest_T04_EV_0441.AccessibleName = "رقم المركز";
        field_ReceiptRequest_T04_EV_0441.Tag = "T04-EV-0441";
        field_ReceiptRequest_T04_EV_0441.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0441.TabIndex = 11;
        lbl_ReceiptRequest_T04_EV_0441.Text = "رقم المركز";
        lbl_ReceiptRequest_T04_EV_0441.AutoSize = true;
        lbl_ReceiptRequest_T04_EV_0441.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0441.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0441.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_ReceiptRequest_T04_EV_0441.DropDownStyle = ComboBoxStyle.DropDownList;
        field_ReceiptRequest_T04_EV_0441.DropDownWidth = 420;
        field_ReceiptRequest_T04_EV_0442.Name = "field_ReceiptRequest_T04_EV_0442";
        lbl_ReceiptRequest_T04_EV_0442.Name = "lbl_ReceiptRequest_T04_EV_0442";
        field_ReceiptRequest_T04_EV_0442.AccessibleName = "رقم المشروع";
        field_ReceiptRequest_T04_EV_0442.Tag = "T04-EV-0442";
        field_ReceiptRequest_T04_EV_0442.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0442.TabIndex = 12;
        lbl_ReceiptRequest_T04_EV_0442.Text = "رقم المشروع";
        lbl_ReceiptRequest_T04_EV_0442.AutoSize = true;
        lbl_ReceiptRequest_T04_EV_0442.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0442.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0442.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_ReceiptRequest_T04_EV_0442.DropDownStyle = ComboBoxStyle.DropDownList;
        field_ReceiptRequest_T04_EV_0442.DropDownWidth = 420;
        field_ReceiptRequest_T04_EV_0443.Name = "field_ReceiptRequest_T04_EV_0443";
        lbl_ReceiptRequest_T04_EV_0443.Name = "lbl_ReceiptRequest_T04_EV_0443";
        field_ReceiptRequest_T04_EV_0443.AccessibleName = "رقم النشاط";
        field_ReceiptRequest_T04_EV_0443.Tag = "T04-EV-0443";
        field_ReceiptRequest_T04_EV_0443.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0443.TabIndex = 13;
        lbl_ReceiptRequest_T04_EV_0443.Text = "رقم النشاط";
        lbl_ReceiptRequest_T04_EV_0443.AutoSize = true;
        lbl_ReceiptRequest_T04_EV_0443.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0443.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0443.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_ReceiptRequest_T04_EV_0443.DropDownStyle = ComboBoxStyle.DropDownList;
        field_ReceiptRequest_T04_EV_0443.DropDownWidth = 420;
        field_ReceiptRequest_R05_AT_0272.Name = "field_ReceiptRequest_R05_AT_0272";
        lbl_ReceiptRequest_R05_AT_0272.Name = "lbl_ReceiptRequest_R05_AT_0272";
        field_ReceiptRequest_R05_AT_0272.AccessibleName = "رقم الصندوق";
        field_ReceiptRequest_R05_AT_0272.Tag = "R05-AT-0272";
        field_ReceiptRequest_R05_AT_0272.Dock = DockStyle.Fill;
        field_ReceiptRequest_R05_AT_0272.TabIndex = 14;
        lbl_ReceiptRequest_R05_AT_0272.Text = "رقم الصندوق";
        lbl_ReceiptRequest_R05_AT_0272.AutoSize = true;
        lbl_ReceiptRequest_R05_AT_0272.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_R05_AT_0272.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_R05_AT_0272.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_ReceiptRequest_R05_AT_0272.DropDownStyle = ComboBoxStyle.DropDownList;
        field_ReceiptRequest_R05_AT_0272.DropDownWidth = 420;
        field_ReceiptRequest_R05_AT_0273.Name = "field_ReceiptRequest_R05_AT_0273";
        lbl_ReceiptRequest_R05_AT_0273.Name = "lbl_ReceiptRequest_R05_AT_0273";
        field_ReceiptRequest_R05_AT_0273.AccessibleName = "اسم الصندوق";
        field_ReceiptRequest_R05_AT_0273.Tag = "R05-AT-0273";
        field_ReceiptRequest_R05_AT_0273.Dock = DockStyle.Fill;
        field_ReceiptRequest_R05_AT_0273.TabIndex = 15;
        lbl_ReceiptRequest_R05_AT_0273.Text = "اسم الصندوق";
        lbl_ReceiptRequest_R05_AT_0273.AutoSize = true;
        lbl_ReceiptRequest_R05_AT_0273.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_R05_AT_0273.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_R05_AT_0273.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_ReceiptRequest_R05_AT_0273.ReadOnly = true;
        field_ReceiptRequest_R05_AT_0273.TabStop = false;
        field_ReceiptRequest_R05_AT_0274.Name = "field_ReceiptRequest_R05_AT_0274";
        lbl_ReceiptRequest_R05_AT_0274.Name = "lbl_ReceiptRequest_R05_AT_0274";
        field_ReceiptRequest_R05_AT_0274.AccessibleName = "رقم البنك";
        field_ReceiptRequest_R05_AT_0274.Tag = "R05-AT-0274";
        field_ReceiptRequest_R05_AT_0274.Dock = DockStyle.Fill;
        field_ReceiptRequest_R05_AT_0274.TabIndex = 16;
        lbl_ReceiptRequest_R05_AT_0274.Text = "رقم البنك";
        lbl_ReceiptRequest_R05_AT_0274.AutoSize = true;
        lbl_ReceiptRequest_R05_AT_0274.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_R05_AT_0274.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_R05_AT_0274.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_ReceiptRequest_R05_AT_0274, 0, 16);
        layout0.Controls.Add(field_ReceiptRequest_R05_AT_0274, 1, 16);
        field_ReceiptRequest_R05_AT_0274.DropDownStyle = ComboBoxStyle.DropDownList;
        field_ReceiptRequest_R05_AT_0274.DropDownWidth = 420;
        field_ReceiptRequest_R05_AT_0275.Name = "field_ReceiptRequest_R05_AT_0275";
        lbl_ReceiptRequest_R05_AT_0275.Name = "lbl_ReceiptRequest_R05_AT_0275";
        field_ReceiptRequest_R05_AT_0275.AccessibleName = "اسم البنك";
        field_ReceiptRequest_R05_AT_0275.Tag = "R05-AT-0275";
        field_ReceiptRequest_R05_AT_0275.Dock = DockStyle.Fill;
        field_ReceiptRequest_R05_AT_0275.TabIndex = 17;
        lbl_ReceiptRequest_R05_AT_0275.Text = "اسم البنك";
        lbl_ReceiptRequest_R05_AT_0275.AutoSize = true;
        lbl_ReceiptRequest_R05_AT_0275.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_R05_AT_0275.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_R05_AT_0275.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_ReceiptRequest_R05_AT_0275, 0, 17);
        layout0.Controls.Add(field_ReceiptRequest_R05_AT_0275, 1, 17);
        field_ReceiptRequest_R05_AT_0275.ReadOnly = true;
        field_ReceiptRequest_R05_AT_0275.TabStop = false;
        field_ReceiptRequest_T04_EV_0124.Name = "field_ReceiptRequest_T04_EV_0124";
        lbl_ReceiptRequest_T04_EV_0124.Name = "lbl_ReceiptRequest_T04_EV_0124";
        field_ReceiptRequest_T04_EV_0124.AccessibleName = "مستخدم";
        field_ReceiptRequest_T04_EV_0124.Tag = "T04-EV-0124";
        field_ReceiptRequest_T04_EV_0124.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0124.TabIndex = 18;
        lbl_ReceiptRequest_T04_EV_0124.Text = "مستخدم";
        lbl_ReceiptRequest_T04_EV_0124.AutoSize = true;
        lbl_ReceiptRequest_T04_EV_0124.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0124.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0124.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_ReceiptRequest_T04_EV_0124, 0, 18);
        layout0.Controls.Add(field_ReceiptRequest_T04_EV_0124, 1, 18);
        field_ReceiptRequest_T04_EV_0124.ReadOnly = true;
        field_ReceiptRequest_T04_EV_0124.TabStop = false;
        field_ReceiptRequest_T04_EV_0125.Name = "field_ReceiptRequest_T04_EV_0125";
        lbl_ReceiptRequest_T04_EV_0125.Name = "lbl_ReceiptRequest_T04_EV_0125";
        field_ReceiptRequest_T04_EV_0125.AccessibleName = "معلق";
        field_ReceiptRequest_T04_EV_0125.Tag = "T04-EV-0125";
        field_ReceiptRequest_T04_EV_0125.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0125.TabIndex = 19;
        lbl_ReceiptRequest_T04_EV_0125.Text = "معلق";
        lbl_ReceiptRequest_T04_EV_0125.AutoSize = true;
        lbl_ReceiptRequest_T04_EV_0125.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0125.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0125.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_ReceiptRequest_T04_EV_0125, 0, 19);
        layout0.Controls.Add(field_ReceiptRequest_T04_EV_0125, 1, 19);
        field_ReceiptRequest_T04_EV_0125.ReadOnly = true;
        field_ReceiptRequest_T04_EV_0125.TabStop = false;
        layout0.RowCount = 20;
        tp1.Name = "tp1";
        tp1.Text = "البيانات التفصيلية";
        tp1.AutoScroll = true;
        tp1.TabIndex = 1;
        tabs.Controls.Add(tp1);
        layout1.Name = "layout1";
        layout1.Dock = DockStyle.Top;
        layout1.AutoSize = true;
        layout1.ColumnCount = 2;
        layout1.MinimumSize = new Size(650,0);
        layout1.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp1.Controls.Add(layout1);
        layout1.RowCount = 0;
        dgvLines.Name = "dgvLines";
        dgvLines.Dock = DockStyle.Fill;
        dgvLines.MinimumSize = new Size(650,260);
        dgvLines.AutoGenerateColumns = false;
        dgvLines.AllowUserToAddRows = false;
        dgvLines.AllowUserToDeleteRows = false;
        dgvLines.AllowUserToOrderColumns = false;
        dgvLines.RowHeadersVisible = false;
        dgvLines.MultiSelect = false;
        dgvLines.SelectionMode = DataGridViewSelectionMode.CellSelect;
        dgvLines.AccessibleName = "البيانات التفصيلية";
        dgvLines.TabIndex = 1;
        col_rowNo.Name = "col_rowNo";
        col_rowNo.Name = "rowNo";
        col_rowNo.HeaderText = "#";
        col_rowNo.ReadOnly = true;
        col_rowNo.Tag = "text";
        col_rowNo.MinimumWidth = 90;
        col_rowNo.Width = 140;
        col_rowNo.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_rowNo);
        col_ReceiptRequest_T04_EV_0129.Name = "col_ReceiptRequest_T04_EV_0129";
        col_ReceiptRequest_T04_EV_0129.Name = "ReceiptRequest_T04_EV_0129";
        col_ReceiptRequest_T04_EV_0129.HeaderText = "الحساب التحليلي";
        col_ReceiptRequest_T04_EV_0129.ReadOnly = false;
        col_ReceiptRequest_T04_EV_0129.Tag = "lookup";
        col_ReceiptRequest_T04_EV_0129.MinimumWidth = 90;
        col_ReceiptRequest_T04_EV_0129.Width = 140;
        col_ReceiptRequest_T04_EV_0129.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_ReceiptRequest_T04_EV_0129.DisplayStyle = DataGridViewComboBoxDisplayStyle.DropDownButton;
        col_ReceiptRequest_T04_EV_0129.ValueType = typeof(string);
        dgvLines.Columns.Add(col_ReceiptRequest_T04_EV_0129);
        col_ReceiptRequest_T04_EV_0447.Name = "col_ReceiptRequest_T04_EV_0447";
        col_ReceiptRequest_T04_EV_0447.Name = "ReceiptRequest_T04_EV_0447";
        col_ReceiptRequest_T04_EV_0447.HeaderText = "العملة";
        col_ReceiptRequest_T04_EV_0447.ReadOnly = false;
        col_ReceiptRequest_T04_EV_0447.Tag = "lookup";
        col_ReceiptRequest_T04_EV_0447.MinimumWidth = 90;
        col_ReceiptRequest_T04_EV_0447.Width = 140;
        col_ReceiptRequest_T04_EV_0447.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_ReceiptRequest_T04_EV_0447.DisplayStyle = DataGridViewComboBoxDisplayStyle.DropDownButton;
        col_ReceiptRequest_T04_EV_0447.ValueType = typeof(string);
        dgvLines.Columns.Add(col_ReceiptRequest_T04_EV_0447);
        col_ReceiptRequest_T04_EV_0448.Name = "col_ReceiptRequest_T04_EV_0448";
        col_ReceiptRequest_T04_EV_0448.Name = "ReceiptRequest_T04_EV_0448";
        col_ReceiptRequest_T04_EV_0448.HeaderText = "سعر التحويل";
        col_ReceiptRequest_T04_EV_0448.ReadOnly = false;
        col_ReceiptRequest_T04_EV_0448.Tag = "decimal";
        col_ReceiptRequest_T04_EV_0448.MinimumWidth = 90;
        col_ReceiptRequest_T04_EV_0448.Width = 140;
        col_ReceiptRequest_T04_EV_0448.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_ReceiptRequest_T04_EV_0448.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_ReceiptRequest_T04_EV_0448);
        col_ReceiptRequest_T04_EV_0449.Name = "col_ReceiptRequest_T04_EV_0449";
        col_ReceiptRequest_T04_EV_0449.Name = "ReceiptRequest_T04_EV_0449";
        col_ReceiptRequest_T04_EV_0449.HeaderText = "المبلغ المحلي";
        col_ReceiptRequest_T04_EV_0449.ReadOnly = false;
        col_ReceiptRequest_T04_EV_0449.Tag = "decimal";
        col_ReceiptRequest_T04_EV_0449.MinimumWidth = 90;
        col_ReceiptRequest_T04_EV_0449.Width = 140;
        col_ReceiptRequest_T04_EV_0449.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_ReceiptRequest_T04_EV_0449.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_ReceiptRequest_T04_EV_0449);
        col_ReceiptRequest_T04_EV_0450.Name = "col_ReceiptRequest_T04_EV_0450";
        col_ReceiptRequest_T04_EV_0450.Name = "ReceiptRequest_T04_EV_0450";
        col_ReceiptRequest_T04_EV_0450.HeaderText = "المبلغ الأجنبي";
        col_ReceiptRequest_T04_EV_0450.ReadOnly = false;
        col_ReceiptRequest_T04_EV_0450.Tag = "decimal";
        col_ReceiptRequest_T04_EV_0450.MinimumWidth = 90;
        col_ReceiptRequest_T04_EV_0450.Width = 140;
        col_ReceiptRequest_T04_EV_0450.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_ReceiptRequest_T04_EV_0450.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_ReceiptRequest_T04_EV_0450);
        col_ReceiptRequest_R05_AT_0276.Name = "col_ReceiptRequest_R05_AT_0276";
        col_ReceiptRequest_R05_AT_0276.Name = "ReceiptRequest_R05_AT_0276";
        col_ReceiptRequest_R05_AT_0276.HeaderText = "رقم الحساب";
        col_ReceiptRequest_R05_AT_0276.ReadOnly = false;
        col_ReceiptRequest_R05_AT_0276.Tag = "lookup";
        col_ReceiptRequest_R05_AT_0276.MinimumWidth = 90;
        col_ReceiptRequest_R05_AT_0276.Width = 140;
        col_ReceiptRequest_R05_AT_0276.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_ReceiptRequest_R05_AT_0276.DisplayStyle = DataGridViewComboBoxDisplayStyle.DropDownButton;
        col_ReceiptRequest_R05_AT_0276.ValueType = typeof(string);
        dgvLines.Columns.Add(col_ReceiptRequest_R05_AT_0276);
        col_ReceiptRequest_R05_AT_0277.Name = "col_ReceiptRequest_R05_AT_0277";
        col_ReceiptRequest_R05_AT_0277.Name = "ReceiptRequest_R05_AT_0277";
        col_ReceiptRequest_R05_AT_0277.HeaderText = "اسم الحساب";
        col_ReceiptRequest_R05_AT_0277.ReadOnly = true;
        col_ReceiptRequest_R05_AT_0277.Tag = "text";
        col_ReceiptRequest_R05_AT_0277.MinimumWidth = 90;
        col_ReceiptRequest_R05_AT_0277.Width = 140;
        col_ReceiptRequest_R05_AT_0277.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_ReceiptRequest_R05_AT_0277);
        linesHost.Name = "linesHost";
        linesHost.Dock = DockStyle.Fill;
        linesHost.ColumnCount = 1;
        linesHost.RowCount = 3;
        linesHost.MinimumSize = new Size(680,380);
        linesHost.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        linesHost.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        linesHost.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        linesHost.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        tp1.Controls.Remove(layout1);
        linesHost.Controls.Add(layout1, 0, 0);
        tp1.Controls.Add(linesHost);
        linesHost.Controls.Add(dgvLines, 0, 2);
        lineActions.Name = "lineActions";
        lineActions.Dock = DockStyle.Fill;
        lineActions.AutoSize = true;
        linesHost.Controls.Add(lineActions, 0, 1);
        btnAddRow.Name = "btnAddRow";
        btnAddRow.Text = "إضافة سطر";
        btnAddRow.AutoSize = true;
        lineActions.Controls.Add(btnAddRow);
        btnRemoveRow.Name = "btnRemoveRow";
        btnRemoveRow.Text = "حذف سطر";
        btnRemoveRow.AutoSize = true;
        lineActions.Controls.Add(btnRemoveRow);
        tp2.Name = "tp2";
        tp2.Text = "الحسابات";
        tp2.AutoScroll = true;
        tp2.TabIndex = 2;
        tabs.Controls.Add(tp2);
        layout2.Name = "layout2";
        layout2.Dock = DockStyle.Top;
        layout2.AutoSize = true;
        layout2.ColumnCount = 2;
        layout2.MinimumSize = new Size(650,0);
        layout2.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp2.Controls.Add(layout2);
        layout2.RowCount = 0;
        layout2.Dock = DockStyle.Fill;
        layout2.RowCount = 1;
        layout2.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        context2.Name = "context2";
        context2.ReadOnly = true;
        context2.Dock = DockStyle.Fill;
        context2.AccessibleName = "الحسابات";
        context2.DetectUrls = false;
        layout2.Controls.Add(context2, 0, 0);
        layout2.SetColumnSpan(context2,2);
        tp3.Name = "tp3";
        tp3.Text = "بيانات إضافية";
        tp3.AutoScroll = true;
        tp3.TabIndex = 3;
        tabs.Controls.Add(tp3);
        layout3.Name = "layout3";
        layout3.Dock = DockStyle.Top;
        layout3.AutoSize = true;
        layout3.ColumnCount = 2;
        layout3.MinimumSize = new Size(650,0);
        layout3.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout3.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp3.Controls.Add(layout3);
        field_localNotes.Name = "field_localNotes";
        lbl_localNotes.Name = "lbl_localNotes";
        field_localNotes.AccessibleName = "ملاحظات";
        field_localNotes.Tag = "LOCAL:notes";
        field_localNotes.Dock = DockStyle.Fill;
        field_localNotes.TabIndex = 0;
        lbl_localNotes.Text = "ملاحظات";
        lbl_localNotes.AutoSize = true;
        lbl_localNotes.Dock = DockStyle.Fill;
        lbl_localNotes.TextAlign = ContentAlignment.MiddleRight;
        lbl_localNotes.TabStop = false;
        layout3.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout3.Controls.Add(lbl_localNotes, 0, 0);
        layout3.Controls.Add(field_localNotes, 1, 0);
        field_localNotes.Multiline = true;
        field_localNotes.Height = 70;
        field_localNotes.ScrollBars = ScrollBars.Vertical;
        layout3.RowCount = 1;
        tp4.Name = "tp4";
        tp4.Text = "البيانات الافتراضية";
        tp4.AutoScroll = true;
        tp4.TabIndex = 4;
        tabs.Controls.Add(tp4);
        layout4.Name = "layout4";
        layout4.Dock = DockStyle.Top;
        layout4.AutoSize = true;
        layout4.ColumnCount = 2;
        layout4.MinimumSize = new Size(650,0);
        layout4.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout4.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp4.Controls.Add(layout4);
        layout4.RowCount = 0;
        layout4.Dock = DockStyle.Fill;
        layout4.RowCount = 1;
        layout4.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        context4.Name = "context4";
        context4.ReadOnly = true;
        context4.Dock = DockStyle.Fill;
        context4.AccessibleName = "البيانات الافتراضية";
        context4.DetectUrls = false;
        layout4.Controls.Add(context4, 0, 0);
        layout4.SetColumnSpan(context4,2);
        tp5.Name = "tp5";
        tp5.Text = "استيراد من ملف";
        tp5.AutoScroll = true;
        tp5.TabIndex = 5;
        tabs.Controls.Add(tp5);
        layout5.Name = "layout5";
        layout5.Dock = DockStyle.Top;
        layout5.AutoSize = true;
        layout5.ColumnCount = 2;
        layout5.MinimumSize = new Size(650,0);
        layout5.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout5.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp5.Controls.Add(layout5);
        layout5.RowCount = 0;
        layout5.Dock = DockStyle.Fill;
        layout5.RowCount = 3;
        layout5.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout5.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout5.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        txtCsvPath.Name = "txtCsvPath";
        txtCsvPath.ReadOnly = true;
        txtCsvPath.Dock = DockStyle.Fill;
        txtCsvPath.AccessibleName = "مسار ملف CSV";
        layout5.Controls.Add(txtCsvPath, 1, 0);
        csvActions.Name = "csvActions";
        csvActions.AutoSize = true;
        csvActions.Dock = DockStyle.Fill;
        layout5.Controls.Add(csvActions, 0, 0);
        btnChooseCsv.Name = "btnChooseCsv";
        btnChooseCsv.Text = "اختيار ومعاينة CSV";
        btnChooseCsv.AutoSize = true;
        csvActions.Controls.Add(btnChooseCsv);
        btnImportCsv.Name = "btnImportCsv";
        btnImportCsv.Text = "إضافة إلى المسودة";
        btnImportCsv.AutoSize = true;
        csvActions.Controls.Add(btnImportCsv);
        txtCsvSchema.Name = "txtCsvSchema";
        txtCsvSchema.ReadOnly = true;
        txtCsvSchema.Multiline = true;
        txtCsvSchema.Height = 75;
        txtCsvSchema.Dock = DockStyle.Fill;
        txtCsvSchema.Text = "قالب CSV محلي: UTF-8، فاصل فاصلة، الرموز من القوائم المرتبطة. عناوين الأعمدة بالترتيب:\r\nT04_EV_0129,ReceiptRequest_T04_EV_0447,ReceiptRequest_T04_EV_0448,ReceiptRequest_T04_EV_0449,ReceiptRequest_T04_EV_0450,ReceiptRequest_R05_AT_0276";
        layout5.Controls.Add(txtCsvSchema, 0, 1);
        layout5.SetColumnSpan(txtCsvSchema,2);
        dgvImport.Name = "dgvImport";
        dgvImport.Dock = DockStyle.Fill;
        dgvImport.ReadOnly = true;
        dgvImport.AllowUserToAddRows = false;
        dgvImport.AllowUserToDeleteRows = false;
        dgvImport.AutoGenerateColumns = false;
        dgvImport.MinimumSize = new Size(650,200);
        layout5.Controls.Add(dgvImport, 0, 2);
        layout5.SetColumnSpan(dgvImport,2);
        AutoScaleDimensions = new SizeF(96F,96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Name = "UcOnyxSCREEN0098";
        Text = "طلبات سندات القبض";
        Tag = "ONYX:SCREEN-0100";
        Size = new Size(1100,720);
        Controls.Add(mainLayout);
        ResumeLayout(false);
        PerformLayout();

        col_rowNo.DisplayIndex = 0;
        // Reference layout: Onyx general ledger manual, second edition.
        referenceLabel11.Text = "رقم المحصل";
        referenceField11.ReadOnly = true;
        referenceField11.TabStop = false;
        referenceField11.AccessibleDescription = "حقل مرجعي؛ لم يربط بخدمة السند بعد";
        referenceField11.BackColor = Color.FromArgb(245,245,245);
        referenceLabel12.Text = "نسبة العمولة";
        referenceField12.ReadOnly = true;
        referenceField12.TabStop = false;
        referenceField12.AccessibleDescription = "حقل مرجعي؛ لم يربط بخدمة السند بعد";
        referenceField12.BackColor = Color.FromArgb(245,245,245);
        referenceLabel14.Text = "اسم المرجع";
        referenceField14.ReadOnly = true;
        referenceField14.TabStop = false;
        referenceField14.AccessibleDescription = "حقل مرجعي؛ لم يربط بخدمة السند بعد";
        referenceField14.BackColor = Color.FromArgb(245,245,245);
        referenceLabel15.Text = "عدد المرفقات";
        referenceField15.ReadOnly = true;
        referenceField15.TabStop = false;
        referenceField15.AccessibleDescription = "حقل مرجعي؛ لم يربط بخدمة السند بعد";
        referenceField15.BackColor = Color.FromArgb(245,245,245);
        layout0.AutoScroll = true;
        layout1.AutoScroll = true;
        layout2.AutoScroll = true;
        layout3.AutoScroll = true;
        layout4.AutoScroll = true;
        layout5.AutoScroll = true;
        referenceExtra.Name = "referenceExtra";
        referenceExtra.Text = "بيانات إضافية";
        referenceExtra.AutoScroll = true;
        tp0.Controls.Remove(layout0);
        referenceExtra.Controls.Add(layout0);
        tabs.Controls.Add(referenceExtra);
        tp0.Controls.Add(referenceHeader);
        referenceHeader.Name = "referenceHeader";
        referenceHeader.Dock = DockStyle.Top;
        referenceHeader.AutoSize = true;
        referenceHeader.RightToLeft = RightToLeft.Yes;
        referenceHeader.BackColor = Color.FromArgb(245,245,245);
        referenceHeader.Padding = new Padding(8);
        referenceHeader.ColumnCount = 6;
        referenceHeader.RowCount = 9;
        referenceHeader.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        referenceHeader.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        referenceHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,115F));
        referenceHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,33.333F));
        referenceHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,115F));
        referenceHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,33.333F));
        referenceHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,115F));
        referenceHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,33.333F));
        referenceHeader.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        referenceHeader.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        referenceHeader.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        referenceHeader.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        referenceHeader.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        referenceHeader.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        referenceHeader.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        lbl_ReceiptRequest_T04_EV_0111.AutoSize = false;
        lbl_ReceiptRequest_T04_EV_0111.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0111.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0111.Margin = new Padding(2);
        field_ReceiptRequest_T04_EV_0111.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0111.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_ReceiptRequest_T04_EV_0111, 0, 0);
        referenceHeader.Controls.Add(field_ReceiptRequest_T04_EV_0111, 1, 0);
        lbl_ReceiptRequest_T04_EV_0112.AutoSize = false;
        lbl_ReceiptRequest_T04_EV_0112.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0112.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0112.Margin = new Padding(2);
        field_ReceiptRequest_T04_EV_0112.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0112.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_ReceiptRequest_T04_EV_0112, 2, 0);
        referenceHeader.Controls.Add(field_ReceiptRequest_T04_EV_0112, 3, 0);
        lbl_ReceiptRequest_T04_EV_0118.AutoSize = false;
        lbl_ReceiptRequest_T04_EV_0118.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0118.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0118.Margin = new Padding(2);
        field_ReceiptRequest_T04_EV_0118.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0118.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_ReceiptRequest_T04_EV_0118, 4, 0);
        referenceHeader.Controls.Add(field_ReceiptRequest_T04_EV_0118, 5, 0);
        lbl_ReceiptRequest_T04_EV_0119.AutoSize = false;
        lbl_ReceiptRequest_T04_EV_0119.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0119.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0119.Margin = new Padding(2);
        field_ReceiptRequest_T04_EV_0119.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0119.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_ReceiptRequest_T04_EV_0119, 0, 1);
        referenceHeader.Controls.Add(field_ReceiptRequest_T04_EV_0119, 1, 1);
        lbl_ReceiptRequest_R05_AT_0272.AutoSize = false;
        lbl_ReceiptRequest_R05_AT_0272.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_R05_AT_0272.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_R05_AT_0272.Margin = new Padding(2);
        field_ReceiptRequest_R05_AT_0272.Dock = DockStyle.Fill;
        field_ReceiptRequest_R05_AT_0272.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_ReceiptRequest_R05_AT_0272, 2, 1);
        referenceHeader.Controls.Add(field_ReceiptRequest_R05_AT_0272, 3, 1);
        lbl_ReceiptRequest_R05_AT_0273.AutoSize = false;
        lbl_ReceiptRequest_R05_AT_0273.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_R05_AT_0273.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_R05_AT_0273.Margin = new Padding(2);
        field_ReceiptRequest_R05_AT_0273.Dock = DockStyle.Fill;
        field_ReceiptRequest_R05_AT_0273.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_ReceiptRequest_R05_AT_0273, 4, 1);
        referenceHeader.Controls.Add(field_ReceiptRequest_R05_AT_0273, 5, 1);
        lbl_ReceiptRequest_T04_EV_0115.AutoSize = false;
        lbl_ReceiptRequest_T04_EV_0115.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0115.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0115.Margin = new Padding(2);
        field_ReceiptRequest_T04_EV_0115.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0115.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_ReceiptRequest_T04_EV_0115, 0, 2);
        referenceHeader.Controls.Add(field_ReceiptRequest_T04_EV_0115, 1, 2);
        lbl_ReceiptRequest_T04_EV_0116.AutoSize = false;
        lbl_ReceiptRequest_T04_EV_0116.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0116.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0116.Margin = new Padding(2);
        field_ReceiptRequest_T04_EV_0116.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0116.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_ReceiptRequest_T04_EV_0116, 2, 2);
        referenceHeader.Controls.Add(field_ReceiptRequest_T04_EV_0116, 3, 2);
        lbl_ReceiptRequest_T04_EV_0439.AutoSize = false;
        lbl_ReceiptRequest_T04_EV_0439.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0439.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0439.Margin = new Padding(2);
        field_ReceiptRequest_T04_EV_0439.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0439.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_ReceiptRequest_T04_EV_0439, 4, 2);
        referenceHeader.Controls.Add(field_ReceiptRequest_T04_EV_0439, 5, 2);
        lbl_ReceiptRequest_T04_EV_0440.AutoSize = false;
        lbl_ReceiptRequest_T04_EV_0440.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0440.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0440.Margin = new Padding(2);
        field_ReceiptRequest_T04_EV_0440.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0440.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_ReceiptRequest_T04_EV_0440, 0, 3);
        referenceHeader.Controls.Add(field_ReceiptRequest_T04_EV_0440, 1, 3);
        lbl_ReceiptRequest_T04_EV_0122.AutoSize = false;
        lbl_ReceiptRequest_T04_EV_0122.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0122.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0122.Margin = new Padding(2);
        field_ReceiptRequest_T04_EV_0122.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0122.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_ReceiptRequest_T04_EV_0122, 2, 3);
        referenceHeader.Controls.Add(field_ReceiptRequest_T04_EV_0122, 3, 3);
        referenceLabel11.AutoSize = false;
        referenceLabel11.Dock = DockStyle.Fill;
        referenceLabel11.TextAlign = ContentAlignment.MiddleRight;
        referenceLabel11.Margin = new Padding(2);
        referenceField11.Dock = DockStyle.Fill;
        referenceField11.Margin = new Padding(2);
        referenceHeader.Controls.Add(referenceLabel11, 4, 3);
        referenceHeader.Controls.Add(referenceField11, 5, 3);
        referenceLabel12.AutoSize = false;
        referenceLabel12.Dock = DockStyle.Fill;
        referenceLabel12.TextAlign = ContentAlignment.MiddleRight;
        referenceLabel12.Margin = new Padding(2);
        referenceField12.Dock = DockStyle.Fill;
        referenceField12.Margin = new Padding(2);
        referenceHeader.Controls.Add(referenceLabel12, 0, 4);
        referenceHeader.Controls.Add(referenceField12, 1, 4);
        lbl_ReceiptRequest_T04_EV_0123.AutoSize = false;
        lbl_ReceiptRequest_T04_EV_0123.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0123.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0123.Margin = new Padding(2);
        field_ReceiptRequest_T04_EV_0123.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0123.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_ReceiptRequest_T04_EV_0123, 2, 4);
        referenceHeader.Controls.Add(field_ReceiptRequest_T04_EV_0123, 3, 4);
        referenceLabel14.AutoSize = false;
        referenceLabel14.Dock = DockStyle.Fill;
        referenceLabel14.TextAlign = ContentAlignment.MiddleRight;
        referenceLabel14.Margin = new Padding(2);
        referenceField14.Dock = DockStyle.Fill;
        referenceField14.Margin = new Padding(2);
        referenceHeader.Controls.Add(referenceLabel14, 4, 4);
        referenceHeader.Controls.Add(referenceField14, 5, 4);
        referenceLabel15.AutoSize = false;
        referenceLabel15.Dock = DockStyle.Fill;
        referenceLabel15.TextAlign = ContentAlignment.MiddleRight;
        referenceLabel15.Margin = new Padding(2);
        referenceField15.Dock = DockStyle.Fill;
        referenceField15.Margin = new Padding(2);
        referenceHeader.Controls.Add(referenceLabel15, 0, 5);
        referenceHeader.Controls.Add(referenceField15, 1, 5);
        lbl_ReceiptRequest_T04_EV_0117.AutoSize = false;
        lbl_ReceiptRequest_T04_EV_0117.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0117.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0117.Margin = new Padding(2);
        field_ReceiptRequest_T04_EV_0117.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0117.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_ReceiptRequest_T04_EV_0117, 2, 5);
        referenceHeader.Controls.Add(field_ReceiptRequest_T04_EV_0117, 3, 5);
        lbl_ReceiptRequest_T04_EV_0441.AutoSize = false;
        lbl_ReceiptRequest_T04_EV_0441.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0441.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0441.Margin = new Padding(2);
        field_ReceiptRequest_T04_EV_0441.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0441.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_ReceiptRequest_T04_EV_0441, 4, 5);
        referenceHeader.Controls.Add(field_ReceiptRequest_T04_EV_0441, 5, 5);
        lbl_ReceiptRequest_T04_EV_0442.AutoSize = false;
        lbl_ReceiptRequest_T04_EV_0442.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0442.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0442.Margin = new Padding(2);
        field_ReceiptRequest_T04_EV_0442.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0442.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_ReceiptRequest_T04_EV_0442, 0, 6);
        referenceHeader.Controls.Add(field_ReceiptRequest_T04_EV_0442, 1, 6);
        lbl_ReceiptRequest_T04_EV_0443.AutoSize = false;
        lbl_ReceiptRequest_T04_EV_0443.Dock = DockStyle.Fill;
        lbl_ReceiptRequest_T04_EV_0443.TextAlign = ContentAlignment.MiddleRight;
        lbl_ReceiptRequest_T04_EV_0443.Margin = new Padding(2);
        field_ReceiptRequest_T04_EV_0443.Dock = DockStyle.Fill;
        field_ReceiptRequest_T04_EV_0443.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_ReceiptRequest_T04_EV_0443, 2, 6);
        referenceHeader.Controls.Add(field_ReceiptRequest_T04_EV_0443, 3, 6);
        // General-ledger curriculum page 90: request state and stopped indicator.
        lblReferenceRequestState.Name = "lblReferenceRequestState";
        lblReferenceRequestState.Text = "الحالة";
        lblReferenceRequestState.Dock = DockStyle.Fill;
        lblReferenceRequestState.TextAlign = ContentAlignment.MiddleLeft;
        lblReferenceRequestState.Margin = new Padding(3);
        referenceRequestStateLayout.Name = "referenceRequestStateLayout";
        referenceRequestStateLayout.Dock = DockStyle.Fill;
        referenceRequestStateLayout.Margin = Padding.Empty;
        referenceRequestStateLayout.RightToLeft = RightToLeft.Yes;
        referenceRequestStateLayout.ColumnCount = 2;
        referenceRequestStateLayout.RowCount = 1;
        referenceRequestStateLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        referenceRequestStateLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 96F));
        referenceRequestStateLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        cboReferenceRequestState.Name = "cboReferenceRequestState";
        cboReferenceRequestState.AccessibleName = "حالة الطلب";
        cboReferenceRequestState.Dock = DockStyle.Fill;
        cboReferenceRequestState.DropDownStyle = ComboBoxStyle.DropDownList;
        cboReferenceRequestState.Items.AddRange(new object[] { "غير معتمد", "معتمد", "رفض", "إرجاع" });
        cboReferenceRequestState.Enabled = false;
        cboReferenceRequestState.TabStop = false;
        chkReferenceRequestStopped.Name = "chkReferenceRequestStopped";
        chkReferenceRequestStopped.Text = "موقف";
        chkReferenceRequestStopped.AccessibleName = "الطلب موقف";
        chkReferenceRequestStopped.Dock = DockStyle.Fill;
        chkReferenceRequestStopped.Enabled = false;
        chkReferenceRequestStopped.TabStop = false;
        referenceRequestStateLayout.Controls.Add(cboReferenceRequestState, 0, 0);
        referenceRequestStateLayout.Controls.Add(chkReferenceRequestStopped, 1, 0);
        referenceHeader.Controls.Add(lblReferenceRequestState, 0, 7);
        referenceHeader.Controls.Add(referenceRequestStateLayout, 1, 7);
        referenceHeader.SetColumnSpan(referenceRequestStateLayout, 3);
        // Main-view-only additions from general-ledger pages 88 and 90; outside legacy payload.
        lblReferencePaymentMode.Name = "lblReferencePaymentMode";
        lblReferencePaymentMode.Text = "طريقة الدفع";
        lblReferencePaymentMode.Dock = DockStyle.Fill;
        lblReferencePaymentMode.TextAlign = ContentAlignment.MiddleLeft;
        referencePaymentModeLayout.Name = "referencePaymentModeLayout";
        referencePaymentModeLayout.Dock = DockStyle.Fill;
        referencePaymentModeLayout.Margin = Padding.Empty;
        referencePaymentModeLayout.FlowDirection = FlowDirection.RightToLeft;
        referencePaymentModeLayout.WrapContents = false;
        radioReferenceCash.Name = "radioReferenceCash";
        radioReferenceCash.Text = "نقداً";
        radioReferenceCash.AutoSize = true;
        radioReferenceCash.Enabled = false;
        radioReferenceBank.Name = "radioReferenceBank";
        radioReferenceBank.Text = "بنكي";
        radioReferenceBank.AutoSize = true;
        radioReferenceBank.Enabled = false;
        referencePaymentModeLayout.Controls.Add(radioReferenceCash);
        referencePaymentModeLayout.Controls.Add(radioReferenceBank);
        lblReferenceOperationType.Name = "lblReferenceOperationType";
        lblReferenceOperationType.Text = "نوع العملية";
        lblReferenceOperationType.Dock = DockStyle.Fill;
        lblReferenceOperationType.TextAlign = ContentAlignment.MiddleLeft;
        cboReferenceOperationType.Name = "cboReferenceOperationType";
        cboReferenceOperationType.AccessibleName = "نوع العملية";
        cboReferenceOperationType.DropDownStyle = ComboBoxStyle.DropDownList;
        cboReferenceOperationType.Dock = DockStyle.Fill;
        cboReferenceOperationType.Enabled = false;
        lblReferenceRecipient.Name = "lblReferenceRecipient";
        lblReferenceRecipient.Text = "المستلم";
        lblReferenceRecipient.Dock = DockStyle.Fill;
        lblReferenceRecipient.TextAlign = ContentAlignment.MiddleLeft;
        txtReferenceRecipient.Name = "txtReferenceRecipient";
        txtReferenceRecipient.AccessibleName = "المستلم";
        txtReferenceRecipient.Dock = DockStyle.Fill;
        txtReferenceRecipient.ReadOnly = true;
        referenceHeader.Controls.Add(lblReferenceRecipient, 4, 7);
        referenceHeader.Controls.Add(txtReferenceRecipient, 5, 7);
        referenceHeader.Controls.Add(lblReferencePaymentMode, 0, 8);
        referenceHeader.Controls.Add(referencePaymentModeLayout, 1, 8);
        referenceHeader.Controls.Add(lblReferenceOperationType, 2, 8);
        referenceHeader.Controls.Add(cboReferenceOperationType, 3, 8);

        dgvLines.Parent.Controls.Remove(dgvLines);
        btnAddRow.Parent.Controls.Remove(btnAddRow);
        btnRemoveRow.Parent.Controls.Remove(btnRemoveRow);
        flpActions.Controls.Add(btnAddRow);
        flpActions.Controls.Add(btnRemoveRow);
        referenceCol2.Name = "referenceOnly2";
        referenceCol2.HeaderText = "البيان";
        referenceCol2.ReadOnly = true;
        referenceCol2.Width = 140;
        referenceCol2.ToolTipText = "للعرض؛ يحتاج ربطًا بخدمة السند";
        dgvLines.Columns.Add(referenceCol2);
        // Display indices require all nine columns, including the reference description.
        col_ReceiptRequest_R05_AT_0276.DisplayIndex = 1;
        col_ReceiptRequest_T04_EV_0129.DisplayIndex = 2;
        col_ReceiptRequest_R05_AT_0277.DisplayIndex = 3;
        referenceCol2.DisplayIndex = 4;
        col_ReceiptRequest_T04_EV_0447.DisplayIndex = 5;
        col_ReceiptRequest_T04_EV_0448.DisplayIndex = 6;
        col_ReceiptRequest_T04_EV_0449.DisplayIndex = 7;
        col_ReceiptRequest_T04_EV_0450.DisplayIndex = 8;
        dgvLines.Dock = DockStyle.Fill;
        dgvLines.MinimumSize = new Size(900,160);
        dgvLines.BackgroundColor = Color.White;
        dgvLines.RightToLeft = RightToLeft.Yes;
        dgvLines.EnableHeadersVisualStyles = false;
        dgvLines.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(232,232,232);
        dgvLines.ColumnHeadersHeight = 34;
        dgvLines.RowTemplate.Height = 27;
        dgvLines.DefaultCellStyle.BackColor = Color.FromArgb(255,255,226);
        dgvLines.AlternatingRowsDefaultCellStyle.BackColor = Color.White;
        dgvLines.ScrollBars = ScrollBars.Both;
        mainLayout.Controls.Remove(tabs);
        mainLayout.Controls.Remove(lblStatus);
        mainLayout.RowStyles.Clear();
        mainLayout.RowCount = 7;
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute,34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute,343F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute,48F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.Controls.Add(tabs,0,2);
        mainLayout.Controls.Add(dgvLines,0,3);
        mainLayout.Controls.Add(referenceTotals,0,4);
        mainLayout.Controls.Add(referenceAudit,0,5);
        mainLayout.Controls.Add(lblStatus,0,6);
        referenceTotals.Dock = DockStyle.Fill;
        referenceTotals.TextAlign = ContentAlignment.MiddleCenter;
        referenceTotals.BackColor = Color.FromArgb(250,223,249);
        referenceTotals.Text = "الإجمالي: —          الفارق: —";
        referenceAudit.Dock = DockStyle.Fill;
        referenceAudit.BackColor = Color.FromArgb(225,223,247);
        referenceAudit.TextAlign = ContentAlignment.MiddleRight;
        referenceAudit.Text = "مدخل السجل: —    تاريخ الإدخال: —    الجهاز: —\r\nمعدل السجل: —    تاريخ التعديل: —    مرات التعديل: —    مرات الطباعة: —";
        lblTitle.Text = "طلبات سندات القبض";
        lblTitle.BackColor = Color.FromArgb(232,232,242);
        lblTitle.ForeColor = Color.FromArgb(35,35,50);
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Margin = new Padding(0);
        flpActions.BackColor = Color.FromArgb(239,239,244);
        flpActions.RightToLeft = RightToLeft.Yes;
        flpActions.FlowDirection = FlowDirection.RightToLeft;
        flpActions.WrapContents = true;
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeft = RightToLeft.Yes;
        tabs.RightToLeftLayout = true;
        tabs.Font = new Font("Tahoma",9F);
        mainLayout.MinimumSize = new Size(1080,780);
        AutoScroll = true;
        Font = new Font("Tahoma",9F);
        BackColor = Color.FromArgb(240,240,240);
        Text = "طلبات سندات القبض";
        referencePrint.Text = "طباعة";
        referencePrint.AutoSize = true;
        referencePrint.Enabled = false;

        // Tabs based on documented Onyx behavior; no claim of pixel-identical unseen tabs.
        documentAdditional.Name = "documentAdditional";
        documentAdditional.Text = "بيانات إضافية";
        documentAdditional.AutoScroll = true;
        documentAdditionalSections.Dock = DockStyle.Fill;
        documentAdditionalSections.RightToLeft = RightToLeft.Yes;
        documentAdditionalSections.RightToLeftLayout = true;
        documentAdditional.Controls.Add(documentAdditionalSections);
        tabs.Controls.Remove(tp1);
        documentAdditionalSections.Controls.Add(tp1);
        tabs.Controls.Remove(tp2);
        documentAdditionalSections.Controls.Add(tp2);
        tabs.Controls.Remove(tp3);
        documentAdditionalSections.Controls.Add(tp3);
        tabs.Controls.Remove(tp4);
        documentAdditionalSections.Controls.Add(tp4);
        tabs.Controls.Remove(referenceExtra);
        documentAdditionalSections.Controls.Add(referenceExtra);
        referenceExtra.Text = "حقول تكميلية";
        tabs.Controls.Add(documentAdditional);
        documentDefaults.Name = "documentDefaults";
        documentDefaults.Text = "البيانات الافتراضية";
        documentDefaults.AutoScroll = true;
        documentDefaultsLayout.Dock = DockStyle.Top;
        documentDefaultsLayout.AutoSize = true;
        documentDefaultsLayout.ColumnCount = 2;
        documentDefaultsLayout.RowCount = 2;
        documentDefaultsLayout.Padding = new Padding(12);
        documentDefaultsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,140F));
        documentDefaultsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,280F));
        documentDefaults.Controls.Add(documentDefaultsLayout);
        lblDefaultCurrency.Text = "العملة";
        lblDefaultCurrency.AutoSize = true;
        cboDefaultCurrency.Dock = DockStyle.Fill;
        cboDefaultCurrency.DropDownStyle = ComboBoxStyle.DropDownList;
        cboDefaultCurrency.Enabled = false;
        cboDefaultCurrency.AccessibleDescription = "تحتاج ربط قوائم القيم وتطبيقها على التفاصيل";
        documentDefaultsLayout.Controls.Add(lblDefaultCurrency,0,0);
        documentDefaultsLayout.Controls.Add(cboDefaultCurrency,1,0);
        lblDefaultCostCenter.Text = "مركز التكلفة";
        lblDefaultCostCenter.AutoSize = true;
        cboDefaultCostCenter.Dock = DockStyle.Fill;
        cboDefaultCostCenter.DropDownStyle = ComboBoxStyle.DropDownList;
        cboDefaultCostCenter.Enabled = false;
        cboDefaultCostCenter.AccessibleDescription = "تحتاج ربط قوائم القيم وتطبيقها على التفاصيل";
        documentDefaultsLayout.Controls.Add(lblDefaultCostCenter,0,1);
        documentDefaultsLayout.Controls.Add(cboDefaultCostCenter,1,1);
        tabs.Controls.Add(documentDefaults);
        documentAccounts.Name = "documentAccounts";
        documentAccounts.Text = "الحسابات";
        documentAccounts.AutoScroll = true;
        documentAccountsGrid.Name = "documentAccountsGrid";
        documentAccountsGrid.Dock = DockStyle.Fill;
        documentAccountsGrid.ReadOnly = true;
        documentAccountsGrid.AllowUserToAddRows = false;
        documentAccountsGrid.AllowUserToDeleteRows = false;
        documentAccountsGrid.RightToLeft = RightToLeft.Yes;
        documentAccountsGrid.BackgroundColor = Color.White;
        documentAccountsGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        documentAccountsGrid.EnableHeadersVisualStyles = false;
        documentAccountsGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(232,232,232);
        documentAccountsGrid.DefaultCellStyle.BackColor = Color.FromArgb(255,255,226);
        documentAccounts.Controls.Add(documentAccountsGrid);
        documentAccountsGridColumn0.Name = "documentAccountsGridColumn0";
        documentAccountsGridColumn0.HeaderText = "رقم الحساب";
        documentAccountsGrid.Columns.Add(documentAccountsGridColumn0);
        documentAccountsGridColumn1.Name = "documentAccountsGridColumn1";
        documentAccountsGridColumn1.HeaderText = "الحساب التحليلي";
        documentAccountsGrid.Columns.Add(documentAccountsGridColumn1);
        documentAccountsGridColumn2.Name = "documentAccountsGridColumn2";
        documentAccountsGridColumn2.HeaderText = "اسم الحساب";
        documentAccountsGrid.Columns.Add(documentAccountsGridColumn2);
        documentAccountsGridColumn3.Name = "documentAccountsGridColumn3";
        documentAccountsGridColumn3.HeaderText = "البيان";
        documentAccountsGrid.Columns.Add(documentAccountsGridColumn3);
        documentAccountsGridColumn4.Name = "documentAccountsGridColumn4";
        documentAccountsGridColumn4.HeaderText = "العملة";
        documentAccountsGrid.Columns.Add(documentAccountsGridColumn4);
        documentAccountsGridColumn5.Name = "documentAccountsGridColumn5";
        documentAccountsGridColumn5.HeaderText = "سعر التحويل";
        documentAccountsGrid.Columns.Add(documentAccountsGridColumn5);
        documentAccountsGridColumn6.Name = "documentAccountsGridColumn6";
        documentAccountsGridColumn6.HeaderText = "المبلغ المحلي";
        documentAccountsGrid.Columns.Add(documentAccountsGridColumn6);
        documentAccountsGridColumn7.Name = "documentAccountsGridColumn7";
        documentAccountsGridColumn7.HeaderText = "المبلغ الأجنبي";
        documentAccountsGrid.Columns.Add(documentAccountsGridColumn7);
        documentAccountsGrid.AccessibleDescription = "الحسابات المتعددة؛ ربط خدمة السند والصلاحيات غير مكتمل";
        tabs.Controls.Add(documentAccounts);
        tabs.Controls.Clear();
        tabs.Controls.Add(tp0);
        tabs.Controls.Add(documentAccounts);
        tabs.Controls.Add(documentAdditional);
        tabs.Controls.Add(documentDefaults);
        tabs.Controls.Add(tp5);
        tabs.SelectedIndex = 0;

        // Engineering correction: common toolbar and compact workspace bounds.
        btnSave.AutoSize = false;
        btnSave.MinimumSize = new Size(132,36);
        btnSave.Size = new Size(132,36);
        btnSave.Margin = new Padding(3);
        btnApprove.AutoSize = false;
        btnApprove.MinimumSize = new Size(132,36);
        btnApprove.Size = new Size(132,36);
        btnApprove.Margin = new Padding(3);
        btnClear.AutoSize = false;
        btnClear.MinimumSize = new Size(132,36);
        btnClear.Size = new Size(132,36);
        btnClear.Margin = new Padding(3);
        btnClose.AutoSize = false;
        btnClose.MinimumSize = new Size(132,36);
        btnClose.Size = new Size(132,36);
        btnClose.Margin = new Padding(3);
        btnAddRow.AutoSize = false;
        btnAddRow.MinimumSize = new Size(132,36);
        btnAddRow.Size = new Size(132,36);
        btnAddRow.Margin = new Padding(3);
        btnRemoveRow.AutoSize = false;
        btnRemoveRow.MinimumSize = new Size(132,36);
        btnRemoveRow.Size = new Size(132,36);
        btnRemoveRow.Margin = new Padding(3);
        referencePrint.AutoSize = false;
        referencePrint.MinimumSize = new Size(132,36);
        referencePrint.Size = new Size(132,36);
        referencePrint.Margin = new Padding(3);
        mainLayout.MinimumSize = new Size(980,680);
        dgvLines.MinimumSize = new Size(900,80);
        mainLayout.RowStyles[5].Height = 36F;
        flpActions.FlowDirection = FlowDirection.LeftToRight;
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Fill;
        designerCommandBar.RightToLeft = RightToLeft.Yes;
        designerCommandBar.Controls.Add(flpActions);
        flpActions.Dock = DockStyle.Fill;
        flpActions.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        flpActions.Name = "flpActions";
        flpActions.Dock = DockStyle.Fill;
        flpActions.AutoSize = false;
        flpActions.WrapContents = false;
        flpActions.FlowDirection = FlowDirection.RightToLeft;
        flpActions.RightToLeft = RightToLeft.No;
        flpActions.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 44;
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = true;
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = true;
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandView.Name = "standardCommandView";
        standardCommandView.Enabled = false;
        standardCommandView.Visible = true;
        standardCommandView.AccessibleName = "عرض";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandAdd.AutoSize = false;
        standardCommandAdd.Dock = DockStyle.None;
        standardCommandAdd.MinimumSize = Size.Empty;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandAdd.Text = "";
        flpActions.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.AutoSize = false;
        standardCommandEdit.Dock = DockStyle.None;
        standardCommandEdit.MinimumSize = Size.Empty;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandEdit.Text = "";
        flpActions.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        flpActions.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.AutoSize = false;
        standardCommandCancel.Dock = DockStyle.None;
        standardCommandCancel.MinimumSize = Size.Empty;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandCancel.Text = "";
        flpActions.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        standardCommandView.AutoSize = false;
        standardCommandView.Dock = DockStyle.None;
        standardCommandView.MinimumSize = Size.Empty;
        standardCommandView.Size = new Size(26, 24);
        standardCommandView.Margin = new Padding(1);
        standardCommandView.FlatStyle = FlatStyle.Flat;
        standardCommandView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        standardCommandView.Text = "";
        flpActions.Controls.Add(standardCommandView);
        designerCommandBar.SetCommandRole(standardCommandView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        flpActions.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        flpActions.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        flpActions.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        flpActions.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        btnSave.AutoSize = false;
        btnSave.Dock = DockStyle.None;
        btnSave.MinimumSize = Size.Empty;
        btnSave.Size = new Size(26, 24);
        btnSave.Margin = new Padding(1);
        btnSave.FlatStyle = FlatStyle.Flat;
        btnSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        btnSave.Text = "";
        flpActions.Controls.Add(btnSave);
        designerCommandBar.SetCommandRole(btnSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        referencePrint.AutoSize = false;
        referencePrint.Dock = DockStyle.None;
        referencePrint.MinimumSize = Size.Empty;
        referencePrint.Size = new Size(26, 24);
        referencePrint.Margin = new Padding(1);
        referencePrint.FlatStyle = FlatStyle.Flat;
        referencePrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        referencePrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        referencePrint.Text = "";
        flpActions.Controls.Add(referencePrint);
        designerCommandBar.SetCommandRole(referencePrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        btnClose.AutoSize = false;
        btnClose.Dock = DockStyle.None;
        btnClose.MinimumSize = Size.Empty;
        btnClose.Size = new Size(26, 24);
        btnClose.Margin = new Padding(1);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        btnClose.Text = "";
        designerCloseHost.Controls.Add(btnClose);
        btnClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        flpActions.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        flpActions.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        flpActions.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        flpActions.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        referenceAudit.Visible = false;
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}
}
