using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcOnyxSCREEN0102
{
    private AuditMetadataControl standardAuditMetadata = null!;
    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private TableLayoutPanel filterLayout = null!;
    private TableLayoutPanel selectionFields = null!;
    private Label lblDateFrom = null!;
    private TextBox txtDateFrom = null!;
    private Label lblDateTo = null!;
    private TextBox txtDateTo = null!;
    private Label lblBankFrom = null!;
    private TextBox txtBankFrom = null!;
    private Label lblBankTo = null!;
    private TextBox txtBankTo = null!;
    private Label lblVoucherFrom = null!;
    private TextBox txtVoucherFrom = null!;
    private Label lblVoucherTo = null!;
    private TextBox txtVoucherTo = null!;
    private Label lblAmountFrom = null!;
    private TextBox txtAmountFrom = null!;
    private Label lblAmountTo = null!;
    private TextBox txtAmountTo = null!;
    private Label lblAccountFrom = null!;
    private TextBox txtAccountFrom = null!;
    private Label lblAccountTo = null!;
    private TextBox txtAccountTo = null!;
    private Label lblCustomerFrom = null!;
    private TextBox txtCustomerFrom = null!;
    private Label lblCustomerTo = null!;
    private TextBox txtCustomerTo = null!;
    private Label lblSupplierFrom = null!;
    private TextBox txtSupplierFrom = null!;
    private Label lblSupplierTo = null!;
    private TextBox txtSupplierTo = null!;
    private Label lblRecipient = null!;
    private TextBox txtRecipient = null!;
    private Button btnView = null!;
    private TableLayoutPanel displayFields = null!;
    private Label lblSort = null!;
    private ComboBox cmbSort = null!;
    private Label lblBranch = null!;
    private ComboBox cmbBranch = null!;
    private Label lblStatus = null!;
    private ComboBox cmbStatus = null!;
    private DataGridView gridDeposits = null!;
    private DataGridViewTextBoxColumn colVoucher = null!;
    private DataGridViewTextBoxColumn colDocumentDate = null!;
    private DataGridViewTextBoxColumn colAccount = null!;
    private DataGridViewTextBoxColumn colAccountName = null!;
    private DataGridViewTextBoxColumn colLocalAmount = null!;
    private DataGridViewTextBoxColumn colForeignAmount = null!;
    private DataGridViewTextBoxColumn colCurrency = null!;
    private DataGridViewTextBoxColumn colDueDate = null!;
    private DataGridViewCheckBoxColumn colSelected = null!;
    private DataGridViewComboBoxColumn colStatus = null!;
    private DataGridViewTextBoxColumn colReason = null!;
    private TableLayoutPanel accountDetails = null!;
    private Label lblAnalyticalType = null!;
    private TextBox txtAnalyticalType = null!;
    private Label lblAnalyticalAccount = null!;
    private TextBox txtAnalyticalAccount = null!;
    private Label lblCostCenter = null!;
    private TextBox txtCostCenter = null!;
    private Panel auditFooter = null!;
    private Label lblOperationStatus = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 7;
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = new Padding(2);
        mainLayout.Padding = new Padding(2);
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        mainLayout.RowStyles.Clear();
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 169F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "تحقيق الإيداع النقدي لدى البنوك";
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.Margin = new Padding(1);
        lblTitle.AutoSize = false;
        mainLayout.Controls.Add(lblTitle, 0, 0);
        lblTitle.BackColor = Color.FromArgb(23, 50, 78);
        lblTitle.ForeColor = Color.White;
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        commandBar.Dock = DockStyle.Fill;
        commandBar.Margin = Padding.Empty;
        mainLayout.Controls.Add(commandBar, 0, 1);
        filterLayout = new TableLayoutPanel();
        filterLayout.Name = "filterLayout";
        filterLayout.ColumnCount = 2;
        filterLayout.RowCount = 1;
        filterLayout.Dock = DockStyle.Fill;
        filterLayout.Margin = new Padding(2);
        filterLayout.Padding = new Padding(2);
        filterLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 72F));
        filterLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 28F));
        filterLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        filterLayout.RowStyles[0].SizeType = SizeType.Percent;
        filterLayout.RowStyles[0].Height = 100F;
        mainLayout.Controls.Add(filterLayout, 0, 2);
        selectionFields = new TableLayoutPanel();
        selectionFields.Name = "selectionFields";
        selectionFields.ColumnCount = 8;
        selectionFields.RowCount = 5;
        selectionFields.Dock = DockStyle.Fill;
        selectionFields.Margin = new Padding(2);
        selectionFields.Padding = new Padding(2);
        selectionFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 88F));
        selectionFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
        selectionFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 30F));
        selectionFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
        selectionFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 80F));
        selectionFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
        selectionFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 30F));
        selectionFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
        selectionFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        selectionFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        selectionFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        selectionFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        selectionFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        selectionFields.CellBorderStyle = TableLayoutPanelCellBorderStyle.None;
        selectionFields.BorderStyle = BorderStyle.FixedSingle;
        selectionFields.BackColor = Color.FromArgb(244,244,244);
        filterLayout.Controls.Add(selectionFields, 0, 0);
        lblDateFrom = new Label();
        lblDateFrom.Name = "lblDateFrom";
        lblDateFrom.Text = "من تاريخ";
        lblDateFrom.Dock = DockStyle.Fill;
        lblDateFrom.TextAlign = ContentAlignment.MiddleRight;
        lblDateFrom.Margin = new Padding(1);
        lblDateFrom.AutoSize = false;
        selectionFields.Controls.Add(lblDateFrom, 0, 0);
        txtDateFrom = new TextBox();
        txtDateFrom.Name = "txtDateFrom";
        txtDateFrom.Dock = DockStyle.Fill;
        txtDateFrom.Margin = new Padding(2);
        txtDateFrom.AccessibleName = "من تاريخ";
        txtDateFrom.RightToLeft = RightToLeft.No;
        txtDateFrom.ReadOnly = false;
        selectionFields.Controls.Add(txtDateFrom, 1, 0);
        lblDateTo = new Label();
        lblDateTo.Name = "lblDateTo";
        lblDateTo.Text = "إلى";
        lblDateTo.Dock = DockStyle.Fill;
        lblDateTo.TextAlign = ContentAlignment.MiddleRight;
        lblDateTo.Margin = new Padding(1);
        lblDateTo.AutoSize = false;
        selectionFields.Controls.Add(lblDateTo, 2, 0);
        txtDateTo = new TextBox();
        txtDateTo.Name = "txtDateTo";
        txtDateTo.Dock = DockStyle.Fill;
        txtDateTo.Margin = new Padding(2);
        txtDateTo.AccessibleName = "من تاريخ إلى";
        txtDateTo.RightToLeft = RightToLeft.No;
        txtDateTo.ReadOnly = false;
        selectionFields.Controls.Add(txtDateTo, 3, 0);
        lblBankFrom = new Label();
        lblBankFrom.Name = "lblBankFrom";
        lblBankFrom.Text = "رقم البنك";
        lblBankFrom.Dock = DockStyle.Fill;
        lblBankFrom.TextAlign = ContentAlignment.MiddleRight;
        lblBankFrom.Margin = new Padding(1);
        lblBankFrom.AutoSize = false;
        selectionFields.Controls.Add(lblBankFrom, 0, 1);
        txtBankFrom = new TextBox();
        txtBankFrom.Name = "txtBankFrom";
        txtBankFrom.Dock = DockStyle.Fill;
        txtBankFrom.Margin = new Padding(2);
        txtBankFrom.AccessibleName = "رقم البنك";
        txtBankFrom.RightToLeft = RightToLeft.No;
        txtBankFrom.ReadOnly = false;
        selectionFields.Controls.Add(txtBankFrom, 1, 1);
        lblBankTo = new Label();
        lblBankTo.Name = "lblBankTo";
        lblBankTo.Text = "إلى";
        lblBankTo.Dock = DockStyle.Fill;
        lblBankTo.TextAlign = ContentAlignment.MiddleRight;
        lblBankTo.Margin = new Padding(1);
        lblBankTo.AutoSize = false;
        selectionFields.Controls.Add(lblBankTo, 2, 1);
        txtBankTo = new TextBox();
        txtBankTo.Name = "txtBankTo";
        txtBankTo.Dock = DockStyle.Fill;
        txtBankTo.Margin = new Padding(2);
        txtBankTo.AccessibleName = "رقم البنك إلى";
        txtBankTo.RightToLeft = RightToLeft.No;
        txtBankTo.ReadOnly = false;
        selectionFields.Controls.Add(txtBankTo, 3, 1);
        lblVoucherFrom = new Label();
        lblVoucherFrom.Name = "lblVoucherFrom";
        lblVoucherFrom.Text = "من سند رقم";
        lblVoucherFrom.Dock = DockStyle.Fill;
        lblVoucherFrom.TextAlign = ContentAlignment.MiddleRight;
        lblVoucherFrom.Margin = new Padding(1);
        lblVoucherFrom.AutoSize = false;
        selectionFields.Controls.Add(lblVoucherFrom, 0, 3);
        txtVoucherFrom = new TextBox();
        txtVoucherFrom.Name = "txtVoucherFrom";
        txtVoucherFrom.Dock = DockStyle.Fill;
        txtVoucherFrom.Margin = new Padding(2);
        txtVoucherFrom.AccessibleName = "من سند رقم";
        txtVoucherFrom.RightToLeft = RightToLeft.No;
        txtVoucherFrom.ReadOnly = false;
        selectionFields.Controls.Add(txtVoucherFrom, 1, 3);
        lblVoucherTo = new Label();
        lblVoucherTo.Name = "lblVoucherTo";
        lblVoucherTo.Text = "إلى";
        lblVoucherTo.Dock = DockStyle.Fill;
        lblVoucherTo.TextAlign = ContentAlignment.MiddleRight;
        lblVoucherTo.Margin = new Padding(1);
        lblVoucherTo.AutoSize = false;
        selectionFields.Controls.Add(lblVoucherTo, 2, 3);
        txtVoucherTo = new TextBox();
        txtVoucherTo.Name = "txtVoucherTo";
        txtVoucherTo.Dock = DockStyle.Fill;
        txtVoucherTo.Margin = new Padding(2);
        txtVoucherTo.AccessibleName = "من سند رقم إلى";
        txtVoucherTo.RightToLeft = RightToLeft.No;
        txtVoucherTo.ReadOnly = false;
        selectionFields.Controls.Add(txtVoucherTo, 3, 3);
        lblAmountFrom = new Label();
        lblAmountFrom.Name = "lblAmountFrom";
        lblAmountFrom.Text = "المبلغ";
        lblAmountFrom.Dock = DockStyle.Fill;
        lblAmountFrom.TextAlign = ContentAlignment.MiddleRight;
        lblAmountFrom.Margin = new Padding(1);
        lblAmountFrom.AutoSize = false;
        selectionFields.Controls.Add(lblAmountFrom, 0, 4);
        txtAmountFrom = new TextBox();
        txtAmountFrom.Name = "txtAmountFrom";
        txtAmountFrom.Dock = DockStyle.Fill;
        txtAmountFrom.Margin = new Padding(2);
        txtAmountFrom.AccessibleName = "المبلغ";
        txtAmountFrom.RightToLeft = RightToLeft.No;
        txtAmountFrom.ReadOnly = false;
        selectionFields.Controls.Add(txtAmountFrom, 1, 4);
        lblAmountTo = new Label();
        lblAmountTo.Name = "lblAmountTo";
        lblAmountTo.Text = "إلى";
        lblAmountTo.Dock = DockStyle.Fill;
        lblAmountTo.TextAlign = ContentAlignment.MiddleRight;
        lblAmountTo.Margin = new Padding(1);
        lblAmountTo.AutoSize = false;
        selectionFields.Controls.Add(lblAmountTo, 2, 4);
        txtAmountTo = new TextBox();
        txtAmountTo.Name = "txtAmountTo";
        txtAmountTo.Dock = DockStyle.Fill;
        txtAmountTo.Margin = new Padding(2);
        txtAmountTo.AccessibleName = "المبلغ إلى";
        txtAmountTo.RightToLeft = RightToLeft.No;
        txtAmountTo.ReadOnly = false;
        selectionFields.Controls.Add(txtAmountTo, 3, 4);
        lblAccountFrom = new Label();
        lblAccountFrom.Name = "lblAccountFrom";
        lblAccountFrom.Text = "من حساب";
        lblAccountFrom.Dock = DockStyle.Fill;
        lblAccountFrom.TextAlign = ContentAlignment.MiddleRight;
        lblAccountFrom.Margin = new Padding(1);
        lblAccountFrom.AutoSize = false;
        selectionFields.Controls.Add(lblAccountFrom, 4, 0);
        txtAccountFrom = new TextBox();
        txtAccountFrom.Name = "txtAccountFrom";
        txtAccountFrom.Dock = DockStyle.Fill;
        txtAccountFrom.Margin = new Padding(2);
        txtAccountFrom.AccessibleName = "من حساب";
        txtAccountFrom.RightToLeft = RightToLeft.No;
        txtAccountFrom.ReadOnly = false;
        selectionFields.Controls.Add(txtAccountFrom, 5, 0);
        lblAccountTo = new Label();
        lblAccountTo.Name = "lblAccountTo";
        lblAccountTo.Text = "إلى";
        lblAccountTo.Dock = DockStyle.Fill;
        lblAccountTo.TextAlign = ContentAlignment.MiddleRight;
        lblAccountTo.Margin = new Padding(1);
        lblAccountTo.AutoSize = false;
        selectionFields.Controls.Add(lblAccountTo, 6, 0);
        txtAccountTo = new TextBox();
        txtAccountTo.Name = "txtAccountTo";
        txtAccountTo.Dock = DockStyle.Fill;
        txtAccountTo.Margin = new Padding(2);
        txtAccountTo.AccessibleName = "من حساب إلى";
        txtAccountTo.RightToLeft = RightToLeft.No;
        txtAccountTo.ReadOnly = false;
        selectionFields.Controls.Add(txtAccountTo, 7, 0);
        lblCustomerFrom = new Label();
        lblCustomerFrom.Name = "lblCustomerFrom";
        lblCustomerFrom.Text = "رقم العميل";
        lblCustomerFrom.Dock = DockStyle.Fill;
        lblCustomerFrom.TextAlign = ContentAlignment.MiddleRight;
        lblCustomerFrom.Margin = new Padding(1);
        lblCustomerFrom.AutoSize = false;
        selectionFields.Controls.Add(lblCustomerFrom, 4, 1);
        txtCustomerFrom = new TextBox();
        txtCustomerFrom.Name = "txtCustomerFrom";
        txtCustomerFrom.Dock = DockStyle.Fill;
        txtCustomerFrom.Margin = new Padding(2);
        txtCustomerFrom.AccessibleName = "رقم العميل";
        txtCustomerFrom.RightToLeft = RightToLeft.No;
        txtCustomerFrom.ReadOnly = false;
        selectionFields.Controls.Add(txtCustomerFrom, 5, 1);
        lblCustomerTo = new Label();
        lblCustomerTo.Name = "lblCustomerTo";
        lblCustomerTo.Text = "إلى";
        lblCustomerTo.Dock = DockStyle.Fill;
        lblCustomerTo.TextAlign = ContentAlignment.MiddleRight;
        lblCustomerTo.Margin = new Padding(1);
        lblCustomerTo.AutoSize = false;
        selectionFields.Controls.Add(lblCustomerTo, 6, 1);
        txtCustomerTo = new TextBox();
        txtCustomerTo.Name = "txtCustomerTo";
        txtCustomerTo.Dock = DockStyle.Fill;
        txtCustomerTo.Margin = new Padding(2);
        txtCustomerTo.AccessibleName = "رقم العميل إلى";
        txtCustomerTo.RightToLeft = RightToLeft.No;
        txtCustomerTo.ReadOnly = false;
        selectionFields.Controls.Add(txtCustomerTo, 7, 1);
        lblSupplierFrom = new Label();
        lblSupplierFrom.Name = "lblSupplierFrom";
        lblSupplierFrom.Text = "رقم المورد";
        lblSupplierFrom.Dock = DockStyle.Fill;
        lblSupplierFrom.TextAlign = ContentAlignment.MiddleRight;
        lblSupplierFrom.Margin = new Padding(1);
        lblSupplierFrom.AutoSize = false;
        selectionFields.Controls.Add(lblSupplierFrom, 4, 2);
        txtSupplierFrom = new TextBox();
        txtSupplierFrom.Name = "txtSupplierFrom";
        txtSupplierFrom.Dock = DockStyle.Fill;
        txtSupplierFrom.Margin = new Padding(2);
        txtSupplierFrom.AccessibleName = "رقم المورد";
        txtSupplierFrom.RightToLeft = RightToLeft.No;
        txtSupplierFrom.ReadOnly = false;
        selectionFields.Controls.Add(txtSupplierFrom, 5, 2);
        lblSupplierTo = new Label();
        lblSupplierTo.Name = "lblSupplierTo";
        lblSupplierTo.Text = "إلى";
        lblSupplierTo.Dock = DockStyle.Fill;
        lblSupplierTo.TextAlign = ContentAlignment.MiddleRight;
        lblSupplierTo.Margin = new Padding(1);
        lblSupplierTo.AutoSize = false;
        selectionFields.Controls.Add(lblSupplierTo, 6, 2);
        txtSupplierTo = new TextBox();
        txtSupplierTo.Name = "txtSupplierTo";
        txtSupplierTo.Dock = DockStyle.Fill;
        txtSupplierTo.Margin = new Padding(2);
        txtSupplierTo.AccessibleName = "رقم المورد إلى";
        txtSupplierTo.RightToLeft = RightToLeft.No;
        txtSupplierTo.ReadOnly = false;
        selectionFields.Controls.Add(txtSupplierTo, 7, 2);
        lblRecipient = new Label();
        lblRecipient.Name = "lblRecipient";
        lblRecipient.Text = "اسم المستلم";
        lblRecipient.Dock = DockStyle.Fill;
        lblRecipient.TextAlign = ContentAlignment.MiddleRight;
        lblRecipient.Margin = new Padding(1);
        lblRecipient.AutoSize = false;
        selectionFields.Controls.Add(lblRecipient, 4, 4);
        txtRecipient = new TextBox();
        txtRecipient.Name = "txtRecipient";
        txtRecipient.Dock = DockStyle.Fill;
        txtRecipient.Margin = new Padding(2);
        txtRecipient.AccessibleName = "اسم المستلم";
        txtRecipient.RightToLeft = RightToLeft.No;
        txtRecipient.ReadOnly = false;
        selectionFields.Controls.Add(txtRecipient, 5, 4);
        txtRecipient.RightToLeft = RightToLeft.Yes;
        txtRecipient.BackColor = Color.LightCyan;
        selectionFields.SetColumnSpan(txtRecipient, 3);
        btnView = new Button();
        btnView.Name = "btnView";
        btnView.Text = "عرض";
        btnView.Dock = DockStyle.Fill;
        btnView.Margin = new Padding(2);
        selectionFields.Controls.Add(btnView, 4, 3);
        selectionFields.SetColumnSpan(btnView, 4);
        btnView.Click += BtnView_Click;
        displayFields = new TableLayoutPanel();
        displayFields.Name = "displayFields";
        displayFields.ColumnCount = 2;
        displayFields.RowCount = 3;
        displayFields.Dock = DockStyle.Top;
        displayFields.Height = 98;
        displayFields.BorderStyle = BorderStyle.FixedSingle;
        displayFields.Margin = new Padding(2);
        displayFields.Padding = new Padding(2);
        displayFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 84F));
        displayFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        displayFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        displayFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        displayFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        filterLayout.Controls.Add(displayFields, 1, 0);
        lblSort = new Label();
        lblSort.Name = "lblSort";
        lblSort.Text = "الترتيب حسب";
        lblSort.Dock = DockStyle.Fill;
        lblSort.TextAlign = ContentAlignment.MiddleRight;
        lblSort.Margin = new Padding(1);
        lblSort.AutoSize = false;
        displayFields.Controls.Add(lblSort, 0, 0);
        cmbSort = new ComboBox();
        cmbSort.Name = "cmbSort";
        cmbSort.Dock = DockStyle.Fill;
        cmbSort.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbSort.Margin = new Padding(2);
        cmbSort.AccessibleName = "الترتيب حسب";
        displayFields.Controls.Add(cmbSort, 1, 0);
        lblBranch = new Label();
        lblBranch.Name = "lblBranch";
        lblBranch.Text = "الفرع";
        lblBranch.Dock = DockStyle.Fill;
        lblBranch.TextAlign = ContentAlignment.MiddleRight;
        lblBranch.Margin = new Padding(1);
        lblBranch.AutoSize = false;
        displayFields.Controls.Add(lblBranch, 0, 1);
        cmbBranch = new ComboBox();
        cmbBranch.Name = "cmbBranch";
        cmbBranch.Dock = DockStyle.Fill;
        cmbBranch.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbBranch.Margin = new Padding(2);
        cmbBranch.AccessibleName = "الفرع";
        cmbBranch.Items.AddRange(new object[] { "كلي" });
        displayFields.Controls.Add(cmbBranch, 1, 1);
        lblStatus = new Label();
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "الاستحقاق";
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.TextAlign = ContentAlignment.MiddleRight;
        lblStatus.Margin = new Padding(1);
        lblStatus.AutoSize = false;
        displayFields.Controls.Add(lblStatus, 0, 2);
        cmbStatus = new ComboBox();
        cmbStatus.Name = "cmbStatus";
        cmbStatus.Dock = DockStyle.Fill;
        cmbStatus.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbStatus.Margin = new Padding(2);
        cmbStatus.AccessibleName = "الاستحقاق";
        cmbStatus.Items.AddRange(new object[] { "تحت التحصيل", "مستحق", "مرتجع" });
        displayFields.Controls.Add(cmbStatus, 1, 2);
        gridDeposits = new DataGridView();
        gridDeposits.Name = "gridDeposits";
        gridDeposits.Dock = DockStyle.Fill;
        gridDeposits.AllowUserToAddRows = false;
        gridDeposits.AllowUserToDeleteRows = false;
        gridDeposits.AllowUserToOrderColumns = false;
        gridDeposits.AutoGenerateColumns = false;
        gridDeposits.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        gridDeposits.ReadOnly = true;
        gridDeposits.RowHeadersVisible = false;
        gridDeposits.BackgroundColor = Color.White;
        gridDeposits.BorderStyle = BorderStyle.FixedSingle;
        gridDeposits.ColumnHeadersHeight = 32;
        gridDeposits.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridDeposits.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        gridDeposits.MultiSelect = false;
        gridDeposits.AccessibleName = "بيانات عمليات الإيداع";
        colVoucher = new DataGridViewTextBoxColumn();
        colVoucher.Name = "colVoucher";
        colVoucher.HeaderText = "رقم السند";
        colVoucher.DataPropertyName = "Voucher";
        colVoucher.Width = 85;
        colVoucher.FillWeight = 85F;
        colVoucher.MinimumWidth = 70;
        colVoucher.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridDeposits.Columns.Add(colVoucher);
        colDocumentDate = new DataGridViewTextBoxColumn();
        colDocumentDate.Name = "colDocumentDate";
        colDocumentDate.HeaderText = "تاريخ المستند";
        colDocumentDate.DataPropertyName = "DocumentDate";
        colDocumentDate.Width = 95;
        colDocumentDate.FillWeight = 95F;
        colDocumentDate.MinimumWidth = 70;
        colDocumentDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridDeposits.Columns.Add(colDocumentDate);
        colAccount = new DataGridViewTextBoxColumn();
        colAccount.Name = "colAccount";
        colAccount.HeaderText = "رقم الحساب";
        colAccount.DataPropertyName = "Account";
        colAccount.Width = 100;
        colAccount.FillWeight = 100F;
        colAccount.MinimumWidth = 70;
        colAccount.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridDeposits.Columns.Add(colAccount);
        colAccountName = new DataGridViewTextBoxColumn();
        colAccountName.Name = "colAccountName";
        colAccountName.HeaderText = "اسم الحساب";
        colAccountName.DataPropertyName = "AccountName";
        colAccountName.Width = 165;
        colAccountName.FillWeight = 165F;
        colAccountName.MinimumWidth = 70;
        colAccountName.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridDeposits.Columns.Add(colAccountName);
        colLocalAmount = new DataGridViewTextBoxColumn();
        colLocalAmount.Name = "colLocalAmount";
        colLocalAmount.HeaderText = "المبلغ المحلي";
        colLocalAmount.DataPropertyName = "LocalAmount";
        colLocalAmount.Width = 105;
        colLocalAmount.FillWeight = 105F;
        colLocalAmount.MinimumWidth = 70;
        colLocalAmount.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridDeposits.Columns.Add(colLocalAmount);
        colForeignAmount = new DataGridViewTextBoxColumn();
        colForeignAmount.Name = "colForeignAmount";
        colForeignAmount.HeaderText = "المبلغ الأجنبي";
        colForeignAmount.DataPropertyName = "ForeignAmount";
        colForeignAmount.Width = 105;
        colForeignAmount.FillWeight = 105F;
        colForeignAmount.MinimumWidth = 70;
        colForeignAmount.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridDeposits.Columns.Add(colForeignAmount);
        colCurrency = new DataGridViewTextBoxColumn();
        colCurrency.Name = "colCurrency";
        colCurrency.HeaderText = "العملة";
        colCurrency.DataPropertyName = "Currency";
        colCurrency.Width = 62;
        colCurrency.FillWeight = 62F;
        colCurrency.MinimumWidth = 62;
        colCurrency.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridDeposits.Columns.Add(colCurrency);
        colDueDate = new DataGridViewTextBoxColumn();
        colDueDate.Name = "colDueDate";
        colDueDate.HeaderText = "تاريخ الاستحقاق";
        colDueDate.DataPropertyName = "DueDate";
        colDueDate.Width = 105;
        colDueDate.FillWeight = 105F;
        colDueDate.MinimumWidth = 70;
        colDueDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridDeposits.Columns.Add(colDueDate);
        colSelected = new DataGridViewCheckBoxColumn();
        colSelected.Name = "colSelected";
        colSelected.HeaderText = "";
        colSelected.DataPropertyName = "Selected";
        colSelected.Width = 28;
        colSelected.FillWeight = 28F;
        colSelected.MinimumWidth = 28;
        colSelected.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridDeposits.Columns.Add(colSelected);
        colStatus = new DataGridViewComboBoxColumn();
        colStatus.Name = "colStatus";
        colStatus.HeaderText = "الاستحقاق";
        colStatus.DataPropertyName = "Status";
        colStatus.Width = 105;
        colStatus.FillWeight = 105F;
        colStatus.MinimumWidth = 70;
        colStatus.SortMode = DataGridViewColumnSortMode.NotSortable;
        colStatus.Items.AddRange(new object[] { "تحت التحصيل", "مستحق", "مرتجع" });
        gridDeposits.Columns.Add(colStatus);
        colReason = new DataGridViewTextBoxColumn();
        colReason.Name = "colReason";
        colReason.HeaderText = "السبب";
        colReason.DataPropertyName = "Reason";
        colReason.Width = 145;
        colReason.FillWeight = 145F;
        colReason.MinimumWidth = 70;
        colReason.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridDeposits.Columns.Add(colReason);
        mainLayout.Controls.Add(gridDeposits, 0, 3);
        accountDetails = new TableLayoutPanel();
        accountDetails.Name = "accountDetails";
        accountDetails.ColumnCount = 6;
        accountDetails.RowCount = 1;
        accountDetails.Dock = DockStyle.Fill;
        accountDetails.Margin = new Padding(2);
        accountDetails.Padding = new Padding(2);
        accountDetails.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 130F));
        accountDetails.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33F));
        accountDetails.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 115F));
        accountDetails.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 34F));
        accountDetails.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 90F));
        accountDetails.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33F));
        accountDetails.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        lblAnalyticalType = new Label();
        lblAnalyticalType.Name = "lblAnalyticalType";
        lblAnalyticalType.Text = "نوع الحساب التحليلي";
        lblAnalyticalType.Dock = DockStyle.Fill;
        lblAnalyticalType.TextAlign = ContentAlignment.MiddleRight;
        lblAnalyticalType.Margin = new Padding(1);
        lblAnalyticalType.AutoSize = false;
        accountDetails.Controls.Add(lblAnalyticalType, 0, 0);
        txtAnalyticalType = new TextBox();
        txtAnalyticalType.Name = "txtAnalyticalType";
        txtAnalyticalType.Dock = DockStyle.Fill;
        txtAnalyticalType.Margin = new Padding(2);
        txtAnalyticalType.AccessibleName = "نوع الحساب التحليلي";
        txtAnalyticalType.RightToLeft = RightToLeft.No;
        txtAnalyticalType.ReadOnly = true;
        txtAnalyticalType.BackColor = Color.LightCyan;
        accountDetails.Controls.Add(txtAnalyticalType, 1, 0);
        lblAnalyticalAccount = new Label();
        lblAnalyticalAccount.Name = "lblAnalyticalAccount";
        lblAnalyticalAccount.Text = "الحساب التحليلي";
        lblAnalyticalAccount.Dock = DockStyle.Fill;
        lblAnalyticalAccount.TextAlign = ContentAlignment.MiddleRight;
        lblAnalyticalAccount.Margin = new Padding(1);
        lblAnalyticalAccount.AutoSize = false;
        accountDetails.Controls.Add(lblAnalyticalAccount, 2, 0);
        txtAnalyticalAccount = new TextBox();
        txtAnalyticalAccount.Name = "txtAnalyticalAccount";
        txtAnalyticalAccount.Dock = DockStyle.Fill;
        txtAnalyticalAccount.Margin = new Padding(2);
        txtAnalyticalAccount.AccessibleName = "الحساب التحليلي";
        txtAnalyticalAccount.RightToLeft = RightToLeft.No;
        txtAnalyticalAccount.ReadOnly = true;
        txtAnalyticalAccount.BackColor = Color.LightCyan;
        accountDetails.Controls.Add(txtAnalyticalAccount, 3, 0);
        lblCostCenter = new Label();
        lblCostCenter.Name = "lblCostCenter";
        lblCostCenter.Text = "رقم المركز";
        lblCostCenter.Dock = DockStyle.Fill;
        lblCostCenter.TextAlign = ContentAlignment.MiddleRight;
        lblCostCenter.Margin = new Padding(1);
        lblCostCenter.AutoSize = false;
        accountDetails.Controls.Add(lblCostCenter, 4, 0);
        txtCostCenter = new TextBox();
        txtCostCenter.Name = "txtCostCenter";
        txtCostCenter.Dock = DockStyle.Fill;
        txtCostCenter.Margin = new Padding(2);
        txtCostCenter.AccessibleName = "رقم المركز";
        txtCostCenter.RightToLeft = RightToLeft.No;
        txtCostCenter.ReadOnly = true;
        txtCostCenter.BackColor = Color.LightCyan;
        accountDetails.Controls.Add(txtCostCenter, 5, 0);
        mainLayout.Controls.Add(accountDetails, 0, 4);
        auditFooter = new Panel();
        auditFooter.Name = "auditFooter";
        auditFooter.Dock = DockStyle.Fill;
        auditFooter.Margin = Padding.Empty;
        auditFooter.BackColor = Color.FromArgb(232,227,246);
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Fill;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.Profile = AuditMetadataProfile.Standard;
        auditFooter.Controls.Add(standardAuditMetadata);
        mainLayout.Controls.Add(auditFooter, 0, 5);
        lblOperationStatus = new Label();
        lblOperationStatus.Name = "lblOperationStatus";
        lblOperationStatus.Text = "لم يتم ربط مصدر عمليات الإيداع بهذه الشاشة بعد.";
        lblOperationStatus.Dock = DockStyle.Fill;
        lblOperationStatus.TextAlign = ContentAlignment.MiddleRight;
        lblOperationStatus.Margin = new Padding(1);
        lblOperationStatus.AutoSize = false;
        mainLayout.Controls.Add(lblOperationStatus, 0, 6);
        lblOperationStatus.AutoEllipsis = true;
        lblOperationStatus.BackColor = Color.FromArgb(244,244,244);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Tahoma", 9F);
        RightToLeft = RightToLeft.Yes;
        Name = "UcOnyxSCREEN0102";
        Text = "تحقيق الإيداع النقدي لدى البنوك";
        Size = new Size(1180, 720);
        MinimumSize = new Size(1040, 620);
        BackColor = Color.FromArgb(244,244,244);
        Controls.Add(mainLayout);
        ResumeLayout(false);
    }
}
