#nullable enable
using System.Drawing;
using System.Windows.Forms;
namespace TransportERP.EmptyForms;
partial class UcScreen_04_11_03
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandSave = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private FlowLayoutPanel flpActions = null!;
    private Button btnView = null!;
    private Button btnCreate = null!;
    private Button btnEdit = null!;
    private Button btnCancel = null!;
    private Button btnPost = null!;
    private Button btnReverse = null!;
    private Button btnClear = null!;
    private Button btnClose = null!;
    private TabControl tabs = null!;
    private Label lblStatus = null!;
    private TabPage tp0 = null!;
    private TableLayoutPanel layout0 = null!;
    private TextBox field_documentNumber = null!;
    private Label lbl_documentNumber = null!;
    private DateTimePicker field_accountingDate = null!;
    private Label lbl_accountingDate = null!;
    private TextBox field_reference = null!;
    private Label lbl_reference = null!;
    private TextBox field_description = null!;
    private Label lbl_description = null!;
    private ComboBox field_currencyRef = null!;
    private Label lbl_currencyRef = null!;
    private TextBox field_exchangeRate = null!;
    private Label lbl_exchangeRate = null!;
    private TextBox field_state = null!;
    private Label lbl_state = null!;
    private TabPage tp1 = null!;
    private TableLayoutPanel layout1 = null!;
    private DataGridView dgvLines = null!;
    private DataGridViewTextBoxColumn col_rowNo = null!;
    private DataGridViewComboBoxColumn col_accountRef = null!;
    private DataGridViewComboBoxColumn col_costCenterRef = null!;
    private DataGridViewTextBoxColumn col_lineDescription = null!;
    private DataGridViewTextBoxColumn col_debit = null!;
    private DataGridViewTextBoxColumn col_credit = null!;
    private DataGridViewComboBoxColumn col_currencyRef = null!;
    private DataGridViewTextBoxColumn col_exchangeRate = null!;
    private DataGridViewTextBoxColumn col_accountingAmount = null!;
    private TableLayoutPanel linesHost = null!;
    private FlowLayoutPanel lineActions = null!;
    private Button btnAddRow = null!;
    private Button btnRemoveRow = null!;
    private TabPage tp2 = null!;
    private TableLayoutPanel layout2 = null!;
    private RichTextBox context2 = null!;
    private TabPage tp3 = null!;
    private TableLayoutPanel layout3 = null!;
    private RichTextBox context3 = null!;
    private TabPage tp4 = null!;
    private TableLayoutPanel layout4 = null!;
    private RichTextBox context4 = null!;
    private System.ComponentModel.IContainer? components;
    private ErrorProvider validationErrors = null!;
    protected override void Dispose(bool disposing) { if(disposing) components?.Dispose(); base.Dispose(disposing); }
    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandDelete = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandSave = new Button();
        standardCommandPrint = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        components = new System.ComponentModel.Container();
        validationErrors = new ErrorProvider(components);
        validationErrors.ContainerControl = this;
        validationErrors.BlinkStyle = ErrorBlinkStyle.NeverBlink;
        mainLayout = new TableLayoutPanel();
        lblTitle = new Label();
        flpActions = new FlowLayoutPanel();
        btnView = new Button();
        btnCreate = new Button();
        btnEdit = new Button();
        btnCancel = new Button();
        btnPost = new Button();
        btnReverse = new Button();
        btnClear = new Button();
        btnClose = new Button();
        tabs = new TabControl();
        lblStatus = new Label();
        tp0 = new TabPage();
        layout0 = new TableLayoutPanel();
        field_documentNumber = new TextBox();
        lbl_documentNumber = new Label();
        field_accountingDate = new DateTimePicker();
        lbl_accountingDate = new Label();
        field_reference = new TextBox();
        lbl_reference = new Label();
        field_description = new TextBox();
        lbl_description = new Label();
        field_currencyRef = new ComboBox();
        lbl_currencyRef = new Label();
        field_exchangeRate = new TextBox();
        lbl_exchangeRate = new Label();
        field_state = new TextBox();
        lbl_state = new Label();
        tp1 = new TabPage();
        layout1 = new TableLayoutPanel();
        dgvLines = new DataGridView();
        col_rowNo = new DataGridViewTextBoxColumn();
        col_accountRef = new DataGridViewComboBoxColumn();
        col_costCenterRef = new DataGridViewComboBoxColumn();
        col_lineDescription = new DataGridViewTextBoxColumn();
        col_debit = new DataGridViewTextBoxColumn();
        col_credit = new DataGridViewTextBoxColumn();
        col_currencyRef = new DataGridViewComboBoxColumn();
        col_exchangeRate = new DataGridViewTextBoxColumn();
        col_accountingAmount = new DataGridViewTextBoxColumn();
        linesHost = new TableLayoutPanel();
        lineActions = new FlowLayoutPanel();
        btnAddRow = new Button();
        btnRemoveRow = new Button();
        tp2 = new TabPage();
        layout2 = new TableLayoutPanel();
        context2 = new RichTextBox();
        tp3 = new TabPage();
        layout3 = new TableLayoutPanel();
        context3 = new RichTextBox();
        tp4 = new TabPage();
        layout4 = new TableLayoutPanel();
        context4 = new RichTextBox();
        SuspendLayout();
        mainLayout.Name = "mainLayout";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "قيود التسوية والإقفال السنوي";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Padding = new Padding(8);
        lblTitle.TabStop = false;
        mainLayout.Controls.Add(lblTitle, 0, 0);
        flpActions.Name = "flpActions";
        flpActions.AutoSize = true;
        flpActions.Dock = DockStyle.Fill;
        flpActions.WrapContents = true;
        flpActions.FlowDirection = FlowDirection.LeftToRight;
        flpActions.RightToLeft = RightToLeft.Yes;
        mainLayout.Controls.Add(designerCommandBar, 0, 1);
        btnView.Name = "btnView";
        btnView.Text = "عرض / إعادة تحميل";
        btnView.AutoSize = true;
        btnView.MinimumSize = new Size(100,32);
        btnView.TabIndex = 0;
        btnView.AccessibleName = "عرض / إعادة تحميل";

        btnView.Enabled = false;
        btnCreate.Name = "btnCreate";
        btnCreate.Text = "حفظ جديد";
        btnCreate.AutoSize = true;
        btnCreate.MinimumSize = new Size(100,32);
        btnCreate.TabIndex = 1;
        btnCreate.AccessibleName = "حفظ جديد";
        flpActions.Controls.Add(btnCreate);
        btnCreate.Enabled = false;
        btnEdit.Name = "btnEdit";
        btnEdit.Text = "حفظ التعديل";
        btnEdit.AutoSize = true;
        btnEdit.MinimumSize = new Size(100,32);
        btnEdit.TabIndex = 2;
        btnEdit.AccessibleName = "حفظ التعديل";

        btnEdit.Enabled = false;
        btnCancel.Name = "btnCancel";
        btnCancel.Text = "إلغاء المستند";
        btnCancel.AutoSize = true;
        btnCancel.MinimumSize = new Size(100,32);
        btnCancel.TabIndex = 3;
        btnCancel.AccessibleName = "إلغاء المستند";

        btnCancel.Enabled = false;
        btnPost.Name = "btnPost";
        btnPost.Text = "ترحيل";
        btnPost.AutoSize = true;
        btnPost.MinimumSize = new Size(100,32);
        btnPost.TabIndex = 4;
        btnPost.AccessibleName = "ترحيل";
        flpActions.Controls.Add(btnPost);
        btnPost.Enabled = false;
        btnReverse.Name = "btnReverse";
        btnReverse.Text = "عكس القيد";
        btnReverse.AutoSize = true;
        btnReverse.MinimumSize = new Size(100,32);
        btnReverse.TabIndex = 5;
        btnReverse.AccessibleName = "عكس القيد";
        flpActions.Controls.Add(btnReverse);
        btnReverse.Enabled = false;
        btnClear.Name = "btnClear";
        btnClear.Text = "تفريغ المسودة";
        btnClear.AutoSize = true;
        btnClear.MinimumSize = new Size(100,32);
        btnClear.TabIndex = 6;
        btnClear.AccessibleName = "تفريغ المسودة";
        flpActions.Controls.Add(btnClear);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.AutoSize = true;
        btnClose.MinimumSize = new Size(100,32);
        btnClose.TabIndex = 7;
        btnClose.AccessibleName = "إغلاق";

        tabs.Name = "tabs";
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeftLayout = true;
        tabs.Multiline = true;
        tabs.TabIndex = 1;
        mainLayout.Controls.Add(tabs, 0, 2);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "مسودة واجهة غير محفوظة — الخدمات غير موصولة";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.Padding = new Padding(6);
        mainLayout.Controls.Add(lblStatus, 0, 3);
        tp0.Name = "tp0";
        tp0.Text = "البيانات الرئيسية";
        tp0.AutoScroll = true;
        tp0.TabIndex = 0;
        tabs.Controls.Add(tp0);
        layout0.Name = "layout0";
        layout0.Dock = DockStyle.Top;
        layout0.AutoSize = true;
        layout0.ColumnCount = 2;
        layout0.MinimumSize = new Size(650,0);
        layout0.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp0.Controls.Add(layout0);
        field_documentNumber.Name = "field_documentNumber";
        lbl_documentNumber.Name = "lbl_documentNumber";
        field_documentNumber.AccessibleName = "رقم المستند";
        field_documentNumber.Tag = "ACC-055:documentNumber";
        field_documentNumber.Dock = DockStyle.Fill;
        field_documentNumber.TabIndex = 0;
        lbl_documentNumber.Text = "رقم المستند";
        lbl_documentNumber.AutoSize = true;
        lbl_documentNumber.Dock = DockStyle.Fill;
        lbl_documentNumber.TextAlign = ContentAlignment.MiddleRight;
        lbl_documentNumber.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_documentNumber, 0, 0);
        layout0.Controls.Add(field_documentNumber, 1, 0);
        field_documentNumber.ReadOnly = true;
        field_documentNumber.TabStop = false;
        field_accountingDate.Name = "field_accountingDate";
        lbl_accountingDate.Name = "lbl_accountingDate";
        field_accountingDate.AccessibleName = "التاريخ المحاسبي";
        field_accountingDate.Tag = "ACC-055:accountingDate";
        field_accountingDate.Dock = DockStyle.Fill;
        field_accountingDate.TabIndex = 1;
        lbl_accountingDate.Text = "التاريخ المحاسبي";
        lbl_accountingDate.AutoSize = true;
        lbl_accountingDate.Dock = DockStyle.Fill;
        lbl_accountingDate.TextAlign = ContentAlignment.MiddleRight;
        lbl_accountingDate.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_accountingDate, 0, 1);
        layout0.Controls.Add(field_accountingDate, 1, 1);
        field_accountingDate.Format = DateTimePickerFormat.Custom;
        field_accountingDate.CustomFormat = "yyyy-MM-dd";
        field_accountingDate.ShowCheckBox = true;
        field_accountingDate.Checked = false;
        field_accountingDate.BackColor = Color.LightYellow;
        field_reference.Name = "field_reference";
        lbl_reference.Name = "lbl_reference";
        field_reference.AccessibleName = "المرجع";
        field_reference.Tag = "ACC-055:reference";
        field_reference.Dock = DockStyle.Fill;
        field_reference.TabIndex = 2;
        lbl_reference.Text = "المرجع";
        lbl_reference.AutoSize = true;
        lbl_reference.Dock = DockStyle.Fill;
        lbl_reference.TextAlign = ContentAlignment.MiddleRight;
        lbl_reference.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_reference, 0, 2);
        layout0.Controls.Add(field_reference, 1, 2);
        field_description.Name = "field_description";
        lbl_description.Name = "lbl_description";
        field_description.AccessibleName = "الوصف";
        field_description.Tag = "ACC-055:description";
        field_description.Dock = DockStyle.Fill;
        field_description.TabIndex = 3;
        lbl_description.Text = "الوصف";
        lbl_description.AutoSize = true;
        lbl_description.Dock = DockStyle.Fill;
        lbl_description.TextAlign = ContentAlignment.MiddleRight;
        lbl_description.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_description, 0, 3);
        layout0.Controls.Add(field_description, 1, 3);
        field_description.BackColor = Color.LightYellow;
        field_currencyRef.Name = "field_currencyRef";
        lbl_currencyRef.Name = "lbl_currencyRef";
        field_currencyRef.AccessibleName = "العملة";
        field_currencyRef.Tag = "ACC-055:currencyRef";
        field_currencyRef.Dock = DockStyle.Fill;
        field_currencyRef.TabIndex = 4;
        lbl_currencyRef.Text = "العملة";
        lbl_currencyRef.AutoSize = true;
        lbl_currencyRef.Dock = DockStyle.Fill;
        lbl_currencyRef.TextAlign = ContentAlignment.MiddleRight;
        lbl_currencyRef.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_currencyRef, 0, 4);
        layout0.Controls.Add(field_currencyRef, 1, 4);
        field_currencyRef.DropDownStyle = ComboBoxStyle.DropDownList;
        field_currencyRef.DropDownWidth = 420;
        field_currencyRef.BackColor = Color.LightYellow;
        field_exchangeRate.Name = "field_exchangeRate";
        lbl_exchangeRate.Name = "lbl_exchangeRate";
        field_exchangeRate.AccessibleName = "سعر الصرف";
        field_exchangeRate.Tag = "ACC-055:exchangeRate";
        field_exchangeRate.Dock = DockStyle.Fill;
        field_exchangeRate.TabIndex = 5;
        lbl_exchangeRate.Text = "سعر الصرف";
        lbl_exchangeRate.AutoSize = true;
        lbl_exchangeRate.Dock = DockStyle.Fill;
        lbl_exchangeRate.TextAlign = ContentAlignment.MiddleRight;
        lbl_exchangeRate.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_exchangeRate, 0, 5);
        layout0.Controls.Add(field_exchangeRate, 1, 5);
        field_exchangeRate.RightToLeft = RightToLeft.No;
        field_exchangeRate.TextAlign = HorizontalAlignment.Right;
        field_exchangeRate.BackColor = Color.LightYellow;
        field_state.Name = "field_state";
        lbl_state.Name = "lbl_state";
        field_state.AccessibleName = "الحالة";
        field_state.Tag = "ACC-055:state";
        field_state.Dock = DockStyle.Fill;
        field_state.TabIndex = 6;
        lbl_state.Text = "الحالة";
        lbl_state.AutoSize = true;
        lbl_state.Dock = DockStyle.Fill;
        lbl_state.TextAlign = ContentAlignment.MiddleRight;
        lbl_state.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_state, 0, 6);
        layout0.Controls.Add(field_state, 1, 6);
        field_state.ReadOnly = true;
        field_state.TabStop = false;
        layout0.RowCount = 7;
        tp1.Name = "tp1";
        tp1.Text = "التفاصيل والحركات";
        tp1.AutoScroll = true;
        tp1.TabIndex = 1;
        tabs.Controls.Add(tp1);
        layout1.Name = "layout1";
        layout1.Dock = DockStyle.Top;
        layout1.AutoSize = true;
        layout1.ColumnCount = 2;
        layout1.MinimumSize = new Size(650,0);
        layout1.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp1.Controls.Add(layout1);
        layout1.RowCount = 0;
        dgvLines.Name = "dgvLines";
        dgvLines.Dock = DockStyle.Fill;
        dgvLines.MinimumSize = new Size(650,260);
        dgvLines.AutoGenerateColumns = false;
        dgvLines.AllowUserToAddRows = false;
        dgvLines.AllowUserToDeleteRows = false;
        dgvLines.AllowUserToOrderColumns = false;
        dgvLines.RowHeadersVisible = false;
        dgvLines.MultiSelect = false;
        dgvLines.SelectionMode = DataGridViewSelectionMode.CellSelect;
        dgvLines.AccessibleName = "التفاصيل والحركات";
        dgvLines.TabIndex = 1;
        col_rowNo.Name = "col_rowNo";
        col_rowNo.Name = "rowNo";
        col_rowNo.HeaderText = "#";
        col_rowNo.ReadOnly = true;
        col_rowNo.Tag = "text";
        col_rowNo.MinimumWidth = 90;
        col_rowNo.Width = 140;
        col_rowNo.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_rowNo);
        col_accountRef.Name = "col_accountRef";
        col_accountRef.Name = "accountRef";
        col_accountRef.HeaderText = "الحساب";
        col_accountRef.HeaderCell.Tag = "required";
        col_accountRef.DefaultCellStyle.BackColor = Color.LightYellow;
        col_accountRef.ReadOnly = false;
        col_accountRef.Tag = "lookup";
        col_accountRef.MinimumWidth = 90;
        col_accountRef.Width = 140;
        col_accountRef.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_accountRef.DisplayStyle = DataGridViewComboBoxDisplayStyle.DropDownButton;
        col_accountRef.ValueType = typeof(string);
        dgvLines.Columns.Add(col_accountRef);
        col_costCenterRef.Name = "col_costCenterRef";
        col_costCenterRef.Name = "costCenterRef";
        col_costCenterRef.HeaderText = "مركز التكلفة/الأبعاد";
        col_costCenterRef.ReadOnly = false;
        col_costCenterRef.Tag = "lookup";
        col_costCenterRef.MinimumWidth = 90;
        col_costCenterRef.Width = 140;
        col_costCenterRef.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_costCenterRef.DisplayStyle = DataGridViewComboBoxDisplayStyle.DropDownButton;
        col_costCenterRef.ValueType = typeof(string);
        dgvLines.Columns.Add(col_costCenterRef);
        col_lineDescription.Name = "col_lineDescription";
        col_lineDescription.Name = "lineDescription";
        col_lineDescription.HeaderText = "البيان";
        col_lineDescription.ReadOnly = false;
        col_lineDescription.Tag = "text";
        col_lineDescription.MinimumWidth = 90;
        col_lineDescription.Width = 140;
        col_lineDescription.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_lineDescription.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        dgvLines.Columns.Add(col_lineDescription);
        col_debit.Name = "col_debit";
        col_debit.Name = "debit";
        col_debit.HeaderText = "مدين";
        col_debit.ReadOnly = false;
        col_debit.Tag = "decimal";
        col_debit.MinimumWidth = 90;
        col_debit.Width = 140;
        col_debit.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_debit.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_debit);
        col_credit.Name = "col_credit";
        col_credit.Name = "credit";
        col_credit.HeaderText = "دائن";
        col_credit.ReadOnly = false;
        col_credit.Tag = "decimal";
        col_credit.MinimumWidth = 90;
        col_credit.Width = 140;
        col_credit.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_credit.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_credit);
        col_currencyRef.Name = "col_currencyRef";
        col_currencyRef.Name = "currencyRef";
        col_currencyRef.HeaderText = "العملة";
        col_currencyRef.ReadOnly = false;
        col_currencyRef.Tag = "lookup";
        col_currencyRef.MinimumWidth = 90;
        col_currencyRef.Width = 140;
        col_currencyRef.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_currencyRef.DisplayStyle = DataGridViewComboBoxDisplayStyle.DropDownButton;
        col_currencyRef.ValueType = typeof(string);
        dgvLines.Columns.Add(col_currencyRef);
        col_exchangeRate.Name = "col_exchangeRate";
        col_exchangeRate.Name = "exchangeRate";
        col_exchangeRate.HeaderText = "سعر الصرف";
        col_exchangeRate.ReadOnly = false;
        col_exchangeRate.Tag = "decimal";
        col_exchangeRate.MinimumWidth = 90;
        col_exchangeRate.Width = 140;
        col_exchangeRate.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_exchangeRate.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_exchangeRate);
        col_accountingAmount.Name = "col_accountingAmount";
        col_accountingAmount.Name = "accountingAmount";
        col_accountingAmount.HeaderText = "المبلغ المحاسبي";
        col_accountingAmount.ReadOnly = true;
        col_accountingAmount.Tag = "decimal";
        col_accountingAmount.MinimumWidth = 90;
        col_accountingAmount.Width = 140;
        col_accountingAmount.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_accountingAmount.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_accountingAmount);
        linesHost.Name = "linesHost";
        linesHost.Dock = DockStyle.Fill;
        linesHost.ColumnCount = 1;
        linesHost.RowCount = 3;
        linesHost.MinimumSize = new Size(680,380);
        linesHost.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        linesHost.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        linesHost.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        linesHost.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        tp1.Controls.Remove(layout1);
        linesHost.Controls.Add(layout1, 0, 0);
        tp1.Controls.Add(linesHost);
        linesHost.Controls.Add(dgvLines, 0, 2);
        lineActions.Name = "lineActions";
        lineActions.Dock = DockStyle.Fill;
        lineActions.AutoSize = true;
        linesHost.Controls.Add(lineActions, 0, 1);
        btnAddRow.Name = "btnAddRow";
        btnAddRow.Text = "إضافة سطر";
        btnAddRow.AutoSize = true;
        lineActions.Controls.Add(btnAddRow);
        btnRemoveRow.Name = "btnRemoveRow";
        btnRemoveRow.Text = "حذف سطر";
        btnRemoveRow.AutoSize = true;
        lineActions.Controls.Add(btnRemoveRow);
        tp2.Name = "tp2";
        tp2.Text = "المرفقات والربط بالمستندات";
        tp2.AutoScroll = true;
        tp2.TabIndex = 2;
        tabs.Controls.Add(tp2);
        layout2.Name = "layout2";
        layout2.Dock = DockStyle.Top;
        layout2.AutoSize = true;
        layout2.ColumnCount = 2;
        layout2.MinimumSize = new Size(650,0);
        layout2.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp2.Controls.Add(layout2);
        layout2.RowCount = 0;
        layout2.Dock = DockStyle.Fill;
        layout2.RowCount = 1;
        layout2.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        context2.Name = "context2";
        context2.ReadOnly = true;
        context2.Dock = DockStyle.Fill;
        context2.AccessibleName = "المرفقات والربط بالمستندات";
        context2.DetectUrls = false;
        layout2.Controls.Add(context2, 0, 0);
        layout2.SetColumnSpan(context2,2);
        tp3.Name = "tp3";
        tp3.Text = "الاعتمادات";
        tp3.AutoScroll = true;
        tp3.TabIndex = 3;
        tabs.Controls.Add(tp3);
        layout3.Name = "layout3";
        layout3.Dock = DockStyle.Top;
        layout3.AutoSize = true;
        layout3.ColumnCount = 2;
        layout3.MinimumSize = new Size(650,0);
        layout3.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout3.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp3.Controls.Add(layout3);
        layout3.RowCount = 0;
        layout3.Dock = DockStyle.Fill;
        layout3.RowCount = 1;
        layout3.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        context3.Name = "context3";
        context3.ReadOnly = true;
        context3.Dock = DockStyle.Fill;
        context3.AccessibleName = "الاعتمادات";
        context3.DetectUrls = false;
        layout3.Controls.Add(context3, 0, 0);
        layout3.SetColumnSpan(context3,2);
        tp4.Name = "tp4";
        tp4.Text = "سجل العمليات";
        tp4.AutoScroll = true;
        tp4.TabIndex = 4;
        tabs.Controls.Add(tp4);
        layout4.Name = "layout4";
        layout4.Dock = DockStyle.Top;
        layout4.AutoSize = true;
        layout4.ColumnCount = 2;
        layout4.MinimumSize = new Size(650,0);
        layout4.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout4.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp4.Controls.Add(layout4);
        layout4.RowCount = 0;
        layout4.Dock = DockStyle.Fill;
        layout4.RowCount = 1;
        layout4.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        context4.Name = "context4";
        context4.ReadOnly = true;
        context4.Dock = DockStyle.Fill;
        context4.AccessibleName = "سجل العمليات";
        context4.DetectUrls = false;
        layout4.Controls.Add(context4, 0, 0);
        layout4.SetColumnSpan(context4,2);
        AutoScaleDimensions = new SizeF(96F,96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Name = "UcScreen_04_11_03";
        Text = "قيود التسوية والإقفال السنوي";
        Tag = "04.11.03";
        Size = new Size(1100,720);
        Controls.Add(mainLayout);
        ResumeLayout(false);
        PerformLayout();
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Fill;
        designerCommandBar.RightToLeft = RightToLeft.Yes;
        designerCommandBar.Controls.Add(flpActions);
        flpActions.Dock = DockStyle.Fill;
        flpActions.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        flpActions.Name = "flpActions";
        flpActions.Dock = DockStyle.Fill;
        flpActions.AutoSize = false;
        flpActions.WrapContents = false;
        flpActions.FlowDirection = FlowDirection.RightToLeft;
        flpActions.RightToLeft = RightToLeft.No;
        flpActions.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 44;
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = true;
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandSave.Name = "standardCommandSave";
        standardCommandSave.Enabled = false;
        standardCommandSave.Visible = true;
        standardCommandSave.AccessibleName = "حفظ";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandAdd.AutoSize = false;
        standardCommandAdd.Dock = DockStyle.None;
        standardCommandAdd.MinimumSize = Size.Empty;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandAdd.Text = "";
        flpActions.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        btnEdit.AutoSize = false;
        btnEdit.Dock = DockStyle.None;
        btnEdit.MinimumSize = Size.Empty;
        btnEdit.Size = new Size(26, 24);
        btnEdit.Margin = new Padding(1);
        btnEdit.FlatStyle = FlatStyle.Flat;
        btnEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        btnEdit.Text = "";
        flpActions.Controls.Add(btnEdit);
        designerCommandBar.SetCommandRole(btnEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        flpActions.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        btnCancel.AutoSize = false;
        btnCancel.Dock = DockStyle.None;
        btnCancel.MinimumSize = Size.Empty;
        btnCancel.Size = new Size(26, 24);
        btnCancel.Margin = new Padding(1);
        btnCancel.FlatStyle = FlatStyle.Flat;
        btnCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        btnCancel.Text = "";
        flpActions.Controls.Add(btnCancel);
        designerCommandBar.SetCommandRole(btnCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        btnView.AutoSize = false;
        btnView.Dock = DockStyle.None;
        btnView.MinimumSize = Size.Empty;
        btnView.Size = new Size(26, 24);
        btnView.Margin = new Padding(1);
        btnView.FlatStyle = FlatStyle.Flat;
        btnView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        btnView.Text = "";
        flpActions.Controls.Add(btnView);
        designerCommandBar.SetCommandRole(btnView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        flpActions.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        flpActions.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        flpActions.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        flpActions.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        standardCommandSave.AutoSize = false;
        standardCommandSave.Dock = DockStyle.None;
        standardCommandSave.MinimumSize = Size.Empty;
        standardCommandSave.Size = new Size(26, 24);
        standardCommandSave.Margin = new Padding(1);
        standardCommandSave.FlatStyle = FlatStyle.Flat;
        standardCommandSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        standardCommandSave.Text = "";
        flpActions.Controls.Add(standardCommandSave);
        designerCommandBar.SetCommandRole(standardCommandSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        flpActions.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        btnClose.AutoSize = false;
        btnClose.Dock = DockStyle.None;
        btnClose.MinimumSize = Size.Empty;
        btnClose.Size = new Size(26, 24);
        btnClose.Margin = new Padding(1);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        btnClose.Text = "";
        designerCloseHost.Controls.Add(btnClose);
        btnClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        flpActions.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        flpActions.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        flpActions.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        flpActions.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}
}
