#nullable enable
using System.Drawing;
using System.Windows.Forms;
namespace TransportERP.EmptyForms;
partial class UcScreen_04_10_05
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandView = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private FlowLayoutPanel flpActions = null!;
    private Button btnSave = null!;
    private Button btnClear = null!;
    private Button btnClose = null!;
    private TabControl tabs = null!;
    private Label lblStatus = null!;
    private TabPage tp0 = null!;
    private TableLayoutPanel layout0 = null!;
    private TextBox field_T04_EV_0413 = null!;
    private Label lbl_T04_EV_0413 = null!;
    private DateTimePicker field_T04_EV_0415 = null!;
    private Label lbl_T04_EV_0415 = null!;
    private TextBox field_T04_EV_0416 = null!;
    private Label lbl_T04_EV_0416 = null!;
    private TextBox field_T04_EV_0417 = null!;
    private Label lbl_T04_EV_0417 = null!;
    private ComboBox field_R05_AT_0304 = null!;
    private Label lbl_R05_AT_0304 = null!;
    private TextBox field_R05_AT_0305 = null!;
    private Label lbl_R05_AT_0305 = null!;
    private TabPage tp1 = null!;
    private TableLayoutPanel layout1 = null!;
    private DataGridView dgvLines = null!;
    private DataGridViewTextBoxColumn col_rowNo = null!;
    private DataGridViewComboBoxColumn col_T04_EV_0419 = null!;
    private DataGridViewTextBoxColumn col_T04_EV_0420 = null!;
    private DataGridViewComboBoxColumn col_T04_EV_0421 = null!;
    private DataGridViewTextBoxColumn col_T04_EV_0422 = null!;
    private DataGridViewTextBoxColumn col_T04_EV_0423 = null!;
    private TableLayoutPanel linesHost = null!;
    private FlowLayoutPanel lineActions = null!;
    private Button btnAddRow = null!;
    private Button btnRemoveRow = null!;
    private System.ComponentModel.IContainer? components;
    private ErrorProvider validationErrors = null!;
    protected override void Dispose(bool disposing) { if(disposing) components?.Dispose(); base.Dispose(disposing); }
    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandView = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandPrint = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        components = new System.ComponentModel.Container();
        validationErrors = new ErrorProvider(components);
        validationErrors.ContainerControl = this;
        validationErrors.BlinkStyle = ErrorBlinkStyle.NeverBlink;
        mainLayout = new TableLayoutPanel();
        lblTitle = new Label();
        flpActions = new FlowLayoutPanel();
        btnSave = new Button();
        btnClear = new Button();
        btnClose = new Button();
        tabs = new TabControl();
        lblStatus = new Label();
        tp0 = new TabPage();
        layout0 = new TableLayoutPanel();
        field_T04_EV_0413 = new TextBox();
        lbl_T04_EV_0413 = new Label();
        field_T04_EV_0415 = new DateTimePicker();
        lbl_T04_EV_0415 = new Label();
        field_T04_EV_0416 = new TextBox();
        lbl_T04_EV_0416 = new Label();
        field_T04_EV_0417 = new TextBox();
        lbl_T04_EV_0417 = new Label();
        field_R05_AT_0304 = new ComboBox();
        lbl_R05_AT_0304 = new Label();
        field_R05_AT_0305 = new TextBox();
        lbl_R05_AT_0305 = new Label();
        tp1 = new TabPage();
        layout1 = new TableLayoutPanel();
        dgvLines = new DataGridView();
        col_rowNo = new DataGridViewTextBoxColumn();
        col_T04_EV_0419 = new DataGridViewComboBoxColumn();
        col_T04_EV_0420 = new DataGridViewTextBoxColumn();
        col_T04_EV_0421 = new DataGridViewComboBoxColumn();
        col_T04_EV_0422 = new DataGridViewTextBoxColumn();
        col_T04_EV_0423 = new DataGridViewTextBoxColumn();
        linesHost = new TableLayoutPanel();
        lineActions = new FlowLayoutPanel();
        btnAddRow = new Button();
        btnRemoveRow = new Button();
        SuspendLayout();
        mainLayout.Name = "mainLayout";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "جرد النقدية";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Padding = new Padding(8);
        lblTitle.TabStop = false;
        mainLayout.Controls.Add(lblTitle, 0, 0);
        flpActions.Name = "flpActions";
        flpActions.AutoSize = true;
        flpActions.Dock = DockStyle.Fill;
        flpActions.WrapContents = true;
        flpActions.FlowDirection = FlowDirection.LeftToRight;
        flpActions.RightToLeft = RightToLeft.Yes;
        mainLayout.Controls.Add(designerCommandBar, 0, 1);
        btnSave.Name = "btnSave";
        btnSave.Text = "حفظ";
        btnSave.AutoSize = true;
        btnSave.MinimumSize = new Size(100,32);
        btnSave.TabIndex = 0;
        btnSave.AccessibleName = "حفظ";

        btnSave.Enabled = false;
        btnClear.Name = "btnClear";
        btnClear.Text = "تفريغ المسودة";
        btnClear.AutoSize = true;
        btnClear.MinimumSize = new Size(100,32);
        btnClear.TabIndex = 1;
        btnClear.AccessibleName = "تفريغ المسودة";
        flpActions.Controls.Add(btnClear);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.AutoSize = true;
        btnClose.MinimumSize = new Size(100,32);
        btnClose.TabIndex = 2;
        btnClose.AccessibleName = "إغلاق";

        tabs.Name = "tabs";
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeftLayout = true;
        tabs.Multiline = true;
        tabs.TabIndex = 1;
        mainLayout.Controls.Add(tabs, 0, 2);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "مسودة واجهة غير محفوظة — الخدمات غير موصولة";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.Padding = new Padding(6);
        mainLayout.Controls.Add(lblStatus, 0, 3);
        tp0.Name = "tp0";
        tp0.Text = "البيانات الرئيسية";
        tp0.AutoScroll = true;
        tp0.TabIndex = 0;
        tabs.Controls.Add(tp0);
        layout0.Name = "layout0";
        layout0.Dock = DockStyle.Top;
        layout0.AutoSize = true;
        layout0.ColumnCount = 2;
        layout0.MinimumSize = new Size(650,0);
        layout0.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp0.Controls.Add(layout0);
        field_T04_EV_0413.Name = "field_T04_EV_0413";
        lbl_T04_EV_0413.Name = "lbl_T04_EV_0413";
        field_T04_EV_0413.AccessibleName = "رقم السند";
        field_T04_EV_0413.Tag = "T04-EV-0413";
        field_T04_EV_0413.Dock = DockStyle.Fill;
        field_T04_EV_0413.TabIndex = 0;
        lbl_T04_EV_0413.Text = "رقم السند";
        lbl_T04_EV_0413.AutoSize = true;
        lbl_T04_EV_0413.Dock = DockStyle.Fill;
        lbl_T04_EV_0413.TextAlign = ContentAlignment.MiddleRight;
        lbl_T04_EV_0413.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_T04_EV_0413, 0, 0);
        layout0.Controls.Add(field_T04_EV_0413, 1, 0);
        field_T04_EV_0413.ReadOnly = true;
        field_T04_EV_0413.TabStop = false;
        field_T04_EV_0415.Name = "field_T04_EV_0415";
        lbl_T04_EV_0415.Name = "lbl_T04_EV_0415";
        field_T04_EV_0415.AccessibleName = "التاريخ";
        field_T04_EV_0415.Tag = "T04-EV-0415";
        field_T04_EV_0415.Dock = DockStyle.Fill;
        field_T04_EV_0415.TabIndex = 1;
        lbl_T04_EV_0415.Text = "التاريخ";
        lbl_T04_EV_0415.AutoSize = true;
        lbl_T04_EV_0415.Dock = DockStyle.Fill;
        lbl_T04_EV_0415.TextAlign = ContentAlignment.MiddleRight;
        lbl_T04_EV_0415.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_T04_EV_0415, 0, 1);
        layout0.Controls.Add(field_T04_EV_0415, 1, 1);
        field_T04_EV_0415.Format = DateTimePickerFormat.Custom;
        field_T04_EV_0415.CustomFormat = "yyyy-MM-dd";
        field_T04_EV_0415.ShowCheckBox = true;
        field_T04_EV_0415.Checked = false;
        field_T04_EV_0416.Name = "field_T04_EV_0416";
        lbl_T04_EV_0416.Name = "lbl_T04_EV_0416";
        field_T04_EV_0416.AccessibleName = "البيان";
        field_T04_EV_0416.Tag = "T04-EV-0416";
        field_T04_EV_0416.Dock = DockStyle.Fill;
        field_T04_EV_0416.TabIndex = 2;
        lbl_T04_EV_0416.Text = "البيان";
        lbl_T04_EV_0416.AutoSize = true;
        lbl_T04_EV_0416.Dock = DockStyle.Fill;
        lbl_T04_EV_0416.TextAlign = ContentAlignment.MiddleRight;
        lbl_T04_EV_0416.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_T04_EV_0416, 0, 2);
        layout0.Controls.Add(field_T04_EV_0416, 1, 2);
        field_T04_EV_0416.Multiline = true;
        field_T04_EV_0416.Height = 70;
        field_T04_EV_0416.ScrollBars = ScrollBars.Vertical;
        field_T04_EV_0417.Name = "field_T04_EV_0417";
        lbl_T04_EV_0417.Name = "lbl_T04_EV_0417";
        field_T04_EV_0417.AccessibleName = "الاسم";
        field_T04_EV_0417.Tag = "T04-EV-0417";
        field_T04_EV_0417.Dock = DockStyle.Fill;
        field_T04_EV_0417.TabIndex = 3;
        lbl_T04_EV_0417.Text = "الاسم";
        lbl_T04_EV_0417.AutoSize = true;
        lbl_T04_EV_0417.Dock = DockStyle.Fill;
        lbl_T04_EV_0417.TextAlign = ContentAlignment.MiddleRight;
        lbl_T04_EV_0417.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_T04_EV_0417, 0, 3);
        layout0.Controls.Add(field_T04_EV_0417, 1, 3);
        field_R05_AT_0304.Name = "field_R05_AT_0304";
        lbl_R05_AT_0304.Name = "lbl_R05_AT_0304";
        field_R05_AT_0304.AccessibleName = "رقم الصندوق";
        field_R05_AT_0304.Tag = "R05-AT-0304";
        field_R05_AT_0304.Dock = DockStyle.Fill;
        field_R05_AT_0304.TabIndex = 4;
        lbl_R05_AT_0304.Text = "رقم الصندوق";
        lbl_R05_AT_0304.AutoSize = true;
        lbl_R05_AT_0304.Dock = DockStyle.Fill;
        lbl_R05_AT_0304.TextAlign = ContentAlignment.MiddleRight;
        lbl_R05_AT_0304.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_R05_AT_0304, 0, 4);
        layout0.Controls.Add(field_R05_AT_0304, 1, 4);
        field_R05_AT_0304.DropDownStyle = ComboBoxStyle.DropDownList;
        field_R05_AT_0304.DropDownWidth = 420;
        field_R05_AT_0305.Name = "field_R05_AT_0305";
        lbl_R05_AT_0305.Name = "lbl_R05_AT_0305";
        field_R05_AT_0305.AccessibleName = "اسم الصندوق";
        field_R05_AT_0305.Tag = "R05-AT-0305";
        field_R05_AT_0305.Dock = DockStyle.Fill;
        field_R05_AT_0305.TabIndex = 5;
        lbl_R05_AT_0305.Text = "اسم الصندوق";
        lbl_R05_AT_0305.AutoSize = true;
        lbl_R05_AT_0305.Dock = DockStyle.Fill;
        lbl_R05_AT_0305.TextAlign = ContentAlignment.MiddleRight;
        lbl_R05_AT_0305.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_R05_AT_0305, 0, 5);
        layout0.Controls.Add(field_R05_AT_0305, 1, 5);
        field_R05_AT_0305.ReadOnly = true;
        field_R05_AT_0305.TabStop = false;
        layout0.RowCount = 6;
        tp1.Name = "tp1";
        tp1.Text = "البيانات التفصيلية";
        tp1.AutoScroll = true;
        tp1.TabIndex = 1;
        tabs.Controls.Add(tp1);
        layout1.Name = "layout1";
        layout1.Dock = DockStyle.Top;
        layout1.AutoSize = true;
        layout1.ColumnCount = 2;
        layout1.MinimumSize = new Size(650,0);
        layout1.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp1.Controls.Add(layout1);
        layout1.RowCount = 0;
        dgvLines.Name = "dgvLines";
        dgvLines.Dock = DockStyle.Fill;
        dgvLines.MinimumSize = new Size(650,260);
        dgvLines.AutoGenerateColumns = false;
        dgvLines.AllowUserToAddRows = false;
        dgvLines.AllowUserToDeleteRows = false;
        dgvLines.AllowUserToOrderColumns = false;
        dgvLines.RowHeadersVisible = false;
        dgvLines.MultiSelect = false;
        dgvLines.SelectionMode = DataGridViewSelectionMode.CellSelect;
        dgvLines.AccessibleName = "البيانات التفصيلية";
        dgvLines.TabIndex = 1;
        col_rowNo.Name = "col_rowNo";
        col_rowNo.Name = "rowNo";
        col_rowNo.HeaderText = "#";
        col_rowNo.ReadOnly = true;
        col_rowNo.Tag = "text";
        col_rowNo.MinimumWidth = 90;
        col_rowNo.Width = 140;
        col_rowNo.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_rowNo);
        col_T04_EV_0419.Name = "col_T04_EV_0419";
        col_T04_EV_0419.Name = "T04_EV_0419";
        col_T04_EV_0419.HeaderText = "العملة";
        col_T04_EV_0419.ReadOnly = false;
        col_T04_EV_0419.Tag = "lookup";
        col_T04_EV_0419.MinimumWidth = 90;
        col_T04_EV_0419.Width = 140;
        col_T04_EV_0419.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_T04_EV_0419.DisplayStyle = DataGridViewComboBoxDisplayStyle.DropDownButton;
        col_T04_EV_0419.ValueType = typeof(string);
        dgvLines.Columns.Add(col_T04_EV_0419);
        col_T04_EV_0420.Name = "col_T04_EV_0420";
        col_T04_EV_0420.Name = "T04_EV_0420";
        col_T04_EV_0420.HeaderText = "الرصيد بالعملة";
        col_T04_EV_0420.ReadOnly = true;
        col_T04_EV_0420.Tag = "text";
        col_T04_EV_0420.MinimumWidth = 90;
        col_T04_EV_0420.Width = 140;
        col_T04_EV_0420.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_T04_EV_0420);
        col_T04_EV_0421.Name = "col_T04_EV_0421";
        col_T04_EV_0421.Name = "T04_EV_0421";
        col_T04_EV_0421.HeaderText = "اسم الفئة";
        col_T04_EV_0421.ReadOnly = false;
        col_T04_EV_0421.Tag = "lookup";
        col_T04_EV_0421.MinimumWidth = 90;
        col_T04_EV_0421.Width = 140;
        col_T04_EV_0421.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_T04_EV_0421.DisplayStyle = DataGridViewComboBoxDisplayStyle.DropDownButton;
        col_T04_EV_0421.ValueType = typeof(string);
        dgvLines.Columns.Add(col_T04_EV_0421);
        col_T04_EV_0422.Name = "col_T04_EV_0422";
        col_T04_EV_0422.Name = "T04_EV_0422";
        col_T04_EV_0422.HeaderText = "قيمة الجرد";
        col_T04_EV_0422.ReadOnly = false;
        col_T04_EV_0422.Tag = "decimal";
        col_T04_EV_0422.MinimumWidth = 90;
        col_T04_EV_0422.Width = 140;
        col_T04_EV_0422.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_T04_EV_0422.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_T04_EV_0422);
        col_T04_EV_0423.Name = "col_T04_EV_0423";
        col_T04_EV_0423.Name = "T04_EV_0423";
        col_T04_EV_0423.HeaderText = "الفارق";
        col_T04_EV_0423.ReadOnly = true;
        col_T04_EV_0423.Tag = "text";
        col_T04_EV_0423.MinimumWidth = 90;
        col_T04_EV_0423.Width = 140;
        col_T04_EV_0423.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_T04_EV_0423);
        linesHost.Name = "linesHost";
        linesHost.Dock = DockStyle.Fill;
        linesHost.ColumnCount = 1;
        linesHost.RowCount = 3;
        linesHost.MinimumSize = new Size(680,380);
        linesHost.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        linesHost.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        linesHost.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        linesHost.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        tp1.Controls.Remove(layout1);
        linesHost.Controls.Add(layout1, 0, 0);
        tp1.Controls.Add(linesHost);
        linesHost.Controls.Add(dgvLines, 0, 2);
        lineActions.Name = "lineActions";
        lineActions.Dock = DockStyle.Fill;
        lineActions.AutoSize = true;
        linesHost.Controls.Add(lineActions, 0, 1);
        btnAddRow.Name = "btnAddRow";
        btnAddRow.Text = "إضافة سطر";
        btnAddRow.AutoSize = true;
        lineActions.Controls.Add(btnAddRow);
        btnRemoveRow.Name = "btnRemoveRow";
        btnRemoveRow.Text = "حذف سطر";
        btnRemoveRow.AutoSize = true;
        lineActions.Controls.Add(btnRemoveRow);
        AutoScaleDimensions = new SizeF(96F,96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Name = "UcScreen_04_10_05";
        Text = "جرد النقدية";
        Tag = "04.10.05";
        Size = new Size(1100,720);
        Controls.Add(mainLayout);
        ResumeLayout(false);
        PerformLayout();
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Fill;
        designerCommandBar.RightToLeft = RightToLeft.Yes;
        designerCommandBar.Controls.Add(flpActions);
        flpActions.Dock = DockStyle.Fill;
        flpActions.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        flpActions.Name = "flpActions";
        flpActions.Dock = DockStyle.Fill;
        flpActions.AutoSize = false;
        flpActions.WrapContents = false;
        flpActions.FlowDirection = FlowDirection.RightToLeft;
        flpActions.RightToLeft = RightToLeft.No;
        flpActions.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 44;
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = true;
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = true;
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandView.Name = "standardCommandView";
        standardCommandView.Enabled = false;
        standardCommandView.Visible = true;
        standardCommandView.AccessibleName = "عرض";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandAdd.AutoSize = false;
        standardCommandAdd.Dock = DockStyle.None;
        standardCommandAdd.MinimumSize = Size.Empty;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandAdd.Text = "";
        flpActions.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.AutoSize = false;
        standardCommandEdit.Dock = DockStyle.None;
        standardCommandEdit.MinimumSize = Size.Empty;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandEdit.Text = "";
        flpActions.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        flpActions.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.AutoSize = false;
        standardCommandCancel.Dock = DockStyle.None;
        standardCommandCancel.MinimumSize = Size.Empty;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandCancel.Text = "";
        flpActions.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        standardCommandView.AutoSize = false;
        standardCommandView.Dock = DockStyle.None;
        standardCommandView.MinimumSize = Size.Empty;
        standardCommandView.Size = new Size(26, 24);
        standardCommandView.Margin = new Padding(1);
        standardCommandView.FlatStyle = FlatStyle.Flat;
        standardCommandView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        standardCommandView.Text = "";
        flpActions.Controls.Add(standardCommandView);
        designerCommandBar.SetCommandRole(standardCommandView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        flpActions.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        flpActions.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        flpActions.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        flpActions.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        btnSave.AutoSize = false;
        btnSave.Dock = DockStyle.None;
        btnSave.MinimumSize = Size.Empty;
        btnSave.Size = new Size(26, 24);
        btnSave.Margin = new Padding(1);
        btnSave.FlatStyle = FlatStyle.Flat;
        btnSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        btnSave.Text = "";
        flpActions.Controls.Add(btnSave);
        designerCommandBar.SetCommandRole(btnSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        flpActions.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        btnClose.AutoSize = false;
        btnClose.Dock = DockStyle.None;
        btnClose.MinimumSize = Size.Empty;
        btnClose.Size = new Size(26, 24);
        btnClose.Margin = new Padding(1);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        btnClose.Text = "";
        designerCloseHost.Controls.Add(btnClose);
        btnClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        flpActions.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        flpActions.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        flpActions.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        flpActions.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}
}
