using System.Drawing;
using System.Windows.Forms;

namespace TransportERP.EmptyForms;

partial class UcScreen_02_04_06
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandSave = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandClose = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel root = null!;
    private Label lblTitle = null!;
    private FlowLayoutPanel actions = null!;
    private Button btnView = null!;
    private Button btnExecute = null!;
    private Button btnApprove = null!;
    private Button btnReject = null!;
    private Button btnReturn = null!;
    private Button btnReopen = null!;
    private TableLayoutPanel filters = null!;
    private Label lblCompany = null!;
    private ComboBox filterCompany = null!;
    private Label lblStatus = null!;
    private ComboBox filterStatus = null!;
    private Label lblStartDate = null!;
    private DateTimePicker filterStartDate = null!;
    private Label lblEndDate = null!;
    private DateTimePicker filterEndDate = null!;
    private DataGridView years = null!;
    private DataGridViewTextBoxColumn colCode = null!;
    private DataGridViewTextBoxColumn colStartDate = null!;
    private DataGridViewTextBoxColumn colEndDate = null!;
    private DataGridViewTextBoxColumn colStatus = null!;
    private FlowLayoutPanel paging = null!;
    private Button btnPrevious = null!;
    private Button btnNext = null!;
    private Label lblPage = null!;
    private TableLayoutPanel approval = null!;
    private Label lblAction = null!;
    private ComboBox cboAction = null!;
    private Label lblReason = null!;
    private TextBox txtReason = null!;
    private TableLayoutPanel audit = null!;
    private Label audit0 = null!;
    private Label audit1 = null!;
    private Label audit2 = null!;
    private Label audit3 = null!;
    private Label audit4 = null!;
    private Label audit5 = null!;
    private Label audit6 = null!;
    private GroupBox approvalHistoryHost = null!;
    private DataGridView approvalHistory = null!;
    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandSave = new Button();
        standardCommandPrint = new Button();
        standardCommandClose = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        SuspendLayout();
        approvalHistoryHost = new GroupBox();
        approvalHistory = new DataGridView();
        approvalHistoryHost.Name = "approvalHistoryHost";
        approvalHistoryHost.Text = "سجل طلبات الاعتماد — لا توجد بيانات محمّلة";
        approvalHistoryHost.Dock = DockStyle.Fill;
        approvalHistoryHost.Padding = new Padding(8);
        approvalHistoryHost.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        approvalHistory.Name = "approvalHistory";
        approvalHistory.Dock = DockStyle.Fill;
        approvalHistory.ReadOnly = true;
        approvalHistory.AllowUserToAddRows = false;
        approvalHistory.AllowUserToDeleteRows = false;
        approvalHistory.AutoGenerateColumns = true;
        approvalHistory.BackgroundColor = Color.White;
        approvalHistoryHost.Controls.Add(approvalHistory);
        root = new TableLayoutPanel();
        root.Dock = DockStyle.Fill;
        root.ColumnCount = 1;
        root.RowCount = 8;
        root.Margin = new Padding(0);
        root.Padding = new Padding(8);
        root.Name = "root";
        root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        root.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 112F));
        root.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 144F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 176F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        lblTitle = new Label();
        lblTitle.Text = "السنوات المالية";
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleRight;
        lblTitle.Margin = new Padding(3);
        lblTitle.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        lblTitle.Name = "lblTitle";
        lblTitle.BackColor = Color.FromArgb(192, 192, 255);
        lblTitle.Font = new Font("Segoe UI", 16F);
        root.Controls.Add(lblTitle, 0, 0);
        actions = new FlowLayoutPanel();
        actions.Dock = DockStyle.Fill;
        actions.AutoSize = true;
        actions.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        actions.WrapContents = true;
        actions.Padding = new Padding(5);
        actions.MinimumSize = new Size(0, 48);
        actions.BackColor = Color.FromArgb(224, 224, 224);
        actions.Name = "actions";
        btnView = new Button();
        btnView.Text = "عرض";
        btnView.Size = new Size(70, 30);
        btnView.Margin = new Padding(4);
        btnView.Dock = DockStyle.None;
        btnView.Font = new Font("Microsoft Sans Serif", 10F);
        btnView.FlatStyle = FlatStyle.Flat;
        btnView.BackColor = Color.FromArgb(224, 224, 224);
        btnView.Enabled = false;
        btnView.Name = "btnView";

        btnExecute = new Button();
        btnExecute.Text = "طلب إجراء محمي";
        btnExecute.Size = new Size(140, 30);
        btnExecute.Margin = new Padding(4);
        btnExecute.Dock = DockStyle.None;
        btnExecute.Font = new Font("Microsoft Sans Serif", 10F);
        btnExecute.FlatStyle = FlatStyle.Flat;
        btnExecute.BackColor = Color.FromArgb(224, 224, 224);
        btnExecute.Enabled = false;
        btnExecute.Name = "btnExecute";
        actions.Controls.Add(btnExecute);
        btnApprove = new Button();
        btnApprove.Text = "اعتماد";
        btnApprove.Size = new Size(70, 30);
        btnApprove.Margin = new Padding(4);
        btnApprove.Dock = DockStyle.None;
        btnApprove.Font = new Font("Microsoft Sans Serif", 10F);
        btnApprove.FlatStyle = FlatStyle.Flat;
        btnApprove.BackColor = Color.FromArgb(224, 224, 224);
        btnApprove.Enabled = false;
        btnApprove.Name = "btnApprove";
        actions.Controls.Add(btnApprove);
        btnReject = new Button();
        btnReject.Text = "رفض";
        btnReject.Size = new Size(70, 30);
        btnReject.Margin = new Padding(4);
        btnReject.Dock = DockStyle.None;
        btnReject.Font = new Font("Microsoft Sans Serif", 10F);
        btnReject.FlatStyle = FlatStyle.Flat;
        btnReject.BackColor = Color.FromArgb(224, 224, 224);
        btnReject.Enabled = false;
        btnReject.Name = "btnReject";
        actions.Controls.Add(btnReject);
        btnReturn = new Button();
        btnReturn.Text = "إعادة للمراجعة";
        btnReturn.Size = new Size(125, 30);
        btnReturn.Margin = new Padding(4);
        btnReturn.Dock = DockStyle.None;
        btnReturn.Font = new Font("Microsoft Sans Serif", 10F);
        btnReturn.FlatStyle = FlatStyle.Flat;
        btnReturn.BackColor = Color.FromArgb(224, 224, 224);
        btnReturn.Enabled = false;
        btnReturn.Name = "btnReturn";
        actions.Controls.Add(btnReturn);
        btnReopen = new Button();
        btnReopen.Text = "إعادة فتح";
        btnReopen.Size = new Size(90, 30);
        btnReopen.Margin = new Padding(4);
        btnReopen.Dock = DockStyle.None;
        btnReopen.Font = new Font("Microsoft Sans Serif", 10F);
        btnReopen.FlatStyle = FlatStyle.Flat;
        btnReopen.BackColor = Color.FromArgb(224, 224, 224);
        btnReopen.Enabled = false;
        btnReopen.Name = "btnReopen";
        actions.Controls.Add(btnReopen);
        root.Controls.Add(designerCommandBar, 0, 1);
        filters = new TableLayoutPanel();
        filters.Dock = DockStyle.Fill;
        filters.ColumnCount = 4;
        filters.RowCount = 2;
        filters.Margin = new Padding(0);
        filters.Padding = new Padding(8);
        filters.Name = "filters";
        filters.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 115F));
        filters.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        filters.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 115F));
        filters.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        filters.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        filters.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        lblCompany = new Label();
        lblCompany.Text = "الشركة";
        lblCompany.Dock = DockStyle.Fill;
        lblCompany.TextAlign = ContentAlignment.MiddleRight;
        lblCompany.Margin = new Padding(3);
        lblCompany.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        lblCompany.Name = "lblCompany";
        filterCompany = new ComboBox();
        filterCompany.Dock = DockStyle.Fill;
        filterCompany.Margin = new Padding(3);
        filterCompany.Font = new Font("Segoe UI", 11F);
        filterCompany.Name = "filterCompany";
        filterCompany.DropDownStyle = ComboBoxStyle.DropDownList;
        filters.Controls.Add(lblCompany, 0, 0);
        filters.Controls.Add(filterCompany, 1, 0);
        lblStatus = new Label();
        lblStatus.Text = "الحالة";
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.TextAlign = ContentAlignment.MiddleRight;
        lblStatus.Margin = new Padding(3);
        lblStatus.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        lblStatus.Name = "lblStatus";
        filterStatus = new ComboBox();
        filterStatus.Dock = DockStyle.Fill;
        filterStatus.Margin = new Padding(3);
        filterStatus.Font = new Font("Segoe UI", 11F);
        filterStatus.Name = "filterStatus";
        filterStatus.DropDownStyle = ComboBoxStyle.DropDownList;
        filters.Controls.Add(lblStatus, 2, 0);
        filters.Controls.Add(filterStatus, 3, 0);
        lblStartDate = new Label();
        lblStartDate.Text = "من تاريخ";
        lblStartDate.Dock = DockStyle.Fill;
        lblStartDate.TextAlign = ContentAlignment.MiddleRight;
        lblStartDate.Margin = new Padding(3);
        lblStartDate.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        lblStartDate.Name = "lblStartDate";
        filterStartDate = new DateTimePicker();
        filterStartDate.Dock = DockStyle.Fill;
        filterStartDate.Margin = new Padding(3);
        filterStartDate.Font = new Font("Segoe UI", 11F);
        filterStartDate.Name = "filterStartDate";
        filterStartDate.Format = DateTimePickerFormat.Short;
        filterStartDate.ShowCheckBox = true;
        filterStartDate.Checked = false;
        filters.Controls.Add(lblStartDate, 0, 1);
        filters.Controls.Add(filterStartDate, 1, 1);
        lblEndDate = new Label();
        lblEndDate.Text = "إلى تاريخ";
        lblEndDate.Dock = DockStyle.Fill;
        lblEndDate.TextAlign = ContentAlignment.MiddleRight;
        lblEndDate.Margin = new Padding(3);
        lblEndDate.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        lblEndDate.Name = "lblEndDate";
        filterEndDate = new DateTimePicker();
        filterEndDate.Dock = DockStyle.Fill;
        filterEndDate.Margin = new Padding(3);
        filterEndDate.Font = new Font("Segoe UI", 11F);
        filterEndDate.Name = "filterEndDate";
        filterEndDate.Format = DateTimePickerFormat.Short;
        filterEndDate.ShowCheckBox = true;
        filterEndDate.Checked = false;
        filters.Controls.Add(lblEndDate, 2, 1);
        filters.Controls.Add(filterEndDate, 3, 1);
        root.Controls.Add(filters, 0, 2);
        years = new DataGridView();
        years.Dock = DockStyle.Fill;
        years.ReadOnly = true;
        years.AutoGenerateColumns = false;
        years.AllowUserToAddRows = false;
        years.AllowUserToDeleteRows = false;
        years.RowHeadersVisible = false;
        years.MultiSelect = false;
        years.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        years.BackgroundColor = Color.White;
        years.Font = new Font("Segoe UI", 10F);
        years.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        years.Name = "years";
        colCode = new DataGridViewTextBoxColumn();
        colCode.DataPropertyName = "Code";
        colCode.HeaderText = "رمز السنة";
        colCode.ReadOnly = true;
        colCode.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colCode.MinimumWidth = 120;
        colCode.Name = "colCode";
        years.Columns.Add(colCode);
        colStartDate = new DataGridViewTextBoxColumn();
        colStartDate.DataPropertyName = "StartDate";
        colStartDate.HeaderText = "بداية السنة";
        colStartDate.ReadOnly = true;
        colStartDate.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colStartDate.MinimumWidth = 120;
        colStartDate.Name = "colStartDate";
        years.Columns.Add(colStartDate);
        colEndDate = new DataGridViewTextBoxColumn();
        colEndDate.DataPropertyName = "EndDate";
        colEndDate.HeaderText = "نهاية السنة";
        colEndDate.ReadOnly = true;
        colEndDate.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colEndDate.MinimumWidth = 120;
        colEndDate.Name = "colEndDate";
        years.Columns.Add(colEndDate);
        colStatus = new DataGridViewTextBoxColumn();
        colStatus.DataPropertyName = "Status";
        colStatus.HeaderText = "الحالة";
        colStatus.ReadOnly = true;
        colStatus.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colStatus.MinimumWidth = 120;
        colStatus.Name = "colStatus";
        years.Columns.Add(colStatus);
        root.Controls.Add(years, 0, 3);
        paging = new FlowLayoutPanel();
        paging.Dock = DockStyle.Fill;
        paging.WrapContents = false;
        paging.AutoScroll = true;
        paging.Name = "paging";
        btnPrevious = new Button();
        btnPrevious.Text = "السابق";
        btnPrevious.Size = new Size(70, 30);
        btnPrevious.Margin = new Padding(4);
        btnPrevious.Enabled = false;
        btnPrevious.Name = "btnPrevious";
        paging.Controls.Add(btnPrevious);
        btnNext = new Button();
        btnNext.Text = "التالي";
        btnNext.Size = new Size(70, 30);
        btnNext.Margin = new Padding(4);
        btnNext.Enabled = false;
        btnNext.Name = "btnNext";
        paging.Controls.Add(btnNext);
        lblPage = new Label();
        lblPage.Text = "لا توجد صفحة محمّلة";
        lblPage.AutoSize = true;
        lblPage.Margin = new Padding(8);
        lblPage.Name = "lblPage";
        paging.Controls.Add(lblPage);
        root.Controls.Add(paging, 0, 4);
        approval = new TableLayoutPanel();
        approval.Dock = DockStyle.Fill;
        approval.ColumnCount = 2;
        approval.RowCount = 2;
        approval.Margin = new Padding(0);
        approval.Padding = new Padding(8);
        approval.Name = "approval";
        approval.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        approval.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        approval.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        approval.RowStyles.Add(new RowStyle(SizeType.Absolute, 72F));
        lblAction = new Label();
        lblAction.Text = "الإجراء المسموح";
        lblAction.Dock = DockStyle.Fill;
        lblAction.TextAlign = ContentAlignment.MiddleRight;
        lblAction.Margin = new Padding(3);
        lblAction.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        lblAction.Name = "lblAction";
        cboAction = new ComboBox();
        cboAction.Dock = DockStyle.Fill;
        cboAction.DropDownStyle = ComboBoxStyle.DropDownList;
        cboAction.Enabled = false;
        cboAction.Margin = new Padding(3);
        cboAction.Font = new Font("Segoe UI", 11F);
        cboAction.Name = "cboAction";
        approval.Controls.Add(lblAction, 0, 0);
        approval.Controls.Add(cboAction, 1, 0);
        lblReason = new Label();
        lblReason.Text = "سبب الطلب";
        lblReason.Dock = DockStyle.Fill;
        lblReason.TextAlign = ContentAlignment.MiddleRight;
        lblReason.Margin = new Padding(3);
        lblReason.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        lblReason.Name = "lblReason";
        txtReason = new TextBox();
        txtReason.Dock = DockStyle.Fill;
        txtReason.Multiline = true;
        txtReason.ScrollBars = ScrollBars.Vertical;
        txtReason.Margin = new Padding(3);
        txtReason.Font = new Font("Segoe UI", 11F);
        txtReason.Name = "txtReason";
        approval.Controls.Add(lblReason, 0, 1);
        approval.Controls.Add(txtReason, 1, 1);
        root.Controls.Add(approval, 0, 5);
        audit = new TableLayoutPanel();
        audit.Dock = DockStyle.Fill;
        audit.ColumnCount = 7;
        audit.RowCount = 1;
        audit.Margin = new Padding(0);
        audit.Padding = new Padding(8);
        audit.Name = "audit";
        audit.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 14F));
        audit.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16F));
        audit.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 14F));
        audit.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16F));
        audit.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 12F));
        audit.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16F));
        audit.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 12F));
        audit.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        audit0 = new Label();
        audit0.Text = "أنشأ بواسطة: —";
        audit0.Dock = DockStyle.Fill;
        audit0.TextAlign = ContentAlignment.MiddleRight;
        audit0.Margin = new Padding(3);
        audit0.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        audit0.Name = "audit0";
        audit0.Font = new Font("Segoe UI", 10F);
        audit0.BackColor = Color.FromArgb(192, 255, 255);
        audit0.AutoEllipsis = true;
        audit.Controls.Add(audit0, 0, 0);
        audit1 = new Label();
        audit1.Text = "تاريخ الإنشاء: —";
        audit1.Dock = DockStyle.Fill;
        audit1.TextAlign = ContentAlignment.MiddleRight;
        audit1.Margin = new Padding(3);
        audit1.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        audit1.Name = "audit1";
        audit1.Font = new Font("Segoe UI", 10F);
        audit1.BackColor = Color.FromArgb(192, 255, 255);
        audit1.AutoEllipsis = true;
        audit.Controls.Add(audit1, 1, 0);
        audit2 = new Label();
        audit2.Text = "عدّل بواسطة: —";
        audit2.Dock = DockStyle.Fill;
        audit2.TextAlign = ContentAlignment.MiddleRight;
        audit2.Margin = new Padding(3);
        audit2.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        audit2.Name = "audit2";
        audit2.Font = new Font("Segoe UI", 10F);
        audit2.BackColor = Color.FromArgb(192, 255, 255);
        audit2.AutoEllipsis = true;
        audit.Controls.Add(audit2, 2, 0);
        audit3 = new Label();
        audit3.Text = "تاريخ التعديل: —";
        audit3.Dock = DockStyle.Fill;
        audit3.TextAlign = ContentAlignment.MiddleRight;
        audit3.Margin = new Padding(3);
        audit3.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        audit3.Name = "audit3";
        audit3.Font = new Font("Segoe UI", 10F);
        audit3.BackColor = Color.FromArgb(192, 255, 255);
        audit3.AutoEllipsis = true;
        audit.Controls.Add(audit3, 3, 0);
        audit4 = new Label();
        audit4.Text = "عدد التعديلات: —";
        audit4.Dock = DockStyle.Fill;
        audit4.TextAlign = ContentAlignment.MiddleRight;
        audit4.Margin = new Padding(3);
        audit4.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        audit4.Name = "audit4";
        audit4.Font = new Font("Segoe UI", 10F);
        audit4.BackColor = Color.FromArgb(192, 255, 255);
        audit4.AutoEllipsis = true;
        audit.Controls.Add(audit4, 4, 0);
        audit5 = new Label();
        audit5.Text = "آخر طباعة: —";
        audit5.Dock = DockStyle.Fill;
        audit5.TextAlign = ContentAlignment.MiddleRight;
        audit5.Margin = new Padding(3);
        audit5.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        audit5.Name = "audit5";
        audit5.Font = new Font("Segoe UI", 10F);
        audit5.BackColor = Color.FromArgb(192, 255, 255);
        audit5.AutoEllipsis = true;
        audit.Controls.Add(audit5, 5, 0);
        audit6 = new Label();
        audit6.Text = "عدد مرات الطباعة: —";
        audit6.Dock = DockStyle.Fill;
        audit6.TextAlign = ContentAlignment.MiddleRight;
        audit6.Margin = new Padding(3);
        audit6.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        audit6.Name = "audit6";
        audit6.Font = new Font("Segoe UI", 10F);
        audit6.BackColor = Color.FromArgb(192, 255, 255);
        audit6.AutoEllipsis = true;
        audit.Controls.Add(audit6, 6, 0);
        root.Controls.Add(approvalHistoryHost, 0, 6);
        root.Controls.Add(audit, 0, 7);
        AutoScaleDimensions = new SizeF(120F, 120F);
        AutoScaleMode = AutoScaleMode.Dpi;
        RightToLeft = RightToLeft.Yes;
        Font = new Font("Segoe UI", 10F);
        BackColor = Color.LightCyan;
        Size = new Size(1200, 1060);
        MinimumSize = new Size(1000, 940);
        Name = "UcScreen_02_04_06";
        Text = "السنوات المالية";
        Controls.Add(root);
        lblTitle.TabIndex = 0;
        actions.TabIndex = 1;
        filters.TabIndex = 2;
        years.TabIndex = 3;
        paging.TabIndex = 4;
        approval.TabIndex = 5;
        approvalHistoryHost.TabIndex = 6;
        audit.TabIndex = 7;
        lblCompany.TabIndex = 0;
        filterCompany.TabIndex = 1;
        lblStatus.TabIndex = 2;
        filterStatus.TabIndex = 3;
        lblStartDate.TabIndex = 4;
        filterStartDate.TabIndex = 5;
        lblEndDate.TabIndex = 6;
        filterEndDate.TabIndex = 7;
        lblAction.TabIndex = 0;
        cboAction.TabIndex = 1;
        lblReason.TabIndex = 2;
        txtReason.TabIndex = 3;
        audit0.TabIndex = 0;
        audit1.TabIndex = 1;
        audit2.TabIndex = 2;
        audit3.TabIndex = 3;
        audit4.TabIndex = 4;
        audit5.TabIndex = 5;
        audit6.TabIndex = 6;
        btnView.TabIndex = 0;
        btnExecute.TabIndex = 1;
        btnApprove.TabIndex = 2;
        btnReject.TabIndex = 3;
        btnReturn.TabIndex = 4;
        btnReopen.TabIndex = 5;
        btnPrevious.TabIndex = 0;
        btnNext.TabIndex = 1;
        lblPage.TabIndex = 2;
        ResumeLayout(true);
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Fill;
        designerCommandBar.MinimumSize = new Size(0, 48);
        designerCommandBar.TabIndex = 1;
        designerCommandBar.Controls.Add(actions);
        actions.Dock = DockStyle.Fill;
        actions.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        actions.Name = "actions";
        actions.Dock = DockStyle.Fill;
        actions.AutoSize = false;
        actions.WrapContents = false;
        actions.FlowDirection = FlowDirection.RightToLeft;
        actions.RightToLeft = RightToLeft.No;
        actions.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 44;
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = false;
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = false;
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = false;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = false;
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = false;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = false;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = false;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = false;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandSave.Name = "standardCommandSave";
        standardCommandSave.Enabled = false;
        standardCommandSave.Visible = false;
        standardCommandSave.AccessibleName = "حفظ";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandClose.Name = "standardCommandClose";
        standardCommandClose.Enabled = false;
        standardCommandClose.Visible = true;
        standardCommandClose.AccessibleName = "إغلاق";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = true;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = true;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandAdd.AutoSize = false;
        standardCommandAdd.Dock = DockStyle.None;
        standardCommandAdd.MinimumSize = Size.Empty;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandAdd.Text = "";
        actions.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.AutoSize = false;
        standardCommandEdit.Dock = DockStyle.None;
        standardCommandEdit.MinimumSize = Size.Empty;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandEdit.Text = "";
        actions.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        actions.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.AutoSize = false;
        standardCommandCancel.Dock = DockStyle.None;
        standardCommandCancel.MinimumSize = Size.Empty;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandCancel.Text = "";
        actions.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        btnView.AutoSize = false;
        btnView.Dock = DockStyle.None;
        btnView.MinimumSize = Size.Empty;
        btnView.Size = new Size(26, 24);
        btnView.Margin = new Padding(1);
        btnView.FlatStyle = FlatStyle.Flat;
        btnView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        btnView.Text = "";
        actions.Controls.Add(btnView);
        designerCommandBar.SetCommandRole(btnView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        actions.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        actions.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        actions.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        actions.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        standardCommandSave.AutoSize = false;
        standardCommandSave.Dock = DockStyle.None;
        standardCommandSave.MinimumSize = Size.Empty;
        standardCommandSave.Size = new Size(26, 24);
        standardCommandSave.Margin = new Padding(1);
        standardCommandSave.FlatStyle = FlatStyle.Flat;
        standardCommandSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        standardCommandSave.Text = "";
        actions.Controls.Add(standardCommandSave);
        designerCommandBar.SetCommandRole(standardCommandSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        actions.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        standardCommandClose.AutoSize = false;
        standardCommandClose.Dock = DockStyle.None;
        standardCommandClose.MinimumSize = Size.Empty;
        standardCommandClose.Size = new Size(26, 24);
        standardCommandClose.Margin = new Padding(1);
        standardCommandClose.FlatStyle = FlatStyle.Flat;
        standardCommandClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        standardCommandClose.Text = "";
        designerCloseHost.Controls.Add(standardCommandClose);
        standardCommandClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(standardCommandClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        actions.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        actions.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        actions.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        actions.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        audit.Visible = false;
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}
}
