#nullable enable
using System.Drawing;
using System.Windows.Forms;
namespace TransportERP.EmptyForms;
partial class UcScreen_04_11_04
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandSave = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private FlowLayoutPanel flpActions = null!;
    private Button btnView = null!;
    private Button btnCreate = null!;
    private Button btnEdit = null!;
    private Button btnCancel = null!;
    private Button btnReverse = null!;
    private Button btnClear = null!;
    private Button btnClose = null!;
    private TabControl tabs = null!;
    private Label lblStatus = null!;
    private TabPage tp0 = null!;
    private TableLayoutPanel layout0 = null!;
    private TextBox field_reversalRequestNumber = null!;
    private Label lbl_reversalRequestNumber = null!;
    private ComboBox field_originalEntryRef = null!;
    private Label lbl_originalEntryRef = null!;
    private TextBox field_originalEntryNumber = null!;
    private Label lbl_originalEntryNumber = null!;
    private TextBox field_originalEntryDate = null!;
    private Label lbl_originalEntryDate = null!;
    private TextBox field_reversalReason = null!;
    private Label lbl_reversalReason = null!;
    private DateTimePicker field_reversalDate = null!;
    private Label lbl_reversalDate = null!;
    private ComboBox field_reversalPolicy = null!;
    private Label lbl_reversalPolicy = null!;
    private TextBox field_reversingEntryRef = null!;
    private Label lbl_reversingEntryRef = null!;
    private TextBox field_reversingEntryNumber = null!;
    private Label lbl_reversingEntryNumber = null!;
    private TextBox field_reversalState = null!;
    private Label lbl_reversalState = null!;
    private TabPage tp1 = null!;
    private TableLayoutPanel layout1 = null!;
    private DataGridView dgvLines = null!;
    private DataGridViewTextBoxColumn col_rowNo = null!;
    private DataGridViewTextBoxColumn col_accountRef = null!;
    private DataGridViewTextBoxColumn col_costCenterRef = null!;
    private DataGridViewTextBoxColumn col_lineDescription = null!;
    private DataGridViewTextBoxColumn col_debit = null!;
    private DataGridViewTextBoxColumn col_credit = null!;
    private DataGridViewTextBoxColumn col_currencyRef = null!;
    private DataGridViewTextBoxColumn col_exchangeRate = null!;
    private DataGridViewTextBoxColumn col_accountingAmount = null!;
    private TableLayoutPanel linesHost = null!;
    private TabPage tp2 = null!;
    private TableLayoutPanel layout2 = null!;
    private RichTextBox context2 = null!;
    private TabPage tp3 = null!;
    private TableLayoutPanel layout3 = null!;
    private RichTextBox context3 = null!;
    private TabPage tp4 = null!;
    private TableLayoutPanel layout4 = null!;
    private RichTextBox context4 = null!;
    private System.ComponentModel.IContainer? components;
    private ErrorProvider validationErrors = null!;
    protected override void Dispose(bool disposing) { if(disposing) components?.Dispose(); base.Dispose(disposing); }
    private DataGridViewTextBoxColumn reverse_rowNo = null!;
    private DataGridViewTextBoxColumn reverse_accountRef = null!;
    private DataGridViewTextBoxColumn reverse_costCenterRef = null!;
    private DataGridViewTextBoxColumn reverse_lineDescription = null!;
    private DataGridViewTextBoxColumn reverse_debit = null!;
    private DataGridViewTextBoxColumn reverse_credit = null!;
    private DataGridViewTextBoxColumn reverse_currencyRef = null!;
    private DataGridViewTextBoxColumn reverse_exchangeRate = null!;
    private DataGridViewTextBoxColumn reverse_accountingAmount = null!;
    private TabControl entryViews = null!;
    private TabPage originalView = null!, reversingView = null!;
    private DataGridView dgvReversing = null!;
    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandDelete = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandSave = new Button();
        standardCommandPrint = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        components = new System.ComponentModel.Container();
        validationErrors = new ErrorProvider(components);
        validationErrors.ContainerControl = this;
        validationErrors.BlinkStyle = ErrorBlinkStyle.NeverBlink;
        mainLayout = new TableLayoutPanel();
        lblTitle = new Label();
        flpActions = new FlowLayoutPanel();
        btnView = new Button();
        btnCreate = new Button();
        btnEdit = new Button();
        btnCancel = new Button();
        btnReverse = new Button();
        btnClear = new Button();
        btnClose = new Button();
        tabs = new TabControl();
        lblStatus = new Label();
        tp0 = new TabPage();
        layout0 = new TableLayoutPanel();
        field_reversalRequestNumber = new TextBox();
        lbl_reversalRequestNumber = new Label();
        field_originalEntryRef = new ComboBox();
        lbl_originalEntryRef = new Label();
        field_originalEntryNumber = new TextBox();
        lbl_originalEntryNumber = new Label();
        field_originalEntryDate = new TextBox();
        lbl_originalEntryDate = new Label();
        field_reversalReason = new TextBox();
        lbl_reversalReason = new Label();
        field_reversalDate = new DateTimePicker();
        lbl_reversalDate = new Label();
        field_reversalPolicy = new ComboBox();
        lbl_reversalPolicy = new Label();
        field_reversingEntryRef = new TextBox();
        lbl_reversingEntryRef = new Label();
        field_reversingEntryNumber = new TextBox();
        lbl_reversingEntryNumber = new Label();
        field_reversalState = new TextBox();
        lbl_reversalState = new Label();
        tp1 = new TabPage();
        layout1 = new TableLayoutPanel();
        dgvLines = new DataGridView();
        col_rowNo = new DataGridViewTextBoxColumn();
        col_accountRef = new DataGridViewTextBoxColumn();
        col_costCenterRef = new DataGridViewTextBoxColumn();
        col_lineDescription = new DataGridViewTextBoxColumn();
        col_debit = new DataGridViewTextBoxColumn();
        col_credit = new DataGridViewTextBoxColumn();
        col_currencyRef = new DataGridViewTextBoxColumn();
        col_exchangeRate = new DataGridViewTextBoxColumn();
        col_accountingAmount = new DataGridViewTextBoxColumn();
        linesHost = new TableLayoutPanel();
        tp2 = new TabPage();
        layout2 = new TableLayoutPanel();
        context2 = new RichTextBox();
        tp3 = new TabPage();
        layout3 = new TableLayoutPanel();
        context3 = new RichTextBox();
        tp4 = new TabPage();
        layout4 = new TableLayoutPanel();
        context4 = new RichTextBox();
        SuspendLayout();
        mainLayout.Name = "mainLayout";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "القيود العكسية وربط القيد الأصلي بالقيد العاكس";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Padding = new Padding(8);
        lblTitle.TabStop = false;
        mainLayout.Controls.Add(lblTitle, 0, 0);
        flpActions.Name = "flpActions";
        flpActions.AutoSize = true;
        flpActions.Dock = DockStyle.Fill;
        flpActions.WrapContents = true;
        flpActions.FlowDirection = FlowDirection.LeftToRight;
        flpActions.RightToLeft = RightToLeft.Yes;
        mainLayout.Controls.Add(designerCommandBar, 0, 1);
        btnView.Name = "btnView";
        btnView.Text = "عرض / إعادة تحميل";
        btnView.AutoSize = true;
        btnView.MinimumSize = new Size(100,32);
        btnView.TabIndex = 0;
        btnView.AccessibleName = "عرض / إعادة تحميل";

        btnView.Enabled = false;
        btnCreate.Name = "btnCreate";
        btnCreate.Text = "حفظ جديد";
        btnCreate.AutoSize = true;
        btnCreate.MinimumSize = new Size(100,32);
        btnCreate.TabIndex = 1;
        btnCreate.AccessibleName = "حفظ جديد";
        flpActions.Controls.Add(btnCreate);
        btnCreate.Enabled = false;
        btnEdit.Name = "btnEdit";
        btnEdit.Text = "حفظ التعديل";
        btnEdit.AutoSize = true;
        btnEdit.MinimumSize = new Size(100,32);
        btnEdit.TabIndex = 2;
        btnEdit.AccessibleName = "حفظ التعديل";

        btnEdit.Enabled = false;
        btnCancel.Name = "btnCancel";
        btnCancel.Text = "إلغاء المستند";
        btnCancel.AutoSize = true;
        btnCancel.MinimumSize = new Size(100,32);
        btnCancel.TabIndex = 3;
        btnCancel.AccessibleName = "إلغاء المستند";

        btnCancel.Enabled = false;
        btnReverse.Name = "btnReverse";
        btnReverse.Text = "عكس القيد";
        btnReverse.AutoSize = true;
        btnReverse.MinimumSize = new Size(100,32);
        btnReverse.TabIndex = 4;
        btnReverse.AccessibleName = "عكس القيد";
        flpActions.Controls.Add(btnReverse);
        btnReverse.Enabled = false;
        btnClear.Name = "btnClear";
        btnClear.Text = "تفريغ المسودة";
        btnClear.AutoSize = true;
        btnClear.MinimumSize = new Size(100,32);
        btnClear.TabIndex = 5;
        btnClear.AccessibleName = "تفريغ المسودة";
        flpActions.Controls.Add(btnClear);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.AutoSize = true;
        btnClose.MinimumSize = new Size(100,32);
        btnClose.TabIndex = 6;
        btnClose.AccessibleName = "إغلاق";

        tabs.Name = "tabs";
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeftLayout = true;
        tabs.Multiline = true;
        tabs.TabIndex = 1;
        mainLayout.Controls.Add(tabs, 0, 2);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "مسودة واجهة غير محفوظة — الخدمات غير موصولة";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.Padding = new Padding(6);
        mainLayout.Controls.Add(lblStatus, 0, 3);
        tp0.Name = "tp0";
        tp0.Text = "البيانات الرئيسية";
        tp0.AutoScroll = true;
        tp0.TabIndex = 0;
        tabs.Controls.Add(tp0);
        layout0.Name = "layout0";
        layout0.Dock = DockStyle.Top;
        layout0.AutoSize = true;
        layout0.ColumnCount = 2;
        layout0.MinimumSize = new Size(650,0);
        layout0.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp0.Controls.Add(layout0);
        field_reversalRequestNumber.Name = "field_reversalRequestNumber";
        lbl_reversalRequestNumber.Name = "lbl_reversalRequestNumber";
        field_reversalRequestNumber.AccessibleName = "رقم طلب العكس";
        field_reversalRequestNumber.Tag = "ACC-056:reversalRequestNumber";
        field_reversalRequestNumber.Dock = DockStyle.Fill;
        field_reversalRequestNumber.TabIndex = 0;
        lbl_reversalRequestNumber.Text = "رقم طلب العكس";
        lbl_reversalRequestNumber.AutoSize = true;
        lbl_reversalRequestNumber.Dock = DockStyle.Fill;
        lbl_reversalRequestNumber.TextAlign = ContentAlignment.MiddleRight;
        lbl_reversalRequestNumber.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_reversalRequestNumber, 0, 0);
        layout0.Controls.Add(field_reversalRequestNumber, 1, 0);
        field_reversalRequestNumber.ReadOnly = true;
        field_reversalRequestNumber.TabStop = false;
        field_originalEntryRef.Name = "field_originalEntryRef";
        lbl_originalEntryRef.Name = "lbl_originalEntryRef";
        field_originalEntryRef.AccessibleName = "القيد الأصلي";
        field_originalEntryRef.Tag = "ACC-056:originalEntryRef";
        field_originalEntryRef.Dock = DockStyle.Fill;
        field_originalEntryRef.TabIndex = 1;
        lbl_originalEntryRef.Text = "القيد الأصلي";
        lbl_originalEntryRef.AutoSize = true;
        lbl_originalEntryRef.Dock = DockStyle.Fill;
        lbl_originalEntryRef.TextAlign = ContentAlignment.MiddleRight;
        lbl_originalEntryRef.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_originalEntryRef, 0, 1);
        layout0.Controls.Add(field_originalEntryRef, 1, 1);
        field_originalEntryRef.DropDownStyle = ComboBoxStyle.DropDownList;
        field_originalEntryRef.DropDownWidth = 420;
        field_originalEntryRef.BackColor = Color.LightYellow;
        field_originalEntryNumber.Name = "field_originalEntryNumber";
        lbl_originalEntryNumber.Name = "lbl_originalEntryNumber";
        field_originalEntryNumber.AccessibleName = "رقم القيد الأصلي";
        field_originalEntryNumber.Tag = "ACC-056:originalEntryNumber";
        field_originalEntryNumber.Dock = DockStyle.Fill;
        field_originalEntryNumber.TabIndex = 2;
        lbl_originalEntryNumber.Text = "رقم القيد الأصلي";
        lbl_originalEntryNumber.AutoSize = true;
        lbl_originalEntryNumber.Dock = DockStyle.Fill;
        lbl_originalEntryNumber.TextAlign = ContentAlignment.MiddleRight;
        lbl_originalEntryNumber.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_originalEntryNumber, 0, 2);
        layout0.Controls.Add(field_originalEntryNumber, 1, 2);
        field_originalEntryNumber.ReadOnly = true;
        field_originalEntryNumber.TabStop = false;
        field_originalEntryDate.Name = "field_originalEntryDate";
        lbl_originalEntryDate.Name = "lbl_originalEntryDate";
        field_originalEntryDate.AccessibleName = "تاريخ القيد الأصلي";
        field_originalEntryDate.Tag = "ACC-056:originalEntryDate";
        field_originalEntryDate.Dock = DockStyle.Fill;
        field_originalEntryDate.TabIndex = 3;
        lbl_originalEntryDate.Text = "تاريخ القيد الأصلي";
        lbl_originalEntryDate.AutoSize = true;
        lbl_originalEntryDate.Dock = DockStyle.Fill;
        lbl_originalEntryDate.TextAlign = ContentAlignment.MiddleRight;
        lbl_originalEntryDate.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_originalEntryDate, 0, 3);
        layout0.Controls.Add(field_originalEntryDate, 1, 3);
        field_originalEntryDate.ReadOnly = true;
        field_originalEntryDate.TabStop = false;
        field_reversalReason.Name = "field_reversalReason";
        lbl_reversalReason.Name = "lbl_reversalReason";
        field_reversalReason.AccessibleName = "سبب العكس";
        field_reversalReason.Tag = "ACC-056:reversalReason";
        field_reversalReason.Dock = DockStyle.Fill;
        field_reversalReason.TabIndex = 4;
        lbl_reversalReason.Text = "سبب العكس";
        lbl_reversalReason.AutoSize = true;
        lbl_reversalReason.Dock = DockStyle.Fill;
        lbl_reversalReason.TextAlign = ContentAlignment.MiddleRight;
        lbl_reversalReason.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_reversalReason, 0, 4);
        layout0.Controls.Add(field_reversalReason, 1, 4);
        field_reversalReason.Multiline = true;
        field_reversalReason.Height = 70;
        field_reversalReason.ScrollBars = ScrollBars.Vertical;
        field_reversalReason.BackColor = Color.LightYellow;
        field_reversalDate.Name = "field_reversalDate";
        lbl_reversalDate.Name = "lbl_reversalDate";
        field_reversalDate.AccessibleName = "تاريخ العكس";
        field_reversalDate.Tag = "ACC-056:reversalDate";
        field_reversalDate.Dock = DockStyle.Fill;
        field_reversalDate.TabIndex = 5;
        lbl_reversalDate.Text = "تاريخ العكس";
        lbl_reversalDate.AutoSize = true;
        lbl_reversalDate.Dock = DockStyle.Fill;
        lbl_reversalDate.TextAlign = ContentAlignment.MiddleRight;
        lbl_reversalDate.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_reversalDate, 0, 5);
        layout0.Controls.Add(field_reversalDate, 1, 5);
        field_reversalDate.Format = DateTimePickerFormat.Custom;
        field_reversalDate.CustomFormat = "yyyy-MM-dd";
        field_reversalDate.ShowCheckBox = true;
        field_reversalDate.Checked = false;
        field_reversalDate.BackColor = Color.LightYellow;
        field_reversalPolicy.Name = "field_reversalPolicy";
        lbl_reversalPolicy.Name = "lbl_reversalPolicy";
        field_reversalPolicy.AccessibleName = "سياسة العكس";
        field_reversalPolicy.Tag = "ACC-056:reversalPolicy";
        field_reversalPolicy.Dock = DockStyle.Fill;
        field_reversalPolicy.TabIndex = 6;
        lbl_reversalPolicy.Text = "سياسة العكس";
        lbl_reversalPolicy.AutoSize = true;
        lbl_reversalPolicy.Dock = DockStyle.Fill;
        lbl_reversalPolicy.TextAlign = ContentAlignment.MiddleRight;
        lbl_reversalPolicy.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_reversalPolicy, 0, 6);
        layout0.Controls.Add(field_reversalPolicy, 1, 6);
        field_reversalPolicy.DropDownStyle = ComboBoxStyle.DropDownList;
        field_reversalPolicy.DropDownWidth = 420;
        field_reversalPolicy.BackColor = Color.LightYellow;
        field_reversingEntryRef.Name = "field_reversingEntryRef";
        lbl_reversingEntryRef.Name = "lbl_reversingEntryRef";
        field_reversingEntryRef.AccessibleName = "القيد العاكس";
        field_reversingEntryRef.Tag = "ACC-056:reversingEntryRef";
        field_reversingEntryRef.Dock = DockStyle.Fill;
        field_reversingEntryRef.TabIndex = 7;
        lbl_reversingEntryRef.Text = "القيد العاكس";
        lbl_reversingEntryRef.AutoSize = true;
        lbl_reversingEntryRef.Dock = DockStyle.Fill;
        lbl_reversingEntryRef.TextAlign = ContentAlignment.MiddleRight;
        lbl_reversingEntryRef.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_reversingEntryRef, 0, 7);
        layout0.Controls.Add(field_reversingEntryRef, 1, 7);
        field_reversingEntryRef.ReadOnly = true;
        field_reversingEntryRef.TabStop = false;
        field_reversingEntryNumber.Name = "field_reversingEntryNumber";
        lbl_reversingEntryNumber.Name = "lbl_reversingEntryNumber";
        field_reversingEntryNumber.AccessibleName = "رقم القيد العاكس";
        field_reversingEntryNumber.Tag = "ACC-056:reversingEntryNumber";
        field_reversingEntryNumber.Dock = DockStyle.Fill;
        field_reversingEntryNumber.TabIndex = 8;
        lbl_reversingEntryNumber.Text = "رقم القيد العاكس";
        lbl_reversingEntryNumber.AutoSize = true;
        lbl_reversingEntryNumber.Dock = DockStyle.Fill;
        lbl_reversingEntryNumber.TextAlign = ContentAlignment.MiddleRight;
        lbl_reversingEntryNumber.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_reversingEntryNumber, 0, 8);
        layout0.Controls.Add(field_reversingEntryNumber, 1, 8);
        field_reversingEntryNumber.ReadOnly = true;
        field_reversingEntryNumber.TabStop = false;
        field_reversalState.Name = "field_reversalState";
        lbl_reversalState.Name = "lbl_reversalState";
        field_reversalState.AccessibleName = "حالة العكس";
        field_reversalState.Tag = "ACC-056:reversalState";
        field_reversalState.Dock = DockStyle.Fill;
        field_reversalState.TabIndex = 9;
        lbl_reversalState.Text = "حالة العكس";
        lbl_reversalState.AutoSize = true;
        lbl_reversalState.Dock = DockStyle.Fill;
        lbl_reversalState.TextAlign = ContentAlignment.MiddleRight;
        lbl_reversalState.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_reversalState, 0, 9);
        layout0.Controls.Add(field_reversalState, 1, 9);
        field_reversalState.ReadOnly = true;
        field_reversalState.TabStop = false;
        layout0.RowCount = 10;
        tp1.Name = "tp1";
        tp1.Text = "القيد الأصلي والقيد العاكس";
        tp1.AutoScroll = true;
        tp1.TabIndex = 1;
        tabs.Controls.Add(tp1);
        layout1.Name = "layout1";
        layout1.Dock = DockStyle.Top;
        layout1.AutoSize = true;
        layout1.ColumnCount = 2;
        layout1.MinimumSize = new Size(650,0);
        layout1.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp1.Controls.Add(layout1);
        layout1.RowCount = 0;
        dgvLines.Name = "dgvLines";
        dgvLines.Dock = DockStyle.Fill;
        dgvLines.MinimumSize = new Size(650,260);
        dgvLines.AutoGenerateColumns = false;
        dgvLines.AllowUserToAddRows = false;
        dgvLines.AllowUserToDeleteRows = false;
        dgvLines.AllowUserToOrderColumns = false;
        dgvLines.RowHeadersVisible = false;
        dgvLines.MultiSelect = false;
        dgvLines.SelectionMode = DataGridViewSelectionMode.CellSelect;
        dgvLines.AccessibleName = "القيد الأصلي والقيد العاكس";
        dgvLines.TabIndex = 1;
        col_rowNo.Name = "col_rowNo";
        col_rowNo.Name = "rowNo";
        col_rowNo.HeaderText = "#";
        col_rowNo.ReadOnly = true;
        col_rowNo.Tag = "text";
        col_rowNo.MinimumWidth = 90;
        col_rowNo.Width = 140;
        col_rowNo.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_rowNo);
        col_accountRef.Name = "col_accountRef";
        col_accountRef.Name = "accountRef";
        col_accountRef.HeaderText = "الحساب";
        col_accountRef.ReadOnly = true;
        col_accountRef.Tag = "text";
        col_accountRef.MinimumWidth = 90;
        col_accountRef.Width = 140;
        col_accountRef.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_accountRef);
        col_costCenterRef.Name = "col_costCenterRef";
        col_costCenterRef.Name = "costCenterRef";
        col_costCenterRef.HeaderText = "مركز التكلفة/الأبعاد";
        col_costCenterRef.ReadOnly = true;
        col_costCenterRef.Tag = "text";
        col_costCenterRef.MinimumWidth = 90;
        col_costCenterRef.Width = 140;
        col_costCenterRef.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_costCenterRef);
        col_lineDescription.Name = "col_lineDescription";
        col_lineDescription.Name = "lineDescription";
        col_lineDescription.HeaderText = "البيان";
        col_lineDescription.ReadOnly = true;
        col_lineDescription.Tag = "text";
        col_lineDescription.MinimumWidth = 90;
        col_lineDescription.Width = 140;
        col_lineDescription.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_lineDescription.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        dgvLines.Columns.Add(col_lineDescription);
        col_debit.Name = "col_debit";
        col_debit.Name = "debit";
        col_debit.HeaderText = "مدين";
        col_debit.ReadOnly = true;
        col_debit.Tag = "decimal";
        col_debit.MinimumWidth = 90;
        col_debit.Width = 140;
        col_debit.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_debit.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_debit);
        col_credit.Name = "col_credit";
        col_credit.Name = "credit";
        col_credit.HeaderText = "دائن";
        col_credit.ReadOnly = true;
        col_credit.Tag = "decimal";
        col_credit.MinimumWidth = 90;
        col_credit.Width = 140;
        col_credit.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_credit.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_credit);
        col_currencyRef.Name = "col_currencyRef";
        col_currencyRef.Name = "currencyRef";
        col_currencyRef.HeaderText = "العملة";
        col_currencyRef.ReadOnly = true;
        col_currencyRef.Tag = "text";
        col_currencyRef.MinimumWidth = 90;
        col_currencyRef.Width = 140;
        col_currencyRef.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_currencyRef);
        col_exchangeRate.Name = "col_exchangeRate";
        col_exchangeRate.Name = "exchangeRate";
        col_exchangeRate.HeaderText = "سعر الصرف";
        col_exchangeRate.ReadOnly = true;
        col_exchangeRate.Tag = "decimal";
        col_exchangeRate.MinimumWidth = 90;
        col_exchangeRate.Width = 140;
        col_exchangeRate.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_exchangeRate.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_exchangeRate);
        col_accountingAmount.Name = "col_accountingAmount";
        col_accountingAmount.Name = "accountingAmount";
        col_accountingAmount.HeaderText = "المبلغ المحاسبي";
        col_accountingAmount.ReadOnly = true;
        col_accountingAmount.Tag = "decimal";
        col_accountingAmount.MinimumWidth = 90;
        col_accountingAmount.Width = 140;
        col_accountingAmount.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_accountingAmount.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_accountingAmount);
        linesHost.Name = "linesHost";
        linesHost.Dock = DockStyle.Fill;
        linesHost.ColumnCount = 1;
        linesHost.RowCount = 3;
        linesHost.MinimumSize = new Size(680,380);
        linesHost.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        linesHost.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        linesHost.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        linesHost.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        tp1.Controls.Remove(layout1);
        linesHost.Controls.Add(layout1, 0, 0);
        tp1.Controls.Add(linesHost);
        linesHost.Controls.Add(dgvLines, 0, 2);
        tp2.Name = "tp2";
        tp2.Text = "المرفقات والربط بالمستندات";
        tp2.AutoScroll = true;
        tp2.TabIndex = 2;
        tabs.Controls.Add(tp2);
        layout2.Name = "layout2";
        layout2.Dock = DockStyle.Top;
        layout2.AutoSize = true;
        layout2.ColumnCount = 2;
        layout2.MinimumSize = new Size(650,0);
        layout2.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp2.Controls.Add(layout2);
        layout2.RowCount = 0;
        layout2.Dock = DockStyle.Fill;
        layout2.RowCount = 1;
        layout2.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        context2.Name = "context2";
        context2.ReadOnly = true;
        context2.Dock = DockStyle.Fill;
        context2.AccessibleName = "المرفقات والربط بالمستندات";
        context2.DetectUrls = false;
        layout2.Controls.Add(context2, 0, 0);
        layout2.SetColumnSpan(context2,2);
        tp3.Name = "tp3";
        tp3.Text = "الاعتمادات";
        tp3.AutoScroll = true;
        tp3.TabIndex = 3;
        tabs.Controls.Add(tp3);
        layout3.Name = "layout3";
        layout3.Dock = DockStyle.Top;
        layout3.AutoSize = true;
        layout3.ColumnCount = 2;
        layout3.MinimumSize = new Size(650,0);
        layout3.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout3.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp3.Controls.Add(layout3);
        layout3.RowCount = 0;
        layout3.Dock = DockStyle.Fill;
        layout3.RowCount = 1;
        layout3.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        context3.Name = "context3";
        context3.ReadOnly = true;
        context3.Dock = DockStyle.Fill;
        context3.AccessibleName = "الاعتمادات";
        context3.DetectUrls = false;
        layout3.Controls.Add(context3, 0, 0);
        layout3.SetColumnSpan(context3,2);
        tp4.Name = "tp4";
        tp4.Text = "سجل العمليات";
        tp4.AutoScroll = true;
        tp4.TabIndex = 4;
        tabs.Controls.Add(tp4);
        layout4.Name = "layout4";
        layout4.Dock = DockStyle.Top;
        layout4.AutoSize = true;
        layout4.ColumnCount = 2;
        layout4.MinimumSize = new Size(650,0);
        layout4.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout4.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp4.Controls.Add(layout4);
        layout4.RowCount = 0;
        layout4.Dock = DockStyle.Fill;
        layout4.RowCount = 1;
        layout4.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        context4.Name = "context4";
        context4.ReadOnly = true;
        context4.Dock = DockStyle.Fill;
        context4.AccessibleName = "سجل العمليات";
        context4.DetectUrls = false;
        layout4.Controls.Add(context4, 0, 0);
        layout4.SetColumnSpan(context4,2);
        entryViews=new TabControl();
        originalView=new TabPage();reversingView=new TabPage();dgvReversing=new DataGridView();
        entryViews.Name="entryViews";entryViews.Dock=DockStyle.Fill;entryViews.RightToLeftLayout=true;
        originalView.Name="originalView";originalView.Text="القيد الأصلي";
        reversingView.Name="reversingView";reversingView.Text="القيد العاكس";
        dgvReversing.Name="dgvReversing";dgvReversing.Dock=DockStyle.Fill;dgvReversing.ReadOnly=true;
        dgvReversing.AllowUserToAddRows=false;dgvReversing.AllowUserToDeleteRows=false;
        dgvReversing.AutoGenerateColumns=false;dgvReversing.RowHeadersVisible=false;
        dgvReversing.AccessibleName="تفاصيل القيد العاكس";
        linesHost.Controls.Remove(dgvLines);
        originalView.Controls.Add(dgvLines);reversingView.Controls.Add(dgvReversing);
        entryViews.Controls.Add(originalView);entryViews.Controls.Add(reversingView);
        linesHost.Controls.Add(entryViews,0,2);
        reverse_rowNo=new DataGridViewTextBoxColumn();
        reverse_rowNo.Name="rowNo";
        reverse_rowNo.HeaderText="#";
        reverse_rowNo.ReadOnly=true;
        reverse_rowNo.Width=140;
        reverse_rowNo.SortMode=DataGridViewColumnSortMode.NotSortable;
        dgvReversing.Columns.Add(reverse_rowNo);
        reverse_accountRef=new DataGridViewTextBoxColumn();
        reverse_accountRef.Name="accountRef";
        reverse_accountRef.HeaderText="الحساب";
        reverse_accountRef.ReadOnly=true;
        reverse_accountRef.Width=140;
        reverse_accountRef.SortMode=DataGridViewColumnSortMode.NotSortable;
        dgvReversing.Columns.Add(reverse_accountRef);
        reverse_costCenterRef=new DataGridViewTextBoxColumn();
        reverse_costCenterRef.Name="costCenterRef";
        reverse_costCenterRef.HeaderText="مركز التكلفة/الأبعاد";
        reverse_costCenterRef.ReadOnly=true;
        reverse_costCenterRef.Width=140;
        reverse_costCenterRef.SortMode=DataGridViewColumnSortMode.NotSortable;
        dgvReversing.Columns.Add(reverse_costCenterRef);
        reverse_lineDescription=new DataGridViewTextBoxColumn();
        reverse_lineDescription.Name="lineDescription";
        reverse_lineDescription.HeaderText="البيان";
        reverse_lineDescription.ReadOnly=true;
        reverse_lineDescription.Width=140;
        reverse_lineDescription.SortMode=DataGridViewColumnSortMode.NotSortable;
        dgvReversing.Columns.Add(reverse_lineDescription);
        reverse_debit=new DataGridViewTextBoxColumn();
        reverse_debit.Name="debit";
        reverse_debit.HeaderText="مدين";
        reverse_debit.ReadOnly=true;
        reverse_debit.Width=140;
        reverse_debit.SortMode=DataGridViewColumnSortMode.NotSortable;
        dgvReversing.Columns.Add(reverse_debit);
        reverse_credit=new DataGridViewTextBoxColumn();
        reverse_credit.Name="credit";
        reverse_credit.HeaderText="دائن";
        reverse_credit.ReadOnly=true;
        reverse_credit.Width=140;
        reverse_credit.SortMode=DataGridViewColumnSortMode.NotSortable;
        dgvReversing.Columns.Add(reverse_credit);
        reverse_currencyRef=new DataGridViewTextBoxColumn();
        reverse_currencyRef.Name="currencyRef";
        reverse_currencyRef.HeaderText="العملة";
        reverse_currencyRef.ReadOnly=true;
        reverse_currencyRef.Width=140;
        reverse_currencyRef.SortMode=DataGridViewColumnSortMode.NotSortable;
        dgvReversing.Columns.Add(reverse_currencyRef);
        reverse_exchangeRate=new DataGridViewTextBoxColumn();
        reverse_exchangeRate.Name="exchangeRate";
        reverse_exchangeRate.HeaderText="سعر الصرف";
        reverse_exchangeRate.ReadOnly=true;
        reverse_exchangeRate.Width=140;
        reverse_exchangeRate.SortMode=DataGridViewColumnSortMode.NotSortable;
        dgvReversing.Columns.Add(reverse_exchangeRate);
        reverse_accountingAmount=new DataGridViewTextBoxColumn();
        reverse_accountingAmount.Name="accountingAmount";
        reverse_accountingAmount.HeaderText="المبلغ المحاسبي";
        reverse_accountingAmount.ReadOnly=true;
        reverse_accountingAmount.Width=140;
        reverse_accountingAmount.SortMode=DataGridViewColumnSortMode.NotSortable;
        dgvReversing.Columns.Add(reverse_accountingAmount);
        AutoScaleDimensions = new SizeF(96F,96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Name = "UcScreen_04_11_04";
        Text = "القيود العكسية وربط القيد الأصلي بالقيد العاكس";
        Tag = "04.11.04";
        Size = new Size(1100,720);
        Controls.Add(mainLayout);
        ResumeLayout(false);
        PerformLayout();
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Fill;
        designerCommandBar.RightToLeft = RightToLeft.Yes;
        designerCommandBar.Controls.Add(flpActions);
        flpActions.Dock = DockStyle.Fill;
        flpActions.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        flpActions.Name = "flpActions";
        flpActions.Dock = DockStyle.Fill;
        flpActions.AutoSize = false;
        flpActions.WrapContents = false;
        flpActions.FlowDirection = FlowDirection.RightToLeft;
        flpActions.RightToLeft = RightToLeft.No;
        flpActions.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 44;
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = true;
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandSave.Name = "standardCommandSave";
        standardCommandSave.Enabled = false;
        standardCommandSave.Visible = true;
        standardCommandSave.AccessibleName = "حفظ";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandAdd.AutoSize = false;
        standardCommandAdd.Dock = DockStyle.None;
        standardCommandAdd.MinimumSize = Size.Empty;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandAdd.Text = "";
        flpActions.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        btnEdit.AutoSize = false;
        btnEdit.Dock = DockStyle.None;
        btnEdit.MinimumSize = Size.Empty;
        btnEdit.Size = new Size(26, 24);
        btnEdit.Margin = new Padding(1);
        btnEdit.FlatStyle = FlatStyle.Flat;
        btnEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        btnEdit.Text = "";
        flpActions.Controls.Add(btnEdit);
        designerCommandBar.SetCommandRole(btnEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        flpActions.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        btnCancel.AutoSize = false;
        btnCancel.Dock = DockStyle.None;
        btnCancel.MinimumSize = Size.Empty;
        btnCancel.Size = new Size(26, 24);
        btnCancel.Margin = new Padding(1);
        btnCancel.FlatStyle = FlatStyle.Flat;
        btnCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        btnCancel.Text = "";
        flpActions.Controls.Add(btnCancel);
        designerCommandBar.SetCommandRole(btnCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        btnView.AutoSize = false;
        btnView.Dock = DockStyle.None;
        btnView.MinimumSize = Size.Empty;
        btnView.Size = new Size(26, 24);
        btnView.Margin = new Padding(1);
        btnView.FlatStyle = FlatStyle.Flat;
        btnView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        btnView.Text = "";
        flpActions.Controls.Add(btnView);
        designerCommandBar.SetCommandRole(btnView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        flpActions.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        flpActions.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        flpActions.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        flpActions.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        standardCommandSave.AutoSize = false;
        standardCommandSave.Dock = DockStyle.None;
        standardCommandSave.MinimumSize = Size.Empty;
        standardCommandSave.Size = new Size(26, 24);
        standardCommandSave.Margin = new Padding(1);
        standardCommandSave.FlatStyle = FlatStyle.Flat;
        standardCommandSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        standardCommandSave.Text = "";
        flpActions.Controls.Add(standardCommandSave);
        designerCommandBar.SetCommandRole(standardCommandSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        flpActions.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        btnClose.AutoSize = false;
        btnClose.Dock = DockStyle.None;
        btnClose.MinimumSize = Size.Empty;
        btnClose.Size = new Size(26, 24);
        btnClose.Margin = new Padding(1);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        btnClose.Text = "";
        designerCloseHost.Controls.Add(btnClose);
        btnClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        flpActions.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        flpActions.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        flpActions.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        flpActions.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}
}
