#nullable enable
using System.Drawing;
using System.Windows.Forms;
namespace TransportERP.EmptyForms;
partial class UcScreen_04_10_04
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandView = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private FlowLayoutPanel flpActions = null!;
    private Button btnSave = null!;
    private Button btnReviewDocuments = null!;
    private Button btnLoadSource = null!;
    private Button btnClear = null!;
    private Button btnClose = null!;
    private TabControl tabs = null!;
    private Label lblStatus = null!;
    private TabPage tp0 = null!;
    private TableLayoutPanel layout0 = null!;
    private ComboBox field_T04_EV_0399 = null!;
    private Label lbl_T04_EV_0399 = null!;
    private TextBox field_T04_EV_0400 = null!;
    private Label lbl_T04_EV_0400 = null!;
    private DateTimePicker field_T04_EV_0401 = null!;
    private Label lbl_T04_EV_0401 = null!;
    private TextBox field_T04_EV_0402 = null!;
    private Label lbl_T04_EV_0402 = null!;
    private ComboBox field_T04_EV_0403 = null!;
    private Label lbl_T04_EV_0403 = null!;
    private ComboBox field_T04_EV_0404 = null!;
    private Label lbl_T04_EV_0404 = null!;
    private TabPage tp1 = null!;
    private TableLayoutPanel layout1 = null!;
    private DataGridView dgvLines = null!;
    private DataGridViewTextBoxColumn col_rowNo = null!;
    private DataGridViewTextBoxColumn col_dueDate = null!;
    private DataGridViewComboBoxColumn col_accountRef = null!;
    private DataGridViewTextBoxColumn col_description = null!;
    private DataGridViewComboBoxColumn col_currencyRef = null!;
    private DataGridViewTextBoxColumn col_amount = null!;
    private DataGridViewTextBoxColumn col_accruedAmount = null!;
    private DataGridViewTextBoxColumn col_remainingAmount = null!;
    private TableLayoutPanel linesHost = null!;
    private FlowLayoutPanel lineActions = null!;
    private Button btnAddRow = null!;
    private Button btnRemoveRow = null!;
    private TabPage tp2 = null!;
    private TableLayoutPanel layout2 = null!;
    private TextBox field_T04_EV_0407 = null!;
    private Label lbl_T04_EV_0407 = null!;
    private TextBox field_T04_EV_0408 = null!;
    private Label lbl_T04_EV_0408 = null!;
    private TextBox field_actualAmount = null!;
    private Label lbl_actualAmount = null!;
    private TextBox field_actualCurrency = null!;
    private Label lbl_actualCurrency = null!;
    private System.ComponentModel.IContainer? components;
    private ErrorProvider validationErrors = null!;
    protected override void Dispose(bool disposing) { if(disposing) components?.Dispose(); base.Dispose(disposing); }
    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandView = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandPrint = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        components = new System.ComponentModel.Container();
        validationErrors = new ErrorProvider(components);
        validationErrors.ContainerControl = this;
        validationErrors.BlinkStyle = ErrorBlinkStyle.NeverBlink;
        mainLayout = new TableLayoutPanel();
        lblTitle = new Label();
        flpActions = new FlowLayoutPanel();
        btnSave = new Button();
        btnReviewDocuments = new Button();
        btnLoadSource = new Button();
        btnClear = new Button();
        btnClose = new Button();
        tabs = new TabControl();
        lblStatus = new Label();
        tp0 = new TabPage();
        layout0 = new TableLayoutPanel();
        field_T04_EV_0399 = new ComboBox();
        lbl_T04_EV_0399 = new Label();
        field_T04_EV_0400 = new TextBox();
        lbl_T04_EV_0400 = new Label();
        field_T04_EV_0401 = new DateTimePicker();
        lbl_T04_EV_0401 = new Label();
        field_T04_EV_0402 = new TextBox();
        lbl_T04_EV_0402 = new Label();
        field_T04_EV_0403 = new ComboBox();
        lbl_T04_EV_0403 = new Label();
        field_T04_EV_0404 = new ComboBox();
        lbl_T04_EV_0404 = new Label();
        tp1 = new TabPage();
        layout1 = new TableLayoutPanel();
        dgvLines = new DataGridView();
        col_rowNo = new DataGridViewTextBoxColumn();
        col_dueDate = new DataGridViewTextBoxColumn();
        col_accountRef = new DataGridViewComboBoxColumn();
        col_description = new DataGridViewTextBoxColumn();
        col_currencyRef = new DataGridViewComboBoxColumn();
        col_amount = new DataGridViewTextBoxColumn();
        col_accruedAmount = new DataGridViewTextBoxColumn();
        col_remainingAmount = new DataGridViewTextBoxColumn();
        linesHost = new TableLayoutPanel();
        lineActions = new FlowLayoutPanel();
        btnAddRow = new Button();
        btnRemoveRow = new Button();
        tp2 = new TabPage();
        layout2 = new TableLayoutPanel();
        field_T04_EV_0407 = new TextBox();
        lbl_T04_EV_0407 = new Label();
        field_T04_EV_0408 = new TextBox();
        lbl_T04_EV_0408 = new Label();
        field_actualAmount = new TextBox();
        lbl_actualAmount = new Label();
        field_actualCurrency = new TextBox();
        lbl_actualCurrency = new Label();
        SuspendLayout();
        mainLayout.Name = "mainLayout";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "تسوية الإيرادات المقدمة";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Padding = new Padding(8);
        lblTitle.TabStop = false;
        mainLayout.Controls.Add(lblTitle, 0, 0);
        flpActions.Name = "flpActions";
        flpActions.AutoSize = true;
        flpActions.Dock = DockStyle.Fill;
        flpActions.WrapContents = true;
        flpActions.FlowDirection = FlowDirection.LeftToRight;
        flpActions.RightToLeft = RightToLeft.Yes;
        mainLayout.Controls.Add(designerCommandBar, 0, 1);
        btnSave.Name = "btnSave";
        btnSave.Text = "حفظ";
        btnSave.AutoSize = true;
        btnSave.MinimumSize = new Size(100,32);
        btnSave.TabIndex = 0;
        btnSave.AccessibleName = "حفظ";

        btnSave.Enabled = false;
        btnReviewDocuments.Name = "btnReviewDocuments";
        btnReviewDocuments.Text = "مراجعة الوثائق";
        btnReviewDocuments.AutoSize = true;
        btnReviewDocuments.MinimumSize = new Size(100,32);
        btnReviewDocuments.TabIndex = 1;
        btnReviewDocuments.AccessibleName = "مراجعة الوثائق";
        flpActions.Controls.Add(btnReviewDocuments);
        btnReviewDocuments.Enabled = false;
        btnLoadSource.Name = "btnLoadSource";
        btnLoadSource.Text = "إنزال البيانات";
        btnLoadSource.AutoSize = true;
        btnLoadSource.MinimumSize = new Size(100,32);
        btnLoadSource.TabIndex = 2;
        btnLoadSource.AccessibleName = "إنزال البيانات";
        flpActions.Controls.Add(btnLoadSource);
        btnLoadSource.Enabled = false;
        btnClear.Name = "btnClear";
        btnClear.Text = "تفريغ المسودة";
        btnClear.AutoSize = true;
        btnClear.MinimumSize = new Size(100,32);
        btnClear.TabIndex = 3;
        btnClear.AccessibleName = "تفريغ المسودة";
        flpActions.Controls.Add(btnClear);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.AutoSize = true;
        btnClose.MinimumSize = new Size(100,32);
        btnClose.TabIndex = 4;
        btnClose.AccessibleName = "إغلاق";

        tabs.Name = "tabs";
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeftLayout = true;
        tabs.Multiline = true;
        tabs.TabIndex = 1;
        mainLayout.Controls.Add(tabs, 0, 2);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "مسودة واجهة غير محفوظة — الخدمات غير موصولة";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.Padding = new Padding(6);
        mainLayout.Controls.Add(lblStatus, 0, 3);
        tp0.Name = "tp0";
        tp0.Text = "البيانات الرئيسية";
        tp0.AutoScroll = true;
        tp0.TabIndex = 0;
        tabs.Controls.Add(tp0);
        layout0.Name = "layout0";
        layout0.Dock = DockStyle.Top;
        layout0.AutoSize = true;
        layout0.ColumnCount = 2;
        layout0.MinimumSize = new Size(650,0);
        layout0.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp0.Controls.Add(layout0);
        field_T04_EV_0399.Name = "field_T04_EV_0399";
        lbl_T04_EV_0399.Name = "lbl_T04_EV_0399";
        field_T04_EV_0399.AccessibleName = "رقم الفرع";
        field_T04_EV_0399.Tag = "T04-EV-0399";
        field_T04_EV_0399.Dock = DockStyle.Fill;
        field_T04_EV_0399.TabIndex = 0;
        lbl_T04_EV_0399.Text = "رقم الفرع";
        lbl_T04_EV_0399.AutoSize = true;
        lbl_T04_EV_0399.Dock = DockStyle.Fill;
        lbl_T04_EV_0399.TextAlign = ContentAlignment.MiddleRight;
        lbl_T04_EV_0399.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_T04_EV_0399, 0, 0);
        layout0.Controls.Add(field_T04_EV_0399, 1, 0);
        field_T04_EV_0399.DropDownStyle = ComboBoxStyle.DropDownList;
        field_T04_EV_0399.DropDownWidth = 420;
        field_T04_EV_0400.Name = "field_T04_EV_0400";
        lbl_T04_EV_0400.Name = "lbl_T04_EV_0400";
        field_T04_EV_0400.AccessibleName = "رقم المستند";
        field_T04_EV_0400.Tag = "T04-EV-0400";
        field_T04_EV_0400.Dock = DockStyle.Fill;
        field_T04_EV_0400.TabIndex = 1;
        lbl_T04_EV_0400.Text = "رقم المستند";
        lbl_T04_EV_0400.AutoSize = true;
        lbl_T04_EV_0400.Dock = DockStyle.Fill;
        lbl_T04_EV_0400.TextAlign = ContentAlignment.MiddleRight;
        lbl_T04_EV_0400.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_T04_EV_0400, 0, 1);
        layout0.Controls.Add(field_T04_EV_0400, 1, 1);
        field_T04_EV_0400.ReadOnly = true;
        field_T04_EV_0400.TabStop = false;
        field_T04_EV_0401.Name = "field_T04_EV_0401";
        lbl_T04_EV_0401.Name = "lbl_T04_EV_0401";
        field_T04_EV_0401.AccessibleName = "التاريخ";
        field_T04_EV_0401.Tag = "T04-EV-0401";
        field_T04_EV_0401.Dock = DockStyle.Fill;
        field_T04_EV_0401.TabIndex = 2;
        lbl_T04_EV_0401.Text = "التاريخ";
        lbl_T04_EV_0401.AutoSize = true;
        lbl_T04_EV_0401.Dock = DockStyle.Fill;
        lbl_T04_EV_0401.TextAlign = ContentAlignment.MiddleRight;
        lbl_T04_EV_0401.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_T04_EV_0401, 0, 2);
        layout0.Controls.Add(field_T04_EV_0401, 1, 2);
        field_T04_EV_0401.Format = DateTimePickerFormat.Custom;
        field_T04_EV_0401.CustomFormat = "yyyy-MM-dd";
        field_T04_EV_0401.ShowCheckBox = true;
        field_T04_EV_0401.Checked = false;
        field_T04_EV_0402.Name = "field_T04_EV_0402";
        lbl_T04_EV_0402.Name = "lbl_T04_EV_0402";
        field_T04_EV_0402.AccessibleName = "رقم المرجع";
        field_T04_EV_0402.Tag = "T04-EV-0402";
        field_T04_EV_0402.Dock = DockStyle.Fill;
        field_T04_EV_0402.TabIndex = 3;
        lbl_T04_EV_0402.Text = "رقم المرجع";
        lbl_T04_EV_0402.AutoSize = true;
        lbl_T04_EV_0402.Dock = DockStyle.Fill;
        lbl_T04_EV_0402.TextAlign = ContentAlignment.MiddleRight;
        lbl_T04_EV_0402.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_T04_EV_0402, 0, 3);
        layout0.Controls.Add(field_T04_EV_0402, 1, 3);
        field_T04_EV_0403.Name = "field_T04_EV_0403";
        lbl_T04_EV_0403.Name = "lbl_T04_EV_0403";
        field_T04_EV_0403.AccessibleName = "إنزال البيانات من";
        field_T04_EV_0403.Tag = "T04-EV-0403";
        field_T04_EV_0403.Dock = DockStyle.Fill;
        field_T04_EV_0403.TabIndex = 4;
        lbl_T04_EV_0403.Text = "إنزال البيانات من";
        lbl_T04_EV_0403.AutoSize = true;
        lbl_T04_EV_0403.Dock = DockStyle.Fill;
        lbl_T04_EV_0403.TextAlign = ContentAlignment.MiddleRight;
        lbl_T04_EV_0403.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_T04_EV_0403, 0, 4);
        layout0.Controls.Add(field_T04_EV_0403, 1, 4);
        field_T04_EV_0403.DropDownStyle = ComboBoxStyle.DropDownList;
        field_T04_EV_0403.DropDownWidth = 420;
        field_T04_EV_0404.Name = "field_T04_EV_0404";
        lbl_T04_EV_0404.Name = "lbl_T04_EV_0404";
        field_T04_EV_0404.AccessibleName = "رقم الوثيقة";
        field_T04_EV_0404.Tag = "T04-EV-0404";
        field_T04_EV_0404.Dock = DockStyle.Fill;
        field_T04_EV_0404.TabIndex = 5;
        lbl_T04_EV_0404.Text = "رقم الوثيقة";
        lbl_T04_EV_0404.AutoSize = true;
        lbl_T04_EV_0404.Dock = DockStyle.Fill;
        lbl_T04_EV_0404.TextAlign = ContentAlignment.MiddleRight;
        lbl_T04_EV_0404.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_T04_EV_0404, 0, 5);
        layout0.Controls.Add(field_T04_EV_0404, 1, 5);
        field_T04_EV_0404.DropDownStyle = ComboBoxStyle.DropDownList;
        field_T04_EV_0404.DropDownWidth = 420;
        layout0.RowCount = 6;
        tp1.Name = "tp1";
        tp1.Text = "بيانات الإيراد المقدم";
        tp1.AutoScroll = true;
        tp1.TabIndex = 1;
        tabs.Controls.Add(tp1);
        layout1.Name = "layout1";
        layout1.Dock = DockStyle.Top;
        layout1.AutoSize = true;
        layout1.ColumnCount = 2;
        layout1.MinimumSize = new Size(650,0);
        layout1.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp1.Controls.Add(layout1);
        layout1.RowCount = 0;
        dgvLines.Name = "dgvLines";
        dgvLines.Dock = DockStyle.Fill;
        dgvLines.MinimumSize = new Size(650,260);
        dgvLines.AutoGenerateColumns = false;
        dgvLines.AllowUserToAddRows = false;
        dgvLines.AllowUserToDeleteRows = false;
        dgvLines.AllowUserToOrderColumns = false;
        dgvLines.RowHeadersVisible = false;
        dgvLines.MultiSelect = false;
        dgvLines.SelectionMode = DataGridViewSelectionMode.CellSelect;
        dgvLines.AccessibleName = "بيانات الإيراد المقدم";
        dgvLines.TabIndex = 1;
        col_rowNo.Name = "col_rowNo";
        col_rowNo.Name = "rowNo";
        col_rowNo.HeaderText = "#";
        col_rowNo.ReadOnly = true;
        col_rowNo.Tag = "text";
        col_rowNo.MinimumWidth = 90;
        col_rowNo.Width = 140;
        col_rowNo.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_rowNo);
        col_dueDate.Name = "col_dueDate";
        col_dueDate.Name = "dueDate";
        col_dueDate.HeaderText = "تاريخ الاستحقاق";
        col_dueDate.ReadOnly = false;
        col_dueDate.Tag = "date";
        col_dueDate.DefaultCellStyle.Format = "yyyy-MM-dd";
        col_dueDate.ToolTipText = "yyyy-MM-dd";
        col_dueDate.MinimumWidth = 90;
        col_dueDate.Width = 140;
        col_dueDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_dueDate);
        col_accountRef.Name = "col_accountRef";
        col_accountRef.Name = "accountRef";
        col_accountRef.HeaderText = "الحساب";
        col_accountRef.ReadOnly = false;
        col_accountRef.Tag = "lookup";
        col_accountRef.MinimumWidth = 90;
        col_accountRef.Width = 140;
        col_accountRef.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_accountRef.DisplayStyle = DataGridViewComboBoxDisplayStyle.DropDownButton;
        col_accountRef.ValueType = typeof(string);
        dgvLines.Columns.Add(col_accountRef);
        col_description.Name = "col_description";
        col_description.Name = "description";
        col_description.HeaderText = "البيان";
        col_description.ReadOnly = false;
        col_description.Tag = "text";
        col_description.MinimumWidth = 90;
        col_description.Width = 140;
        col_description.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_description);
        col_currencyRef.Name = "col_currencyRef";
        col_currencyRef.Name = "currencyRef";
        col_currencyRef.HeaderText = "العملة";
        col_currencyRef.ReadOnly = false;
        col_currencyRef.Tag = "lookup";
        col_currencyRef.MinimumWidth = 90;
        col_currencyRef.Width = 140;
        col_currencyRef.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_currencyRef.DisplayStyle = DataGridViewComboBoxDisplayStyle.DropDownButton;
        col_currencyRef.ValueType = typeof(string);
        dgvLines.Columns.Add(col_currencyRef);
        col_amount.Name = "col_amount";
        col_amount.Name = "amount";
        col_amount.HeaderText = "المبلغ";
        col_amount.ReadOnly = false;
        col_amount.Tag = "decimal";
        col_amount.MinimumWidth = 90;
        col_amount.Width = 140;
        col_amount.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_amount.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_amount);
        col_accruedAmount.Name = "col_accruedAmount";
        col_accruedAmount.Name = "accruedAmount";
        col_accruedAmount.HeaderText = "المبلغ المستحق";
        col_accruedAmount.ReadOnly = true;
        col_accruedAmount.Tag = "decimal";
        col_accruedAmount.MinimumWidth = 90;
        col_accruedAmount.Width = 140;
        col_accruedAmount.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_accruedAmount.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_accruedAmount);
        col_remainingAmount.Name = "col_remainingAmount";
        col_remainingAmount.Name = "remainingAmount";
        col_remainingAmount.HeaderText = "المتبقي";
        col_remainingAmount.ReadOnly = true;
        col_remainingAmount.Tag = "decimal";
        col_remainingAmount.MinimumWidth = 90;
        col_remainingAmount.Width = 140;
        col_remainingAmount.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_remainingAmount.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_remainingAmount);
        linesHost.Name = "linesHost";
        linesHost.Dock = DockStyle.Fill;
        linesHost.ColumnCount = 1;
        linesHost.RowCount = 3;
        linesHost.MinimumSize = new Size(680,380);
        linesHost.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        linesHost.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        linesHost.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        linesHost.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        tp1.Controls.Remove(layout1);
        linesHost.Controls.Add(layout1, 0, 0);
        tp1.Controls.Add(linesHost);
        linesHost.Controls.Add(dgvLines, 0, 2);
        lineActions.Name = "lineActions";
        lineActions.Dock = DockStyle.Fill;
        lineActions.AutoSize = true;
        linesHost.Controls.Add(lineActions, 0, 1);
        btnAddRow.Name = "btnAddRow";
        btnAddRow.Text = "إضافة سطر";
        btnAddRow.AutoSize = true;
        lineActions.Controls.Add(btnAddRow);
        btnRemoveRow.Name = "btnRemoveRow";
        btnRemoveRow.Text = "حذف سطر";
        btnRemoveRow.AutoSize = true;
        lineActions.Controls.Add(btnRemoveRow);
        tp2.Name = "tp2";
        tp2.Text = "بيانات الإيراد الفعلي";
        tp2.AutoScroll = true;
        tp2.TabIndex = 2;
        tabs.Controls.Add(tp2);
        layout2.Name = "layout2";
        layout2.Dock = DockStyle.Top;
        layout2.AutoSize = true;
        layout2.ColumnCount = 2;
        layout2.MinimumSize = new Size(650,0);
        layout2.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp2.Controls.Add(layout2);
        field_T04_EV_0407.Name = "field_T04_EV_0407";
        lbl_T04_EV_0407.Name = "lbl_T04_EV_0407";
        field_T04_EV_0407.AccessibleName = "قيد الاستحقاق";
        field_T04_EV_0407.Tag = "T04-EV-0407";
        field_T04_EV_0407.Dock = DockStyle.Fill;
        field_T04_EV_0407.TabIndex = 0;
        lbl_T04_EV_0407.Text = "قيد الاستحقاق";
        lbl_T04_EV_0407.AutoSize = true;
        lbl_T04_EV_0407.Dock = DockStyle.Fill;
        lbl_T04_EV_0407.TextAlign = ContentAlignment.MiddleRight;
        lbl_T04_EV_0407.TabStop = false;
        layout2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout2.Controls.Add(lbl_T04_EV_0407, 0, 0);
        layout2.Controls.Add(field_T04_EV_0407, 1, 0);
        field_T04_EV_0407.ReadOnly = true;
        field_T04_EV_0407.TabStop = false;
        field_T04_EV_0408.Name = "field_T04_EV_0408";
        lbl_T04_EV_0408.Name = "lbl_T04_EV_0408";
        field_T04_EV_0408.AccessibleName = "إلغاء";
        field_T04_EV_0408.Tag = "T04-EV-0408";
        field_T04_EV_0408.Dock = DockStyle.Fill;
        field_T04_EV_0408.TabIndex = 1;
        lbl_T04_EV_0408.Text = "إلغاء";
        lbl_T04_EV_0408.AutoSize = true;
        lbl_T04_EV_0408.Dock = DockStyle.Fill;
        lbl_T04_EV_0408.TextAlign = ContentAlignment.MiddleRight;
        lbl_T04_EV_0408.TabStop = false;
        layout2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout2.Controls.Add(lbl_T04_EV_0408, 0, 1);
        layout2.Controls.Add(field_T04_EV_0408, 1, 1);
        field_T04_EV_0408.ReadOnly = true;
        field_T04_EV_0408.TabStop = false;
        field_actualAmount.Name = "field_actualAmount";
        lbl_actualAmount.Name = "lbl_actualAmount";
        field_actualAmount.AccessibleName = "المبلغ الفعلي";
        field_actualAmount.Tag = "LOCAL";
        field_actualAmount.Dock = DockStyle.Fill;
        field_actualAmount.TabIndex = 2;
        lbl_actualAmount.Text = "المبلغ الفعلي";
        lbl_actualAmount.AutoSize = true;
        lbl_actualAmount.Dock = DockStyle.Fill;
        lbl_actualAmount.TextAlign = ContentAlignment.MiddleRight;
        lbl_actualAmount.TabStop = false;
        layout2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout2.Controls.Add(lbl_actualAmount, 0, 2);
        layout2.Controls.Add(field_actualAmount, 1, 2);
        field_actualAmount.ReadOnly = true;
        field_actualAmount.TabStop = false;
        field_actualCurrency.Name = "field_actualCurrency";
        lbl_actualCurrency.Name = "lbl_actualCurrency";
        field_actualCurrency.AccessibleName = "العملة";
        field_actualCurrency.Tag = "LOCAL";
        field_actualCurrency.Dock = DockStyle.Fill;
        field_actualCurrency.TabIndex = 3;
        lbl_actualCurrency.Text = "العملة";
        lbl_actualCurrency.AutoSize = true;
        lbl_actualCurrency.Dock = DockStyle.Fill;
        lbl_actualCurrency.TextAlign = ContentAlignment.MiddleRight;
        lbl_actualCurrency.TabStop = false;
        layout2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout2.Controls.Add(lbl_actualCurrency, 0, 3);
        layout2.Controls.Add(field_actualCurrency, 1, 3);
        field_actualCurrency.ReadOnly = true;
        field_actualCurrency.TabStop = false;
        layout2.RowCount = 4;
        AutoScaleDimensions = new SizeF(96F,96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Name = "UcScreen_04_10_04";
        Text = "تسوية الإيرادات المقدمة";
        Tag = "04.10.04";
        Size = new Size(1100,720);
        Controls.Add(mainLayout);
        ResumeLayout(false);
        PerformLayout();
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Fill;
        designerCommandBar.RightToLeft = RightToLeft.Yes;
        designerCommandBar.Controls.Add(flpActions);
        flpActions.Dock = DockStyle.Fill;
        flpActions.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        flpActions.Name = "flpActions";
        flpActions.Dock = DockStyle.Fill;
        flpActions.AutoSize = false;
        flpActions.WrapContents = false;
        flpActions.FlowDirection = FlowDirection.RightToLeft;
        flpActions.RightToLeft = RightToLeft.No;
        flpActions.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 44;
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = true;
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = true;
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandView.Name = "standardCommandView";
        standardCommandView.Enabled = false;
        standardCommandView.Visible = true;
        standardCommandView.AccessibleName = "عرض";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandAdd.AutoSize = false;
        standardCommandAdd.Dock = DockStyle.None;
        standardCommandAdd.MinimumSize = Size.Empty;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandAdd.Text = "";
        flpActions.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.AutoSize = false;
        standardCommandEdit.Dock = DockStyle.None;
        standardCommandEdit.MinimumSize = Size.Empty;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandEdit.Text = "";
        flpActions.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        flpActions.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.AutoSize = false;
        standardCommandCancel.Dock = DockStyle.None;
        standardCommandCancel.MinimumSize = Size.Empty;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandCancel.Text = "";
        flpActions.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        standardCommandView.AutoSize = false;
        standardCommandView.Dock = DockStyle.None;
        standardCommandView.MinimumSize = Size.Empty;
        standardCommandView.Size = new Size(26, 24);
        standardCommandView.Margin = new Padding(1);
        standardCommandView.FlatStyle = FlatStyle.Flat;
        standardCommandView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        standardCommandView.Text = "";
        flpActions.Controls.Add(standardCommandView);
        designerCommandBar.SetCommandRole(standardCommandView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        flpActions.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        flpActions.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        flpActions.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        flpActions.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        btnSave.AutoSize = false;
        btnSave.Dock = DockStyle.None;
        btnSave.MinimumSize = Size.Empty;
        btnSave.Size = new Size(26, 24);
        btnSave.Margin = new Padding(1);
        btnSave.FlatStyle = FlatStyle.Flat;
        btnSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        btnSave.Text = "";
        flpActions.Controls.Add(btnSave);
        designerCommandBar.SetCommandRole(btnSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        flpActions.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        btnClose.AutoSize = false;
        btnClose.Dock = DockStyle.None;
        btnClose.MinimumSize = Size.Empty;
        btnClose.Size = new Size(26, 24);
        btnClose.Margin = new Padding(1);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        btnClose.Text = "";
        designerCloseHost.Controls.Add(btnClose);
        btnClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        flpActions.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        flpActions.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        flpActions.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        flpActions.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}
}
