#nullable enable
using System.Drawing;
using System.Windows.Forms;
namespace TransportERP.EmptyForms;
partial class UcScreen_04_08_01
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandSave = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private FlowLayoutPanel flpActions = null!;
    private Button btnView = null!;
    private Button btnCreate = null!;
    private Button btnEdit = null!;
    private Button btnCancel = null!;
    private Button btnPost = null!;
    private Button btnReverse = null!;
    private Button btnClear = null!;
    private Button btnClose = null!;
    private TabControl tabs = null!;
    private Label lblStatus = null!;
    private TabPage tp0 = null!;
    private TableLayoutPanel layout0 = null!;
    private TextBox field_noteNumber = null!;
    private Label lbl_noteNumber = null!;
    private DateTimePicker field_noteDate = null!;
    private Label lbl_noteDate = null!;
    private ComboBox field_partyRef = null!;
    private Label lbl_partyRef = null!;
    private ComboBox field_originalDocumentRef = null!;
    private Label lbl_originalDocumentRef = null!;
    private TextBox field_reason = null!;
    private Label lbl_reason = null!;
    private ComboBox field_currencyRef = null!;
    private Label lbl_currencyRef = null!;
    private TextBox field_state = null!;
    private Label lbl_state = null!;
    private TabPage tp1 = null!;
    private TableLayoutPanel layout1 = null!;
    private TextBox field_baseAmount = null!;
    private Label lbl_baseAmount = null!;
    private TextBox field_taxAmount = null!;
    private Label lbl_taxAmount = null!;
    private TextBox field_totalAmount = null!;
    private Label lbl_totalAmount = null!;
    private ComboBox field_partyAccountRef = null!;
    private Label lbl_partyAccountRef = null!;
    private ComboBox field_counterAccountRef = null!;
    private Label lbl_counterAccountRef = null!;
    private ComboBox field_costCenterRef = null!;
    private Label lbl_costCenterRef = null!;
    private TabPage tp2 = null!;
    private TableLayoutPanel layout2 = null!;
    private TextBox field_allocationContext = null!;
    private Label lbl_allocationContext = null!;
    private TextBox field_balanceContext = null!;
    private Label lbl_balanceContext = null!;
    private DataGridView dgvLines = null!;
    private DataGridViewTextBoxColumn col_rowNo = null!;
    private DataGridViewComboBoxColumn col_documentRef = null!;
    private DataGridViewTextBoxColumn col_documentDate = null!;
    private DataGridViewTextBoxColumn col_openBalance = null!;
    private DataGridViewTextBoxColumn col_allocatedAmount = null!;
    private DataGridViewTextBoxColumn col_remaining = null!;
    private DataGridViewComboBoxColumn col_currencyRef = null!;
    private TableLayoutPanel linesHost = null!;
    private FlowLayoutPanel lineActions = null!;
    private Button btnAddRow = null!;
    private Button btnRemoveRow = null!;
    private TabPage tp3 = null!;
    private TableLayoutPanel layout3 = null!;
    private RichTextBox context3 = null!;
    private TabPage tp4 = null!;
    private TableLayoutPanel layout4 = null!;
    private RichTextBox context4 = null!;
    private System.ComponentModel.IContainer? components;
    private ErrorProvider validationErrors = null!;
    protected override void Dispose(bool disposing) { if(disposing) components?.Dispose(); base.Dispose(disposing); }
    private TableLayoutPanel referenceHeader = null!;
    private TabPage referenceExtra = null!;
    private Label referenceAudit = null!;
    private Label referenceTotals = null!;
    private Label referenceLabel0 = null!;
    private TextBox referenceField0 = null!;
    private Label referenceLabel1 = null!;
    private TextBox referenceField1 = null!;
    private Label referenceLabel5 = null!;
    private TextBox referenceField5 = null!;
    private Label referenceLabel6 = null!;
    private TextBox referenceField6 = null!;
    private Button referencePrint = null!;
    private TabPage documentAdditional = null!;
    private TabControl documentAdditionalSections = null!;
    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandDelete = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandSave = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        documentAdditional = new TabPage();
        documentAdditionalSections = new TabControl();
        referenceHeader = new TableLayoutPanel();
        referenceExtra = new TabPage();
        referenceAudit = new Label();
        referenceTotals = new Label();
        referenceLabel0 = new Label();
        referenceField0 = new TextBox();
        referenceLabel1 = new Label();
        referenceField1 = new TextBox();
        referenceLabel5 = new Label();
        referenceField5 = new TextBox();
        referenceLabel6 = new Label();
        referenceField6 = new TextBox();
        referencePrint = new Button();
        components = new System.ComponentModel.Container();
        validationErrors = new ErrorProvider(components);
        validationErrors.ContainerControl = this;
        validationErrors.BlinkStyle = ErrorBlinkStyle.NeverBlink;
        mainLayout = new TableLayoutPanel();
        lblTitle = new Label();
        flpActions = new FlowLayoutPanel();
        btnView = new Button();
        btnCreate = new Button();
        btnEdit = new Button();
        btnCancel = new Button();
        btnPost = new Button();
        btnReverse = new Button();
        btnClear = new Button();
        btnClose = new Button();
        tabs = new TabControl();
        lblStatus = new Label();
        tp0 = new TabPage();
        layout0 = new TableLayoutPanel();
        field_noteNumber = new TextBox();
        lbl_noteNumber = new Label();
        field_noteDate = new DateTimePicker();
        lbl_noteDate = new Label();
        field_partyRef = new ComboBox();
        lbl_partyRef = new Label();
        field_originalDocumentRef = new ComboBox();
        lbl_originalDocumentRef = new Label();
        field_reason = new TextBox();
        lbl_reason = new Label();
        field_currencyRef = new ComboBox();
        lbl_currencyRef = new Label();
        field_state = new TextBox();
        lbl_state = new Label();
        tp1 = new TabPage();
        layout1 = new TableLayoutPanel();
        field_baseAmount = new TextBox();
        lbl_baseAmount = new Label();
        field_taxAmount = new TextBox();
        lbl_taxAmount = new Label();
        field_totalAmount = new TextBox();
        lbl_totalAmount = new Label();
        field_partyAccountRef = new ComboBox();
        lbl_partyAccountRef = new Label();
        field_counterAccountRef = new ComboBox();
        lbl_counterAccountRef = new Label();
        field_costCenterRef = new ComboBox();
        lbl_costCenterRef = new Label();
        tp2 = new TabPage();
        layout2 = new TableLayoutPanel();
        field_allocationContext = new TextBox();
        lbl_allocationContext = new Label();
        field_balanceContext = new TextBox();
        lbl_balanceContext = new Label();
        dgvLines = new DataGridView();
        col_rowNo = new DataGridViewTextBoxColumn();
        col_documentRef = new DataGridViewComboBoxColumn();
        col_documentDate = new DataGridViewTextBoxColumn();
        col_openBalance = new DataGridViewTextBoxColumn();
        col_allocatedAmount = new DataGridViewTextBoxColumn();
        col_remaining = new DataGridViewTextBoxColumn();
        col_currencyRef = new DataGridViewComboBoxColumn();
        linesHost = new TableLayoutPanel();
        lineActions = new FlowLayoutPanel();
        btnAddRow = new Button();
        btnRemoveRow = new Button();
        tp3 = new TabPage();
        layout3 = new TableLayoutPanel();
        context3 = new RichTextBox();
        tp4 = new TabPage();
        layout4 = new TableLayoutPanel();
        context4 = new RichTextBox();
        SuspendLayout();
        mainLayout.Name = "mainLayout";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "إشعارات مدينة";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Padding = new Padding(8);
        lblTitle.TabStop = false;
        mainLayout.Controls.Add(lblTitle, 0, 0);
        flpActions.Name = "flpActions";
        flpActions.AutoSize = true;
        flpActions.Dock = DockStyle.Fill;
        flpActions.WrapContents = true;
        flpActions.FlowDirection = FlowDirection.LeftToRight;
        flpActions.RightToLeft = RightToLeft.Yes;
        mainLayout.Controls.Add(designerCommandBar, 0, 1);
        btnView.Name = "btnView";
        btnView.Text = "عرض / إعادة تحميل";
        btnView.AutoSize = true;
        btnView.MinimumSize = new Size(100,32);
        btnView.TabIndex = 0;
        btnView.AccessibleName = "عرض / إعادة تحميل";

        btnView.Enabled = false;
        btnCreate.Name = "btnCreate";
        btnCreate.Text = "حفظ جديد";
        btnCreate.AutoSize = true;
        btnCreate.MinimumSize = new Size(100,32);
        btnCreate.TabIndex = 1;
        btnCreate.AccessibleName = "حفظ جديد";
        flpActions.Controls.Add(btnCreate);
        btnCreate.Enabled = false;
        btnEdit.Name = "btnEdit";
        btnEdit.Text = "حفظ التعديل";
        btnEdit.AutoSize = true;
        btnEdit.MinimumSize = new Size(100,32);
        btnEdit.TabIndex = 2;
        btnEdit.AccessibleName = "حفظ التعديل";

        btnEdit.Enabled = false;
        btnCancel.Name = "btnCancel";
        btnCancel.Text = "إلغاء المستند";
        btnCancel.AutoSize = true;
        btnCancel.MinimumSize = new Size(100,32);
        btnCancel.TabIndex = 3;
        btnCancel.AccessibleName = "إلغاء المستند";

        btnCancel.Enabled = false;
        btnPost.Name = "btnPost";
        btnPost.Text = "ترحيل";
        btnPost.AutoSize = true;
        btnPost.MinimumSize = new Size(100,32);
        btnPost.TabIndex = 4;
        btnPost.AccessibleName = "ترحيل";
        flpActions.Controls.Add(btnPost);
        btnPost.Enabled = false;
        btnReverse.Name = "btnReverse";
        btnReverse.Text = "عكس القيد";
        btnReverse.AutoSize = true;
        btnReverse.MinimumSize = new Size(100,32);
        btnReverse.TabIndex = 5;
        btnReverse.AccessibleName = "عكس القيد";
        flpActions.Controls.Add(btnReverse);
        btnReverse.Enabled = false;
        btnClear.Name = "btnClear";
        btnClear.Text = "تفريغ المسودة";
        btnClear.AutoSize = true;
        btnClear.MinimumSize = new Size(100,32);
        btnClear.TabIndex = 6;
        btnClear.AccessibleName = "تفريغ المسودة";
        flpActions.Controls.Add(btnClear);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.AutoSize = true;
        btnClose.MinimumSize = new Size(100,32);
        btnClose.TabIndex = 7;
        btnClose.AccessibleName = "إغلاق";

        tabs.Name = "tabs";
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeftLayout = true;
        tabs.Multiline = true;
        tabs.TabIndex = 1;
        mainLayout.Controls.Add(tabs, 0, 2);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "مسودة واجهة غير محفوظة — الخدمات غير موصولة";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.Padding = new Padding(6);
        mainLayout.Controls.Add(lblStatus, 0, 3);
        tp0.Name = "tp0";
        tp0.Text = "البيانات الرئيسية";
        tp0.AutoScroll = true;
        tp0.TabIndex = 0;
        tabs.Controls.Add(tp0);
        layout0.Name = "layout0";
        layout0.Dock = DockStyle.Top;
        layout0.AutoSize = true;
        layout0.ColumnCount = 2;
        layout0.MinimumSize = new Size(650,0);
        layout0.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp0.Controls.Add(layout0);
        field_noteNumber.Name = "field_noteNumber";
        lbl_noteNumber.Name = "lbl_noteNumber";
        field_noteNumber.AccessibleName = "رقم الإشعار";
        field_noteNumber.Tag = "ACC-077:1";
        field_noteNumber.Dock = DockStyle.Fill;
        field_noteNumber.TabIndex = 0;
        lbl_noteNumber.Text = "رقم الإشعار";
        lbl_noteNumber.AutoSize = true;
        lbl_noteNumber.Dock = DockStyle.Fill;
        lbl_noteNumber.TextAlign = ContentAlignment.MiddleRight;
        lbl_noteNumber.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_noteNumber.ReadOnly = true;
        field_noteNumber.TabStop = false;
        field_noteDate.Name = "field_noteDate";
        lbl_noteDate.Name = "lbl_noteDate";
        field_noteDate.AccessibleName = "تاريخ الإشعار";
        field_noteDate.Tag = "ACC-077:2";
        field_noteDate.Dock = DockStyle.Fill;
        field_noteDate.TabIndex = 1;
        lbl_noteDate.Text = "تاريخ الإشعار";
        lbl_noteDate.AutoSize = true;
        lbl_noteDate.Dock = DockStyle.Fill;
        lbl_noteDate.TextAlign = ContentAlignment.MiddleRight;
        lbl_noteDate.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_noteDate.Format = DateTimePickerFormat.Custom;
        field_noteDate.CustomFormat = "yyyy-MM-dd";
        field_noteDate.ShowCheckBox = true;
        field_noteDate.Checked = false;
        field_partyRef.Name = "field_partyRef";
        lbl_partyRef.Name = "lbl_partyRef";
        field_partyRef.AccessibleName = "العميل";
        field_partyRef.Tag = "ACC-077:3";
        field_partyRef.Dock = DockStyle.Fill;
        field_partyRef.TabIndex = 2;
        lbl_partyRef.Text = "العميل";
        lbl_partyRef.AutoSize = true;
        lbl_partyRef.Dock = DockStyle.Fill;
        lbl_partyRef.TextAlign = ContentAlignment.MiddleRight;
        lbl_partyRef.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_partyRef, 0, 2);
        layout0.Controls.Add(field_partyRef, 1, 2);
        field_partyRef.DropDownStyle = ComboBoxStyle.DropDownList;
        field_partyRef.DropDownWidth = 420;
        field_originalDocumentRef.Name = "field_originalDocumentRef";
        lbl_originalDocumentRef.Name = "lbl_originalDocumentRef";
        field_originalDocumentRef.AccessibleName = "المستند الأصلي";
        field_originalDocumentRef.Tag = "ACC-077:4";
        field_originalDocumentRef.Dock = DockStyle.Fill;
        field_originalDocumentRef.TabIndex = 3;
        lbl_originalDocumentRef.Text = "المستند الأصلي";
        lbl_originalDocumentRef.AutoSize = true;
        lbl_originalDocumentRef.Dock = DockStyle.Fill;
        lbl_originalDocumentRef.TextAlign = ContentAlignment.MiddleRight;
        lbl_originalDocumentRef.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_originalDocumentRef, 0, 3);
        layout0.Controls.Add(field_originalDocumentRef, 1, 3);
        field_originalDocumentRef.DropDownStyle = ComboBoxStyle.DropDownList;
        field_originalDocumentRef.DropDownWidth = 420;
        field_reason.Name = "field_reason";
        lbl_reason.Name = "lbl_reason";
        field_reason.AccessibleName = "سبب الإشعار";
        field_reason.Tag = "ACC-077:5";
        field_reason.Dock = DockStyle.Fill;
        field_reason.TabIndex = 4;
        lbl_reason.Text = "سبب الإشعار";
        lbl_reason.AutoSize = true;
        lbl_reason.Dock = DockStyle.Fill;
        lbl_reason.TextAlign = ContentAlignment.MiddleRight;
        lbl_reason.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_reason, 0, 4);
        layout0.Controls.Add(field_reason, 1, 4);
        field_reason.Multiline = true;
        field_reason.Height = 70;
        field_reason.ScrollBars = ScrollBars.Vertical;
        field_reason.BackColor = Color.LightYellow;
        field_currencyRef.Name = "field_currencyRef";
        lbl_currencyRef.Name = "lbl_currencyRef";
        field_currencyRef.AccessibleName = "العملة";
        field_currencyRef.Tag = "ACC-077:6";
        field_currencyRef.Dock = DockStyle.Fill;
        field_currencyRef.TabIndex = 5;
        lbl_currencyRef.Text = "العملة";
        lbl_currencyRef.AutoSize = true;
        lbl_currencyRef.Dock = DockStyle.Fill;
        lbl_currencyRef.TextAlign = ContentAlignment.MiddleRight;
        lbl_currencyRef.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_currencyRef.DropDownStyle = ComboBoxStyle.DropDownList;
        field_currencyRef.DropDownWidth = 420;
        field_state.Name = "field_state";
        lbl_state.Name = "lbl_state";
        field_state.AccessibleName = "الحالة";
        field_state.Tag = "ACC-077:15";
        field_state.Dock = DockStyle.Fill;
        field_state.TabIndex = 6;
        lbl_state.Text = "الحالة";
        lbl_state.AutoSize = true;
        lbl_state.Dock = DockStyle.Fill;
        lbl_state.TextAlign = ContentAlignment.MiddleRight;
        lbl_state.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_state.ReadOnly = true;
        field_state.TabStop = false;
        layout0.RowCount = 7;
        tp1.Name = "tp1";
        tp1.Text = "تفاصيل الإشعار";
        tp1.AutoScroll = true;
        tp1.TabIndex = 1;
        tabs.Controls.Add(tp1);
        layout1.Name = "layout1";
        layout1.Dock = DockStyle.Top;
        layout1.AutoSize = true;
        layout1.ColumnCount = 2;
        layout1.MinimumSize = new Size(650,0);
        layout1.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp1.Controls.Add(layout1);
        field_baseAmount.Name = "field_baseAmount";
        lbl_baseAmount.Name = "lbl_baseAmount";
        field_baseAmount.AccessibleName = "المبلغ قبل الضريبة";
        field_baseAmount.Tag = "ACC-077:7";
        field_baseAmount.Dock = DockStyle.Fill;
        field_baseAmount.TabIndex = 0;
        lbl_baseAmount.Text = "المبلغ قبل الضريبة";
        lbl_baseAmount.AutoSize = true;
        lbl_baseAmount.Dock = DockStyle.Fill;
        lbl_baseAmount.TextAlign = ContentAlignment.MiddleRight;
        lbl_baseAmount.TabStop = false;
        layout1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout1.Controls.Add(lbl_baseAmount, 0, 0);
        layout1.Controls.Add(field_baseAmount, 1, 0);
        field_baseAmount.RightToLeft = RightToLeft.No;
        field_baseAmount.TextAlign = HorizontalAlignment.Right;
        field_taxAmount.Name = "field_taxAmount";
        lbl_taxAmount.Name = "lbl_taxAmount";
        field_taxAmount.AccessibleName = "الضريبة";
        field_taxAmount.Tag = "ACC-077:8";
        field_taxAmount.Dock = DockStyle.Fill;
        field_taxAmount.TabIndex = 1;
        lbl_taxAmount.Text = "الضريبة";
        lbl_taxAmount.AutoSize = true;
        lbl_taxAmount.Dock = DockStyle.Fill;
        lbl_taxAmount.TextAlign = ContentAlignment.MiddleRight;
        lbl_taxAmount.TabStop = false;
        layout1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout1.Controls.Add(lbl_taxAmount, 0, 1);
        layout1.Controls.Add(field_taxAmount, 1, 1);
        field_taxAmount.RightToLeft = RightToLeft.No;
        field_taxAmount.TextAlign = HorizontalAlignment.Right;
        field_totalAmount.Name = "field_totalAmount";
        lbl_totalAmount.Name = "lbl_totalAmount";
        field_totalAmount.AccessibleName = "الإجمالي";
        field_totalAmount.Tag = "ACC-077:9";
        field_totalAmount.Dock = DockStyle.Fill;
        field_totalAmount.TabIndex = 2;
        lbl_totalAmount.Text = "الإجمالي";
        lbl_totalAmount.AutoSize = true;
        lbl_totalAmount.Dock = DockStyle.Fill;
        lbl_totalAmount.TextAlign = ContentAlignment.MiddleRight;
        lbl_totalAmount.TabStop = false;
        layout1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout1.Controls.Add(lbl_totalAmount, 0, 2);
        layout1.Controls.Add(field_totalAmount, 1, 2);
        field_totalAmount.ReadOnly = true;
        field_totalAmount.TabStop = false;
        field_partyAccountRef.Name = "field_partyAccountRef";
        lbl_partyAccountRef.Name = "lbl_partyAccountRef";
        field_partyAccountRef.AccessibleName = "حساب المدين";
        field_partyAccountRef.Tag = "ACC-077:10";
        field_partyAccountRef.Dock = DockStyle.Fill;
        field_partyAccountRef.TabIndex = 3;
        lbl_partyAccountRef.Text = "حساب المدين";
        lbl_partyAccountRef.AutoSize = true;
        lbl_partyAccountRef.Dock = DockStyle.Fill;
        lbl_partyAccountRef.TextAlign = ContentAlignment.MiddleRight;
        lbl_partyAccountRef.TabStop = false;
        layout1.RowStyles.Add(new RowStyle(SizeType.AutoSize));


        field_partyAccountRef.DropDownStyle = ComboBoxStyle.DropDownList;
        field_partyAccountRef.DropDownWidth = 420;
        field_counterAccountRef.Name = "field_counterAccountRef";
        lbl_counterAccountRef.Name = "lbl_counterAccountRef";
        field_counterAccountRef.AccessibleName = "الحساب المقابل";
        field_counterAccountRef.Tag = "ACC-077:11";
        field_counterAccountRef.Dock = DockStyle.Fill;
        field_counterAccountRef.TabIndex = 4;
        lbl_counterAccountRef.Text = "الحساب المقابل";
        lbl_counterAccountRef.AutoSize = true;
        lbl_counterAccountRef.Dock = DockStyle.Fill;
        lbl_counterAccountRef.TextAlign = ContentAlignment.MiddleRight;
        lbl_counterAccountRef.TabStop = false;
        layout1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout1.Controls.Add(lbl_counterAccountRef, 0, 4);
        layout1.Controls.Add(field_counterAccountRef, 1, 4);
        field_counterAccountRef.DropDownStyle = ComboBoxStyle.DropDownList;
        field_counterAccountRef.DropDownWidth = 420;
        field_costCenterRef.Name = "field_costCenterRef";
        lbl_costCenterRef.Name = "lbl_costCenterRef";
        field_costCenterRef.AccessibleName = "مركز التكلفة/الأبعاد";
        field_costCenterRef.Tag = "ACC-077:12";
        field_costCenterRef.Dock = DockStyle.Fill;
        field_costCenterRef.TabIndex = 5;
        lbl_costCenterRef.Text = "مركز التكلفة/الأبعاد";
        lbl_costCenterRef.AutoSize = true;
        lbl_costCenterRef.Dock = DockStyle.Fill;
        lbl_costCenterRef.TextAlign = ContentAlignment.MiddleRight;
        lbl_costCenterRef.TabStop = false;
        layout1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout1.Controls.Add(lbl_costCenterRef, 0, 5);
        layout1.Controls.Add(field_costCenterRef, 1, 5);
        field_costCenterRef.DropDownStyle = ComboBoxStyle.DropDownList;
        field_costCenterRef.DropDownWidth = 420;
        layout1.RowCount = 6;
        tp2.Name = "tp2";
        tp2.Text = "المستندات والتخصيص";
        tp2.AutoScroll = true;
        tp2.TabIndex = 2;
        tabs.Controls.Add(tp2);
        layout2.Name = "layout2";
        layout2.Dock = DockStyle.Top;
        layout2.AutoSize = true;
        layout2.ColumnCount = 2;
        layout2.MinimumSize = new Size(650,0);
        layout2.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp2.Controls.Add(layout2);
        field_allocationContext.Name = "field_allocationContext";
        lbl_allocationContext.Name = "lbl_allocationContext";
        field_allocationContext.AccessibleName = "التخصيص على مستندات";
        field_allocationContext.Tag = "ACC-077:13";
        field_allocationContext.Dock = DockStyle.Fill;
        field_allocationContext.TabIndex = 0;
        lbl_allocationContext.Text = "التخصيص على مستندات";
        lbl_allocationContext.AutoSize = true;
        lbl_allocationContext.Dock = DockStyle.Fill;
        lbl_allocationContext.TextAlign = ContentAlignment.MiddleRight;
        lbl_allocationContext.TabStop = false;
        layout2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout2.Controls.Add(lbl_allocationContext, 0, 0);
        layout2.Controls.Add(field_allocationContext, 1, 0);
        field_allocationContext.ReadOnly = true;
        field_allocationContext.TabStop = false;
        field_balanceContext.Name = "field_balanceContext";
        lbl_balanceContext.Name = "lbl_balanceContext";
        field_balanceContext.AccessibleName = "الرصيد قبل/بعد";
        field_balanceContext.Tag = "ACC-077:14";
        field_balanceContext.Dock = DockStyle.Fill;
        field_balanceContext.TabIndex = 1;
        lbl_balanceContext.Text = "الرصيد قبل/بعد";
        lbl_balanceContext.AutoSize = true;
        lbl_balanceContext.Dock = DockStyle.Fill;
        lbl_balanceContext.TextAlign = ContentAlignment.MiddleRight;
        lbl_balanceContext.TabStop = false;
        layout2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout2.Controls.Add(lbl_balanceContext, 0, 1);
        layout2.Controls.Add(field_balanceContext, 1, 1);
        field_balanceContext.ReadOnly = true;
        field_balanceContext.TabStop = false;
        layout2.RowCount = 2;
        dgvLines.Name = "dgvLines";
        dgvLines.Dock = DockStyle.Fill;
        dgvLines.MinimumSize = new Size(650,260);
        dgvLines.AutoGenerateColumns = false;
        dgvLines.AllowUserToAddRows = false;
        dgvLines.AllowUserToDeleteRows = false;
        dgvLines.AllowUserToOrderColumns = false;
        dgvLines.RowHeadersVisible = false;
        dgvLines.MultiSelect = false;
        dgvLines.SelectionMode = DataGridViewSelectionMode.CellSelect;
        dgvLines.AccessibleName = "المستندات والتخصيص";
        dgvLines.TabIndex = 3;
        col_rowNo.Name = "col_rowNo";
        col_rowNo.Name = "rowNo";
        col_rowNo.HeaderText = "#";
        col_rowNo.ReadOnly = true;
        col_rowNo.Tag = "text";
        col_rowNo.MinimumWidth = 90;
        col_rowNo.Width = 140;
        col_rowNo.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_rowNo);
        col_documentRef.Name = "col_documentRef";
        col_documentRef.Name = "documentRef";
        col_documentRef.HeaderText = "المستند المرتبط";
        col_documentRef.ReadOnly = false;
        col_documentRef.Tag = "lookup";
        col_documentRef.MinimumWidth = 90;
        col_documentRef.Width = 140;
        col_documentRef.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_documentRef.DisplayStyle = DataGridViewComboBoxDisplayStyle.DropDownButton;
        col_documentRef.ValueType = typeof(string);
        dgvLines.Columns.Add(col_documentRef);
        col_documentDate.Name = "col_documentDate";
        col_documentDate.Name = "documentDate";
        col_documentDate.HeaderText = "تاريخ المستند";
        col_documentDate.ReadOnly = true;
        col_documentDate.Tag = "text";
        col_documentDate.MinimumWidth = 90;
        col_documentDate.Width = 140;
        col_documentDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLines.Columns.Add(col_documentDate);
        col_openBalance.Name = "col_openBalance";
        col_openBalance.Name = "openBalance";
        col_openBalance.HeaderText = "الرصيد المفتوح";
        col_openBalance.ReadOnly = true;
        col_openBalance.Tag = "decimal";
        col_openBalance.MinimumWidth = 90;
        col_openBalance.Width = 140;
        col_openBalance.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_openBalance.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_openBalance);
        col_allocatedAmount.Name = "col_allocatedAmount";
        col_allocatedAmount.Name = "allocatedAmount";
        col_allocatedAmount.HeaderText = "المبلغ المخصص";
        col_allocatedAmount.ReadOnly = false;
        col_allocatedAmount.Tag = "decimal";
        col_allocatedAmount.MinimumWidth = 90;
        col_allocatedAmount.Width = 140;
        col_allocatedAmount.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_allocatedAmount.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_allocatedAmount);
        col_remaining.Name = "col_remaining";
        col_remaining.Name = "remaining";
        col_remaining.HeaderText = "المتبقي";
        col_remaining.ReadOnly = true;
        col_remaining.Tag = "decimal";
        col_remaining.MinimumWidth = 90;
        col_remaining.Width = 140;
        col_remaining.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_remaining.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
        dgvLines.Columns.Add(col_remaining);
        col_currencyRef.Name = "col_currencyRef";
        col_currencyRef.Name = "currencyRef";
        col_currencyRef.HeaderText = "العملة";
        col_currencyRef.ReadOnly = true;
        col_currencyRef.Tag = "lookup";
        col_currencyRef.MinimumWidth = 90;
        col_currencyRef.Width = 140;
        col_currencyRef.SortMode = DataGridViewColumnSortMode.NotSortable;
        col_currencyRef.DisplayStyle = DataGridViewComboBoxDisplayStyle.DropDownButton;
        col_currencyRef.ValueType = typeof(string);
        dgvLines.Columns.Add(col_currencyRef);
        linesHost.Name = "linesHost";
        linesHost.Dock = DockStyle.Fill;
        linesHost.ColumnCount = 1;
        linesHost.RowCount = 3;
        linesHost.MinimumSize = new Size(680,380);
        linesHost.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        linesHost.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        linesHost.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        linesHost.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        tp2.Controls.Remove(layout2);
        linesHost.Controls.Add(layout2, 0, 0);
        tp2.Controls.Add(linesHost);
        linesHost.Controls.Add(dgvLines, 0, 2);
        lineActions.Name = "lineActions";
        lineActions.Dock = DockStyle.Fill;
        lineActions.AutoSize = true;
        linesHost.Controls.Add(lineActions, 0, 1);
        btnAddRow.Name = "btnAddRow";
        btnAddRow.Text = "إضافة سطر";
        btnAddRow.AutoSize = true;
        lineActions.Controls.Add(btnAddRow);
        btnRemoveRow.Name = "btnRemoveRow";
        btnRemoveRow.Text = "حذف سطر";
        btnRemoveRow.AutoSize = true;
        lineActions.Controls.Add(btnRemoveRow);
        tp3.Name = "tp3";
        tp3.Text = "الاعتماد والترحيل";
        tp3.AutoScroll = true;
        tp3.TabIndex = 3;
        tabs.Controls.Add(tp3);
        layout3.Name = "layout3";
        layout3.Dock = DockStyle.Top;
        layout3.AutoSize = true;
        layout3.ColumnCount = 2;
        layout3.MinimumSize = new Size(650,0);
        layout3.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout3.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp3.Controls.Add(layout3);
        layout3.RowCount = 0;
        layout3.Dock = DockStyle.Fill;
        layout3.RowCount = 1;
        layout3.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        context3.Name = "context3";
        context3.ReadOnly = true;
        context3.Dock = DockStyle.Fill;
        context3.AccessibleName = "الاعتماد والترحيل";
        context3.DetectUrls = false;
        layout3.Controls.Add(context3, 0, 0);
        layout3.SetColumnSpan(context3,2);
        tp4.Name = "tp4";
        tp4.Text = "سجل العمليات";
        tp4.AutoScroll = true;
        tp4.TabIndex = 4;
        tabs.Controls.Add(tp4);
        layout4.Name = "layout4";
        layout4.Dock = DockStyle.Top;
        layout4.AutoSize = true;
        layout4.ColumnCount = 2;
        layout4.MinimumSize = new Size(650,0);
        layout4.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout4.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp4.Controls.Add(layout4);
        layout4.RowCount = 0;
        layout4.Dock = DockStyle.Fill;
        layout4.RowCount = 1;
        layout4.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        context4.Name = "context4";
        context4.ReadOnly = true;
        context4.Dock = DockStyle.Fill;
        context4.AccessibleName = "سجل العمليات";
        context4.DetectUrls = false;
        layout4.Controls.Add(context4, 0, 0);
        layout4.SetColumnSpan(context4,2);
        AutoScaleDimensions = new SizeF(96F,96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Name = "UcScreen_04_08_01";
        Text = "إشعارات مدينة";
        Tag = "04.08.01";
        Size = new Size(1100,720);
        Controls.Add(mainLayout);
        ResumeLayout(false);
        PerformLayout();

        col_rowNo.DisplayIndex = 0;
        col_currencyRef.DisplayIndex = 1;
        col_documentRef.DisplayIndex = 2;
        col_documentDate.DisplayIndex = 3;
        col_openBalance.DisplayIndex = 4;
        col_allocatedAmount.DisplayIndex = 5;
        col_remaining.DisplayIndex = 6;
        // Reference layout: Onyx general ledger manual, second edition.
        referenceLabel0.Text = "رقم الفرع";
        referenceField0.ReadOnly = true;
        referenceField0.TabStop = false;
        referenceField0.AccessibleDescription = "حقل مرجعي؛ لم يربط بخدمة السند بعد";
        referenceField0.BackColor = Color.FromArgb(245,245,245);
        referenceLabel1.Text = "نوع الإشعار";
        referenceField1.ReadOnly = true;
        referenceField1.TabStop = false;
        referenceField1.AccessibleDescription = "حقل مرجعي؛ لم يربط بخدمة السند بعد";
        referenceField1.BackColor = Color.FromArgb(245,245,245);
        referenceLabel5.Text = "الحساب التحليلي";
        referenceField5.ReadOnly = true;
        referenceField5.TabStop = false;
        referenceField5.AccessibleDescription = "حقل مرجعي؛ لم يربط بخدمة السند بعد";
        referenceField5.BackColor = Color.FromArgb(245,245,245);
        referenceLabel6.Text = "اسم الحساب";
        referenceField6.ReadOnly = true;
        referenceField6.TabStop = false;
        referenceField6.AccessibleDescription = "حقل مرجعي؛ لم يربط بخدمة السند بعد";
        referenceField6.BackColor = Color.FromArgb(245,245,245);
        layout0.AutoScroll = true;
        layout1.AutoScroll = true;
        layout2.AutoScroll = true;
        layout3.AutoScroll = true;
        layout4.AutoScroll = true;
        referenceExtra.Name = "referenceExtra";
        referenceExtra.Text = "بيانات إضافية";
        referenceExtra.AutoScroll = true;
        tp0.Controls.Remove(layout0);
        referenceExtra.Controls.Add(layout0);
        tabs.Controls.Add(referenceExtra);
        tp0.Controls.Add(referenceHeader);
        referenceHeader.Name = "referenceHeader";
        referenceHeader.Dock = DockStyle.Top;
        referenceHeader.AutoSize = true;
        referenceHeader.RightToLeft = RightToLeft.Yes;
        referenceHeader.BackColor = Color.FromArgb(245,245,245);
        referenceHeader.Padding = new Padding(8);
        referenceHeader.ColumnCount = 6;
        referenceHeader.RowCount = 3;
        referenceHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,115F));
        referenceHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,33.333F));
        referenceHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,115F));
        referenceHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,33.333F));
        referenceHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,115F));
        referenceHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,33.333F));
        referenceHeader.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        referenceHeader.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        referenceHeader.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        referenceLabel0.AutoSize = false;
        referenceLabel0.Dock = DockStyle.Fill;
        referenceLabel0.TextAlign = ContentAlignment.MiddleRight;
        referenceLabel0.Margin = new Padding(2);
        referenceField0.Dock = DockStyle.Fill;
        referenceField0.Margin = new Padding(2);
        referenceHeader.Controls.Add(referenceLabel0, 0, 0);
        referenceHeader.Controls.Add(referenceField0, 1, 0);
        referenceLabel1.AutoSize = false;
        referenceLabel1.Dock = DockStyle.Fill;
        referenceLabel1.TextAlign = ContentAlignment.MiddleRight;
        referenceLabel1.Margin = new Padding(2);
        referenceField1.Dock = DockStyle.Fill;
        referenceField1.Margin = new Padding(2);
        referenceHeader.Controls.Add(referenceLabel1, 2, 0);
        referenceHeader.Controls.Add(referenceField1, 3, 0);
        lbl_noteNumber.AutoSize = false;
        lbl_noteNumber.Dock = DockStyle.Fill;
        lbl_noteNumber.TextAlign = ContentAlignment.MiddleRight;
        lbl_noteNumber.Margin = new Padding(2);
        field_noteNumber.Dock = DockStyle.Fill;
        field_noteNumber.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_noteNumber, 4, 0);
        referenceHeader.Controls.Add(field_noteNumber, 5, 0);
        lbl_noteDate.AutoSize = false;
        lbl_noteDate.Dock = DockStyle.Fill;
        lbl_noteDate.TextAlign = ContentAlignment.MiddleRight;
        lbl_noteDate.Margin = new Padding(2);
        field_noteDate.Dock = DockStyle.Fill;
        field_noteDate.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_noteDate, 0, 1);
        referenceHeader.Controls.Add(field_noteDate, 1, 1);
        lbl_partyAccountRef.AutoSize = false;
        lbl_partyAccountRef.Dock = DockStyle.Fill;
        lbl_partyAccountRef.TextAlign = ContentAlignment.MiddleRight;
        lbl_partyAccountRef.Margin = new Padding(2);
        field_partyAccountRef.Dock = DockStyle.Fill;
        field_partyAccountRef.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_partyAccountRef, 2, 1);
        referenceHeader.Controls.Add(field_partyAccountRef, 3, 1);
        referenceLabel5.AutoSize = false;
        referenceLabel5.Dock = DockStyle.Fill;
        referenceLabel5.TextAlign = ContentAlignment.MiddleRight;
        referenceLabel5.Margin = new Padding(2);
        referenceField5.Dock = DockStyle.Fill;
        referenceField5.Margin = new Padding(2);
        referenceHeader.Controls.Add(referenceLabel5, 4, 1);
        referenceHeader.Controls.Add(referenceField5, 5, 1);
        referenceLabel6.AutoSize = false;
        referenceLabel6.Dock = DockStyle.Fill;
        referenceLabel6.TextAlign = ContentAlignment.MiddleRight;
        referenceLabel6.Margin = new Padding(2);
        referenceField6.Dock = DockStyle.Fill;
        referenceField6.Margin = new Padding(2);
        referenceHeader.Controls.Add(referenceLabel6, 0, 2);
        referenceHeader.Controls.Add(referenceField6, 1, 2);
        lbl_currencyRef.AutoSize = false;
        lbl_currencyRef.Dock = DockStyle.Fill;
        lbl_currencyRef.TextAlign = ContentAlignment.MiddleRight;
        lbl_currencyRef.Margin = new Padding(2);
        field_currencyRef.Dock = DockStyle.Fill;
        field_currencyRef.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_currencyRef, 2, 2);
        referenceHeader.Controls.Add(field_currencyRef, 3, 2);
        lbl_state.AutoSize = false;
        lbl_state.Dock = DockStyle.Fill;
        lbl_state.TextAlign = ContentAlignment.MiddleRight;
        lbl_state.Margin = new Padding(2);
        field_state.Dock = DockStyle.Fill;
        field_state.Margin = new Padding(2);
        referenceHeader.Controls.Add(lbl_state, 4, 2);
        referenceHeader.Controls.Add(field_state, 5, 2);
        mainLayout.Controls.Remove(tabs);
        mainLayout.Controls.Remove(lblStatus);
        mainLayout.RowStyles.Clear();
        mainLayout.RowCount = 7;
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute,34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute,210F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute,48F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.Controls.Add(tabs,0,2);
        // Display the grid already bound to the notice service; do not fabricate ledger rows.
        mainLayout.Controls.Add(dgvLines,0,3);
        dgvLines.Dock = DockStyle.Fill;
        dgvLines.MinimumSize = new Size(700,120);
        dgvLines.AccessibleName = "المستندات المرتبطة وتخصيص الإشعار";
        dgvLines.BackgroundColor = Color.White;
        dgvLines.EnableHeadersVisualStyles = false;
        dgvLines.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(232,232,232);
        dgvLines.ColumnHeadersHeight = 34;
        dgvLines.RowTemplate.Height = 27;
        flpActions.Controls.Add(btnAddRow);
        flpActions.Controls.Add(btnRemoveRow);
        mainLayout.Controls.Add(referenceTotals,0,4);
        mainLayout.Controls.Add(referenceAudit,0,5);
        mainLayout.Controls.Add(lblStatus,0,6);
        referenceTotals.Dock = DockStyle.Fill;
        referenceTotals.TextAlign = ContentAlignment.MiddleCenter;
        referenceTotals.BackColor = Color.FromArgb(250,223,249);
        referenceTotals.Text = "الإجمالي: —          الفارق: —";
        referenceAudit.Dock = DockStyle.Fill;
        referenceAudit.BackColor = Color.FromArgb(225,223,247);
        referenceAudit.TextAlign = ContentAlignment.MiddleRight;
        referenceAudit.Text = "مدخل السجل: —    تاريخ الإدخال: —    الجهاز: —\r\nمعدل السجل: —    تاريخ التعديل: —    مرات التعديل: —    مرات الطباعة: —";
        lblTitle.Text = "إشعارات مدينة";
        lblTitle.BackColor = Color.FromArgb(232,232,242);
        lblTitle.ForeColor = Color.FromArgb(35,35,50);
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Margin = new Padding(0);
        flpActions.BackColor = Color.FromArgb(239,239,244);
        flpActions.RightToLeft = RightToLeft.Yes;
        flpActions.FlowDirection = FlowDirection.RightToLeft;
        flpActions.WrapContents = true;
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeft = RightToLeft.Yes;
        tabs.RightToLeftLayout = true;
        tabs.Font = new Font("Tahoma",9F);
        mainLayout.MinimumSize = new Size(1080,780);
        AutoScroll = true;
        Font = new Font("Tahoma",9F);
        BackColor = Color.FromArgb(240,240,240);
        Text = "إشعارات مدينة";
        referencePrint.Text = "طباعة";
        referencePrint.AutoSize = true;
        referencePrint.Enabled = false;

        // Tabs based on documented Onyx behavior; no claim of pixel-identical unseen tabs.
        documentAdditional.Name = "documentAdditional";
        documentAdditional.Text = "بيانات إضافية";
        documentAdditional.AutoScroll = true;
        documentAdditionalSections.Dock = DockStyle.Fill;
        documentAdditionalSections.RightToLeft = RightToLeft.Yes;
        documentAdditionalSections.RightToLeftLayout = true;
        documentAdditional.Controls.Add(documentAdditionalSections);
        tabs.Controls.Remove(tp1);
        documentAdditionalSections.Controls.Add(tp1);
        tabs.Controls.Remove(tp2);
        documentAdditionalSections.Controls.Add(tp2);
        tabs.Controls.Remove(tp3);
        documentAdditionalSections.Controls.Add(tp3);
        tabs.Controls.Remove(tp4);
        documentAdditionalSections.Controls.Add(tp4);
        tabs.Controls.Remove(referenceExtra);
        documentAdditionalSections.Controls.Add(referenceExtra);
        referenceExtra.Text = "حقول تكميلية";
        tabs.Controls.Add(documentAdditional);
        tabs.Controls.Clear();
        tabs.Controls.Add(tp0);
        tabs.Controls.Add(documentAdditional);
        tabs.SelectedIndex = 0;

        // Engineering correction: common toolbar and compact workspace bounds.
        btnView.AutoSize = false;
        btnView.MinimumSize = new Size(132,36);
        btnView.Size = new Size(132,36);
        btnView.Margin = new Padding(3);
        btnCreate.AutoSize = false;
        btnCreate.MinimumSize = new Size(132,36);
        btnCreate.Size = new Size(132,36);
        btnCreate.Margin = new Padding(3);
        btnEdit.AutoSize = false;
        btnEdit.MinimumSize = new Size(132,36);
        btnEdit.Size = new Size(132,36);
        btnEdit.Margin = new Padding(3);
        btnCancel.AutoSize = false;
        btnCancel.MinimumSize = new Size(132,36);
        btnCancel.Size = new Size(132,36);
        btnCancel.Margin = new Padding(3);
        btnPost.AutoSize = false;
        btnPost.MinimumSize = new Size(132,36);
        btnPost.Size = new Size(132,36);
        btnPost.Margin = new Padding(3);
        btnReverse.AutoSize = false;
        btnReverse.MinimumSize = new Size(132,36);
        btnReverse.Size = new Size(132,36);
        btnReverse.Margin = new Padding(3);
        btnClear.AutoSize = false;
        btnClear.MinimumSize = new Size(132,36);
        btnClear.Size = new Size(132,36);
        btnClear.Margin = new Padding(3);
        btnClose.AutoSize = false;
        btnClose.MinimumSize = new Size(132,36);
        btnClose.Size = new Size(132,36);
        btnClose.Margin = new Padding(3);
        btnAddRow.AutoSize = false;
        btnAddRow.MinimumSize = new Size(132,36);
        btnAddRow.Size = new Size(132,36);
        btnAddRow.Margin = new Padding(3);
        btnRemoveRow.AutoSize = false;
        btnRemoveRow.MinimumSize = new Size(132,36);
        btnRemoveRow.Size = new Size(132,36);
        btnRemoveRow.Margin = new Padding(3);
        referencePrint.AutoSize = false;
        referencePrint.MinimumSize = new Size(132,36);
        referencePrint.Size = new Size(132,36);
        referencePrint.Margin = new Padding(3);
        mainLayout.MinimumSize = new Size(980,680);
        dgvLines.MinimumSize = new Size(900,80);
        mainLayout.RowStyles[5].Height = 36F;
        flpActions.FlowDirection = FlowDirection.LeftToRight;
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Fill;
        designerCommandBar.RightToLeft = RightToLeft.Yes;
        designerCommandBar.Controls.Add(flpActions);
        flpActions.Dock = DockStyle.Fill;
        flpActions.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        flpActions.Name = "flpActions";
        flpActions.Dock = DockStyle.Fill;
        flpActions.AutoSize = false;
        flpActions.WrapContents = false;
        flpActions.FlowDirection = FlowDirection.RightToLeft;
        flpActions.RightToLeft = RightToLeft.No;
        flpActions.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 44;
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = true;
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandSave.Name = "standardCommandSave";
        standardCommandSave.Enabled = false;
        standardCommandSave.Visible = true;
        standardCommandSave.AccessibleName = "حفظ";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandAdd.AutoSize = false;
        standardCommandAdd.Dock = DockStyle.None;
        standardCommandAdd.MinimumSize = Size.Empty;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandAdd.Text = "";
        flpActions.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        btnEdit.AutoSize = false;
        btnEdit.Dock = DockStyle.None;
        btnEdit.MinimumSize = Size.Empty;
        btnEdit.Size = new Size(26, 24);
        btnEdit.Margin = new Padding(1);
        btnEdit.FlatStyle = FlatStyle.Flat;
        btnEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        btnEdit.Text = "";
        flpActions.Controls.Add(btnEdit);
        designerCommandBar.SetCommandRole(btnEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        flpActions.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        btnCancel.AutoSize = false;
        btnCancel.Dock = DockStyle.None;
        btnCancel.MinimumSize = Size.Empty;
        btnCancel.Size = new Size(26, 24);
        btnCancel.Margin = new Padding(1);
        btnCancel.FlatStyle = FlatStyle.Flat;
        btnCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        btnCancel.Text = "";
        flpActions.Controls.Add(btnCancel);
        designerCommandBar.SetCommandRole(btnCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        btnView.AutoSize = false;
        btnView.Dock = DockStyle.None;
        btnView.MinimumSize = Size.Empty;
        btnView.Size = new Size(26, 24);
        btnView.Margin = new Padding(1);
        btnView.FlatStyle = FlatStyle.Flat;
        btnView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        btnView.Text = "";
        flpActions.Controls.Add(btnView);
        designerCommandBar.SetCommandRole(btnView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        flpActions.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        flpActions.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        flpActions.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        flpActions.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        standardCommandSave.AutoSize = false;
        standardCommandSave.Dock = DockStyle.None;
        standardCommandSave.MinimumSize = Size.Empty;
        standardCommandSave.Size = new Size(26, 24);
        standardCommandSave.Margin = new Padding(1);
        standardCommandSave.FlatStyle = FlatStyle.Flat;
        standardCommandSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        standardCommandSave.Text = "";
        flpActions.Controls.Add(standardCommandSave);
        designerCommandBar.SetCommandRole(standardCommandSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        referencePrint.AutoSize = false;
        referencePrint.Dock = DockStyle.None;
        referencePrint.MinimumSize = Size.Empty;
        referencePrint.Size = new Size(26, 24);
        referencePrint.Margin = new Padding(1);
        referencePrint.FlatStyle = FlatStyle.Flat;
        referencePrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        referencePrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        referencePrint.Text = "";
        flpActions.Controls.Add(referencePrint);
        designerCommandBar.SetCommandRole(referencePrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        btnClose.AutoSize = false;
        btnClose.Dock = DockStyle.None;
        btnClose.MinimumSize = Size.Empty;
        btnClose.Size = new Size(26, 24);
        btnClose.Margin = new Padding(1);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        btnClose.Text = "";
        designerCloseHost.Controls.Add(btnClose);
        btnClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        flpActions.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        flpActions.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        flpActions.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        flpActions.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        referenceAudit.Visible = false;
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}
}
