namespace TransportERP.EmptyForms;

partial class UcScreen_04_03_01
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel mainLayout = null!;
    private TableLayoutPanel pnlHeader = null!;
    private Label lblTitle = null!;
    private FlowLayoutPanel pnlToolbar = null!;
    private Button btnView = null!;
    private Button btnNew = null!;
    private Button btnSave = null!;
    private Button btnEdit = null!;
    private Button btnDisable = null!;
    private Button btnClose = null!;
    private Label lblDataStatus = null!;
    private TextBox txtAttachmentsContext = null!;
    private TextBox txtOperationsContext = null!;
    private Panel pnlContent = null!;
    private TableLayoutPanel contentLayout = null!;
    private TabControl detailsTabs = null!;
    private Label lblMoneyValidation = null!;
    private TabPage tabMain = null!;
    private TableLayoutPanel tabMainFields = null!;
    private TabPage tabAdditional = null!;
    private TableLayoutPanel tabAdditionalFields = null!;
    private TabPage tabAccounting = null!;
    private TableLayoutPanel tabAccountingFields = null!;
    private TabPage tabLimits = null!;
    private TableLayoutPanel tabLimitsFields = null!;
    private TabPage tabAttachments = null!;
    private TableLayoutPanel tabAttachmentsFields = null!;
    private TabPage tabOperations = null!;
    private TableLayoutPanel tabOperationsFields = null!;
    private Label lblAttachmentsState = null!;
    private Label lblOperationsState = null!;
    private Label lblcashboxCode = null!;
    private TextBox txtcashboxCode = null!;
    private Label lblcashboxName = null!;
    private TextBox txtcashboxName = null!;
    private Label lblcompanyRef = null!;
    private ComboBox cmbcompanyRef = null!;
    private Label lblbranchRef = null!;
    private ComboBox cmbbranchRef = null!;
    private Label lblcurrencyRef = null!;
    private ComboBox cmbcurrencyRef = null!;
    private Label lblstatus = null!;
    private TextBox txtstatus = null!;
    private Label lbldefaultCashierRef = null!;
    private ComboBox cmbdefaultCashierRef = null!;
    private Label lblglAccountRef = null!;
    private ComboBox cmbglAccountRef = null!;
    private Label lblmaximumBalance = null!;
    private TextBox txtmaximumBalance = null!;
    private Label lblsingleTransactionLimit = null!;
    private TextBox txtsingleTransactionLimit = null!;
    private Label lblrequiresShiftClose = null!;
    private CheckBox chkRequiresShiftClose = null!;
    private TableLayoutPanel searchLayout = null!;
    private Label lblFiltercode = null!;
    private TextBox filtercode = null!;
    private Label lblFiltername = null!;
    private TextBox filtername = null!;
    private Label lblFilterstatus = null!;
    private ComboBox filterstatus = null!;
    private Button btnSearch = null!;
    private DataGridView dgvRecords = null!;
    private DataGridViewTextBoxColumn colcashboxCode = null!;
    private DataGridViewTextBoxColumn colcashboxName = null!;
    private DataGridViewTextBoxColumn colcompanyRef = null!;
    private DataGridViewTextBoxColumn colbranchRef = null!;
    private DataGridViewTextBoxColumn colcurrencyRef = null!;
    private DataGridViewTextBoxColumn colstatus = null!;
    private DataGridViewTextBoxColumn collastModified = null!;
    private FlowLayoutPanel paging = null!;
    private Button btnPrevious = null!;
    private Button btnNext = null!;
    private Label lblPage = null!;
    private TableLayoutPanel tlpAuditInfo = null!;
    private Label lblCreatedBy = null!;
    private Label lblCreatedAt = null!;
    private Label lblModifiedBy = null!;
    private Label lblModifiedAt = null!;

    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCloseHost = new Panel();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandPrint = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        mainLayout = new TableLayoutPanel();
        pnlHeader = new TableLayoutPanel();
        lblTitle = new Label();
        pnlToolbar = new FlowLayoutPanel();
        btnView = new Button();
        btnNew = new Button();
        btnSave = new Button();
        btnEdit = new Button();
        btnDisable = new Button();
        btnClose = new Button();
        lblDataStatus = new Label();
        pnlContent = new Panel();
        contentLayout = new TableLayoutPanel();
        detailsTabs = new TabControl();
        lblMoneyValidation = new Label();
        tabMain = new TabPage();
        tabMainFields = new TableLayoutPanel();
        tabAdditional = new TabPage();
        tabAdditionalFields = new TableLayoutPanel();
        tabAccounting = new TabPage();
        tabAccountingFields = new TableLayoutPanel();
        tabLimits = new TabPage();
        tabLimitsFields = new TableLayoutPanel();
        tabAttachments = new TabPage();
        tabAttachmentsFields = new TableLayoutPanel();
        tabOperations = new TabPage();
        tabOperationsFields = new TableLayoutPanel();
        lblAttachmentsState = new Label();
        lblOperationsState = new Label();
        lblcashboxCode = new Label();
        txtcashboxCode = new TextBox();
        lblcashboxName = new Label();
        txtcashboxName = new TextBox();
        lblcompanyRef = new Label();
        cmbcompanyRef = new ComboBox();
        lblbranchRef = new Label();
        cmbbranchRef = new ComboBox();
        lblcurrencyRef = new Label();
        cmbcurrencyRef = new ComboBox();
        lblstatus = new Label();
        txtstatus = new TextBox();
        lbldefaultCashierRef = new Label();
        cmbdefaultCashierRef = new ComboBox();
        lblglAccountRef = new Label();
        cmbglAccountRef = new ComboBox();
        lblmaximumBalance = new Label();
        txtmaximumBalance = new TextBox();
        lblsingleTransactionLimit = new Label();
        txtsingleTransactionLimit = new TextBox();
        lblrequiresShiftClose = new Label();
        chkRequiresShiftClose = new CheckBox();
        searchLayout = new TableLayoutPanel();
        lblFiltercode = new Label();
        filtercode = new TextBox();
        lblFiltername = new Label();
        filtername = new TextBox();
        lblFilterstatus = new Label();
        filterstatus = new ComboBox();
        btnSearch = new Button();
        dgvRecords = new DataGridView();
        colcashboxCode = new DataGridViewTextBoxColumn();
        colcashboxName = new DataGridViewTextBoxColumn();
        colcompanyRef = new DataGridViewTextBoxColumn();
        colbranchRef = new DataGridViewTextBoxColumn();
        colcurrencyRef = new DataGridViewTextBoxColumn();
        colstatus = new DataGridViewTextBoxColumn();
        collastModified = new DataGridViewTextBoxColumn();
        paging = new FlowLayoutPanel();
        btnPrevious = new Button();
        btnNext = new Button();
        lblPage = new Label();
        tlpAuditInfo = new TableLayoutPanel();
        lblCreatedBy = new Label();
        lblCreatedAt = new Label();
        lblModifiedBy = new Label();
        lblModifiedAt = new Label();
        SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)dgvRecords).BeginInit();
        mainLayout.Name = "mainLayout";
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 3;
        mainLayout.Margin = Padding.Empty;
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlHeader.Name = "pnlHeader";
        pnlHeader.ColumnCount = 1;
        pnlHeader.RowCount = 2;
        pnlHeader.Margin = Padding.Empty;
        pnlHeader.Dock = DockStyle.Top;
        pnlHeader.AutoSize = true;
        pnlHeader.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "الصناديق";
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.AutoSize = true;
        lblTitle.Font = new Font("Segoe UI", 16F);
        lblTitle.BackColor = Color.FromArgb(192, 192, 255);
        pnlHeader.Controls.Add(lblTitle, 0, 0);
        pnlToolbar.Name = "pnlToolbar";
        pnlToolbar.Dock = DockStyle.Top;
        pnlToolbar.AutoSize = true;
        pnlToolbar.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlToolbar.FlowDirection = FlowDirection.LeftToRight;
        pnlToolbar.RightToLeft = RightToLeft.Yes;
        pnlToolbar.WrapContents = true;
        btnView.Name = "btnView";
        btnView.Text = "عرض";
        btnView.AutoSize = true;
        btnView.Dock = DockStyle.None;
        btnView.Size = new Size(70, 30);
        btnView.Margin = new Padding(4);
        btnView.Enabled = false;
        btnView.AccessibleDescription = "غير منفذ: لم يتم ربط خدمة البيانات أو الحفظ.";

        btnNew.Name = "btnNew";
        btnNew.Text = "جديد";
        btnNew.AutoSize = true;
        btnNew.Dock = DockStyle.None;
        btnNew.Size = new Size(70, 30);
        btnNew.Margin = new Padding(4);
        btnNew.Enabled = false;
        btnNew.AccessibleDescription = "غير منفذ: لم يتم ربط خدمة البيانات أو الحفظ.";

        btnSave.Name = "btnSave";
        btnSave.Text = "حفظ";
        btnSave.AutoSize = true;
        btnSave.Dock = DockStyle.None;
        btnSave.Size = new Size(70, 30);
        btnSave.Margin = new Padding(4);
        btnSave.Enabled = false;
        btnSave.AccessibleDescription = "غير منفذ: لم يتم ربط خدمة البيانات أو الحفظ.";

        btnEdit.Name = "btnEdit";
        btnEdit.Text = "تعديل";
        btnEdit.AutoSize = true;
        btnEdit.Dock = DockStyle.None;
        btnEdit.Size = new Size(70, 30);
        btnEdit.Margin = new Padding(4);
        btnEdit.Enabled = false;
        btnEdit.AccessibleDescription = "غير منفذ: لم يتم ربط خدمة البيانات أو الحفظ.";

        btnDisable.Name = "btnDisable";
        btnDisable.Text = "إيقاف";
        btnDisable.AutoSize = true;
        btnDisable.Dock = DockStyle.None;
        btnDisable.Size = new Size(70, 30);
        btnDisable.Margin = new Padding(4);
        btnDisable.Enabled = false;
        btnDisable.AccessibleDescription = "غير منفذ: لم يتم ربط خدمة البيانات أو الحفظ.";
        pnlToolbar.Controls.Add(btnDisable);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.AutoSize = true;
        btnClose.Dock = DockStyle.None;
        btnClose.Size = new Size(70, 30);
        btnClose.Margin = new Padding(4);
        btnClose.Enabled = true;
        btnClose.AccessibleDescription = "إغلاق الشاشة";

        btnClose.Click += BtnClose_Click;
        pnlHeader.Controls.Add(designerCommandBar, 0, 1);
        mainLayout.Controls.Add(pnlHeader, 0, 0);
        lblDataStatus.Name = "lblDataStatus";
        lblDataStatus.Text = "واجهة تصميم — لم يتم تحميل بيانات؛ الحفظ والبحث والتصفح غير مربوطين بالخدمات.";
        lblDataStatus.AutoSize = true;
        lblDataStatus.Dock = DockStyle.Fill;
        mainLayout.Controls.Add(lblDataStatus, 0, 1);
        pnlContent.Name = "pnlContent";
        pnlContent.Dock = DockStyle.Fill;
        pnlContent.AutoScroll = true;
        mainLayout.Controls.Add(pnlContent, 0, 2);
        contentLayout.Name = "contentLayout";
        contentLayout.ColumnCount = 1;
        contentLayout.RowCount = 5;
        contentLayout.Margin = Padding.Empty;
        contentLayout.Dock = DockStyle.None;
        contentLayout.AutoSize = false;
        contentLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        contentLayout.MinimumSize = new Size(700, 0);
        contentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 200F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        pnlContent.Controls.Add(contentLayout);
        lblcashboxCode.Name = "lblcashboxCode";
        lblcashboxCode.Text = "رمز الصندوق *";
        lblcashboxCode.Dock = DockStyle.Fill;
        lblcashboxCode.TextAlign = ContentAlignment.MiddleRight;
        txtcashboxCode.Name = "txtcashboxCode";
        txtcashboxCode.AccessibleName = "رمز الصندوق";
        txtcashboxCode.Tag = "cashboxCode";
        txtcashboxCode.Dock = DockStyle.Fill;
        txtcashboxCode.Margin = new Padding(3);
        txtcashboxCode.TabIndex = 0;
        txtcashboxCode.BackColor = Color.FromArgb(255, 249, 219);
        txtcashboxCode.RightToLeft = RightToLeft.No;
        lblcashboxName.Name = "lblcashboxName";
        lblcashboxName.Text = "اسم الصندوق *";
        lblcashboxName.Dock = DockStyle.Fill;
        lblcashboxName.TextAlign = ContentAlignment.MiddleRight;
        txtcashboxName.Name = "txtcashboxName";
        txtcashboxName.AccessibleName = "اسم الصندوق";
        txtcashboxName.Tag = "cashboxName";
        txtcashboxName.Dock = DockStyle.Fill;
        txtcashboxName.Margin = new Padding(3);
        txtcashboxName.TabIndex = 1;
        txtcashboxName.BackColor = Color.FromArgb(255, 249, 219);
        lblcompanyRef.Name = "lblcompanyRef";
        lblcompanyRef.Text = "الشركة *";
        lblcompanyRef.Dock = DockStyle.Fill;
        lblcompanyRef.TextAlign = ContentAlignment.MiddleRight;
        cmbcompanyRef.Name = "cmbcompanyRef";
        cmbcompanyRef.AccessibleName = "الشركة";
        cmbcompanyRef.Tag = "companyRef";
        cmbcompanyRef.Dock = DockStyle.Fill;
        cmbcompanyRef.Margin = new Padding(3);
        cmbcompanyRef.TabIndex = 2;
        cmbcompanyRef.BackColor = Color.FromArgb(255, 249, 219);
        cmbcompanyRef.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbcompanyRef.AccessibleDescription = "مرجع تصميم؛ لا يوجد مزود بيانات مرتبط. تعيين الحقول والصلاحيات مؤجل حتى ربط الخدمة.";
        lblbranchRef.Name = "lblbranchRef";
        lblbranchRef.Text = "الفرع *";
        lblbranchRef.Dock = DockStyle.Fill;
        lblbranchRef.TextAlign = ContentAlignment.MiddleRight;
        cmbbranchRef.Name = "cmbbranchRef";
        cmbbranchRef.AccessibleName = "الفرع";
        cmbbranchRef.Tag = "branchRef";
        cmbbranchRef.Dock = DockStyle.Fill;
        cmbbranchRef.Margin = new Padding(3);
        cmbbranchRef.TabIndex = 3;
        cmbbranchRef.BackColor = Color.FromArgb(255, 249, 219);
        cmbbranchRef.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbbranchRef.AccessibleDescription = "مرجع تصميم؛ لا يوجد مزود بيانات مرتبط. تعيين الحقول والصلاحيات مؤجل حتى ربط الخدمة.";
        lblcurrencyRef.Name = "lblcurrencyRef";
        lblcurrencyRef.Text = "العملة *";
        lblcurrencyRef.Dock = DockStyle.Fill;
        lblcurrencyRef.TextAlign = ContentAlignment.MiddleRight;
        cmbcurrencyRef.Name = "cmbcurrencyRef";
        cmbcurrencyRef.AccessibleName = "العملة";
        cmbcurrencyRef.Tag = "currencyRef";
        cmbcurrencyRef.Dock = DockStyle.Fill;
        cmbcurrencyRef.Margin = new Padding(3);
        cmbcurrencyRef.TabIndex = 4;
        cmbcurrencyRef.BackColor = Color.FromArgb(255, 249, 219);
        cmbcurrencyRef.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbcurrencyRef.AccessibleDescription = "مرجع تصميم؛ لا يوجد مزود بيانات مرتبط. تعيين الحقول والصلاحيات مؤجل حتى ربط الخدمة.";
        lblstatus.Name = "lblstatus";
        lblstatus.Text = "الحالة";
        lblstatus.Dock = DockStyle.Fill;
        lblstatus.TextAlign = ContentAlignment.MiddleRight;
        txtstatus.Name = "txtstatus";
        txtstatus.AccessibleName = "الحالة";
        txtstatus.Tag = "status";
        txtstatus.Dock = DockStyle.Fill;
        txtstatus.Margin = new Padding(3);
        txtstatus.TabIndex = 5;
        txtstatus.ReadOnly = true;
        txtstatus.AccessibleDescription = "إسقاط حالة من الخدمة؛ لا تُعدل الحالة مباشرة.";
        lbldefaultCashierRef.Name = "lbldefaultCashierRef";
        lbldefaultCashierRef.Text = "أمين الصندوق الافتراضي";
        lbldefaultCashierRef.Dock = DockStyle.Fill;
        lbldefaultCashierRef.TextAlign = ContentAlignment.MiddleRight;
        cmbdefaultCashierRef.Name = "cmbdefaultCashierRef";
        cmbdefaultCashierRef.AccessibleName = "أمين الصندوق الافتراضي";
        cmbdefaultCashierRef.Tag = "defaultCashierRef";
        cmbdefaultCashierRef.Dock = DockStyle.Fill;
        cmbdefaultCashierRef.Margin = new Padding(3);
        cmbdefaultCashierRef.TabIndex = 6;
        cmbdefaultCashierRef.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbdefaultCashierRef.AccessibleDescription = "مرجع تصميم؛ لا يوجد مزود بيانات مرتبط. تعيين الحقول والصلاحيات مؤجل حتى ربط الخدمة.";
        lblglAccountRef.Name = "lblglAccountRef";
        lblglAccountRef.Text = "حساب الأستاذ *";
        lblglAccountRef.Dock = DockStyle.Fill;
        lblglAccountRef.TextAlign = ContentAlignment.MiddleRight;
        cmbglAccountRef.Name = "cmbglAccountRef";
        cmbglAccountRef.AccessibleName = "حساب الأستاذ";
        cmbglAccountRef.Tag = "glAccountRef";
        cmbglAccountRef.Dock = DockStyle.Fill;
        cmbglAccountRef.Margin = new Padding(3);
        cmbglAccountRef.TabIndex = 7;
        cmbglAccountRef.BackColor = Color.FromArgb(255, 249, 219);
        cmbglAccountRef.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbglAccountRef.AccessibleDescription = "مرجع تصميم؛ لا يوجد مزود بيانات مرتبط. تعيين الحقول والصلاحيات مؤجل حتى ربط الخدمة.";
        lblmaximumBalance.Name = "lblmaximumBalance";
        lblmaximumBalance.Text = "الحد الأقصى للرصيد";
        lblmaximumBalance.Dock = DockStyle.Fill;
        lblmaximumBalance.TextAlign = ContentAlignment.MiddleRight;
        txtmaximumBalance.Name = "txtmaximumBalance";
        txtmaximumBalance.AccessibleName = "الحد الأقصى للرصيد";
        txtmaximumBalance.Tag = "maximumBalance";
        txtmaximumBalance.Dock = DockStyle.Fill;
        txtmaximumBalance.Margin = new Padding(3);
        txtmaximumBalance.TabIndex = 8;
        txtmaximumBalance.RightToLeft = RightToLeft.No;
        txtmaximumBalance.TextAlign = HorizontalAlignment.Right;
        lblsingleTransactionLimit.Name = "lblsingleTransactionLimit";
        lblsingleTransactionLimit.Text = "حد العملية الواحدة";
        lblsingleTransactionLimit.Dock = DockStyle.Fill;
        lblsingleTransactionLimit.TextAlign = ContentAlignment.MiddleRight;
        txtsingleTransactionLimit.Name = "txtsingleTransactionLimit";
        txtsingleTransactionLimit.AccessibleName = "حد العملية الواحدة";
        txtsingleTransactionLimit.Tag = "singleTransactionLimit";
        txtsingleTransactionLimit.Dock = DockStyle.Fill;
        txtsingleTransactionLimit.Margin = new Padding(3);
        txtsingleTransactionLimit.TabIndex = 9;
        txtsingleTransactionLimit.RightToLeft = RightToLeft.No;
        txtsingleTransactionLimit.TextAlign = HorizontalAlignment.Right;
        lblrequiresShiftClose.Name = "lblrequiresShiftClose";
        lblrequiresShiftClose.Text = "يتطلب إقفال وردية *";
        lblrequiresShiftClose.Dock = DockStyle.Fill;
        lblrequiresShiftClose.TextAlign = ContentAlignment.MiddleRight;
        chkRequiresShiftClose.Name = "chkRequiresShiftClose";
        chkRequiresShiftClose.AccessibleName = "يتطلب إقفال وردية";
        chkRequiresShiftClose.Tag = "requiresShiftClose";
        chkRequiresShiftClose.Dock = DockStyle.Fill;
        chkRequiresShiftClose.AutoSize = true;
        chkRequiresShiftClose.Text = "نعم";
        chkRequiresShiftClose.Margin = new Padding(3);
        chkRequiresShiftClose.TabIndex = 10;
        chkRequiresShiftClose.BackColor = Color.FromArgb(255, 249, 219);
        detailsTabs.Name = "detailsTabs";
        detailsTabs.Dock = DockStyle.Fill;
        detailsTabs.RightToLeft = RightToLeft.Yes;
        detailsTabs.RightToLeftLayout = true;
        detailsTabs.MinimumSize = new Size(700, 200);
        detailsTabs.TabIndex = 0;
        tabMain.Name = "tabMain";
        tabMain.Text = "البيانات الرئيسية";
        tabMain.UseVisualStyleBackColor = true;
        tabMainFields.Name = "tabMainFields";
        tabMainFields.Dock = DockStyle.Top;
        tabMainFields.AutoSize = true;
        tabMainFields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        tabMainFields.ColumnCount = 4;
        tabMainFields.RowCount = 3;
        tabMainFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        tabMainFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tabMainFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        tabMainFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tabMainFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        tabMainFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        tabMainFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        tabMainFields.Controls.Add(lblcashboxCode, 0, 0);
        tabMainFields.Controls.Add(txtcashboxCode, 1, 0);
        tabMainFields.Controls.Add(lblcashboxName, 2, 0);
        tabMainFields.Controls.Add(txtcashboxName, 3, 0);
        tabMainFields.Controls.Add(lblcompanyRef, 0, 1);
        tabMainFields.Controls.Add(cmbcompanyRef, 1, 1);
        tabMainFields.Controls.Add(lblbranchRef, 2, 1);
        tabMainFields.Controls.Add(cmbbranchRef, 3, 1);
        tabMainFields.Controls.Add(lblcurrencyRef, 0, 2);
        tabMainFields.Controls.Add(cmbcurrencyRef, 1, 2);
        tabMainFields.Controls.Add(lblstatus, 2, 2);
        tabMainFields.Controls.Add(txtstatus, 3, 2);
        tabMain.Controls.Add(tabMainFields);
        detailsTabs.TabPages.Add(tabMain);
        tabAdditional.Name = "tabAdditional";
        tabAdditional.Text = "بيانات إضافية";
        tabAdditional.UseVisualStyleBackColor = true;
        tabAdditionalFields.Name = "tabAdditionalFields";
        tabAdditionalFields.Dock = DockStyle.Top;
        tabAdditionalFields.AutoSize = true;
        tabAdditionalFields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        tabAdditionalFields.ColumnCount = 4;
        tabAdditionalFields.RowCount = 1;
        tabAdditionalFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        tabAdditionalFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tabAdditionalFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        tabAdditionalFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tabAdditionalFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        tabAdditionalFields.Controls.Add(lbldefaultCashierRef, 0, 0);
        tabAdditionalFields.Controls.Add(cmbdefaultCashierRef, 1, 0);
        tabAdditional.Controls.Add(tabAdditionalFields);
        detailsTabs.TabPages.Add(tabAdditional);
        tabAccounting.Name = "tabAccounting";
        tabAccounting.Text = "الربط المحاسبي";
        tabAccounting.UseVisualStyleBackColor = true;
        tabAccountingFields.Name = "tabAccountingFields";
        tabAccountingFields.Dock = DockStyle.Top;
        tabAccountingFields.AutoSize = true;
        tabAccountingFields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        tabAccountingFields.ColumnCount = 4;
        tabAccountingFields.RowCount = 1;
        tabAccountingFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        tabAccountingFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tabAccountingFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        tabAccountingFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tabAccountingFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        tabAccountingFields.Controls.Add(lblglAccountRef, 0, 0);
        tabAccountingFields.Controls.Add(cmbglAccountRef, 1, 0);
        tabAccounting.Controls.Add(tabAccountingFields);
        detailsTabs.TabPages.Add(tabAccounting);
        tabLimits.Name = "tabLimits";
        tabLimits.Text = "الحدود والصلاحيات";
        tabLimits.UseVisualStyleBackColor = true;
        tabLimitsFields.Name = "tabLimitsFields";
        tabLimitsFields.Dock = DockStyle.Top;
        tabLimitsFields.AutoSize = true;
        tabLimitsFields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        tabLimitsFields.ColumnCount = 4;
        tabLimitsFields.RowCount = 3;
        tabLimitsFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        tabLimitsFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tabLimitsFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        tabLimitsFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tabLimitsFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        tabLimitsFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        tabLimitsFields.Controls.Add(lblmaximumBalance, 0, 0);
        tabLimitsFields.Controls.Add(txtmaximumBalance, 1, 0);
        tabLimitsFields.Controls.Add(lblsingleTransactionLimit, 2, 0);
        tabLimitsFields.Controls.Add(txtsingleTransactionLimit, 3, 0);
        tabLimitsFields.Controls.Add(lblrequiresShiftClose, 0, 1);
        tabLimitsFields.Controls.Add(chkRequiresShiftClose, 1, 1);
        tabLimits.Controls.Add(tabLimitsFields);
        detailsTabs.TabPages.Add(tabLimits);
        tabAttachments.Name = "tabAttachments";
        tabAttachments.Text = "المرفقات";
        tabAttachments.UseVisualStyleBackColor = true;
        tabAttachmentsFields.Name = "tabAttachmentsFields";
        tabAttachmentsFields.Dock = DockStyle.Top;
        tabAttachmentsFields.AutoSize = true;
        tabAttachmentsFields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        tabAttachmentsFields.ColumnCount = 4;
        tabAttachmentsFields.RowCount = 1;
        tabAttachmentsFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        tabAttachmentsFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tabAttachmentsFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        tabAttachmentsFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tabAttachmentsFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        tabAttachments.Controls.Add(tabAttachmentsFields);
        detailsTabs.TabPages.Add(tabAttachments);
        tabOperations.Name = "tabOperations";
        tabOperations.Text = "سجل العمليات";
        tabOperations.UseVisualStyleBackColor = true;
        tabOperationsFields.Name = "tabOperationsFields";
        tabOperationsFields.Dock = DockStyle.Top;
        tabOperationsFields.AutoSize = true;
        tabOperationsFields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        tabOperationsFields.ColumnCount = 4;
        tabOperationsFields.RowCount = 1;
        tabOperationsFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        tabOperationsFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tabOperationsFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        tabOperationsFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tabOperationsFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        tabOperations.Controls.Add(tabOperationsFields);
        detailsTabs.TabPages.Add(tabOperations);
        lblMoneyValidation.Name = "lblMoneyValidation";
        lblMoneyValidation.AutoSize = true;
        lblMoneyValidation.Dock = DockStyle.Fill;
        lblMoneyValidation.Text = "المبالغ اختيارية؛ الفراغ يعني عدم التحديد. يقبل مبلغ غير سالب دون إجراء حسابات.";
        tabLimitsFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        tabLimitsFields.Controls.Add(lblMoneyValidation, 0, 2);
        tabLimitsFields.SetColumnSpan(lblMoneyValidation, 4);
        lblAttachmentsState.Name = "lblAttachmentsState";
        lblAttachmentsState.Text = "المرفقات: لا يوجد مزود مرتبط، ولم تصدر صلاحيات رفع أو تنزيل أو حذف.";
        lblAttachmentsState.Dock = DockStyle.Fill;
        lblAttachmentsState.AutoSize = true;
        tabAttachmentsFields.Controls.Add(lblAttachmentsState, 0, 0);
        txtAttachmentsContext = new TextBox();
        txtAttachmentsContext.Name = "txtAttachmentsContext";
        txtAttachmentsContext.ReadOnly = true;
        txtAttachmentsContext.Multiline = true;
        txtAttachmentsContext.ScrollBars = ScrollBars.Both;
        txtAttachmentsContext.Dock = DockStyle.Fill;
        txtAttachmentsContext.MinimumSize = new Size(240, 140);
        txtAttachmentsContext.AccessibleName = "عرض البيانات المرتبطة";
        tabAttachmentsFields.RowCount = 2;
        tabAttachmentsFields.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tabAttachmentsFields.Controls.Add(txtAttachmentsContext, 0, 1);
        tabAttachmentsFields.SetColumnSpan(lblAttachmentsState, 4);
        lblOperationsState.Name = "lblOperationsState";
        lblOperationsState.Text = "سجل العمليات: لم يتم تحميل بيانات أو ربط مزود السجل.";
        lblOperationsState.Dock = DockStyle.Fill;
        lblOperationsState.AutoSize = true;
        tabOperationsFields.Controls.Add(lblOperationsState, 0, 0);
        txtOperationsContext = new TextBox();
        txtOperationsContext.Name = "txtOperationsContext";
        txtOperationsContext.ReadOnly = true;
        txtOperationsContext.Multiline = true;
        txtOperationsContext.ScrollBars = ScrollBars.Both;
        txtOperationsContext.Dock = DockStyle.Fill;
        txtOperationsContext.MinimumSize = new Size(240, 140);
        txtOperationsContext.AccessibleName = "عرض البيانات المرتبطة";
        tabOperationsFields.RowCount = 2;
        tabOperationsFields.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tabOperationsFields.Controls.Add(txtOperationsContext, 0, 1);
        tabOperationsFields.SetColumnSpan(lblOperationsState, 4);
        contentLayout.Controls.Add(detailsTabs, 0, 0);
        txtmaximumBalance.TextChanged += MonetaryTextChanged;
        txtsingleTransactionLimit.TextChanged += MonetaryTextChanged;
        searchLayout.Name = "searchLayout";
        searchLayout.ColumnCount = 4;
        searchLayout.RowCount = 2;
        searchLayout.Margin = Padding.Empty;
        searchLayout.AutoSize = true;
        searchLayout.Dock = DockStyle.Top;
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        searchLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        lblFiltercode.Name = "lblFiltercode";
        lblFiltercode.Text = "رمز الصندوق";
        lblFiltercode.Dock = DockStyle.Fill;
        filtercode.Name = "filtercode";
        filtercode.Dock = DockStyle.Fill;
        filtercode.TabIndex = 0;
        filtercode.AccessibleName = "رمز الصندوق";
        searchLayout.Controls.Add(lblFiltercode, 0, 0);
        searchLayout.Controls.Add(filtercode, 1, 0);
        lblFiltername.Name = "lblFiltername";
        lblFiltername.Text = "اسم الصندوق";
        lblFiltername.Dock = DockStyle.Fill;
        filtername.Name = "filtername";
        filtername.Dock = DockStyle.Fill;
        filtername.TabIndex = 1;
        filtername.AccessibleName = "اسم الصندوق";
        searchLayout.Controls.Add(lblFiltername, 2, 0);
        searchLayout.Controls.Add(filtername, 3, 0);
        lblFilterstatus.Name = "lblFilterstatus";
        lblFilterstatus.Text = "الحالة";
        lblFilterstatus.Dock = DockStyle.Fill;
        filterstatus.Name = "filterstatus";
        filterstatus.Dock = DockStyle.Fill;
        filterstatus.TabIndex = 2;
        filterstatus.AccessibleName = "الحالة";
        filterstatus.DropDownStyle = ComboBoxStyle.DropDownList;
        searchLayout.Controls.Add(lblFilterstatus, 0, 1);
        searchLayout.Controls.Add(filterstatus, 1, 1);
        btnSearch.Name = "btnSearch";
        btnSearch.Text = "بحث";
        btnSearch.Enabled = false;
        btnSearch.AutoSize = true;
        btnSearch.Dock = DockStyle.None;
        btnSearch.AccessibleDescription = "البحث بالخدمة غير مربوط.";
        searchLayout.Controls.Add(btnSearch, 3, 1);
        contentLayout.Controls.Add(searchLayout, 0, 1);
        dgvRecords.Name = "dgvRecords";
        dgvRecords.Dock = DockStyle.Fill;
        dgvRecords.MinimumSize = new Size(0, 160);
        dgvRecords.ReadOnly = true;
        dgvRecords.AutoGenerateColumns = false;
        dgvRecords.AllowUserToAddRows = false;
        dgvRecords.AllowUserToDeleteRows = false;
        dgvRecords.MultiSelect = false;
        dgvRecords.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvRecords.RowHeadersVisible = false;
        dgvRecords.AccessibleName = "قائمة البيانات — لا توجد بيانات محملة";
        colcashboxCode.Name = "colcashboxCode";
        colcashboxCode.HeaderText = "الرمز";
        colcashboxCode.Tag = "cashboxCode";
        colcashboxCode.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
        colcashboxCode.MinimumWidth = 75;
        colcashboxCode.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colcashboxCode);
        colcashboxName.Name = "colcashboxName";
        colcashboxName.HeaderText = "الاسم";
        colcashboxName.Tag = "cashboxName";
        colcashboxName.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colcashboxName.MinimumWidth = 75;
        colcashboxName.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colcashboxName);
        colcompanyRef.Name = "colcompanyRef";
        colcompanyRef.HeaderText = "الشركة";
        colcompanyRef.Tag = "companyRef";
        colcompanyRef.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
        colcompanyRef.MinimumWidth = 75;
        colcompanyRef.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colcompanyRef);
        colbranchRef.Name = "colbranchRef";
        colbranchRef.HeaderText = "الفرع/النطاق";
        colbranchRef.Tag = "branchRef";
        colbranchRef.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
        colbranchRef.MinimumWidth = 75;
        colbranchRef.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colbranchRef);
        colcurrencyRef.Name = "colcurrencyRef";
        colcurrencyRef.HeaderText = "العملة";
        colcurrencyRef.Tag = "currencyRef";
        colcurrencyRef.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
        colcurrencyRef.MinimumWidth = 75;
        colcurrencyRef.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colcurrencyRef);
        colstatus.Name = "colstatus";
        colstatus.HeaderText = "الحالة";
        colstatus.Tag = "status";
        colstatus.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
        colstatus.MinimumWidth = 75;
        colstatus.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colstatus);
        collastModified.Name = "collastModified";
        collastModified.HeaderText = "آخر تعديل";
        collastModified.Tag = "lastModified";
        collastModified.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
        collastModified.MinimumWidth = 75;
        collastModified.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(collastModified);
        contentLayout.Controls.Add(dgvRecords, 0, 2);
        paging.Name = "paging";
        paging.Dock = DockStyle.Top;
        paging.AutoSize = true;
        paging.WrapContents = true;
        paging.FlowDirection = FlowDirection.LeftToRight;
        paging.RightToLeft = RightToLeft.Yes;
        btnPrevious.Name = "btnPrevious";
        btnPrevious.Text = "السابق";
        btnPrevious.AutoSize = true;
        btnPrevious.Dock = DockStyle.None;
        btnPrevious.Size = new Size(70, 30);
        btnPrevious.Margin = new Padding(4);
        btnPrevious.Enabled = false;
        btnPrevious.AccessibleDescription = "غير منفذ: لم يتم ربط خدمة البيانات أو الحفظ.";
        paging.Controls.Add(btnPrevious);
        btnNext.Name = "btnNext";
        btnNext.Text = "التالي";
        btnNext.AutoSize = true;
        btnNext.Dock = DockStyle.None;
        btnNext.Size = new Size(70, 30);
        btnNext.Margin = new Padding(4);
        btnNext.Enabled = false;
        btnNext.AccessibleDescription = "غير منفذ: لم يتم ربط خدمة البيانات أو الحفظ.";
        paging.Controls.Add(btnNext);
        lblPage.Name = "lblPage";
        lblPage.Text = "الصفحات: — لم يتصل مزود البيانات";
        lblPage.AutoSize = true;
        paging.Controls.Add(lblPage);
        contentLayout.Controls.Add(paging, 0, 3);
        tlpAuditInfo.Name = "tlpAuditInfo";
        tlpAuditInfo.ColumnCount = 2;
        tlpAuditInfo.RowCount = 2;
        tlpAuditInfo.Margin = Padding.Empty;
        tlpAuditInfo.Dock = DockStyle.Top;
        tlpAuditInfo.AutoSize = true;
        tlpAuditInfo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tlpAuditInfo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tlpAuditInfo.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        tlpAuditInfo.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        lblCreatedBy.Name = "lblCreatedBy";
        lblCreatedBy.Text = "أنشأ بواسطة: —";
        lblCreatedBy.AutoSize = true;
        lblCreatedBy.Dock = DockStyle.Fill;
        tlpAuditInfo.Controls.Add(lblCreatedBy, 0, 0);
        lblCreatedAt.Name = "lblCreatedAt";
        lblCreatedAt.Text = "تاريخ الإنشاء: —";
        lblCreatedAt.AutoSize = true;
        lblCreatedAt.Dock = DockStyle.Fill;
        tlpAuditInfo.Controls.Add(lblCreatedAt, 1, 0);
        lblModifiedBy.Name = "lblModifiedBy";
        lblModifiedBy.Text = "عدل بواسطة: —";
        lblModifiedBy.AutoSize = true;
        lblModifiedBy.Dock = DockStyle.Fill;
        tlpAuditInfo.Controls.Add(lblModifiedBy, 0, 1);
        lblModifiedAt.Name = "lblModifiedAt";
        lblModifiedAt.Text = "تاريخ التعديل: —";
        lblModifiedAt.AutoSize = true;
        lblModifiedAt.Dock = DockStyle.Fill;
        tlpAuditInfo.Controls.Add(lblModifiedAt, 1, 1);
        contentLayout.Controls.Add(tlpAuditInfo, 0, 4);
        Controls.Add(mainLayout);
        Name = "UcScreen_04_03_01";
        Text = "الصناديق";
        Tag = "04.03.01";
        AutoScaleDimensions = new SizeF(120F, 120F);
        AutoScaleMode = AutoScaleMode.Dpi;
        RightToLeft = RightToLeft.Yes;
        Font = new Font("Segoe UI", 10F);
        Size = new Size(1100, 760);
        pnlHeader.TabIndex = 0;
        lblDataStatus.TabIndex = 1;
        pnlContent.TabIndex = 2;
        searchLayout.TabIndex = 1;
        dgvRecords.TabIndex = 2;
        paging.TabIndex = 3;
        tlpAuditInfo.TabIndex = 4;
        ((System.ComponentModel.ISupportInitialize)dgvRecords).EndInit();
        pnlContent.SizeChanged += ContentSizeChanged;
        ResumeLayout(false);
        PerformLayout();
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.RightToLeft = RightToLeft.Yes;
        designerCommandBar.Controls.Add(pnlToolbar);
        pnlToolbar.Dock = DockStyle.Fill;
        pnlToolbar.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        pnlToolbar.Name = "pnlToolbar";
        pnlToolbar.Dock = DockStyle.Fill;
        pnlToolbar.AutoSize = false;
        pnlToolbar.WrapContents = false;
        pnlToolbar.FlowDirection = FlowDirection.RightToLeft;
        pnlToolbar.RightToLeft = RightToLeft.No;
        pnlToolbar.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 44;
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        btnNew.AutoSize = false;
        btnNew.Dock = DockStyle.None;
        btnNew.MinimumSize = Size.Empty;
        btnNew.Size = new Size(26, 24);
        btnNew.Margin = new Padding(1);
        btnNew.FlatStyle = FlatStyle.Flat;
        btnNew.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnNew.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        btnNew.Text = "";
        pnlToolbar.Controls.Add(btnNew);
        designerCommandBar.SetCommandRole(btnNew, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        btnEdit.AutoSize = false;
        btnEdit.Dock = DockStyle.None;
        btnEdit.MinimumSize = Size.Empty;
        btnEdit.Size = new Size(26, 24);
        btnEdit.Margin = new Padding(1);
        btnEdit.FlatStyle = FlatStyle.Flat;
        btnEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        btnEdit.Text = "";
        pnlToolbar.Controls.Add(btnEdit);
        designerCommandBar.SetCommandRole(btnEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        pnlToolbar.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.AutoSize = false;
        standardCommandCancel.Dock = DockStyle.None;
        standardCommandCancel.MinimumSize = Size.Empty;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandCancel.Text = "";
        pnlToolbar.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        btnView.AutoSize = false;
        btnView.Dock = DockStyle.None;
        btnView.MinimumSize = Size.Empty;
        btnView.Size = new Size(26, 24);
        btnView.Margin = new Padding(1);
        btnView.FlatStyle = FlatStyle.Flat;
        btnView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        btnView.Text = "";
        pnlToolbar.Controls.Add(btnView);
        designerCommandBar.SetCommandRole(btnView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        pnlToolbar.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        pnlToolbar.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        pnlToolbar.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        pnlToolbar.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        btnSave.AutoSize = false;
        btnSave.Dock = DockStyle.None;
        btnSave.MinimumSize = Size.Empty;
        btnSave.Size = new Size(26, 24);
        btnSave.Margin = new Padding(1);
        btnSave.FlatStyle = FlatStyle.Flat;
        btnSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        btnSave.Text = "";
        pnlToolbar.Controls.Add(btnSave);
        designerCommandBar.SetCommandRole(btnSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        pnlToolbar.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        btnClose.AutoSize = false;
        btnClose.Dock = DockStyle.None;
        btnClose.MinimumSize = Size.Empty;
        btnClose.Size = new Size(26, 24);
        btnClose.Margin = new Padding(1);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        btnClose.Text = "";
        designerCloseHost.Controls.Add(btnClose);
        btnClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        pnlToolbar.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        pnlToolbar.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        pnlToolbar.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        pnlToolbar.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        tlpAuditInfo.Visible = false;
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}
}
