namespace TransportERP.EmptyForms;
partial class UcScreen_04_03_03
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel mainLayout = null!;
    private TableLayoutPanel pnlHeader = null!;
    private Label lblTitle = null!;
    private FlowLayoutPanel pnlToolbar = null!;
    private Button btnView = null!;
    private Button btnNew = null!;
    private Button btnSave = null!;
    private Button btnEdit = null!;
    private Button btnDisable = null!;
    private Button btnClose = null!;
    private Label lblDataStatus = null!;
    private Panel pnlContent = null!;
    private TableLayoutPanel contentLayout = null!;
    private TabControl detailsTabs = null!;
    private TabPage section0 = null!;
    private TableLayoutPanel section0Fields = null!;
    private Label labelbankAccountCode = null!;
    private TextBox fieldbankAccountCode = null!;
    private Label labelbankName = null!;
    private TextBox fieldbankName = null!;
    private Label labelaccountName = null!;
    private TextBox fieldaccountName = null!;
    private Label labelaccountNumber = null!;
    private TextBox fieldaccountNumber = null!;
    private Label labelcompanyRef = null!;
    private ComboBox fieldcompanyRef = null!;
    private Label labelbranchRef = null!;
    private ComboBox fieldbranchRef = null!;
    private Label labelcurrencyRef = null!;
    private ComboBox fieldcurrencyRef = null!;
    private Label labelstatus = null!;
    private TextBox fieldstatus = null!;
    private TabPage section1 = null!;
    private TableLayoutPanel section1Fields = null!;
    private Label labeliban = null!;
    private TextBox fieldiban = null!;
    private Label labelswiftBic = null!;
    private TextBox fieldswiftBic = null!;
    private TabPage section2 = null!;
    private TableLayoutPanel section2Fields = null!;
    private Label labelglAccountRef = null!;
    private ComboBox fieldglAccountRef = null!;
    private Label labelbankFeesAccountRef = null!;
    private ComboBox fieldbankFeesAccountRef = null!;
    private Label labelreconciliationDifferenceAccountRef = null!;
    private ComboBox fieldreconciliationDifferenceAccountRef = null!;
    private TabPage section3 = null!;
    private TableLayoutPanel section3Fields = null!;
    private Label labelwithdrawalTransferLimit = null!;
    private TextBox fieldwithdrawalTransferLimit = null!;
    private TabPage section4 = null!;
    private TableLayoutPanel section4Fields = null!;
    private RichTextBox state4 = null!;
    private TabPage section5 = null!;
    private TableLayoutPanel section5Fields = null!;
    private RichTextBox state5 = null!;
    private TableLayoutPanel searchLayout = null!;
    private Label filterLabelcode = null!;
    private TextBox filtercode = null!;
    private Label filterLabelname = null!;
    private TextBox filtername = null!;
    private Label filterLabelstatus = null!;
    private ComboBox filterstatus = null!;
    private Button btnSearch = null!;
    private DataGridView dgvRecords = null!;
    private DataGridViewTextBoxColumn colbankAccountCode = null!;
    private DataGridViewTextBoxColumn coldisplayName = null!;
    private DataGridViewTextBoxColumn colcompanyRef = null!;
    private DataGridViewTextBoxColumn colbranchRef = null!;
    private DataGridViewTextBoxColumn colcurrencyRef = null!;
    private DataGridViewTextBoxColumn colstatus = null!;
    private DataGridViewTextBoxColumn collastModified = null!;
    private FlowLayoutPanel paging = null!;
    private Button btnPrevious = null!;
    private Button btnNext = null!;
    private Label lblPage = null!;
    private TableLayoutPanel statusLayout = null!;
    private Label lblState = null!;
    private TableLayoutPanel tlpAuditInfo = null!;
    private Label lblCreatedBy = null!;
    private Label lblCreatedAt = null!;
    private Label lblModifiedBy = null!;
    private Label lblModifiedAt = null!;
    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCloseHost = new Panel();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandPrint = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        mainLayout = new TableLayoutPanel();
        pnlHeader = new TableLayoutPanel();
        lblTitle = new Label();
        pnlToolbar = new FlowLayoutPanel();
        btnView = new Button();
        btnNew = new Button();
        btnSave = new Button();
        btnEdit = new Button();
        btnDisable = new Button();
        btnClose = new Button();
        lblDataStatus = new Label();
        pnlContent = new Panel();
        contentLayout = new TableLayoutPanel();
        detailsTabs = new TabControl();
        section0 = new TabPage();
        section0Fields = new TableLayoutPanel();
        labelbankAccountCode = new Label();
        fieldbankAccountCode = new TextBox();
        labelbankName = new Label();
        fieldbankName = new TextBox();
        labelaccountName = new Label();
        fieldaccountName = new TextBox();
        labelaccountNumber = new Label();
        fieldaccountNumber = new TextBox();
        labelcompanyRef = new Label();
        fieldcompanyRef = new ComboBox();
        labelbranchRef = new Label();
        fieldbranchRef = new ComboBox();
        labelcurrencyRef = new Label();
        fieldcurrencyRef = new ComboBox();
        labelstatus = new Label();
        fieldstatus = new TextBox();
        section1 = new TabPage();
        section1Fields = new TableLayoutPanel();
        labeliban = new Label();
        fieldiban = new TextBox();
        labelswiftBic = new Label();
        fieldswiftBic = new TextBox();
        section2 = new TabPage();
        section2Fields = new TableLayoutPanel();
        labelglAccountRef = new Label();
        fieldglAccountRef = new ComboBox();
        labelbankFeesAccountRef = new Label();
        fieldbankFeesAccountRef = new ComboBox();
        labelreconciliationDifferenceAccountRef = new Label();
        fieldreconciliationDifferenceAccountRef = new ComboBox();
        section3 = new TabPage();
        section3Fields = new TableLayoutPanel();
        labelwithdrawalTransferLimit = new Label();
        fieldwithdrawalTransferLimit = new TextBox();
        section4 = new TabPage();
        section4Fields = new TableLayoutPanel();
        state4 = new RichTextBox();
        section5 = new TabPage();
        section5Fields = new TableLayoutPanel();
        state5 = new RichTextBox();
        searchLayout = new TableLayoutPanel();
        filterLabelcode = new Label();
        filtercode = new TextBox();
        filterLabelname = new Label();
        filtername = new TextBox();
        filterLabelstatus = new Label();
        filterstatus = new ComboBox();
        btnSearch = new Button();
        dgvRecords = new DataGridView();
        colbankAccountCode = new DataGridViewTextBoxColumn();
        coldisplayName = new DataGridViewTextBoxColumn();
        colcompanyRef = new DataGridViewTextBoxColumn();
        colbranchRef = new DataGridViewTextBoxColumn();
        colcurrencyRef = new DataGridViewTextBoxColumn();
        colstatus = new DataGridViewTextBoxColumn();
        collastModified = new DataGridViewTextBoxColumn();
        paging = new FlowLayoutPanel();
        btnPrevious = new Button();
        btnNext = new Button();
        lblPage = new Label();
        statusLayout = new TableLayoutPanel();
        lblState = new Label();
        tlpAuditInfo = new TableLayoutPanel();
        lblCreatedBy = new Label();
        lblCreatedAt = new Label();
        lblModifiedBy = new Label();
        lblModifiedAt = new Label();
        SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)dgvRecords).BeginInit();
        mainLayout.Name = "mainLayout";
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 3;
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = Padding.Empty;
        mainLayout.AutoSize = false;
        mainLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlHeader.Name = "pnlHeader";
        pnlHeader.ColumnCount = 1;
        pnlHeader.RowCount = 2;
        pnlHeader.Dock = DockStyle.Top;
        pnlHeader.Margin = Padding.Empty;
        pnlHeader.AutoSize = true;
        pnlHeader.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "الحسابات البنكية";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleRight;
        pnlHeader.Controls.Add(lblTitle, 0, 0);
        lblTitle.Font = new Font("Segoe UI", 16F);
        pnlToolbar.Name = "pnlToolbar";
        pnlToolbar.Dock = DockStyle.Top;
        pnlToolbar.AutoSize = true;
        pnlToolbar.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlToolbar.FlowDirection = FlowDirection.LeftToRight;
        pnlToolbar.RightToLeft = RightToLeft.Yes;
        pnlToolbar.WrapContents = true;
        btnView.Name = "btnView";
        btnView.Text = "عرض";
        btnView.Size = new Size(70, 30);
        btnView.Dock = DockStyle.None;
        btnView.AutoSize = true;
        btnView.Enabled = false;
        btnView.AccessibleDescription = "غير مربوط بالخدمة؛ لا يتم تنفيذ أو حفظ بيانات.";

        btnNew.Name = "btnNew";
        btnNew.Text = "جديد";
        btnNew.Size = new Size(70, 30);
        btnNew.Dock = DockStyle.None;
        btnNew.AutoSize = true;
        btnNew.Enabled = false;
        btnNew.AccessibleDescription = "غير مربوط بالخدمة؛ لا يتم تنفيذ أو حفظ بيانات.";

        btnSave.Name = "btnSave";
        btnSave.Text = "حفظ";
        btnSave.Size = new Size(70, 30);
        btnSave.Dock = DockStyle.None;
        btnSave.AutoSize = true;
        btnSave.Enabled = false;
        btnSave.AccessibleDescription = "غير مربوط بالخدمة؛ لا يتم تنفيذ أو حفظ بيانات.";

        btnEdit.Name = "btnEdit";
        btnEdit.Text = "تعديل";
        btnEdit.Size = new Size(70, 30);
        btnEdit.Dock = DockStyle.None;
        btnEdit.AutoSize = true;
        btnEdit.Enabled = false;
        btnEdit.AccessibleDescription = "غير مربوط بالخدمة؛ لا يتم تنفيذ أو حفظ بيانات.";

        btnDisable.Name = "btnDisable";
        btnDisable.Text = "إيقاف";
        btnDisable.Size = new Size(70, 30);
        btnDisable.Dock = DockStyle.None;
        btnDisable.AutoSize = true;
        btnDisable.Enabled = false;
        btnDisable.AccessibleDescription = "غير مربوط بالخدمة؛ لا يتم تنفيذ أو حفظ بيانات.";
        pnlToolbar.Controls.Add(btnDisable);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.Size = new Size(70, 30);
        btnClose.Dock = DockStyle.None;
        btnClose.AutoSize = true;
        btnClose.Enabled = true;
        btnClose.AccessibleDescription = "إغلاق الشاشة";

        btnClose.Click += BtnClose_Click;
        pnlHeader.Controls.Add(designerCommandBar, 0, 1);
        mainLayout.Controls.Add(pnlHeader, 0, 0);
        lblDataStatus.Name = "lblDataStatus";
        lblDataStatus.Text = "واجهة تصميم — لا توجد بيانات محملة؛ الأوامر والبحث والتصفح غير مرتبطة بالخدمات.";
        lblDataStatus.AutoSize = true;
        lblDataStatus.Dock = DockStyle.Fill;
        lblDataStatus.TextAlign = ContentAlignment.MiddleRight;
        mainLayout.Controls.Add(lblDataStatus, 0, 1);
        pnlContent.Name = "pnlContent";
        pnlContent.Dock = DockStyle.Fill;
        pnlContent.AutoScroll = true;
        mainLayout.Controls.Add(pnlContent, 0, 2);
        contentLayout.Name = "contentLayout";
        contentLayout.ColumnCount = 1;
        contentLayout.RowCount = 6;
        contentLayout.Dock = DockStyle.Fill;
        contentLayout.Margin = Padding.Empty;
        contentLayout.AutoSize = false;
        contentLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        contentLayout.Dock = DockStyle.None;
        contentLayout.MinimumSize = new Size(700, 0);
        contentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 200F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        pnlContent.Controls.Add(contentLayout);
        detailsTabs.Name = "detailsTabs";
        detailsTabs.Dock = DockStyle.Fill;
        detailsTabs.RightToLeftLayout = true;
        detailsTabs.MinimumSize = new Size(0, 200);
        contentLayout.Controls.Add(detailsTabs, 0, 0);
        section0.Name = "section0";
        section0.Text = "البيانات الرئيسية";
        section0.Dock = DockStyle.Top;
        section0.AutoSize = true;
        section0Fields.Name = "section0Fields";
        section0Fields.ColumnCount = 4;
        section0Fields.RowCount = 4;
        section0Fields.Dock = DockStyle.Top;
        section0Fields.Margin = Padding.Empty;
        section0Fields.AutoSize = true;
        section0Fields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        section0Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        section0Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        section0Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        section0Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        section0Fields.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        section0Fields.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        section0Fields.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        section0Fields.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        labelbankAccountCode.Name = "labelbankAccountCode";
        labelbankAccountCode.Text = "رمز الحساب البنكي *";
        labelbankAccountCode.AutoSize = true;
        labelbankAccountCode.Dock = DockStyle.Fill;
        labelbankAccountCode.TextAlign = ContentAlignment.MiddleRight;
        section0Fields.Controls.Add(labelbankAccountCode, 0, 0);
        fieldbankAccountCode.Name = "fieldbankAccountCode";
        fieldbankAccountCode.Tag = "bankAccountCode";
        fieldbankAccountCode.AccessibleName = "رمز الحساب البنكي";
        fieldbankAccountCode.Dock = DockStyle.Fill;
        fieldbankAccountCode.Margin = new Padding(3);
        fieldbankAccountCode.TabIndex = 0;
        fieldbankAccountCode.BackColor = Color.FromArgb(255, 249, 219);
        fieldbankAccountCode.RightToLeft = RightToLeft.No;
        section0Fields.Controls.Add(fieldbankAccountCode, 1, 0);
        labelbankName.Name = "labelbankName";
        labelbankName.Text = "اسم البنك *";
        labelbankName.AutoSize = true;
        labelbankName.Dock = DockStyle.Fill;
        labelbankName.TextAlign = ContentAlignment.MiddleRight;
        section0Fields.Controls.Add(labelbankName, 2, 0);
        fieldbankName.Name = "fieldbankName";
        fieldbankName.Tag = "bankName";
        fieldbankName.AccessibleName = "اسم البنك";
        fieldbankName.Dock = DockStyle.Fill;
        fieldbankName.Margin = new Padding(3);
        fieldbankName.TabIndex = 1;
        fieldbankName.BackColor = Color.FromArgb(255, 249, 219);
        section0Fields.Controls.Add(fieldbankName, 3, 0);
        labelaccountName.Name = "labelaccountName";
        labelaccountName.Text = "اسم الحساب *";
        labelaccountName.AutoSize = true;
        labelaccountName.Dock = DockStyle.Fill;
        labelaccountName.TextAlign = ContentAlignment.MiddleRight;
        section0Fields.Controls.Add(labelaccountName, 0, 1);
        fieldaccountName.Name = "fieldaccountName";
        fieldaccountName.Tag = "accountName";
        fieldaccountName.AccessibleName = "اسم الحساب";
        fieldaccountName.Dock = DockStyle.Fill;
        fieldaccountName.Margin = new Padding(3);
        fieldaccountName.TabIndex = 2;
        fieldaccountName.BackColor = Color.FromArgb(255, 249, 219);
        section0Fields.Controls.Add(fieldaccountName, 1, 1);
        labelaccountNumber.Name = "labelaccountNumber";
        labelaccountNumber.Text = "رقم الحساب *";
        labelaccountNumber.AutoSize = true;
        labelaccountNumber.Dock = DockStyle.Fill;
        labelaccountNumber.TextAlign = ContentAlignment.MiddleRight;
        section0Fields.Controls.Add(labelaccountNumber, 2, 1);
        fieldaccountNumber.Name = "fieldaccountNumber";
        fieldaccountNumber.Tag = "accountNumber";
        fieldaccountNumber.AccessibleName = "رقم الحساب";
        fieldaccountNumber.Dock = DockStyle.Fill;
        fieldaccountNumber.Margin = new Padding(3);
        fieldaccountNumber.TabIndex = 3;
        fieldaccountNumber.BackColor = Color.FromArgb(255, 249, 219);
        fieldaccountNumber.RightToLeft = RightToLeft.No;
        section0Fields.Controls.Add(fieldaccountNumber, 3, 1);
        labelcompanyRef.Name = "labelcompanyRef";
        labelcompanyRef.Text = "الشركة *";
        labelcompanyRef.AutoSize = true;
        labelcompanyRef.Dock = DockStyle.Fill;
        labelcompanyRef.TextAlign = ContentAlignment.MiddleRight;
        section0Fields.Controls.Add(labelcompanyRef, 0, 2);
        fieldcompanyRef.Name = "fieldcompanyRef";
        fieldcompanyRef.Tag = "companyRef";
        fieldcompanyRef.AccessibleName = "الشركة";
        fieldcompanyRef.Dock = DockStyle.Fill;
        fieldcompanyRef.Margin = new Padding(3);
        fieldcompanyRef.TabIndex = 4;
        fieldcompanyRef.BackColor = Color.FromArgb(255, 249, 219);
        fieldcompanyRef.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldcompanyRef.AccessibleDescription = "القيم والمزود والتعيين التقني غير موصولة؛ لا توجد قائمة محلية مفترضة.";
        section0Fields.Controls.Add(fieldcompanyRef, 1, 2);
        labelbranchRef.Name = "labelbranchRef";
        labelbranchRef.Text = "الفرع";
        labelbranchRef.AutoSize = true;
        labelbranchRef.Dock = DockStyle.Fill;
        labelbranchRef.TextAlign = ContentAlignment.MiddleRight;
        section0Fields.Controls.Add(labelbranchRef, 2, 2);
        fieldbranchRef.Name = "fieldbranchRef";
        fieldbranchRef.Tag = "branchRef";
        fieldbranchRef.AccessibleName = "الفرع";
        fieldbranchRef.Dock = DockStyle.Fill;
        fieldbranchRef.Margin = new Padding(3);
        fieldbranchRef.TabIndex = 5;
        fieldbranchRef.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldbranchRef.AccessibleDescription = "القيم والمزود والتعيين التقني غير موصولة؛ لا توجد قائمة محلية مفترضة.";
        section0Fields.Controls.Add(fieldbranchRef, 3, 2);
        labelcurrencyRef.Name = "labelcurrencyRef";
        labelcurrencyRef.Text = "العملة *";
        labelcurrencyRef.AutoSize = true;
        labelcurrencyRef.Dock = DockStyle.Fill;
        labelcurrencyRef.TextAlign = ContentAlignment.MiddleRight;
        section0Fields.Controls.Add(labelcurrencyRef, 0, 3);
        fieldcurrencyRef.Name = "fieldcurrencyRef";
        fieldcurrencyRef.Tag = "currencyRef";
        fieldcurrencyRef.AccessibleName = "العملة";
        fieldcurrencyRef.Dock = DockStyle.Fill;
        fieldcurrencyRef.Margin = new Padding(3);
        fieldcurrencyRef.TabIndex = 6;
        fieldcurrencyRef.BackColor = Color.FromArgb(255, 249, 219);
        fieldcurrencyRef.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldcurrencyRef.AccessibleDescription = "القيم والمزود والتعيين التقني غير موصولة؛ لا توجد قائمة محلية مفترضة.";
        section0Fields.Controls.Add(fieldcurrencyRef, 1, 3);
        labelstatus.Name = "labelstatus";
        labelstatus.Text = "الحالة";
        labelstatus.AutoSize = true;
        labelstatus.Dock = DockStyle.Fill;
        labelstatus.TextAlign = ContentAlignment.MiddleRight;
        section0Fields.Controls.Add(labelstatus, 2, 3);
        fieldstatus.Name = "fieldstatus";
        fieldstatus.Tag = "status";
        fieldstatus.AccessibleName = "الحالة";
        fieldstatus.Dock = DockStyle.Fill;
        fieldstatus.Margin = new Padding(3);
        fieldstatus.TabIndex = 7;
        fieldstatus.ReadOnly = true;
        section0Fields.Controls.Add(fieldstatus, 3, 3);
        section0.Controls.Add(section0Fields);
        detailsTabs.TabPages.Add(section0);
        section1.Name = "section1";
        section1.Text = "بيانات إضافية";
        section1.Dock = DockStyle.Top;
        section1.AutoSize = true;
        section1Fields.Name = "section1Fields";
        section1Fields.ColumnCount = 4;
        section1Fields.RowCount = 1;
        section1Fields.Dock = DockStyle.Top;
        section1Fields.Margin = Padding.Empty;
        section1Fields.AutoSize = true;
        section1Fields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        section1Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        section1Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        section1Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        section1Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        section1Fields.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        labeliban.Name = "labeliban";
        labeliban.Text = "IBAN";
        labeliban.AutoSize = true;
        labeliban.Dock = DockStyle.Fill;
        labeliban.TextAlign = ContentAlignment.MiddleRight;
        section1Fields.Controls.Add(labeliban, 0, 0);
        fieldiban.Name = "fieldiban";
        fieldiban.Tag = "iban";
        fieldiban.AccessibleName = "IBAN";
        fieldiban.Dock = DockStyle.Fill;
        fieldiban.Margin = new Padding(3);
        fieldiban.TabIndex = 0;
        fieldiban.RightToLeft = RightToLeft.No;
        section1Fields.Controls.Add(fieldiban, 1, 0);
        labelswiftBic.Name = "labelswiftBic";
        labelswiftBic.Text = "SWIFT/BIC";
        labelswiftBic.AutoSize = true;
        labelswiftBic.Dock = DockStyle.Fill;
        labelswiftBic.TextAlign = ContentAlignment.MiddleRight;
        section1Fields.Controls.Add(labelswiftBic, 2, 0);
        fieldswiftBic.Name = "fieldswiftBic";
        fieldswiftBic.Tag = "swiftBic";
        fieldswiftBic.AccessibleName = "SWIFT/BIC";
        fieldswiftBic.Dock = DockStyle.Fill;
        fieldswiftBic.Margin = new Padding(3);
        fieldswiftBic.TabIndex = 1;
        fieldswiftBic.RightToLeft = RightToLeft.No;
        section1Fields.Controls.Add(fieldswiftBic, 3, 0);
        section1.Controls.Add(section1Fields);
        detailsTabs.TabPages.Add(section1);
        section2.Name = "section2";
        section2.Text = "الربط المحاسبي";
        section2.Dock = DockStyle.Top;
        section2.AutoSize = true;
        section2Fields.Name = "section2Fields";
        section2Fields.ColumnCount = 4;
        section2Fields.RowCount = 2;
        section2Fields.Dock = DockStyle.Top;
        section2Fields.Margin = Padding.Empty;
        section2Fields.AutoSize = true;
        section2Fields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        section2Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        section2Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        section2Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        section2Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        section2Fields.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        section2Fields.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        labelglAccountRef.Name = "labelglAccountRef";
        labelglAccountRef.Text = "حساب الأستاذ *";
        labelglAccountRef.AutoSize = true;
        labelglAccountRef.Dock = DockStyle.Fill;
        labelglAccountRef.TextAlign = ContentAlignment.MiddleRight;
        section2Fields.Controls.Add(labelglAccountRef, 0, 0);
        fieldglAccountRef.Name = "fieldglAccountRef";
        fieldglAccountRef.Tag = "glAccountRef";
        fieldglAccountRef.AccessibleName = "حساب الأستاذ";
        fieldglAccountRef.Dock = DockStyle.Fill;
        fieldglAccountRef.Margin = new Padding(3);
        fieldglAccountRef.TabIndex = 0;
        fieldglAccountRef.BackColor = Color.FromArgb(255, 249, 219);
        fieldglAccountRef.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldglAccountRef.AccessibleDescription = "القيم والمزود والتعيين التقني غير موصولة؛ لا توجد قائمة محلية مفترضة.";
        section2Fields.Controls.Add(fieldglAccountRef, 1, 0);
        labelbankFeesAccountRef.Name = "labelbankFeesAccountRef";
        labelbankFeesAccountRef.Text = "حساب رسوم البنك";
        labelbankFeesAccountRef.AutoSize = true;
        labelbankFeesAccountRef.Dock = DockStyle.Fill;
        labelbankFeesAccountRef.TextAlign = ContentAlignment.MiddleRight;
        section2Fields.Controls.Add(labelbankFeesAccountRef, 2, 0);
        fieldbankFeesAccountRef.Name = "fieldbankFeesAccountRef";
        fieldbankFeesAccountRef.Tag = "bankFeesAccountRef";
        fieldbankFeesAccountRef.AccessibleName = "حساب رسوم البنك";
        fieldbankFeesAccountRef.Dock = DockStyle.Fill;
        fieldbankFeesAccountRef.Margin = new Padding(3);
        fieldbankFeesAccountRef.TabIndex = 1;
        fieldbankFeesAccountRef.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldbankFeesAccountRef.AccessibleDescription = "القيم والمزود والتعيين التقني غير موصولة؛ لا توجد قائمة محلية مفترضة.";
        section2Fields.Controls.Add(fieldbankFeesAccountRef, 3, 0);
        labelreconciliationDifferenceAccountRef.Name = "labelreconciliationDifferenceAccountRef";
        labelreconciliationDifferenceAccountRef.Text = "حساب فروق التسوية";
        labelreconciliationDifferenceAccountRef.AutoSize = true;
        labelreconciliationDifferenceAccountRef.Dock = DockStyle.Fill;
        labelreconciliationDifferenceAccountRef.TextAlign = ContentAlignment.MiddleRight;
        section2Fields.Controls.Add(labelreconciliationDifferenceAccountRef, 0, 1);
        fieldreconciliationDifferenceAccountRef.Name = "fieldreconciliationDifferenceAccountRef";
        fieldreconciliationDifferenceAccountRef.Tag = "reconciliationDifferenceAccountRef";
        fieldreconciliationDifferenceAccountRef.AccessibleName = "حساب فروق التسوية";
        fieldreconciliationDifferenceAccountRef.Dock = DockStyle.Fill;
        fieldreconciliationDifferenceAccountRef.Margin = new Padding(3);
        fieldreconciliationDifferenceAccountRef.TabIndex = 2;
        fieldreconciliationDifferenceAccountRef.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldreconciliationDifferenceAccountRef.AccessibleDescription = "القيم والمزود والتعيين التقني غير موصولة؛ لا توجد قائمة محلية مفترضة.";
        section2Fields.Controls.Add(fieldreconciliationDifferenceAccountRef, 1, 1);
        section2.Controls.Add(section2Fields);
        detailsTabs.TabPages.Add(section2);
        section3.Name = "section3";
        section3.Text = "الحدود والصلاحيات";
        section3.Dock = DockStyle.Top;
        section3.AutoSize = true;
        section3Fields.Name = "section3Fields";
        section3Fields.ColumnCount = 4;
        section3Fields.RowCount = 1;
        section3Fields.Dock = DockStyle.Top;
        section3Fields.Margin = Padding.Empty;
        section3Fields.AutoSize = true;
        section3Fields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        section3Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        section3Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        section3Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        section3Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        section3Fields.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        labelwithdrawalTransferLimit.Name = "labelwithdrawalTransferLimit";
        labelwithdrawalTransferLimit.Text = "حد السحب/التحويل";
        labelwithdrawalTransferLimit.AutoSize = true;
        labelwithdrawalTransferLimit.Dock = DockStyle.Fill;
        labelwithdrawalTransferLimit.TextAlign = ContentAlignment.MiddleRight;
        section3Fields.Controls.Add(labelwithdrawalTransferLimit, 0, 0);
        fieldwithdrawalTransferLimit.Name = "fieldwithdrawalTransferLimit";
        fieldwithdrawalTransferLimit.Tag = "withdrawalTransferLimit";
        fieldwithdrawalTransferLimit.AccessibleName = "حد السحب/التحويل";
        fieldwithdrawalTransferLimit.Dock = DockStyle.Fill;
        fieldwithdrawalTransferLimit.Margin = new Padding(3);
        fieldwithdrawalTransferLimit.TabIndex = 0;
        fieldwithdrawalTransferLimit.RightToLeft = RightToLeft.No;
        fieldwithdrawalTransferLimit.TextAlign = HorizontalAlignment.Right;
        fieldwithdrawalTransferLimit.TextChanged += MonetaryTextChanged;
        section3Fields.Controls.Add(fieldwithdrawalTransferLimit, 1, 0);
        section3.Controls.Add(section3Fields);
        detailsTabs.TabPages.Add(section3);
        section4.Name = "section4";
        section4.Text = "المرفقات";
        section4.Dock = DockStyle.Top;
        section4.AutoSize = true;
        section4Fields.Name = "section4Fields";
        section4Fields.ColumnCount = 4;
        section4Fields.RowCount = 1;
        section4Fields.Dock = DockStyle.Top;
        section4Fields.Margin = Padding.Empty;
        section4Fields.AutoSize = true;
        section4Fields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        section4Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        section4Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        section4Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        section4Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        section4Fields.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        state4.Name = "state4";
        state4.Text = "المرفقات غير مرتبطة؛ لا توجد صلاحيات رفع أو تنزيل أو حذف.";
        state4.Dock = DockStyle.Fill;
        state4.Dock = DockStyle.Fill;
        state4.ReadOnly = true;
        state4.BorderStyle = BorderStyle.None;
        state4.BackColor = SystemColors.Window;
        state4.MinimumSize = new Size(0, 180);
        section4Fields.Controls.Add(state4, 0, 0);
        section4Fields.SetColumnSpan(state4, 4);
        section4.Controls.Add(section4Fields);
        detailsTabs.TabPages.Add(section4);
        section5.Name = "section5";
        section5.Text = "سجل العمليات";
        section5.Dock = DockStyle.Top;
        section5.AutoSize = true;
        section5Fields.Name = "section5Fields";
        section5Fields.ColumnCount = 4;
        section5Fields.RowCount = 1;
        section5Fields.Dock = DockStyle.Top;
        section5Fields.Margin = Padding.Empty;
        section5Fields.AutoSize = true;
        section5Fields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        section5Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        section5Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        section5Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        section5Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        section5Fields.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        state5.Name = "state5";
        state5.Text = "سجل العمليات غير مرتبط؛ لا توجد سجلات محملة.";
        state5.Dock = DockStyle.Fill;
        state5.Dock = DockStyle.Fill;
        state5.ReadOnly = true;
        state5.BorderStyle = BorderStyle.None;
        state5.BackColor = SystemColors.Window;
        state5.MinimumSize = new Size(0, 180);
        section5Fields.Controls.Add(state5, 0, 0);
        section5Fields.SetColumnSpan(state5, 4);
        section5.Controls.Add(section5Fields);
        detailsTabs.TabPages.Add(section5);
        searchLayout.Name = "searchLayout";
        searchLayout.ColumnCount = 4;
        searchLayout.RowCount = 2;
        searchLayout.Dock = DockStyle.Top;
        searchLayout.Margin = Padding.Empty;
        searchLayout.AutoSize = true;
        searchLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        searchLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        filterLabelcode.Name = "filterLabelcode";
        filterLabelcode.Text = "الرمز";
        filterLabelcode.AutoSize = true;
        filterLabelcode.Dock = DockStyle.Fill;
        filterLabelcode.TextAlign = ContentAlignment.MiddleRight;
        searchLayout.Controls.Add(filterLabelcode, 0, 0);
        filtercode.Name = "filtercode";
        filtercode.Dock = DockStyle.Fill;
        filtercode.AccessibleName = "الرمز";
        filtercode.TabIndex = 0;
        searchLayout.Controls.Add(filtercode, 1, 0);
        filterLabelname.Name = "filterLabelname";
        filterLabelname.Text = "الاسم";
        filterLabelname.AutoSize = true;
        filterLabelname.Dock = DockStyle.Fill;
        filterLabelname.TextAlign = ContentAlignment.MiddleRight;
        searchLayout.Controls.Add(filterLabelname, 2, 0);
        filtername.Name = "filtername";
        filtername.Dock = DockStyle.Fill;
        filtername.AccessibleName = "الاسم";
        filtername.TabIndex = 1;
        searchLayout.Controls.Add(filtername, 3, 0);
        filterLabelstatus.Name = "filterLabelstatus";
        filterLabelstatus.Text = "الحالة";
        filterLabelstatus.AutoSize = true;
        filterLabelstatus.Dock = DockStyle.Fill;
        filterLabelstatus.TextAlign = ContentAlignment.MiddleRight;
        searchLayout.Controls.Add(filterLabelstatus, 0, 1);
        filterstatus.Name = "filterstatus";
        filterstatus.Dock = DockStyle.Fill;
        filterstatus.AccessibleName = "الحالة";
        filterstatus.TabIndex = 2;
        filterstatus.DropDownStyle = ComboBoxStyle.DropDownList;
        searchLayout.Controls.Add(filterstatus, 1, 1);
        btnSearch.Name = "btnSearch";
        btnSearch.Text = "بحث";
        btnSearch.Enabled = false;
        btnSearch.AutoSize = true;
        searchLayout.Controls.Add(btnSearch, 3, 1);
        contentLayout.Controls.Add(searchLayout, 0, 1);
        dgvRecords.Name = "dgvRecords";
        dgvRecords.Dock = DockStyle.Fill;
        dgvRecords.MinimumSize = new Size(0, 160);
        dgvRecords.ReadOnly = true;
        dgvRecords.AutoGenerateColumns = false;
        dgvRecords.AllowUserToAddRows = false;
        dgvRecords.AllowUserToDeleteRows = false;
        dgvRecords.MultiSelect = false;
        dgvRecords.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvRecords.RowHeadersVisible = false;
        colbankAccountCode.Name = "colbankAccountCode";
        colbankAccountCode.HeaderText = "الرمز";
        colbankAccountCode.Tag = "bankAccountCode";
        colbankAccountCode.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
        colbankAccountCode.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colbankAccountCode);
        coldisplayName.Name = "coldisplayName";
        coldisplayName.HeaderText = "الاسم";
        coldisplayName.Tag = "displayName";
        coldisplayName.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        coldisplayName.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(coldisplayName);
        colcompanyRef.Name = "colcompanyRef";
        colcompanyRef.HeaderText = "الشركة";
        colcompanyRef.Tag = "companyRef";
        colcompanyRef.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
        colcompanyRef.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colcompanyRef);
        colbranchRef.Name = "colbranchRef";
        colbranchRef.HeaderText = "الفرع/النطاق";
        colbranchRef.Tag = "branchRef";
        colbranchRef.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
        colbranchRef.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colbranchRef);
        colcurrencyRef.Name = "colcurrencyRef";
        colcurrencyRef.HeaderText = "العملة";
        colcurrencyRef.Tag = "currencyRef";
        colcurrencyRef.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
        colcurrencyRef.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colcurrencyRef);
        colstatus.Name = "colstatus";
        colstatus.HeaderText = "الحالة";
        colstatus.Tag = "status";
        colstatus.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
        colstatus.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colstatus);
        collastModified.Name = "collastModified";
        collastModified.HeaderText = "آخر تعديل";
        collastModified.Tag = "lastModified";
        collastModified.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
        collastModified.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(collastModified);
        contentLayout.Controls.Add(dgvRecords, 0, 2);
        paging.Name = "paging";
        paging.Dock = DockStyle.Top;
        paging.AutoSize = true;
        paging.WrapContents = true;
        btnPrevious.Name = "btnPrevious";
        btnPrevious.Text = "السابق";
        btnPrevious.Size = new Size(70, 30);
        btnPrevious.Dock = DockStyle.None;
        btnPrevious.AutoSize = true;
        btnPrevious.Enabled = false;
        btnPrevious.AccessibleDescription = "غير مربوط بالخدمة؛ لا يتم تنفيذ أو حفظ بيانات.";
        paging.Controls.Add(btnPrevious);
        btnNext.Name = "btnNext";
        btnNext.Text = "التالي";
        btnNext.Size = new Size(70, 30);
        btnNext.Dock = DockStyle.None;
        btnNext.AutoSize = true;
        btnNext.Enabled = false;
        btnNext.AccessibleDescription = "غير مربوط بالخدمة؛ لا يتم تنفيذ أو حفظ بيانات.";
        paging.Controls.Add(btnNext);
        lblPage.Name = "lblPage";
        lblPage.Text = "الصفحات: — لم يتم تحميل بيانات";
        lblPage.AutoSize = true;
        paging.Controls.Add(lblPage);
        contentLayout.Controls.Add(paging, 0, 3);
        statusLayout.Name = "statusLayout";
        statusLayout.ColumnCount = 1;
        statusLayout.RowCount = 1;
        statusLayout.Dock = DockStyle.Top;
        statusLayout.Margin = Padding.Empty;
        statusLayout.AutoSize = true;
        statusLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        statusLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        statusLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        lblState.Name = "lblState";
        lblState.Text = "التعيين التقني والحفظ والمزودات غير مربوطة.";
        lblState.AutoSize = true;
        lblState.Dock = DockStyle.Fill;
        lblState.TextAlign = ContentAlignment.MiddleRight;
        statusLayout.Controls.Add(lblState, 0, 0);
        contentLayout.Controls.Add(statusLayout, 0, 4);
        lblState.Text = "حد السحب/التحويل اختياري؛ الفراغ يعني عدم التحديد، والقيمة غير سالبة. لا يوجد حفظ أو تنفيذ للحد.";
        tlpAuditInfo.Name = "tlpAuditInfo";
        tlpAuditInfo.ColumnCount = 2;
        tlpAuditInfo.RowCount = 2;
        tlpAuditInfo.Dock = DockStyle.Top;
        tlpAuditInfo.Margin = Padding.Empty;
        tlpAuditInfo.AutoSize = true;
        tlpAuditInfo.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        tlpAuditInfo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tlpAuditInfo.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        tlpAuditInfo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tlpAuditInfo.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        lblCreatedBy.Name = "lblCreatedBy";
        lblCreatedBy.Text = "أنشأ بواسطة: —";
        lblCreatedBy.AutoSize = true;
        lblCreatedBy.Dock = DockStyle.Fill;
        lblCreatedBy.TextAlign = ContentAlignment.MiddleRight;
        tlpAuditInfo.Controls.Add(lblCreatedBy, 0, 0);
        lblCreatedAt.Name = "lblCreatedAt";
        lblCreatedAt.Text = "تاريخ الإنشاء: —";
        lblCreatedAt.AutoSize = true;
        lblCreatedAt.Dock = DockStyle.Fill;
        lblCreatedAt.TextAlign = ContentAlignment.MiddleRight;
        tlpAuditInfo.Controls.Add(lblCreatedAt, 1, 0);
        lblModifiedBy.Name = "lblModifiedBy";
        lblModifiedBy.Text = "عدل بواسطة: —";
        lblModifiedBy.AutoSize = true;
        lblModifiedBy.Dock = DockStyle.Fill;
        lblModifiedBy.TextAlign = ContentAlignment.MiddleRight;
        tlpAuditInfo.Controls.Add(lblModifiedBy, 0, 1);
        lblModifiedAt.Name = "lblModifiedAt";
        lblModifiedAt.Text = "تاريخ التعديل: —";
        lblModifiedAt.AutoSize = true;
        lblModifiedAt.Dock = DockStyle.Fill;
        lblModifiedAt.TextAlign = ContentAlignment.MiddleRight;
        tlpAuditInfo.Controls.Add(lblModifiedAt, 1, 1);
        contentLayout.Controls.Add(tlpAuditInfo, 0, 5);
        this.Controls.Add(mainLayout);
        Name = "UcScreen_04_03_03";
        Text = "الحسابات البنكية";
        Tag = "04.03.03";
        Size = new Size(1100, 760);
        AutoScaleMode = AutoScaleMode.Dpi;
        AutoScaleDimensions = new SizeF(120F, 120F);
        RightToLeft = RightToLeft.Yes;
        Font = new Font("Segoe UI", 10F);
        pnlContent.SizeChanged += ContentSizeChanged;
        ((System.ComponentModel.ISupportInitialize)dgvRecords).EndInit();
        ResumeLayout(false);
        PerformLayout();
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.RightToLeft = RightToLeft.Yes;
        designerCommandBar.Controls.Add(pnlToolbar);
        pnlToolbar.Dock = DockStyle.Fill;
        pnlToolbar.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        pnlToolbar.Name = "pnlToolbar";
        pnlToolbar.Dock = DockStyle.Fill;
        pnlToolbar.AutoSize = false;
        pnlToolbar.WrapContents = false;
        pnlToolbar.FlowDirection = FlowDirection.RightToLeft;
        pnlToolbar.RightToLeft = RightToLeft.No;
        pnlToolbar.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 44;
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        btnNew.AutoSize = false;
        btnNew.Dock = DockStyle.None;
        btnNew.MinimumSize = Size.Empty;
        btnNew.Size = new Size(26, 24);
        btnNew.Margin = new Padding(1);
        btnNew.FlatStyle = FlatStyle.Flat;
        btnNew.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnNew.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        btnNew.Text = "";
        pnlToolbar.Controls.Add(btnNew);
        designerCommandBar.SetCommandRole(btnNew, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        btnEdit.AutoSize = false;
        btnEdit.Dock = DockStyle.None;
        btnEdit.MinimumSize = Size.Empty;
        btnEdit.Size = new Size(26, 24);
        btnEdit.Margin = new Padding(1);
        btnEdit.FlatStyle = FlatStyle.Flat;
        btnEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        btnEdit.Text = "";
        pnlToolbar.Controls.Add(btnEdit);
        designerCommandBar.SetCommandRole(btnEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        pnlToolbar.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.AutoSize = false;
        standardCommandCancel.Dock = DockStyle.None;
        standardCommandCancel.MinimumSize = Size.Empty;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandCancel.Text = "";
        pnlToolbar.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        btnView.AutoSize = false;
        btnView.Dock = DockStyle.None;
        btnView.MinimumSize = Size.Empty;
        btnView.Size = new Size(26, 24);
        btnView.Margin = new Padding(1);
        btnView.FlatStyle = FlatStyle.Flat;
        btnView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        btnView.Text = "";
        pnlToolbar.Controls.Add(btnView);
        designerCommandBar.SetCommandRole(btnView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        pnlToolbar.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        pnlToolbar.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        pnlToolbar.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        pnlToolbar.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        btnSave.AutoSize = false;
        btnSave.Dock = DockStyle.None;
        btnSave.MinimumSize = Size.Empty;
        btnSave.Size = new Size(26, 24);
        btnSave.Margin = new Padding(1);
        btnSave.FlatStyle = FlatStyle.Flat;
        btnSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        btnSave.Text = "";
        pnlToolbar.Controls.Add(btnSave);
        designerCommandBar.SetCommandRole(btnSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        pnlToolbar.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        btnClose.AutoSize = false;
        btnClose.Dock = DockStyle.None;
        btnClose.MinimumSize = Size.Empty;
        btnClose.Size = new Size(26, 24);
        btnClose.Margin = new Padding(1);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        btnClose.Text = "";
        designerCloseHost.Controls.Add(btnClose);
        btnClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        pnlToolbar.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        pnlToolbar.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        pnlToolbar.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        pnlToolbar.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        tlpAuditInfo.Visible = false;
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}
}
