using System.Drawing;
using System.Windows.Forms;
namespace TransportERP.EmptyForms;
partial class UcScreen_04_02_01
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCloseHost = new Panel();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandPrint = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        mainLayout = new TableLayoutPanel();
        pnlHeader = new TableLayoutPanel();
        lblTitle = new Label();
        pnlToolbar = new FlowLayoutPanel();
        btnView = new Button();
        btnNew = new Button();
        btnSave = new Button();
        btnEdit = new Button();
        btnDisable = new Button();
        btnMove = new Button();
        btnClose = new Button();
        lblDataStatus = new Label();
        pnlContent = new Panel();
        contentLayout = new TableLayoutPanel();
        fieldsLayout = new TableLayoutPanel();
        lblCompanyId = new Label();
        cmbCompanyId = new ComboBox();
        lblBranchId = new Label();
        cmbBranchId = new ComboBox();
        lblParentCostCenterId = new Label();
        cmbParentCostCenterId = new ComboBox();
        lblCode = new Label();
        txtCode = new TextBox();
        lblArabicName = new Label();
        txtArabicName = new TextBox();
        lblEnglishName = new Label();
        txtEnglishName = new TextBox();
        lblStatus = new Label();
        txtStatus = new TextBox();
        searchLayout = new TableLayoutPanel();
        lblFilterSearchText = new Label();
        txtFilterSearchText = new TextBox();
        lblFilterStatus = new Label();
        cmbFilterStatus = new ComboBox();
        lblFilterCompanyId = new Label();
        cmbFilterCompanyId = new ComboBox();
        lblFilterBranchId = new Label();
        cmbFilterBranchId = new ComboBox();
        lblFilterParentCostCenterId = new Label();
        cmbFilterParentCostCenterId = new ComboBox();
        treeLayout = new TableLayoutPanel();
        tvCostCenters = new TreeView();
        dgvRecords = new DataGridView();
        colCode = new DataGridViewTextBoxColumn();
        colArabicName = new DataGridViewTextBoxColumn();
        colEnglishName = new DataGridViewTextBoxColumn();
        colBranch = new DataGridViewTextBoxColumn();
        colStatus = new DataGridViewTextBoxColumn();
        txtVersion = new TextBox();
        paging = new FlowLayoutPanel();
        btnSearch = new Button();
        btnPrevious = new Button();
        btnNext = new Button();
        lblPage = new Label();
        tlpAuditInfo = new TableLayoutPanel();
        lblCreatedBy = new Label();
        lblCreatedAt = new Label();
        lblModifiedBy = new Label();
        lblModifiedAt = new Label();
        SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)dgvRecords).BeginInit();
        mainLayout.Name = "mainLayout";
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 3;
        mainLayout.Dock = DockStyle.Top;
        mainLayout.AutoSize = true;
        mainLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        mainLayout.Margin = Padding.Empty;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.AutoSize = false;
        pnlHeader.Name = "pnlHeader";
        pnlHeader.ColumnCount = 1;
        pnlHeader.RowCount = 2;
        pnlHeader.Dock = DockStyle.Top;
        pnlHeader.AutoSize = true;
        pnlHeader.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlHeader.Margin = Padding.Empty;
        pnlHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "مراكز التكلفة";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        pnlHeader.Controls.Add(lblTitle, 0, 0);
        lblTitle.Font = new Font("Segoe UI", 16F);
        lblTitle.BackColor = Color.FromArgb(192, 192, 255);
        pnlToolbar.Name = "pnlToolbar";
        pnlToolbar.Dock = DockStyle.Top;
        pnlToolbar.AutoSize = true;
        pnlToolbar.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlToolbar.WrapContents = true;
        pnlToolbar.FlowDirection = FlowDirection.LeftToRight;
        pnlToolbar.RightToLeft = RightToLeft.Yes;
        btnView.Name = "btnView";
        btnView.Text = "عرض";
        btnView.AutoSize = true;
        btnView.MinimumSize = new Size(70, 30);
        btnView.Margin = new Padding(4);
        btnView.Enabled = false;

        btnNew.Name = "btnNew";
        btnNew.Text = "جديد";
        btnNew.AutoSize = true;
        btnNew.MinimumSize = new Size(70, 30);
        btnNew.Margin = new Padding(4);
        btnNew.Enabled = false;

        btnSave.Name = "btnSave";
        btnSave.Text = "حفظ";
        btnSave.AutoSize = true;
        btnSave.MinimumSize = new Size(70, 30);
        btnSave.Margin = new Padding(4);
        btnSave.Enabled = false;

        btnEdit.Name = "btnEdit";
        btnEdit.Text = "تعديل";
        btnEdit.AutoSize = true;
        btnEdit.MinimumSize = new Size(70, 30);
        btnEdit.Margin = new Padding(4);
        btnEdit.Enabled = false;

        btnDisable.Name = "btnDisable";
        btnDisable.Text = "إيقاف";
        btnDisable.AutoSize = true;
        btnDisable.MinimumSize = new Size(70, 30);
        btnDisable.Margin = new Padding(4);
        btnDisable.Enabled = false;
        pnlToolbar.Controls.Add(btnDisable);
        btnMove.Name = "btnMove";
        btnMove.Text = "نقل";
        btnMove.AutoSize = true;
        btnMove.MinimumSize = new Size(70, 30);
        btnMove.Margin = new Padding(4);
        btnMove.Enabled = false;
        pnlToolbar.Controls.Add(btnMove);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.AutoSize = true;
        btnClose.MinimumSize = new Size(70, 30);
        btnClose.Margin = new Padding(4);
        btnClose.Enabled = true;

        btnClose.Click += BtnClose_Click;
        pnlHeader.Controls.Add(designerCommandBar, 0, 1);
        mainLayout.Controls.Add(pnlHeader, 0, 0);
        lblDataStatus.Name = "lblDataStatus";
        lblDataStatus.Text = "وضع المعاينة — الحفظ وتحميل البيانات غير متاحين";
        lblDataStatus.AutoSize = true;
        lblDataStatus.Dock = DockStyle.Fill;
        mainLayout.Controls.Add(lblDataStatus, 0, 1);
        pnlContent.Name = "pnlContent";
        pnlContent.Dock = DockStyle.Fill;
        pnlContent.AutoScroll = true;
        mainLayout.Controls.Add(pnlContent, 0, 2);
        contentLayout.Name = "contentLayout";
        contentLayout.ColumnCount = 1;
        contentLayout.RowCount = 5;
        contentLayout.Dock = DockStyle.None;
        contentLayout.AutoSize = false;
        contentLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        contentLayout.Margin = Padding.Empty;
        contentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        contentLayout.MinimumSize = new Size(720, 0);
        pnlContent.Controls.Add(contentLayout);
        fieldsLayout.Name = "fieldsLayout";
        fieldsLayout.ColumnCount = 4;
        fieldsLayout.RowCount = 4;
        fieldsLayout.Dock = DockStyle.Top;
        fieldsLayout.AutoSize = true;
        fieldsLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        fieldsLayout.Margin = Padding.Empty;
        fieldsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        fieldsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        fieldsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        fieldsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        fieldsLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        fieldsLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        fieldsLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        fieldsLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        fieldsLayout.Padding = new Padding(4);
        lblCompanyId.Name = "lblCompanyId";
        lblCompanyId.Text = "الشركة *";
        lblCompanyId.AutoSize = true;
        lblCompanyId.Dock = DockStyle.Fill;
        fieldsLayout.Controls.Add(lblCompanyId, 0, 0);
        lblCompanyId.TextAlign = ContentAlignment.MiddleRight;
        lblCompanyId.MinimumSize = new Size(0, 36);
        cmbCompanyId.Name = "cmbCompanyId";
        cmbCompanyId.Dock = DockStyle.Fill;
        cmbCompanyId.Margin = new Padding(3);
        cmbCompanyId.TabIndex = 0;
        cmbCompanyId.AccessibleName = "الشركة";
        cmbCompanyId.Tag = "CompanyId";
        cmbCompanyId.BackColor = Color.FromArgb(255, 249, 219);
        cmbCompanyId.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldsLayout.Controls.Add(cmbCompanyId, 1, 0);
        lblBranchId.Name = "lblBranchId";
        lblBranchId.Text = "الفرع";
        lblBranchId.AutoSize = true;
        lblBranchId.Dock = DockStyle.Fill;
        fieldsLayout.Controls.Add(lblBranchId, 2, 0);
        lblBranchId.TextAlign = ContentAlignment.MiddleRight;
        lblBranchId.MinimumSize = new Size(0, 36);
        cmbBranchId.Name = "cmbBranchId";
        cmbBranchId.Dock = DockStyle.Fill;
        cmbBranchId.Margin = new Padding(3);
        cmbBranchId.TabIndex = 1;
        cmbBranchId.AccessibleName = "الفرع";
        cmbBranchId.Tag = "BranchId";
        cmbBranchId.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldsLayout.Controls.Add(cmbBranchId, 3, 0);
        lblParentCostCenterId.Name = "lblParentCostCenterId";
        lblParentCostCenterId.Text = "مركز التكلفة الأب";
        lblParentCostCenterId.AutoSize = true;
        lblParentCostCenterId.Dock = DockStyle.Fill;
        fieldsLayout.Controls.Add(lblParentCostCenterId, 0, 1);
        lblParentCostCenterId.TextAlign = ContentAlignment.MiddleRight;
        lblParentCostCenterId.MinimumSize = new Size(0, 36);
        cmbParentCostCenterId.Name = "cmbParentCostCenterId";
        cmbParentCostCenterId.Dock = DockStyle.Fill;
        cmbParentCostCenterId.Margin = new Padding(3);
        cmbParentCostCenterId.TabIndex = 2;
        cmbParentCostCenterId.AccessibleName = "مركز التكلفة الأب";
        cmbParentCostCenterId.Tag = "ParentCostCenterId";
        cmbParentCostCenterId.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldsLayout.Controls.Add(cmbParentCostCenterId, 1, 1);
        lblCode.Name = "lblCode";
        lblCode.Text = "الرمز *";
        lblCode.AutoSize = true;
        lblCode.Dock = DockStyle.Fill;
        fieldsLayout.Controls.Add(lblCode, 2, 1);
        lblCode.TextAlign = ContentAlignment.MiddleRight;
        lblCode.MinimumSize = new Size(0, 36);
        txtCode.Name = "txtCode";
        txtCode.Dock = DockStyle.Fill;
        txtCode.Margin = new Padding(3);
        txtCode.TabIndex = 3;
        txtCode.AccessibleName = "الرمز";
        txtCode.Tag = "Code";
        txtCode.BackColor = Color.FromArgb(255, 249, 219);
        txtCode.RightToLeft = RightToLeft.No;
        fieldsLayout.Controls.Add(txtCode, 3, 1);
        lblArabicName.Name = "lblArabicName";
        lblArabicName.Text = "الاسم العربي *";
        lblArabicName.AutoSize = true;
        lblArabicName.Dock = DockStyle.Fill;
        fieldsLayout.Controls.Add(lblArabicName, 0, 2);
        lblArabicName.TextAlign = ContentAlignment.MiddleRight;
        lblArabicName.MinimumSize = new Size(0, 36);
        txtArabicName.Name = "txtArabicName";
        txtArabicName.Dock = DockStyle.Fill;
        txtArabicName.Margin = new Padding(3);
        txtArabicName.TabIndex = 4;
        txtArabicName.AccessibleName = "الاسم العربي";
        txtArabicName.Tag = "ArabicName";
        txtArabicName.BackColor = Color.FromArgb(255, 249, 219);
        fieldsLayout.Controls.Add(txtArabicName, 1, 2);
        lblEnglishName.Name = "lblEnglishName";
        lblEnglishName.Text = "الاسم الإنجليزي";
        lblEnglishName.AutoSize = true;
        lblEnglishName.Dock = DockStyle.Fill;
        fieldsLayout.Controls.Add(lblEnglishName, 2, 2);
        lblEnglishName.TextAlign = ContentAlignment.MiddleRight;
        lblEnglishName.MinimumSize = new Size(0, 36);
        txtEnglishName.Name = "txtEnglishName";
        txtEnglishName.Dock = DockStyle.Fill;
        txtEnglishName.Margin = new Padding(3);
        txtEnglishName.TabIndex = 5;
        txtEnglishName.AccessibleName = "الاسم الإنجليزي";
        txtEnglishName.Tag = "EnglishName";
        txtEnglishName.RightToLeft = RightToLeft.No;
        fieldsLayout.Controls.Add(txtEnglishName, 3, 2);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "الحالة";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        fieldsLayout.Controls.Add(lblStatus, 0, 3);
        lblStatus.TextAlign = ContentAlignment.MiddleRight;
        lblStatus.MinimumSize = new Size(0, 36);
        txtStatus.Name = "txtStatus";
        txtStatus.Dock = DockStyle.Fill;
        txtStatus.Margin = new Padding(3);
        txtStatus.TabIndex = 6;
        txtStatus.AccessibleName = "الحالة";
        txtStatus.Tag = "Status";
        txtStatus.ReadOnly = true;
        fieldsLayout.Controls.Add(txtStatus, 1, 3);
        contentLayout.Controls.Add(fieldsLayout, 0, 0);
        cmbCompanyId.AccessibleDescription = "اختيار عند الإنشاء فقط؛ لا يتغير في التعديل. لا يوجد مزود بيانات متصل.";
        cmbParentCostCenterId.AccessibleDescription = "اختيار عند الإنشاء فقط؛ لا يتغير في التعديل. لا يوجد مزود بيانات متصل.";
        cmbParentCostCenterId.AccessibleDescription = "الاختيار الأولي عند الإنشاء فقط؛ الأصل الفارغ جذر. تغيير الأصل لاحقاً بواسطة نقل فقط.";
        searchLayout.Name = "searchLayout";
        searchLayout.ColumnCount = 4;
        searchLayout.RowCount = 3;
        searchLayout.Dock = DockStyle.Top;
        searchLayout.AutoSize = true;
        searchLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        searchLayout.Margin = Padding.Empty;
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        searchLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        searchLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        searchLayout.Padding = new Padding(4);
        lblFilterSearchText.Name = "lblFilterSearchText";
        lblFilterSearchText.Text = "نص البحث";
        lblFilterSearchText.AutoSize = true;
        lblFilterSearchText.Dock = DockStyle.Fill;
        searchLayout.Controls.Add(lblFilterSearchText, 0, 0);
        lblFilterSearchText.TextAlign = ContentAlignment.MiddleRight;
        lblFilterSearchText.MinimumSize = new Size(0, 36);
        txtFilterSearchText.Name = "txtFilterSearchText";
        txtFilterSearchText.Dock = DockStyle.Fill;
        txtFilterSearchText.Margin = new Padding(3);
        txtFilterSearchText.TabIndex = 0;
        txtFilterSearchText.AccessibleName = "نص البحث";
        txtFilterSearchText.Tag = "FilterSearchText";
        searchLayout.Controls.Add(txtFilterSearchText, 1, 0);
        lblFilterStatus.Name = "lblFilterStatus";
        lblFilterStatus.Text = "الحالة";
        lblFilterStatus.AutoSize = true;
        lblFilterStatus.Dock = DockStyle.Fill;
        searchLayout.Controls.Add(lblFilterStatus, 2, 0);
        lblFilterStatus.TextAlign = ContentAlignment.MiddleRight;
        lblFilterStatus.MinimumSize = new Size(0, 36);
        cmbFilterStatus.Name = "cmbFilterStatus";
        cmbFilterStatus.Dock = DockStyle.Fill;
        cmbFilterStatus.Margin = new Padding(3);
        cmbFilterStatus.TabIndex = 1;
        cmbFilterStatus.AccessibleName = "الحالة";
        cmbFilterStatus.Tag = "FilterStatus";
        cmbFilterStatus.DropDownStyle = ComboBoxStyle.DropDownList;
        searchLayout.Controls.Add(cmbFilterStatus, 3, 0);
        lblFilterCompanyId.Name = "lblFilterCompanyId";
        lblFilterCompanyId.Text = "الشركة";
        lblFilterCompanyId.AutoSize = true;
        lblFilterCompanyId.Dock = DockStyle.Fill;
        searchLayout.Controls.Add(lblFilterCompanyId, 0, 1);
        lblFilterCompanyId.TextAlign = ContentAlignment.MiddleRight;
        lblFilterCompanyId.MinimumSize = new Size(0, 36);
        cmbFilterCompanyId.Name = "cmbFilterCompanyId";
        cmbFilterCompanyId.Dock = DockStyle.Fill;
        cmbFilterCompanyId.Margin = new Padding(3);
        cmbFilterCompanyId.TabIndex = 2;
        cmbFilterCompanyId.AccessibleName = "الشركة";
        cmbFilterCompanyId.Tag = "FilterCompanyId";
        cmbFilterCompanyId.DropDownStyle = ComboBoxStyle.DropDownList;
        searchLayout.Controls.Add(cmbFilterCompanyId, 1, 1);
        lblFilterBranchId.Name = "lblFilterBranchId";
        lblFilterBranchId.Text = "الفرع";
        lblFilterBranchId.AutoSize = true;
        lblFilterBranchId.Dock = DockStyle.Fill;
        searchLayout.Controls.Add(lblFilterBranchId, 2, 1);
        lblFilterBranchId.TextAlign = ContentAlignment.MiddleRight;
        lblFilterBranchId.MinimumSize = new Size(0, 36);
        cmbFilterBranchId.Name = "cmbFilterBranchId";
        cmbFilterBranchId.Dock = DockStyle.Fill;
        cmbFilterBranchId.Margin = new Padding(3);
        cmbFilterBranchId.TabIndex = 3;
        cmbFilterBranchId.AccessibleName = "الفرع";
        cmbFilterBranchId.Tag = "FilterBranchId";
        cmbFilterBranchId.DropDownStyle = ComboBoxStyle.DropDownList;
        searchLayout.Controls.Add(cmbFilterBranchId, 3, 1);
        lblFilterParentCostCenterId.Name = "lblFilterParentCostCenterId";
        lblFilterParentCostCenterId.Text = "مركز التكلفة الأب";
        lblFilterParentCostCenterId.AutoSize = true;
        lblFilterParentCostCenterId.Dock = DockStyle.Fill;
        searchLayout.Controls.Add(lblFilterParentCostCenterId, 0, 2);
        lblFilterParentCostCenterId.TextAlign = ContentAlignment.MiddleRight;
        lblFilterParentCostCenterId.MinimumSize = new Size(0, 36);
        cmbFilterParentCostCenterId.Name = "cmbFilterParentCostCenterId";
        cmbFilterParentCostCenterId.Dock = DockStyle.Fill;
        cmbFilterParentCostCenterId.Margin = new Padding(3);
        cmbFilterParentCostCenterId.TabIndex = 4;
        cmbFilterParentCostCenterId.AccessibleName = "مركز التكلفة الأب";
        cmbFilterParentCostCenterId.Tag = "FilterParentCostCenterId";
        cmbFilterParentCostCenterId.DropDownStyle = ComboBoxStyle.DropDownList;
        searchLayout.Controls.Add(cmbFilterParentCostCenterId, 1, 2);
        contentLayout.Controls.Add(searchLayout, 0, 1);
        treeLayout.Name = "treeLayout";
        treeLayout.ColumnCount = 2;
        treeLayout.RowCount = 1;
        treeLayout.Dock = DockStyle.Top;
        treeLayout.AutoSize = true;
        treeLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        treeLayout.Margin = Padding.Empty;
        treeLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 30F));
        treeLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 70F));
        treeLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        treeLayout.Dock = DockStyle.Fill;
        treeLayout.MinimumSize = new Size(0, 300);
        treeLayout.AutoSize = false;
        contentLayout.Controls.Add(treeLayout, 0, 2);
        tvCostCenters.Name = "tvCostCenters";
        tvCostCenters.Dock = DockStyle.Fill;
        tvCostCenters.HideSelection = false;
        tvCostCenters.AccessibleDescription = "معاينة بلا عقد؛ تحميل الأبناء الكسول وتصفح الخادم غير مربوطين.";
        treeLayout.Controls.Add(tvCostCenters, 0, 0);
        dgvRecords.Name = "dgvRecords";
        dgvRecords.Dock = DockStyle.Fill;
        dgvRecords.ReadOnly = true;
        dgvRecords.AutoGenerateColumns = false;
        dgvRecords.AllowUserToAddRows = false;
        dgvRecords.AllowUserToDeleteRows = false;
        dgvRecords.MultiSelect = false;
        dgvRecords.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvRecords.RowHeadersVisible = false;
        treeLayout.Controls.Add(dgvRecords, 1, 0);
        colCode.Name = "colCode";
        colCode.HeaderText = "الرمز";
        colCode.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colCode.FillWeight = 100F;
        colCode.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colCode);
        colArabicName.Name = "colArabicName";
        colArabicName.HeaderText = "الاسم العربي";
        colArabicName.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colArabicName.FillWeight = 180F;
        colArabicName.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colArabicName);
        colEnglishName.Name = "colEnglishName";
        colEnglishName.HeaderText = "الاسم الإنجليزي";
        colEnglishName.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colEnglishName.FillWeight = 100F;
        colEnglishName.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colEnglishName);
        colBranch.Name = "colBranch";
        colBranch.HeaderText = "الفرع";
        colBranch.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colBranch.FillWeight = 100F;
        colBranch.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colBranch);
        colStatus.Name = "colStatus";
        colStatus.HeaderText = "الحالة";
        colStatus.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colStatus.FillWeight = 100F;
        colStatus.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colStatus);
        txtVersion.Name = "txtVersion";
        txtVersion.Visible = false;
        txtVersion.ReadOnly = true;
        txtVersion.TabStop = false;
        pnlContent.Controls.Add(txtVersion);
        paging.Name = "paging";
        paging.Dock = DockStyle.Top;
        paging.AutoSize = true;
        paging.WrapContents = true;
        btnSearch.Name = "btnSearch";
        btnSearch.Text = "بحث";
        btnSearch.AutoSize = true;
        btnSearch.MinimumSize = new Size(70, 30);
        btnSearch.Margin = new Padding(4);
        btnSearch.Enabled = false;
        paging.Controls.Add(btnSearch);
        btnPrevious.Name = "btnPrevious";
        btnPrevious.Text = "السابق";
        btnPrevious.AutoSize = true;
        btnPrevious.MinimumSize = new Size(70, 30);
        btnPrevious.Margin = new Padding(4);
        btnPrevious.Enabled = false;
        paging.Controls.Add(btnPrevious);
        btnNext.Name = "btnNext";
        btnNext.Text = "التالي";
        btnNext.AutoSize = true;
        btnNext.MinimumSize = new Size(70, 30);
        btnNext.Margin = new Padding(4);
        btnNext.Enabled = false;
        paging.Controls.Add(btnNext);
        lblPage.Name = "lblPage";
        lblPage.Text = "الصفحات: —";
        lblPage.AutoSize = true;
        lblPage.Dock = DockStyle.Fill;
        paging.Controls.Add(lblPage);
        contentLayout.Controls.Add(paging, 0, 3);
        tlpAuditInfo.Name = "tlpAuditInfo";
        tlpAuditInfo.ColumnCount = 2;
        tlpAuditInfo.RowCount = 2;
        tlpAuditInfo.Dock = DockStyle.Top;
        tlpAuditInfo.AutoSize = true;
        tlpAuditInfo.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        tlpAuditInfo.Margin = Padding.Empty;
        tlpAuditInfo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tlpAuditInfo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tlpAuditInfo.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        tlpAuditInfo.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        lblCreatedBy.Name = "lblCreatedBy";
        lblCreatedBy.Text = "أنشأ بواسطة: —";
        lblCreatedBy.AutoSize = true;
        lblCreatedBy.Dock = DockStyle.Fill;
        tlpAuditInfo.Controls.Add(lblCreatedBy, 0, 0);
        lblCreatedAt.Name = "lblCreatedAt";
        lblCreatedAt.Text = "تاريخ الإنشاء: —";
        lblCreatedAt.AutoSize = true;
        lblCreatedAt.Dock = DockStyle.Fill;
        tlpAuditInfo.Controls.Add(lblCreatedAt, 1, 0);
        lblModifiedBy.Name = "lblModifiedBy";
        lblModifiedBy.Text = "عدل بواسطة: —";
        lblModifiedBy.AutoSize = true;
        lblModifiedBy.Dock = DockStyle.Fill;
        tlpAuditInfo.Controls.Add(lblModifiedBy, 0, 1);
        lblModifiedAt.Name = "lblModifiedAt";
        lblModifiedAt.Text = "تاريخ التعديل: —";
        lblModifiedAt.AutoSize = true;
        lblModifiedAt.Dock = DockStyle.Fill;
        tlpAuditInfo.Controls.Add(lblModifiedAt, 1, 1);
        contentLayout.Controls.Add(tlpAuditInfo, 0, 4);
        pnlContent.SizeChanged += ContentSizeChanged;
        Controls.Add(mainLayout);
        Name = "UcScreen_04_02_01";
        Text = "مراكز التكلفة";
        Tag = "04.02.01";
        AutoScaleDimensions = new SizeF(120F, 120F);
        AutoScaleMode = AutoScaleMode.Dpi;
        RightToLeft = RightToLeft.Yes;
        Font = new Font("Segoe UI", 10F);
        Size = new Size(1100, 760);
        ((System.ComponentModel.ISupportInitialize)dgvRecords).EndInit();
        ResumeLayout(false);
        PerformLayout();
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.RightToLeft = RightToLeft.Yes;
        designerCommandBar.Controls.Add(pnlToolbar);
        pnlToolbar.Dock = DockStyle.Fill;
        pnlToolbar.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        pnlToolbar.Name = "pnlToolbar";
        pnlToolbar.Dock = DockStyle.Fill;
        pnlToolbar.AutoSize = false;
        pnlToolbar.WrapContents = false;
        pnlToolbar.FlowDirection = FlowDirection.RightToLeft;
        pnlToolbar.RightToLeft = RightToLeft.No;
        pnlToolbar.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 44;
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        btnNew.AutoSize = false;
        btnNew.Dock = DockStyle.None;
        btnNew.MinimumSize = Size.Empty;
        btnNew.Size = new Size(26, 24);
        btnNew.Margin = new Padding(1);
        btnNew.FlatStyle = FlatStyle.Flat;
        btnNew.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnNew.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        btnNew.Text = "";
        pnlToolbar.Controls.Add(btnNew);
        designerCommandBar.SetCommandRole(btnNew, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        btnEdit.AutoSize = false;
        btnEdit.Dock = DockStyle.None;
        btnEdit.MinimumSize = Size.Empty;
        btnEdit.Size = new Size(26, 24);
        btnEdit.Margin = new Padding(1);
        btnEdit.FlatStyle = FlatStyle.Flat;
        btnEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        btnEdit.Text = "";
        pnlToolbar.Controls.Add(btnEdit);
        designerCommandBar.SetCommandRole(btnEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        pnlToolbar.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.AutoSize = false;
        standardCommandCancel.Dock = DockStyle.None;
        standardCommandCancel.MinimumSize = Size.Empty;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandCancel.Text = "";
        pnlToolbar.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        btnView.AutoSize = false;
        btnView.Dock = DockStyle.None;
        btnView.MinimumSize = Size.Empty;
        btnView.Size = new Size(26, 24);
        btnView.Margin = new Padding(1);
        btnView.FlatStyle = FlatStyle.Flat;
        btnView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        btnView.Text = "";
        pnlToolbar.Controls.Add(btnView);
        designerCommandBar.SetCommandRole(btnView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        pnlToolbar.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        pnlToolbar.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        pnlToolbar.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        pnlToolbar.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        btnSave.AutoSize = false;
        btnSave.Dock = DockStyle.None;
        btnSave.MinimumSize = Size.Empty;
        btnSave.Size = new Size(26, 24);
        btnSave.Margin = new Padding(1);
        btnSave.FlatStyle = FlatStyle.Flat;
        btnSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        btnSave.Text = "";
        pnlToolbar.Controls.Add(btnSave);
        designerCommandBar.SetCommandRole(btnSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        pnlToolbar.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        btnClose.AutoSize = false;
        btnClose.Dock = DockStyle.None;
        btnClose.MinimumSize = Size.Empty;
        btnClose.Size = new Size(26, 24);
        btnClose.Margin = new Padding(1);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        btnClose.Text = "";
        designerCloseHost.Controls.Add(btnClose);
        btnClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        pnlToolbar.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        pnlToolbar.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        pnlToolbar.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        pnlToolbar.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        tlpAuditInfo.Visible = false;
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}
    private TableLayoutPanel mainLayout = null!;
    private TableLayoutPanel pnlHeader = null!;
    private Label lblTitle = null!;
    private FlowLayoutPanel pnlToolbar = null!;
    private Button btnView = null!;
    private Button btnNew = null!;
    private Button btnSave = null!;
    private Button btnEdit = null!;
    private Button btnDisable = null!;
    private Button btnMove = null!;
    private Button btnClose = null!;
    private Label lblDataStatus = null!;
    private Panel pnlContent = null!;
    private TableLayoutPanel contentLayout = null!;
    private TableLayoutPanel fieldsLayout = null!;
    private Label lblCompanyId = null!;
    private ComboBox cmbCompanyId = null!;
    private Label lblBranchId = null!;
    private ComboBox cmbBranchId = null!;
    private Label lblParentCostCenterId = null!;
    private ComboBox cmbParentCostCenterId = null!;
    private Label lblCode = null!;
    private TextBox txtCode = null!;
    private Label lblArabicName = null!;
    private TextBox txtArabicName = null!;
    private Label lblEnglishName = null!;
    private TextBox txtEnglishName = null!;
    private Label lblStatus = null!;
    private TextBox txtStatus = null!;
    private TableLayoutPanel searchLayout = null!;
    private Label lblFilterSearchText = null!;
    private TextBox txtFilterSearchText = null!;
    private Label lblFilterStatus = null!;
    private ComboBox cmbFilterStatus = null!;
    private Label lblFilterCompanyId = null!;
    private ComboBox cmbFilterCompanyId = null!;
    private Label lblFilterBranchId = null!;
    private ComboBox cmbFilterBranchId = null!;
    private Label lblFilterParentCostCenterId = null!;
    private ComboBox cmbFilterParentCostCenterId = null!;
    private TableLayoutPanel treeLayout = null!;
    private TreeView tvCostCenters = null!;
    private DataGridView dgvRecords = null!;
    private DataGridViewTextBoxColumn colCode = null!;
    private DataGridViewTextBoxColumn colArabicName = null!;
    private DataGridViewTextBoxColumn colEnglishName = null!;
    private DataGridViewTextBoxColumn colBranch = null!;
    private DataGridViewTextBoxColumn colStatus = null!;
    private TextBox txtVersion = null!;
    private FlowLayoutPanel paging = null!;
    private Button btnSearch = null!;
    private Button btnPrevious = null!;
    private Button btnNext = null!;
    private Label lblPage = null!;
    private TableLayoutPanel tlpAuditInfo = null!;
    private Label lblCreatedBy = null!;
    private Label lblCreatedAt = null!;
    private Label lblModifiedBy = null!;
    private Label lblModifiedAt = null!;
}
