namespace TransportERP.EmptyForms;
partial class UcScreen_04_11_01
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandSave = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel mainLayout = null!;
    private TableLayoutPanel pnlHeader = null!;
    private Label lblTitle = null!;
    private FlowLayoutPanel pnlToolbar = null!;
    private Button btnView = null!;
    private Button btnExecute = null!;
    private Button btnApprove = null!;
    private Button btnReject = null!;
    private Button btnReturn = null!;
    private Button btnReopen = null!;
    private Button btnClose = null!;
    private Label lblDataStatus = null!;
    private Panel pnlContent = null!;
    private TableLayoutPanel contentLayout = null!;
    private TableLayoutPanel detailsLayout = null!;
    private TextBox hiddenVersion = null!;
    private TableLayoutPanel searchLayout = null!;
    private Label filterLabelFiscalYearId = null!;
    private ComboBox filterFiscalYearId = null!;
    private Label filterLabelStatus = null!;
    private ComboBox filterStatus = null!;
    private Label filterLabelDateFrom = null!;
    private DateTimePicker filterDateFrom = null!;
    private Label filterLabelDateTo = null!;
    private DateTimePicker filterDateTo = null!;
    private Label filterLabelAction = null!;
    private ComboBox filterAction = null!;
    private Label filterLabelAuthorizedScope = null!;
    private TextBox filterAuthorizedScope = null!;
    private Button btnSearch = null!;
    private DataGridView dgvRecords = null!;
    private DataGridViewTextBoxColumn colFiscalYear = null!;
    private DataGridViewTextBoxColumn colPeriodNo = null!;
    private DataGridViewTextBoxColumn colStartDate = null!;
    private DataGridViewTextBoxColumn colEndDate = null!;
    private DataGridViewTextBoxColumn colStatus = null!;
    private FlowLayoutPanel paging = null!;
    private Button btnPrevious = null!;
    private Button btnNext = null!;
    private Label lblPage = null!;
    private TableLayoutPanel statusLayout = null!;
    private RichTextBox lblState = null!;
    private Label lblReason = null!;
    private TextBox txtReason = null!;
    private TableLayoutPanel tlpAuditInfo = null!;
    private Label lblCreatedBy = null!;
    private Label lblCreatedAt = null!;
    private Label lblModifiedBy = null!;
    private Label lblModifiedAt = null!;
    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandSave = new Button();
        standardCommandPrint = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        mainLayout = new TableLayoutPanel();
        pnlHeader = new TableLayoutPanel();
        lblTitle = new Label();
        pnlToolbar = new FlowLayoutPanel();
        btnView = new Button();
        btnExecute = new Button();
        btnApprove = new Button();
        btnReject = new Button();
        btnReturn = new Button();
        btnReopen = new Button();
        btnClose = new Button();
        lblDataStatus = new Label();
        pnlContent = new Panel();
        contentLayout = new TableLayoutPanel();
        detailsLayout = new TableLayoutPanel();
        hiddenVersion = new TextBox();
        searchLayout = new TableLayoutPanel();
        filterLabelFiscalYearId = new Label();
        filterFiscalYearId = new ComboBox();
        filterLabelStatus = new Label();
        filterStatus = new ComboBox();
        filterLabelDateFrom = new Label();
        filterDateFrom = new DateTimePicker();
        filterLabelDateTo = new Label();
        filterDateTo = new DateTimePicker();
        filterLabelAction = new Label();
        filterAction = new ComboBox();
        filterLabelAuthorizedScope = new Label();
        filterAuthorizedScope = new TextBox();
        btnSearch = new Button();
        dgvRecords = new DataGridView();
        colFiscalYear = new DataGridViewTextBoxColumn();
        colPeriodNo = new DataGridViewTextBoxColumn();
        colStartDate = new DataGridViewTextBoxColumn();
        colEndDate = new DataGridViewTextBoxColumn();
        colStatus = new DataGridViewTextBoxColumn();
        paging = new FlowLayoutPanel();
        btnPrevious = new Button();
        btnNext = new Button();
        lblPage = new Label();
        statusLayout = new TableLayoutPanel();
        lblState = new RichTextBox();
        lblReason = new Label();
        txtReason = new TextBox();
        tlpAuditInfo = new TableLayoutPanel();
        lblCreatedBy = new Label();
        lblCreatedAt = new Label();
        lblModifiedBy = new Label();
        lblModifiedAt = new Label();
        SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)dgvRecords).BeginInit();
        mainLayout.Name = "mainLayout";
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 3;
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = Padding.Empty;
        mainLayout.AutoSize = false;
        mainLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlHeader.Name = "pnlHeader";
        pnlHeader.ColumnCount = 1;
        pnlHeader.RowCount = 2;
        pnlHeader.Dock = DockStyle.Top;
        pnlHeader.Margin = Padding.Empty;
        pnlHeader.AutoSize = true;
        pnlHeader.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "الفترات المحاسبية";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleRight;
        pnlHeader.Controls.Add(lblTitle, 0, 0);
        lblTitle.Font = new Font("Segoe UI", 16F);
        pnlToolbar.Name = "pnlToolbar";
        pnlToolbar.Dock = DockStyle.Top;
        pnlToolbar.AutoSize = true;
        pnlToolbar.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlToolbar.FlowDirection = FlowDirection.LeftToRight;
        pnlToolbar.RightToLeft = RightToLeft.Yes;
        pnlToolbar.WrapContents = true;
        btnView.Name = "btnView";
        btnView.Text = "عرض";
        btnView.Size = new Size(70, 30);
        btnView.Dock = DockStyle.None;
        btnView.AutoSize = true;
        btnView.Enabled = false;
        btnView.AccessibleDescription = "غير مربوط بالخدمة؛ لا يتم تنفيذ أو حفظ بيانات.";

        btnExecute.Name = "btnExecute";
        btnExecute.Text = "طلب إجراء محمي";
        btnExecute.Size = new Size(70, 30);
        btnExecute.Dock = DockStyle.None;
        btnExecute.AutoSize = true;
        btnExecute.Enabled = false;
        btnExecute.AccessibleDescription = "غير مربوط بالخدمة؛ لا يتم تنفيذ أو حفظ بيانات.";
        pnlToolbar.Controls.Add(btnExecute);
        btnApprove.Name = "btnApprove";
        btnApprove.Text = "اعتماد";
        btnApprove.Size = new Size(70, 30);
        btnApprove.Dock = DockStyle.None;
        btnApprove.AutoSize = true;
        btnApprove.Enabled = false;
        btnApprove.AccessibleDescription = "غير مربوط بالخدمة؛ لا يتم تنفيذ أو حفظ بيانات.";
        pnlToolbar.Controls.Add(btnApprove);
        btnReject.Name = "btnReject";
        btnReject.Text = "رفض";
        btnReject.Size = new Size(70, 30);
        btnReject.Dock = DockStyle.None;
        btnReject.AutoSize = true;
        btnReject.Enabled = false;
        btnReject.AccessibleDescription = "غير مربوط بالخدمة؛ لا يتم تنفيذ أو حفظ بيانات.";
        pnlToolbar.Controls.Add(btnReject);
        btnReturn.Name = "btnReturn";
        btnReturn.Text = "إرجاع";
        btnReturn.Size = new Size(70, 30);
        btnReturn.Dock = DockStyle.None;
        btnReturn.AutoSize = true;
        btnReturn.Enabled = false;
        btnReturn.AccessibleDescription = "غير مربوط بالخدمة؛ لا يتم تنفيذ أو حفظ بيانات.";
        pnlToolbar.Controls.Add(btnReturn);
        btnReopen.Name = "btnReopen";
        btnReopen.Text = "إعادة فتح";
        btnReopen.Size = new Size(70, 30);
        btnReopen.Dock = DockStyle.None;
        btnReopen.AutoSize = true;
        btnReopen.Enabled = false;
        btnReopen.AccessibleDescription = "غير مربوط بالخدمة؛ لا يتم تنفيذ أو حفظ بيانات.";
        pnlToolbar.Controls.Add(btnReopen);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.Size = new Size(70, 30);
        btnClose.Dock = DockStyle.None;
        btnClose.AutoSize = true;
        btnClose.Enabled = true;
        btnClose.AccessibleDescription = "إغلاق الشاشة";

        btnClose.Click += BtnClose_Click;
        pnlHeader.Controls.Add(designerCommandBar, 0, 1);
        mainLayout.Controls.Add(pnlHeader, 0, 0);
        lblDataStatus.Name = "lblDataStatus";
        lblDataStatus.Text = "واجهة تصميم — لا توجد بيانات محملة؛ الأوامر والبحث والتصفح غير مرتبطة بالخدمات.";
        lblDataStatus.AutoSize = true;
        lblDataStatus.Dock = DockStyle.Fill;
        lblDataStatus.TextAlign = ContentAlignment.MiddleRight;
        mainLayout.Controls.Add(lblDataStatus, 0, 1);
        pnlContent.Name = "pnlContent";
        pnlContent.Dock = DockStyle.Fill;
        pnlContent.AutoScroll = true;
        mainLayout.Controls.Add(pnlContent, 0, 2);
        contentLayout.Name = "contentLayout";
        contentLayout.ColumnCount = 1;
        contentLayout.RowCount = 6;
        contentLayout.Dock = DockStyle.Fill;
        contentLayout.Margin = Padding.Empty;
        contentLayout.AutoSize = false;
        contentLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        contentLayout.Dock = DockStyle.None;
        contentLayout.MinimumSize = new Size(700, 0);
        contentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        pnlContent.Controls.Add(contentLayout);
        detailsLayout.Name = "detailsLayout";
        detailsLayout.ColumnCount = 1;
        detailsLayout.RowCount = 0;
        detailsLayout.Dock = DockStyle.Top;
        detailsLayout.Margin = Padding.Empty;
        detailsLayout.AutoSize = true;
        detailsLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        detailsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        contentLayout.Controls.Add(detailsLayout, 0, 0);
        hiddenVersion.Name = "hiddenVersion";
        hiddenVersion.Visible = false;
        hiddenVersion.ReadOnly = true;
        hiddenVersion.TabStop = false;
        hiddenVersion.Tag = "Version";
        pnlContent.Controls.Add(hiddenVersion);
        searchLayout.Name = "searchLayout";
        searchLayout.ColumnCount = 4;
        searchLayout.RowCount = 4;
        searchLayout.Dock = DockStyle.Top;
        searchLayout.Margin = Padding.Empty;
        searchLayout.AutoSize = true;
        searchLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        searchLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        searchLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        searchLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        filterLabelFiscalYearId.Name = "filterLabelFiscalYearId";
        filterLabelFiscalYearId.Text = "السنة المالية";
        filterLabelFiscalYearId.AutoSize = true;
        filterLabelFiscalYearId.Dock = DockStyle.Fill;
        filterLabelFiscalYearId.TextAlign = ContentAlignment.MiddleRight;
        searchLayout.Controls.Add(filterLabelFiscalYearId, 0, 0);
        filterFiscalYearId.Name = "filterFiscalYearId";
        filterFiscalYearId.Dock = DockStyle.Fill;
        filterFiscalYearId.AccessibleName = "السنة المالية";
        filterFiscalYearId.TabIndex = 0;
        filterFiscalYearId.DropDownStyle = ComboBoxStyle.DropDownList;
        searchLayout.Controls.Add(filterFiscalYearId, 1, 0);
        filterLabelStatus.Name = "filterLabelStatus";
        filterLabelStatus.Text = "الحالة";
        filterLabelStatus.AutoSize = true;
        filterLabelStatus.Dock = DockStyle.Fill;
        filterLabelStatus.TextAlign = ContentAlignment.MiddleRight;
        searchLayout.Controls.Add(filterLabelStatus, 2, 0);
        filterStatus.Name = "filterStatus";
        filterStatus.Dock = DockStyle.Fill;
        filterStatus.AccessibleName = "الحالة";
        filterStatus.TabIndex = 1;
        filterStatus.DropDownStyle = ComboBoxStyle.DropDownList;
        searchLayout.Controls.Add(filterStatus, 3, 0);
        filterLabelDateFrom.Name = "filterLabelDateFrom";
        filterLabelDateFrom.Text = "من تاريخ";
        filterLabelDateFrom.AutoSize = true;
        filterLabelDateFrom.Dock = DockStyle.Fill;
        filterLabelDateFrom.TextAlign = ContentAlignment.MiddleRight;
        searchLayout.Controls.Add(filterLabelDateFrom, 0, 1);
        filterDateFrom.Name = "filterDateFrom";
        filterDateFrom.Dock = DockStyle.Fill;
        filterDateFrom.AccessibleName = "من تاريخ";
        filterDateFrom.TabIndex = 2;
        filterDateFrom.Format = DateTimePickerFormat.Custom;
        filterDateFrom.CustomFormat = "yyyy/MM/dd";
        filterDateFrom.ShowCheckBox = true;
        filterDateFrom.Checked = false;
        searchLayout.Controls.Add(filterDateFrom, 1, 1);
        filterLabelDateTo.Name = "filterLabelDateTo";
        filterLabelDateTo.Text = "إلى تاريخ";
        filterLabelDateTo.AutoSize = true;
        filterLabelDateTo.Dock = DockStyle.Fill;
        filterLabelDateTo.TextAlign = ContentAlignment.MiddleRight;
        searchLayout.Controls.Add(filterLabelDateTo, 2, 1);
        filterDateTo.Name = "filterDateTo";
        filterDateTo.Dock = DockStyle.Fill;
        filterDateTo.AccessibleName = "إلى تاريخ";
        filterDateTo.TabIndex = 3;
        filterDateTo.Format = DateTimePickerFormat.Custom;
        filterDateTo.CustomFormat = "yyyy/MM/dd";
        filterDateTo.ShowCheckBox = true;
        filterDateTo.Checked = false;
        searchLayout.Controls.Add(filterDateTo, 3, 1);
        filterLabelAction.Name = "filterLabelAction";
        filterLabelAction.Text = "الإجراء";
        filterLabelAction.AutoSize = true;
        filterLabelAction.Dock = DockStyle.Fill;
        filterLabelAction.TextAlign = ContentAlignment.MiddleRight;
        searchLayout.Controls.Add(filterLabelAction, 0, 2);
        filterAction.Name = "filterAction";
        filterAction.Dock = DockStyle.Fill;
        filterAction.AccessibleName = "الإجراء";
        filterAction.TabIndex = 4;
        filterAction.DropDownStyle = ComboBoxStyle.DropDownList;
        searchLayout.Controls.Add(filterAction, 1, 2);
        filterLabelAuthorizedScope.Name = "filterLabelAuthorizedScope";
        filterLabelAuthorizedScope.Text = "النطاق المصرح";
        filterLabelAuthorizedScope.AutoSize = true;
        filterLabelAuthorizedScope.Dock = DockStyle.Fill;
        filterLabelAuthorizedScope.TextAlign = ContentAlignment.MiddleRight;
        searchLayout.Controls.Add(filterLabelAuthorizedScope, 2, 2);
        filterAuthorizedScope.Name = "filterAuthorizedScope";
        filterAuthorizedScope.Dock = DockStyle.Fill;
        filterAuthorizedScope.AccessibleName = "النطاق المصرح";
        filterAuthorizedScope.TabIndex = 5;
        filterAuthorizedScope.ReadOnly = true;
        filterAuthorizedScope.AccessibleDescription = "النطاق مشتق من الصلاحيات في الخدمة، غير محمل.";
        searchLayout.Controls.Add(filterAuthorizedScope, 3, 2);
        btnSearch.Name = "btnSearch";
        btnSearch.Text = "بحث";
        btnSearch.Enabled = false;
        btnSearch.AutoSize = true;
        searchLayout.Controls.Add(btnSearch, 3, 3);
        contentLayout.Controls.Add(searchLayout, 0, 1);
        dgvRecords.Name = "dgvRecords";
        dgvRecords.Dock = DockStyle.Fill;
        dgvRecords.MinimumSize = new Size(0, 160);
        dgvRecords.ReadOnly = true;
        dgvRecords.AutoGenerateColumns = false;
        dgvRecords.AllowUserToAddRows = false;
        dgvRecords.AllowUserToDeleteRows = false;
        dgvRecords.MultiSelect = false;
        dgvRecords.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvRecords.RowHeadersVisible = false;
        colFiscalYear.Name = "colFiscalYear";
        colFiscalYear.HeaderText = "السنة المالية";
        colFiscalYear.Tag = "FiscalYear";
        colFiscalYear.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colFiscalYear.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colFiscalYear);
        colPeriodNo.Name = "colPeriodNo";
        colPeriodNo.HeaderText = "رقم الفترة";
        colPeriodNo.Tag = "PeriodNo";
        colPeriodNo.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
        colPeriodNo.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colPeriodNo);
        colStartDate.Name = "colStartDate";
        colStartDate.HeaderText = "تاريخ البداية";
        colStartDate.Tag = "StartDate";
        colStartDate.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
        colStartDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colStartDate);
        colEndDate.Name = "colEndDate";
        colEndDate.HeaderText = "تاريخ النهاية";
        colEndDate.Tag = "EndDate";
        colEndDate.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
        colEndDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colEndDate);
        colStatus.Name = "colStatus";
        colStatus.HeaderText = "الحالة";
        colStatus.Tag = "Status";
        colStatus.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
        colStatus.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colStatus);
        contentLayout.Controls.Add(dgvRecords, 0, 2);
        paging.Name = "paging";
        paging.Dock = DockStyle.Top;
        paging.AutoSize = true;
        paging.WrapContents = true;
        btnPrevious.Name = "btnPrevious";
        btnPrevious.Text = "السابق";
        btnPrevious.Size = new Size(70, 30);
        btnPrevious.Dock = DockStyle.None;
        btnPrevious.AutoSize = true;
        btnPrevious.Enabled = false;
        btnPrevious.AccessibleDescription = "غير مربوط بالخدمة؛ لا يتم تنفيذ أو حفظ بيانات.";
        paging.Controls.Add(btnPrevious);
        btnNext.Name = "btnNext";
        btnNext.Text = "التالي";
        btnNext.Size = new Size(70, 30);
        btnNext.Dock = DockStyle.None;
        btnNext.AutoSize = true;
        btnNext.Enabled = false;
        btnNext.AccessibleDescription = "غير مربوط بالخدمة؛ لا يتم تنفيذ أو حفظ بيانات.";
        paging.Controls.Add(btnNext);
        lblPage.Name = "lblPage";
        lblPage.Text = "الصفحات: — لم يتم تحميل بيانات";
        lblPage.AutoSize = true;
        paging.Controls.Add(lblPage);
        contentLayout.Controls.Add(paging, 0, 3);
        statusLayout.Name = "statusLayout";
        statusLayout.ColumnCount = 1;
        statusLayout.RowCount = 1;
        statusLayout.Dock = DockStyle.Top;
        statusLayout.Margin = Padding.Empty;
        statusLayout.AutoSize = true;
        statusLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        statusLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        statusLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        lblState.Name = "lblState";
        lblState.Text = "سجل الموافقات غير مرتبط. الإجراء المحمي من الخدمة فقط؛ إعادة الفتح تتطلب سبباً ونسخة حديثة.";
        lblState.ReadOnly = true;
        lblState.BorderStyle = BorderStyle.None;
        lblState.BackColor = SystemColors.Window;
        lblState.MinimumSize = new Size(0, 140);
        lblState.Dock = DockStyle.Fill;
        statusLayout.Controls.Add(lblState, 0, 0);
        contentLayout.Controls.Add(statusLayout, 0, 4);
        statusLayout.RowCount = 3;
        statusLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        statusLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        lblReason.Name = "lblReason";
        lblReason.Text = "سبب إعادة الفتح — مطلوب عند ربط الإجراء";
        lblReason.AutoSize = true;
        lblReason.Dock = DockStyle.Fill;
        lblReason.TextAlign = ContentAlignment.MiddleRight;
        statusLayout.Controls.Add(lblReason, 0, 1);
        txtReason.Name = "txtReason";
        txtReason.Dock = DockStyle.Fill;
        txtReason.AccessibleName = "سبب إعادة الفتح";
        statusLayout.Controls.Add(txtReason, 0, 2);
        tlpAuditInfo.Name = "tlpAuditInfo";
        tlpAuditInfo.ColumnCount = 2;
        tlpAuditInfo.RowCount = 2;
        tlpAuditInfo.Dock = DockStyle.Top;
        tlpAuditInfo.Margin = Padding.Empty;
        tlpAuditInfo.AutoSize = true;
        tlpAuditInfo.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        tlpAuditInfo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tlpAuditInfo.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        tlpAuditInfo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tlpAuditInfo.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        lblCreatedBy.Name = "lblCreatedBy";
        lblCreatedBy.Text = "أنشأ بواسطة: —";
        lblCreatedBy.AutoSize = true;
        lblCreatedBy.Dock = DockStyle.Fill;
        lblCreatedBy.TextAlign = ContentAlignment.MiddleRight;
        tlpAuditInfo.Controls.Add(lblCreatedBy, 0, 0);
        lblCreatedAt.Name = "lblCreatedAt";
        lblCreatedAt.Text = "تاريخ الإنشاء: —";
        lblCreatedAt.AutoSize = true;
        lblCreatedAt.Dock = DockStyle.Fill;
        lblCreatedAt.TextAlign = ContentAlignment.MiddleRight;
        tlpAuditInfo.Controls.Add(lblCreatedAt, 1, 0);
        lblModifiedBy.Name = "lblModifiedBy";
        lblModifiedBy.Text = "عدل بواسطة: —";
        lblModifiedBy.AutoSize = true;
        lblModifiedBy.Dock = DockStyle.Fill;
        lblModifiedBy.TextAlign = ContentAlignment.MiddleRight;
        tlpAuditInfo.Controls.Add(lblModifiedBy, 0, 1);
        lblModifiedAt.Name = "lblModifiedAt";
        lblModifiedAt.Text = "تاريخ التعديل: —";
        lblModifiedAt.AutoSize = true;
        lblModifiedAt.Dock = DockStyle.Fill;
        lblModifiedAt.TextAlign = ContentAlignment.MiddleRight;
        tlpAuditInfo.Controls.Add(lblModifiedAt, 1, 1);
        contentLayout.Controls.Add(tlpAuditInfo, 0, 5);
        this.Controls.Add(mainLayout);
        Name = "UcScreen_04_11_01";
        Text = "الفترات المحاسبية";
        Tag = "04.11.01";
        Size = new Size(1100, 760);
        AutoScaleMode = AutoScaleMode.Dpi;
        AutoScaleDimensions = new SizeF(120F, 120F);
        RightToLeft = RightToLeft.Yes;
        Font = new Font("Segoe UI", 10F);
        pnlContent.SizeChanged += ContentSizeChanged;
        ((System.ComponentModel.ISupportInitialize)dgvRecords).EndInit();
        ResumeLayout(false);
        PerformLayout();
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.RightToLeft = RightToLeft.Yes;
        designerCommandBar.Controls.Add(pnlToolbar);
        pnlToolbar.Dock = DockStyle.Fill;
        pnlToolbar.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        pnlToolbar.Name = "pnlToolbar";
        pnlToolbar.Dock = DockStyle.Fill;
        pnlToolbar.AutoSize = false;
        pnlToolbar.WrapContents = false;
        pnlToolbar.FlowDirection = FlowDirection.RightToLeft;
        pnlToolbar.RightToLeft = RightToLeft.No;
        pnlToolbar.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 44;
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = false;
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = false;
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = false;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = false;
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = false;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = false;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = false;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = false;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandSave.Name = "standardCommandSave";
        standardCommandSave.Enabled = false;
        standardCommandSave.Visible = false;
        standardCommandSave.AccessibleName = "حفظ";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = true;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = true;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandAdd.AutoSize = false;
        standardCommandAdd.Dock = DockStyle.None;
        standardCommandAdd.MinimumSize = Size.Empty;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandAdd.Text = "";
        pnlToolbar.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.AutoSize = false;
        standardCommandEdit.Dock = DockStyle.None;
        standardCommandEdit.MinimumSize = Size.Empty;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandEdit.Text = "";
        pnlToolbar.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        pnlToolbar.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.AutoSize = false;
        standardCommandCancel.Dock = DockStyle.None;
        standardCommandCancel.MinimumSize = Size.Empty;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandCancel.Text = "";
        pnlToolbar.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        btnView.AutoSize = false;
        btnView.Dock = DockStyle.None;
        btnView.MinimumSize = Size.Empty;
        btnView.Size = new Size(26, 24);
        btnView.Margin = new Padding(1);
        btnView.FlatStyle = FlatStyle.Flat;
        btnView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        btnView.Text = "";
        pnlToolbar.Controls.Add(btnView);
        designerCommandBar.SetCommandRole(btnView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        pnlToolbar.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        pnlToolbar.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        pnlToolbar.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        pnlToolbar.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        standardCommandSave.AutoSize = false;
        standardCommandSave.Dock = DockStyle.None;
        standardCommandSave.MinimumSize = Size.Empty;
        standardCommandSave.Size = new Size(26, 24);
        standardCommandSave.Margin = new Padding(1);
        standardCommandSave.FlatStyle = FlatStyle.Flat;
        standardCommandSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        standardCommandSave.Text = "";
        pnlToolbar.Controls.Add(standardCommandSave);
        designerCommandBar.SetCommandRole(standardCommandSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        pnlToolbar.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        btnClose.AutoSize = false;
        btnClose.Dock = DockStyle.None;
        btnClose.MinimumSize = Size.Empty;
        btnClose.Size = new Size(26, 24);
        btnClose.Margin = new Padding(1);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        btnClose.Text = "";
        designerCloseHost.Controls.Add(btnClose);
        btnClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        pnlToolbar.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        pnlToolbar.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        pnlToolbar.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        pnlToolbar.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        tlpAuditInfo.Visible = false;
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}
}
