#nullable enable
using System.Drawing;
using System.Windows.Forms;
namespace TransportERP.EmptyForms;
partial class UcScreen_04_11_05
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandSave = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private FlowLayoutPanel flpActions = null!;
    private Button btnView = null!;
    private Button btnExecute = null!;
    private Button btnApprove = null!;
    private Button btnReject = null!;
    private Button btnReturn = null!;
    private Button btnClear = null!;
    private Button btnClose = null!;
    private TabControl tabs = null!;
    private Label lblStatus = null!;
    private TabPage tp0 = null!;
    private TableLayoutPanel layout0 = null!;
    private TextBox field_requestNumber = null!;
    private Label lbl_requestNumber = null!;
    private TextBox field_documentTypeRef = null!;
    private Label lbl_documentTypeRef = null!;
    private TextBox field_linkedDocumentRef = null!;
    private Label lbl_linkedDocumentRef = null!;
    private TextBox field_requestedBy = null!;
    private Label lbl_requestedBy = null!;
    private TextBox field_requestedAt = null!;
    private Label lbl_requestedAt = null!;
    private TextBox field_documentAmount = null!;
    private Label lbl_documentAmount = null!;
    private TextBox field_currency = null!;
    private Label lbl_currency = null!;
    private TextBox field_requestReasonNote = null!;
    private Label lbl_requestReasonNote = null!;
    private TextBox field_approvalLevel = null!;
    private Label lbl_approvalLevel = null!;
    private TabPage tp1 = null!;
    private TableLayoutPanel layout1 = null!;
    private RichTextBox context1 = null!;
    private TabPage tp2 = null!;
    private TableLayoutPanel layout2 = null!;
    private ComboBox field_decision = null!;
    private Label lbl_decision = null!;
    private TextBox field_decisionReason = null!;
    private Label lbl_decisionReason = null!;
    private TabPage tp3 = null!;
    private TableLayoutPanel layout3 = null!;
    private RichTextBox context3 = null!;
    private System.ComponentModel.IContainer? components;
    private ErrorProvider validationErrors = null!;
    protected override void Dispose(bool disposing) { if(disposing) components?.Dispose(); base.Dispose(disposing); }
    private ApprovalQueuePicker approvalQueue = null!;
    private TableLayoutPanel queueHost = null!;
    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandSave = new Button();
        standardCommandPrint = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        components = new System.ComponentModel.Container();
        validationErrors = new ErrorProvider(components);
        validationErrors.ContainerControl = this;
        validationErrors.BlinkStyle = ErrorBlinkStyle.NeverBlink;
        mainLayout = new TableLayoutPanel();
        lblTitle = new Label();
        flpActions = new FlowLayoutPanel();
        btnView = new Button();
        btnExecute = new Button();
        btnApprove = new Button();
        btnReject = new Button();
        btnReturn = new Button();
        btnClear = new Button();
        btnClose = new Button();
        tabs = new TabControl();
        lblStatus = new Label();
        tp0 = new TabPage();
        layout0 = new TableLayoutPanel();
        field_requestNumber = new TextBox();
        lbl_requestNumber = new Label();
        field_documentTypeRef = new TextBox();
        lbl_documentTypeRef = new Label();
        field_linkedDocumentRef = new TextBox();
        lbl_linkedDocumentRef = new Label();
        field_requestedBy = new TextBox();
        lbl_requestedBy = new Label();
        field_requestedAt = new TextBox();
        lbl_requestedAt = new Label();
        field_documentAmount = new TextBox();
        lbl_documentAmount = new Label();
        field_currency = new TextBox();
        lbl_currency = new Label();
        field_requestReasonNote = new TextBox();
        lbl_requestReasonNote = new Label();
        field_approvalLevel = new TextBox();
        lbl_approvalLevel = new Label();
        tp1 = new TabPage();
        layout1 = new TableLayoutPanel();
        context1 = new RichTextBox();
        tp2 = new TabPage();
        layout2 = new TableLayoutPanel();
        field_decision = new ComboBox();
        lbl_decision = new Label();
        field_decisionReason = new TextBox();
        lbl_decisionReason = new Label();
        tp3 = new TabPage();
        layout3 = new TableLayoutPanel();
        context3 = new RichTextBox();
        SuspendLayout();
        mainLayout.Name = "mainLayout";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "طلبات الاعتماد المحاسبية";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Padding = new Padding(8);
        lblTitle.TabStop = false;
        mainLayout.Controls.Add(lblTitle, 0, 0);
        flpActions.Name = "flpActions";
        flpActions.AutoSize = true;
        flpActions.Dock = DockStyle.Fill;
        flpActions.WrapContents = true;
        flpActions.FlowDirection = FlowDirection.LeftToRight;
        flpActions.RightToLeft = RightToLeft.Yes;
        mainLayout.Controls.Add(designerCommandBar, 0, 1);
        btnView.Name = "btnView";
        btnView.Text = "عرض / إعادة تحميل";
        btnView.AutoSize = true;
        btnView.MinimumSize = new Size(100,32);
        btnView.TabIndex = 0;
        btnView.AccessibleName = "عرض / إعادة تحميل";

        btnView.Enabled = false;
        btnExecute.Name = "btnExecute";
        btnExecute.Text = "تنفيذ الطلب";
        btnExecute.AutoSize = true;
        btnExecute.MinimumSize = new Size(100,32);
        btnExecute.TabIndex = 1;
        btnExecute.AccessibleName = "تنفيذ الطلب";
        flpActions.Controls.Add(btnExecute);
        btnExecute.Enabled = false;
        btnApprove.Name = "btnApprove";
        btnApprove.Text = "اعتماد";
        btnApprove.AutoSize = true;
        btnApprove.MinimumSize = new Size(100,32);
        btnApprove.TabIndex = 2;
        btnApprove.AccessibleName = "اعتماد";
        flpActions.Controls.Add(btnApprove);
        btnApprove.Enabled = false;
        btnReject.Name = "btnReject";
        btnReject.Text = "رفض";
        btnReject.AutoSize = true;
        btnReject.MinimumSize = new Size(100,32);
        btnReject.TabIndex = 3;
        btnReject.AccessibleName = "رفض";
        flpActions.Controls.Add(btnReject);
        btnReject.Enabled = false;
        btnReturn.Name = "btnReturn";
        btnReturn.Text = "إرجاع";
        btnReturn.AutoSize = true;
        btnReturn.MinimumSize = new Size(100,32);
        btnReturn.TabIndex = 4;
        btnReturn.AccessibleName = "إرجاع";
        flpActions.Controls.Add(btnReturn);
        btnReturn.Enabled = false;
        btnClear.Name = "btnClear";
        btnClear.Text = "تفريغ المسودة";
        btnClear.AutoSize = true;
        btnClear.MinimumSize = new Size(100,32);
        btnClear.TabIndex = 5;
        btnClear.AccessibleName = "تفريغ المسودة";
        flpActions.Controls.Add(btnClear);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.AutoSize = true;
        btnClose.MinimumSize = new Size(100,32);
        btnClose.TabIndex = 6;
        btnClose.AccessibleName = "إغلاق";

        tabs.Name = "tabs";
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeftLayout = true;
        tabs.Multiline = true;
        tabs.TabIndex = 1;
        mainLayout.Controls.Add(tabs, 0, 2);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "مسودة واجهة غير محفوظة — الخدمات غير موصولة";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.Padding = new Padding(6);
        mainLayout.Controls.Add(lblStatus, 0, 3);
        tp0.Name = "tp0";
        tp0.Text = "الطلب";
        tp0.AutoScroll = true;
        tp0.TabIndex = 0;
        tabs.Controls.Add(tp0);
        layout0.Name = "layout0";
        layout0.Dock = DockStyle.Top;
        layout0.AutoSize = true;
        layout0.ColumnCount = 2;
        layout0.MinimumSize = new Size(650,0);
        layout0.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp0.Controls.Add(layout0);
        field_requestNumber.Name = "field_requestNumber";
        lbl_requestNumber.Name = "lbl_requestNumber";
        field_requestNumber.AccessibleName = "رقم الطلب";
        field_requestNumber.Tag = "ACC-057:requestNumber";
        field_requestNumber.Dock = DockStyle.Fill;
        field_requestNumber.TabIndex = 0;
        lbl_requestNumber.Text = "رقم الطلب";
        lbl_requestNumber.AutoSize = true;
        lbl_requestNumber.Dock = DockStyle.Fill;
        lbl_requestNumber.TextAlign = ContentAlignment.MiddleRight;
        lbl_requestNumber.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_requestNumber, 0, 0);
        layout0.Controls.Add(field_requestNumber, 1, 0);
        field_requestNumber.ReadOnly = true;
        field_requestNumber.TabStop = false;
        field_documentTypeRef.Name = "field_documentTypeRef";
        lbl_documentTypeRef.Name = "lbl_documentTypeRef";
        field_documentTypeRef.AccessibleName = "نوع المستند";
        field_documentTypeRef.Tag = "ACC-057:documentTypeRef";
        field_documentTypeRef.Dock = DockStyle.Fill;
        field_documentTypeRef.TabIndex = 1;
        lbl_documentTypeRef.Text = "نوع المستند";
        lbl_documentTypeRef.AutoSize = true;
        lbl_documentTypeRef.Dock = DockStyle.Fill;
        lbl_documentTypeRef.TextAlign = ContentAlignment.MiddleRight;
        lbl_documentTypeRef.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_documentTypeRef, 0, 1);
        layout0.Controls.Add(field_documentTypeRef, 1, 1);
        field_documentTypeRef.ReadOnly = true;
        field_documentTypeRef.TabStop = false;
        field_linkedDocumentRef.Name = "field_linkedDocumentRef";
        lbl_linkedDocumentRef.Name = "lbl_linkedDocumentRef";
        field_linkedDocumentRef.AccessibleName = "المستند المرتبط";
        field_linkedDocumentRef.Tag = "ACC-057:linkedDocumentRef";
        field_linkedDocumentRef.Dock = DockStyle.Fill;
        field_linkedDocumentRef.TabIndex = 2;
        lbl_linkedDocumentRef.Text = "المستند المرتبط";
        lbl_linkedDocumentRef.AutoSize = true;
        lbl_linkedDocumentRef.Dock = DockStyle.Fill;
        lbl_linkedDocumentRef.TextAlign = ContentAlignment.MiddleRight;
        lbl_linkedDocumentRef.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_linkedDocumentRef, 0, 2);
        layout0.Controls.Add(field_linkedDocumentRef, 1, 2);
        field_linkedDocumentRef.ReadOnly = true;
        field_linkedDocumentRef.TabStop = false;
        field_requestedBy.Name = "field_requestedBy";
        lbl_requestedBy.Name = "lbl_requestedBy";
        field_requestedBy.AccessibleName = "مقدم الطلب";
        field_requestedBy.Tag = "ACC-057:requestedBy";
        field_requestedBy.Dock = DockStyle.Fill;
        field_requestedBy.TabIndex = 3;
        lbl_requestedBy.Text = "مقدم الطلب";
        lbl_requestedBy.AutoSize = true;
        lbl_requestedBy.Dock = DockStyle.Fill;
        lbl_requestedBy.TextAlign = ContentAlignment.MiddleRight;
        lbl_requestedBy.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_requestedBy, 0, 3);
        layout0.Controls.Add(field_requestedBy, 1, 3);
        field_requestedBy.ReadOnly = true;
        field_requestedBy.TabStop = false;
        field_requestedAt.Name = "field_requestedAt";
        lbl_requestedAt.Name = "lbl_requestedAt";
        field_requestedAt.AccessibleName = "وقت الطلب";
        field_requestedAt.Tag = "ACC-057:requestedAt";
        field_requestedAt.Dock = DockStyle.Fill;
        field_requestedAt.TabIndex = 4;
        lbl_requestedAt.Text = "وقت الطلب";
        lbl_requestedAt.AutoSize = true;
        lbl_requestedAt.Dock = DockStyle.Fill;
        lbl_requestedAt.TextAlign = ContentAlignment.MiddleRight;
        lbl_requestedAt.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_requestedAt, 0, 4);
        layout0.Controls.Add(field_requestedAt, 1, 4);
        field_requestedAt.ReadOnly = true;
        field_requestedAt.TabStop = false;
        field_documentAmount.Name = "field_documentAmount";
        lbl_documentAmount.Name = "lbl_documentAmount";
        field_documentAmount.AccessibleName = "مبلغ المستند";
        field_documentAmount.Tag = "ACC-057:documentAmount";
        field_documentAmount.Dock = DockStyle.Fill;
        field_documentAmount.TabIndex = 5;
        lbl_documentAmount.Text = "مبلغ المستند";
        lbl_documentAmount.AutoSize = true;
        lbl_documentAmount.Dock = DockStyle.Fill;
        lbl_documentAmount.TextAlign = ContentAlignment.MiddleRight;
        lbl_documentAmount.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_documentAmount, 0, 5);
        layout0.Controls.Add(field_documentAmount, 1, 5);
        field_documentAmount.ReadOnly = true;
        field_documentAmount.TabStop = false;
        field_currency.Name = "field_currency";
        lbl_currency.Name = "lbl_currency";
        field_currency.AccessibleName = "العملة";
        field_currency.Tag = "ACC-057:currency";
        field_currency.Dock = DockStyle.Fill;
        field_currency.TabIndex = 6;
        lbl_currency.Text = "العملة";
        lbl_currency.AutoSize = true;
        lbl_currency.Dock = DockStyle.Fill;
        lbl_currency.TextAlign = ContentAlignment.MiddleRight;
        lbl_currency.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_currency, 0, 6);
        layout0.Controls.Add(field_currency, 1, 6);
        field_currency.ReadOnly = true;
        field_currency.TabStop = false;
        field_requestReasonNote.Name = "field_requestReasonNote";
        lbl_requestReasonNote.Name = "lbl_requestReasonNote";
        field_requestReasonNote.AccessibleName = "سبب/ملاحظة الطلب";
        field_requestReasonNote.Tag = "ACC-057:requestReasonNote";
        field_requestReasonNote.Dock = DockStyle.Fill;
        field_requestReasonNote.TabIndex = 7;
        lbl_requestReasonNote.Text = "سبب/ملاحظة الطلب";
        lbl_requestReasonNote.AutoSize = true;
        lbl_requestReasonNote.Dock = DockStyle.Fill;
        lbl_requestReasonNote.TextAlign = ContentAlignment.MiddleRight;
        lbl_requestReasonNote.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_requestReasonNote, 0, 7);
        layout0.Controls.Add(field_requestReasonNote, 1, 7);
        field_requestReasonNote.ReadOnly = true;
        field_requestReasonNote.TabStop = false;
        field_approvalLevel.Name = "field_approvalLevel";
        lbl_approvalLevel.Name = "lbl_approvalLevel";
        field_approvalLevel.AccessibleName = "مستوى الاعتماد";
        field_approvalLevel.Tag = "ACC-057:approvalLevel";
        field_approvalLevel.Dock = DockStyle.Fill;
        field_approvalLevel.TabIndex = 8;
        lbl_approvalLevel.Text = "مستوى الاعتماد";
        lbl_approvalLevel.AutoSize = true;
        lbl_approvalLevel.Dock = DockStyle.Fill;
        lbl_approvalLevel.TextAlign = ContentAlignment.MiddleRight;
        lbl_approvalLevel.TabStop = false;
        layout0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout0.Controls.Add(lbl_approvalLevel, 0, 8);
        layout0.Controls.Add(field_approvalLevel, 1, 8);
        field_approvalLevel.ReadOnly = true;
        field_approvalLevel.TabStop = false;
        layout0.RowCount = 9;
        tp1.Name = "tp1";
        tp1.Text = "المستندات المرتبطة";
        tp1.AutoScroll = true;
        tp1.TabIndex = 1;
        tabs.Controls.Add(tp1);
        layout1.Name = "layout1";
        layout1.Dock = DockStyle.Top;
        layout1.AutoSize = true;
        layout1.ColumnCount = 2;
        layout1.MinimumSize = new Size(650,0);
        layout1.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp1.Controls.Add(layout1);
        layout1.RowCount = 0;
        layout1.Dock = DockStyle.Fill;
        layout1.RowCount = 1;
        layout1.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        context1.Name = "context1";
        context1.ReadOnly = true;
        context1.Dock = DockStyle.Fill;
        context1.AccessibleName = "المستندات المرتبطة";
        context1.DetectUrls = false;
        layout1.Controls.Add(context1, 0, 0);
        layout1.SetColumnSpan(context1,2);
        tp2.Name = "tp2";
        tp2.Text = "قرار الاعتماد";
        tp2.AutoScroll = true;
        tp2.TabIndex = 2;
        tabs.Controls.Add(tp2);
        layout2.Name = "layout2";
        layout2.Dock = DockStyle.Top;
        layout2.AutoSize = true;
        layout2.ColumnCount = 2;
        layout2.MinimumSize = new Size(650,0);
        layout2.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp2.Controls.Add(layout2);
        field_decision.Name = "field_decision";
        lbl_decision.Name = "lbl_decision";
        field_decision.AccessibleName = "القرار";
        field_decision.Tag = "ACC-057:decision";
        field_decision.Dock = DockStyle.Fill;
        field_decision.TabIndex = 0;
        lbl_decision.Text = "القرار";
        lbl_decision.AutoSize = true;
        lbl_decision.Dock = DockStyle.Fill;
        lbl_decision.TextAlign = ContentAlignment.MiddleRight;
        lbl_decision.TabStop = false;
        layout2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout2.Controls.Add(lbl_decision, 0, 0);
        layout2.Controls.Add(field_decision, 1, 0);
        field_decision.DropDownStyle = ComboBoxStyle.DropDownList;
        field_decision.DropDownWidth = 420;
        field_decisionReason.Name = "field_decisionReason";
        lbl_decisionReason.Name = "lbl_decisionReason";
        field_decisionReason.AccessibleName = "سبب القرار";
        field_decisionReason.Tag = "ACC-057:decisionReason";
        field_decisionReason.Dock = DockStyle.Fill;
        field_decisionReason.TabIndex = 1;
        lbl_decisionReason.Text = "سبب القرار";
        lbl_decisionReason.AutoSize = true;
        lbl_decisionReason.Dock = DockStyle.Fill;
        lbl_decisionReason.TextAlign = ContentAlignment.MiddleRight;
        lbl_decisionReason.TabStop = false;
        layout2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout2.Controls.Add(lbl_decisionReason, 0, 1);
        layout2.Controls.Add(field_decisionReason, 1, 1);
        field_decisionReason.Multiline = true;
        field_decisionReason.Height = 70;
        field_decisionReason.ScrollBars = ScrollBars.Vertical;
        layout2.RowCount = 2;
        tp3.Name = "tp3";
        tp3.Text = "سجل الاعتماد والتدقيق";
        tp3.AutoScroll = true;
        tp3.TabIndex = 3;
        tabs.Controls.Add(tp3);
        layout3.Name = "layout3";
        layout3.Dock = DockStyle.Top;
        layout3.AutoSize = true;
        layout3.ColumnCount = 2;
        layout3.MinimumSize = new Size(650,0);
        layout3.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,195F));
        layout3.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        tp3.Controls.Add(layout3);
        layout3.RowCount = 0;
        layout3.Dock = DockStyle.Fill;
        layout3.RowCount = 1;
        layout3.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        context3.Name = "context3";
        context3.ReadOnly = true;
        context3.Dock = DockStyle.Fill;
        context3.AccessibleName = "سجل الاعتماد والتدقيق";
        context3.DetectUrls = false;
        layout3.Controls.Add(context3, 0, 0);
        layout3.SetColumnSpan(context3,2);
        approvalQueue = new ApprovalQueuePicker();
        queueHost = new TableLayoutPanel();
        approvalQueue.Name = "approvalQueue";
        approvalQueue.Dock = DockStyle.Fill;
        approvalQueue.TabIndex = 0;
        queueHost.Name = "queueHost";
        queueHost.Dock = DockStyle.Top;
        queueHost.AutoSize = true;
        queueHost.ColumnCount = 1;
        queueHost.RowCount = 2;
        queueHost.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        queueHost.RowStyles.Add(new RowStyle(SizeType.Absolute,190F));
        queueHost.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        tp0.Controls.Remove(layout0);
        queueHost.Controls.Add(approvalQueue,0,0);
        queueHost.Controls.Add(layout0,0,1);
        layout0.TabIndex=1;
        tp0.Controls.Add(queueHost);
        btnClear.Visible=false;
        AutoScaleDimensions = new SizeF(96F,96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Name = "UcScreen_04_11_05";
        Text = "طلبات الاعتماد المحاسبية";
        Tag = "04.11.05";
        Size = new Size(1100,720);
        Controls.Add(mainLayout);
        ResumeLayout(false);
        PerformLayout();
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Fill;
        designerCommandBar.RightToLeft = RightToLeft.Yes;
        designerCommandBar.Controls.Add(flpActions);
        flpActions.Dock = DockStyle.Fill;
        flpActions.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        flpActions.Name = "flpActions";
        flpActions.Dock = DockStyle.Fill;
        flpActions.AutoSize = false;
        flpActions.WrapContents = false;
        flpActions.FlowDirection = FlowDirection.RightToLeft;
        flpActions.RightToLeft = RightToLeft.No;
        flpActions.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 44;
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = false;
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = false;
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = false;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = false;
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = false;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = false;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = false;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = false;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandSave.Name = "standardCommandSave";
        standardCommandSave.Enabled = false;
        standardCommandSave.Visible = false;
        standardCommandSave.AccessibleName = "حفظ";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = true;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = true;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandAdd.AutoSize = false;
        standardCommandAdd.Dock = DockStyle.None;
        standardCommandAdd.MinimumSize = Size.Empty;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandAdd.Text = "";
        flpActions.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.AutoSize = false;
        standardCommandEdit.Dock = DockStyle.None;
        standardCommandEdit.MinimumSize = Size.Empty;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandEdit.Text = "";
        flpActions.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        flpActions.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.AutoSize = false;
        standardCommandCancel.Dock = DockStyle.None;
        standardCommandCancel.MinimumSize = Size.Empty;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandCancel.Text = "";
        flpActions.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        btnView.AutoSize = false;
        btnView.Dock = DockStyle.None;
        btnView.MinimumSize = Size.Empty;
        btnView.Size = new Size(26, 24);
        btnView.Margin = new Padding(1);
        btnView.FlatStyle = FlatStyle.Flat;
        btnView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        btnView.Text = "";
        flpActions.Controls.Add(btnView);
        designerCommandBar.SetCommandRole(btnView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        flpActions.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        flpActions.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        flpActions.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        flpActions.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        standardCommandSave.AutoSize = false;
        standardCommandSave.Dock = DockStyle.None;
        standardCommandSave.MinimumSize = Size.Empty;
        standardCommandSave.Size = new Size(26, 24);
        standardCommandSave.Margin = new Padding(1);
        standardCommandSave.FlatStyle = FlatStyle.Flat;
        standardCommandSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        standardCommandSave.Text = "";
        flpActions.Controls.Add(standardCommandSave);
        designerCommandBar.SetCommandRole(standardCommandSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        flpActions.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        btnClose.AutoSize = false;
        btnClose.Dock = DockStyle.None;
        btnClose.MinimumSize = Size.Empty;
        btnClose.Size = new Size(26, 24);
        btnClose.Margin = new Padding(1);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        btnClose.Text = "";
        designerCloseHost.Controls.Add(btnClose);
        btnClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        flpActions.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        flpActions.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        flpActions.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        flpActions.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}
}
