namespace TransportERP.EmptyForms;

partial class UcScreen_02_02_08
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel mainLayout = null!;
    private TableLayoutPanel pnlHeader = null!;
    private Label lblTitle = null!;
    private FlowLayoutPanel pnlToolbar = null!;
    private Button btnView = null!;
    private Button btnNew = null!;
    private Button btnSave = null!;
    private Button btnEdit = null!;
    private Button btnDisable = null!;
    private Button btnClose = null!;
    private Label lblDataStatus = null!;
    private Panel pnlContent = null!;
    private TableLayoutPanel contentLayout = null!;
    private TableLayoutPanel fieldsLayout = null!;
    private Label lblCityId = null!;
    private ComboBox cmbCityId = null!;
    private Label lblCode = null!;
    private TextBox txtCode = null!;
    private Label lblArabicName = null!;
    private TextBox txtArabicName = null!;
    private Label lblEnglishName = null!;
    private TextBox txtEnglishName = null!;
    private Label lblStatus = null!;
    private TextBox txtStatus = null!;
    private TextBox txtVersion = null!;
    private TableLayoutPanel searchLayout = null!;
    private Label lblFilterSearchText = null!;
    private TextBox filterSearchText = null!;
    private Label lblFilterStatus = null!;
    private ComboBox filterStatus = null!;
    private Label lblFilterCityId = null!;
    private ComboBox filterCityId = null!;
    private Button btnSearch = null!;
    private DataGridView dgvRecords = null!;
    private DataGridViewTextBoxColumn colCode = null!;
    private DataGridViewTextBoxColumn colArabicName = null!;
    private DataGridViewTextBoxColumn colEnglishName = null!;
    private DataGridViewTextBoxColumn colStatus = null!;
    private FlowLayoutPanel paging = null!;
    private Button btnPrevious = null!;
    private Button btnNext = null!;
    private Label lblPage = null!;
    private TableLayoutPanel tlpAuditInfo = null!;
    private Label lblCreatedBy = null!;
    private Label lblCreatedAt = null!;
    private Label lblModifiedBy = null!;
    private Label lblModifiedAt = null!;

    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCloseHost = new Panel();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandPrint = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        mainLayout = new TableLayoutPanel();
        pnlHeader = new TableLayoutPanel();
        lblTitle = new Label();
        pnlToolbar = new FlowLayoutPanel();
        btnView = new Button();
        btnNew = new Button();
        btnSave = new Button();
        btnEdit = new Button();
        btnDisable = new Button();
        btnClose = new Button();
        lblDataStatus = new Label();
        pnlContent = new Panel();
        contentLayout = new TableLayoutPanel();
        fieldsLayout = new TableLayoutPanel();
        lblCityId = new Label();
        cmbCityId = new ComboBox();
        lblCode = new Label();
        txtCode = new TextBox();
        lblArabicName = new Label();
        txtArabicName = new TextBox();
        lblEnglishName = new Label();
        txtEnglishName = new TextBox();
        lblStatus = new Label();
        txtStatus = new TextBox();
        txtVersion = new TextBox();
        searchLayout = new TableLayoutPanel();
        lblFilterSearchText = new Label();
        filterSearchText = new TextBox();
        lblFilterStatus = new Label();
        filterStatus = new ComboBox();
        lblFilterCityId = new Label();
        filterCityId = new ComboBox();
        btnSearch = new Button();
        dgvRecords = new DataGridView();
        colCode = new DataGridViewTextBoxColumn();
        colArabicName = new DataGridViewTextBoxColumn();
        colEnglishName = new DataGridViewTextBoxColumn();
        colStatus = new DataGridViewTextBoxColumn();
        paging = new FlowLayoutPanel();
        btnPrevious = new Button();
        btnNext = new Button();
        lblPage = new Label();
        tlpAuditInfo = new TableLayoutPanel();
        lblCreatedBy = new Label();
        lblCreatedAt = new Label();
        lblModifiedBy = new Label();
        lblModifiedAt = new Label();
        SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)dgvRecords).BeginInit();
        mainLayout.Name = "mainLayout";
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 3;
        mainLayout.Margin = Padding.Empty;
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pnlHeader.Name = "pnlHeader";
        pnlHeader.ColumnCount = 1;
        pnlHeader.RowCount = 2;
        pnlHeader.Margin = Padding.Empty;
        pnlHeader.Dock = DockStyle.Top;
        pnlHeader.AutoSize = true;
        pnlHeader.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        pnlHeader.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "المناطق";
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.AutoSize = true;
        lblTitle.Font = new Font("Segoe UI", 16F);
        lblTitle.BackColor = Color.FromArgb(192, 192, 255);
        pnlHeader.Controls.Add(lblTitle, 0, 0);
        pnlToolbar.Name = "pnlToolbar";
        pnlToolbar.Dock = DockStyle.Top;
        pnlToolbar.AutoSize = true;
        pnlToolbar.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlToolbar.FlowDirection = FlowDirection.LeftToRight;
        pnlToolbar.RightToLeft = RightToLeft.Yes;
        pnlToolbar.WrapContents = true;
        btnView.Name = "btnView";
        btnView.Text = "عرض";
        btnView.AutoSize = true;
        btnView.Dock = DockStyle.None;
        btnView.Size = new Size(70, 30);
        btnView.Margin = new Padding(4);
        btnView.Enabled = false;
        btnView.AccessibleDescription = "غير منفذ: لم يتم ربط خدمة البيانات أو الحفظ.";

        btnNew.Name = "btnNew";
        btnNew.Text = "جديد";
        btnNew.AutoSize = true;
        btnNew.Dock = DockStyle.None;
        btnNew.Size = new Size(70, 30);
        btnNew.Margin = new Padding(4);
        btnNew.Enabled = false;
        btnNew.AccessibleDescription = "غير منفذ: لم يتم ربط خدمة البيانات أو الحفظ.";

        btnSave.Name = "btnSave";
        btnSave.Text = "حفظ";
        btnSave.AutoSize = true;
        btnSave.Dock = DockStyle.None;
        btnSave.Size = new Size(70, 30);
        btnSave.Margin = new Padding(4);
        btnSave.Enabled = false;
        btnSave.AccessibleDescription = "غير منفذ: لم يتم ربط خدمة البيانات أو الحفظ.";

        btnEdit.Name = "btnEdit";
        btnEdit.Text = "تعديل";
        btnEdit.AutoSize = true;
        btnEdit.Dock = DockStyle.None;
        btnEdit.Size = new Size(70, 30);
        btnEdit.Margin = new Padding(4);
        btnEdit.Enabled = false;
        btnEdit.AccessibleDescription = "غير منفذ: لم يتم ربط خدمة البيانات أو الحفظ.";

        btnDisable.Name = "btnDisable";
        btnDisable.Text = "إيقاف";
        btnDisable.AutoSize = true;
        btnDisable.Dock = DockStyle.None;
        btnDisable.Size = new Size(70, 30);
        btnDisable.Margin = new Padding(4);
        btnDisable.Enabled = false;
        btnDisable.AccessibleDescription = "غير منفذ: لم يتم ربط خدمة البيانات أو الحفظ.";
        pnlToolbar.Controls.Add(btnDisable);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.AutoSize = true;
        btnClose.Dock = DockStyle.None;
        btnClose.Size = new Size(70, 30);
        btnClose.Margin = new Padding(4);
        btnClose.Enabled = true;
        btnClose.AccessibleDescription = "إغلاق الشاشة";

        btnClose.Click += BtnClose_Click;
        pnlHeader.Controls.Add(designerCommandBar, 0, 1);
        mainLayout.Controls.Add(pnlHeader, 0, 0);
        lblDataStatus.Name = "lblDataStatus";
        lblDataStatus.Text = "واجهة تصميم — لم يتم تحميل بيانات؛ الحفظ والبحث والتصفح غير مربوطين بالخدمات.";
        lblDataStatus.AutoSize = true;
        lblDataStatus.Dock = DockStyle.Fill;
        mainLayout.Controls.Add(lblDataStatus, 0, 1);
        pnlContent.Name = "pnlContent";
        pnlContent.Dock = DockStyle.Fill;
        pnlContent.AutoScroll = true;
        mainLayout.Controls.Add(pnlContent, 0, 2);
        contentLayout.Name = "contentLayout";
        contentLayout.ColumnCount = 1;
        contentLayout.RowCount = 5;
        contentLayout.Margin = Padding.Empty;
        contentLayout.Dock = DockStyle.Top;
        contentLayout.AutoSize = false;
        contentLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        contentLayout.MinimumSize = new Size(700, 0);
        contentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        pnlContent.Controls.Add(contentLayout);
        fieldsLayout.Name = "fieldsLayout";
        fieldsLayout.ColumnCount = 4;
        fieldsLayout.RowCount = 3;
        fieldsLayout.Margin = Padding.Empty;
        fieldsLayout.Dock = DockStyle.Top;
        fieldsLayout.AutoSize = true;
        fieldsLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        fieldsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        fieldsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        fieldsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        fieldsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        fieldsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        fieldsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        fieldsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        lblCityId.Name = "lblCityId";
        lblCityId.Text = "المدينة *";
        lblCityId.Dock = DockStyle.Fill;
        lblCityId.TextAlign = ContentAlignment.MiddleRight;
        cmbCityId.Name = "cmbCityId";
        cmbCityId.AccessibleName = "المدينة";
        cmbCityId.Tag = "CityId";
        cmbCityId.Dock = DockStyle.Fill;
        cmbCityId.Margin = new Padding(3);
        cmbCityId.TabIndex = 0;
        cmbCityId.BackColor = Color.FromArgb(255, 249, 219);
        cmbCityId.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbCityId.AccessibleDescription = "يُحدد الأصل عند الإنشاء فقط ولا يمكن تغييره عند التعديل؛ تطبيق القيد ينتظر ربط دورة السجل.";
        cmbCityId.AccessibleDescription = "مرجع مطلوب؛ لا يوجد مزود بيانات متصل. اختيار الأصل خاص بالإنشاء ولا يُغيّر عند التعديل.";
        fieldsLayout.Controls.Add(lblCityId, 0, 0);
        fieldsLayout.Controls.Add(cmbCityId, 1, 0);
        lblCode.Name = "lblCode";
        lblCode.Text = "الرمز *";
        lblCode.Dock = DockStyle.Fill;
        lblCode.TextAlign = ContentAlignment.MiddleRight;
        txtCode.Name = "txtCode";
        txtCode.AccessibleName = "الرمز";
        txtCode.Tag = "Code";
        txtCode.Dock = DockStyle.Fill;
        txtCode.Margin = new Padding(3);
        txtCode.TabIndex = 1;
        txtCode.BackColor = Color.FromArgb(255, 249, 219);
        txtCode.RightToLeft = RightToLeft.No;
        fieldsLayout.Controls.Add(lblCode, 2, 0);
        fieldsLayout.Controls.Add(txtCode, 3, 0);
        lblArabicName.Name = "lblArabicName";
        lblArabicName.Text = "الاسم العربي *";
        lblArabicName.Dock = DockStyle.Fill;
        lblArabicName.TextAlign = ContentAlignment.MiddleRight;
        txtArabicName.Name = "txtArabicName";
        txtArabicName.AccessibleName = "الاسم العربي";
        txtArabicName.Tag = "ArabicName";
        txtArabicName.Dock = DockStyle.Fill;
        txtArabicName.Margin = new Padding(3);
        txtArabicName.TabIndex = 2;
        txtArabicName.BackColor = Color.FromArgb(255, 249, 219);
        fieldsLayout.Controls.Add(lblArabicName, 0, 1);
        fieldsLayout.Controls.Add(txtArabicName, 1, 1);
        lblEnglishName.Name = "lblEnglishName";
        lblEnglishName.Text = "الاسم الإنجليزي";
        lblEnglishName.Dock = DockStyle.Fill;
        lblEnglishName.TextAlign = ContentAlignment.MiddleRight;
        txtEnglishName.Name = "txtEnglishName";
        txtEnglishName.AccessibleName = "الاسم الإنجليزي";
        txtEnglishName.Tag = "EnglishName";
        txtEnglishName.Dock = DockStyle.Fill;
        txtEnglishName.Margin = new Padding(3);
        txtEnglishName.TabIndex = 3;
        txtEnglishName.RightToLeft = RightToLeft.No;
        fieldsLayout.Controls.Add(lblEnglishName, 2, 1);
        fieldsLayout.Controls.Add(txtEnglishName, 3, 1);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "الحالة";
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.TextAlign = ContentAlignment.MiddleRight;
        txtStatus.Name = "txtStatus";
        txtStatus.AccessibleName = "الحالة";
        txtStatus.Tag = "Status";
        txtStatus.Dock = DockStyle.Fill;
        txtStatus.Margin = new Padding(3);
        txtStatus.TabIndex = 4;
        txtStatus.ReadOnly = true;
        txtStatus.AccessibleDescription = "إسقاط حالة من الخدمة؛ لا تُعدل الحالة مباشرة.";
        fieldsLayout.Controls.Add(lblStatus, 0, 2);
        fieldsLayout.Controls.Add(txtStatus, 1, 2);
        contentLayout.Controls.Add(fieldsLayout, 0, 0);
        txtVersion.Name = "txtVersion";
        txtVersion.Tag = "Version";
        txtVersion.Visible = false;
        txtVersion.ReadOnly = true;
        txtVersion.TabStop = false;
        pnlContent.Controls.Add(txtVersion);
        searchLayout.Name = "searchLayout";
        searchLayout.ColumnCount = 4;
        searchLayout.RowCount = 2;
        searchLayout.Margin = Padding.Empty;
        searchLayout.AutoSize = true;
        searchLayout.Dock = DockStyle.Top;
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        searchLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        lblFilterSearchText.Name = "lblFilterSearchText";
        lblFilterSearchText.Text = "نص البحث";
        lblFilterSearchText.Dock = DockStyle.Fill;
        filterSearchText.Name = "filterSearchText";
        filterSearchText.Dock = DockStyle.Fill;
        filterSearchText.TabIndex = 0;
        filterSearchText.AccessibleName = "نص البحث";
        searchLayout.Controls.Add(lblFilterSearchText, 0, 0);
        searchLayout.Controls.Add(filterSearchText, 1, 0);
        lblFilterStatus.Name = "lblFilterStatus";
        lblFilterStatus.Text = "الحالة";
        lblFilterStatus.Dock = DockStyle.Fill;
        filterStatus.Name = "filterStatus";
        filterStatus.Dock = DockStyle.Fill;
        filterStatus.TabIndex = 1;
        filterStatus.AccessibleName = "الحالة";
        filterStatus.DropDownStyle = ComboBoxStyle.DropDownList;
        filterStatus.Items.AddRange(new object[] { "الكل", "Active", "Stopped" });
        filterStatus.SelectedIndex = 0;
        searchLayout.Controls.Add(lblFilterStatus, 2, 0);
        searchLayout.Controls.Add(filterStatus, 3, 0);
        lblFilterCityId.Name = "lblFilterCityId";
        lblFilterCityId.Text = "المدينة";
        lblFilterCityId.Dock = DockStyle.Fill;
        filterCityId.Name = "filterCityId";
        filterCityId.Dock = DockStyle.Fill;
        filterCityId.TabIndex = 2;
        filterCityId.AccessibleName = "المدينة";
        filterCityId.DropDownStyle = ComboBoxStyle.DropDownList;
        filterCityId.Items.Add("الكل");
        filterCityId.SelectedIndex = 0;
        searchLayout.Controls.Add(lblFilterCityId, 0, 1);
        searchLayout.Controls.Add(filterCityId, 1, 1);
        btnSearch.Name = "btnSearch";
        btnSearch.Text = "بحث";
        btnSearch.Enabled = false;
        btnSearch.AutoSize = true;
        btnSearch.Dock = DockStyle.None;
        btnSearch.AccessibleDescription = "البحث بالخدمة غير مربوط.";
        searchLayout.Controls.Add(btnSearch, 3, 1);
        contentLayout.Controls.Add(searchLayout, 0, 1);
        dgvRecords.Name = "dgvRecords";
        dgvRecords.Dock = DockStyle.Fill;
        dgvRecords.MinimumSize = new Size(0, 280);
        dgvRecords.ReadOnly = true;
        dgvRecords.AutoGenerateColumns = false;
        dgvRecords.AllowUserToAddRows = false;
        dgvRecords.AllowUserToDeleteRows = false;
        dgvRecords.MultiSelect = false;
        dgvRecords.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvRecords.RowHeadersVisible = false;
        dgvRecords.AccessibleName = "قائمة البيانات — لا توجد بيانات محملة";
        colCode.Name = "colCode";
        colCode.HeaderText = "الرمز";
        colCode.Tag = "Code";
        colCode.AutoSizeMode = DataGridViewAutoSizeColumnMode.DisplayedCells;
        colCode.MinimumWidth = 75;
        colCode.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colCode);
        colArabicName.Name = "colArabicName";
        colArabicName.HeaderText = "الاسم العربي";
        colArabicName.Tag = "ArabicName";
        colArabicName.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colArabicName.FillWeight = 160F;
        colArabicName.MinimumWidth = 75;
        colArabicName.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colArabicName);
        colEnglishName.Name = "colEnglishName";
        colEnglishName.HeaderText = "الاسم الإنجليزي";
        colEnglishName.Tag = "EnglishName";
        colEnglishName.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colEnglishName.FillWeight = 100F;
        colEnglishName.MinimumWidth = 75;
        colEnglishName.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colEnglishName);
        colStatus.Name = "colStatus";
        colStatus.HeaderText = "الحالة";
        colStatus.Tag = "Status";
        colStatus.AutoSizeMode = DataGridViewAutoSizeColumnMode.DisplayedCells;
        colStatus.MinimumWidth = 75;
        colStatus.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRecords.Columns.Add(colStatus);
        contentLayout.Controls.Add(dgvRecords, 0, 2);
        paging.Name = "paging";
        paging.Dock = DockStyle.Top;
        paging.AutoSize = true;
        paging.WrapContents = true;
        paging.FlowDirection = FlowDirection.LeftToRight;
        paging.RightToLeft = RightToLeft.Yes;
        btnPrevious.Name = "btnPrevious";
        btnPrevious.Text = "السابق";
        btnPrevious.AutoSize = true;
        btnPrevious.Dock = DockStyle.None;
        btnPrevious.Size = new Size(70, 30);
        btnPrevious.Margin = new Padding(4);
        btnPrevious.Enabled = false;
        btnPrevious.AccessibleDescription = "غير منفذ: لم يتم ربط خدمة البيانات أو الحفظ.";
        paging.Controls.Add(btnPrevious);
        btnNext.Name = "btnNext";
        btnNext.Text = "التالي";
        btnNext.AutoSize = true;
        btnNext.Dock = DockStyle.None;
        btnNext.Size = new Size(70, 30);
        btnNext.Margin = new Padding(4);
        btnNext.Enabled = false;
        btnNext.AccessibleDescription = "غير منفذ: لم يتم ربط خدمة البيانات أو الحفظ.";
        paging.Controls.Add(btnNext);
        lblPage.Name = "lblPage";
        lblPage.Text = "الصفحات: — لم يتصل مزود البيانات";
        lblPage.AutoSize = true;
        paging.Controls.Add(lblPage);
        contentLayout.Controls.Add(paging, 0, 3);
        tlpAuditInfo.Name = "tlpAuditInfo";
        tlpAuditInfo.ColumnCount = 2;
        tlpAuditInfo.RowCount = 2;
        tlpAuditInfo.Margin = Padding.Empty;
        tlpAuditInfo.Dock = DockStyle.Top;
        tlpAuditInfo.AutoSize = true;
        tlpAuditInfo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tlpAuditInfo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        tlpAuditInfo.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        tlpAuditInfo.RowStyles.Add(new RowStyle(SizeType.AutoSize, 0F));
        lblCreatedBy.Name = "lblCreatedBy";
        lblCreatedBy.Text = "أنشأ بواسطة: —";
        lblCreatedBy.AutoSize = true;
        lblCreatedBy.Dock = DockStyle.Fill;
        tlpAuditInfo.Controls.Add(lblCreatedBy, 0, 0);
        lblCreatedAt.Name = "lblCreatedAt";
        lblCreatedAt.Text = "تاريخ الإنشاء: —";
        lblCreatedAt.AutoSize = true;
        lblCreatedAt.Dock = DockStyle.Fill;
        tlpAuditInfo.Controls.Add(lblCreatedAt, 1, 0);
        lblModifiedBy.Name = "lblModifiedBy";
        lblModifiedBy.Text = "عدل بواسطة: —";
        lblModifiedBy.AutoSize = true;
        lblModifiedBy.Dock = DockStyle.Fill;
        tlpAuditInfo.Controls.Add(lblModifiedBy, 0, 1);
        lblModifiedAt.Name = "lblModifiedAt";
        lblModifiedAt.Text = "تاريخ التعديل: —";
        lblModifiedAt.AutoSize = true;
        lblModifiedAt.Dock = DockStyle.Fill;
        tlpAuditInfo.Controls.Add(lblModifiedAt, 1, 1);
        contentLayout.Controls.Add(tlpAuditInfo, 0, 4);
        Controls.Add(mainLayout);
        Name = "UcScreen_02_02_08";
        Text = "المناطق";
        Tag = "02.02.08";
        AutoScaleDimensions = new SizeF(120F, 120F);
        AutoScaleMode = AutoScaleMode.Dpi;
        RightToLeft = RightToLeft.Yes;
        Font = new Font("Segoe UI", 10F);
        Size = new Size(1100, 760);
        pnlHeader.TabIndex = 0;
        lblDataStatus.TabIndex = 1;
        pnlContent.TabIndex = 2;
        fieldsLayout.TabIndex = 0;
        searchLayout.TabIndex = 1;
        dgvRecords.TabIndex = 2;
        paging.TabIndex = 3;
        tlpAuditInfo.TabIndex = 4;
        ((System.ComponentModel.ISupportInitialize)dgvRecords).EndInit();
        ResumeLayout(false);
        PerformLayout();
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.RightToLeft = RightToLeft.Yes;
        designerCommandBar.Controls.Add(pnlToolbar);
        pnlToolbar.Dock = DockStyle.Fill;
        pnlToolbar.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        pnlToolbar.Name = "pnlToolbar";
        pnlToolbar.Dock = DockStyle.Fill;
        pnlToolbar.AutoSize = false;
        pnlToolbar.WrapContents = false;
        pnlToolbar.FlowDirection = FlowDirection.RightToLeft;
        pnlToolbar.RightToLeft = RightToLeft.No;
        pnlToolbar.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 44;
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        btnNew.AutoSize = false;
        btnNew.Dock = DockStyle.None;
        btnNew.MinimumSize = Size.Empty;
        btnNew.Size = new Size(26, 24);
        btnNew.Margin = new Padding(1);
        btnNew.FlatStyle = FlatStyle.Flat;
        btnNew.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnNew.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        btnNew.Text = "";
        pnlToolbar.Controls.Add(btnNew);
        designerCommandBar.SetCommandRole(btnNew, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        btnEdit.AutoSize = false;
        btnEdit.Dock = DockStyle.None;
        btnEdit.MinimumSize = Size.Empty;
        btnEdit.Size = new Size(26, 24);
        btnEdit.Margin = new Padding(1);
        btnEdit.FlatStyle = FlatStyle.Flat;
        btnEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        btnEdit.Text = "";
        pnlToolbar.Controls.Add(btnEdit);
        designerCommandBar.SetCommandRole(btnEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        pnlToolbar.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.AutoSize = false;
        standardCommandCancel.Dock = DockStyle.None;
        standardCommandCancel.MinimumSize = Size.Empty;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandCancel.Text = "";
        pnlToolbar.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        btnView.AutoSize = false;
        btnView.Dock = DockStyle.None;
        btnView.MinimumSize = Size.Empty;
        btnView.Size = new Size(26, 24);
        btnView.Margin = new Padding(1);
        btnView.FlatStyle = FlatStyle.Flat;
        btnView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        btnView.Text = "";
        pnlToolbar.Controls.Add(btnView);
        designerCommandBar.SetCommandRole(btnView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        pnlToolbar.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        pnlToolbar.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        pnlToolbar.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        pnlToolbar.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        btnSave.AutoSize = false;
        btnSave.Dock = DockStyle.None;
        btnSave.MinimumSize = Size.Empty;
        btnSave.Size = new Size(26, 24);
        btnSave.Margin = new Padding(1);
        btnSave.FlatStyle = FlatStyle.Flat;
        btnSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        btnSave.Text = "";
        pnlToolbar.Controls.Add(btnSave);
        designerCommandBar.SetCommandRole(btnSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        pnlToolbar.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        btnClose.AutoSize = false;
        btnClose.Dock = DockStyle.None;
        btnClose.MinimumSize = Size.Empty;
        btnClose.Size = new Size(26, 24);
        btnClose.Margin = new Padding(1);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        btnClose.Text = "";
        designerCloseHost.Controls.Add(btnClose);
        btnClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        pnlToolbar.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        pnlToolbar.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        pnlToolbar.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        pnlToolbar.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Profile = TransportERP.Desktop.CoreUI.AuditMetadataProfile.ModificationOnly;
        standardAuditMetadata.Size = new Size(800, 36);
        tlpAuditInfo.Visible = false;
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}
}
