using System.Drawing;
using System.Windows.Forms;

namespace TransportERP.EmptyForms;

partial class UcAccountOpeningRequest
{
    private System.ComponentModel.IContainer? components;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        mainLayout = new TableLayoutPanel();
        pnlActions = new FlowLayoutPanel();
        btnNew = new Button();
        btnSave = new Button();
        btnEdit = new Button();
        btnDelete = new Button();
        btnRefresh = new Button();
        btnClose = new Button();
        lblPreview = new Label();
        tabMain = new TabControl();
        tpRequest = new TabPage();
        Requests = new TableLayoutPanel();
        RequestsFields = new TableLayoutPanel();
        lbltxtRequestNumber = new Label();
        txtRequestNumber = new TextBox();
        lbldtpRequestDate = new Label();
        dtpRequestDate = new DateTimePicker();
        lblcmbCompany = new Label();
        cmbCompany = new ComboBox();
        lblcmbBranch = new Label();
        cmbBranch = new ComboBox();
        lblcmbParentAccount = new Label();
        cmbParentAccount = new ComboBox();
        lbltxtRequestedAccountName = new Label();
        txtRequestedAccountName = new TextBox();
        lblcmbRequestedAccountType = new Label();
        cmbRequestedAccountType = new ComboBox();
        lbltxtRequestStatus = new Label();
        txtRequestStatus = new TextBox();
        lbltxtRequestReason = new Label();
        txtRequestReason = new TextBox();
        dgvRequests = new DataGridView();
        dgvRequestsColNumber = new DataGridViewTextBoxColumn();
        dgvRequestsColDate = new DataGridViewTextBoxColumn();
        dgvRequestsColAccount = new DataGridViewTextBoxColumn();
        dgvRequestsColStatus = new DataGridViewTextBoxColumn();
        tpNotes = new TabPage();
        txtNotes = new TextBox();
        ((System.ComponentModel.ISupportInitialize)dgvRequests).BeginInit();
        mainLayout.SuspendLayout();
        pnlActions.SuspendLayout();
        tabMain.SuspendLayout();
        tpRequest.SuspendLayout();
        Requests.SuspendLayout();
        RequestsFields.SuspendLayout();
        tpNotes.SuspendLayout();
        SuspendLayout();
        mainLayout.Name = "mainLayout";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 3;
        mainLayout.Padding = new Padding(12);
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
        pnlActions.Name = "pnlActions";
        pnlActions.Dock = DockStyle.Fill;
        pnlActions.WrapContents = false;
        pnlActions.AutoScroll = true;
        pnlActions.FlowDirection = FlowDirection.LeftToRight;
        btnNew.Name = "btnNew";
        btnNew.Text = "جديد";
        btnNew.Size = new Size(112, 36);
        btnNew.Margin = new Padding(4);
        btnNew.Enabled = false;
        btnNew.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnNew);
        btnSave.Name = "btnSave";
        btnSave.Text = "حفظ";
        btnSave.Size = new Size(112, 36);
        btnSave.Margin = new Padding(4);
        btnSave.Enabled = false;
        btnSave.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnSave);
        btnEdit.Name = "btnEdit";
        btnEdit.Text = "تعديل";
        btnEdit.Size = new Size(112, 36);
        btnEdit.Margin = new Padding(4);
        btnEdit.Enabled = false;
        btnEdit.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnEdit);
        btnDelete.Name = "btnDelete";
        btnDelete.Text = "حذف";
        btnDelete.Size = new Size(112, 36);
        btnDelete.Margin = new Padding(4);
        btnDelete.Enabled = false;
        btnDelete.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnDelete);
        btnRefresh.Name = "btnRefresh";
        btnRefresh.Text = "تحديث";
        btnRefresh.Size = new Size(112, 36);
        btnRefresh.Margin = new Padding(4);
        btnRefresh.Enabled = false;
        btnRefresh.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnRefresh);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.Size = new Size(112, 36);
        btnClose.Margin = new Padding(4);
        btnClose.Enabled = true;
        btnClose.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnClose);
        btnClose.Click += BtnClose_Click;
        lblPreview.Name = "lblPreview";
        lblPreview.Text = "وضع المعاينة — التغييرات غير محفوظة";
        lblPreview.Dock = DockStyle.Fill;
        lblPreview.TextAlign = ContentAlignment.MiddleLeft;
        lblPreview.ForeColor = Color.DimGray;
        mainLayout.Controls.Add(pnlActions, 0, 0);
        mainLayout.Controls.Add(lblPreview, 0, 2);
        tabMain.Name = "tabMain";
        tabMain.Dock = DockStyle.Fill;
        tabMain.RightToLeftLayout = true;
        tabMain.SizeMode = TabSizeMode.Normal;
        mainLayout.Controls.Add(tabMain, 0, 1);
        tpRequest.Name = "tpRequest";
        tpRequest.Text = "بيانات الطلب";
        tpRequest.Padding = new Padding(12);
        tpRequest.AutoScroll = true;
        tpRequest.BackColor = Color.White;
        tabMain.TabPages.Add(tpRequest);
        Requests.Name = "Requests";
        Requests.Dock = DockStyle.Fill;
        Requests.ColumnCount = 1;
        Requests.RowCount = 2;
        Requests.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        Requests.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        Requests.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        RequestsFields.Name = "RequestsFields";
        RequestsFields.Dock = DockStyle.Top;
        RequestsFields.AutoSize = true;
        RequestsFields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        RequestsFields.ColumnCount = 4;
        RequestsFields.RowCount = 5;
        RequestsFields.Padding = new Padding(4);
        RequestsFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        RequestsFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        RequestsFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        RequestsFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        RequestsFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        RequestsFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        RequestsFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        RequestsFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        RequestsFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        lbltxtRequestNumber.Name = "lbltxtRequestNumber";
        lbltxtRequestNumber.Text = "رقم الطلب";
        lbltxtRequestNumber.Dock = DockStyle.Fill;
        lbltxtRequestNumber.TextAlign = ContentAlignment.MiddleLeft;
        lbltxtRequestNumber.AutoSize = false;
        lbltxtRequestNumber.TabStop = false;
        txtRequestNumber.Name = "txtRequestNumber";
        txtRequestNumber.Dock = DockStyle.Fill;
        txtRequestNumber.Margin = new Padding(6, 10, 12, 10);
        txtRequestNumber.TabIndex = 0;
        txtRequestNumber.AccessibleName = "رقم الطلب";
        txtRequestNumber.ReadOnly = true;
        txtRequestNumber.TabStop = false;
        RequestsFields.Controls.Add(lbltxtRequestNumber, 0, 0);
        RequestsFields.Controls.Add(txtRequestNumber, 1, 0);
        lbldtpRequestDate.Name = "lbldtpRequestDate";
        lbldtpRequestDate.Text = "تاريخ الطلب *";
        lbldtpRequestDate.Dock = DockStyle.Fill;
        lbldtpRequestDate.TextAlign = ContentAlignment.MiddleLeft;
        lbldtpRequestDate.AutoSize = false;
        lbldtpRequestDate.TabStop = false;
        dtpRequestDate.Name = "dtpRequestDate";
        dtpRequestDate.Dock = DockStyle.Fill;
        dtpRequestDate.Margin = new Padding(6, 10, 12, 10);
        dtpRequestDate.TabIndex = 1;
        dtpRequestDate.AccessibleName = "تاريخ الطلب";
        dtpRequestDate.BackColor = Color.FromArgb(255, 250, 205);
        dtpRequestDate.Format = DateTimePickerFormat.Custom;
        dtpRequestDate.CustomFormat = "yyyy/MM/dd";
        dtpRequestDate.ShowCheckBox = true;
        dtpRequestDate.Checked = false;
        RequestsFields.Controls.Add(lbldtpRequestDate, 2, 0);
        RequestsFields.Controls.Add(dtpRequestDate, 3, 0);
        lblcmbCompany.Name = "lblcmbCompany";
        lblcmbCompany.Text = "الشركة *";
        lblcmbCompany.Dock = DockStyle.Fill;
        lblcmbCompany.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbCompany.AutoSize = false;
        lblcmbCompany.TabStop = false;
        cmbCompany.Name = "cmbCompany";
        cmbCompany.Dock = DockStyle.Fill;
        cmbCompany.Margin = new Padding(6, 10, 12, 10);
        cmbCompany.TabIndex = 2;
        cmbCompany.AccessibleName = "الشركة";
        cmbCompany.BackColor = Color.FromArgb(255, 250, 205);
        cmbCompany.DropDownStyle = ComboBoxStyle.DropDownList;
        RequestsFields.Controls.Add(lblcmbCompany, 0, 1);
        RequestsFields.Controls.Add(cmbCompany, 1, 1);
        lblcmbBranch.Name = "lblcmbBranch";
        lblcmbBranch.Text = "الفرع";
        lblcmbBranch.Dock = DockStyle.Fill;
        lblcmbBranch.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbBranch.AutoSize = false;
        lblcmbBranch.TabStop = false;
        cmbBranch.Name = "cmbBranch";
        cmbBranch.Dock = DockStyle.Fill;
        cmbBranch.Margin = new Padding(6, 10, 12, 10);
        cmbBranch.TabIndex = 3;
        cmbBranch.AccessibleName = "الفرع";
        cmbBranch.DropDownStyle = ComboBoxStyle.DropDownList;
        RequestsFields.Controls.Add(lblcmbBranch, 2, 1);
        RequestsFields.Controls.Add(cmbBranch, 3, 1);
        lblcmbParentAccount.Name = "lblcmbParentAccount";
        lblcmbParentAccount.Text = "الحساب الأب *";
        lblcmbParentAccount.Dock = DockStyle.Fill;
        lblcmbParentAccount.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbParentAccount.AutoSize = false;
        lblcmbParentAccount.TabStop = false;
        cmbParentAccount.Name = "cmbParentAccount";
        cmbParentAccount.Dock = DockStyle.Fill;
        cmbParentAccount.Margin = new Padding(6, 10, 12, 10);
        cmbParentAccount.TabIndex = 4;
        cmbParentAccount.AccessibleName = "الحساب الأب";
        cmbParentAccount.BackColor = Color.FromArgb(255, 250, 205);
        cmbParentAccount.DropDownStyle = ComboBoxStyle.DropDownList;
        RequestsFields.Controls.Add(lblcmbParentAccount, 0, 2);
        RequestsFields.Controls.Add(cmbParentAccount, 1, 2);
        lbltxtRequestedAccountName.Name = "lbltxtRequestedAccountName";
        lbltxtRequestedAccountName.Text = "اسم الحساب المطلوب *";
        lbltxtRequestedAccountName.Dock = DockStyle.Fill;
        lbltxtRequestedAccountName.TextAlign = ContentAlignment.MiddleLeft;
        lbltxtRequestedAccountName.AutoSize = false;
        lbltxtRequestedAccountName.TabStop = false;
        txtRequestedAccountName.Name = "txtRequestedAccountName";
        txtRequestedAccountName.Dock = DockStyle.Fill;
        txtRequestedAccountName.Margin = new Padding(6, 10, 12, 10);
        txtRequestedAccountName.TabIndex = 5;
        txtRequestedAccountName.AccessibleName = "اسم الحساب المطلوب";
        txtRequestedAccountName.BackColor = Color.FromArgb(255, 250, 205);
        RequestsFields.Controls.Add(lbltxtRequestedAccountName, 2, 2);
        RequestsFields.Controls.Add(txtRequestedAccountName, 3, 2);
        lblcmbRequestedAccountType.Name = "lblcmbRequestedAccountType";
        lblcmbRequestedAccountType.Text = "نوع الحساب *";
        lblcmbRequestedAccountType.Dock = DockStyle.Fill;
        lblcmbRequestedAccountType.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbRequestedAccountType.AutoSize = false;
        lblcmbRequestedAccountType.TabStop = false;
        cmbRequestedAccountType.Name = "cmbRequestedAccountType";
        cmbRequestedAccountType.Dock = DockStyle.Fill;
        cmbRequestedAccountType.Margin = new Padding(6, 10, 12, 10);
        cmbRequestedAccountType.TabIndex = 6;
        cmbRequestedAccountType.AccessibleName = "نوع الحساب";
        cmbRequestedAccountType.BackColor = Color.FromArgb(255, 250, 205);
        cmbRequestedAccountType.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbRequestedAccountType.Items.AddRange(new object[] { "أصول", "التزامات", "حقوق ملكية", "إيرادات", "مصروفات" });
        RequestsFields.Controls.Add(lblcmbRequestedAccountType, 0, 3);
        RequestsFields.Controls.Add(cmbRequestedAccountType, 1, 3);
        lbltxtRequestStatus.Name = "lbltxtRequestStatus";
        lbltxtRequestStatus.Text = "الحالة";
        lbltxtRequestStatus.Dock = DockStyle.Fill;
        lbltxtRequestStatus.TextAlign = ContentAlignment.MiddleLeft;
        lbltxtRequestStatus.AutoSize = false;
        lbltxtRequestStatus.TabStop = false;
        txtRequestStatus.Name = "txtRequestStatus";
        txtRequestStatus.Dock = DockStyle.Fill;
        txtRequestStatus.Margin = new Padding(6, 10, 12, 10);
        txtRequestStatus.TabIndex = 7;
        txtRequestStatus.AccessibleName = "الحالة";
        txtRequestStatus.ReadOnly = true;
        txtRequestStatus.TabStop = false;
        RequestsFields.Controls.Add(lbltxtRequestStatus, 2, 3);
        RequestsFields.Controls.Add(txtRequestStatus, 3, 3);
        lbltxtRequestReason.Name = "lbltxtRequestReason";
        lbltxtRequestReason.Text = "سبب الطلب *";
        lbltxtRequestReason.Dock = DockStyle.Fill;
        lbltxtRequestReason.TextAlign = ContentAlignment.MiddleLeft;
        lbltxtRequestReason.AutoSize = false;
        lbltxtRequestReason.TabStop = false;
        txtRequestReason.Name = "txtRequestReason";
        txtRequestReason.Dock = DockStyle.Fill;
        txtRequestReason.Margin = new Padding(6, 10, 12, 10);
        txtRequestReason.TabIndex = 8;
        txtRequestReason.AccessibleName = "سبب الطلب";
        txtRequestReason.BackColor = Color.FromArgb(255, 250, 205);
        RequestsFields.Controls.Add(lbltxtRequestReason, 0, 4);
        RequestsFields.Controls.Add(txtRequestReason, 1, 4);
        Requests.Controls.Add(RequestsFields);
        Requests.SetCellPosition(RequestsFields, new TableLayoutPanelCellPosition(0, 0));
        dgvRequests.Name = "dgvRequests";
        dgvRequests.Dock = DockStyle.Fill;
        dgvRequests.BackgroundColor = Color.White;
        dgvRequests.BorderStyle = BorderStyle.FixedSingle;
        dgvRequests.AutoGenerateColumns = false;
        dgvRequests.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        dgvRequests.AllowUserToAddRows = false;
        dgvRequests.AllowUserToDeleteRows = false;
        dgvRequests.ReadOnly = true;
        dgvRequests.RowHeadersVisible = false;
        dgvRequests.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvRequests.MultiSelect = false;
        dgvRequests.MinimumSize = new Size(0, 160);
        dgvRequests.AccessibleName = "قائمة البيانات — لم يتم تحميل بيانات";
        dgvRequestsColNumber.Name = "dgvRequestsColNumber";
        dgvRequestsColNumber.HeaderText = "رقم الطلب";
        dgvRequestsColNumber.MinimumWidth = 90;
        dgvRequestsColNumber.FillWeight = 100F;
        dgvRequestsColNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRequests.Columns.Add(dgvRequestsColNumber);
        dgvRequestsColDate.Name = "dgvRequestsColDate";
        dgvRequestsColDate.HeaderText = "التاريخ";
        dgvRequestsColDate.MinimumWidth = 90;
        dgvRequestsColDate.FillWeight = 100F;
        dgvRequestsColDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRequests.Columns.Add(dgvRequestsColDate);
        dgvRequestsColAccount.Name = "dgvRequestsColAccount";
        dgvRequestsColAccount.HeaderText = "الحساب المطلوب";
        dgvRequestsColAccount.MinimumWidth = 90;
        dgvRequestsColAccount.FillWeight = 100F;
        dgvRequestsColAccount.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRequests.Columns.Add(dgvRequestsColAccount);
        dgvRequestsColStatus.Name = "dgvRequestsColStatus";
        dgvRequestsColStatus.HeaderText = "الحالة";
        dgvRequestsColStatus.MinimumWidth = 90;
        dgvRequestsColStatus.FillWeight = 100F;
        dgvRequestsColStatus.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRequests.Columns.Add(dgvRequestsColStatus);
        Requests.Controls.Add(dgvRequests);
        Requests.SetCellPosition(dgvRequests, new TableLayoutPanelCellPosition(0, 1));
        tpRequest.Controls.Add(Requests);
        tpNotes.Name = "tpNotes";
        tpNotes.Text = "الملاحظات";
        tpNotes.Padding = new Padding(12);
        tpNotes.AutoScroll = true;
        tpNotes.BackColor = Color.White;
        tabMain.TabPages.Add(tpNotes);
        txtNotes.Name = "txtNotes";
        txtNotes.Dock = DockStyle.Fill;
        txtNotes.Multiline = true;
        txtNotes.ScrollBars = ScrollBars.Vertical;
        txtNotes.MaxLength = 4000;
        txtNotes.AccessibleName = "الملاحظات";
        tpNotes.Controls.Add(txtNotes);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 10F);
        BackColor = Color.White;
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1120, 720);
        MinimumSize = new Size(936, 600);
        Name = "UcAccountOpeningRequest";
        Text = "طلب فتح حساب";
        Tag = "ONYX:SCREEN-0086";
        Controls.Add(mainLayout);
        tpNotes.ResumeLayout(false);
        tpNotes.PerformLayout();
        RequestsFields.ResumeLayout(false);
        RequestsFields.PerformLayout();
        Requests.ResumeLayout(false);
        Requests.PerformLayout();
        tpRequest.ResumeLayout(false);
        tpRequest.PerformLayout();
        tabMain.ResumeLayout(false);
        tabMain.PerformLayout();
        pnlActions.ResumeLayout(false);
        pnlActions.PerformLayout();
        mainLayout.ResumeLayout(false);
        mainLayout.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)dgvRequests).EndInit();
        ResumeLayout(false);
    }

    private TableLayoutPanel mainLayout = null!;
    private FlowLayoutPanel pnlActions = null!;
    private Button btnNew = null!;
    private Button btnSave = null!;
    private Button btnEdit = null!;
    private Button btnDelete = null!;
    private Button btnRefresh = null!;
    private Button btnClose = null!;
    private Label lblPreview = null!;
    private TabControl tabMain = null!;
    private TabPage tpRequest = null!;
    private TableLayoutPanel Requests = null!;
    private TableLayoutPanel RequestsFields = null!;
    private Label lbltxtRequestNumber = null!;
    private TextBox txtRequestNumber = null!;
    private Label lbldtpRequestDate = null!;
    private DateTimePicker dtpRequestDate = null!;
    private Label lblcmbCompany = null!;
    private ComboBox cmbCompany = null!;
    private Label lblcmbBranch = null!;
    private ComboBox cmbBranch = null!;
    private Label lblcmbParentAccount = null!;
    private ComboBox cmbParentAccount = null!;
    private Label lbltxtRequestedAccountName = null!;
    private TextBox txtRequestedAccountName = null!;
    private Label lblcmbRequestedAccountType = null!;
    private ComboBox cmbRequestedAccountType = null!;
    private Label lbltxtRequestStatus = null!;
    private TextBox txtRequestStatus = null!;
    private Label lbltxtRequestReason = null!;
    private TextBox txtRequestReason = null!;
    private DataGridView dgvRequests = null!;
    private DataGridViewTextBoxColumn dgvRequestsColNumber = null!;
    private DataGridViewTextBoxColumn dgvRequestsColDate = null!;
    private DataGridViewTextBoxColumn dgvRequestsColAccount = null!;
    private DataGridViewTextBoxColumn dgvRequestsColStatus = null!;
    private TabPage tpNotes = null!;
    private TextBox txtNotes = null!;
}
