using System.Drawing;
using System.Windows.Forms;

namespace TransportERP.EmptyForms;

partial class UcAccountCostCenterLinking
{
    private System.ComponentModel.IContainer? components;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        mainLayout = new TableLayoutPanel();
        pnlActions = new FlowLayoutPanel();
        btnNew = new Button();
        btnSave = new Button();
        btnEdit = new Button();
        btnDelete = new Button();
        btnRefresh = new Button();
        btnClose = new Button();
        lblPreview = new Label();
        tabMain = new TabControl();
        tpLinks = new TabPage();
        Links = new TableLayoutPanel();
        LinksFields = new TableLayoutPanel();
        lblcmbCompany = new Label();
        cmbCompany = new ComboBox();
        lblcmbAccount = new Label();
        cmbAccount = new ComboBox();
        lblcmbTarget = new Label();
        cmbTarget = new ComboBox();
        lblcmbBranch = new Label();
        cmbBranch = new ComboBox();
        lblchkLinkActive = new Label();
        chkLinkActive = new CheckBox();
        dgvLinks = new DataGridView();
        dgvLinksColAccount = new DataGridViewTextBoxColumn();
        dgvLinksColTarget = new DataGridViewTextBoxColumn();
        dgvLinksColBranch = new DataGridViewTextBoxColumn();
        dgvLinksColActive = new DataGridViewTextBoxColumn();
        tpNotes = new TabPage();
        txtNotes = new TextBox();
        ((System.ComponentModel.ISupportInitialize)dgvLinks).BeginInit();
        mainLayout.SuspendLayout();
        pnlActions.SuspendLayout();
        tabMain.SuspendLayout();
        tpLinks.SuspendLayout();
        Links.SuspendLayout();
        LinksFields.SuspendLayout();
        tpNotes.SuspendLayout();
        SuspendLayout();
        mainLayout.Name = "mainLayout";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 3;
        mainLayout.Padding = new Padding(12);
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
        pnlActions.Name = "pnlActions";
        pnlActions.Dock = DockStyle.Fill;
        pnlActions.WrapContents = false;
        pnlActions.AutoScroll = true;
        pnlActions.FlowDirection = FlowDirection.LeftToRight;
        btnNew.Name = "btnNew";
        btnNew.Text = "جديد";
        btnNew.Size = new Size(112, 36);
        btnNew.Margin = new Padding(4);
        btnNew.Enabled = false;
        btnNew.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnNew);
        btnSave.Name = "btnSave";
        btnSave.Text = "حفظ";
        btnSave.Size = new Size(112, 36);
        btnSave.Margin = new Padding(4);
        btnSave.Enabled = false;
        btnSave.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnSave);
        btnEdit.Name = "btnEdit";
        btnEdit.Text = "تعديل";
        btnEdit.Size = new Size(112, 36);
        btnEdit.Margin = new Padding(4);
        btnEdit.Enabled = false;
        btnEdit.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnEdit);
        btnDelete.Name = "btnDelete";
        btnDelete.Text = "حذف";
        btnDelete.Size = new Size(112, 36);
        btnDelete.Margin = new Padding(4);
        btnDelete.Enabled = false;
        btnDelete.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnDelete);
        btnRefresh.Name = "btnRefresh";
        btnRefresh.Text = "تحديث";
        btnRefresh.Size = new Size(112, 36);
        btnRefresh.Margin = new Padding(4);
        btnRefresh.Enabled = false;
        btnRefresh.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnRefresh);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.Size = new Size(112, 36);
        btnClose.Margin = new Padding(4);
        btnClose.Enabled = true;
        btnClose.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnClose);
        btnClose.Click += BtnClose_Click;
        lblPreview.Name = "lblPreview";
        lblPreview.Text = "وضع المعاينة — التغييرات غير محفوظة";
        lblPreview.Dock = DockStyle.Fill;
        lblPreview.TextAlign = ContentAlignment.MiddleLeft;
        lblPreview.ForeColor = Color.DimGray;
        mainLayout.Controls.Add(pnlActions, 0, 0);
        mainLayout.Controls.Add(lblPreview, 0, 2);
        tabMain.Name = "tabMain";
        tabMain.Dock = DockStyle.Fill;
        tabMain.RightToLeftLayout = true;
        tabMain.SizeMode = TabSizeMode.Normal;
        mainLayout.Controls.Add(tabMain, 0, 1);
        tpLinks.Name = "tpLinks";
        tpLinks.Text = "الربط";
        tpLinks.Padding = new Padding(12);
        tpLinks.AutoScroll = true;
        tpLinks.BackColor = Color.White;
        tabMain.TabPages.Add(tpLinks);
        Links.Name = "Links";
        Links.Dock = DockStyle.Fill;
        Links.ColumnCount = 1;
        Links.RowCount = 2;
        Links.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        Links.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        Links.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        LinksFields.Name = "LinksFields";
        LinksFields.Dock = DockStyle.Top;
        LinksFields.AutoSize = true;
        LinksFields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        LinksFields.ColumnCount = 4;
        LinksFields.RowCount = 3;
        LinksFields.Padding = new Padding(4);
        LinksFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        LinksFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        LinksFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        LinksFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        LinksFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        LinksFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        LinksFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        lblcmbCompany.Name = "lblcmbCompany";
        lblcmbCompany.Text = "الشركة *";
        lblcmbCompany.Dock = DockStyle.Fill;
        lblcmbCompany.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbCompany.AutoSize = false;
        lblcmbCompany.TabStop = false;
        cmbCompany.Name = "cmbCompany";
        cmbCompany.Dock = DockStyle.Fill;
        cmbCompany.Margin = new Padding(6, 10, 12, 10);
        cmbCompany.TabIndex = 0;
        cmbCompany.AccessibleName = "الشركة";
        cmbCompany.BackColor = Color.FromArgb(255, 250, 205);
        cmbCompany.DropDownStyle = ComboBoxStyle.DropDownList;
        LinksFields.Controls.Add(lblcmbCompany, 0, 0);
        LinksFields.Controls.Add(cmbCompany, 1, 0);
        lblcmbAccount.Name = "lblcmbAccount";
        lblcmbAccount.Text = "الحساب *";
        lblcmbAccount.Dock = DockStyle.Fill;
        lblcmbAccount.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbAccount.AutoSize = false;
        lblcmbAccount.TabStop = false;
        cmbAccount.Name = "cmbAccount";
        cmbAccount.Dock = DockStyle.Fill;
        cmbAccount.Margin = new Padding(6, 10, 12, 10);
        cmbAccount.TabIndex = 1;
        cmbAccount.AccessibleName = "الحساب";
        cmbAccount.BackColor = Color.FromArgb(255, 250, 205);
        cmbAccount.DropDownStyle = ComboBoxStyle.DropDownList;
        LinksFields.Controls.Add(lblcmbAccount, 2, 0);
        LinksFields.Controls.Add(cmbAccount, 3, 0);
        lblcmbTarget.Name = "lblcmbTarget";
        lblcmbTarget.Text = "مركز التكلفة *";
        lblcmbTarget.Dock = DockStyle.Fill;
        lblcmbTarget.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbTarget.AutoSize = false;
        lblcmbTarget.TabStop = false;
        cmbTarget.Name = "cmbTarget";
        cmbTarget.Dock = DockStyle.Fill;
        cmbTarget.Margin = new Padding(6, 10, 12, 10);
        cmbTarget.TabIndex = 2;
        cmbTarget.AccessibleName = "مركز التكلفة";
        cmbTarget.BackColor = Color.FromArgb(255, 250, 205);
        cmbTarget.DropDownStyle = ComboBoxStyle.DropDownList;
        LinksFields.Controls.Add(lblcmbTarget, 0, 1);
        LinksFields.Controls.Add(cmbTarget, 1, 1);
        lblcmbBranch.Name = "lblcmbBranch";
        lblcmbBranch.Text = "نطاق الفرع";
        lblcmbBranch.Dock = DockStyle.Fill;
        lblcmbBranch.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbBranch.AutoSize = false;
        lblcmbBranch.TabStop = false;
        cmbBranch.Name = "cmbBranch";
        cmbBranch.Dock = DockStyle.Fill;
        cmbBranch.Margin = new Padding(6, 10, 12, 10);
        cmbBranch.TabIndex = 3;
        cmbBranch.AccessibleName = "نطاق الفرع";
        cmbBranch.DropDownStyle = ComboBoxStyle.DropDownList;
        LinksFields.Controls.Add(lblcmbBranch, 2, 1);
        LinksFields.Controls.Add(cmbBranch, 3, 1);
        lblchkLinkActive.Name = "lblchkLinkActive";
        lblchkLinkActive.Text = "نشط";
        lblchkLinkActive.Dock = DockStyle.Fill;
        lblchkLinkActive.TextAlign = ContentAlignment.MiddleLeft;
        lblchkLinkActive.AutoSize = false;
        lblchkLinkActive.TabStop = false;
        chkLinkActive.Name = "chkLinkActive";
        chkLinkActive.Dock = DockStyle.None;
        chkLinkActive.Margin = new Padding(6, 10, 12, 10);
        chkLinkActive.TabIndex = 4;
        chkLinkActive.AccessibleName = "نشط";
        chkLinkActive.Text = "نشط";
        chkLinkActive.AutoSize = true;
        LinksFields.Controls.Add(lblchkLinkActive, 0, 2);
        LinksFields.Controls.Add(chkLinkActive, 1, 2);
        Links.Controls.Add(LinksFields);
        Links.SetCellPosition(LinksFields, new TableLayoutPanelCellPosition(0, 0));
        dgvLinks.Name = "dgvLinks";
        dgvLinks.Dock = DockStyle.Fill;
        dgvLinks.BackgroundColor = Color.White;
        dgvLinks.BorderStyle = BorderStyle.FixedSingle;
        dgvLinks.AutoGenerateColumns = false;
        dgvLinks.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        dgvLinks.AllowUserToAddRows = false;
        dgvLinks.AllowUserToDeleteRows = false;
        dgvLinks.ReadOnly = true;
        dgvLinks.RowHeadersVisible = false;
        dgvLinks.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvLinks.MultiSelect = false;
        dgvLinks.MinimumSize = new Size(0, 160);
        dgvLinks.AccessibleName = "قائمة البيانات — لم يتم تحميل بيانات";
        dgvLinksColAccount.Name = "dgvLinksColAccount";
        dgvLinksColAccount.HeaderText = "الحساب";
        dgvLinksColAccount.MinimumWidth = 90;
        dgvLinksColAccount.FillWeight = 100F;
        dgvLinksColAccount.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLinks.Columns.Add(dgvLinksColAccount);
        dgvLinksColTarget.Name = "dgvLinksColTarget";
        dgvLinksColTarget.HeaderText = "مركز التكلفة";
        dgvLinksColTarget.MinimumWidth = 90;
        dgvLinksColTarget.FillWeight = 100F;
        dgvLinksColTarget.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLinks.Columns.Add(dgvLinksColTarget);
        dgvLinksColBranch.Name = "dgvLinksColBranch";
        dgvLinksColBranch.HeaderText = "الفرع";
        dgvLinksColBranch.MinimumWidth = 90;
        dgvLinksColBranch.FillWeight = 100F;
        dgvLinksColBranch.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLinks.Columns.Add(dgvLinksColBranch);
        dgvLinksColActive.Name = "dgvLinksColActive";
        dgvLinksColActive.HeaderText = "الحالة";
        dgvLinksColActive.MinimumWidth = 90;
        dgvLinksColActive.FillWeight = 100F;
        dgvLinksColActive.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvLinks.Columns.Add(dgvLinksColActive);
        Links.Controls.Add(dgvLinks);
        Links.SetCellPosition(dgvLinks, new TableLayoutPanelCellPosition(0, 1));
        tpLinks.Controls.Add(Links);
        tpNotes.Name = "tpNotes";
        tpNotes.Text = "الملاحظات";
        tpNotes.Padding = new Padding(12);
        tpNotes.AutoScroll = true;
        tpNotes.BackColor = Color.White;
        tabMain.TabPages.Add(tpNotes);
        txtNotes.Name = "txtNotes";
        txtNotes.Dock = DockStyle.Fill;
        txtNotes.Multiline = true;
        txtNotes.ScrollBars = ScrollBars.Vertical;
        txtNotes.MaxLength = 4000;
        txtNotes.AccessibleName = "الملاحظات";
        tpNotes.Controls.Add(txtNotes);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 10F);
        BackColor = Color.White;
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1120, 720);
        MinimumSize = new Size(936, 600);
        Name = "UcAccountCostCenterLinking";
        Text = "ربط الحسابات بالمراكز";
        Tag = "ONYX:SCREEN-0093";
        Controls.Add(mainLayout);
        tpNotes.ResumeLayout(false);
        tpNotes.PerformLayout();
        LinksFields.ResumeLayout(false);
        LinksFields.PerformLayout();
        Links.ResumeLayout(false);
        Links.PerformLayout();
        tpLinks.ResumeLayout(false);
        tpLinks.PerformLayout();
        tabMain.ResumeLayout(false);
        tabMain.PerformLayout();
        pnlActions.ResumeLayout(false);
        pnlActions.PerformLayout();
        mainLayout.ResumeLayout(false);
        mainLayout.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)dgvLinks).EndInit();
        ResumeLayout(false);
    }

    private TableLayoutPanel mainLayout = null!;
    private FlowLayoutPanel pnlActions = null!;
    private Button btnNew = null!;
    private Button btnSave = null!;
    private Button btnEdit = null!;
    private Button btnDelete = null!;
    private Button btnRefresh = null!;
    private Button btnClose = null!;
    private Label lblPreview = null!;
    private TabControl tabMain = null!;
    private TabPage tpLinks = null!;
    private TableLayoutPanel Links = null!;
    private TableLayoutPanel LinksFields = null!;
    private Label lblcmbCompany = null!;
    private ComboBox cmbCompany = null!;
    private Label lblcmbAccount = null!;
    private ComboBox cmbAccount = null!;
    private Label lblcmbTarget = null!;
    private ComboBox cmbTarget = null!;
    private Label lblcmbBranch = null!;
    private ComboBox cmbBranch = null!;
    private Label lblchkLinkActive = null!;
    private CheckBox chkLinkActive = null!;
    private DataGridView dgvLinks = null!;
    private DataGridViewTextBoxColumn dgvLinksColAccount = null!;
    private DataGridViewTextBoxColumn dgvLinksColTarget = null!;
    private DataGridViewTextBoxColumn dgvLinksColBranch = null!;
    private DataGridViewTextBoxColumn dgvLinksColActive = null!;
    private TabPage tpNotes = null!;
    private TextBox txtNotes = null!;
}
