using System.Drawing;
using System.Windows.Forms;

namespace TransportERP.EmptyForms;

partial class UcChartOfAccounts
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private FlowLayoutPanel designerHiddenCommands = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private System.ComponentModel.IContainer? components;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerHiddenCommands = new FlowLayoutPanel();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandPrint = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        pnlHeader = new Panel();
        lblTitle = new Label();
        tlpAuditInfo = new TableLayoutPanel();
        txtCurrentRecordNo = new TextBox();
        btnFirst = new Button();
        btnPrevious = new Button();
        btnNext = new Button();
        btnLast = new Button();
        btnSearch = new Button();
        lblCreatedBy = new Label();
        lblCreatedAt = new Label();
        lblModifiedBy = new Label();
        lblModifiedAt = new Label();
        lblEditCount = new Label();
        lblLastPrintedAt = new Label();
        lblPrintCount = new Label();
        mainLayout = new TableLayoutPanel();
        pnlActions = new FlowLayoutPanel();
        btnNew = new Button();
        btnSave = new Button();
        btnEdit = new Button();
        btnRefresh = new Button();
        btnClose = new Button();
        lblPreview = new Label();
        btnDisable = new Button();
        btnMove = new Button();
        chartLayout = new TableLayoutPanel();
        contentViewport = new Panel();
        tvAccounts = new TreeView();
        detailLayout = new TableLayoutPanel();
        AccountFields = new TableLayoutPanel();
        searchFields = new TableLayoutPanel();
        dgvAccounts = new DataGridView();
        lblcmbCompany = new Label();
        cmbCompany = new ComboBox();
        lblcmbParentAccount = new Label();
        cmbParentAccount = new ComboBox();
        lblcmbAccountGroup = new Label();
        cmbAccountGroup = new ComboBox();
        lblcmbAccountType = new Label();
        cmbAccountType = new ComboBox();
        lbltxtAccountCode = new Label();
        txtAccountCode = new TextBox();
        lbltxtAccountNameAr = new Label();
        txtAccountNameAr = new TextBox();
        lbltxtAccountNameEn = new Label();
        txtAccountNameEn = new TextBox();
        lblchkIsPostable = new Label();
        chkIsPostable = new CheckBox();
        lbltxtAccountStatus = new Label();
        txtAccountStatus = new TextBox();
        lbltxtSearch = new Label();
        txtSearch = new TextBox();
        lblcmbStatusFilter = new Label();
        cmbStatusFilter = new ComboBox();
        lblcmbCompanyFilter = new Label();
        cmbCompanyFilter = new ComboBox();
        lblcmbParentFilter = new Label();
        cmbParentFilter = new ComboBox();
        lblcmbGroupFilter = new Label();
        cmbGroupFilter = new ComboBox();
        lblcmbTypeFilter = new Label();
        cmbTypeFilter = new ComboBox();
        lblcmbPostableFilter = new Label();
        cmbPostableFilter = new ComboBox();
        colCode = new DataGridViewTextBoxColumn();
        colArabicName = new DataGridViewTextBoxColumn();
        colEnglishName = new DataGridViewTextBoxColumn();
        colGroup = new DataGridViewTextBoxColumn();
        colType = new DataGridViewTextBoxColumn();
        colIsPostable = new DataGridViewCheckBoxColumn();
        colStatus = new DataGridViewTextBoxColumn();
        SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)dgvAccounts).BeginInit();
        pnlHeader.SuspendLayout();
        tlpAuditInfo.SuspendLayout();
        mainLayout.SuspendLayout();
        pnlActions.SuspendLayout();
        chartLayout.SuspendLayout();
        detailLayout.SuspendLayout();
        AccountFields.SuspendLayout();
        searchFields.SuspendLayout();
        pnlHeader.Name = "pnlHeader";
        lblTitle.Name = "lblTitle";
        tlpAuditInfo.Name = "tlpAuditInfo";
        txtCurrentRecordNo.Name = "txtCurrentRecordNo";
        btnFirst.Name = "btnFirst";
        btnPrevious.Name = "btnPrevious";
        btnNext.Name = "btnNext";
        btnLast.Name = "btnLast";
        btnSearch.Name = "btnSearch";
        lblCreatedBy.Name = "lblCreatedBy";
        lblCreatedAt.Name = "lblCreatedAt";
        lblModifiedBy.Name = "lblModifiedBy";
        lblModifiedAt.Name = "lblModifiedAt";
        lblEditCount.Name = "lblEditCount";
        lblLastPrintedAt.Name = "lblLastPrintedAt";
        lblPrintCount.Name = "lblPrintCount";
        mainLayout.Name = "mainLayout";
        pnlActions.Name = "pnlActions";
        btnNew.Name = "btnNew";
        btnSave.Name = "btnSave";
        btnEdit.Name = "btnEdit";
        btnRefresh.Name = "btnRefresh";
        btnClose.Name = "btnClose";
        lblPreview.Name = "lblPreview";
        btnDisable.Name = "btnDisable";
        btnMove.Name = "btnMove";
        chartLayout.Name = "chartLayout";
        tvAccounts.Name = "tvAccounts";
        detailLayout.Name = "detailLayout";
        AccountFields.Name = "AccountFields";
        searchFields.Name = "searchFields";
        dgvAccounts.Name = "dgvAccounts";
        lblcmbCompany.Name = "lblcmbCompany";
        cmbCompany.Name = "cmbCompany";
        lblcmbParentAccount.Name = "lblcmbParentAccount";
        cmbParentAccount.Name = "cmbParentAccount";
        lblcmbAccountGroup.Name = "lblcmbAccountGroup";
        cmbAccountGroup.Name = "cmbAccountGroup";
        lblcmbAccountType.Name = "lblcmbAccountType";
        cmbAccountType.Name = "cmbAccountType";
        lbltxtAccountCode.Name = "lbltxtAccountCode";
        txtAccountCode.Name = "txtAccountCode";
        lbltxtAccountNameAr.Name = "lbltxtAccountNameAr";
        txtAccountNameAr.Name = "txtAccountNameAr";
        lbltxtAccountNameEn.Name = "lbltxtAccountNameEn";
        txtAccountNameEn.Name = "txtAccountNameEn";
        lblchkIsPostable.Name = "lblchkIsPostable";
        chkIsPostable.Name = "chkIsPostable";
        lbltxtAccountStatus.Name = "lbltxtAccountStatus";
        txtAccountStatus.Name = "txtAccountStatus";
        lbltxtSearch.Name = "lbltxtSearch";
        txtSearch.Name = "txtSearch";
        lblcmbStatusFilter.Name = "lblcmbStatusFilter";
        cmbStatusFilter.Name = "cmbStatusFilter";
        lblcmbCompanyFilter.Name = "lblcmbCompanyFilter";
        cmbCompanyFilter.Name = "cmbCompanyFilter";
        lblcmbParentFilter.Name = "lblcmbParentFilter";
        cmbParentFilter.Name = "cmbParentFilter";
        lblcmbGroupFilter.Name = "lblcmbGroupFilter";
        cmbGroupFilter.Name = "cmbGroupFilter";
        lblcmbTypeFilter.Name = "lblcmbTypeFilter";
        cmbTypeFilter.Name = "cmbTypeFilter";
        lblcmbPostableFilter.Name = "lblcmbPostableFilter";
        cmbPostableFilter.Name = "cmbPostableFilter";
        colCode.Name = "colCode";
        colArabicName.Name = "colArabicName";
        colEnglishName.Name = "colEnglishName";
        colGroup.Name = "colGroup";
        colType.Name = "colType";
        colIsPostable.Name = "colIsPostable";
        colStatus.Name = "colStatus";
        mainLayout.Name = "mainLayout";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.Padding = new Padding(0);
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        pnlActions.Name = "pnlActions";
        pnlActions.Dock = DockStyle.Top;
        pnlActions.WrapContents = true;
        pnlActions.BackColor = Color.FromArgb(224, 224, 224);
        pnlActions.Padding = new Padding(5);
        pnlActions.Margin = new Padding(0);
        pnlActions.RightToLeft = RightToLeft.Yes;
        pnlActions.AutoScroll = false;
        pnlActions.FlowDirection = FlowDirection.LeftToRight;
        btnNew.Name = "btnNew";
        btnNew.Text = "جديد";
        btnNew.Size = new Size(70, 30);
        btnNew.FlatStyle = FlatStyle.Flat;
        btnNew.Font = new Font("Microsoft Sans Serif", 10F);
        btnNew.Margin = new Padding(4);
        btnNew.Enabled = false;
        btnNew.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnNew);
        btnSave.Name = "btnSave";
        btnSave.Text = "حفظ";
        btnSave.Size = new Size(70, 30);
        btnSave.FlatStyle = FlatStyle.Flat;
        btnSave.Font = new Font("Microsoft Sans Serif", 10F);
        btnSave.Margin = new Padding(4);
        btnSave.Enabled = false;
        btnSave.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnSave);
        btnEdit.Name = "btnEdit";
        btnEdit.Text = "تعديل";
        btnEdit.Size = new Size(70, 30);
        btnEdit.FlatStyle = FlatStyle.Flat;
        btnEdit.Font = new Font("Microsoft Sans Serif", 10F);
        btnEdit.Margin = new Padding(4);
        btnEdit.Enabled = false;
        btnEdit.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnEdit);
        btnRefresh.Name = "btnRefresh";
        btnRefresh.Text = "تحديث";
        btnRefresh.Size = new Size(70, 30);
        btnRefresh.FlatStyle = FlatStyle.Flat;
        btnRefresh.Font = new Font("Microsoft Sans Serif", 10F);
        btnRefresh.Margin = new Padding(4);
        btnRefresh.Enabled = false;
        btnRefresh.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnRefresh);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.Size = new Size(70, 30);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.Font = new Font("Microsoft Sans Serif", 10F);
        btnClose.Margin = new Padding(4);
        btnClose.Enabled = true;
        btnClose.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnClose);
        btnClose.Click += BtnClose_Click;
        btnFirst.Name = "btnFirst";
        btnFirst.Text = "الأول";
        btnFirst.Size = new Size(70, 30);
        btnFirst.Margin = new Padding(4);
        btnFirst.Font = new Font("Microsoft Sans Serif", 10F);
        btnFirst.FlatStyle = FlatStyle.Flat;
        btnFirst.Enabled = false;
        btnFirst.TabIndex = 6;
        btnFirst.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnFirst);
        btnPrevious.Name = "btnPrevious";
        btnPrevious.Text = "السابق";
        btnPrevious.Size = new Size(70, 30);
        btnPrevious.Margin = new Padding(4);
        btnPrevious.Font = new Font("Microsoft Sans Serif", 10F);
        btnPrevious.FlatStyle = FlatStyle.Flat;
        btnPrevious.Enabled = false;
        btnPrevious.TabIndex = 7;
        btnPrevious.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnPrevious);
        txtCurrentRecordNo.Name = "txtCurrentRecordNo";
        txtCurrentRecordNo.Size = new Size(62, 30);
        txtCurrentRecordNo.Margin = new Padding(4);
        txtCurrentRecordNo.Font = new Font("Microsoft Sans Serif", 10F);
        txtCurrentRecordNo.ReadOnly = true;
        txtCurrentRecordNo.TabStop = false;
        txtCurrentRecordNo.Text = "—";
        txtCurrentRecordNo.TextAlign = HorizontalAlignment.Center;
        txtCurrentRecordNo.AccessibleName = "رقم السجل الحالي";
        pnlActions.Controls.Add(txtCurrentRecordNo);
        btnNext.Name = "btnNext";
        btnNext.Text = "التالي";
        btnNext.Size = new Size(70, 30);
        btnNext.Margin = new Padding(4);
        btnNext.Font = new Font("Microsoft Sans Serif", 10F);
        btnNext.FlatStyle = FlatStyle.Flat;
        btnNext.Enabled = false;
        btnNext.TabIndex = 8;
        btnNext.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnNext);
        btnLast.Name = "btnLast";
        btnLast.Text = "الأخير";
        btnLast.Size = new Size(70, 30);
        btnLast.Margin = new Padding(4);
        btnLast.Font = new Font("Microsoft Sans Serif", 10F);
        btnLast.FlatStyle = FlatStyle.Flat;
        btnLast.Enabled = false;
        btnLast.TabIndex = 9;
        btnLast.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnLast);
        btnSearch.Name = "btnSearch";
        btnSearch.Text = "بحث";
        btnSearch.Size = new Size(70, 30);
        btnSearch.Margin = new Padding(4);
        btnSearch.Font = new Font("Microsoft Sans Serif", 10F);
        btnSearch.FlatStyle = FlatStyle.Flat;
        btnSearch.Enabled = false;
        btnSearch.TabIndex = 11;
        btnSearch.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnSearch);

        lblPreview.Name = "lblPreview";
        lblPreview.Text = "معاينة التصميم — لم تُحمّل الحسابات؛ الحفظ والنقل والإيقاف غير متصلة";
        lblPreview.Dock = DockStyle.Fill;
        lblPreview.TextAlign = ContentAlignment.MiddleLeft;
        lblPreview.ForeColor = Color.DimGray;
        lblPreview.Padding = new Padding(8, 0, 8, 0);
        lblPreview.BackColor = Color.FromArgb(248, 250, 252);
        pnlHeader.Name = "pnlHeader";
        pnlHeader.Dock = DockStyle.Fill;
        pnlHeader.Margin = new Padding(0);
        pnlHeader.BackColor = Color.FromArgb(224, 224, 224);
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "دليل الحسابات";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Right;
        lblTitle.Font = new Font("Segoe UI", 16F);
        lblTitle.BackColor = Color.FromArgb(192, 192, 255);
        lblTitle.Padding = new Padding(8, 0, 15, 0);
        lblTitle.RightToLeft = RightToLeft.Yes;
        lblTitle.TextAlign = ContentAlignment.MiddleCenter;
        lblTitle.TabStop = false;
        pnlHeader.Controls.Add(designerCommandBar);
        pnlHeader.Controls.Add(lblTitle);
        mainLayout.Controls.Add(pnlHeader, 0, 0);
        tlpAuditInfo.Name = "tlpAuditInfo";
        tlpAuditInfo.AccessibleName = "بيانات الإنشاء والتعديل والطباعة";
        tlpAuditInfo.Dock = DockStyle.Fill;
        tlpAuditInfo.Margin = new Padding(0);
        tlpAuditInfo.Padding = new Padding(8);
        tlpAuditInfo.RightToLeft = RightToLeft.Yes;
        tlpAuditInfo.ColumnCount = 7;
        tlpAuditInfo.RowCount = 1;
        tlpAuditInfo.GrowStyle = TableLayoutPanelGrowStyle.FixedSize;
        tlpAuditInfo.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tlpAuditInfo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 14F));
        tlpAuditInfo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16F));
        tlpAuditInfo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 14F));
        tlpAuditInfo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16F));
        tlpAuditInfo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 12F));
        tlpAuditInfo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16F));
        tlpAuditInfo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 12F));
        lblCreatedBy.Name = "lblCreatedBy";
        lblCreatedBy.Text = "أنشأ بواسطة: —";
        lblCreatedBy.Dock = DockStyle.Fill;
        lblCreatedBy.AutoSize = false;
        lblCreatedBy.TextAlign = ContentAlignment.MiddleRight;
        lblCreatedBy.Font = new Font("Microsoft Sans Serif", 9F);
        lblCreatedBy.BackColor = Color.FromArgb(192, 255, 255);
        lblCreatedBy.TabStop = false;
        tlpAuditInfo.Controls.Add(lblCreatedBy, 0, 0);
        lblCreatedAt.Name = "lblCreatedAt";
        lblCreatedAt.Text = "تاريخ الإنشاء: —";
        lblCreatedAt.Dock = DockStyle.Fill;
        lblCreatedAt.AutoSize = false;
        lblCreatedAt.TextAlign = ContentAlignment.MiddleRight;
        lblCreatedAt.Font = new Font("Microsoft Sans Serif", 9F);
        lblCreatedAt.BackColor = Color.FromArgb(192, 255, 255);
        lblCreatedAt.TabStop = false;
        tlpAuditInfo.Controls.Add(lblCreatedAt, 1, 0);
        lblModifiedBy.Name = "lblModifiedBy";
        lblModifiedBy.Text = "عدّل بواسطة: —";
        lblModifiedBy.Dock = DockStyle.Fill;
        lblModifiedBy.AutoSize = false;
        lblModifiedBy.TextAlign = ContentAlignment.MiddleRight;
        lblModifiedBy.Font = new Font("Microsoft Sans Serif", 9F);
        lblModifiedBy.BackColor = Color.FromArgb(192, 255, 255);
        lblModifiedBy.TabStop = false;
        tlpAuditInfo.Controls.Add(lblModifiedBy, 2, 0);
        lblModifiedAt.Name = "lblModifiedAt";
        lblModifiedAt.Text = "تاريخ التعديل: —";
        lblModifiedAt.Dock = DockStyle.Fill;
        lblModifiedAt.AutoSize = false;
        lblModifiedAt.TextAlign = ContentAlignment.MiddleRight;
        lblModifiedAt.Font = new Font("Microsoft Sans Serif", 9F);
        lblModifiedAt.BackColor = Color.FromArgb(192, 255, 255);
        lblModifiedAt.TabStop = false;
        tlpAuditInfo.Controls.Add(lblModifiedAt, 3, 0);
        lblEditCount.Name = "lblEditCount";
        lblEditCount.Text = "عدد التعديلات: —";
        lblEditCount.Dock = DockStyle.Fill;
        lblEditCount.AutoSize = false;
        lblEditCount.TextAlign = ContentAlignment.MiddleRight;
        lblEditCount.Font = new Font("Microsoft Sans Serif", 9F);
        lblEditCount.BackColor = Color.FromArgb(192, 255, 255);
        lblEditCount.TabStop = false;
        tlpAuditInfo.Controls.Add(lblEditCount, 4, 0);
        lblLastPrintedAt.Name = "lblLastPrintedAt";
        lblLastPrintedAt.Text = "آخر طباعة: —";
        lblLastPrintedAt.Dock = DockStyle.Fill;
        lblLastPrintedAt.AutoSize = false;
        lblLastPrintedAt.TextAlign = ContentAlignment.MiddleRight;
        lblLastPrintedAt.Font = new Font("Microsoft Sans Serif", 9F);
        lblLastPrintedAt.BackColor = Color.FromArgb(192, 255, 255);
        lblLastPrintedAt.TabStop = false;
        tlpAuditInfo.Controls.Add(lblLastPrintedAt, 5, 0);
        lblPrintCount.Name = "lblPrintCount";
        lblPrintCount.Text = "عدد مرات الطباعة: —";
        lblPrintCount.Dock = DockStyle.Fill;
        lblPrintCount.AutoSize = false;
        lblPrintCount.TextAlign = ContentAlignment.MiddleRight;
        lblPrintCount.Font = new Font("Microsoft Sans Serif", 9F);
        lblPrintCount.BackColor = Color.FromArgb(192, 255, 255);
        lblPrintCount.TabStop = false;
        tlpAuditInfo.Controls.Add(lblPrintCount, 6, 0);
        mainLayout.Controls.Add(tlpAuditInfo, 0, 3);
        mainLayout.Controls.Add(lblPreview, 0, 2);
        btnDisable.Text = "إيقاف";
        btnDisable.Dock = DockStyle.None;
        btnDisable.AutoSize = true;
        btnDisable.Margin = new Padding(4);
        btnDisable.BackColor = Color.FromArgb(224, 224, 224);
        btnDisable.Enabled = false;
        pnlActions.Controls.Add(btnDisable);
        btnMove.Text = "نقل الحساب";
        btnMove.Dock = DockStyle.None;
        btnMove.AutoSize = true;
        btnMove.Margin = new Padding(4);
        btnMove.BackColor = Color.FromArgb(224, 224, 224);
        btnMove.Enabled = false;
        pnlActions.Controls.Add(btnMove);
        pnlHeader.AutoSize = true;
        pnlHeader.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlActions.AutoSize = true;
        pnlActions.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        chartLayout.Dock = DockStyle.Fill;
        chartLayout.ColumnCount = 2;
        chartLayout.RowCount = 1;
        chartLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 240F));
        chartLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        chartLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tvAccounts.Dock = DockStyle.Fill;
        tvAccounts.RightToLeft = RightToLeft.Yes;
        tvAccounts.RightToLeftLayout = true;
        tvAccounts.HideSelection = false;
        tvAccounts.AccessibleName = "شجرة دليل الحسابات — لم يتم تحميل بيانات";
        detailLayout.Dock = DockStyle.Fill;
        detailLayout.ColumnCount = 1;
        detailLayout.RowCount = 3;
        detailLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        chartLayout.Controls.Add(tvAccounts, 0, 0);
        chartLayout.Controls.Add(detailLayout, 1, 0);
        contentViewport.Name = "contentViewport";
        contentViewport.Dock = DockStyle.Fill;
        contentViewport.AutoScroll = true;
        contentViewport.Margin = Padding.Empty;
        contentViewport.TabIndex = 1;
        chartLayout.MinimumSize = new Size(900, 620);
        contentViewport.Controls.Add(chartLayout);
        mainLayout.Controls.Add(contentViewport, 0, 1);
        AccountFields.Dock = DockStyle.Top;
        AccountFields.AutoSize = true;
        AccountFields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        AccountFields.ColumnCount = 4;
        AccountFields.RowCount = 5;
        AccountFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 145F));
        AccountFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        AccountFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 145F));
        AccountFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        AccountFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        AccountFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        AccountFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        AccountFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        AccountFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        searchFields.Dock = DockStyle.Top;
        searchFields.AutoSize = true;
        searchFields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        searchFields.ColumnCount = 4;
        searchFields.RowCount = 4;
        searchFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 145F));
        searchFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 145F));
        searchFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        searchFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        searchFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        searchFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        lblcmbCompany.Text = "الشركة *";
        lblcmbCompany.Dock = DockStyle.Fill;
        lblcmbCompany.TextAlign = ContentAlignment.MiddleRight;
        lblcmbCompany.AutoEllipsis = true;
        cmbCompany.Dock = DockStyle.Fill;
        cmbCompany.AccessibleName = "الشركة";
        cmbCompany.TabIndex = 0;
        cmbCompany.Margin = new Padding(3);
        AccountFields.Controls.Add(lblcmbCompany, 0, 0);
        AccountFields.Controls.Add(cmbCompany, 1, 0);
        cmbCompany.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbCompany.BackColor = Color.FromArgb(255, 249, 219);
        lblcmbParentAccount.Text = "الحساب الأب";
        lblcmbParentAccount.Dock = DockStyle.Fill;
        lblcmbParentAccount.TextAlign = ContentAlignment.MiddleRight;
        lblcmbParentAccount.AutoEllipsis = true;
        cmbParentAccount.Dock = DockStyle.Fill;
        cmbParentAccount.AccessibleName = "الحساب الأب";
        cmbParentAccount.TabIndex = 1;
        cmbParentAccount.Margin = new Padding(3);
        AccountFields.Controls.Add(lblcmbParentAccount, 2, 0);
        AccountFields.Controls.Add(cmbParentAccount, 3, 0);
        cmbParentAccount.DropDownStyle = ComboBoxStyle.DropDownList;
        lblcmbAccountGroup.Text = "مجموعة الحساب *";
        lblcmbAccountGroup.Dock = DockStyle.Fill;
        lblcmbAccountGroup.TextAlign = ContentAlignment.MiddleRight;
        lblcmbAccountGroup.AutoEllipsis = true;
        cmbAccountGroup.Dock = DockStyle.Fill;
        cmbAccountGroup.AccessibleName = "مجموعة الحساب";
        cmbAccountGroup.TabIndex = 2;
        cmbAccountGroup.Margin = new Padding(3);
        AccountFields.Controls.Add(lblcmbAccountGroup, 0, 1);
        AccountFields.Controls.Add(cmbAccountGroup, 1, 1);
        cmbAccountGroup.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbAccountGroup.BackColor = Color.FromArgb(255, 249, 219);
        lblcmbAccountType.Text = "نوع الحساب *";
        lblcmbAccountType.Dock = DockStyle.Fill;
        lblcmbAccountType.TextAlign = ContentAlignment.MiddleRight;
        lblcmbAccountType.AutoEllipsis = true;
        cmbAccountType.Dock = DockStyle.Fill;
        cmbAccountType.AccessibleName = "نوع الحساب";
        cmbAccountType.TabIndex = 3;
        cmbAccountType.Margin = new Padding(3);
        AccountFields.Controls.Add(lblcmbAccountType, 2, 1);
        AccountFields.Controls.Add(cmbAccountType, 3, 1);
        cmbAccountType.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbAccountType.BackColor = Color.FromArgb(255, 249, 219);
        lbltxtAccountCode.Text = "رمز الحساب *";
        lbltxtAccountCode.Dock = DockStyle.Fill;
        lbltxtAccountCode.TextAlign = ContentAlignment.MiddleRight;
        lbltxtAccountCode.AutoEllipsis = true;
        txtAccountCode.Dock = DockStyle.Fill;
        txtAccountCode.AccessibleName = "رمز الحساب";
        txtAccountCode.TabIndex = 4;
        txtAccountCode.Margin = new Padding(3);
        AccountFields.Controls.Add(lbltxtAccountCode, 0, 2);
        AccountFields.Controls.Add(txtAccountCode, 1, 2);
        txtAccountCode.BackColor = Color.FromArgb(255, 249, 219);
        txtAccountCode.RightToLeft = RightToLeft.No;
        txtAccountCode.TextAlign = HorizontalAlignment.Left;
        lbltxtAccountNameAr.Text = "اسم الحساب العربي *";
        lbltxtAccountNameAr.Dock = DockStyle.Fill;
        lbltxtAccountNameAr.TextAlign = ContentAlignment.MiddleRight;
        lbltxtAccountNameAr.AutoEllipsis = true;
        txtAccountNameAr.Dock = DockStyle.Fill;
        txtAccountNameAr.AccessibleName = "اسم الحساب العربي";
        txtAccountNameAr.TabIndex = 5;
        txtAccountNameAr.Margin = new Padding(3);
        AccountFields.Controls.Add(lbltxtAccountNameAr, 2, 2);
        AccountFields.Controls.Add(txtAccountNameAr, 3, 2);
        txtAccountNameAr.BackColor = Color.FromArgb(255, 249, 219);
        lbltxtAccountNameEn.Text = "اسم الحساب الإنجليزي";
        lbltxtAccountNameEn.Dock = DockStyle.Fill;
        lbltxtAccountNameEn.TextAlign = ContentAlignment.MiddleRight;
        lbltxtAccountNameEn.AutoEllipsis = true;
        txtAccountNameEn.Dock = DockStyle.Fill;
        txtAccountNameEn.AccessibleName = "اسم الحساب الإنجليزي";
        txtAccountNameEn.TabIndex = 6;
        txtAccountNameEn.Margin = new Padding(3);
        AccountFields.Controls.Add(lbltxtAccountNameEn, 0, 3);
        AccountFields.Controls.Add(txtAccountNameEn, 1, 3);
        txtAccountNameEn.RightToLeft = RightToLeft.No;
        txtAccountNameEn.TextAlign = HorizontalAlignment.Left;
        lblchkIsPostable.Text = "قابل للترحيل *";
        lblchkIsPostable.Dock = DockStyle.Fill;
        lblchkIsPostable.TextAlign = ContentAlignment.MiddleRight;
        lblchkIsPostable.AutoEllipsis = true;
        chkIsPostable.Dock = DockStyle.Fill;
        chkIsPostable.AccessibleName = "قابل للترحيل";
        chkIsPostable.TabIndex = 7;
        chkIsPostable.Margin = new Padding(3);
        AccountFields.Controls.Add(lblchkIsPostable, 2, 3);
        AccountFields.Controls.Add(chkIsPostable, 3, 3);
        chkIsPostable.BackColor = Color.FromArgb(255, 249, 219);
        lbltxtAccountStatus.Text = "الحالة";
        lbltxtAccountStatus.Dock = DockStyle.Fill;
        lbltxtAccountStatus.TextAlign = ContentAlignment.MiddleRight;
        lbltxtAccountStatus.AutoEllipsis = true;
        txtAccountStatus.Dock = DockStyle.Fill;
        txtAccountStatus.AccessibleName = "الحالة";
        txtAccountStatus.TabIndex = 8;
        txtAccountStatus.Margin = new Padding(3);
        AccountFields.Controls.Add(lbltxtAccountStatus, 0, 4);
        AccountFields.Controls.Add(txtAccountStatus, 1, 4);
        cmbCompany.Tag = "CompanyId: Create only";
        cmbParentAccount.Tag = "ParentAccountId: Create only; use Move after creation";
        txtAccountStatus.ReadOnly = true;
        txtAccountStatus.TabStop = false;
        txtAccountStatus.Text = "—";
        txtAccountStatus.BackColor = SystemColors.Control;
        lbltxtSearch.Text = "بحث بالرمز أو الاسم";
        lbltxtSearch.Dock = DockStyle.Fill;
        lbltxtSearch.TextAlign = ContentAlignment.MiddleRight;
        lbltxtSearch.AutoEllipsis = true;
        txtSearch.Dock = DockStyle.Fill;
        txtSearch.AccessibleName = "بحث بالرمز أو الاسم";
        txtSearch.TabIndex = 0;
        searchFields.Controls.Add(lbltxtSearch, 0, 0);
        searchFields.Controls.Add(txtSearch, 1, 0);
        lblcmbStatusFilter.Text = "تصفية الحالة";
        lblcmbStatusFilter.Dock = DockStyle.Fill;
        lblcmbStatusFilter.TextAlign = ContentAlignment.MiddleRight;
        lblcmbStatusFilter.AutoEllipsis = true;
        cmbStatusFilter.Dock = DockStyle.Fill;
        cmbStatusFilter.AccessibleName = "تصفية الحالة";
        cmbStatusFilter.TabIndex = 1;
        searchFields.Controls.Add(lblcmbStatusFilter, 2, 0);
        searchFields.Controls.Add(cmbStatusFilter, 3, 0);
        cmbStatusFilter.DropDownStyle = ComboBoxStyle.DropDownList;
        lblcmbCompanyFilter.Text = "تصفية الشركة";
        lblcmbCompanyFilter.Dock = DockStyle.Fill;
        lblcmbCompanyFilter.TextAlign = ContentAlignment.MiddleRight;
        lblcmbCompanyFilter.AutoEllipsis = true;
        cmbCompanyFilter.Dock = DockStyle.Fill;
        cmbCompanyFilter.AccessibleName = "تصفية الشركة";
        cmbCompanyFilter.TabIndex = 2;
        searchFields.Controls.Add(lblcmbCompanyFilter, 0, 1);
        searchFields.Controls.Add(cmbCompanyFilter, 1, 1);
        cmbCompanyFilter.DropDownStyle = ComboBoxStyle.DropDownList;
        lblcmbParentFilter.Text = "تصفية الحساب الأب";
        lblcmbParentFilter.Dock = DockStyle.Fill;
        lblcmbParentFilter.TextAlign = ContentAlignment.MiddleRight;
        lblcmbParentFilter.AutoEllipsis = true;
        cmbParentFilter.Dock = DockStyle.Fill;
        cmbParentFilter.AccessibleName = "تصفية الحساب الأب";
        cmbParentFilter.TabIndex = 3;
        searchFields.Controls.Add(lblcmbParentFilter, 2, 1);
        searchFields.Controls.Add(cmbParentFilter, 3, 1);
        cmbParentFilter.DropDownStyle = ComboBoxStyle.DropDownList;
        lblcmbGroupFilter.Text = "تصفية المجموعة";
        lblcmbGroupFilter.Dock = DockStyle.Fill;
        lblcmbGroupFilter.TextAlign = ContentAlignment.MiddleRight;
        lblcmbGroupFilter.AutoEllipsis = true;
        cmbGroupFilter.Dock = DockStyle.Fill;
        cmbGroupFilter.AccessibleName = "تصفية المجموعة";
        cmbGroupFilter.TabIndex = 4;
        searchFields.Controls.Add(lblcmbGroupFilter, 0, 2);
        searchFields.Controls.Add(cmbGroupFilter, 1, 2);
        cmbGroupFilter.DropDownStyle = ComboBoxStyle.DropDownList;
        lblcmbTypeFilter.Text = "تصفية النوع";
        lblcmbTypeFilter.Dock = DockStyle.Fill;
        lblcmbTypeFilter.TextAlign = ContentAlignment.MiddleRight;
        lblcmbTypeFilter.AutoEllipsis = true;
        cmbTypeFilter.Dock = DockStyle.Fill;
        cmbTypeFilter.AccessibleName = "تصفية النوع";
        cmbTypeFilter.TabIndex = 5;
        searchFields.Controls.Add(lblcmbTypeFilter, 2, 2);
        searchFields.Controls.Add(cmbTypeFilter, 3, 2);
        cmbTypeFilter.DropDownStyle = ComboBoxStyle.DropDownList;
        lblcmbPostableFilter.Text = "تصفية قابلية الترحيل";
        lblcmbPostableFilter.Dock = DockStyle.Fill;
        lblcmbPostableFilter.TextAlign = ContentAlignment.MiddleRight;
        lblcmbPostableFilter.AutoEllipsis = true;
        cmbPostableFilter.Dock = DockStyle.Fill;
        cmbPostableFilter.AccessibleName = "تصفية قابلية الترحيل";
        cmbPostableFilter.TabIndex = 6;
        searchFields.Controls.Add(lblcmbPostableFilter, 0, 3);
        searchFields.Controls.Add(cmbPostableFilter, 1, 3);
        cmbPostableFilter.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbStatusFilter.Items.AddRange(new object[] { "الكل", "نشط", "موقوف" });
        cmbStatusFilter.SelectedIndex = 0;
        cmbPostableFilter.Items.AddRange(new object[] { "الكل", "نعم", "لا" });
        cmbPostableFilter.SelectedIndex = 0;
        dgvAccounts.Dock = DockStyle.Fill;
        dgvAccounts.AutoGenerateColumns = false;
        dgvAccounts.AllowUserToAddRows = false;
        dgvAccounts.AllowUserToDeleteRows = false;
        dgvAccounts.ReadOnly = true;
        dgvAccounts.MultiSelect = false;
        dgvAccounts.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvAccounts.RowHeadersVisible = false;
        dgvAccounts.BackgroundColor = Color.White;
        dgvAccounts.AccessibleName = "قائمة الحسابات — لم تُحمّل بيانات";
        colCode.HeaderText = "الرمز";
        colCode.ReadOnly = true;
        colCode.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colCode.MinimumWidth = 70;
        dgvAccounts.Columns.Add(colCode);
        colArabicName.HeaderText = "الاسم العربي";
        colArabicName.ReadOnly = true;
        colArabicName.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colArabicName.MinimumWidth = 70;
        dgvAccounts.Columns.Add(colArabicName);
        colEnglishName.HeaderText = "الاسم الإنجليزي";
        colEnglishName.ReadOnly = true;
        colEnglishName.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colEnglishName.MinimumWidth = 70;
        dgvAccounts.Columns.Add(colEnglishName);
        colGroup.HeaderText = "المجموعة";
        colGroup.ReadOnly = true;
        colGroup.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colGroup.MinimumWidth = 70;
        dgvAccounts.Columns.Add(colGroup);
        colType.HeaderText = "النوع";
        colType.ReadOnly = true;
        colType.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colType.MinimumWidth = 70;
        dgvAccounts.Columns.Add(colType);
        colIsPostable.HeaderText = "قابل للترحيل";
        colIsPostable.ReadOnly = true;
        colIsPostable.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colIsPostable.MinimumWidth = 70;
        dgvAccounts.Columns.Add(colIsPostable);
        colStatus.HeaderText = "الحالة";
        colStatus.ReadOnly = true;
        colStatus.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
        colStatus.MinimumWidth = 70;
        dgvAccounts.Columns.Add(colStatus);
        detailLayout.Controls.Add(searchFields, 0, 0);
        detailLayout.Controls.Add(AccountFields, 0, 1);
        detailLayout.Controls.Add(dgvAccounts, 0, 2);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 10F);
        BackColor = Color.FromArgb(248, 250, 252);
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1200, 900);
        Name = "UcChartOfAccounts";
        Text = "دليل الحسابات";
        Tag = "04.01.01";
        Controls.Add(mainLayout);
        searchFields.ResumeLayout(false);
        searchFields.PerformLayout();
        AccountFields.ResumeLayout(false);
        AccountFields.PerformLayout();
        detailLayout.ResumeLayout(false);
        detailLayout.PerformLayout();
        chartLayout.ResumeLayout(false);
        chartLayout.PerformLayout();
        pnlActions.ResumeLayout(false);
        pnlActions.PerformLayout();
        mainLayout.ResumeLayout(false);
        mainLayout.PerformLayout();
        tlpAuditInfo.ResumeLayout(false);
        tlpAuditInfo.PerformLayout();
        pnlHeader.ResumeLayout(false);
        pnlHeader.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)dgvAccounts).EndInit();
        ResumeLayout(false);
        PerformLayout();
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.Margin = new Padding(0);
        designerCommandBar.RightToLeft = RightToLeft.Yes;
        designerCommandBar.Controls.Add(pnlActions);
        pnlActions.Dock = DockStyle.Fill;
        pnlActions.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerHiddenCommands.Name = "designerHiddenCommands";
        designerHiddenCommands.Visible = false;
        designerCommandBar.Controls.Add(designerHiddenCommands);
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = false;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = false;
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = false;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        designerCommandBar.SetCommandRole(btnNew, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        designerCommandBar.SetCommandRole(btnEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        designerHiddenCommands.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.AutoSize = false;
        standardCommandCancel.Dock = DockStyle.None;
        standardCommandCancel.MinimumSize = Size.Empty;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandCancel.Text = "";
        designerHiddenCommands.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        designerCommandBar.SetCommandRole(btnSearch, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        designerCommandBar.SetCommandRole(btnLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        designerCommandBar.SetCommandRole(btnNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        designerCommandBar.SetCommandRole(btnPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        designerCommandBar.SetCommandRole(btnFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        designerCommandBar.SetCommandRole(btnSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        designerHiddenCommands.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        designerCommandBar.SetCommandRole(btnRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        designerHiddenCommands.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        designerHiddenCommands.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        designerHiddenCommands.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        tlpAuditInfo.Visible = false;
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}

    private Panel pnlHeader = null!;
    private Label lblTitle = null!;
    private TableLayoutPanel tlpAuditInfo = null!;
    private TextBox txtCurrentRecordNo = null!;
    private Button btnFirst = null!;
    private Button btnPrevious = null!;
    private Button btnNext = null!;
    private Button btnLast = null!;
    private Button btnSearch = null!;
    private Label lblCreatedBy = null!;
    private Label lblCreatedAt = null!;
    private Label lblModifiedBy = null!;
    private Label lblModifiedAt = null!;
    private Label lblEditCount = null!;
    private Label lblLastPrintedAt = null!;
    private Label lblPrintCount = null!;
    private TableLayoutPanel mainLayout = null!;
    private FlowLayoutPanel pnlActions = null!;
    private Button btnNew = null!;
    private Button btnSave = null!;
    private Button btnEdit = null!;
    private Button btnRefresh = null!;
    private Button btnClose = null!;
    private Label lblPreview = null!;
    private Button btnDisable = null!;
    private Button btnMove = null!;
    private TableLayoutPanel chartLayout = null!;
    private Panel contentViewport = null!;
    private TreeView tvAccounts = null!;
    private TableLayoutPanel detailLayout = null!;
    private TableLayoutPanel AccountFields = null!;
    private TableLayoutPanel searchFields = null!;
    private DataGridView dgvAccounts = null!;
    private Label lblcmbCompany = null!;
    private ComboBox cmbCompany = null!;
    private Label lblcmbParentAccount = null!;
    private ComboBox cmbParentAccount = null!;
    private Label lblcmbAccountGroup = null!;
    private ComboBox cmbAccountGroup = null!;
    private Label lblcmbAccountType = null!;
    private ComboBox cmbAccountType = null!;
    private Label lbltxtAccountCode = null!;
    private TextBox txtAccountCode = null!;
    private Label lbltxtAccountNameAr = null!;
    private TextBox txtAccountNameAr = null!;
    private Label lbltxtAccountNameEn = null!;
    private TextBox txtAccountNameEn = null!;
    private Label lblchkIsPostable = null!;
    private CheckBox chkIsPostable = null!;
    private Label lbltxtAccountStatus = null!;
    private TextBox txtAccountStatus = null!;
    private Label lbltxtSearch = null!;
    private TextBox txtSearch = null!;
    private Label lblcmbStatusFilter = null!;
    private ComboBox cmbStatusFilter = null!;
    private Label lblcmbCompanyFilter = null!;
    private ComboBox cmbCompanyFilter = null!;
    private Label lblcmbParentFilter = null!;
    private ComboBox cmbParentFilter = null!;
    private Label lblcmbGroupFilter = null!;
    private ComboBox cmbGroupFilter = null!;
    private Label lblcmbTypeFilter = null!;
    private ComboBox cmbTypeFilter = null!;
    private Label lblcmbPostableFilter = null!;
    private ComboBox cmbPostableFilter = null!;
    private DataGridViewTextBoxColumn colCode = null!;
    private DataGridViewTextBoxColumn colArabicName = null!;
    private DataGridViewTextBoxColumn colEnglishName = null!;
    private DataGridViewTextBoxColumn colGroup = null!;
    private DataGridViewTextBoxColumn colType = null!;
    private DataGridViewCheckBoxColumn colIsPostable = null!;
    private DataGridViewTextBoxColumn colStatus = null!;
}
