using System.Drawing;
using System.Windows.Forms;

namespace TransportERP.EmptyForms;

partial class UcChartOfAccounts
{
    private System.ComponentModel.IContainer? components;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        mainLayout = new TableLayoutPanel();
        pnlActions = new FlowLayoutPanel();
        btnNew = new Button();
        btnSave = new Button();
        btnEdit = new Button();
        btnDelete = new Button();
        btnRefresh = new Button();
        btnClose = new Button();
        lblPreview = new Label();
        tabMain = new TabControl();
        chartLayout = new TableLayoutPanel();
        tvAccounts = new TreeView();
        tpAccountDetails = new TabPage();
        AccountFields = new TableLayoutPanel();
        lblcmbCompany = new Label();
        cmbCompany = new ComboBox();
        lblcmbParentAccount = new Label();
        cmbParentAccount = new ComboBox();
        lbltxtAccountCode = new Label();
        txtAccountCode = new TextBox();
        lbltxtAccountNameAr = new Label();
        txtAccountNameAr = new TextBox();
        lbltxtAccountNameEn = new Label();
        txtAccountNameEn = new TextBox();
        lblcmbAccountType = new Label();
        cmbAccountType = new ComboBox();
        lblcmbNormalBalance = new Label();
        cmbNormalBalance = new ComboBox();
        lblcmbAccountGroup = new Label();
        cmbAccountGroup = new ComboBox();
        lblcmbAccountCategory = new Label();
        cmbAccountCategory = new ComboBox();
        lbltxtAccountLevel = new Label();
        txtAccountLevel = new TextBox();
        lblcmbAccountKind = new Label();
        cmbAccountKind = new ComboBox();
        lblcmbAccountStatus = new Label();
        cmbAccountStatus = new ComboBox();
        tpAccountCurrencies = new TabPage();
        dgvAccountCurrencies = new DataGridView();
        dgvAccountCurrenciesColCurrency = new DataGridViewTextBoxColumn();
        dgvAccountCurrenciesColDefault = new DataGridViewTextBoxColumn();
        dgvAccountCurrenciesColActive = new DataGridViewTextBoxColumn();
        tpAccountBranches = new TabPage();
        dgvAccountBranches = new DataGridView();
        dgvAccountBranchesColBranch = new DataGridViewTextBoxColumn();
        dgvAccountBranchesColActive = new DataGridViewTextBoxColumn();
        tpNotes = new TabPage();
        txtNotes = new TextBox();
        ((System.ComponentModel.ISupportInitialize)dgvAccountCurrencies).BeginInit();
        ((System.ComponentModel.ISupportInitialize)dgvAccountBranches).BeginInit();
        mainLayout.SuspendLayout();
        pnlActions.SuspendLayout();
        tabMain.SuspendLayout();
        chartLayout.SuspendLayout();
        tpAccountDetails.SuspendLayout();
        AccountFields.SuspendLayout();
        tpAccountCurrencies.SuspendLayout();
        tpAccountBranches.SuspendLayout();
        tpNotes.SuspendLayout();
        SuspendLayout();
        mainLayout.Name = "mainLayout";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 3;
        mainLayout.Padding = new Padding(12);
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
        pnlActions.Name = "pnlActions";
        pnlActions.Dock = DockStyle.Fill;
        pnlActions.WrapContents = false;
        pnlActions.AutoScroll = true;
        pnlActions.FlowDirection = FlowDirection.LeftToRight;
        btnNew.Name = "btnNew";
        btnNew.Text = "جديد";
        btnNew.Size = new Size(112, 36);
        btnNew.Margin = new Padding(4);
        btnNew.Enabled = false;
        btnNew.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnNew);
        btnSave.Name = "btnSave";
        btnSave.Text = "حفظ";
        btnSave.Size = new Size(112, 36);
        btnSave.Margin = new Padding(4);
        btnSave.Enabled = false;
        btnSave.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnSave);
        btnEdit.Name = "btnEdit";
        btnEdit.Text = "تعديل";
        btnEdit.Size = new Size(112, 36);
        btnEdit.Margin = new Padding(4);
        btnEdit.Enabled = false;
        btnEdit.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnEdit);
        btnDelete.Name = "btnDelete";
        btnDelete.Text = "حذف";
        btnDelete.Size = new Size(112, 36);
        btnDelete.Margin = new Padding(4);
        btnDelete.Enabled = false;
        btnDelete.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnDelete);
        btnRefresh.Name = "btnRefresh";
        btnRefresh.Text = "تحديث";
        btnRefresh.Size = new Size(112, 36);
        btnRefresh.Margin = new Padding(4);
        btnRefresh.Enabled = false;
        btnRefresh.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnRefresh);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.Size = new Size(112, 36);
        btnClose.Margin = new Padding(4);
        btnClose.Enabled = true;
        btnClose.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnClose);
        btnClose.Click += BtnClose_Click;
        lblPreview.Name = "lblPreview";
        lblPreview.Text = "وضع المعاينة — التغييرات غير محفوظة";
        lblPreview.Dock = DockStyle.Fill;
        lblPreview.TextAlign = ContentAlignment.MiddleLeft;
        lblPreview.ForeColor = Color.DimGray;
        mainLayout.Controls.Add(pnlActions, 0, 0);
        mainLayout.Controls.Add(lblPreview, 0, 2);
        tabMain.Name = "tabMain";
        tabMain.Dock = DockStyle.Fill;
        tabMain.RightToLeftLayout = true;
        tabMain.SizeMode = TabSizeMode.Normal;
        mainLayout.Controls.Add(tabMain, 0, 1);
        mainLayout.Controls.Remove(tabMain);
        chartLayout.Name = "chartLayout";
        chartLayout.Dock = DockStyle.Fill;
        chartLayout.ColumnCount = 2;
        chartLayout.RowCount = 1;
        chartLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 240F));
        chartLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        chartLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tvAccounts.Name = "tvAccounts";
        tvAccounts.Dock = DockStyle.Fill;
        tvAccounts.RightToLeftLayout = true;
        tvAccounts.HideSelection = false;
        tvAccounts.AccessibleName = "شجرة دليل الحسابات";
        chartLayout.Controls.Add(tvAccounts, 0, 0);
        chartLayout.Controls.Add(tabMain, 1, 0);
        mainLayout.Controls.Add(chartLayout, 0, 1);
        tpAccountDetails.Name = "tpAccountDetails";
        tpAccountDetails.Text = "بيانات الحساب";
        tpAccountDetails.Padding = new Padding(12);
        tpAccountDetails.AutoScroll = true;
        tpAccountDetails.BackColor = Color.White;
        tabMain.TabPages.Add(tpAccountDetails);
        AccountFields.Name = "AccountFields";
        AccountFields.Dock = DockStyle.Top;
        AccountFields.AutoSize = true;
        AccountFields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        AccountFields.ColumnCount = 2;
        AccountFields.RowCount = 12;
        AccountFields.Padding = new Padding(4);
        AccountFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        AccountFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100.0F));
        AccountFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        AccountFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        AccountFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        AccountFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        AccountFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        AccountFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        AccountFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        AccountFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        AccountFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        AccountFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        AccountFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        AccountFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        lblcmbCompany.Name = "lblcmbCompany";
        lblcmbCompany.Text = "الشركة *";
        lblcmbCompany.Dock = DockStyle.Fill;
        lblcmbCompany.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbCompany.AutoSize = false;
        lblcmbCompany.TabStop = false;
        cmbCompany.Name = "cmbCompany";
        cmbCompany.Dock = DockStyle.Fill;
        cmbCompany.Margin = new Padding(6, 10, 12, 10);
        cmbCompany.TabIndex = 0;
        cmbCompany.AccessibleName = "الشركة";
        cmbCompany.BackColor = Color.FromArgb(255, 250, 205);
        cmbCompany.DropDownStyle = ComboBoxStyle.DropDownList;
        AccountFields.Controls.Add(lblcmbCompany, 0, 0);
        AccountFields.Controls.Add(cmbCompany, 1, 0);
        lblcmbParentAccount.Name = "lblcmbParentAccount";
        lblcmbParentAccount.Text = "الحساب الأب";
        lblcmbParentAccount.Dock = DockStyle.Fill;
        lblcmbParentAccount.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbParentAccount.AutoSize = false;
        lblcmbParentAccount.TabStop = false;
        cmbParentAccount.Name = "cmbParentAccount";
        cmbParentAccount.Dock = DockStyle.Fill;
        cmbParentAccount.Margin = new Padding(6, 10, 12, 10);
        cmbParentAccount.TabIndex = 1;
        cmbParentAccount.AccessibleName = "الحساب الأب";
        cmbParentAccount.DropDownStyle = ComboBoxStyle.DropDownList;
        AccountFields.Controls.Add(lblcmbParentAccount, 0, 1);
        AccountFields.Controls.Add(cmbParentAccount, 1, 1);
        lbltxtAccountCode.Name = "lbltxtAccountCode";
        lbltxtAccountCode.Text = "رمز الحساب *";
        lbltxtAccountCode.Dock = DockStyle.Fill;
        lbltxtAccountCode.TextAlign = ContentAlignment.MiddleLeft;
        lbltxtAccountCode.AutoSize = false;
        lbltxtAccountCode.TabStop = false;
        txtAccountCode.Name = "txtAccountCode";
        txtAccountCode.Dock = DockStyle.Fill;
        txtAccountCode.Margin = new Padding(6, 10, 12, 10);
        txtAccountCode.TabIndex = 2;
        txtAccountCode.AccessibleName = "رمز الحساب";
        txtAccountCode.BackColor = Color.FromArgb(255, 250, 205);
        txtAccountCode.MaxLength = 30;
        AccountFields.Controls.Add(lbltxtAccountCode, 0, 2);
        AccountFields.Controls.Add(txtAccountCode, 1, 2);
        lbltxtAccountNameAr.Name = "lbltxtAccountNameAr";
        lbltxtAccountNameAr.Text = "اسم الحساب العربي *";
        lbltxtAccountNameAr.Dock = DockStyle.Fill;
        lbltxtAccountNameAr.TextAlign = ContentAlignment.MiddleLeft;
        lbltxtAccountNameAr.AutoSize = false;
        lbltxtAccountNameAr.TabStop = false;
        txtAccountNameAr.Name = "txtAccountNameAr";
        txtAccountNameAr.Dock = DockStyle.Fill;
        txtAccountNameAr.Margin = new Padding(6, 10, 12, 10);
        txtAccountNameAr.TabIndex = 3;
        txtAccountNameAr.AccessibleName = "اسم الحساب العربي";
        txtAccountNameAr.BackColor = Color.FromArgb(255, 250, 205);
        txtAccountNameAr.MaxLength = 150;
        AccountFields.Controls.Add(lbltxtAccountNameAr, 0, 3);
        AccountFields.Controls.Add(txtAccountNameAr, 1, 3);
        lbltxtAccountNameEn.Name = "lbltxtAccountNameEn";
        lbltxtAccountNameEn.Text = "اسم الحساب الإنجليزي";
        lbltxtAccountNameEn.Dock = DockStyle.Fill;
        lbltxtAccountNameEn.TextAlign = ContentAlignment.MiddleLeft;
        lbltxtAccountNameEn.AutoSize = false;
        lbltxtAccountNameEn.TabStop = false;
        txtAccountNameEn.Name = "txtAccountNameEn";
        txtAccountNameEn.Dock = DockStyle.Fill;
        txtAccountNameEn.Margin = new Padding(6, 10, 12, 10);
        txtAccountNameEn.TabIndex = 4;
        txtAccountNameEn.AccessibleName = "اسم الحساب الإنجليزي";
        txtAccountNameEn.MaxLength = 150;
        AccountFields.Controls.Add(lbltxtAccountNameEn, 0, 4);
        AccountFields.Controls.Add(txtAccountNameEn, 1, 4);
        lblcmbAccountType.Name = "lblcmbAccountType";
        lblcmbAccountType.Text = "نوع الحساب *";
        lblcmbAccountType.Dock = DockStyle.Fill;
        lblcmbAccountType.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbAccountType.AutoSize = false;
        lblcmbAccountType.TabStop = false;
        cmbAccountType.Name = "cmbAccountType";
        cmbAccountType.Dock = DockStyle.Fill;
        cmbAccountType.Margin = new Padding(6, 10, 12, 10);
        cmbAccountType.TabIndex = 5;
        cmbAccountType.AccessibleName = "نوع الحساب";
        cmbAccountType.BackColor = Color.FromArgb(255, 250, 205);
        cmbAccountType.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbAccountType.Items.AddRange(new object[] { "أصول", "التزامات", "حقوق ملكية", "إيرادات", "مصروفات" });
        AccountFields.Controls.Add(lblcmbAccountType, 0, 5);
        AccountFields.Controls.Add(cmbAccountType, 1, 5);
        lblcmbNormalBalance.Name = "lblcmbNormalBalance";
        lblcmbNormalBalance.Text = "طبيعة الحساب *";
        lblcmbNormalBalance.Dock = DockStyle.Fill;
        lblcmbNormalBalance.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbNormalBalance.AutoSize = false;
        lblcmbNormalBalance.TabStop = false;
        cmbNormalBalance.Name = "cmbNormalBalance";
        cmbNormalBalance.Dock = DockStyle.Fill;
        cmbNormalBalance.Margin = new Padding(6, 10, 12, 10);
        cmbNormalBalance.TabIndex = 6;
        cmbNormalBalance.AccessibleName = "طبيعة الحساب";
        cmbNormalBalance.BackColor = Color.FromArgb(255, 250, 205);
        cmbNormalBalance.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbNormalBalance.Items.AddRange(new object[] { "مدين", "دائن" });
        AccountFields.Controls.Add(lblcmbNormalBalance, 0, 6);
        AccountFields.Controls.Add(cmbNormalBalance, 1, 6);
        lblcmbAccountGroup.Name = "lblcmbAccountGroup";
        lblcmbAccountGroup.Text = "مجموعة الحساب";
        lblcmbAccountGroup.Dock = DockStyle.Fill;
        lblcmbAccountGroup.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbAccountGroup.AutoSize = false;
        lblcmbAccountGroup.TabStop = false;
        cmbAccountGroup.Name = "cmbAccountGroup";
        cmbAccountGroup.Dock = DockStyle.Fill;
        cmbAccountGroup.Margin = new Padding(6, 10, 12, 10);
        cmbAccountGroup.TabIndex = 7;
        cmbAccountGroup.AccessibleName = "مجموعة الحساب";
        cmbAccountGroup.DropDownStyle = ComboBoxStyle.DropDownList;
        AccountFields.Controls.Add(lblcmbAccountGroup, 0, 7);
        AccountFields.Controls.Add(cmbAccountGroup, 1, 7);
        lblcmbAccountCategory.Name = "lblcmbAccountCategory";
        lblcmbAccountCategory.Text = "تصنيف الحساب *";
        lblcmbAccountCategory.Dock = DockStyle.Fill;
        lblcmbAccountCategory.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbAccountCategory.AutoSize = false;
        lblcmbAccountCategory.TabStop = false;
        cmbAccountCategory.Name = "cmbAccountCategory";
        cmbAccountCategory.Dock = DockStyle.Fill;
        cmbAccountCategory.Margin = new Padding(6, 10, 12, 10);
        cmbAccountCategory.TabIndex = 8;
        cmbAccountCategory.AccessibleName = "تصنيف الحساب";
        cmbAccountCategory.BackColor = Color.FromArgb(255, 250, 205);
        cmbAccountCategory.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbAccountCategory.Items.AddRange(new object[] { "عام", "نقدية", "بنك", "عملاء", "موردون", "إيرادات", "مصروفات", "عهد" });
        AccountFields.Controls.Add(lblcmbAccountCategory, 0, 8);
        AccountFields.Controls.Add(cmbAccountCategory, 1, 8);
        lbltxtAccountLevel.Name = "lbltxtAccountLevel";
        lbltxtAccountLevel.Text = "المستوى";
        lbltxtAccountLevel.Dock = DockStyle.Fill;
        lbltxtAccountLevel.TextAlign = ContentAlignment.MiddleLeft;
        lbltxtAccountLevel.AutoSize = false;
        lbltxtAccountLevel.TabStop = false;
        txtAccountLevel.Name = "txtAccountLevel";
        txtAccountLevel.Dock = DockStyle.Fill;
        txtAccountLevel.Margin = new Padding(6, 10, 12, 10);
        txtAccountLevel.TabIndex = 9;
        txtAccountLevel.AccessibleName = "المستوى";
        txtAccountLevel.ReadOnly = true;
        txtAccountLevel.TabStop = false;
        AccountFields.Controls.Add(lbltxtAccountLevel, 0, 9);
        AccountFields.Controls.Add(txtAccountLevel, 1, 9);
        lblcmbAccountKind.Name = "lblcmbAccountKind";
        lblcmbAccountKind.Text = "مستوى الاستخدام *";
        lblcmbAccountKind.Dock = DockStyle.Fill;
        lblcmbAccountKind.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbAccountKind.AutoSize = false;
        lblcmbAccountKind.TabStop = false;
        cmbAccountKind.Name = "cmbAccountKind";
        cmbAccountKind.Dock = DockStyle.Fill;
        cmbAccountKind.Margin = new Padding(6, 10, 12, 10);
        cmbAccountKind.TabIndex = 10;
        cmbAccountKind.AccessibleName = "مستوى الاستخدام";
        cmbAccountKind.BackColor = Color.FromArgb(255, 250, 205);
        cmbAccountKind.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbAccountKind.Items.AddRange(new object[] { "رئيسي / تجميعي", "فرعي / يقبل الحركة" });
        AccountFields.Controls.Add(lblcmbAccountKind, 0, 10);
        AccountFields.Controls.Add(cmbAccountKind, 1, 10);
        lblcmbAccountStatus.Name = "lblcmbAccountStatus";
        lblcmbAccountStatus.Text = "الحالة *";
        lblcmbAccountStatus.Dock = DockStyle.Fill;
        lblcmbAccountStatus.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbAccountStatus.AutoSize = false;
        lblcmbAccountStatus.TabStop = false;
        cmbAccountStatus.Name = "cmbAccountStatus";
        cmbAccountStatus.Dock = DockStyle.Fill;
        cmbAccountStatus.Margin = new Padding(6, 10, 12, 10);
        cmbAccountStatus.TabIndex = 11;
        cmbAccountStatus.AccessibleName = "الحالة";
        cmbAccountStatus.BackColor = Color.FromArgb(255, 250, 205);
        cmbAccountStatus.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbAccountStatus.Items.AddRange(new object[] { "نشط", "موقوف" });
        AccountFields.Controls.Add(lblcmbAccountStatus, 0, 11);
        AccountFields.Controls.Add(cmbAccountStatus, 1, 11);
        tpAccountDetails.Controls.Add(AccountFields);
        tpAccountCurrencies.Name = "tpAccountCurrencies";
        tpAccountCurrencies.Text = "العملات المسموح بها";
        tpAccountCurrencies.Padding = new Padding(12);
        tpAccountCurrencies.AutoScroll = true;
        tpAccountCurrencies.BackColor = Color.White;
        tabMain.TabPages.Add(tpAccountCurrencies);
        dgvAccountCurrencies.Name = "dgvAccountCurrencies";
        dgvAccountCurrencies.Dock = DockStyle.Fill;
        dgvAccountCurrencies.BackgroundColor = Color.White;
        dgvAccountCurrencies.BorderStyle = BorderStyle.FixedSingle;
        dgvAccountCurrencies.AutoGenerateColumns = false;
        dgvAccountCurrencies.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        dgvAccountCurrencies.AllowUserToAddRows = false;
        dgvAccountCurrencies.AllowUserToDeleteRows = false;
        dgvAccountCurrencies.ReadOnly = true;
        dgvAccountCurrencies.RowHeadersVisible = false;
        dgvAccountCurrencies.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvAccountCurrencies.MultiSelect = false;
        dgvAccountCurrencies.MinimumSize = new Size(0, 160);
        dgvAccountCurrencies.AccessibleName = "قائمة البيانات — لم يتم تحميل بيانات";
        dgvAccountCurrenciesColCurrency.Name = "dgvAccountCurrenciesColCurrency";
        dgvAccountCurrenciesColCurrency.HeaderText = "العملة";
        dgvAccountCurrenciesColCurrency.MinimumWidth = 90;
        dgvAccountCurrenciesColCurrency.FillWeight = 100F;
        dgvAccountCurrenciesColCurrency.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvAccountCurrencies.Columns.Add(dgvAccountCurrenciesColCurrency);
        dgvAccountCurrenciesColDefault.Name = "dgvAccountCurrenciesColDefault";
        dgvAccountCurrenciesColDefault.HeaderText = "افتراضية";
        dgvAccountCurrenciesColDefault.MinimumWidth = 90;
        dgvAccountCurrenciesColDefault.FillWeight = 100F;
        dgvAccountCurrenciesColDefault.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvAccountCurrencies.Columns.Add(dgvAccountCurrenciesColDefault);
        dgvAccountCurrenciesColActive.Name = "dgvAccountCurrenciesColActive";
        dgvAccountCurrenciesColActive.HeaderText = "مسموحة";
        dgvAccountCurrenciesColActive.MinimumWidth = 90;
        dgvAccountCurrenciesColActive.FillWeight = 100F;
        dgvAccountCurrenciesColActive.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvAccountCurrencies.Columns.Add(dgvAccountCurrenciesColActive);
        tpAccountCurrencies.Controls.Add(dgvAccountCurrencies);
        tpAccountBranches.Name = "tpAccountBranches";
        tpAccountBranches.Text = "الفروع المسموح بها";
        tpAccountBranches.Padding = new Padding(12);
        tpAccountBranches.AutoScroll = true;
        tpAccountBranches.BackColor = Color.White;
        tabMain.TabPages.Add(tpAccountBranches);
        dgvAccountBranches.Name = "dgvAccountBranches";
        dgvAccountBranches.Dock = DockStyle.Fill;
        dgvAccountBranches.BackgroundColor = Color.White;
        dgvAccountBranches.BorderStyle = BorderStyle.FixedSingle;
        dgvAccountBranches.AutoGenerateColumns = false;
        dgvAccountBranches.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        dgvAccountBranches.AllowUserToAddRows = false;
        dgvAccountBranches.AllowUserToDeleteRows = false;
        dgvAccountBranches.ReadOnly = true;
        dgvAccountBranches.RowHeadersVisible = false;
        dgvAccountBranches.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvAccountBranches.MultiSelect = false;
        dgvAccountBranches.MinimumSize = new Size(0, 160);
        dgvAccountBranches.AccessibleName = "قائمة البيانات — لم يتم تحميل بيانات";
        dgvAccountBranchesColBranch.Name = "dgvAccountBranchesColBranch";
        dgvAccountBranchesColBranch.HeaderText = "الفرع";
        dgvAccountBranchesColBranch.MinimumWidth = 90;
        dgvAccountBranchesColBranch.FillWeight = 100F;
        dgvAccountBranchesColBranch.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvAccountBranches.Columns.Add(dgvAccountBranchesColBranch);
        dgvAccountBranchesColActive.Name = "dgvAccountBranchesColActive";
        dgvAccountBranchesColActive.HeaderText = "مسموح";
        dgvAccountBranchesColActive.MinimumWidth = 90;
        dgvAccountBranchesColActive.FillWeight = 100F;
        dgvAccountBranchesColActive.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvAccountBranches.Columns.Add(dgvAccountBranchesColActive);
        tpAccountBranches.Controls.Add(dgvAccountBranches);
        tpNotes.Name = "tpNotes";
        tpNotes.Text = "الملاحظات";
        tpNotes.Padding = new Padding(12);
        tpNotes.AutoScroll = true;
        tpNotes.BackColor = Color.White;
        tabMain.TabPages.Add(tpNotes);
        txtNotes.Name = "txtNotes";
        txtNotes.Dock = DockStyle.Fill;
        txtNotes.Multiline = true;
        txtNotes.ScrollBars = ScrollBars.Vertical;
        txtNotes.MaxLength = 4000;
        txtNotes.AccessibleName = "الملاحظات";
        tpNotes.Controls.Add(txtNotes);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 10F);
        BackColor = Color.White;
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1120, 720);
        MinimumSize = new Size(936, 600);
        Name = "UcChartOfAccounts";
        Text = "دليل الحسابات";
        Tag = "04.01.01";
        Controls.Add(mainLayout);
        tpNotes.ResumeLayout(false);
        tpNotes.PerformLayout();
        tpAccountBranches.ResumeLayout(false);
        tpAccountBranches.PerformLayout();
        tpAccountCurrencies.ResumeLayout(false);
        tpAccountCurrencies.PerformLayout();
        AccountFields.ResumeLayout(false);
        AccountFields.PerformLayout();
        tpAccountDetails.ResumeLayout(false);
        tpAccountDetails.PerformLayout();
        chartLayout.ResumeLayout(false);
        chartLayout.PerformLayout();
        tabMain.ResumeLayout(false);
        tabMain.PerformLayout();
        pnlActions.ResumeLayout(false);
        pnlActions.PerformLayout();
        mainLayout.ResumeLayout(false);
        mainLayout.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)dgvAccountCurrencies).EndInit();
        ((System.ComponentModel.ISupportInitialize)dgvAccountBranches).EndInit();
        ResumeLayout(false);
    }

    private TableLayoutPanel mainLayout = null!;
    private FlowLayoutPanel pnlActions = null!;
    private Button btnNew = null!;
    private Button btnSave = null!;
    private Button btnEdit = null!;
    private Button btnDelete = null!;
    private Button btnRefresh = null!;
    private Button btnClose = null!;
    private Label lblPreview = null!;
    private TabControl tabMain = null!;
    private TableLayoutPanel chartLayout = null!;
    private TreeView tvAccounts = null!;
    private TabPage tpAccountDetails = null!;
    private TableLayoutPanel AccountFields = null!;
    private Label lblcmbCompany = null!;
    private ComboBox cmbCompany = null!;
    private Label lblcmbParentAccount = null!;
    private ComboBox cmbParentAccount = null!;
    private Label lbltxtAccountCode = null!;
    private TextBox txtAccountCode = null!;
    private Label lbltxtAccountNameAr = null!;
    private TextBox txtAccountNameAr = null!;
    private Label lbltxtAccountNameEn = null!;
    private TextBox txtAccountNameEn = null!;
    private Label lblcmbAccountType = null!;
    private ComboBox cmbAccountType = null!;
    private Label lblcmbNormalBalance = null!;
    private ComboBox cmbNormalBalance = null!;
    private Label lblcmbAccountGroup = null!;
    private ComboBox cmbAccountGroup = null!;
    private Label lblcmbAccountCategory = null!;
    private ComboBox cmbAccountCategory = null!;
    private Label lbltxtAccountLevel = null!;
    private TextBox txtAccountLevel = null!;
    private Label lblcmbAccountKind = null!;
    private ComboBox cmbAccountKind = null!;
    private Label lblcmbAccountStatus = null!;
    private ComboBox cmbAccountStatus = null!;
    private TabPage tpAccountCurrencies = null!;
    private DataGridView dgvAccountCurrencies = null!;
    private DataGridViewTextBoxColumn dgvAccountCurrenciesColCurrency = null!;
    private DataGridViewTextBoxColumn dgvAccountCurrenciesColDefault = null!;
    private DataGridViewTextBoxColumn dgvAccountCurrenciesColActive = null!;
    private TabPage tpAccountBranches = null!;
    private DataGridView dgvAccountBranches = null!;
    private DataGridViewTextBoxColumn dgvAccountBranchesColBranch = null!;
    private DataGridViewTextBoxColumn dgvAccountBranchesColActive = null!;
    private TabPage tpNotes = null!;
    private TextBox txtNotes = null!;
}
