using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcCustomerInstallmentSettlement
{
    private TableLayoutPanel mainLayout = null!;
    private TableLayoutPanel headerLayout = null!;
    private TableLayoutPanel totalsLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private DataGridView gridInstallments = null!;
    private Panel auditFooter = null!;
    private AuditMetadataControl standardAuditMetadata = null!;
    private Label lblOperationStatus = null!;
    private Label lblBranch = null!;
    private ComboBox fieldBranch = null!;
    private Label lblSerialNumber = null!;
    private TextBox fieldSerialNumber = null!;
    private Label lblDate = null!;
    private TextBox fieldDate = null!;
    private Label lblCostCenter = null!;
    private ComboBox fieldCostCenter = null!;
    private Label lblCustomerNumber = null!;
    private TextBox fieldCustomerNumber = null!;
    private Label lblCustomerName = null!;
    private TextBox fieldCustomerName = null!;
    private Label lblCurrency = null!;
    private ComboBox fieldCurrency = null!;
    private Label lblDocumentType = null!;
    private ComboBox fieldDocumentType = null!;
    private Label lblDocumentNumber = null!;
    private TextBox fieldDocumentNumber = null!;
    private Label lblAmount = null!;
    private TextBox fieldAmount = null!;
    private Label lblReference = null!;
    private TextBox fieldReference = null!;
    private Label lblDocumentDate = null!;
    private TextBox fieldDocumentDate = null!;
    private Label lblRemainingAmount = null!;
    private TextBox fieldRemainingAmount = null!;
    private Label lblDescription = null!;
    private TextBox fieldDescription = null!;
    private DataGridViewComboBoxColumn colDocumentType = null!;
    private DataGridViewTextBoxColumn colDocumentNumber = null!;
    private DataGridViewTextBoxColumn colInstallmentNumber = null!;
    private DataGridViewTextBoxColumn colDueDate = null!;
    private DataGridViewTextBoxColumn colCurrency = null!;
    private DataGridViewTextBoxColumn colAmount = null!;
    private DataGridViewTextBoxColumn colPaidAmount = null!;
    private DataGridViewTextBoxColumn colSettlementAmount = null!;
    private Label lblTotalAmount = null!;
    private TextBox txtTotalAmount = null!;
    private Label lblTotalPaidAmount = null!;
    private TextBox txtTotalPaidAmount = null!;
    private Label lblTotalSettlementAmount = null!;
    private TextBox txtTotalSettlementAmount = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        headerLayout = new TableLayoutPanel();
        headerLayout.Name = "headerLayout";
        totalsLayout = new TableLayoutPanel();
        totalsLayout.Name = "totalsLayout";
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        gridInstallments = new DataGridView();
        gridInstallments.Name = "gridInstallments";
        auditFooter = new Panel();
        auditFooter.Name = "auditFooter";
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        lblOperationStatus = new Label();
        lblOperationStatus.Name = "lblOperationStatus";
        lblBranch = new Label();
        lblBranch.Name = "lblBranch";
        fieldBranch = new ComboBox();
        fieldBranch.Name = "fieldBranch";
        lblSerialNumber = new Label();
        lblSerialNumber.Name = "lblSerialNumber";
        fieldSerialNumber = new TextBox();
        fieldSerialNumber.Name = "fieldSerialNumber";
        lblDate = new Label();
        lblDate.Name = "lblDate";
        fieldDate = new TextBox();
        fieldDate.Name = "fieldDate";
        lblCostCenter = new Label();
        lblCostCenter.Name = "lblCostCenter";
        fieldCostCenter = new ComboBox();
        fieldCostCenter.Name = "fieldCostCenter";
        lblCustomerNumber = new Label();
        lblCustomerNumber.Name = "lblCustomerNumber";
        fieldCustomerNumber = new TextBox();
        fieldCustomerNumber.Name = "fieldCustomerNumber";
        lblCustomerName = new Label();
        lblCustomerName.Name = "lblCustomerName";
        fieldCustomerName = new TextBox();
        fieldCustomerName.Name = "fieldCustomerName";
        lblCurrency = new Label();
        lblCurrency.Name = "lblCurrency";
        fieldCurrency = new ComboBox();
        fieldCurrency.Name = "fieldCurrency";
        lblDocumentType = new Label();
        lblDocumentType.Name = "lblDocumentType";
        fieldDocumentType = new ComboBox();
        fieldDocumentType.Name = "fieldDocumentType";
        lblDocumentNumber = new Label();
        lblDocumentNumber.Name = "lblDocumentNumber";
        fieldDocumentNumber = new TextBox();
        fieldDocumentNumber.Name = "fieldDocumentNumber";
        lblAmount = new Label();
        lblAmount.Name = "lblAmount";
        fieldAmount = new TextBox();
        fieldAmount.Name = "fieldAmount";
        lblReference = new Label();
        lblReference.Name = "lblReference";
        fieldReference = new TextBox();
        fieldReference.Name = "fieldReference";
        lblDocumentDate = new Label();
        lblDocumentDate.Name = "lblDocumentDate";
        fieldDocumentDate = new TextBox();
        fieldDocumentDate.Name = "fieldDocumentDate";
        lblRemainingAmount = new Label();
        lblRemainingAmount.Name = "lblRemainingAmount";
        fieldRemainingAmount = new TextBox();
        fieldRemainingAmount.Name = "fieldRemainingAmount";
        lblDescription = new Label();
        lblDescription.Name = "lblDescription";
        fieldDescription = new TextBox();
        fieldDescription.Name = "fieldDescription";
        colDocumentType = new DataGridViewComboBoxColumn();
        colDocumentType.Name = "colDocumentType";
        colDocumentNumber = new DataGridViewTextBoxColumn();
        colDocumentNumber.Name = "colDocumentNumber";
        colInstallmentNumber = new DataGridViewTextBoxColumn();
        colInstallmentNumber.Name = "colInstallmentNumber";
        colDueDate = new DataGridViewTextBoxColumn();
        colDueDate.Name = "colDueDate";
        colCurrency = new DataGridViewTextBoxColumn();
        colCurrency.Name = "colCurrency";
        colAmount = new DataGridViewTextBoxColumn();
        colAmount.Name = "colAmount";
        colPaidAmount = new DataGridViewTextBoxColumn();
        colPaidAmount.Name = "colPaidAmount";
        colSettlementAmount = new DataGridViewTextBoxColumn();
        colSettlementAmount.Name = "colSettlementAmount";
        lblTotalAmount = new Label();
        lblTotalAmount.Name = "lblTotalAmount";
        txtTotalAmount = new TextBox();
        txtTotalAmount.Name = "txtTotalAmount";
        lblTotalPaidAmount = new Label();
        lblTotalPaidAmount.Name = "lblTotalPaidAmount";
        txtTotalPaidAmount = new TextBox();
        txtTotalPaidAmount.Name = "txtTotalPaidAmount";
        lblTotalSettlementAmount = new Label();
        lblTotalSettlementAmount.Name = "lblTotalSettlementAmount";
        txtTotalSettlementAmount = new TextBox();
        txtTotalSettlementAmount.Name = "txtTotalSettlementAmount";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = Padding.Empty;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 7;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 192F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        lblTitle.Text = "تسوية أقساط العملاء";
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.BackColor = Color.FromArgb(23, 50, 78);
        lblTitle.ForeColor = Color.White;
        commandBar.Dock = DockStyle.Fill;
        commandBar.Margin = Padding.Empty;
        headerLayout.Dock = DockStyle.Fill;
        headerLayout.Margin = Padding.Empty;
        headerLayout.Padding = new Padding(12, 6, 12, 6);
        headerLayout.ColumnCount = 6;
        headerLayout.RowCount = 6;
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 95F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 95F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 95F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        lblBranch.Text = "رقم الفرع";
        lblBranch.Dock = DockStyle.Fill;
        lblBranch.TextAlign = ContentAlignment.MiddleLeft;
        fieldBranch.AccessibleName = "رقم الفرع";
        fieldBranch.Dock = DockStyle.Fill;
        fieldBranch.TabStop = false;
        fieldBranch.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldBranch.Enabled = false;
        headerLayout.Controls.Add(lblBranch, 0, 0);
        headerLayout.Controls.Add(fieldBranch, 1, 0);
        headerLayout.SetColumnSpan(fieldBranch, 3);
        lblSerialNumber.Text = "المسلسل";
        lblSerialNumber.Dock = DockStyle.Fill;
        lblSerialNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldSerialNumber.AccessibleName = "المسلسل";
        fieldSerialNumber.Dock = DockStyle.Fill;
        fieldSerialNumber.TabStop = false;
        fieldSerialNumber.ReadOnly = true;
        headerLayout.Controls.Add(lblSerialNumber, 0, 1);
        headerLayout.Controls.Add(fieldSerialNumber, 1, 1);
        lblDate.Text = "التاريخ";
        lblDate.Dock = DockStyle.Fill;
        lblDate.TextAlign = ContentAlignment.MiddleLeft;
        fieldDate.AccessibleName = "التاريخ";
        fieldDate.Dock = DockStyle.Fill;
        fieldDate.TabStop = false;
        fieldDate.ReadOnly = true;
        headerLayout.Controls.Add(lblDate, 2, 1);
        headerLayout.Controls.Add(fieldDate, 3, 1);
        lblCostCenter.Text = "مركز التكلفة";
        lblCostCenter.Dock = DockStyle.Fill;
        lblCostCenter.TextAlign = ContentAlignment.MiddleLeft;
        fieldCostCenter.AccessibleName = "مركز التكلفة";
        fieldCostCenter.Dock = DockStyle.Fill;
        fieldCostCenter.TabStop = false;
        fieldCostCenter.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldCostCenter.Enabled = false;
        headerLayout.Controls.Add(lblCostCenter, 4, 1);
        headerLayout.Controls.Add(fieldCostCenter, 5, 1);
        lblCustomerNumber.Text = "رقم العميل";
        lblCustomerNumber.Dock = DockStyle.Fill;
        lblCustomerNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldCustomerNumber.AccessibleName = "رقم العميل";
        fieldCustomerNumber.Dock = DockStyle.Fill;
        fieldCustomerNumber.TabStop = false;
        fieldCustomerNumber.ReadOnly = true;
        headerLayout.Controls.Add(lblCustomerNumber, 0, 2);
        headerLayout.Controls.Add(fieldCustomerNumber, 1, 2);
        lblCustomerName.Text = "اسم العميل";
        lblCustomerName.Dock = DockStyle.Fill;
        lblCustomerName.TextAlign = ContentAlignment.MiddleLeft;
        fieldCustomerName.AccessibleName = "اسم العميل";
        fieldCustomerName.Dock = DockStyle.Fill;
        fieldCustomerName.TabStop = false;
        fieldCustomerName.ReadOnly = true;
        headerLayout.Controls.Add(lblCustomerName, 2, 2);
        headerLayout.Controls.Add(fieldCustomerName, 3, 2);
        lblCurrency.Text = "العملة";
        lblCurrency.Dock = DockStyle.Fill;
        lblCurrency.TextAlign = ContentAlignment.MiddleLeft;
        fieldCurrency.AccessibleName = "العملة";
        fieldCurrency.Dock = DockStyle.Fill;
        fieldCurrency.TabStop = false;
        fieldCurrency.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldCurrency.Enabled = false;
        headerLayout.Controls.Add(lblCurrency, 4, 2);
        headerLayout.Controls.Add(fieldCurrency, 5, 2);
        lblDocumentType.Text = "نوع الوثيقة";
        lblDocumentType.Dock = DockStyle.Fill;
        lblDocumentType.TextAlign = ContentAlignment.MiddleLeft;
        fieldDocumentType.AccessibleName = "نوع الوثيقة";
        fieldDocumentType.Dock = DockStyle.Fill;
        fieldDocumentType.TabStop = false;
        fieldDocumentType.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldDocumentType.Enabled = false;
        headerLayout.Controls.Add(lblDocumentType, 0, 3);
        headerLayout.Controls.Add(fieldDocumentType, 1, 3);
        lblDocumentNumber.Text = "رقم الوثيقة";
        lblDocumentNumber.Dock = DockStyle.Fill;
        lblDocumentNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldDocumentNumber.AccessibleName = "رقم الوثيقة";
        fieldDocumentNumber.Dock = DockStyle.Fill;
        fieldDocumentNumber.TabStop = false;
        fieldDocumentNumber.ReadOnly = true;
        headerLayout.Controls.Add(lblDocumentNumber, 2, 3);
        headerLayout.Controls.Add(fieldDocumentNumber, 3, 3);
        lblAmount.Text = "المبلغ";
        lblAmount.Dock = DockStyle.Fill;
        lblAmount.TextAlign = ContentAlignment.MiddleLeft;
        fieldAmount.AccessibleName = "المبلغ";
        fieldAmount.Dock = DockStyle.Fill;
        fieldAmount.TabStop = false;
        fieldAmount.ReadOnly = true;
        headerLayout.Controls.Add(lblAmount, 4, 3);
        headerLayout.Controls.Add(fieldAmount, 5, 3);
        lblReference.Text = "رقم المرجع";
        lblReference.Dock = DockStyle.Fill;
        lblReference.TextAlign = ContentAlignment.MiddleLeft;
        fieldReference.AccessibleName = "رقم المرجع";
        fieldReference.Dock = DockStyle.Fill;
        fieldReference.TabStop = false;
        fieldReference.ReadOnly = true;
        headerLayout.Controls.Add(lblReference, 0, 4);
        headerLayout.Controls.Add(fieldReference, 1, 4);
        lblDocumentDate.Text = "تاريخ الوثيقة";
        lblDocumentDate.Dock = DockStyle.Fill;
        lblDocumentDate.TextAlign = ContentAlignment.MiddleLeft;
        fieldDocumentDate.AccessibleName = "تاريخ الوثيقة";
        fieldDocumentDate.Dock = DockStyle.Fill;
        fieldDocumentDate.TabStop = false;
        fieldDocumentDate.ReadOnly = true;
        headerLayout.Controls.Add(lblDocumentDate, 2, 4);
        headerLayout.Controls.Add(fieldDocumentDate, 3, 4);
        lblRemainingAmount.Text = "المبلغ الباقي";
        lblRemainingAmount.Dock = DockStyle.Fill;
        lblRemainingAmount.TextAlign = ContentAlignment.MiddleLeft;
        fieldRemainingAmount.AccessibleName = "المبلغ الباقي";
        fieldRemainingAmount.Dock = DockStyle.Fill;
        fieldRemainingAmount.TabStop = false;
        fieldRemainingAmount.ReadOnly = true;
        headerLayout.Controls.Add(lblRemainingAmount, 4, 4);
        headerLayout.Controls.Add(fieldRemainingAmount, 5, 4);
        lblDescription.Text = "البيان";
        lblDescription.Dock = DockStyle.Fill;
        lblDescription.TextAlign = ContentAlignment.MiddleLeft;
        fieldDescription.AccessibleName = "البيان";
        fieldDescription.Dock = DockStyle.Fill;
        fieldDescription.TabStop = false;
        fieldDescription.ReadOnly = true;
        headerLayout.Controls.Add(lblDescription, 0, 5);
        headerLayout.Controls.Add(fieldDescription, 1, 5);
        headerLayout.SetColumnSpan(fieldDescription, 5);
        gridInstallments.Dock = DockStyle.Fill;
        gridInstallments.AutoGenerateColumns = false;
        gridInstallments.ReadOnly = true;
        gridInstallments.AllowUserToAddRows = false;
        gridInstallments.AllowUserToDeleteRows = false;
        gridInstallments.AllowUserToOrderColumns = false;
        gridInstallments.RowHeadersVisible = false;
        gridInstallments.BackgroundColor = Color.White;
        gridInstallments.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        gridInstallments.ColumnHeadersHeight = 44;
        gridInstallments.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridInstallments.AccessibleName = "بيانات الأقساط";
        colDocumentType.Name = "DocumentType";
        colDocumentType.HeaderText = "نوع الوثيقة";
        colDocumentType.Width = 180;
        colDocumentType.FillWeight = 180;
        colDocumentType.MinimumWidth = 60;
        colDocumentType.ReadOnly = true;
        colDocumentType.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridInstallments.Columns.Add(colDocumentType);
        colDocumentNumber.Name = "DocumentNumber";
        colDocumentNumber.HeaderText = "رقم الوثيقة";
        colDocumentNumber.Width = 115;
        colDocumentNumber.FillWeight = 115;
        colDocumentNumber.MinimumWidth = 60;
        colDocumentNumber.ReadOnly = true;
        colDocumentNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridInstallments.Columns.Add(colDocumentNumber);
        colInstallmentNumber.Name = "InstallmentNumber";
        colInstallmentNumber.HeaderText = "رقم القسط";
        colInstallmentNumber.Width = 90;
        colInstallmentNumber.FillWeight = 90;
        colInstallmentNumber.MinimumWidth = 60;
        colInstallmentNumber.ReadOnly = true;
        colInstallmentNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridInstallments.Columns.Add(colInstallmentNumber);
        colDueDate.Name = "DueDate";
        colDueDate.HeaderText = "تاريخ الاستحقاق";
        colDueDate.Width = 130;
        colDueDate.FillWeight = 130;
        colDueDate.MinimumWidth = 60;
        colDueDate.ReadOnly = true;
        colDueDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridInstallments.Columns.Add(colDueDate);
        colCurrency.Name = "Currency";
        colCurrency.HeaderText = "العملة";
        colCurrency.Width = 70;
        colCurrency.FillWeight = 70;
        colCurrency.MinimumWidth = 60;
        colCurrency.ReadOnly = true;
        colCurrency.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridInstallments.Columns.Add(colCurrency);
        colAmount.Name = "Amount";
        colAmount.HeaderText = "المبلغ";
        colAmount.Width = 120;
        colAmount.FillWeight = 120;
        colAmount.MinimumWidth = 60;
        colAmount.ReadOnly = true;
        colAmount.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridInstallments.Columns.Add(colAmount);
        colPaidAmount.Name = "PaidAmount";
        colPaidAmount.HeaderText = "المبلغ المدفوع";
        colPaidAmount.Width = 130;
        colPaidAmount.FillWeight = 130;
        colPaidAmount.MinimumWidth = 60;
        colPaidAmount.ReadOnly = true;
        colPaidAmount.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridInstallments.Columns.Add(colPaidAmount);
        colSettlementAmount.Name = "SettlementAmount";
        colSettlementAmount.HeaderText = "مبلغ التسوية";
        colSettlementAmount.Width = 130;
        colSettlementAmount.FillWeight = 130;
        colSettlementAmount.MinimumWidth = 60;
        colSettlementAmount.ReadOnly = true;
        colSettlementAmount.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridInstallments.Columns.Add(colSettlementAmount);
        totalsLayout.Dock = DockStyle.Fill;
        totalsLayout.Margin = Padding.Empty;
        totalsLayout.ColumnCount = 6;
        totalsLayout.RowCount = 1;
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 130F));
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 130F));
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 130F));
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        lblTotalAmount.Text = "إجمالي المبلغ";
        lblTotalAmount.Dock = DockStyle.Fill;
        lblTotalAmount.TextAlign = ContentAlignment.MiddleLeft;
        txtTotalAmount.AccessibleName = "إجمالي المبلغ";
        txtTotalAmount.Dock = DockStyle.Fill;
        txtTotalAmount.ReadOnly = true;
        totalsLayout.Controls.Add(lblTotalAmount, 0, 0);
        totalsLayout.Controls.Add(txtTotalAmount, 1, 0);
        lblTotalPaidAmount.Text = "إجمالي المدفوع";
        lblTotalPaidAmount.Dock = DockStyle.Fill;
        lblTotalPaidAmount.TextAlign = ContentAlignment.MiddleLeft;
        txtTotalPaidAmount.AccessibleName = "إجمالي المدفوع";
        txtTotalPaidAmount.Dock = DockStyle.Fill;
        txtTotalPaidAmount.ReadOnly = true;
        totalsLayout.Controls.Add(lblTotalPaidAmount, 2, 0);
        totalsLayout.Controls.Add(txtTotalPaidAmount, 3, 0);
        lblTotalSettlementAmount.Text = "إجمالي التسوية";
        lblTotalSettlementAmount.Dock = DockStyle.Fill;
        lblTotalSettlementAmount.TextAlign = ContentAlignment.MiddleLeft;
        txtTotalSettlementAmount.AccessibleName = "إجمالي التسوية";
        txtTotalSettlementAmount.Dock = DockStyle.Fill;
        txtTotalSettlementAmount.ReadOnly = true;
        totalsLayout.Controls.Add(lblTotalSettlementAmount, 4, 0);
        totalsLayout.Controls.Add(txtTotalSettlementAmount, 5, 0);
        auditFooter.Dock = DockStyle.Fill;
        auditFooter.Margin = Padding.Empty;
        standardAuditMetadata.Dock = DockStyle.Fill;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.Profile = AuditMetadataProfile.Standard;
        auditFooter.Controls.Add(standardAuditMetadata);
        lblOperationStatus.Text = "الحفظ واختيار وثائق العميل والأقساط غير متاحة حاليًا.";
        lblOperationStatus.Dock = DockStyle.Fill;
        lblOperationStatus.TextAlign = ContentAlignment.MiddleLeft;
        mainLayout.Controls.Add(lblTitle, 0, 0);
        mainLayout.Controls.Add(commandBar, 0, 1);
        mainLayout.Controls.Add(headerLayout, 0, 2);
        mainLayout.Controls.Add(gridInstallments, 0, 3);
        mainLayout.Controls.Add(totalsLayout, 0, 4);
        mainLayout.Controls.Add(auditFooter, 0, 5);
        mainLayout.Controls.Add(lblOperationStatus, 0, 6);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 9F);
        RightToLeft = RightToLeft.Yes;
        Name = "UcCustomerInstallmentSettlement";
        Text = "تسوية أقساط العملاء";
        Tag = "CUS:INSTALLMENT-SETTLEMENT";
        Size = new Size(1180, 720);
        MinimumSize = new Size(1000, 600);
        Controls.Add(mainLayout);
        ResumeLayout(false);
    }
}

