#nullable enable
using System.Drawing;
using System.Windows.Forms;

namespace TransportERP.EmptyForms;

partial class UcGeneralLedgerSettings
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandView = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private System.ComponentModel.IContainer? components;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandView = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandPrint = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        components = new System.ComponentModel.Container();
        mainLayout = new TableLayoutPanel();
        pnlHeader = new Panel();
        lblTitle = new Label();
        pnlActions = new FlowLayoutPanel();
        btnSave = new Button();
        btnUndo = new Button();
        btnRefresh = new Button();
        btnClose = new Button();
        tabMain = new TabControl();
        tpGeneral = new TabPage();
        tpReview = new TabPage();
        tpPosting = new TabPage();
        tpReceipt = new TabPage();
        tpAudit = new TabPage();
        generalLayout = new TableLayoutPanel();
        reviewLayout = new TableLayoutPanel();
        postingLayout = new TableLayoutPanel();
        receiptLayout = new TableLayoutPanel();
        lblScope = new Label();
        lblCoverage = new Label();
        lblPolicyStatus = new Label();
        lblReviewHelp = new Label();
        chkRequireReview = new CheckBox();
        chkRequireJournalDescription = new CheckBox();
        lblJournalDescriptionHelp = new Label();
        chkRequireApproval = new CheckBox();
        lblPostingMode = new Label();
        cmbPostingMode = new ComboBox();
        lblPath = new Label();
        lblReceiptHelp = new Label();
        btnReceiptSettings = new Button();
        lblReceiptScope = new Label();
        auditGrid = new DataGridView();
        auditAt = new DataGridViewTextBoxColumn();
        auditActor = new DataGridViewTextBoxColumn();
        auditAction = new DataGridViewTextBoxColumn();
        auditReason = new DataGridViewTextBoxColumn();
        lblPreview = new Label();
        lblDirty = new Label();
        ((System.ComponentModel.ISupportInitialize)auditGrid).BeginInit();
        SuspendLayout();
        mainLayout.Name = "mainLayout";
        mainLayout.TabIndex = 0;
        pnlHeader.Name = "pnlHeader";
        pnlHeader.TabIndex = 0;
        lblTitle.Name = "lblTitle";
        lblTitle.TabIndex = 0;
        pnlActions.Name = "pnlActions";
        pnlActions.TabIndex = 0;
        btnSave.Name = "btnSave";
        btnSave.TabIndex = 0;
        btnUndo.Name = "btnUndo";
        btnUndo.TabIndex = 0;
        btnRefresh.Name = "btnRefresh";
        btnRefresh.TabIndex = 0;
        btnClose.Name = "btnClose";
        btnClose.TabIndex = 0;
        tabMain.Name = "tabMain";
        tabMain.TabIndex = 0;
        tpGeneral.Name = "tpGeneral";
        tpGeneral.TabIndex = 0;
        tpReview.Name = "tpReview";
        tpReview.TabIndex = 0;
        tpPosting.Name = "tpPosting";
        tpPosting.TabIndex = 0;
        tpReceipt.Name = "tpReceipt";
        tpReceipt.TabIndex = 0;
        tpAudit.Name = "tpAudit";
        tpAudit.TabIndex = 0;
        generalLayout.Name = "generalLayout";
        generalLayout.TabIndex = 0;
        reviewLayout.Name = "reviewLayout";
        reviewLayout.TabIndex = 0;
        postingLayout.Name = "postingLayout";
        postingLayout.TabIndex = 0;
        receiptLayout.Name = "receiptLayout";
        receiptLayout.TabIndex = 0;
        lblScope.Name = "lblScope";
        lblScope.TabIndex = 0;
        lblCoverage.Name = "lblCoverage";
        lblCoverage.TabIndex = 0;
        lblPolicyStatus.Name = "lblPolicyStatus";
        lblPolicyStatus.TabIndex = 0;
        lblReviewHelp.Name = "lblReviewHelp";
        lblReviewHelp.TabIndex = 0;
        chkRequireReview.Name = "chkRequireReview";
        chkRequireReview.TabIndex = 0;
        chkRequireApproval.Name = "chkRequireApproval";
        chkRequireApproval.TabIndex = 0;
        lblPostingMode.Name = "lblPostingMode";
        lblPostingMode.TabIndex = 0;
        cmbPostingMode.Name = "cmbPostingMode";
        cmbPostingMode.TabIndex = 0;
        lblPath.Name = "lblPath";
        lblPath.TabIndex = 0;
        lblReceiptHelp.Name = "lblReceiptHelp";
        lblReceiptHelp.TabIndex = 0;
        btnReceiptSettings.Name = "btnReceiptSettings";
        btnReceiptSettings.TabIndex = 0;
        lblReceiptScope.Name = "lblReceiptScope";
        lblReceiptScope.TabIndex = 0;
        auditGrid.Name = "auditGrid";
        auditGrid.TabIndex = 0;
        auditAt.Name = "auditAt";
        auditActor.Name = "auditActor";
        auditAction.Name = "auditAction";
        auditReason.Name = "auditReason";
        lblPreview.Name = "lblPreview";
        lblPreview.TabIndex = 0;
        lblDirty.Name = "lblDirty";
        lblDirty.TabIndex = 0;
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.Margin = new Padding(0);
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 64F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        pnlHeader.Dock = DockStyle.Fill;
        pnlHeader.Margin = new Padding(0);
        pnlHeader.BackColor = Color.FromArgb(224, 224, 224);
        lblTitle.Text = "إعدادات الأستاذ العام";
        lblTitle.Dock = DockStyle.Right;
        lblTitle.Width = 270;
        lblTitle.Font = new Font("Segoe UI", 16F);
        lblTitle.BackColor = Color.FromArgb(192, 192, 255);
        lblTitle.TextAlign = ContentAlignment.MiddleCenter;
        pnlActions.Dock = DockStyle.Fill;
        pnlActions.Padding = new Padding(5);
        pnlActions.WrapContents = false;
        pnlActions.AutoScroll = true;
        pnlActions.FlowDirection = FlowDirection.LeftToRight;
        pnlActions.RightToLeft = RightToLeft.Yes;
        btnSave.Text = "حفظ وتفعيل";
        btnSave.Size = new Size(100, 36);
        btnSave.Margin = new Padding(4);
        btnSave.FlatStyle = FlatStyle.Flat;
        btnSave.UseVisualStyleBackColor = true;
        btnSave.TabIndex = 0;
        btnSave.AccessibleName = "حفظ وتفعيل";

        btnUndo.Text = "تراجع";
        btnUndo.Size = new Size(100, 36);
        btnUndo.Margin = new Padding(4);
        btnUndo.FlatStyle = FlatStyle.Flat;
        btnUndo.UseVisualStyleBackColor = true;
        btnUndo.TabIndex = 1;
        btnUndo.AccessibleName = "تراجع";

        btnRefresh.Text = "تحديث";
        btnRefresh.Size = new Size(100, 36);
        btnRefresh.Margin = new Padding(4);
        btnRefresh.FlatStyle = FlatStyle.Flat;
        btnRefresh.UseVisualStyleBackColor = true;
        btnRefresh.TabIndex = 2;
        btnRefresh.AccessibleName = "تحديث";

        btnClose.Text = "إغلاق";
        btnClose.Size = new Size(100, 36);
        btnClose.Margin = new Padding(4);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.UseVisualStyleBackColor = true;
        btnClose.TabIndex = 3;
        btnClose.AccessibleName = "إغلاق";

        btnSave.Enabled = false;
        btnUndo.Enabled = false;
        btnRefresh.Enabled = false;
        pnlHeader.Controls.Add(designerCommandBar);
        pnlHeader.Controls.Add(lblTitle);
        mainLayout.Controls.Add(pnlHeader, 0, 0);
        tabMain.Dock = DockStyle.Fill;
        tabMain.RightToLeft = RightToLeft.Yes;
        tabMain.RightToLeftLayout = true;
        tabMain.TabIndex = 1;
        tabMain.Padding = new Point(14, 8);
        tpGeneral.Text = "عام";
        tpGeneral.Padding = new Padding(12);
        tpGeneral.AutoScroll = true;
        tpGeneral.BackColor = Color.FromArgb(248, 250, 252);
        tpGeneral.TabIndex = 0;
        tabMain.Controls.Add(tpGeneral);
        tpReview.Text = "المراجعة والاعتماد";
        tpReview.Padding = new Padding(12);
        tpReview.AutoScroll = true;
        tpReview.BackColor = Color.FromArgb(248, 250, 252);
        tpReview.TabIndex = 1;
        tabMain.Controls.Add(tpReview);
        tpPosting.Text = "الترحيل";
        tpPosting.Padding = new Padding(12);
        tpPosting.AutoScroll = true;
        tpPosting.BackColor = Color.FromArgb(248, 250, 252);
        tpPosting.TabIndex = 2;
        tabMain.Controls.Add(tpPosting);
        tpReceipt.Text = "إعدادات سند القبض";
        tpReceipt.Padding = new Padding(12);
        tpReceipt.AutoScroll = true;
        tpReceipt.BackColor = Color.FromArgb(248, 250, 252);
        tpReceipt.TabIndex = 3;
        tabMain.Controls.Add(tpReceipt);
        tpAudit.Text = "سجل التغييرات";
        tpAudit.Padding = new Padding(12);
        tpAudit.AutoScroll = true;
        tpAudit.BackColor = Color.FromArgb(248, 250, 252);
        tpAudit.TabIndex = 4;
        tabMain.Controls.Add(tpAudit);
        mainLayout.Controls.Add(tabMain, 0, 1);
        generalLayout.Dock = DockStyle.Top;
        generalLayout.AutoSize = true;
        generalLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        generalLayout.ColumnCount = 1;
        generalLayout.RowCount = 5;
        generalLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        generalLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        generalLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        generalLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        generalLayout.MinimumSize = new Size(620, 0);
        generalLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        generalLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        tpGeneral.Controls.Add(generalLayout);
        reviewLayout.Dock = DockStyle.Top;
        reviewLayout.AutoSize = true;
        reviewLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        reviewLayout.ColumnCount = 1;
        reviewLayout.RowCount = 3;
        reviewLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        reviewLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        reviewLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        reviewLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        reviewLayout.MinimumSize = new Size(620, 0);
        tpReview.Controls.Add(reviewLayout);
        postingLayout.Dock = DockStyle.Top;
        postingLayout.AutoSize = true;
        postingLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        postingLayout.ColumnCount = 1;
        postingLayout.RowCount = 3;
        postingLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        postingLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        postingLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        postingLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        postingLayout.MinimumSize = new Size(620, 0);
        tpPosting.Controls.Add(postingLayout);
        receiptLayout.Dock = DockStyle.Top;
        receiptLayout.AutoSize = true;
        receiptLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        receiptLayout.ColumnCount = 1;
        receiptLayout.RowCount = 3;
        receiptLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        receiptLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        receiptLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        receiptLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        receiptLayout.MinimumSize = new Size(620, 0);
        tpReceipt.Controls.Add(receiptLayout);
        lblScope.Text = "الشركة وفرع الجلسة: يتطلب تحميلًا من الخدمة.";
        lblScope.AutoSize = true;
        lblScope.Dock = DockStyle.Fill;
        lblScope.TextAlign = ContentAlignment.MiddleLeft;
        lblScope.Margin = new Padding(8, 10, 8, 10);
        lblScope.Padding = new Padding(8);
        lblScope.TabStop = false;
        generalLayout.Controls.Add(lblScope, 0, 0);
        lblCoverage.Text = "التغطية الفعلية تُحمّل من خدمة الأستاذ العام. لا تعني هذه الشاشة ربط جميع أنواع المستندات تلقائيًا.";
        lblCoverage.AutoSize = true;
        lblCoverage.Dock = DockStyle.Fill;
        lblCoverage.TextAlign = ContentAlignment.MiddleLeft;
        lblCoverage.Margin = new Padding(8, 10, 8, 10);
        lblCoverage.Padding = new Padding(8);
        lblCoverage.TabStop = false;
        generalLayout.Controls.Add(lblCoverage, 0, 1);
        lblPolicyStatus.Text = "لم تُحمّل إعدادات الشركة. لا يمكن حفظ سياسة دون اتصال وصلاحية. الخيارات المرجعية غير المرتبطة بخدمات فعلية غير معروضة هنا.";
        lblPolicyStatus.AutoSize = true;
        lblPolicyStatus.Dock = DockStyle.Fill;
        lblPolicyStatus.TextAlign = ContentAlignment.MiddleLeft;
        lblPolicyStatus.Margin = new Padding(8, 10, 8, 10);
        lblPolicyStatus.Padding = new Padding(8);
        lblPolicyStatus.TabStop = false;
        generalLayout.Controls.Add(lblPolicyStatus, 0, 2);
        chkRequireJournalDescription.Name = "chkRequireJournalDescription";
        chkRequireJournalDescription.Text = "إدخال بيان قيد اليومية إجباري — غير محدد";
        chkRequireJournalDescription.AccessibleName = "إدخال بيان قيد اليومية إجباري";
        chkRequireJournalDescription.ThreeState = true;
        chkRequireJournalDescription.CheckState = CheckState.Indeterminate;
        chkRequireJournalDescription.AutoSize = true;
        chkRequireJournalDescription.Dock = DockStyle.Fill;
        chkRequireJournalDescription.MinimumSize = new Size(0, 40);
        chkRequireJournalDescription.Margin = new Padding(16, 8, 16, 8);
        chkRequireJournalDescription.Enabled = false;
        chkRequireJournalDescription.TabIndex = 3;
        generalLayout.Controls.Add(chkRequireJournalDescription, 0, 3);
        lblJournalDescriptionHelp.Name = "lblJournalDescriptionHelp";
        lblJournalDescriptionHelp.Text = "غير محدد: لم تُحفظ قيمة لهذا الإعداد. نعم: البيان مطلوب ويظهر بالأصفر. لا: البيان اختياري. بعد الحفظ أعد فتح قيد اليومية لتحميل الإعداد؛ لا تُعدّل القيود المحفوظة.";
        lblJournalDescriptionHelp.AutoSize = true;
        lblJournalDescriptionHelp.Dock = DockStyle.Fill;
        lblJournalDescriptionHelp.Margin = new Padding(16, 4, 16, 8);
        generalLayout.Controls.Add(lblJournalDescriptionHelp, 0, 4);
        lblReviewHelp.Text = "المراحل المطلوبة تنفذ بالترتيب وبصلاحياتها: المراجعة أولًا ثم الاعتماد إن طُلبا. تعطيل مرحلة هنا لا يمنح صلاحية ولا يغير المستندات القائمة.";
        lblReviewHelp.AutoSize = true;
        lblReviewHelp.Dock = DockStyle.Fill;
        lblReviewHelp.TextAlign = ContentAlignment.MiddleLeft;
        lblReviewHelp.Margin = new Padding(8, 10, 8, 10);
        lblReviewHelp.Padding = new Padding(8);
        lblReviewHelp.TabStop = false;
        reviewLayout.Controls.Add(lblReviewHelp, 0, 0);
        lblPostingMode.Text = "طريقة الترحيل";
        lblPostingMode.AutoSize = true;
        lblPostingMode.Dock = DockStyle.Fill;
        lblPostingMode.TextAlign = ContentAlignment.MiddleLeft;
        lblPostingMode.Margin = new Padding(8, 10, 8, 10);
        lblPostingMode.Padding = new Padding(8);
        lblPostingMode.TabStop = false;
        postingLayout.Controls.Add(lblPostingMode, 0, 0);
        lblPath.Text = "حفظ مسودة ← اعتماد المسؤول ← ترحيل يدوي بصلاحية الترحيل";
        lblPath.AutoSize = true;
        lblPath.Dock = DockStyle.Fill;
        lblPath.TextAlign = ContentAlignment.MiddleLeft;
        lblPath.Margin = new Padding(8, 10, 8, 10);
        lblPath.Padding = new Padding(8);
        lblPath.TabStop = false;
        postingLayout.Controls.Add(lblPath, 0, 2);
        lblReceiptHelp.Text = "إعدادات خاصة بسند القبض: معالجة الشيك بالبنك أو أوراق القبض، الحسابات والوجهات، أنواع السند والبوليصة، القيم الافتراضية ومراجع الأبعاد. تُفتح شاشة الإعدادات الحالية وتُحفظ في مصدرها القائم.";
        lblReceiptHelp.AutoSize = true;
        lblReceiptHelp.Dock = DockStyle.Fill;
        lblReceiptHelp.TextAlign = ContentAlignment.MiddleLeft;
        lblReceiptHelp.Margin = new Padding(8, 10, 8, 10);
        lblReceiptHelp.Padding = new Padding(8);
        lblReceiptHelp.TabStop = false;
        receiptLayout.Controls.Add(lblReceiptHelp, 0, 0);
        lblReceiptScope.Text = "سياسة المراجعة والاعتماد والترحيل مصدرها الإعدادات العامة أعلاه. لا تعمم إعدادات الشيك أو البوليصة على المستندات الأخرى. فتح هذا القسم يتطلب صلاحية إعداد القبض؛ احفظ تعديلات السياسة العامة أو تراجع عنها أولًا.";
        lblReceiptScope.AutoSize = true;
        lblReceiptScope.Dock = DockStyle.Fill;
        lblReceiptScope.TextAlign = ContentAlignment.MiddleLeft;
        lblReceiptScope.Margin = new Padding(8, 10, 8, 10);
        lblReceiptScope.Padding = new Padding(8);
        lblReceiptScope.TabStop = false;
        receiptLayout.Controls.Add(lblReceiptScope, 0, 2);
        lblPolicyStatus.BackColor = Color.FromArgb(255, 249, 219);
        lblPath.BackColor = Color.FromArgb(224, 244, 250);
        chkRequireReview.Text = "اشتراط مراجعة المحاسب";
        chkRequireReview.AccessibleName = "اشتراط مراجعة المحاسب";
        chkRequireReview.AutoSize = true;
        chkRequireReview.Dock = DockStyle.Fill;
        chkRequireReview.MinimumSize = new Size(0, 40);
        chkRequireReview.Margin = new Padding(16, 8, 16, 8);
        chkRequireReview.Enabled = false;
        chkRequireReview.TabIndex = 0;
        reviewLayout.Controls.Add(chkRequireReview, 0, 1);
        chkRequireApproval.Text = "اشتراط اعتماد المسؤول";
        chkRequireApproval.AccessibleName = "اشتراط اعتماد المسؤول";
        chkRequireApproval.AutoSize = true;
        chkRequireApproval.Dock = DockStyle.Fill;
        chkRequireApproval.MinimumSize = new Size(0, 40);
        chkRequireApproval.Margin = new Padding(16, 8, 16, 8);
        chkRequireApproval.Enabled = false;
        chkRequireApproval.TabIndex = 1;
        reviewLayout.Controls.Add(chkRequireApproval, 0, 2);
        chkRequireApproval.Checked = true;
        cmbPostingMode.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbPostingMode.Items.AddRange(new object[] { "يدوي بعد اكتمال المراحل المطلوبة", "تلقائي بعد اكتمال آخر مرحلة مطلوبة" });
        cmbPostingMode.SelectedIndex = 0;
        cmbPostingMode.AccessibleName = "طريقة الترحيل";
        cmbPostingMode.Dock = DockStyle.Fill;
        cmbPostingMode.Margin = new Padding(16, 4, 16, 12);
        cmbPostingMode.Enabled = false;
        postingLayout.Controls.Add(cmbPostingMode, 0, 1);
        btnReceiptSettings.Text = "فتح إعدادات سند القبض";
        btnReceiptSettings.AccessibleName = "فتح إعدادات سند القبض";
        btnReceiptSettings.AutoSize = true;
        btnReceiptSettings.Size = new Size(250, 42);
        btnReceiptSettings.MinimumSize = new Size(250, 42);
        btnReceiptSettings.Margin = new Padding(16, 8, 16, 8);
        btnReceiptSettings.Enabled = false;
        receiptLayout.Controls.Add(btnReceiptSettings, 0, 1);
        auditGrid.Dock = DockStyle.Fill;
        auditGrid.ReadOnly = true;
        auditGrid.AllowUserToAddRows = false;
        auditGrid.AllowUserToDeleteRows = false;
        auditGrid.AutoGenerateColumns = false;
        auditGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        auditGrid.AutoSizeRowsMode = DataGridViewAutoSizeRowsMode.AllCells;
        auditGrid.DefaultCellStyle.WrapMode = DataGridViewTriState.True;
        auditGrid.RowHeadersVisible = false;
        auditGrid.BackgroundColor = Color.White;
        auditGrid.AccessibleName = "سجل تغييرات سياسة الأستاذ العام";
        auditAt.HeaderText = "الوقت (UTC)";
        auditAt.MinimumWidth = 180;
        auditAt.FillWeight = 180;
        auditActor.HeaderText = "المستخدم";
        auditActor.MinimumWidth = 150;
        auditActor.FillWeight = 150;
        auditAction.HeaderText = "الإجراء";
        auditAction.MinimumWidth = 160;
        auditAction.FillWeight = 160;
        auditReason.HeaderText = "التفاصيل";
        auditReason.MinimumWidth = 260;
        auditReason.FillWeight = 260;
        auditGrid.Columns.AddRange(new DataGridViewColumn[] { auditAt, auditActor, auditAction, auditReason });
        tpAudit.Controls.Add(auditGrid);
        lblPreview.Text = "يلزم الاتصال بالخدمة لتحميل إعدادات الشركة وحفظها.";
        lblPreview.AutoSize = true;
        lblPreview.Dock = DockStyle.Fill;
        lblPreview.Padding = new Padding(12, 6, 12, 6);
        lblPreview.ForeColor = Color.DimGray;
        lblPreview.TabStop = false;
        mainLayout.Controls.Add(lblPreview, 0, 2);
        lblDirty.Text = "لا توجد تعديلات غير محفوظة";
        lblDirty.AutoSize = true;
        lblDirty.Dock = DockStyle.Fill;
        lblDirty.Padding = new Padding(12, 6, 12, 6);
        lblDirty.BackColor = Color.FromArgb(192, 255, 255);
        lblDirty.TabStop = false;
        mainLayout.Controls.Add(lblDirty, 0, 3);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 10F);
        BackColor = Color.FromArgb(248, 250, 252);
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1200, 800);
        MinimumSize = new Size(820, 520);
        Name = "UcGeneralLedgerSettings";
        Text = "إعدادات الأستاذ العام";
        Tag = "ONYX:SCREEN-0078";
        Controls.Add(mainLayout);
        ((System.ComponentModel.ISupportInitialize)auditGrid).EndInit();
        ResumeLayout(false);
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Fill;
        designerCommandBar.TabIndex = 0;
        designerCommandBar.RightToLeft = RightToLeft.Yes;
        designerCommandBar.Controls.Add(pnlActions);
        pnlActions.Dock = DockStyle.Fill;
        pnlActions.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        pnlActions.Name = "pnlActions";
        pnlActions.Dock = DockStyle.Fill;
        pnlActions.AutoSize = false;
        pnlActions.WrapContents = false;
        pnlActions.FlowDirection = FlowDirection.RightToLeft;
        pnlActions.RightToLeft = RightToLeft.No;
        pnlActions.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 30;
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = false;
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = true;
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = false;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandView.Name = "standardCommandView";
        standardCommandView.Enabled = false;
        standardCommandView.Visible = false;
        standardCommandView.AccessibleName = "عرض";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = false;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = false;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = false;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = false;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandAdd.AutoSize = false;
        standardCommandAdd.Dock = DockStyle.None;
        standardCommandAdd.MinimumSize = Size.Empty;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandAdd.Text = "";
        pnlActions.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.AutoSize = false;
        standardCommandEdit.Dock = DockStyle.None;
        standardCommandEdit.MinimumSize = Size.Empty;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandEdit.Text = "";
        pnlActions.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        pnlActions.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        btnUndo.AutoSize = false;
        btnUndo.Dock = DockStyle.None;
        btnUndo.MinimumSize = Size.Empty;
        btnUndo.Size = new Size(26, 24);
        btnUndo.Margin = new Padding(1);
        btnUndo.FlatStyle = FlatStyle.Flat;
        btnUndo.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnUndo.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        btnUndo.Text = "";
        pnlActions.Controls.Add(btnUndo);
        designerCommandBar.SetCommandRole(btnUndo, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        standardCommandView.AutoSize = false;
        standardCommandView.Dock = DockStyle.None;
        standardCommandView.MinimumSize = Size.Empty;
        standardCommandView.Size = new Size(26, 24);
        standardCommandView.Margin = new Padding(1);
        standardCommandView.FlatStyle = FlatStyle.Flat;
        standardCommandView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        standardCommandView.Text = "";
        pnlActions.Controls.Add(standardCommandView);
        designerCommandBar.SetCommandRole(standardCommandView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        pnlActions.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        pnlActions.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        pnlActions.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        pnlActions.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        btnSave.AutoSize = false;
        btnSave.Dock = DockStyle.None;
        btnSave.MinimumSize = Size.Empty;
        btnSave.Size = new Size(26, 24);
        btnSave.Margin = new Padding(1);
        btnSave.FlatStyle = FlatStyle.Flat;
        btnSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        btnSave.Text = "";
        pnlActions.Controls.Add(btnSave);
        designerCommandBar.SetCommandRole(btnSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        pnlActions.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        btnClose.AutoSize = false;
        btnClose.Dock = DockStyle.None;
        btnClose.MinimumSize = Size.Empty;
        btnClose.Size = new Size(26, 24);
        btnClose.Margin = new Padding(1);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        btnClose.Text = "";
        designerCloseHost.Controls.Add(btnClose);
        btnClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        btnRefresh.AutoSize = false;
        btnRefresh.Dock = DockStyle.None;
        btnRefresh.MinimumSize = Size.Empty;
        btnRefresh.Size = new Size(26, 24);
        btnRefresh.Margin = new Padding(1);
        btnRefresh.FlatStyle = FlatStyle.Flat;
        btnRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnRefresh.Text = "تحديث";
        pnlActions.Controls.Add(btnRefresh);
        designerCommandBar.SetCommandRole(btnRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        pnlActions.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        pnlActions.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        pnlActions.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}

    private TableLayoutPanel mainLayout = null!;
    private Panel pnlHeader = null!;
    private Label lblTitle = null!;
    private FlowLayoutPanel pnlActions = null!;
    private Button btnSave = null!;
    private Button btnUndo = null!;
    private Button btnRefresh = null!;
    private Button btnClose = null!;
    private TabControl tabMain = null!;
    private TabPage tpGeneral = null!;
    private TabPage tpReview = null!;
    private TabPage tpPosting = null!;
    private TabPage tpReceipt = null!;
    private TabPage tpAudit = null!;
    private TableLayoutPanel generalLayout = null!;
    private TableLayoutPanel reviewLayout = null!;
    private TableLayoutPanel postingLayout = null!;
    private TableLayoutPanel receiptLayout = null!;
    private Label lblScope = null!;
    private Label lblCoverage = null!;
    private Label lblPolicyStatus = null!;
    private Label lblReviewHelp = null!;
    private CheckBox chkRequireReview = null!;
    private CheckBox chkRequireJournalDescription = null!;
    private Label lblJournalDescriptionHelp = null!;
    private CheckBox chkRequireApproval = null!;
    private Label lblPostingMode = null!;
    private ComboBox cmbPostingMode = null!;
    private Label lblPath = null!;
    private Label lblReceiptHelp = null!;
    private Button btnReceiptSettings = null!;
    private Label lblReceiptScope = null!;
    private DataGridView auditGrid = null!;
    private DataGridViewTextBoxColumn auditAt = null!;
    private DataGridViewTextBoxColumn auditActor = null!;
    private DataGridViewTextBoxColumn auditAction = null!;
    private DataGridViewTextBoxColumn auditReason = null!;
    private Label lblPreview = null!;
    private Label lblDirty = null!;
}
