using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcInventoryQuantityReservation
{
    private AuditMetadataControl standardAuditMetadata = null!;
    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private TableLayoutPanel headerLayout = null!;
    private Label lblBranch = null!;
    private ComboBox cmbBranch = null!;
    private Label lblReservationType = null!;
    private ComboBox cmbReservationType = null!;
    private Label lblReservationNumber = null!;
    private TextBox txtReservationNumber = null!;
    private DataGridView gridReservations = null!;
    private DataGridViewTextBoxColumn colSequence = null!;
    private DataGridViewTextBoxColumn colItemNumber = null!;
    private DataGridViewTextBoxColumn colItemName = null!;
    private DataGridViewTextBoxColumn colUnit = null!;
    private DataGridViewTextBoxColumn colWarehouse = null!;
    private DataGridViewTextBoxColumn colExpiryDate = null!;
    private DataGridViewTextBoxColumn colQuantity = null!;
    private DataGridViewTextBoxColumn colDispatchedQuantity = null!;
    private DataGridViewComboBoxColumn colReserved = null!;
    private DataGridViewTextBoxColumn colUntilDate = null!;
    private DataGridViewTextBoxColumn colNotes = null!;
    private Panel auditFooter = null!;
    private Label lblOperationStatus = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 6;
        mainLayout.Margin = Padding.Empty;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 110F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "حجز كميات الأصناف";
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.BackColor = Color.FromArgb(23,50,78);
        lblTitle.ForeColor = Color.White;
        mainLayout.Controls.Add(lblTitle, 0, 0);
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        commandBar.Dock = DockStyle.Fill;
        commandBar.Margin = Padding.Empty;
        mainLayout.Controls.Add(commandBar, 0, 1);
        headerLayout = new TableLayoutPanel();
        headerLayout.Name = "headerLayout";
        headerLayout.Dock = DockStyle.Fill;
        headerLayout.ColumnCount = 6;
        headerLayout.RowCount = 3;
        headerLayout.Padding = new Padding(4);
        headerLayout.Margin = Padding.Empty;
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 88F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 88F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 29F));
        lblBranch = new Label();
        lblBranch.Name = "lblBranch";
        lblBranch.Text = "الفرع";
        lblBranch.Dock = DockStyle.Fill;
        lblBranch.TextAlign = ContentAlignment.MiddleRight;
        cmbBranch = new ComboBox();
        cmbBranch.Name = "cmbBranch";
        cmbBranch.Dock = DockStyle.Fill;
        cmbBranch.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbBranch.AccessibleName = "الفرع";
        lblReservationType = new Label();
        lblReservationType.Name = "lblReservationType";
        lblReservationType.Text = "نوع الحجز";
        lblReservationType.Dock = DockStyle.Fill;
        lblReservationType.TextAlign = ContentAlignment.MiddleRight;
        cmbReservationType = new ComboBox();
        cmbReservationType.Name = "cmbReservationType";
        cmbReservationType.Dock = DockStyle.Fill;
        cmbReservationType.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbReservationType.AccessibleName = "نوع الحجز";
        lblReservationNumber = new Label();
        lblReservationNumber.Name = "lblReservationNumber";
        lblReservationNumber.Text = "رقم الحجز";
        lblReservationNumber.Dock = DockStyle.Fill;
        lblReservationNumber.TextAlign = ContentAlignment.MiddleRight;
        txtReservationNumber = new TextBox();
        txtReservationNumber.Name = "txtReservationNumber";
        txtReservationNumber.Dock = DockStyle.Fill;
        txtReservationNumber.ReadOnly = true;
        txtReservationNumber.BackColor = Color.LightYellow;
        txtReservationNumber.RightToLeft = RightToLeft.No;
        txtReservationNumber.AccessibleName = "رقم الحجز";
        headerLayout.Controls.Add(lblBranch, 1, 0);
        headerLayout.Controls.Add(cmbBranch, 2, 0);
        headerLayout.SetColumnSpan(cmbBranch, 3);
        headerLayout.Controls.Add(lblReservationType, 1, 1);
        headerLayout.Controls.Add(cmbReservationType, 2, 1);
        headerLayout.Controls.Add(lblReservationNumber, 3, 1);
        headerLayout.Controls.Add(txtReservationNumber, 4, 1);
        mainLayout.Controls.Add(headerLayout, 0, 2);
        gridReservations = new DataGridView();
        gridReservations.Name = "gridReservations";
        gridReservations.Dock = DockStyle.Fill;
        gridReservations.ReadOnly = true;
        gridReservations.AllowUserToAddRows = false;
        gridReservations.AllowUserToDeleteRows = false;
        gridReservations.AllowUserToOrderColumns = false;
        gridReservations.AutoGenerateColumns = false;
        gridReservations.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        gridReservations.RowHeadersVisible = false;
        gridReservations.MultiSelect = false;
        gridReservations.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        gridReservations.ColumnHeadersHeight = 34;
        gridReservations.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridReservations.BackgroundColor = Color.White;
        gridReservations.AccessibleName = "كميات الأصناف المحجوزة";
        colSequence = new DataGridViewTextBoxColumn();
        colSequence.Name = "colSequence";
        colSequence.HeaderText = "م";
        colSequence.DataPropertyName = "Sequence";
        colSequence.Width = 40;
        colSequence.FillWeight = 40F;
        colSequence.MinimumWidth = 40;
        colSequence.SortMode = DataGridViewColumnSortMode.NotSortable;
        colSequence.DefaultCellStyle.BackColor = Color.LightYellow;
        gridReservations.Columns.Add(colSequence);
        colItemNumber = new DataGridViewTextBoxColumn();
        colItemNumber.Name = "colItemNumber";
        colItemNumber.HeaderText = "رقم الصنف";
        colItemNumber.DataPropertyName = "ItemNumber";
        colItemNumber.Width = 110;
        colItemNumber.FillWeight = 110F;
        colItemNumber.MinimumWidth = 70;
        colItemNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colItemNumber.DefaultCellStyle.BackColor = Color.LightYellow;
        gridReservations.Columns.Add(colItemNumber);
        colItemName = new DataGridViewTextBoxColumn();
        colItemName.Name = "colItemName";
        colItemName.HeaderText = "اسم الصنف";
        colItemName.DataPropertyName = "ItemName";
        colItemName.Width = 260;
        colItemName.FillWeight = 260F;
        colItemName.MinimumWidth = 70;
        colItemName.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridReservations.Columns.Add(colItemName);
        colUnit = new DataGridViewTextBoxColumn();
        colUnit.Name = "colUnit";
        colUnit.HeaderText = "الوحدة";
        colUnit.DataPropertyName = "Unit";
        colUnit.Width = 65;
        colUnit.FillWeight = 65F;
        colUnit.MinimumWidth = 65;
        colUnit.SortMode = DataGridViewColumnSortMode.NotSortable;
        colUnit.DefaultCellStyle.BackColor = Color.LightYellow;
        gridReservations.Columns.Add(colUnit);
        colWarehouse = new DataGridViewTextBoxColumn();
        colWarehouse.Name = "colWarehouse";
        colWarehouse.HeaderText = "المخزن";
        colWarehouse.DataPropertyName = "Warehouse";
        colWarehouse.Width = 65;
        colWarehouse.FillWeight = 65F;
        colWarehouse.MinimumWidth = 65;
        colWarehouse.SortMode = DataGridViewColumnSortMode.NotSortable;
        colWarehouse.DefaultCellStyle.BackColor = Color.LightYellow;
        gridReservations.Columns.Add(colWarehouse);
        colExpiryDate = new DataGridViewTextBoxColumn();
        colExpiryDate.Name = "colExpiryDate";
        colExpiryDate.HeaderText = "تاريخ الانتهاء";
        colExpiryDate.DataPropertyName = "ExpiryDate";
        colExpiryDate.Width = 105;
        colExpiryDate.FillWeight = 105F;
        colExpiryDate.MinimumWidth = 70;
        colExpiryDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        colExpiryDate.DefaultCellStyle.BackColor = Color.LightCyan;
        gridReservations.Columns.Add(colExpiryDate);
        colQuantity = new DataGridViewTextBoxColumn();
        colQuantity.Name = "colQuantity";
        colQuantity.HeaderText = "الكمية";
        colQuantity.DataPropertyName = "Quantity";
        colQuantity.Width = 75;
        colQuantity.FillWeight = 75F;
        colQuantity.MinimumWidth = 70;
        colQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        colQuantity.DefaultCellStyle.BackColor = Color.LightYellow;
        gridReservations.Columns.Add(colQuantity);
        colDispatchedQuantity = new DataGridViewTextBoxColumn();
        colDispatchedQuantity.Name = "colDispatchedQuantity";
        colDispatchedQuantity.HeaderText = "الكمية المنصرفة";
        colDispatchedQuantity.DataPropertyName = "DispatchedQuantity";
        colDispatchedQuantity.Width = 95;
        colDispatchedQuantity.FillWeight = 95F;
        colDispatchedQuantity.MinimumWidth = 70;
        colDispatchedQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        colDispatchedQuantity.DefaultCellStyle.BackColor = Color.LightYellow;
        gridReservations.Columns.Add(colDispatchedQuantity);
        colReserved = new DataGridViewComboBoxColumn();
        colReserved.Name = "colReserved";
        colReserved.HeaderText = "حجز الكميات";
        colReserved.DataPropertyName = "Reserved";
        colReserved.Width = 95;
        colReserved.FillWeight = 95F;
        colReserved.MinimumWidth = 70;
        colReserved.SortMode = DataGridViewColumnSortMode.NotSortable;
        colReserved.Items.AddRange(new object[] { "نعم" });
        gridReservations.Columns.Add(colReserved);
        colUntilDate = new DataGridViewTextBoxColumn();
        colUntilDate.Name = "colUntilDate";
        colUntilDate.HeaderText = "إلى تاريخ";
        colUntilDate.DataPropertyName = "UntilDate";
        colUntilDate.Width = 105;
        colUntilDate.FillWeight = 105F;
        colUntilDate.MinimumWidth = 70;
        colUntilDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridReservations.Columns.Add(colUntilDate);
        colNotes = new DataGridViewTextBoxColumn();
        colNotes.Name = "colNotes";
        colNotes.HeaderText = "ملاحظات";
        colNotes.DataPropertyName = "Notes";
        colNotes.Width = 180;
        colNotes.FillWeight = 180F;
        colNotes.MinimumWidth = 70;
        colNotes.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridReservations.Columns.Add(colNotes);
        mainLayout.Controls.Add(gridReservations, 0, 3);
        auditFooter = new Panel();
        auditFooter.Name = "auditFooter";
        auditFooter.Dock = DockStyle.Fill;
        auditFooter.Margin = Padding.Empty;
        auditFooter.BackColor = Color.FromArgb(232,227,246);
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Fill;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.Profile = AuditMetadataProfile.Standard;
        auditFooter.Controls.Add(standardAuditMetadata);
        mainLayout.Controls.Add(auditFooter, 0, 4);
        lblOperationStatus = new Label();
        lblOperationStatus.Name = "lblOperationStatus";
        lblOperationStatus.Text = "لم يتم ربط بيانات المخزون وصلاحيات حجز الكميات بعد.";
        lblOperationStatus.Dock = DockStyle.Fill;
        lblOperationStatus.TextAlign = ContentAlignment.MiddleRight;
        mainLayout.Controls.Add(lblOperationStatus, 0, 5);
        AutoScaleMode = AutoScaleMode.Dpi;
        AutoScaleDimensions = new SizeF(96F,96F);
        Font = new Font("Tahoma",9F);
        RightToLeft = RightToLeft.Yes;
        Name = "UcInventoryQuantityReservation";
        Text = "حجز كميات الأصناف";
        Size = new Size(1180,720);
        MinimumSize = new Size(1040,620);
        BackColor = Color.FromArgb(244,244,244);
        Controls.Add(mainLayout);
        ResumeLayout(false);
    }
}
