using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcInventoryTransferReceipt
{
    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private TabControl tabs = null!;
    private TabPage tabMain = null!;
    private TableLayoutPanel documentLayout = null!;
    private TableLayoutPanel headerLayout = null!;
    private Button btnJournalView = null!;
    private FlowLayoutPanel actionsLayout = null!;
    private CheckBox chkPosted = null!;
    private CheckBox chkSuspended = null!;
    private CheckBox chkManualItems = null!;
    private CheckBox chkTransferReturn = null!;
    private Button btnLoadItems = null!;
    private Button btnTransferLookup = null!;
    private DataGridView gridItems = null!;
    private Panel auditFooter = null!;
    private AuditMetadataControl standardAuditMetadata = null!;
    private Label lblBranch = null!;
    private ComboBox fieldBranch = null!;
    private Label lblReceiptType = null!;
    private ComboBox fieldReceiptType = null!;
    private Label lblReceiptNumber = null!;
    private TextBox fieldReceiptNumber = null!;
    private Label lblWarehouse = null!;
    private ComboBox fieldWarehouse = null!;
    private Label lblSourceWarehouse = null!;
    private ComboBox fieldSourceWarehouse = null!;
    private Label lblDate = null!;
    private TextBox fieldDate = null!;
    private Label lblDescription = null!;
    private TextBox fieldDescription = null!;
    private Label lblReference = null!;
    private TextBox fieldReference = null!;
    private Label lblCostCenter = null!;
    private ComboBox fieldCostCenter = null!;
    private Label lblDriver = null!;
    private ComboBox fieldDriver = null!;
    private Label lblTransferNumber = null!;
    private TextBox fieldTransferNumber = null!;
    private DataGridViewTextBoxColumn colSequence = null!;
    private DataGridViewButtonColumn colLookup = null!;
    private DataGridViewTextBoxColumn colItemNumber = null!;
    private DataGridViewTextBoxColumn colItemName = null!;
    private DataGridViewTextBoxColumn colUnit = null!;
    private DataGridViewTextBoxColumn colExpiryDate = null!;
    private DataGridViewTextBoxColumn colTransferredQuantity = null!;
    private DataGridViewTextBoxColumn colReceivedQuantity = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        tabs = new TabControl();
        tabs.Name = "tabs";
        tabMain = new TabPage();
        tabMain.Name = "tabMain";
        documentLayout = new TableLayoutPanel();
        documentLayout.Name = "documentLayout";
        headerLayout = new TableLayoutPanel();
        headerLayout.Name = "headerLayout";
        btnJournalView = new Button();
        btnJournalView.Name = "btnJournalView";
        btnJournalView.Text = "اليومية العامة";
        btnJournalView.AccessibleName = "اليومية العامة";
        btnJournalView.AutoSize = true;
        btnJournalView.Click += JournalView_Click;
        actionsLayout = new FlowLayoutPanel();
        actionsLayout.Name = "actionsLayout";
        chkPosted = new CheckBox();
        chkPosted.Name = "chkPosted";
        chkSuspended = new CheckBox();
        chkSuspended.Name = "chkSuspended";
        chkManualItems = new CheckBox();
        chkManualItems.Name = "chkManualItems";
        chkTransferReturn = new CheckBox();
        chkTransferReturn.Name = "chkTransferReturn";
        btnLoadItems = new Button();
        btnLoadItems.Name = "btnLoadItems";
        btnTransferLookup = new Button();
        btnTransferLookup.Name = "btnTransferLookup";
        gridItems = new DataGridView();
        gridItems.Name = "gridItems";
        auditFooter = new Panel();
        auditFooter.Name = "auditFooter";
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        lblBranch = new Label();
        lblBranch.Name = "lblBranch";
        fieldBranch = new ComboBox();
        fieldBranch.Name = "fieldBranch";
        lblReceiptType = new Label();
        lblReceiptType.Name = "lblReceiptType";
        fieldReceiptType = new ComboBox();
        fieldReceiptType.Name = "fieldReceiptType";
        lblReceiptNumber = new Label();
        lblReceiptNumber.Name = "lblReceiptNumber";
        fieldReceiptNumber = new TextBox();
        fieldReceiptNumber.Name = "fieldReceiptNumber";
        lblWarehouse = new Label();
        lblWarehouse.Name = "lblWarehouse";
        fieldWarehouse = new ComboBox();
        fieldWarehouse.Name = "fieldWarehouse";
        lblSourceWarehouse = new Label();
        lblSourceWarehouse.Name = "lblSourceWarehouse";
        fieldSourceWarehouse = new ComboBox();
        fieldSourceWarehouse.Name = "fieldSourceWarehouse";
        lblDate = new Label();
        lblDate.Name = "lblDate";
        fieldDate = new TextBox();
        fieldDate.Name = "fieldDate";
        lblDescription = new Label();
        lblDescription.Name = "lblDescription";
        fieldDescription = new TextBox();
        fieldDescription.Name = "fieldDescription";
        lblReference = new Label();
        lblReference.Name = "lblReference";
        fieldReference = new TextBox();
        fieldReference.Name = "fieldReference";
        lblCostCenter = new Label();
        lblCostCenter.Name = "lblCostCenter";
        fieldCostCenter = new ComboBox();
        fieldCostCenter.Name = "fieldCostCenter";
        lblDriver = new Label();
        lblDriver.Name = "lblDriver";
        fieldDriver = new ComboBox();
        fieldDriver.Name = "fieldDriver";
        lblTransferNumber = new Label();
        lblTransferNumber.Name = "lblTransferNumber";
        fieldTransferNumber = new TextBox();
        fieldTransferNumber.Name = "fieldTransferNumber";
        fieldTransferNumber.KeyDown += LookupVisual_KeyDown;
        colSequence = new DataGridViewTextBoxColumn();
        colSequence.Name = "colSequence";
        colLookup = new DataGridViewButtonColumn();
        colLookup.Name = "colLookup";
        colItemNumber = new DataGridViewTextBoxColumn();
        colItemNumber.Name = "colItemNumber";
        colItemName = new DataGridViewTextBoxColumn();
        colItemName.Name = "colItemName";
        colUnit = new DataGridViewTextBoxColumn();
        colUnit.Name = "colUnit";
        colExpiryDate = new DataGridViewTextBoxColumn();
        colExpiryDate.Name = "colExpiryDate";
        colTransferredQuantity = new DataGridViewTextBoxColumn();
        colTransferredQuantity.Name = "colTransferredQuantity";
        colReceivedQuantity = new DataGridViewTextBoxColumn();
        colReceivedQuantity.Name = "colReceivedQuantity";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = Padding.Empty;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.BackColor = Color.FromArgb(23, 50, 78);
        lblTitle.ForeColor = Color.White;
        commandBar.Dock = DockStyle.Fill;
        commandBar.Margin = Padding.Empty;
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeftLayout = true;
        tabMain.Text = "البيانات الرئيسية";
        tabMain.Padding = Padding.Empty;
        tabs.Controls.Add(tabMain);
        documentLayout.Dock = DockStyle.Fill;
        documentLayout.ColumnCount = 1;
        documentLayout.RowCount = 3;
        documentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 140F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tabMain.Controls.Add(documentLayout);
        headerLayout.Dock = DockStyle.Fill;
        headerLayout.Padding = new Padding(10, 6, 10, 6);
        headerLayout.Margin = Padding.Empty;
        headerLayout.ColumnCount = 6;
        headerLayout.RowCount = 4;
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        lblBranch.Text = "الفرع";
        lblBranch.Dock = DockStyle.Fill;
        lblBranch.TextAlign = ContentAlignment.MiddleLeft;
        fieldBranch.AccessibleName = "الفرع";
        fieldBranch.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblBranch, 0, 0);
        headerLayout.Controls.Add(fieldBranch, 1, 0);
        fieldBranch.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldBranch.Enabled = false;
        lblReceiptType.Text = "نوع الاستلام";
        lblReceiptType.Dock = DockStyle.Fill;
        lblReceiptType.TextAlign = ContentAlignment.MiddleLeft;
        fieldReceiptType.AccessibleName = "نوع الاستلام";
        fieldReceiptType.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblReceiptType, 2, 0);
        headerLayout.Controls.Add(fieldReceiptType, 3, 0);
        fieldReceiptType.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldReceiptType.Enabled = false;
        lblReceiptNumber.Text = "رقم الاستلام";
        lblReceiptNumber.Dock = DockStyle.Fill;
        lblReceiptNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldReceiptNumber.AccessibleName = "رقم الاستلام";
        fieldReceiptNumber.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblReceiptNumber, 4, 0);
        headerLayout.Controls.Add(fieldReceiptNumber, 5, 0);
        fieldReceiptNumber.ReadOnly = true;
        lblWarehouse.Text = "رقم المخزن";
        lblWarehouse.Dock = DockStyle.Fill;
        lblWarehouse.TextAlign = ContentAlignment.MiddleLeft;
        fieldWarehouse.AccessibleName = "رقم المخزن";
        fieldWarehouse.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblWarehouse, 0, 1);
        headerLayout.Controls.Add(fieldWarehouse, 1, 1);
        fieldWarehouse.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldWarehouse.Enabled = false;
        lblSourceWarehouse.Text = "المخزن المحول منه";
        lblSourceWarehouse.Dock = DockStyle.Fill;
        lblSourceWarehouse.TextAlign = ContentAlignment.MiddleLeft;
        fieldSourceWarehouse.AccessibleName = "المخزن المحول منه";
        fieldSourceWarehouse.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblSourceWarehouse, 2, 1);
        headerLayout.Controls.Add(fieldSourceWarehouse, 3, 1);
        fieldSourceWarehouse.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldSourceWarehouse.Enabled = false;
        lblDate.Text = "تاريخ الاستلام";
        lblDate.Dock = DockStyle.Fill;
        lblDate.TextAlign = ContentAlignment.MiddleLeft;
        fieldDate.AccessibleName = "تاريخ الاستلام";
        fieldDate.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDate, 4, 1);
        headerLayout.Controls.Add(fieldDate, 5, 1);
        fieldDate.ReadOnly = true;
        lblDescription.Text = "البيان";
        lblDescription.Dock = DockStyle.Fill;
        lblDescription.TextAlign = ContentAlignment.MiddleLeft;
        fieldDescription.AccessibleName = "البيان";
        fieldDescription.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDescription, 0, 2);
        headerLayout.Controls.Add(fieldDescription, 1, 2);
        fieldDescription.ReadOnly = true;
        lblReference.Text = "رقم المرجع";
        lblReference.Dock = DockStyle.Fill;
        lblReference.TextAlign = ContentAlignment.MiddleLeft;
        fieldReference.AccessibleName = "رقم المرجع";
        fieldReference.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblReference, 2, 2);
        headerLayout.Controls.Add(fieldReference, 3, 2);
        fieldReference.ReadOnly = true;
        lblCostCenter.Text = "مركز التكلفة";
        lblCostCenter.Dock = DockStyle.Fill;
        lblCostCenter.TextAlign = ContentAlignment.MiddleLeft;
        fieldCostCenter.AccessibleName = "مركز التكلفة";
        fieldCostCenter.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblCostCenter, 4, 2);
        headerLayout.Controls.Add(fieldCostCenter, 5, 2);
        fieldCostCenter.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldCostCenter.Enabled = false;
        lblDriver.Text = "رقم السائق";
        lblDriver.Dock = DockStyle.Fill;
        lblDriver.TextAlign = ContentAlignment.MiddleLeft;
        fieldDriver.AccessibleName = "رقم السائق";
        fieldDriver.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDriver, 0, 3);
        headerLayout.Controls.Add(fieldDriver, 1, 3);
        fieldDriver.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldDriver.Enabled = false;
        lblTransferNumber.Text = "رقم التحويل";
        lblTransferNumber.Dock = DockStyle.Fill;
        lblTransferNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldTransferNumber.AccessibleName = "رقم التحويل";
        fieldTransferNumber.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblTransferNumber, 2, 3);
        headerLayout.Controls.Add(fieldTransferNumber, 3, 3);
        fieldTransferNumber.ReadOnly = true;
        actionsLayout.Dock = DockStyle.Fill;
        actionsLayout.FlowDirection = FlowDirection.RightToLeft;
        actionsLayout.WrapContents = false;
        actionsLayout.Margin = Padding.Empty;
        actionsLayout.Controls.Add(btnJournalView);
        chkPosted.Text = "مرحل";
        chkPosted.AutoSize = true;
        chkPosted.Enabled = false;
        actionsLayout.Controls.Add(chkPosted);
        chkSuspended.Text = "تعليق";
        chkSuspended.AutoSize = true;
        chkSuspended.Enabled = false;
        actionsLayout.Controls.Add(chkSuspended);
        chkManualItems.Text = "إدخال يدوي للأصناف";
        chkManualItems.AutoSize = true;
        chkManualItems.Enabled = false;
        actionsLayout.Controls.Add(chkManualItems);
        chkTransferReturn.Text = "مرتجع تحويل";
        chkTransferReturn.AutoSize = true;
        chkTransferReturn.Enabled = false;
        actionsLayout.Controls.Add(chkTransferReturn);
        btnLoadItems.Text = "إنزال الأصناف";
        btnLoadItems.AutoSize = true;
        btnLoadItems.Enabled = false;
        actionsLayout.Controls.Add(btnLoadItems);
        btnTransferLookup.Text = "…";
        btnTransferLookup.AccessibleName = "التحويلات المخزنية";
        btnTransferLookup.Width = 35;
        btnTransferLookup.Enabled = false;
        actionsLayout.Controls.Add(btnTransferLookup);
        fieldReceiptType.Items.Add("استلام مخزني");
        gridItems.Dock = DockStyle.Fill;
        gridItems.AccessibleName = "أصناف استلام التحويل المخزني";
        gridItems.ReadOnly = true;
        gridItems.AllowUserToAddRows = false;
        gridItems.AllowUserToDeleteRows = false;
        gridItems.AutoGenerateColumns = false;
        gridItems.RowHeadersVisible = false;
        gridItems.BackgroundColor = Color.White;
        gridItems.ColumnHeadersHeight = 34;
        gridItems.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridItems.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        colSequence.HeaderText = "م";
        colSequence.Width = 45;
        colSequence.ReadOnly = true;
        colSequence.SortMode = DataGridViewColumnSortMode.NotSortable;
        colLookup.HeaderText = "";
        colLookup.Width = 35;
        colLookup.ReadOnly = true;
        colLookup.SortMode = DataGridViewColumnSortMode.NotSortable;
        colLookup.Text = "…";
        colLookup.UseColumnTextForButtonValue = true;
        colItemNumber.HeaderText = "رقم الصنف";
        colItemNumber.Width = 150;
        colItemNumber.ReadOnly = true;
        colItemNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colItemName.HeaderText = "اسم الصنف";
        colItemName.Width = 270;
        colItemName.ReadOnly = true;
        colItemName.SortMode = DataGridViewColumnSortMode.NotSortable;
        colUnit.HeaderText = "الوحدة";
        colUnit.Width = 85;
        colUnit.ReadOnly = true;
        colUnit.SortMode = DataGridViewColumnSortMode.NotSortable;
        colExpiryDate.HeaderText = "تاريخ الانتهاء";
        colExpiryDate.Width = 125;
        colExpiryDate.ReadOnly = true;
        colExpiryDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        colTransferredQuantity.HeaderText = "ك المحولة";
        colTransferredQuantity.Width = 125;
        colTransferredQuantity.ReadOnly = true;
        colTransferredQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        colReceivedQuantity.HeaderText = "ك المستلمة";
        colReceivedQuantity.Width = 125;
        colReceivedQuantity.ReadOnly = true;
        colReceivedQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.AddRange(new DataGridViewColumn[] { colSequence, colLookup, colItemNumber, colItemName, colUnit, colExpiryDate, colTransferredQuantity, colReceivedQuantity });
        documentLayout.Controls.Add(headerLayout, 0, 0);
        documentLayout.Controls.Add(actionsLayout, 0, 1);
        documentLayout.Controls.Add(gridItems, 0, 2);
        auditFooter.Dock = DockStyle.Fill;
        auditFooter.Margin = Padding.Empty;
        standardAuditMetadata.Dock = DockStyle.Fill;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.Profile = AuditMetadataProfile.Standard;
        auditFooter.Controls.Add(standardAuditMetadata);
        mainLayout.Controls.Add(lblTitle, 0, 0);
        mainLayout.Controls.Add(commandBar, 0, 1);
        mainLayout.Controls.Add(tabs, 0, 2);
        mainLayout.Controls.Add(auditFooter, 0, 3);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 9F);
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1180, 720);
        MinimumSize = new Size(1000, 600);
        Controls.Add(mainLayout);
        lblTitle.Text = "استلام تحويل مخزني";
        Name = "UcInventoryTransferReceipt";
        Text = "استلام تحويل مخزني";
        Tag = "INV:TRANSFER-RECEIPT";
        ResumeLayout(false);
    }
}
