using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcInventoryReceiptItemSearch
{
    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private TableLayoutPanel bodyLayout = null!;
    private TableLayoutPanel headerLayout = null!;
    private DataGridView gridItems = null!;
    private FlowLayoutPanel actionsLayout = null!;
    private CheckBox chkExpiryBatch = null!;
    private Button btnSearch = null!;
    private Button btnLoad = null!;
    private Button btnClose = null!;
    private AuditMetadataControl standardAuditMetadata = null!;
    private Label lblWarehouse = null!;
    private ComboBox fieldWarehouse = null!;
    private Label lblGroup = null!;
    private TextBox fieldGroup = null!;
    private Label lblSubgroup = null!;
    private TextBox fieldSubgroup = null!;
    private Label lblItemNumber = null!;
    private TextBox fieldItemNumber = null!;
    private Label lblItemName = null!;
    private TextBox fieldItemName = null!;
    private Label lblNestedSubgroup = null!;
    private TextBox fieldNestedSubgroup = null!;
    private Label lblSpecification = null!;
    private TextBox fieldSpecification = null!;
    private Label lblStorage = null!;
    private ComboBox fieldStorage = null!;
    private Label lblUnit = null!;
    private TextBox fieldUnit = null!;
    private Label lblItemType = null!;
    private ComboBox fieldItemType = null!;
    private Label lblPricing = null!;
    private ComboBox fieldPricing = null!;
    private Label lblShelf = null!;
    private TextBox fieldShelf = null!;
    private Label lblStorageQuantity = null!;
    private ComboBox fieldStorageQuantity = null!;
    private Label lblSupplier = null!;
    private TextBox fieldSupplier = null!;
    private Label lblSimilarNumber = null!;
    private TextBox fieldSimilarNumber = null!;
    private Label lblManufacturingNumber = null!;
    private TextBox fieldManufacturingNumber = null!;
    private Label lblSort = null!;
    private ComboBox fieldSort = null!;
    private Label lblPack = null!;
    private TextBox fieldPack = null!;
    private DataGridViewCheckBoxColumn colSelected = null!;
    private DataGridViewTextBoxColumn colSequence = null!;
    private DataGridViewTextBoxColumn colItemNumber = null!;
    private DataGridViewTextBoxColumn colItemName = null!;
    private DataGridViewTextBoxColumn colUnit = null!;
    private DataGridViewTextBoxColumn colWarehouse = null!;
    private DataGridViewTextBoxColumn colQuantity = null!;
    private DataGridViewTextBoxColumn colPrice = null!;
    private DataGridViewTextBoxColumn colItemType = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        bodyLayout = new TableLayoutPanel();
        bodyLayout.Name = "bodyLayout";
        headerLayout = new TableLayoutPanel();
        headerLayout.Name = "headerLayout";
        gridItems = new DataGridView();
        gridItems.Name = "gridItems";
        actionsLayout = new FlowLayoutPanel();
        actionsLayout.Name = "actionsLayout";
        chkExpiryBatch = new CheckBox();
        chkExpiryBatch.Name = "chkExpiryBatch";
        btnSearch = new Button();
        btnSearch.Name = "btnSearch";
        btnLoad = new Button();
        btnLoad.Name = "btnLoad";
        btnClose = new Button();
        btnClose.Name = "btnClose";
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        lblWarehouse = new Label();
        lblWarehouse.Name = "lblWarehouse";
        fieldWarehouse = new ComboBox();
        fieldWarehouse.Name = "fieldWarehouse";
        lblGroup = new Label();
        lblGroup.Name = "lblGroup";
        fieldGroup = new TextBox();
        fieldGroup.Name = "fieldGroup";
        lblSubgroup = new Label();
        lblSubgroup.Name = "lblSubgroup";
        fieldSubgroup = new TextBox();
        fieldSubgroup.Name = "fieldSubgroup";
        lblItemNumber = new Label();
        lblItemNumber.Name = "lblItemNumber";
        fieldItemNumber = new TextBox();
        fieldItemNumber.Name = "fieldItemNumber";
        lblItemName = new Label();
        lblItemName.Name = "lblItemName";
        fieldItemName = new TextBox();
        fieldItemName.Name = "fieldItemName";
        lblNestedSubgroup = new Label();
        lblNestedSubgroup.Name = "lblNestedSubgroup";
        fieldNestedSubgroup = new TextBox();
        fieldNestedSubgroup.Name = "fieldNestedSubgroup";
        lblSpecification = new Label();
        lblSpecification.Name = "lblSpecification";
        fieldSpecification = new TextBox();
        fieldSpecification.Name = "fieldSpecification";
        lblStorage = new Label();
        lblStorage.Name = "lblStorage";
        fieldStorage = new ComboBox();
        fieldStorage.Name = "fieldStorage";
        lblUnit = new Label();
        lblUnit.Name = "lblUnit";
        fieldUnit = new TextBox();
        fieldUnit.Name = "fieldUnit";
        lblItemType = new Label();
        lblItemType.Name = "lblItemType";
        fieldItemType = new ComboBox();
        fieldItemType.Name = "fieldItemType";
        lblPricing = new Label();
        lblPricing.Name = "lblPricing";
        fieldPricing = new ComboBox();
        fieldPricing.Name = "fieldPricing";
        lblShelf = new Label();
        lblShelf.Name = "lblShelf";
        fieldShelf = new TextBox();
        fieldShelf.Name = "fieldShelf";
        lblStorageQuantity = new Label();
        lblStorageQuantity.Name = "lblStorageQuantity";
        fieldStorageQuantity = new ComboBox();
        fieldStorageQuantity.Name = "fieldStorageQuantity";
        lblSupplier = new Label();
        lblSupplier.Name = "lblSupplier";
        fieldSupplier = new TextBox();
        fieldSupplier.Name = "fieldSupplier";
        lblSimilarNumber = new Label();
        lblSimilarNumber.Name = "lblSimilarNumber";
        fieldSimilarNumber = new TextBox();
        fieldSimilarNumber.Name = "fieldSimilarNumber";
        lblManufacturingNumber = new Label();
        lblManufacturingNumber.Name = "lblManufacturingNumber";
        fieldManufacturingNumber = new TextBox();
        fieldManufacturingNumber.Name = "fieldManufacturingNumber";
        lblSort = new Label();
        lblSort.Name = "lblSort";
        fieldSort = new ComboBox();
        fieldSort.Name = "fieldSort";
        lblPack = new Label();
        lblPack.Name = "lblPack";
        fieldPack = new TextBox();
        fieldPack.Name = "fieldPack";
        colSelected = new DataGridViewCheckBoxColumn();
        colSelected.Name = "colSelected";
        colSequence = new DataGridViewTextBoxColumn();
        colSequence.Name = "colSequence";
        colItemNumber = new DataGridViewTextBoxColumn();
        colItemNumber.Name = "colItemNumber";
        colItemName = new DataGridViewTextBoxColumn();
        colItemName.Name = "colItemName";
        colUnit = new DataGridViewTextBoxColumn();
        colUnit.Name = "colUnit";
        colWarehouse = new DataGridViewTextBoxColumn();
        colWarehouse.Name = "colWarehouse";
        colQuantity = new DataGridViewTextBoxColumn();
        colQuantity.Name = "colQuantity";
        colPrice = new DataGridViewTextBoxColumn();
        colPrice.Name = "colPrice";
        colItemType = new DataGridViewTextBoxColumn();
        colItemType.Name = "colItemType";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        lblTitle.Text = "البحث عن الأصناف / Item Search";
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.BackColor = Color.FromArgb(23, 50, 78);
        lblTitle.ForeColor = Color.White;
        commandBar.Dock = DockStyle.Fill;
        bodyLayout.Dock = DockStyle.Fill;
        bodyLayout.ColumnCount = 1;
        bodyLayout.RowCount = 3;
        bodyLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 204F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
        headerLayout.Dock = DockStyle.Fill;
        headerLayout.Padding = new Padding(10, 6, 10, 6);
        headerLayout.ColumnCount = 6;
        headerLayout.RowCount = 6;
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33333F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        lblWarehouse.Text = "رقم المخزن";
        lblWarehouse.Dock = DockStyle.Fill;
        lblWarehouse.TextAlign = ContentAlignment.MiddleLeft;
        fieldWarehouse.AccessibleName = "رقم المخزن";
        fieldWarehouse.Dock = DockStyle.Fill;
        fieldWarehouse.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldWarehouse.Enabled = false;
        headerLayout.Controls.Add(lblWarehouse, 0, 0);
        headerLayout.Controls.Add(fieldWarehouse, 1, 0);
        lblGroup.Text = "من المجموعة رقم";
        lblGroup.Dock = DockStyle.Fill;
        lblGroup.TextAlign = ContentAlignment.MiddleLeft;
        fieldGroup.AccessibleName = "من المجموعة رقم";
        fieldGroup.Dock = DockStyle.Fill;
        fieldGroup.ReadOnly = true;
        headerLayout.Controls.Add(lblGroup, 2, 0);
        headerLayout.Controls.Add(fieldGroup, 3, 0);
        lblSubgroup.Text = "رقم م.الفرعية";
        lblSubgroup.Dock = DockStyle.Fill;
        lblSubgroup.TextAlign = ContentAlignment.MiddleLeft;
        fieldSubgroup.AccessibleName = "رقم م.الفرعية";
        fieldSubgroup.Dock = DockStyle.Fill;
        fieldSubgroup.ReadOnly = true;
        headerLayout.Controls.Add(lblSubgroup, 4, 0);
        headerLayout.Controls.Add(fieldSubgroup, 5, 0);
        lblItemNumber.Text = "رقم الصنف";
        lblItemNumber.Dock = DockStyle.Fill;
        lblItemNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldItemNumber.AccessibleName = "رقم الصنف";
        fieldItemNumber.Dock = DockStyle.Fill;
        fieldItemNumber.ReadOnly = true;
        headerLayout.Controls.Add(lblItemNumber, 0, 1);
        headerLayout.Controls.Add(fieldItemNumber, 1, 1);
        lblItemName.Text = "اسم الصنف";
        lblItemName.Dock = DockStyle.Fill;
        lblItemName.TextAlign = ContentAlignment.MiddleLeft;
        fieldItemName.AccessibleName = "اسم الصنف";
        fieldItemName.Dock = DockStyle.Fill;
        fieldItemName.ReadOnly = true;
        headerLayout.Controls.Add(lblItemName, 2, 1);
        headerLayout.Controls.Add(fieldItemName, 3, 1);
        lblNestedSubgroup.Text = "رقم م.تحت الفرعية";
        lblNestedSubgroup.Dock = DockStyle.Fill;
        lblNestedSubgroup.TextAlign = ContentAlignment.MiddleLeft;
        fieldNestedSubgroup.AccessibleName = "رقم م.تحت الفرعية";
        fieldNestedSubgroup.Dock = DockStyle.Fill;
        fieldNestedSubgroup.ReadOnly = true;
        headerLayout.Controls.Add(lblNestedSubgroup, 4, 1);
        headerLayout.Controls.Add(fieldNestedSubgroup, 5, 1);
        lblSpecification.Text = "مواصفات الصنف";
        lblSpecification.Dock = DockStyle.Fill;
        lblSpecification.TextAlign = ContentAlignment.MiddleLeft;
        fieldSpecification.AccessibleName = "مواصفات الصنف";
        fieldSpecification.Dock = DockStyle.Fill;
        fieldSpecification.ReadOnly = true;
        headerLayout.Controls.Add(lblSpecification, 0, 2);
        headerLayout.Controls.Add(fieldSpecification, 1, 2);
        lblStorage.Text = "تخزين الأصناف";
        lblStorage.Dock = DockStyle.Fill;
        lblStorage.TextAlign = ContentAlignment.MiddleLeft;
        fieldStorage.AccessibleName = "تخزين الأصناف";
        fieldStorage.Dock = DockStyle.Fill;
        fieldStorage.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldStorage.Enabled = false;
        headerLayout.Controls.Add(lblStorage, 2, 2);
        headerLayout.Controls.Add(fieldStorage, 3, 2);
        lblUnit.Text = "الوحدة";
        lblUnit.Dock = DockStyle.Fill;
        lblUnit.TextAlign = ContentAlignment.MiddleLeft;
        fieldUnit.AccessibleName = "الوحدة";
        fieldUnit.Dock = DockStyle.Fill;
        fieldUnit.ReadOnly = true;
        headerLayout.Controls.Add(lblUnit, 4, 2);
        headerLayout.Controls.Add(fieldUnit, 5, 2);
        lblItemType.Text = "نوع الصنف";
        lblItemType.Dock = DockStyle.Fill;
        lblItemType.TextAlign = ContentAlignment.MiddleLeft;
        fieldItemType.AccessibleName = "نوع الصنف";
        fieldItemType.Dock = DockStyle.Fill;
        fieldItemType.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldItemType.Enabled = false;
        headerLayout.Controls.Add(lblItemType, 0, 3);
        headerLayout.Controls.Add(fieldItemType, 1, 3);
        lblPricing.Text = "تسعير الأصناف";
        lblPricing.Dock = DockStyle.Fill;
        lblPricing.TextAlign = ContentAlignment.MiddleLeft;
        fieldPricing.AccessibleName = "تسعير الأصناف";
        fieldPricing.Dock = DockStyle.Fill;
        fieldPricing.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldPricing.Enabled = false;
        headerLayout.Controls.Add(lblPricing, 2, 3);
        headerLayout.Controls.Add(fieldPricing, 3, 3);
        lblShelf.Text = "رقم الرف";
        lblShelf.Dock = DockStyle.Fill;
        lblShelf.TextAlign = ContentAlignment.MiddleLeft;
        fieldShelf.AccessibleName = "رقم الرف";
        fieldShelf.Dock = DockStyle.Fill;
        fieldShelf.ReadOnly = true;
        headerLayout.Controls.Add(lblShelf, 4, 3);
        headerLayout.Controls.Add(fieldShelf, 5, 3);
        lblStorageQuantity.Text = "كمية التخزين";
        lblStorageQuantity.Dock = DockStyle.Fill;
        lblStorageQuantity.TextAlign = ContentAlignment.MiddleLeft;
        fieldStorageQuantity.AccessibleName = "كمية التخزين";
        fieldStorageQuantity.Dock = DockStyle.Fill;
        fieldStorageQuantity.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldStorageQuantity.Enabled = false;
        headerLayout.Controls.Add(lblStorageQuantity, 0, 4);
        headerLayout.Controls.Add(fieldStorageQuantity, 1, 4);
        lblSupplier.Text = "رقم المورد";
        lblSupplier.Dock = DockStyle.Fill;
        lblSupplier.TextAlign = ContentAlignment.MiddleLeft;
        fieldSupplier.AccessibleName = "رقم المورد";
        fieldSupplier.Dock = DockStyle.Fill;
        fieldSupplier.ReadOnly = true;
        headerLayout.Controls.Add(lblSupplier, 2, 4);
        headerLayout.Controls.Add(fieldSupplier, 3, 4);
        lblSimilarNumber.Text = "ر. المماثلة";
        lblSimilarNumber.Dock = DockStyle.Fill;
        lblSimilarNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldSimilarNumber.AccessibleName = "ر. المماثلة";
        fieldSimilarNumber.Dock = DockStyle.Fill;
        fieldSimilarNumber.ReadOnly = true;
        headerLayout.Controls.Add(lblSimilarNumber, 4, 4);
        headerLayout.Controls.Add(fieldSimilarNumber, 5, 4);
        lblManufacturingNumber.Text = "رقم التصنيع";
        lblManufacturingNumber.Dock = DockStyle.Fill;
        lblManufacturingNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldManufacturingNumber.AccessibleName = "رقم التصنيع";
        fieldManufacturingNumber.Dock = DockStyle.Fill;
        fieldManufacturingNumber.ReadOnly = true;
        headerLayout.Controls.Add(lblManufacturingNumber, 0, 5);
        headerLayout.Controls.Add(fieldManufacturingNumber, 1, 5);
        lblSort.Text = "الترتيب حسب";
        lblSort.Dock = DockStyle.Fill;
        lblSort.TextAlign = ContentAlignment.MiddleLeft;
        fieldSort.AccessibleName = "الترتيب حسب";
        fieldSort.Dock = DockStyle.Fill;
        fieldSort.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldSort.Enabled = false;
        headerLayout.Controls.Add(lblSort, 2, 5);
        headerLayout.Controls.Add(fieldSort, 3, 5);
        lblPack.Text = "العبوة";
        lblPack.Dock = DockStyle.Fill;
        lblPack.TextAlign = ContentAlignment.MiddleLeft;
        fieldPack.AccessibleName = "العبوة";
        fieldPack.Dock = DockStyle.Fill;
        fieldPack.ReadOnly = true;
        headerLayout.Controls.Add(lblPack, 4, 5);
        headerLayout.Controls.Add(fieldPack, 5, 5);
        gridItems.Dock = DockStyle.Fill;
        gridItems.AllowUserToAddRows = false;
        gridItems.AllowUserToDeleteRows = false;
        gridItems.ReadOnly = true;
        gridItems.RowHeadersVisible = false;
        gridItems.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        gridItems.BackgroundColor = Color.White;
        gridItems.ColumnHeadersHeight = 30;
        gridItems.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        colSelected.HeaderText = "";
        colSelected.Width = 35;
        colSelected.ReadOnly = true;
        colSelected.SortMode = DataGridViewColumnSortMode.NotSortable;
        colSequence.HeaderText = "م";
        colSequence.Width = 40;
        colSequence.ReadOnly = true;
        colSequence.SortMode = DataGridViewColumnSortMode.NotSortable;
        colItemNumber.HeaderText = "رقم الصنف";
        colItemNumber.Width = 150;
        colItemNumber.ReadOnly = true;
        colItemNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colItemName.HeaderText = "اسم الصنف";
        colItemName.Width = 250;
        colItemName.ReadOnly = true;
        colItemName.SortMode = DataGridViewColumnSortMode.NotSortable;
        colUnit.HeaderText = "الوحدة";
        colUnit.Width = 80;
        colUnit.ReadOnly = true;
        colUnit.SortMode = DataGridViewColumnSortMode.NotSortable;
        colWarehouse.HeaderText = "المخزن";
        colWarehouse.Width = 90;
        colWarehouse.ReadOnly = true;
        colWarehouse.SortMode = DataGridViewColumnSortMode.NotSortable;
        colQuantity.HeaderText = "الكمية";
        colQuantity.Width = 95;
        colQuantity.ReadOnly = true;
        colQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        colPrice.HeaderText = "السعر";
        colPrice.Width = 100;
        colPrice.ReadOnly = true;
        colPrice.SortMode = DataGridViewColumnSortMode.NotSortable;
        colItemType.HeaderText = "نوع الصنف";
        colItemType.Width = 140;
        colItemType.ReadOnly = true;
        colItemType.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.AddRange(new DataGridViewColumn[] { colSelected, colSequence, colItemNumber, colItemName, colUnit, colWarehouse, colQuantity, colPrice, colItemType });
        actionsLayout.Dock = DockStyle.Fill;
        actionsLayout.FlowDirection = FlowDirection.LeftToRight;
        actionsLayout.WrapContents = false;
        chkExpiryBatch.Text = "إظهار تاريخ الانتهاء والدفعة";
        chkExpiryBatch.AutoSize = true;
        chkExpiryBatch.Enabled = false;
        btnSearch.Text = "بحث";
        btnSearch.Enabled = false;
        btnLoad.Text = "إنزال البيانات";
        btnLoad.Enabled = false;
        btnClose.Text = "إغلاق";
        actionsLayout.Controls.Add(chkExpiryBatch);
        actionsLayout.Controls.Add(btnSearch);
        actionsLayout.Controls.Add(btnLoad);
        actionsLayout.Controls.Add(btnClose);
        bodyLayout.Controls.Add(headerLayout, 0, 0);
        bodyLayout.Controls.Add(gridItems, 0, 1);
        bodyLayout.Controls.Add(actionsLayout, 0, 2);
        standardAuditMetadata.Dock = DockStyle.Fill;
        mainLayout.Controls.Add(lblTitle, 0, 0);
        mainLayout.Controls.Add(commandBar, 0, 1);
        mainLayout.Controls.Add(bodyLayout, 0, 2);
        mainLayout.Controls.Add(standardAuditMetadata, 0, 3);
        Controls.Add(mainLayout);
        AutoScaleMode = AutoScaleMode.None;
        Font = new Font("Tahoma", 9F);
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1180, 720);
        Name = "UcInventoryReceiptItemSearch";
        Text = "البحث عن الأصناف";
        ResumeLayout(false);
    }
}
