using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcInventoryJournalView
{
    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private TableLayoutPanel bodyLayout = null!;
    private TableLayoutPanel headerLayout = null!;
    private DataGridView gridJournal = null!;
    private TableLayoutPanel totalsLayout = null!;
    private Panel auditFooter = null!;
    private AuditMetadataControl standardAuditMetadata = null!;
    private Label lblDocumentNumber = null!;
    private TextBox fieldDocumentNumber = null!;
    private Label lblDocumentSequence = null!;
    private TextBox fieldDocumentSequence = null!;
    private Label lblDebitTotal = null!;
    private TextBox fieldDebitTotal = null!;
    private Label lblCreditTotal = null!;
    private TextBox fieldCreditTotal = null!;
    private DataGridViewTextBoxColumn colAccount = null!;
    private DataGridViewTextBoxColumn colAnalyticalAccount = null!;
    private DataGridViewTextBoxColumn colAccountName = null!;
    private DataGridViewTextBoxColumn colCurrency = null!;
    private DataGridViewTextBoxColumn colDebit = null!;
    private DataGridViewTextBoxColumn colCredit = null!;
    private DataGridViewTextBoxColumn colForeignDebit = null!;
    private DataGridViewTextBoxColumn colForeignCredit = null!;
    private DataGridViewTextBoxColumn colDescription = null!;
    private DataGridViewTextBoxColumn colCostCenter = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        bodyLayout = new TableLayoutPanel();
        bodyLayout.Name = "bodyLayout";
        headerLayout = new TableLayoutPanel();
        headerLayout.Name = "headerLayout";
        gridJournal = new DataGridView();
        gridJournal.Name = "gridJournal";
        totalsLayout = new TableLayoutPanel();
        totalsLayout.Name = "totalsLayout";
        auditFooter = new Panel();
        auditFooter.Name = "auditFooter";
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        lblDocumentNumber = new Label();
        lblDocumentNumber.Name = "lblDocumentNumber";
        fieldDocumentNumber = new TextBox();
        fieldDocumentNumber.Name = "fieldDocumentNumber";
        lblDocumentSequence = new Label();
        lblDocumentSequence.Name = "lblDocumentSequence";
        fieldDocumentSequence = new TextBox();
        fieldDocumentSequence.Name = "fieldDocumentSequence";
        lblDebitTotal = new Label();
        lblDebitTotal.Name = "lblDebitTotal";
        fieldDebitTotal = new TextBox();
        fieldDebitTotal.Name = "fieldDebitTotal";
        lblCreditTotal = new Label();
        lblCreditTotal.Name = "lblCreditTotal";
        fieldCreditTotal = new TextBox();
        fieldCreditTotal.Name = "fieldCreditTotal";
        colAccount = new DataGridViewTextBoxColumn();
        colAccount.Name = "colAccount";
        colAnalyticalAccount = new DataGridViewTextBoxColumn();
        colAnalyticalAccount.Name = "colAnalyticalAccount";
        colAccountName = new DataGridViewTextBoxColumn();
        colAccountName.Name = "colAccountName";
        colCurrency = new DataGridViewTextBoxColumn();
        colCurrency.Name = "colCurrency";
        colDebit = new DataGridViewTextBoxColumn();
        colDebit.Name = "colDebit";
        colCredit = new DataGridViewTextBoxColumn();
        colCredit.Name = "colCredit";
        colForeignDebit = new DataGridViewTextBoxColumn();
        colForeignDebit.Name = "colForeignDebit";
        colForeignCredit = new DataGridViewTextBoxColumn();
        colForeignCredit.Name = "colForeignCredit";
        colDescription = new DataGridViewTextBoxColumn();
        colDescription.Name = "colDescription";
        colCostCenter = new DataGridViewTextBoxColumn();
        colCostCenter.Name = "colCostCenter";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = Padding.Empty;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Text = "اليومية العامة";
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.BackColor = Color.FromArgb(23, 50, 78);
        lblTitle.ForeColor = Color.White;
        commandBar.Dock = DockStyle.Fill;
        commandBar.Margin = Padding.Empty;
        bodyLayout.Dock = DockStyle.Fill;
        bodyLayout.ColumnCount = 1;
        bodyLayout.RowCount = 3;
        bodyLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
        headerLayout.Dock = DockStyle.Fill;
        headerLayout.Padding = new Padding(10, 6, 10, 6);
        headerLayout.ColumnCount = 4;
        headerLayout.RowCount = 1;
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 130F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 130F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        totalsLayout.Dock = DockStyle.Fill;
        totalsLayout.Padding = new Padding(10, 6, 10, 6);
        totalsLayout.ColumnCount = 4;
        totalsLayout.RowCount = 1;
        totalsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 130F));
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 130F));
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        lblDocumentNumber.Text = "رقم الوثيقة";
        lblDocumentNumber.Dock = DockStyle.Fill;
        lblDocumentNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldDocumentNumber.AccessibleName = "رقم الوثيقة";
        fieldDocumentNumber.Dock = DockStyle.Fill;
        fieldDocumentNumber.ReadOnly = true;
        headerLayout.Controls.Add(lblDocumentNumber, 0, 0);
        headerLayout.Controls.Add(fieldDocumentNumber, 1, 0);
        lblDocumentSequence.Text = "تسلسل الوثيقة";
        lblDocumentSequence.Dock = DockStyle.Fill;
        lblDocumentSequence.TextAlign = ContentAlignment.MiddleLeft;
        fieldDocumentSequence.AccessibleName = "تسلسل الوثيقة";
        fieldDocumentSequence.Dock = DockStyle.Fill;
        fieldDocumentSequence.ReadOnly = true;
        headerLayout.Controls.Add(lblDocumentSequence, 2, 0);
        headerLayout.Controls.Add(fieldDocumentSequence, 3, 0);
        lblDebitTotal.Text = "إجمالي مدين";
        lblDebitTotal.Dock = DockStyle.Fill;
        lblDebitTotal.TextAlign = ContentAlignment.MiddleLeft;
        fieldDebitTotal.AccessibleName = "إجمالي مدين";
        fieldDebitTotal.Dock = DockStyle.Fill;
        fieldDebitTotal.ReadOnly = true;
        totalsLayout.Controls.Add(lblDebitTotal, 0, 0);
        totalsLayout.Controls.Add(fieldDebitTotal, 1, 0);
        lblCreditTotal.Text = "إجمالي دائن";
        lblCreditTotal.Dock = DockStyle.Fill;
        lblCreditTotal.TextAlign = ContentAlignment.MiddleLeft;
        fieldCreditTotal.AccessibleName = "إجمالي دائن";
        fieldCreditTotal.Dock = DockStyle.Fill;
        fieldCreditTotal.ReadOnly = true;
        totalsLayout.Controls.Add(lblCreditTotal, 2, 0);
        totalsLayout.Controls.Add(fieldCreditTotal, 3, 0);
        gridJournal.Dock = DockStyle.Fill;
        gridJournal.AccessibleName = "اليومية العامة";
        gridJournal.ReadOnly = true;
        gridJournal.AllowUserToAddRows = false;
        gridJournal.AllowUserToDeleteRows = false;
        gridJournal.AutoGenerateColumns = false;
        gridJournal.RowHeadersVisible = false;
        gridJournal.BackgroundColor = Color.White;
        gridJournal.ColumnHeadersHeight = 34;
        gridJournal.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridJournal.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        colAccount.HeaderText = "رقم الحساب";
        colAccount.Width = 120;
        colAccount.ReadOnly = true;
        colAccount.SortMode = DataGridViewColumnSortMode.NotSortable;
        colAnalyticalAccount.HeaderText = "الحساب التحليلي";
        colAnalyticalAccount.Width = 130;
        colAnalyticalAccount.ReadOnly = true;
        colAnalyticalAccount.SortMode = DataGridViewColumnSortMode.NotSortable;
        colAccountName.HeaderText = "الاسم";
        colAccountName.Width = 200;
        colAccountName.ReadOnly = true;
        colAccountName.SortMode = DataGridViewColumnSortMode.NotSortable;
        colCurrency.HeaderText = "العملة";
        colCurrency.Width = 70;
        colCurrency.ReadOnly = true;
        colCurrency.SortMode = DataGridViewColumnSortMode.NotSortable;
        colDebit.HeaderText = "مدين";
        colDebit.Width = 100;
        colDebit.ReadOnly = true;
        colDebit.SortMode = DataGridViewColumnSortMode.NotSortable;
        colCredit.HeaderText = "دائن";
        colCredit.Width = 100;
        colCredit.ReadOnly = true;
        colCredit.SortMode = DataGridViewColumnSortMode.NotSortable;
        colForeignDebit.HeaderText = "مدين أجنبي";
        colForeignDebit.Width = 110;
        colForeignDebit.ReadOnly = true;
        colForeignDebit.SortMode = DataGridViewColumnSortMode.NotSortable;
        colForeignCredit.HeaderText = "دائن أجنبي";
        colForeignCredit.Width = 110;
        colForeignCredit.ReadOnly = true;
        colForeignCredit.SortMode = DataGridViewColumnSortMode.NotSortable;
        colDescription.HeaderText = "البيان";
        colDescription.Width = 260;
        colDescription.ReadOnly = true;
        colDescription.SortMode = DataGridViewColumnSortMode.NotSortable;
        colCostCenter.HeaderText = "رقم المركز";
        colCostCenter.Width = 110;
        colCostCenter.ReadOnly = true;
        colCostCenter.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridJournal.Columns.AddRange(new DataGridViewColumn[] { colAccount, colAnalyticalAccount, colAccountName, colCurrency, colDebit, colCredit, colForeignDebit, colForeignCredit, colDescription, colCostCenter });
        bodyLayout.Controls.Add(headerLayout, 0, 0);
        bodyLayout.Controls.Add(gridJournal, 0, 1);
        bodyLayout.Controls.Add(totalsLayout, 0, 2);
        auditFooter.Dock = DockStyle.Fill;
        auditFooter.Margin = Padding.Empty;
        standardAuditMetadata.Dock = DockStyle.Fill;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.Profile = AuditMetadataProfile.Standard;
        auditFooter.Controls.Add(standardAuditMetadata);
        mainLayout.Controls.Add(lblTitle, 0, 0);
        mainLayout.Controls.Add(commandBar, 0, 1);
        mainLayout.Controls.Add(bodyLayout, 0, 2);
        mainLayout.Controls.Add(auditFooter, 0, 3);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 9F);
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1180, 720);
        MinimumSize = new Size(1000, 600);
        Name = "UcInventoryJournalView";
        Text = "اليومية العامة";
        Controls.Add(mainLayout);
        ResumeLayout(false);
    }
}
