using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcInventoryItemLookup
{
    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private TableLayoutPanel bodyLayout = null!;
    private TableLayoutPanel searchLayout = null!;
    private Label lblFind = null!;
    private TextBox fieldFind = null!;
    private DataGridView gridLookup = null!;
    private TableLayoutPanel actionsLayout = null!;
    private Button btnFind = null!;
    private Button btnOK = null!;
    private Button btnCancel = null!;
    private Panel auditFooter = null!;
    private AuditMetadataControl standardAuditMetadata = null!;
    private DataGridViewTextBoxColumn colItemNumber = null!;
    private DataGridViewTextBoxColumn colItemName = null!;
    private DataGridViewTextBoxColumn colForeignName = null!;
    private DataGridViewTextBoxColumn colUnit = null!;
    private DataGridViewTextBoxColumn colAvailableQuantity = null!;
    private DataGridViewTextBoxColumn colPrice = null!;
    private DataGridViewTextBoxColumn colSpecification = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        bodyLayout = new TableLayoutPanel();
        bodyLayout.Name = "bodyLayout";
        searchLayout = new TableLayoutPanel();
        searchLayout.Name = "searchLayout";
        lblFind = new Label();
        lblFind.Name = "lblFind";
        fieldFind = new TextBox();
        fieldFind.Name = "fieldFind";
        gridLookup = new DataGridView();
        gridLookup.Name = "gridLookup";
        actionsLayout = new TableLayoutPanel();
        actionsLayout.Name = "actionsLayout";
        btnFind = new Button();
        btnFind.Name = "btnFind";
        btnOK = new Button();
        btnOK.Name = "btnOK";
        btnCancel = new Button();
        btnCancel.Name = "btnCancel";
        auditFooter = new Panel();
        auditFooter.Name = "auditFooter";
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        colItemNumber = new DataGridViewTextBoxColumn();
        colItemNumber.Name = "colItemNumber";
        colItemName = new DataGridViewTextBoxColumn();
        colItemName.Name = "colItemName";
        colForeignName = new DataGridViewTextBoxColumn();
        colForeignName.Name = "colForeignName";
        colUnit = new DataGridViewTextBoxColumn();
        colUnit.Name = "colUnit";
        colAvailableQuantity = new DataGridViewTextBoxColumn();
        colAvailableQuantity.Name = "colAvailableQuantity";
        colPrice = new DataGridViewTextBoxColumn();
        colPrice.Name = "colPrice";
        colSpecification = new DataGridViewTextBoxColumn();
        colSpecification.Name = "colSpecification";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = Padding.Empty;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.BackColor = Color.FromArgb(23, 50, 78);
        lblTitle.ForeColor = Color.White;
        commandBar.Dock = DockStyle.Fill;
        commandBar.Margin = Padding.Empty;
        bodyLayout.Dock = DockStyle.Fill;
        bodyLayout.ColumnCount = 1;
        bodyLayout.RowCount = 3;
        bodyLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 0F));
        searchLayout.Dock = DockStyle.Fill;
        searchLayout.ColumnCount = 4;
        searchLayout.RowCount = 1;
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 70F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 180F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchLayout.Padding = new Padding(6);
        lblFind.Text = "Find";
        lblFind.Dock = DockStyle.Fill;
        lblFind.TextAlign = ContentAlignment.MiddleCenter;
        fieldFind.Dock = DockStyle.Fill;
        fieldFind.AccessibleName = "Find";
        fieldFind.ReadOnly = true;
        searchLayout.Controls.Add(lblFind, 1, 0);
        searchLayout.Controls.Add(fieldFind, 2, 0);
        gridLookup.Dock = DockStyle.Fill;
        gridLookup.ReadOnly = true;
        gridLookup.AllowUserToAddRows = false;
        gridLookup.AllowUserToDeleteRows = false;
        gridLookup.AutoGenerateColumns = false;
        gridLookup.RowHeadersVisible = false;
        gridLookup.BackgroundColor = Color.White;
        gridLookup.ColumnHeadersHeight = 34;
        gridLookup.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridLookup.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        colItemNumber.HeaderText = "رقم الصنف";
        colItemNumber.Width = 140;
        colItemNumber.ReadOnly = true;
        colItemNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colItemName.HeaderText = "اسم الصنف";
        colItemName.Width = 250;
        colItemName.ReadOnly = true;
        colItemName.SortMode = DataGridViewColumnSortMode.NotSortable;
        colForeignName.HeaderText = "الاسم الأجنبي";
        colForeignName.Width = 220;
        colForeignName.ReadOnly = true;
        colForeignName.SortMode = DataGridViewColumnSortMode.NotSortable;
        colUnit.HeaderText = "الوحدة";
        colUnit.Width = 80;
        colUnit.ReadOnly = true;
        colUnit.SortMode = DataGridViewColumnSortMode.NotSortable;
        colAvailableQuantity.HeaderText = "الكمية المتوفرة";
        colAvailableQuantity.Width = 130;
        colAvailableQuantity.ReadOnly = true;
        colAvailableQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        colPrice.HeaderText = "السعر";
        colPrice.Width = 100;
        colPrice.ReadOnly = true;
        colPrice.SortMode = DataGridViewColumnSortMode.NotSortable;
        colSpecification.HeaderText = "مواصفات الصنف";
        colSpecification.Width = 200;
        colSpecification.ReadOnly = true;
        colSpecification.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridLookup.Columns.AddRange(new DataGridViewColumn[] { colItemNumber, colItemName, colForeignName, colUnit, colAvailableQuantity, colPrice, colSpecification });
        actionsLayout.Dock = DockStyle.Fill;
        actionsLayout.ColumnCount = 3;
        actionsLayout.RowCount = 1;
        actionsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        actionsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        actionsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        btnFind.Text = "Find";
        btnFind.Enabled = false;
        btnFind.Anchor = AnchorStyles.Right;
        btnOK.Text = "OK";
        btnOK.Enabled = false;
        btnOK.Anchor = AnchorStyles.None;
        btnCancel.Text = "Cancel";
        btnCancel.Anchor = AnchorStyles.Left;
        actionsLayout.Controls.Add(btnFind, 0, 0);
        actionsLayout.Controls.Add(btnOK, 1, 0);
        actionsLayout.Controls.Add(btnCancel, 2, 0);
        bodyLayout.Controls.Add(searchLayout, 0, 0);
        bodyLayout.Controls.Add(gridLookup, 0, 1);
        bodyLayout.Controls.Add(actionsLayout, 0, 2);
        auditFooter.Dock = DockStyle.Fill;
        auditFooter.Margin = Padding.Empty;
        standardAuditMetadata.Dock = DockStyle.Fill;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.Profile = AuditMetadataProfile.Standard;
        auditFooter.Controls.Add(standardAuditMetadata);
        mainLayout.Controls.Add(lblTitle, 0, 0);
        mainLayout.Controls.Add(commandBar, 0, 1);
        mainLayout.Controls.Add(bodyLayout, 0, 2);
        mainLayout.Controls.Add(auditFooter, 0, 3);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 9F);
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1180, 720);
        MinimumSize = new Size(1000, 600);
        Controls.Add(mainLayout);
        actionsLayout.Visible = false;
        lblTitle.Text = "قائمة الأصناف - مرتبة حسب الأرقام";
        Name = "UcInventoryItemLookup";
        Text = "قائمة الأصناف - مرتبة حسب الأرقام";
        gridLookup.AccessibleName = "قائمة الأصناف - مرتبة حسب الأرقام";
        ResumeLayout(false);
    }
}
