using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcInventorySettlement
{
    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private TabControl tabs = null!;
    private TabPage tabMain = null!;
    private TableLayoutPanel documentLayout = null!;
    private TableLayoutPanel headerLayout = null!;
    private Button btnJournalView = null!;
    private FlowLayoutPanel actionsLayout = null!;
    private RadioButton radioQuantity = null!;
    private RadioButton radioCost = null!;
    private CheckBox chkPosted = null!;
    private CheckBox chkSuspended = null!;
    private TabPage tabDownload = null!;
    private TableLayoutPanel downloadLayout = null!;
    private FlowLayoutPanel downloadModes = null!;
    private RadioButton radioManual = null!;
    private RadioButton radioAutomatic = null!;
    private FlowLayoutPanel calculationLayout = null!;
    private Label lblCalculationNote = null!;
    private Button btnCalculate = null!;
    private Button btnLoadItems = null!;
    private FlowLayoutPanel totalsLayout = null!;
    private Label lblTotal = null!;
    private TextBox txtTotal = null!;
    private Label lblLoadSource = null!;
    private ComboBox fieldLoadSource = null!;
    private Label lblGroupFrom = null!;
    private TextBox fieldGroupFrom = null!;
    private Label lblGroupTo = null!;
    private TextBox fieldGroupTo = null!;
    private Label lblItemFrom = null!;
    private TextBox fieldItemFrom = null!;
    private Label lblItemTo = null!;
    private TextBox fieldItemTo = null!;
    private Label lblWarehouseFrom = null!;
    private TextBox fieldWarehouseFrom = null!;
    private Label lblWarehouseTo = null!;
    private TextBox fieldWarehouseTo = null!;
    private Label lblNumberFrom = null!;
    private TextBox fieldNumberFrom = null!;
    private Label lblNumberTo = null!;
    private TextBox fieldNumberTo = null!;
    private Label lblDateFrom = null!;
    private TextBox fieldDateFrom = null!;
    private Label lblDateTo = null!;
    private TextBox fieldDateTo = null!;
    private Label lblRepeatedItems = null!;
    private ComboBox fieldRepeatedItems = null!;
    private Label lblDisplayMethod = null!;
    private ComboBox fieldDisplayMethod = null!;
    private Label lblCalculationOperator = null!;
    private ComboBox fieldCalculationOperator = null!;
    private Label lblPercentage = null!;
    private TextBox fieldPercentage = null!;
    private DataGridView gridItems = null!;
    private Panel auditFooter = null!;
    private AuditMetadataControl standardAuditMetadata = null!;
    private Label lblBranch = null!;
    private ComboBox fieldBranch = null!;
    private Label lblSettlementType = null!;
    private ComboBox fieldSettlementType = null!;
    private Label lblSettlementNumber = null!;
    private TextBox fieldSettlementNumber = null!;
    private Label lblDate = null!;
    private TextBox fieldDate = null!;
    private Label lblAccountNumber = null!;
    private TextBox fieldAccountNumber = null!;
    private Label lblAccountName = null!;
    private TextBox fieldAccountName = null!;
    private Label lblAnalyticAccount = null!;
    private TextBox fieldAnalyticAccount = null!;
    private Label lblAnalyticName = null!;
    private TextBox fieldAnalyticName = null!;
    private Label lblCurrency = null!;
    private TextBox fieldCurrency = null!;
    private Label lblExchangeRate = null!;
    private TextBox fieldExchangeRate = null!;
    private Label lblDescription = null!;
    private TextBox fieldDescription = null!;
    private Label lblReference = null!;
    private TextBox fieldReference = null!;
    private Label lblCostCenter = null!;
    private TextBox fieldCostCenter = null!;
    private Label lblItemCost = null!;
    private ComboBox fieldItemCost = null!;
    private DataGridViewTextBoxColumn colSequence = null!;
    private DataGridViewButtonColumn colLookup = null!;
    private DataGridViewTextBoxColumn colItemNumber = null!;
    private DataGridViewTextBoxColumn colItemName = null!;
    private DataGridViewTextBoxColumn colUnit = null!;
    private DataGridViewTextBoxColumn colWarehouse = null!;
    private DataGridViewTextBoxColumn colExpiryDate = null!;
    private DataGridViewTextBoxColumn colAverageCost = null!;
    private DataGridViewTextBoxColumn colAvailableQuantity = null!;
    private DataGridViewTextBoxColumn colQuantity = null!;
    private DataGridViewTextBoxColumn colNewCost = null!;
    private DataGridViewTextBoxColumn colDifference = null!;
    private DataGridViewTextBoxColumn colCountQuantity = null!;
    private DataGridViewTextBoxColumn colQuantityAtCount = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        tabs = new TabControl();
        tabs.Name = "tabs";
        tabMain = new TabPage();
        tabMain.Name = "tabMain";
        documentLayout = new TableLayoutPanel();
        documentLayout.Name = "documentLayout";
        headerLayout = new TableLayoutPanel();
        headerLayout.Name = "headerLayout";
        btnJournalView = new Button();
        btnJournalView.Name = "btnJournalView";
        btnJournalView.Text = "اليومية العامة";
        btnJournalView.AccessibleName = "اليومية العامة";
        btnJournalView.AutoSize = true;
        btnJournalView.Click += JournalView_Click;
        actionsLayout = new FlowLayoutPanel();
        actionsLayout.Name = "actionsLayout";
        radioQuantity = new RadioButton();
        radioQuantity.Name = "radioQuantity";
        radioCost = new RadioButton();
        radioCost.Name = "radioCost";
        chkPosted = new CheckBox();
        chkPosted.Name = "chkPosted";
        chkSuspended = new CheckBox();
        chkSuspended.Name = "chkSuspended";
        tabDownload = new TabPage();
        tabDownload.Name = "tabDownload";
        downloadLayout = new TableLayoutPanel();
        downloadLayout.Name = "downloadLayout";
        downloadModes = new FlowLayoutPanel();
        downloadModes.Name = "downloadModes";
        radioManual = new RadioButton();
        radioManual.Name = "radioManual";
        radioAutomatic = new RadioButton();
        radioAutomatic.Name = "radioAutomatic";
        calculationLayout = new FlowLayoutPanel();
        calculationLayout.Name = "calculationLayout";
        lblCalculationNote = new Label();
        lblCalculationNote.Name = "lblCalculationNote";
        btnCalculate = new Button();
        btnCalculate.Name = "btnCalculate";
        btnLoadItems = new Button();
        btnLoadItems.Name = "btnLoadItems";
        totalsLayout = new FlowLayoutPanel();
        totalsLayout.Name = "totalsLayout";
        lblTotal = new Label();
        lblTotal.Name = "lblTotal";
        txtTotal = new TextBox();
        txtTotal.Name = "txtTotal";
        lblLoadSource = new Label();
        lblLoadSource.Name = "lblLoadSource";
        fieldLoadSource = new ComboBox();
        fieldLoadSource.Name = "fieldLoadSource";
        lblGroupFrom = new Label();
        lblGroupFrom.Name = "lblGroupFrom";
        fieldGroupFrom = new TextBox();
        fieldGroupFrom.Name = "fieldGroupFrom";
        lblGroupTo = new Label();
        lblGroupTo.Name = "lblGroupTo";
        fieldGroupTo = new TextBox();
        fieldGroupTo.Name = "fieldGroupTo";
        lblItemFrom = new Label();
        lblItemFrom.Name = "lblItemFrom";
        fieldItemFrom = new TextBox();
        fieldItemFrom.Name = "fieldItemFrom";
        lblItemTo = new Label();
        lblItemTo.Name = "lblItemTo";
        fieldItemTo = new TextBox();
        fieldItemTo.Name = "fieldItemTo";
        lblWarehouseFrom = new Label();
        lblWarehouseFrom.Name = "lblWarehouseFrom";
        fieldWarehouseFrom = new TextBox();
        fieldWarehouseFrom.Name = "fieldWarehouseFrom";
        lblWarehouseTo = new Label();
        lblWarehouseTo.Name = "lblWarehouseTo";
        fieldWarehouseTo = new TextBox();
        fieldWarehouseTo.Name = "fieldWarehouseTo";
        lblNumberFrom = new Label();
        lblNumberFrom.Name = "lblNumberFrom";
        fieldNumberFrom = new TextBox();
        fieldNumberFrom.Name = "fieldNumberFrom";
        lblNumberTo = new Label();
        lblNumberTo.Name = "lblNumberTo";
        fieldNumberTo = new TextBox();
        fieldNumberTo.Name = "fieldNumberTo";
        lblDateFrom = new Label();
        lblDateFrom.Name = "lblDateFrom";
        fieldDateFrom = new TextBox();
        fieldDateFrom.Name = "fieldDateFrom";
        lblDateTo = new Label();
        lblDateTo.Name = "lblDateTo";
        fieldDateTo = new TextBox();
        fieldDateTo.Name = "fieldDateTo";
        lblRepeatedItems = new Label();
        lblRepeatedItems.Name = "lblRepeatedItems";
        fieldRepeatedItems = new ComboBox();
        fieldRepeatedItems.Name = "fieldRepeatedItems";
        lblDisplayMethod = new Label();
        lblDisplayMethod.Name = "lblDisplayMethod";
        fieldDisplayMethod = new ComboBox();
        fieldDisplayMethod.Name = "fieldDisplayMethod";
        lblCalculationOperator = new Label();
        lblCalculationOperator.Name = "lblCalculationOperator";
        fieldCalculationOperator = new ComboBox();
        fieldCalculationOperator.Name = "fieldCalculationOperator";
        lblPercentage = new Label();
        lblPercentage.Name = "lblPercentage";
        fieldPercentage = new TextBox();
        fieldPercentage.Name = "fieldPercentage";
        gridItems = new DataGridView();
        gridItems.Name = "gridItems";
        auditFooter = new Panel();
        auditFooter.Name = "auditFooter";
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        lblBranch = new Label();
        lblBranch.Name = "lblBranch";
        fieldBranch = new ComboBox();
        fieldBranch.Name = "fieldBranch";
        lblSettlementType = new Label();
        lblSettlementType.Name = "lblSettlementType";
        fieldSettlementType = new ComboBox();
        fieldSettlementType.Name = "fieldSettlementType";
        lblSettlementNumber = new Label();
        lblSettlementNumber.Name = "lblSettlementNumber";
        fieldSettlementNumber = new TextBox();
        fieldSettlementNumber.Name = "fieldSettlementNumber";
        lblDate = new Label();
        lblDate.Name = "lblDate";
        fieldDate = new TextBox();
        fieldDate.Name = "fieldDate";
        lblAccountNumber = new Label();
        lblAccountNumber.Name = "lblAccountNumber";
        fieldAccountNumber = new TextBox();
        fieldAccountNumber.Name = "fieldAccountNumber";
        lblAccountName = new Label();
        lblAccountName.Name = "lblAccountName";
        fieldAccountName = new TextBox();
        fieldAccountName.Name = "fieldAccountName";
        lblAnalyticAccount = new Label();
        lblAnalyticAccount.Name = "lblAnalyticAccount";
        fieldAnalyticAccount = new TextBox();
        fieldAnalyticAccount.Name = "fieldAnalyticAccount";
        lblAnalyticName = new Label();
        lblAnalyticName.Name = "lblAnalyticName";
        fieldAnalyticName = new TextBox();
        fieldAnalyticName.Name = "fieldAnalyticName";
        lblCurrency = new Label();
        lblCurrency.Name = "lblCurrency";
        fieldCurrency = new TextBox();
        fieldCurrency.Name = "fieldCurrency";
        lblExchangeRate = new Label();
        lblExchangeRate.Name = "lblExchangeRate";
        fieldExchangeRate = new TextBox();
        fieldExchangeRate.Name = "fieldExchangeRate";
        lblDescription = new Label();
        lblDescription.Name = "lblDescription";
        fieldDescription = new TextBox();
        fieldDescription.Name = "fieldDescription";
        lblReference = new Label();
        lblReference.Name = "lblReference";
        fieldReference = new TextBox();
        fieldReference.Name = "fieldReference";
        lblCostCenter = new Label();
        lblCostCenter.Name = "lblCostCenter";
        fieldCostCenter = new TextBox();
        fieldCostCenter.Name = "fieldCostCenter";
        lblItemCost = new Label();
        lblItemCost.Name = "lblItemCost";
        fieldItemCost = new ComboBox();
        fieldItemCost.Name = "fieldItemCost";
        colSequence = new DataGridViewTextBoxColumn();
        colSequence.Name = "colSequence";
        colLookup = new DataGridViewButtonColumn();
        colLookup.Name = "colLookup";
        colItemNumber = new DataGridViewTextBoxColumn();
        colItemNumber.Name = "colItemNumber";
        colItemName = new DataGridViewTextBoxColumn();
        colItemName.Name = "colItemName";
        colUnit = new DataGridViewTextBoxColumn();
        colUnit.Name = "colUnit";
        colWarehouse = new DataGridViewTextBoxColumn();
        colWarehouse.Name = "colWarehouse";
        colExpiryDate = new DataGridViewTextBoxColumn();
        colExpiryDate.Name = "colExpiryDate";
        colAverageCost = new DataGridViewTextBoxColumn();
        colAverageCost.Name = "colAverageCost";
        colAvailableQuantity = new DataGridViewTextBoxColumn();
        colAvailableQuantity.Name = "colAvailableQuantity";
        colQuantity = new DataGridViewTextBoxColumn();
        colQuantity.Name = "colQuantity";
        colNewCost = new DataGridViewTextBoxColumn();
        colNewCost.Name = "colNewCost";
        colDifference = new DataGridViewTextBoxColumn();
        colDifference.Name = "colDifference";
        colCountQuantity = new DataGridViewTextBoxColumn();
        colCountQuantity.Name = "colCountQuantity";
        colQuantityAtCount = new DataGridViewTextBoxColumn();
        colQuantityAtCount.Name = "colQuantityAtCount";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = Padding.Empty;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.BackColor = Color.FromArgb(23, 50, 78);
        lblTitle.ForeColor = Color.White;
        commandBar.Dock = DockStyle.Fill;
        commandBar.Margin = Padding.Empty;
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeftLayout = true;
        tabMain.Text = "البيانات الرئيسية";
        tabMain.Padding = Padding.Empty;
        tabs.Controls.Add(tabMain);
        documentLayout.Dock = DockStyle.Fill;
        documentLayout.ColumnCount = 1;
        documentLayout.RowCount = 4;
        documentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 172F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tabMain.Controls.Add(documentLayout);
        headerLayout.Dock = DockStyle.Fill;
        headerLayout.Padding = new Padding(10, 6, 10, 6);
        headerLayout.Margin = Padding.Empty;
        headerLayout.ColumnCount = 6;
        headerLayout.RowCount = 5;
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 135F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 135F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 135F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        lblBranch.Text = "الفرع";
        lblBranch.Dock = DockStyle.Fill;
        lblBranch.TextAlign = ContentAlignment.MiddleLeft;
        fieldBranch.AccessibleName = "الفرع";
        fieldBranch.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblBranch, 0, 0);
        headerLayout.Controls.Add(fieldBranch, 1, 0);
        fieldBranch.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldBranch.Enabled = false;
        lblSettlementType.Text = "النوع";
        lblSettlementType.Dock = DockStyle.Fill;
        lblSettlementType.TextAlign = ContentAlignment.MiddleLeft;
        fieldSettlementType.AccessibleName = "النوع";
        fieldSettlementType.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblSettlementType, 2, 0);
        headerLayout.Controls.Add(fieldSettlementType, 3, 0);
        fieldSettlementType.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldSettlementType.Enabled = false;
        lblSettlementNumber.Text = "رقم التسوية";
        lblSettlementNumber.Dock = DockStyle.Fill;
        lblSettlementNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldSettlementNumber.AccessibleName = "رقم التسوية";
        fieldSettlementNumber.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblSettlementNumber, 4, 0);
        headerLayout.Controls.Add(fieldSettlementNumber, 5, 0);
        fieldSettlementNumber.ReadOnly = true;
        lblDate.Text = "التاريخ";
        lblDate.Dock = DockStyle.Fill;
        lblDate.TextAlign = ContentAlignment.MiddleLeft;
        fieldDate.AccessibleName = "التاريخ";
        fieldDate.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDate, 0, 1);
        headerLayout.Controls.Add(fieldDate, 1, 1);
        fieldDate.ReadOnly = true;
        lblAccountNumber.Text = "رقم الحساب";
        lblAccountNumber.Dock = DockStyle.Fill;
        lblAccountNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldAccountNumber.AccessibleName = "رقم الحساب";
        fieldAccountNumber.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblAccountNumber, 2, 1);
        headerLayout.Controls.Add(fieldAccountNumber, 3, 1);
        fieldAccountNumber.ReadOnly = true;
        lblAccountName.Text = "اسم الحساب";
        lblAccountName.Dock = DockStyle.Fill;
        lblAccountName.TextAlign = ContentAlignment.MiddleLeft;
        fieldAccountName.AccessibleName = "اسم الحساب";
        fieldAccountName.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblAccountName, 4, 1);
        headerLayout.Controls.Add(fieldAccountName, 5, 1);
        fieldAccountName.ReadOnly = true;
        lblAnalyticAccount.Text = "الحساب التحليلي";
        lblAnalyticAccount.Dock = DockStyle.Fill;
        lblAnalyticAccount.TextAlign = ContentAlignment.MiddleLeft;
        fieldAnalyticAccount.AccessibleName = "الحساب التحليلي";
        fieldAnalyticAccount.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblAnalyticAccount, 0, 2);
        headerLayout.Controls.Add(fieldAnalyticAccount, 1, 2);
        fieldAnalyticAccount.ReadOnly = true;
        lblAnalyticName.Text = "اسم الحساب التحليلي";
        lblAnalyticName.Dock = DockStyle.Fill;
        lblAnalyticName.TextAlign = ContentAlignment.MiddleLeft;
        fieldAnalyticName.AccessibleName = "اسم الحساب التحليلي";
        fieldAnalyticName.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblAnalyticName, 2, 2);
        headerLayout.Controls.Add(fieldAnalyticName, 3, 2);
        fieldAnalyticName.ReadOnly = true;
        lblCurrency.Text = "العملة";
        lblCurrency.Dock = DockStyle.Fill;
        lblCurrency.TextAlign = ContentAlignment.MiddleLeft;
        fieldCurrency.AccessibleName = "العملة";
        fieldCurrency.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblCurrency, 4, 2);
        headerLayout.Controls.Add(fieldCurrency, 5, 2);
        fieldCurrency.ReadOnly = true;
        lblExchangeRate.Text = "سعر التحويل";
        lblExchangeRate.Dock = DockStyle.Fill;
        lblExchangeRate.TextAlign = ContentAlignment.MiddleLeft;
        fieldExchangeRate.AccessibleName = "سعر التحويل";
        fieldExchangeRate.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblExchangeRate, 0, 3);
        headerLayout.Controls.Add(fieldExchangeRate, 1, 3);
        fieldExchangeRate.ReadOnly = true;
        lblDescription.Text = "البيان";
        lblDescription.Dock = DockStyle.Fill;
        lblDescription.TextAlign = ContentAlignment.MiddleLeft;
        fieldDescription.AccessibleName = "البيان";
        fieldDescription.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDescription, 2, 3);
        headerLayout.Controls.Add(fieldDescription, 3, 3);
        fieldDescription.ReadOnly = true;
        lblReference.Text = "رقم المرجع";
        lblReference.Dock = DockStyle.Fill;
        lblReference.TextAlign = ContentAlignment.MiddleLeft;
        fieldReference.AccessibleName = "رقم المرجع";
        fieldReference.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblReference, 4, 3);
        headerLayout.Controls.Add(fieldReference, 5, 3);
        fieldReference.ReadOnly = true;
        lblCostCenter.Text = "مركز التكلفة";
        lblCostCenter.Dock = DockStyle.Fill;
        lblCostCenter.TextAlign = ContentAlignment.MiddleLeft;
        fieldCostCenter.AccessibleName = "مركز التكلفة";
        fieldCostCenter.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblCostCenter, 0, 4);
        headerLayout.Controls.Add(fieldCostCenter, 1, 4);
        fieldCostCenter.ReadOnly = true;
        lblItemCost.Text = "تكاليف الأصناف";
        lblItemCost.Dock = DockStyle.Fill;
        lblItemCost.TextAlign = ContentAlignment.MiddleLeft;
        fieldItemCost.AccessibleName = "تكاليف الأصناف";
        fieldItemCost.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblItemCost, 2, 4);
        headerLayout.Controls.Add(fieldItemCost, 3, 4);
        fieldItemCost.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldItemCost.Enabled = false;
        actionsLayout.Dock = DockStyle.Fill;
        actionsLayout.FlowDirection = FlowDirection.RightToLeft;
        actionsLayout.WrapContents = false;
        actionsLayout.Margin = Padding.Empty;
        actionsLayout.Controls.Add(btnJournalView);
        radioQuantity.Text = "تسوية كميات";
        radioQuantity.AutoSize = true;
        radioQuantity.Enabled = true;
        actionsLayout.Controls.Add(radioQuantity);
        radioCost.Text = "تسوية تكاليف";
        radioCost.AutoSize = true;
        radioCost.Enabled = true;
        actionsLayout.Controls.Add(radioCost);
        chkPosted.Text = "مرحل";
        chkPosted.AutoSize = true;
        chkPosted.Enabled = false;
        actionsLayout.Controls.Add(chkPosted);
        chkSuspended.Text = "تعليق";
        chkSuspended.AutoSize = true;
        chkSuspended.Enabled = false;
        actionsLayout.Controls.Add(chkSuspended);
        gridItems.Dock = DockStyle.Fill;
        gridItems.AccessibleName = "أصناف تسوية المخزون";
        gridItems.ReadOnly = true;
        gridItems.AllowUserToAddRows = false;
        gridItems.AllowUserToDeleteRows = false;
        gridItems.AutoGenerateColumns = false;
        gridItems.RowHeadersVisible = false;
        gridItems.BackgroundColor = Color.White;
        gridItems.ColumnHeadersHeight = 34;
        gridItems.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridItems.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        colSequence.HeaderText = "م";
        colSequence.Width = 40;
        colSequence.ReadOnly = true;
        colSequence.SortMode = DataGridViewColumnSortMode.NotSortable;
        colLookup.HeaderText = "";
        colLookup.Width = 30;
        colLookup.ReadOnly = true;
        colLookup.SortMode = DataGridViewColumnSortMode.NotSortable;
        colLookup.Text = "…";
        colLookup.UseColumnTextForButtonValue = true;
        colItemNumber.HeaderText = "رقم الصنف";
        colItemNumber.Width = 120;
        colItemNumber.ReadOnly = true;
        colItemNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colItemName.HeaderText = "اسم الصنف";
        colItemName.Width = 210;
        colItemName.ReadOnly = true;
        colItemName.SortMode = DataGridViewColumnSortMode.NotSortable;
        colUnit.HeaderText = "الوحدة";
        colUnit.Width = 75;
        colUnit.ReadOnly = true;
        colUnit.SortMode = DataGridViewColumnSortMode.NotSortable;
        colWarehouse.HeaderText = "المخزن";
        colWarehouse.Width = 85;
        colWarehouse.ReadOnly = true;
        colWarehouse.SortMode = DataGridViewColumnSortMode.NotSortable;
        colExpiryDate.HeaderText = "تاريخ الانتهاء";
        colExpiryDate.Width = 110;
        colExpiryDate.ReadOnly = true;
        colExpiryDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        colAverageCost.HeaderText = "متوسط التكلفة";
        colAverageCost.Width = 110;
        colAverageCost.ReadOnly = true;
        colAverageCost.SortMode = DataGridViewColumnSortMode.NotSortable;
        colAvailableQuantity.HeaderText = "الكمية المتوفرة";
        colAvailableQuantity.Width = 110;
        colAvailableQuantity.ReadOnly = true;
        colAvailableQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        colQuantity.HeaderText = "الكمية";
        colQuantity.Width = 90;
        colQuantity.ReadOnly = true;
        colQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        colNewCost.HeaderText = "التكلفة الجديدة";
        colNewCost.Width = 110;
        colNewCost.ReadOnly = true;
        colNewCost.SortMode = DataGridViewColumnSortMode.NotSortable;
        colDifference.HeaderText = "الفارق";
        colDifference.Width = 90;
        colDifference.ReadOnly = true;
        colDifference.SortMode = DataGridViewColumnSortMode.NotSortable;
        colCountQuantity.HeaderText = "كمية الجرد";
        colCountQuantity.Width = 100;
        colCountQuantity.ReadOnly = true;
        colCountQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        colQuantityAtCount.HeaderText = "ك/وقت الجرد";
        colQuantityAtCount.Width = 105;
        colQuantityAtCount.ReadOnly = true;
        colQuantityAtCount.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.AddRange(new DataGridViewColumn[] { colSequence, colLookup, colItemNumber, colItemName, colUnit, colWarehouse, colExpiryDate, colAverageCost, colAvailableQuantity, colQuantity, colNewCost, colDifference, colCountQuantity, colQuantityAtCount });
        documentLayout.Controls.Add(headerLayout, 0, 0);
        documentLayout.Controls.Add(actionsLayout, 0, 1);
        documentLayout.Controls.Add(gridItems, 0, 2);
        auditFooter.Dock = DockStyle.Fill;
        auditFooter.Margin = Padding.Empty;
        standardAuditMetadata.Dock = DockStyle.Fill;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.Profile = AuditMetadataProfile.Standard;
        auditFooter.Controls.Add(standardAuditMetadata);
        mainLayout.Controls.Add(lblTitle, 0, 0);
        mainLayout.Controls.Add(commandBar, 0, 1);
        mainLayout.Controls.Add(tabs, 0, 2);
        mainLayout.Controls.Add(auditFooter, 0, 3);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 9F);
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1180, 720);
        MinimumSize = new Size(1000, 600);
        Controls.Add(mainLayout);
        lblTitle.Text = "تسوية مخزون";
        Name = "UcInventorySettlement";
        Text = "تسوية مخزون";
        Tag = "INV:SETTLEMENT";
        radioQuantity.Checked = true;
        colNewCost.Visible = false;
        colDifference.Visible = false;
        lblItemCost.Visible = false;
        fieldItemCost.Visible = false;
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        totalsLayout.Dock = DockStyle.Fill;
        totalsLayout.FlowDirection = FlowDirection.RightToLeft;
        totalsLayout.WrapContents = false;
        lblTotal.Text = "إجمالي التكلفة";
        lblTotal.AutoSize = true;
        txtTotal.ReadOnly = true;
        txtTotal.Width = 150;
        totalsLayout.Controls.Add(lblTotal);
        totalsLayout.Controls.Add(txtTotal);
        documentLayout.Controls.Add(totalsLayout, 0, 3);
        tabDownload.Text = "إنزال البيانات";
        tabs.Controls.Add(tabDownload);
        downloadLayout.Dock = DockStyle.Fill;
        downloadLayout.Padding = new Padding(10);
        downloadLayout.ColumnCount = 5;
        downloadLayout.RowCount = 11;
        downloadLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 180F));
        downloadLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        downloadLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 65F));
        downloadLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        downloadLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 130F));
        downloadLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        downloadLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        downloadLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        downloadLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        downloadLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        downloadLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        downloadLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        downloadLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        downloadLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        downloadLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        downloadLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        downloadModes.Dock = DockStyle.Fill;
        downloadModes.FlowDirection = FlowDirection.RightToLeft;
        radioManual.Text = "يدوي";
        radioManual.AutoSize = true;
        radioManual.Enabled = false;
        radioAutomatic.Text = "تلقائي";
        radioAutomatic.AutoSize = true;
        radioAutomatic.Enabled = false;
        downloadModes.Controls.Add(radioManual);
        downloadModes.Controls.Add(radioAutomatic);
        downloadLayout.Controls.Add(downloadModes, 0, 0);
        downloadLayout.SetColumnSpan(downloadModes, 5);
        lblLoadSource.Text = "إنزال البيانات من";
        lblLoadSource.Dock = DockStyle.Fill;
        lblLoadSource.TextAlign = ContentAlignment.MiddleLeft;
        fieldLoadSource.AccessibleName = "إنزال البيانات من";
        fieldLoadSource.Dock = DockStyle.Fill;
        fieldLoadSource.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldLoadSource.Enabled = false;
        lblGroupFrom.Text = "رقم المجموعة";
        lblGroupFrom.Dock = DockStyle.Fill;
        lblGroupFrom.TextAlign = ContentAlignment.MiddleLeft;
        fieldGroupFrom.AccessibleName = "رقم المجموعة";
        fieldGroupFrom.Dock = DockStyle.Fill;
        fieldGroupFrom.ReadOnly = true;
        lblGroupTo.Text = "إلى";
        lblGroupTo.Dock = DockStyle.Fill;
        lblGroupTo.TextAlign = ContentAlignment.MiddleLeft;
        fieldGroupTo.AccessibleName = "إلى";
        fieldGroupTo.Dock = DockStyle.Fill;
        fieldGroupTo.ReadOnly = true;
        lblItemFrom.Text = "من الصنف رقم";
        lblItemFrom.Dock = DockStyle.Fill;
        lblItemFrom.TextAlign = ContentAlignment.MiddleLeft;
        fieldItemFrom.AccessibleName = "من الصنف رقم";
        fieldItemFrom.Dock = DockStyle.Fill;
        fieldItemFrom.ReadOnly = true;
        lblItemTo.Text = "إلى";
        lblItemTo.Dock = DockStyle.Fill;
        lblItemTo.TextAlign = ContentAlignment.MiddleLeft;
        fieldItemTo.AccessibleName = "إلى";
        fieldItemTo.Dock = DockStyle.Fill;
        fieldItemTo.ReadOnly = true;
        lblWarehouseFrom.Text = "من المخزن";
        lblWarehouseFrom.Dock = DockStyle.Fill;
        lblWarehouseFrom.TextAlign = ContentAlignment.MiddleLeft;
        fieldWarehouseFrom.AccessibleName = "من المخزن";
        fieldWarehouseFrom.Dock = DockStyle.Fill;
        fieldWarehouseFrom.ReadOnly = true;
        lblWarehouseTo.Text = "إلى";
        lblWarehouseTo.Dock = DockStyle.Fill;
        lblWarehouseTo.TextAlign = ContentAlignment.MiddleLeft;
        fieldWarehouseTo.AccessibleName = "إلى";
        fieldWarehouseTo.Dock = DockStyle.Fill;
        fieldWarehouseTo.ReadOnly = true;
        lblNumberFrom.Text = "من رقم";
        lblNumberFrom.Dock = DockStyle.Fill;
        lblNumberFrom.TextAlign = ContentAlignment.MiddleLeft;
        fieldNumberFrom.AccessibleName = "من رقم";
        fieldNumberFrom.Dock = DockStyle.Fill;
        fieldNumberFrom.ReadOnly = true;
        lblNumberTo.Text = "إلى رقم";
        lblNumberTo.Dock = DockStyle.Fill;
        lblNumberTo.TextAlign = ContentAlignment.MiddleLeft;
        fieldNumberTo.AccessibleName = "إلى رقم";
        fieldNumberTo.Dock = DockStyle.Fill;
        fieldNumberTo.ReadOnly = true;
        lblDateFrom.Text = "من تاريخ";
        lblDateFrom.Dock = DockStyle.Fill;
        lblDateFrom.TextAlign = ContentAlignment.MiddleLeft;
        fieldDateFrom.AccessibleName = "من تاريخ";
        fieldDateFrom.Dock = DockStyle.Fill;
        fieldDateFrom.ReadOnly = true;
        lblDateTo.Text = "إلى";
        lblDateTo.Dock = DockStyle.Fill;
        lblDateTo.TextAlign = ContentAlignment.MiddleLeft;
        fieldDateTo.AccessibleName = "إلى";
        fieldDateTo.Dock = DockStyle.Fill;
        fieldDateTo.ReadOnly = true;
        lblRepeatedItems.Text = "الأصناف المكررة خلال فترة الجرد";
        lblRepeatedItems.Dock = DockStyle.Fill;
        lblRepeatedItems.TextAlign = ContentAlignment.MiddleLeft;
        fieldRepeatedItems.AccessibleName = "الأصناف المكررة خلال فترة الجرد";
        fieldRepeatedItems.Dock = DockStyle.Fill;
        fieldRepeatedItems.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldRepeatedItems.Enabled = false;
        lblDisplayMethod.Text = "طريقة العرض";
        lblDisplayMethod.Dock = DockStyle.Fill;
        lblDisplayMethod.TextAlign = ContentAlignment.MiddleLeft;
        fieldDisplayMethod.AccessibleName = "طريقة العرض";
        fieldDisplayMethod.Dock = DockStyle.Fill;
        fieldDisplayMethod.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldDisplayMethod.Enabled = false;
        lblCalculationOperator.Text = "";
        lblCalculationOperator.Dock = DockStyle.Fill;
        lblCalculationOperator.TextAlign = ContentAlignment.MiddleLeft;
        fieldCalculationOperator.AccessibleName = "";
        fieldCalculationOperator.Dock = DockStyle.Fill;
        fieldCalculationOperator.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldCalculationOperator.Enabled = false;
        lblPercentage.Text = "%";
        lblPercentage.Dock = DockStyle.Fill;
        lblPercentage.TextAlign = ContentAlignment.MiddleLeft;
        fieldPercentage.AccessibleName = "%";
        fieldPercentage.Dock = DockStyle.Fill;
        fieldPercentage.ReadOnly = true;
        downloadLayout.Controls.Add(lblLoadSource, 0, 1);
        downloadLayout.Controls.Add(fieldLoadSource, 1, 1);
        downloadLayout.SetColumnSpan(fieldLoadSource, 4);
        downloadLayout.Controls.Add(lblGroupFrom, 0, 2);
        downloadLayout.Controls.Add(fieldGroupFrom, 1, 2);
        downloadLayout.Controls.Add(lblGroupTo, 2, 2);
        downloadLayout.Controls.Add(fieldGroupTo, 3, 2);
        downloadLayout.Controls.Add(lblItemFrom, 0, 3);
        downloadLayout.Controls.Add(fieldItemFrom, 1, 3);
        downloadLayout.Controls.Add(lblItemTo, 2, 3);
        downloadLayout.Controls.Add(fieldItemTo, 3, 3);
        downloadLayout.Controls.Add(lblWarehouseFrom, 0, 4);
        downloadLayout.Controls.Add(fieldWarehouseFrom, 1, 4);
        downloadLayout.Controls.Add(lblWarehouseTo, 2, 4);
        downloadLayout.Controls.Add(fieldWarehouseTo, 3, 4);
        downloadLayout.Controls.Add(lblNumberFrom, 0, 5);
        downloadLayout.Controls.Add(fieldNumberFrom, 1, 5);
        downloadLayout.Controls.Add(lblNumberTo, 2, 5);
        downloadLayout.Controls.Add(fieldNumberTo, 3, 5);
        downloadLayout.Controls.Add(lblDateFrom, 0, 6);
        downloadLayout.Controls.Add(fieldDateFrom, 1, 6);
        downloadLayout.Controls.Add(lblDateTo, 2, 6);
        downloadLayout.Controls.Add(fieldDateTo, 3, 6);
        downloadLayout.Controls.Add(lblRepeatedItems, 0, 7);
        downloadLayout.Controls.Add(fieldRepeatedItems, 1, 7);
        downloadLayout.SetColumnSpan(fieldRepeatedItems, 3);
        downloadLayout.Controls.Add(lblDisplayMethod, 0, 8);
        downloadLayout.Controls.Add(fieldDisplayMethod, 1, 8);
        downloadLayout.SetColumnSpan(fieldDisplayMethod, 3);
        fieldLoadSource.Items.Add("فارق الجرد غير سنوي للأصناف المجرودة فقط");
        fieldDisplayMethod.Items.Add("رقم الصنف");
        btnLoadItems.Text = "إنزال الأصناف";
        btnLoadItems.Dock = DockStyle.Fill;
        btnLoadItems.Enabled = false;
        downloadLayout.Controls.Add(btnLoadItems, 4, 8);
        calculationLayout.Dock = DockStyle.Fill;
        calculationLayout.FlowDirection = FlowDirection.RightToLeft;
        calculationLayout.WrapContents = false;
        lblCalculationNote.Text = "سوف تجري عملية الاحتساب على جميع الأصناف المعروضة";
        lblCalculationNote.AutoSize = true;
        lblCalculationNote.ForeColor = Color.Maroon;
        fieldCalculationOperator.Dock = DockStyle.None;
        fieldCalculationOperator.Width = 60;
        fieldCalculationOperator.AccessibleName = "عامل الاحتساب";
        fieldPercentage.Dock = DockStyle.None;
        fieldPercentage.Width = 75;
        lblPercentage.Dock = DockStyle.None;
        lblPercentage.AutoSize = true;
        btnCalculate.Text = "أحسب";
        btnCalculate.AutoSize = true;
        btnCalculate.Enabled = false;
        calculationLayout.Controls.Add(lblCalculationNote);
        calculationLayout.Controls.Add(fieldCalculationOperator);
        calculationLayout.Controls.Add(fieldPercentage);
        calculationLayout.Controls.Add(lblPercentage);
        calculationLayout.Controls.Add(btnCalculate);
        downloadLayout.Controls.Add(calculationLayout, 0, 9);
        downloadLayout.SetColumnSpan(calculationLayout, 5);
        tabDownload.Controls.Add(downloadLayout);
        ResumeLayout(false);
    }
}
