using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcInventoryTransfer
{
    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private TabControl tabs = null!;
    private TabPage tabMain = null!;
    private TableLayoutPanel documentLayout = null!;
    private TableLayoutPanel headerLayout = null!;
    private Button btnJournalView = null!;
    private FlowLayoutPanel actionsLayout = null!;
    private CheckBox chkPosted = null!;
    private CheckBox chkUsed = null!;
    private CheckBox chkSuspended = null!;
    private CheckBox chkAvailableQuantity = null!;
    private CheckBox chkPackTransfer = null!;
    private TabPage tabDownload = null!;
    private TableLayoutPanel downloadLayout = null!;
    private FlowLayoutPanel downloadFlags = null!;
    private CheckBox chkExpiryAvailability = null!;
    private CheckBox chkUnavailableItems = null!;
    private Label lblLoadSource = null!;
    private ComboBox fieldLoadSource = null!;
    private Label lblRequestNumber = null!;
    private TextBox fieldRequestNumber = null!;
    private Button btnLoadItems = null!;
    private FlowLayoutPanel totalsLayout = null!;
    private Label lblGrandTotal = null!;
    private TextBox txtGrandTotal = null!;
    private DataGridView gridItems = null!;
    private Panel auditFooter = null!;
    private AuditMetadataControl standardAuditMetadata = null!;
    private Label lblBranch = null!;
    private ComboBox fieldBranch = null!;
    private Label lblTransferType = null!;
    private ComboBox fieldTransferType = null!;
    private Label lblTransferNumber = null!;
    private TextBox fieldTransferNumber = null!;
    private Label lblSourceWarehouse = null!;
    private TextBox fieldSourceWarehouse = null!;
    private Label lblDestinationWarehouse = null!;
    private TextBox fieldDestinationWarehouse = null!;
    private Label lblDate = null!;
    private TextBox fieldDate = null!;
    private Label lblSourceWarehouseName = null!;
    private TextBox fieldSourceWarehouseName = null!;
    private Label lblDestinationWarehouseName = null!;
    private TextBox fieldDestinationWarehouseName = null!;
    private Label lblDescription = null!;
    private TextBox fieldDescription = null!;
    private Label lblReason = null!;
    private TextBox fieldReason = null!;
    private Label lblReference = null!;
    private TextBox fieldReference = null!;
    private Label lblCostCenter = null!;
    private ComboBox fieldCostCenter = null!;
    private Label lblDriver = null!;
    private ComboBox fieldDriver = null!;
    private Label lblCustomer = null!;
    private ComboBox fieldCustomer = null!;
    private Label lblCostMethod = null!;
    private ComboBox fieldCostMethod = null!;
    private Label lblDifferenceAccount = null!;
    private TextBox fieldDifferenceAccount = null!;
    private Label lblAmount = null!;
    private TextBox fieldAmount = null!;
    private Label lblCurrency = null!;
    private TextBox fieldCurrency = null!;
    private Label lblPriceLevel = null!;
    private ComboBox fieldPriceLevel = null!;
    private Label lblDefaultQuantity = null!;
    private TextBox fieldDefaultQuantity = null!;
    private Label lblSourceDocument = null!;
    private TextBox fieldSourceDocument = null!;
    private DataGridViewTextBoxColumn colSequence = null!;
    private DataGridViewButtonColumn colLookup = null!;
    private DataGridViewTextBoxColumn colItemNumber = null!;
    private DataGridViewTextBoxColumn colItemName = null!;
    private DataGridViewTextBoxColumn colUnit = null!;
    private DataGridViewTextBoxColumn colExpiryDate = null!;
    private DataGridViewTextBoxColumn colQuantity = null!;
    private DataGridViewTextBoxColumn colAvailableFrom = null!;
    private DataGridViewTextBoxColumn colAvailableTo = null!;
    private DataGridViewTextBoxColumn colAvailableReference = null!;
    private DataGridViewTextBoxColumn colPrice = null!;
    private DataGridViewTextBoxColumn colTotal = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        tabs = new TabControl();
        tabs.Name = "tabs";
        tabMain = new TabPage();
        tabMain.Name = "tabMain";
        documentLayout = new TableLayoutPanel();
        documentLayout.Name = "documentLayout";
        headerLayout = new TableLayoutPanel();
        headerLayout.Name = "headerLayout";
        btnJournalView = new Button();
        btnJournalView.Name = "btnJournalView";
        btnJournalView.Text = "اليومية العامة";
        btnJournalView.AccessibleName = "اليومية العامة";
        btnJournalView.AutoSize = true;
        btnJournalView.Click += JournalView_Click;
        actionsLayout = new FlowLayoutPanel();
        actionsLayout.Name = "actionsLayout";
        chkPosted = new CheckBox();
        chkPosted.Name = "chkPosted";
        chkUsed = new CheckBox();
        chkUsed.Name = "chkUsed";
        chkSuspended = new CheckBox();
        chkSuspended.Name = "chkSuspended";
        chkAvailableQuantity = new CheckBox();
        chkAvailableQuantity.Name = "chkAvailableQuantity";
        chkPackTransfer = new CheckBox();
        chkPackTransfer.Name = "chkPackTransfer";
        tabDownload = new TabPage();
        tabDownload.Name = "tabDownload";
        downloadLayout = new TableLayoutPanel();
        downloadLayout.Name = "downloadLayout";
        downloadFlags = new FlowLayoutPanel();
        downloadFlags.Name = "downloadFlags";
        chkExpiryAvailability = new CheckBox();
        chkExpiryAvailability.Name = "chkExpiryAvailability";
        chkUnavailableItems = new CheckBox();
        chkUnavailableItems.Name = "chkUnavailableItems";
        lblLoadSource = new Label();
        lblLoadSource.Name = "lblLoadSource";
        fieldLoadSource = new ComboBox();
        fieldLoadSource.Name = "fieldLoadSource";
        lblRequestNumber = new Label();
        lblRequestNumber.Name = "lblRequestNumber";
        fieldRequestNumber = new TextBox();
        fieldRequestNumber.Name = "fieldRequestNumber";
        btnLoadItems = new Button();
        btnLoadItems.Name = "btnLoadItems";
        totalsLayout = new FlowLayoutPanel();
        totalsLayout.Name = "totalsLayout";
        lblGrandTotal = new Label();
        lblGrandTotal.Name = "lblGrandTotal";
        txtGrandTotal = new TextBox();
        txtGrandTotal.Name = "txtGrandTotal";
        gridItems = new DataGridView();
        gridItems.Name = "gridItems";
        gridItems.KeyDown += LookupVisual_KeyDown;
        auditFooter = new Panel();
        auditFooter.Name = "auditFooter";
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        lblBranch = new Label();
        lblBranch.Name = "lblBranch";
        fieldBranch = new ComboBox();
        fieldBranch.Name = "fieldBranch";
        lblTransferType = new Label();
        lblTransferType.Name = "lblTransferType";
        fieldTransferType = new ComboBox();
        fieldTransferType.Name = "fieldTransferType";
        lblTransferNumber = new Label();
        lblTransferNumber.Name = "lblTransferNumber";
        fieldTransferNumber = new TextBox();
        fieldTransferNumber.Name = "fieldTransferNumber";
        lblSourceWarehouse = new Label();
        lblSourceWarehouse.Name = "lblSourceWarehouse";
        fieldSourceWarehouse = new TextBox();
        fieldSourceWarehouse.Name = "fieldSourceWarehouse";
        lblDestinationWarehouse = new Label();
        lblDestinationWarehouse.Name = "lblDestinationWarehouse";
        fieldDestinationWarehouse = new TextBox();
        fieldDestinationWarehouse.Name = "fieldDestinationWarehouse";
        lblDate = new Label();
        lblDate.Name = "lblDate";
        fieldDate = new TextBox();
        fieldDate.Name = "fieldDate";
        lblSourceWarehouseName = new Label();
        lblSourceWarehouseName.Name = "lblSourceWarehouseName";
        fieldSourceWarehouseName = new TextBox();
        fieldSourceWarehouseName.Name = "fieldSourceWarehouseName";
        lblDestinationWarehouseName = new Label();
        lblDestinationWarehouseName.Name = "lblDestinationWarehouseName";
        fieldDestinationWarehouseName = new TextBox();
        fieldDestinationWarehouseName.Name = "fieldDestinationWarehouseName";
        lblDescription = new Label();
        lblDescription.Name = "lblDescription";
        fieldDescription = new TextBox();
        fieldDescription.Name = "fieldDescription";
        lblReason = new Label();
        lblReason.Name = "lblReason";
        fieldReason = new TextBox();
        fieldReason.Name = "fieldReason";
        lblReference = new Label();
        lblReference.Name = "lblReference";
        fieldReference = new TextBox();
        fieldReference.Name = "fieldReference";
        lblCostCenter = new Label();
        lblCostCenter.Name = "lblCostCenter";
        fieldCostCenter = new ComboBox();
        fieldCostCenter.Name = "fieldCostCenter";
        lblDriver = new Label();
        lblDriver.Name = "lblDriver";
        fieldDriver = new ComboBox();
        fieldDriver.Name = "fieldDriver";
        lblCustomer = new Label();
        lblCustomer.Name = "lblCustomer";
        fieldCustomer = new ComboBox();
        fieldCustomer.Name = "fieldCustomer";
        lblCostMethod = new Label();
        lblCostMethod.Name = "lblCostMethod";
        fieldCostMethod = new ComboBox();
        fieldCostMethod.Name = "fieldCostMethod";
        lblDifferenceAccount = new Label();
        lblDifferenceAccount.Name = "lblDifferenceAccount";
        fieldDifferenceAccount = new TextBox();
        fieldDifferenceAccount.Name = "fieldDifferenceAccount";
        lblAmount = new Label();
        lblAmount.Name = "lblAmount";
        fieldAmount = new TextBox();
        fieldAmount.Name = "fieldAmount";
        lblCurrency = new Label();
        lblCurrency.Name = "lblCurrency";
        fieldCurrency = new TextBox();
        fieldCurrency.Name = "fieldCurrency";
        lblPriceLevel = new Label();
        lblPriceLevel.Name = "lblPriceLevel";
        fieldPriceLevel = new ComboBox();
        fieldPriceLevel.Name = "fieldPriceLevel";
        lblDefaultQuantity = new Label();
        lblDefaultQuantity.Name = "lblDefaultQuantity";
        fieldDefaultQuantity = new TextBox();
        fieldDefaultQuantity.Name = "fieldDefaultQuantity";
        lblSourceDocument = new Label();
        lblSourceDocument.Name = "lblSourceDocument";
        fieldSourceDocument = new TextBox();
        fieldSourceDocument.Name = "fieldSourceDocument";
        colSequence = new DataGridViewTextBoxColumn();
        colSequence.Name = "colSequence";
        colLookup = new DataGridViewButtonColumn();
        colLookup.Name = "colLookup";
        colItemNumber = new DataGridViewTextBoxColumn();
        colItemNumber.Name = "colItemNumber";
        colItemName = new DataGridViewTextBoxColumn();
        colItemName.Name = "colItemName";
        colUnit = new DataGridViewTextBoxColumn();
        colUnit.Name = "colUnit";
        colExpiryDate = new DataGridViewTextBoxColumn();
        colExpiryDate.Name = "colExpiryDate";
        colQuantity = new DataGridViewTextBoxColumn();
        colQuantity.Name = "colQuantity";
        colAvailableFrom = new DataGridViewTextBoxColumn();
        colAvailableFrom.Name = "colAvailableFrom";
        colAvailableTo = new DataGridViewTextBoxColumn();
        colAvailableTo.Name = "colAvailableTo";
        colAvailableReference = new DataGridViewTextBoxColumn();
        colAvailableReference.Name = "colAvailableReference";
        colPrice = new DataGridViewTextBoxColumn();
        colPrice.Name = "colPrice";
        colTotal = new DataGridViewTextBoxColumn();
        colTotal.Name = "colTotal";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = Padding.Empty;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.BackColor = Color.FromArgb(23, 50, 78);
        lblTitle.ForeColor = Color.White;
        commandBar.Dock = DockStyle.Fill;
        commandBar.Margin = Padding.Empty;
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeftLayout = true;
        tabMain.Text = "البيانات الرئيسية";
        tabMain.Padding = Padding.Empty;
        tabs.Controls.Add(tabMain);
        documentLayout.Dock = DockStyle.Fill;
        documentLayout.ColumnCount = 1;
        documentLayout.RowCount = 4;
        documentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 236F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tabMain.Controls.Add(documentLayout);
        headerLayout.Dock = DockStyle.Fill;
        headerLayout.Padding = new Padding(10, 6, 10, 6);
        headerLayout.Margin = Padding.Empty;
        headerLayout.ColumnCount = 6;
        headerLayout.RowCount = 7;
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        lblBranch.Text = "الفرع";
        lblBranch.Dock = DockStyle.Fill;
        lblBranch.TextAlign = ContentAlignment.MiddleLeft;
        fieldBranch.AccessibleName = "الفرع";
        fieldBranch.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblBranch, 0, 0);
        headerLayout.Controls.Add(fieldBranch, 1, 0);
        fieldBranch.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldBranch.Enabled = false;
        lblTransferType.Text = "نوع التحويل";
        lblTransferType.Dock = DockStyle.Fill;
        lblTransferType.TextAlign = ContentAlignment.MiddleLeft;
        fieldTransferType.AccessibleName = "نوع التحويل";
        fieldTransferType.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblTransferType, 2, 0);
        headerLayout.Controls.Add(fieldTransferType, 3, 0);
        fieldTransferType.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldTransferType.Enabled = false;
        lblTransferNumber.Text = "رقم التحويل";
        lblTransferNumber.Dock = DockStyle.Fill;
        lblTransferNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldTransferNumber.AccessibleName = "رقم التحويل";
        fieldTransferNumber.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblTransferNumber, 4, 0);
        headerLayout.Controls.Add(fieldTransferNumber, 5, 0);
        fieldTransferNumber.ReadOnly = true;
        lblSourceWarehouse.Text = "رقم المخزن";
        lblSourceWarehouse.Dock = DockStyle.Fill;
        lblSourceWarehouse.TextAlign = ContentAlignment.MiddleLeft;
        fieldSourceWarehouse.AccessibleName = "رقم المخزن";
        fieldSourceWarehouse.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblSourceWarehouse, 0, 1);
        headerLayout.Controls.Add(fieldSourceWarehouse, 1, 1);
        fieldSourceWarehouse.ReadOnly = true;
        lblDestinationWarehouse.Text = "المخزن المحول إليه";
        lblDestinationWarehouse.Dock = DockStyle.Fill;
        lblDestinationWarehouse.TextAlign = ContentAlignment.MiddleLeft;
        fieldDestinationWarehouse.AccessibleName = "المخزن المحول إليه";
        fieldDestinationWarehouse.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDestinationWarehouse, 2, 1);
        headerLayout.Controls.Add(fieldDestinationWarehouse, 3, 1);
        fieldDestinationWarehouse.ReadOnly = true;
        lblDate.Text = "تاريخ التحويل";
        lblDate.Dock = DockStyle.Fill;
        lblDate.TextAlign = ContentAlignment.MiddleLeft;
        fieldDate.AccessibleName = "تاريخ التحويل";
        fieldDate.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDate, 4, 1);
        headerLayout.Controls.Add(fieldDate, 5, 1);
        fieldDate.ReadOnly = true;
        lblSourceWarehouseName.Text = "اسم المخزن";
        lblSourceWarehouseName.Dock = DockStyle.Fill;
        lblSourceWarehouseName.TextAlign = ContentAlignment.MiddleLeft;
        fieldSourceWarehouseName.AccessibleName = "اسم المخزن";
        fieldSourceWarehouseName.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblSourceWarehouseName, 0, 2);
        headerLayout.Controls.Add(fieldSourceWarehouseName, 1, 2);
        fieldSourceWarehouseName.ReadOnly = true;
        lblDestinationWarehouseName.Text = "اسم المخزن المحول إليه";
        lblDestinationWarehouseName.Dock = DockStyle.Fill;
        lblDestinationWarehouseName.TextAlign = ContentAlignment.MiddleLeft;
        fieldDestinationWarehouseName.AccessibleName = "اسم المخزن المحول إليه";
        fieldDestinationWarehouseName.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDestinationWarehouseName, 2, 2);
        headerLayout.Controls.Add(fieldDestinationWarehouseName, 3, 2);
        fieldDestinationWarehouseName.ReadOnly = true;
        lblDescription.Text = "البيان";
        lblDescription.Dock = DockStyle.Fill;
        lblDescription.TextAlign = ContentAlignment.MiddleLeft;
        fieldDescription.AccessibleName = "البيان";
        fieldDescription.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDescription, 4, 2);
        headerLayout.Controls.Add(fieldDescription, 5, 2);
        fieldDescription.ReadOnly = true;
        lblReason.Text = "السبب";
        lblReason.Dock = DockStyle.Fill;
        lblReason.TextAlign = ContentAlignment.MiddleLeft;
        fieldReason.AccessibleName = "السبب";
        fieldReason.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblReason, 0, 3);
        headerLayout.Controls.Add(fieldReason, 1, 3);
        fieldReason.ReadOnly = true;
        lblReference.Text = "رقم المرجع";
        lblReference.Dock = DockStyle.Fill;
        lblReference.TextAlign = ContentAlignment.MiddleLeft;
        fieldReference.AccessibleName = "رقم المرجع";
        fieldReference.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblReference, 2, 3);
        headerLayout.Controls.Add(fieldReference, 3, 3);
        fieldReference.ReadOnly = true;
        lblCostCenter.Text = "مركز التكلفة";
        lblCostCenter.Dock = DockStyle.Fill;
        lblCostCenter.TextAlign = ContentAlignment.MiddleLeft;
        fieldCostCenter.AccessibleName = "مركز التكلفة";
        fieldCostCenter.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblCostCenter, 4, 3);
        headerLayout.Controls.Add(fieldCostCenter, 5, 3);
        fieldCostCenter.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldCostCenter.Enabled = false;
        lblDriver.Text = "رقم السائق";
        lblDriver.Dock = DockStyle.Fill;
        lblDriver.TextAlign = ContentAlignment.MiddleLeft;
        fieldDriver.AccessibleName = "رقم السائق";
        fieldDriver.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDriver, 0, 4);
        headerLayout.Controls.Add(fieldDriver, 1, 4);
        fieldDriver.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldDriver.Enabled = false;
        lblCustomer.Text = "العميل";
        lblCustomer.Dock = DockStyle.Fill;
        lblCustomer.TextAlign = ContentAlignment.MiddleLeft;
        fieldCustomer.AccessibleName = "العميل";
        fieldCustomer.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblCustomer, 2, 4);
        headerLayout.Controls.Add(fieldCustomer, 3, 4);
        fieldCustomer.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldCustomer.Enabled = false;
        lblCostMethod.Text = "طريقة تكاليف التحويل";
        lblCostMethod.Dock = DockStyle.Fill;
        lblCostMethod.TextAlign = ContentAlignment.MiddleLeft;
        fieldCostMethod.AccessibleName = "طريقة تكاليف التحويل";
        fieldCostMethod.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblCostMethod, 4, 4);
        headerLayout.Controls.Add(fieldCostMethod, 5, 4);
        fieldCostMethod.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldCostMethod.Enabled = false;
        lblDifferenceAccount.Text = "حساب الفارق";
        lblDifferenceAccount.Dock = DockStyle.Fill;
        lblDifferenceAccount.TextAlign = ContentAlignment.MiddleLeft;
        fieldDifferenceAccount.AccessibleName = "حساب الفارق";
        fieldDifferenceAccount.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDifferenceAccount, 0, 5);
        headerLayout.Controls.Add(fieldDifferenceAccount, 1, 5);
        fieldDifferenceAccount.ReadOnly = true;
        lblAmount.Text = "المبلغ";
        lblAmount.Dock = DockStyle.Fill;
        lblAmount.TextAlign = ContentAlignment.MiddleLeft;
        fieldAmount.AccessibleName = "المبلغ";
        fieldAmount.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblAmount, 2, 5);
        headerLayout.Controls.Add(fieldAmount, 3, 5);
        fieldAmount.ReadOnly = true;
        lblCurrency.Text = "العملة";
        lblCurrency.Dock = DockStyle.Fill;
        lblCurrency.TextAlign = ContentAlignment.MiddleLeft;
        fieldCurrency.AccessibleName = "العملة";
        fieldCurrency.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblCurrency, 4, 5);
        headerLayout.Controls.Add(fieldCurrency, 5, 5);
        fieldCurrency.ReadOnly = true;
        lblPriceLevel.Text = "مستوى التسعيرة";
        lblPriceLevel.Dock = DockStyle.Fill;
        lblPriceLevel.TextAlign = ContentAlignment.MiddleLeft;
        fieldPriceLevel.AccessibleName = "مستوى التسعيرة";
        fieldPriceLevel.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblPriceLevel, 0, 6);
        headerLayout.Controls.Add(fieldPriceLevel, 1, 6);
        fieldPriceLevel.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldPriceLevel.Enabled = false;
        lblDefaultQuantity.Text = "الكمية الافتراضية";
        lblDefaultQuantity.Dock = DockStyle.Fill;
        lblDefaultQuantity.TextAlign = ContentAlignment.MiddleLeft;
        fieldDefaultQuantity.AccessibleName = "الكمية الافتراضية";
        fieldDefaultQuantity.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDefaultQuantity, 2, 6);
        headerLayout.Controls.Add(fieldDefaultQuantity, 3, 6);
        fieldDefaultQuantity.ReadOnly = true;
        lblSourceDocument.Text = "رقم الوثيقة المرجع";
        lblSourceDocument.Dock = DockStyle.Fill;
        lblSourceDocument.TextAlign = ContentAlignment.MiddleLeft;
        fieldSourceDocument.AccessibleName = "رقم الوثيقة المرجع";
        fieldSourceDocument.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblSourceDocument, 4, 6);
        headerLayout.Controls.Add(fieldSourceDocument, 5, 6);
        fieldSourceDocument.ReadOnly = true;
        actionsLayout.Dock = DockStyle.Fill;
        actionsLayout.FlowDirection = FlowDirection.RightToLeft;
        actionsLayout.WrapContents = false;
        actionsLayout.Margin = Padding.Empty;
        actionsLayout.Controls.Add(btnJournalView);
        chkPosted.Text = "مرحل";
        chkPosted.AutoSize = true;
        chkPosted.Enabled = false;
        actionsLayout.Controls.Add(chkPosted);
        chkUsed.Text = "مستخدم";
        chkUsed.AutoSize = true;
        chkUsed.Enabled = false;
        actionsLayout.Controls.Add(chkUsed);
        chkSuspended.Text = "تعليق";
        chkSuspended.AutoSize = true;
        chkSuspended.Enabled = false;
        actionsLayout.Controls.Add(chkSuspended);
        chkAvailableQuantity.Text = "إنزال الكمية المتوفرة";
        chkAvailableQuantity.AutoSize = true;
        chkAvailableQuantity.Enabled = false;
        actionsLayout.Controls.Add(chkAvailableQuantity);
        chkPackTransfer.Text = "التحويل بالشد";
        chkPackTransfer.AutoSize = true;
        chkPackTransfer.Enabled = false;
        actionsLayout.Controls.Add(chkPackTransfer);
        gridItems.Dock = DockStyle.Fill;
        gridItems.AccessibleName = "أصناف التحويل المخزني";
        gridItems.ReadOnly = true;
        gridItems.AllowUserToAddRows = false;
        gridItems.AllowUserToDeleteRows = false;
        gridItems.AutoGenerateColumns = false;
        gridItems.RowHeadersVisible = false;
        gridItems.BackgroundColor = Color.White;
        gridItems.ColumnHeadersHeight = 34;
        gridItems.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridItems.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        colSequence.HeaderText = "م";
        colSequence.Width = 40;
        colSequence.ReadOnly = true;
        colSequence.SortMode = DataGridViewColumnSortMode.NotSortable;
        colLookup.HeaderText = "";
        colLookup.Width = 30;
        colLookup.ReadOnly = true;
        colLookup.SortMode = DataGridViewColumnSortMode.NotSortable;
        colLookup.Text = "…";
        colLookup.UseColumnTextForButtonValue = true;
        colItemNumber.HeaderText = "رقم الصنف";
        colItemNumber.Width = 125;
        colItemNumber.ReadOnly = true;
        colItemNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colItemName.HeaderText = "اسم الصنف";
        colItemName.Width = 220;
        colItemName.ReadOnly = true;
        colItemName.SortMode = DataGridViewColumnSortMode.NotSortable;
        colUnit.HeaderText = "الوحدة";
        colUnit.Width = 75;
        colUnit.ReadOnly = true;
        colUnit.SortMode = DataGridViewColumnSortMode.NotSortable;
        colExpiryDate.HeaderText = "تاريخ الانتهاء";
        colExpiryDate.Width = 115;
        colExpiryDate.ReadOnly = true;
        colExpiryDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        colQuantity.HeaderText = "الكمية";
        colQuantity.Width = 85;
        colQuantity.ReadOnly = true;
        colQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        colAvailableFrom.HeaderText = "ك.م.من";
        colAvailableFrom.Width = 85;
        colAvailableFrom.ReadOnly = true;
        colAvailableFrom.SortMode = DataGridViewColumnSortMode.NotSortable;
        colAvailableTo.HeaderText = "ك.م.إلى";
        colAvailableTo.Width = 85;
        colAvailableTo.ReadOnly = true;
        colAvailableTo.SortMode = DataGridViewColumnSortMode.NotSortable;
        colAvailableReference.HeaderText = "ك.م.ع.م";
        colAvailableReference.Width = 85;
        colAvailableReference.ReadOnly = true;
        colAvailableReference.SortMode = DataGridViewColumnSortMode.NotSortable;
        colPrice.HeaderText = "السعر";
        colPrice.Width = 100;
        colPrice.ReadOnly = true;
        colPrice.SortMode = DataGridViewColumnSortMode.NotSortable;
        colTotal.HeaderText = "الإجمالي";
        colTotal.Width = 110;
        colTotal.ReadOnly = true;
        colTotal.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.AddRange(new DataGridViewColumn[] { colSequence, colLookup, colItemNumber, colItemName, colUnit, colExpiryDate, colQuantity, colAvailableFrom, colAvailableTo, colAvailableReference, colPrice, colTotal });
        documentLayout.Controls.Add(headerLayout, 0, 0);
        documentLayout.Controls.Add(actionsLayout, 0, 1);
        documentLayout.Controls.Add(gridItems, 0, 2);
        auditFooter.Dock = DockStyle.Fill;
        auditFooter.Margin = Padding.Empty;
        standardAuditMetadata.Dock = DockStyle.Fill;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.Profile = AuditMetadataProfile.Standard;
        auditFooter.Controls.Add(standardAuditMetadata);
        mainLayout.Controls.Add(lblTitle, 0, 0);
        mainLayout.Controls.Add(commandBar, 0, 1);
        mainLayout.Controls.Add(tabs, 0, 2);
        mainLayout.Controls.Add(auditFooter, 0, 3);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 9F);
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1180, 720);
        MinimumSize = new Size(1000, 600);
        Controls.Add(mainLayout);
        lblTitle.Text = "التحويل المخزني";
        Name = "UcInventoryTransfer";
        Text = "التحويل المخزني";
        Tag = "INV:TRANSFER";
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        totalsLayout.Dock = DockStyle.Fill;
        totalsLayout.FlowDirection = FlowDirection.RightToLeft;
        totalsLayout.WrapContents = false;
        lblGrandTotal.Text = "الإجمالي الكلي";
        lblGrandTotal.AutoSize = true;
        txtGrandTotal.ReadOnly = true;
        txtGrandTotal.Width = 150;
        totalsLayout.Controls.Add(lblGrandTotal);
        totalsLayout.Controls.Add(txtGrandTotal);
        documentLayout.Controls.Add(totalsLayout, 0, 3);
        fieldCostMethod.Items.AddRange(new object[] { "التكلفة", "آخر سعر توريد", "سعر البيع" });
        tabDownload.Text = "إنزال البيانات";
        tabs.Controls.Add(tabDownload);
        downloadLayout.Dock = DockStyle.Fill;
        downloadLayout.Padding = new Padding(12);
        downloadLayout.ColumnCount = 5;
        downloadLayout.RowCount = 3;
        downloadLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
        downloadLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 60F));
        downloadLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 110F));
        downloadLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 40F));
        downloadLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 130F));
        downloadLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
        downloadLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        downloadLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        downloadFlags.Dock = DockStyle.Fill;
        downloadFlags.FlowDirection = FlowDirection.RightToLeft;
        downloadFlags.WrapContents = false;
        chkExpiryAvailability.Text = "تحليل الكمية المتوفرة حسب تاريخ الانتهاء";
        chkExpiryAvailability.AutoSize = true;
        chkExpiryAvailability.Enabled = false;
        chkUnavailableItems.Text = "إنزال الأصناف غير المتوفرة كمياتها";
        chkUnavailableItems.AutoSize = true;
        chkUnavailableItems.Enabled = false;
        downloadFlags.Controls.Add(chkExpiryAvailability);
        downloadFlags.Controls.Add(chkUnavailableItems);
        downloadLayout.Controls.Add(downloadFlags, 0, 0);
        downloadLayout.SetColumnSpan(downloadFlags, 5);
        lblLoadSource.Text = "إنزال البيانات من";
        lblLoadSource.Dock = DockStyle.Fill;
        lblLoadSource.TextAlign = ContentAlignment.MiddleLeft;
        fieldLoadSource.AccessibleName = "إنزال البيانات من";
        fieldLoadSource.Dock = DockStyle.Fill;
        fieldLoadSource.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldLoadSource.Items.Add("طلب مخزني");
        fieldLoadSource.Enabled = false;
        lblRequestNumber.Text = "رقم الطلب";
        lblRequestNumber.Dock = DockStyle.Fill;
        lblRequestNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldRequestNumber.AccessibleName = "رقم الطلب";
        fieldRequestNumber.Dock = DockStyle.Fill;
        fieldRequestNumber.ReadOnly = true;
        btnLoadItems.Text = "إنزال الأصناف";
        btnLoadItems.Dock = DockStyle.Fill;
        btnLoadItems.Enabled = false;
        downloadLayout.Controls.Add(lblLoadSource, 0, 1);
        downloadLayout.Controls.Add(fieldLoadSource, 1, 1);
        downloadLayout.Controls.Add(lblRequestNumber, 2, 1);
        downloadLayout.Controls.Add(fieldRequestNumber, 3, 1);
        downloadLayout.Controls.Add(btnLoadItems, 4, 1);
        tabDownload.Controls.Add(downloadLayout);
        ResumeLayout(false);
    }
}
