using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcInventoryReceiptOrder
{
    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private TabControl tabs = null!;
    private TabPage tabMain = null!;
    private TableLayoutPanel documentLayout = null!;
    private TableLayoutPanel headerLayout = null!;
    private FlowLayoutPanel actionsLayout = null!;
    private CheckBox chkPosted = null!;
    private CheckBox chkSuspended = null!;
    private Button btnJournalView = null!;
    private DataGridView gridItems = null!;
    private Panel auditFooter = null!;
    private AuditMetadataControl standardAuditMetadata = null!;
    private Label lblBranch = null!;
    private ComboBox fieldBranch = null!;
    private Label lblReceiptType = null!;
    private ComboBox fieldReceiptType = null!;
    private Label lblReceiptNumber = null!;
    private TextBox fieldReceiptNumber = null!;
    private Label lblDate = null!;
    private TextBox fieldDate = null!;
    private Label lblWarehouse = null!;
    private ComboBox fieldWarehouse = null!;
    private Label lblAccountNumber = null!;
    private TextBox fieldAccountNumber = null!;
    private Label lblAccountName = null!;
    private TextBox fieldAccountName = null!;
    private Label lblAnalyticalAccount = null!;
    private TextBox fieldAnalyticalAccount = null!;
    private Label lblAnalyticalName = null!;
    private TextBox fieldAnalyticalName = null!;
    private Label lblCurrency = null!;
    private TextBox fieldCurrency = null!;
    private Label lblAccountRate = null!;
    private TextBox fieldAccountRate = null!;
    private Label lblReference = null!;
    private TextBox fieldReference = null!;
    private Label lblDescription = null!;
    private TextBox fieldDescription = null!;
    private Label lblAttachmentCount = null!;
    private TextBox fieldAttachmentCount = null!;
    private Label lblDueDate = null!;
    private TextBox fieldDueDate = null!;
    private Label lblCostMethod = null!;
    private ComboBox fieldCostMethod = null!;
    private Label lblVehicleNumber = null!;
    private TextBox fieldVehicleNumber = null!;
    private Label lblDriverName = null!;
    private TextBox fieldDriverName = null!;
    private Label lblCostCenter = null!;
    private ComboBox fieldCostCenter = null!;
    private DataGridViewButtonColumn colLookup = null!;
    private DataGridViewTextBoxColumn colSequence = null!;
    private DataGridViewTextBoxColumn colItemNumber = null!;
    private DataGridViewTextBoxColumn colItemName = null!;
    private DataGridViewTextBoxColumn colUnit = null!;
    private DataGridViewTextBoxColumn colExpiryDate = null!;
    private DataGridViewTextBoxColumn colQuantity = null!;
    private DataGridViewTextBoxColumn colCost = null!;
    private DataGridViewTextBoxColumn colTotal = null!;
    private DataGridViewTextBoxColumn colExtra1 = null!;
    private DataGridViewTextBoxColumn colExtra2 = null!;
    private DataGridViewTextBoxColumn colExtra3 = null!;
    private TableLayoutPanel mainTabLayout = null!;
    private TabPage tabDownload = null!;
    private TableLayoutPanel downloadHeader = null!;
    private TableLayoutPanel totalsLayout = null!;
    private Label lblDownloadSource = null!;
    private ComboBox downloadSource = null!;
    private Label lblDownloadAuthorizationNumber = null!;
    private TextBox downloadAuthorizationNumber = null!;
    private Label lblDownloadDifferenceAccount = null!;
    private TextBox downloadDifferenceAccount = null!;
    private Label lblDownloadAmount = null!;
    private TextBox downloadAmount = null!;
    private Label lblTotalAfterTax = null!;
    private TextBox txtTotalAfterTax = null!;
    private Label lblTotalGrand = null!;
    private TextBox txtTotalGrand = null!;
    private Label lblTotalQuantity = null!;
    private TextBox txtTotalQuantity = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        tabs = new TabControl();
        tabs.Name = "tabs";
        tabMain = new TabPage();
        tabMain.Name = "tabMain";
        documentLayout = new TableLayoutPanel();
        documentLayout.Name = "documentLayout";
        headerLayout = new TableLayoutPanel();
        headerLayout.Name = "headerLayout";
        actionsLayout = new FlowLayoutPanel();
        actionsLayout.Name = "actionsLayout";
        chkPosted = new CheckBox();
        chkPosted.Name = "chkPosted";
        chkSuspended = new CheckBox();
        chkSuspended.Name = "chkSuspended";
        btnJournalView = new Button();
        btnJournalView.Name = "btnJournalView";
        gridItems = new DataGridView();
        gridItems.Name = "gridItems";
        gridItems.KeyDown += ReceiptItemLookup_KeyDown;
        auditFooter = new Panel();
        auditFooter.Name = "auditFooter";
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        lblBranch = new Label();
        lblBranch.Name = "lblBranch";
        fieldBranch = new ComboBox();
        fieldBranch.Name = "fieldBranch";
        lblReceiptType = new Label();
        lblReceiptType.Name = "lblReceiptType";
        fieldReceiptType = new ComboBox();
        fieldReceiptType.Name = "fieldReceiptType";
        lblReceiptNumber = new Label();
        lblReceiptNumber.Name = "lblReceiptNumber";
        fieldReceiptNumber = new TextBox();
        fieldReceiptNumber.Name = "fieldReceiptNumber";
        lblDate = new Label();
        lblDate.Name = "lblDate";
        fieldDate = new TextBox();
        fieldDate.Name = "fieldDate";
        lblWarehouse = new Label();
        lblWarehouse.Name = "lblWarehouse";
        fieldWarehouse = new ComboBox();
        fieldWarehouse.Name = "fieldWarehouse";
        lblAccountNumber = new Label();
        lblAccountNumber.Name = "lblAccountNumber";
        fieldAccountNumber = new TextBox();
        fieldAccountNumber.Name = "fieldAccountNumber";
        lblAccountName = new Label();
        lblAccountName.Name = "lblAccountName";
        fieldAccountName = new TextBox();
        fieldAccountName.Name = "fieldAccountName";
        lblAnalyticalAccount = new Label();
        lblAnalyticalAccount.Name = "lblAnalyticalAccount";
        fieldAnalyticalAccount = new TextBox();
        fieldAnalyticalAccount.Name = "fieldAnalyticalAccount";
        lblAnalyticalName = new Label();
        lblAnalyticalName.Name = "lblAnalyticalName";
        fieldAnalyticalName = new TextBox();
        fieldAnalyticalName.Name = "fieldAnalyticalName";
        lblCurrency = new Label();
        lblCurrency.Name = "lblCurrency";
        fieldCurrency = new TextBox();
        fieldCurrency.Name = "fieldCurrency";
        lblAccountRate = new Label();
        lblAccountRate.Name = "lblAccountRate";
        fieldAccountRate = new TextBox();
        fieldAccountRate.Name = "fieldAccountRate";
        lblReference = new Label();
        lblReference.Name = "lblReference";
        fieldReference = new TextBox();
        fieldReference.Name = "fieldReference";
        lblDescription = new Label();
        lblDescription.Name = "lblDescription";
        fieldDescription = new TextBox();
        fieldDescription.Name = "fieldDescription";
        lblAttachmentCount = new Label();
        lblAttachmentCount.Name = "lblAttachmentCount";
        fieldAttachmentCount = new TextBox();
        fieldAttachmentCount.Name = "fieldAttachmentCount";
        lblDueDate = new Label();
        lblDueDate.Name = "lblDueDate";
        fieldDueDate = new TextBox();
        fieldDueDate.Name = "fieldDueDate";
        lblCostMethod = new Label();
        lblCostMethod.Name = "lblCostMethod";
        fieldCostMethod = new ComboBox();
        fieldCostMethod.Name = "fieldCostMethod";
        lblVehicleNumber = new Label();
        lblVehicleNumber.Name = "lblVehicleNumber";
        fieldVehicleNumber = new TextBox();
        fieldVehicleNumber.Name = "fieldVehicleNumber";
        lblDriverName = new Label();
        lblDriverName.Name = "lblDriverName";
        fieldDriverName = new TextBox();
        fieldDriverName.Name = "fieldDriverName";
        lblCostCenter = new Label();
        lblCostCenter.Name = "lblCostCenter";
        fieldCostCenter = new ComboBox();
        fieldCostCenter.Name = "fieldCostCenter";
        colLookup = new DataGridViewButtonColumn();
        colLookup.Name = "colLookup";
        colSequence = new DataGridViewTextBoxColumn();
        colSequence.Name = "colSequence";
        colItemNumber = new DataGridViewTextBoxColumn();
        colItemNumber.Name = "colItemNumber";
        colItemName = new DataGridViewTextBoxColumn();
        colItemName.Name = "colItemName";
        colUnit = new DataGridViewTextBoxColumn();
        colUnit.Name = "colUnit";
        colExpiryDate = new DataGridViewTextBoxColumn();
        colExpiryDate.Name = "colExpiryDate";
        colQuantity = new DataGridViewTextBoxColumn();
        colQuantity.Name = "colQuantity";
        colCost = new DataGridViewTextBoxColumn();
        colCost.Name = "colCost";
        colTotal = new DataGridViewTextBoxColumn();
        colTotal.Name = "colTotal";
        colExtra1 = new DataGridViewTextBoxColumn();
        colExtra1.Name = "colExtra1";
        colExtra2 = new DataGridViewTextBoxColumn();
        colExtra2.Name = "colExtra2";
        colExtra3 = new DataGridViewTextBoxColumn();
        colExtra3.Name = "colExtra3";
        mainTabLayout = new TableLayoutPanel();
        mainTabLayout.Name = "mainTabLayout";
        tabDownload = new TabPage();
        tabDownload.Name = "tabDownload";
        downloadHeader = new TableLayoutPanel();
        downloadHeader.Name = "downloadHeader";
        totalsLayout = new TableLayoutPanel();
        totalsLayout.Name = "totalsLayout";
        lblDownloadSource = new Label();
        lblDownloadSource.Name = "lblDownloadSource";
        downloadSource = new ComboBox();
        downloadSource.Name = "downloadSource";
        lblDownloadAuthorizationNumber = new Label();
        lblDownloadAuthorizationNumber.Name = "lblDownloadAuthorizationNumber";
        downloadAuthorizationNumber = new TextBox();
        downloadAuthorizationNumber.Name = "downloadAuthorizationNumber";
        downloadAuthorizationNumber.KeyDown += AuthorizationLookup_KeyDown;
        lblDownloadDifferenceAccount = new Label();
        lblDownloadDifferenceAccount.Name = "lblDownloadDifferenceAccount";
        downloadDifferenceAccount = new TextBox();
        downloadDifferenceAccount.Name = "downloadDifferenceAccount";
        lblDownloadAmount = new Label();
        lblDownloadAmount.Name = "lblDownloadAmount";
        downloadAmount = new TextBox();
        downloadAmount.Name = "downloadAmount";
        lblTotalAfterTax = new Label();
        lblTotalAfterTax.Name = "lblTotalAfterTax";
        txtTotalAfterTax = new TextBox();
        txtTotalAfterTax.Name = "txtTotalAfterTax";
        lblTotalGrand = new Label();
        lblTotalGrand.Name = "lblTotalGrand";
        txtTotalGrand = new TextBox();
        txtTotalGrand.Name = "txtTotalGrand";
        lblTotalQuantity = new Label();
        lblTotalQuantity.Name = "lblTotalQuantity";
        txtTotalQuantity = new TextBox();
        txtTotalQuantity.Name = "txtTotalQuantity";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = Padding.Empty;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.BackColor = Color.FromArgb(23, 50, 78);
        lblTitle.ForeColor = Color.White;
        commandBar.Dock = DockStyle.Fill;
        commandBar.Margin = Padding.Empty;
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeftLayout = true;
        tabMain.Text = "البيانات الرئيسية";
        tabMain.Padding = Padding.Empty;
        tabs.Controls.Add(tabMain);
        documentLayout.Dock = DockStyle.Fill;
        documentLayout.ColumnCount = 1;
        documentLayout.RowCount = 3;
        documentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 282F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainTabLayout.Dock = DockStyle.Fill;
        mainTabLayout.Margin = Padding.Empty;
        mainTabLayout.ColumnCount = 1;
        mainTabLayout.RowCount = 2;
        mainTabLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainTabLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainTabLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        tabMain.Controls.Add(mainTabLayout);
        headerLayout.Dock = DockStyle.Fill;
        headerLayout.Padding = new Padding(10, 6, 10, 6);
        headerLayout.Margin = Padding.Empty;
        headerLayout.ColumnCount = 6;
        headerLayout.RowCount = 7;
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 126F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 126F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 126F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        lblBranch.Text = "الفرع";
        lblBranch.Dock = DockStyle.Fill;
        lblBranch.TextAlign = ContentAlignment.MiddleLeft;
        fieldBranch.AccessibleName = "الفرع";
        fieldBranch.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblBranch, 0, 0);
        headerLayout.Controls.Add(fieldBranch, 1, 0);
        fieldBranch.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldBranch.Enabled = false;
        lblReceiptType.Text = "نوع التوريد";
        lblReceiptType.Dock = DockStyle.Fill;
        lblReceiptType.TextAlign = ContentAlignment.MiddleLeft;
        fieldReceiptType.AccessibleName = "نوع التوريد";
        fieldReceiptType.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblReceiptType, 2, 0);
        headerLayout.Controls.Add(fieldReceiptType, 3, 0);
        fieldReceiptType.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldReceiptType.Enabled = false;
        lblReceiptNumber.Text = "رقم التوريد";
        lblReceiptNumber.Dock = DockStyle.Fill;
        lblReceiptNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldReceiptNumber.AccessibleName = "رقم التوريد";
        fieldReceiptNumber.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblReceiptNumber, 4, 0);
        headerLayout.Controls.Add(fieldReceiptNumber, 5, 0);
        fieldReceiptNumber.ReadOnly = true;
        lblDate.Text = "تاريخ التوريد";
        lblDate.Dock = DockStyle.Fill;
        lblDate.TextAlign = ContentAlignment.MiddleLeft;
        fieldDate.AccessibleName = "تاريخ التوريد";
        fieldDate.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDate, 0, 1);
        headerLayout.Controls.Add(fieldDate, 1, 1);
        fieldDate.ReadOnly = true;
        lblWarehouse.Text = "المخزن";
        lblWarehouse.Dock = DockStyle.Fill;
        lblWarehouse.TextAlign = ContentAlignment.MiddleLeft;
        fieldWarehouse.AccessibleName = "المخزن";
        fieldWarehouse.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblWarehouse, 2, 1);
        headerLayout.Controls.Add(fieldWarehouse, 3, 1);
        fieldWarehouse.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldWarehouse.Enabled = false;
        lblAccountNumber.Text = "رقم الحساب";
        lblAccountNumber.Dock = DockStyle.Fill;
        lblAccountNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldAccountNumber.AccessibleName = "رقم الحساب";
        fieldAccountNumber.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblAccountNumber, 4, 1);
        headerLayout.Controls.Add(fieldAccountNumber, 5, 1);
        fieldAccountNumber.ReadOnly = true;
        lblAccountName.Text = "اسم الحساب";
        lblAccountName.Dock = DockStyle.Fill;
        lblAccountName.TextAlign = ContentAlignment.MiddleLeft;
        fieldAccountName.AccessibleName = "اسم الحساب";
        fieldAccountName.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblAccountName, 0, 2);
        headerLayout.Controls.Add(fieldAccountName, 1, 2);
        fieldAccountName.ReadOnly = true;
        lblAnalyticalAccount.Text = "الحساب التحليلي";
        lblAnalyticalAccount.Dock = DockStyle.Fill;
        lblAnalyticalAccount.TextAlign = ContentAlignment.MiddleLeft;
        fieldAnalyticalAccount.AccessibleName = "الحساب التحليلي";
        fieldAnalyticalAccount.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblAnalyticalAccount, 2, 2);
        headerLayout.Controls.Add(fieldAnalyticalAccount, 3, 2);
        fieldAnalyticalAccount.ReadOnly = true;
        lblAnalyticalName.Text = "اسم الحساب التحليلي";
        lblAnalyticalName.Dock = DockStyle.Fill;
        lblAnalyticalName.TextAlign = ContentAlignment.MiddleLeft;
        fieldAnalyticalName.AccessibleName = "اسم الحساب التحليلي";
        fieldAnalyticalName.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblAnalyticalName, 4, 2);
        headerLayout.Controls.Add(fieldAnalyticalName, 5, 2);
        fieldAnalyticalName.ReadOnly = true;
        lblCurrency.Text = "العملة";
        lblCurrency.Dock = DockStyle.Fill;
        lblCurrency.TextAlign = ContentAlignment.MiddleLeft;
        fieldCurrency.AccessibleName = "العملة";
        fieldCurrency.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblCurrency, 0, 3);
        headerLayout.Controls.Add(fieldCurrency, 1, 3);
        fieldCurrency.ReadOnly = true;
        lblAccountRate.Text = "س.ت الحساب";
        lblAccountRate.Dock = DockStyle.Fill;
        lblAccountRate.TextAlign = ContentAlignment.MiddleLeft;
        fieldAccountRate.AccessibleName = "س.ت الحساب";
        fieldAccountRate.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblAccountRate, 2, 3);
        headerLayout.Controls.Add(fieldAccountRate, 3, 3);
        fieldAccountRate.ReadOnly = true;
        lblReference.Text = "رقم المرجع";
        lblReference.Dock = DockStyle.Fill;
        lblReference.TextAlign = ContentAlignment.MiddleLeft;
        fieldReference.AccessibleName = "رقم المرجع";
        fieldReference.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblReference, 4, 3);
        headerLayout.Controls.Add(fieldReference, 5, 3);
        fieldReference.ReadOnly = true;
        lblDescription.Text = "البيان";
        lblDescription.Dock = DockStyle.Fill;
        lblDescription.TextAlign = ContentAlignment.MiddleLeft;
        fieldDescription.AccessibleName = "البيان";
        fieldDescription.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDescription, 0, 4);
        headerLayout.Controls.Add(fieldDescription, 1, 4);
        fieldDescription.ReadOnly = true;
        lblAttachmentCount.Text = "عدد المرفقات";
        lblAttachmentCount.Dock = DockStyle.Fill;
        lblAttachmentCount.TextAlign = ContentAlignment.MiddleLeft;
        fieldAttachmentCount.AccessibleName = "عدد المرفقات";
        fieldAttachmentCount.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblAttachmentCount, 2, 4);
        headerLayout.Controls.Add(fieldAttachmentCount, 3, 4);
        fieldAttachmentCount.ReadOnly = true;
        lblDueDate.Text = "تاريخ الاستحقاق";
        lblDueDate.Dock = DockStyle.Fill;
        lblDueDate.TextAlign = ContentAlignment.MiddleLeft;
        fieldDueDate.AccessibleName = "تاريخ الاستحقاق";
        fieldDueDate.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDueDate, 4, 4);
        headerLayout.Controls.Add(fieldDueDate, 5, 4);
        fieldDueDate.ReadOnly = true;
        lblCostMethod.Text = "تكاليف الأصناف";
        lblCostMethod.Dock = DockStyle.Fill;
        lblCostMethod.TextAlign = ContentAlignment.MiddleLeft;
        fieldCostMethod.AccessibleName = "تكاليف الأصناف";
        fieldCostMethod.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblCostMethod, 0, 5);
        headerLayout.Controls.Add(fieldCostMethod, 1, 5);
        fieldCostMethod.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldCostMethod.Enabled = false;
        lblVehicleNumber.Text = "رقم السيارة";
        lblVehicleNumber.Dock = DockStyle.Fill;
        lblVehicleNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldVehicleNumber.AccessibleName = "رقم السيارة";
        fieldVehicleNumber.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblVehicleNumber, 2, 5);
        headerLayout.Controls.Add(fieldVehicleNumber, 3, 5);
        fieldVehicleNumber.ReadOnly = true;
        lblDriverName.Text = "اسم السائق";
        lblDriverName.Dock = DockStyle.Fill;
        lblDriverName.TextAlign = ContentAlignment.MiddleLeft;
        fieldDriverName.AccessibleName = "اسم السائق";
        fieldDriverName.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDriverName, 4, 5);
        headerLayout.Controls.Add(fieldDriverName, 5, 5);
        fieldDriverName.ReadOnly = true;
        lblCostCenter.Text = "مركز التكلفة";
        lblCostCenter.Dock = DockStyle.Fill;
        lblCostCenter.TextAlign = ContentAlignment.MiddleLeft;
        fieldCostCenter.AccessibleName = "مركز التكلفة";
        fieldCostCenter.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblCostCenter, 0, 6);
        headerLayout.Controls.Add(fieldCostCenter, 1, 6);
        fieldCostCenter.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldCostCenter.Enabled = false;
        actionsLayout.Dock = DockStyle.Fill;
        actionsLayout.FlowDirection = FlowDirection.RightToLeft;
        actionsLayout.WrapContents = false;
        actionsLayout.Margin = Padding.Empty;
        chkPosted.Text = "مرحل";
        chkPosted.AutoSize = true;
        chkPosted.Enabled = false;
        chkSuspended.Text = "تعليق";
        chkSuspended.AutoSize = true;
        chkSuspended.Enabled = false;
        btnJournalView.Text = "اليومية العامة";
        btnJournalView.AccessibleName = "اليومية العامة";
        btnJournalView.AutoSize = true;
        btnJournalView.Click += JournalView_Click;
        actionsLayout.Controls.Add(chkPosted);
        actionsLayout.Controls.Add(chkSuspended);
        actionsLayout.Controls.Add(btnJournalView);
        fieldReceiptType.Items.Add("أمر توريد مخزني");
        fieldCostMethod.Items.AddRange(new object[] { "آخر سعر توريد", "سعر المورد", "متوسط التكلفة" });
        gridItems.Dock = DockStyle.Fill;
        gridItems.AccessibleName = "أصناف أمر التوريد المخزني";
        gridItems.ReadOnly = true;
        gridItems.AllowUserToAddRows = false;
        gridItems.AllowUserToDeleteRows = false;
        gridItems.AutoGenerateColumns = false;
        gridItems.RowHeadersVisible = false;
        gridItems.BackgroundColor = Color.White;
        gridItems.ColumnHeadersHeight = 34;
        gridItems.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridItems.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        colLookup.HeaderText = "";
        colLookup.Width = 35;
        colLookup.ReadOnly = true;
        colLookup.SortMode = DataGridViewColumnSortMode.NotSortable;
        colLookup.Text = "…";
        colLookup.UseColumnTextForButtonValue = true;
        colSequence.HeaderText = "م";
        colSequence.Width = 45;
        colSequence.ReadOnly = true;
        colSequence.SortMode = DataGridViewColumnSortMode.NotSortable;
        colItemNumber.HeaderText = "رقم الصنف";
        colItemNumber.Width = 140;
        colItemNumber.ReadOnly = true;
        colItemNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colItemName.HeaderText = "اسم الصنف";
        colItemName.Width = 250;
        colItemName.ReadOnly = true;
        colItemName.SortMode = DataGridViewColumnSortMode.NotSortable;
        colUnit.HeaderText = "الوحدة";
        colUnit.Width = 80;
        colUnit.ReadOnly = true;
        colUnit.SortMode = DataGridViewColumnSortMode.NotSortable;
        colExpiryDate.HeaderText = "تاريخ الانتهاء";
        colExpiryDate.Width = 125;
        colExpiryDate.ReadOnly = true;
        colExpiryDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        colQuantity.HeaderText = "الكمية";
        colQuantity.Width = 100;
        colQuantity.ReadOnly = true;
        colQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        colCost.HeaderText = "التكلفة";
        colCost.Width = 110;
        colCost.ReadOnly = true;
        colCost.SortMode = DataGridViewColumnSortMode.NotSortable;
        colTotal.HeaderText = "المجموع";
        colTotal.Width = 110;
        colTotal.ReadOnly = true;
        colTotal.SortMode = DataGridViewColumnSortMode.NotSortable;
        colExtra1.HeaderText = "حقل إضافي 1";
        colExtra1.Width = 140;
        colExtra1.ReadOnly = true;
        colExtra1.SortMode = DataGridViewColumnSortMode.NotSortable;
        colExtra2.HeaderText = "حقل إضافي 2";
        colExtra2.Width = 140;
        colExtra2.ReadOnly = true;
        colExtra2.SortMode = DataGridViewColumnSortMode.NotSortable;
        colExtra3.HeaderText = "حقل إضافي 3";
        colExtra3.Width = 140;
        colExtra3.ReadOnly = true;
        colExtra3.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.AddRange(new DataGridViewColumn[] { colLookup, colSequence, colItemNumber, colItemName, colUnit, colExpiryDate, colQuantity, colCost, colTotal, colExtra1, colExtra2, colExtra3 });
        mainTabLayout.Controls.Add(headerLayout, 0, 0);
        documentLayout.Controls.Add(tabs, 0, 0);
        mainTabLayout.Controls.Add(actionsLayout, 0, 1);
        documentLayout.Controls.Add(gridItems, 0, 1);
        documentLayout.Controls.Add(totalsLayout, 0, 2);
        auditFooter.Dock = DockStyle.Fill;
        auditFooter.Margin = Padding.Empty;
        standardAuditMetadata.Dock = DockStyle.Fill;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.Profile = AuditMetadataProfile.Standard;
        auditFooter.Controls.Add(standardAuditMetadata);
        mainLayout.Controls.Add(lblTitle, 0, 0);
        mainLayout.Controls.Add(commandBar, 0, 1);
        mainLayout.Controls.Add(documentLayout, 0, 2);
        mainLayout.Controls.Add(auditFooter, 0, 3);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 9F);
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1180, 720);
        MinimumSize = new Size(1000, 600);
        Controls.Add(mainLayout);
        lblTitle.Text = "أمر التوريد المخزني";
        Name = "UcInventoryReceiptOrder";
        Text = "أمر التوريد المخزني";
        Tag = "INV:RECEIPT-ORDER";
        tabDownload.Text = "إنزال البيانات";
        tabDownload.Padding = Padding.Empty;
        tabs.Controls.Add(tabDownload);
        downloadHeader.Dock = DockStyle.Top;
        downloadHeader.Height = 92;
        downloadHeader.Padding = new Padding(10, 6, 10, 6);
        downloadHeader.ColumnCount = 6;
        downloadHeader.RowCount = 2;
        downloadHeader.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        downloadHeader.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        downloadHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 126F));
        downloadHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        downloadHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 126F));
        downloadHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        downloadHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 126F));
        downloadHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        lblDownloadSource.Text = "إنزال البيانات من";
        lblDownloadSource.Dock = DockStyle.Fill;
        lblDownloadSource.TextAlign = ContentAlignment.MiddleLeft;
        downloadSource.AccessibleName = "إنزال البيانات من";
        downloadSource.Dock = DockStyle.Fill;
        downloadHeader.Controls.Add(lblDownloadSource, 0, 0);
        downloadHeader.Controls.Add(downloadSource, 1, 0);
        downloadSource.DropDownStyle = ComboBoxStyle.DropDownList;
        downloadSource.Enabled = false;
        lblDownloadAuthorizationNumber.Text = "رقم الإذن";
        lblDownloadAuthorizationNumber.Dock = DockStyle.Fill;
        lblDownloadAuthorizationNumber.TextAlign = ContentAlignment.MiddleLeft;
        downloadAuthorizationNumber.AccessibleName = "رقم الإذن";
        downloadAuthorizationNumber.Dock = DockStyle.Fill;
        downloadHeader.Controls.Add(lblDownloadAuthorizationNumber, 2, 0);
        downloadHeader.Controls.Add(downloadAuthorizationNumber, 3, 0);
        downloadAuthorizationNumber.ReadOnly = true;
        lblDownloadDifferenceAccount.Text = "حساب الفارق";
        lblDownloadDifferenceAccount.Dock = DockStyle.Fill;
        lblDownloadDifferenceAccount.TextAlign = ContentAlignment.MiddleLeft;
        downloadDifferenceAccount.AccessibleName = "حساب الفارق";
        downloadDifferenceAccount.Dock = DockStyle.Fill;
        downloadHeader.Controls.Add(lblDownloadDifferenceAccount, 4, 0);
        downloadHeader.Controls.Add(downloadDifferenceAccount, 5, 0);
        downloadDifferenceAccount.ReadOnly = true;
        lblDownloadAmount.Text = "المبلغ";
        lblDownloadAmount.Dock = DockStyle.Fill;
        lblDownloadAmount.TextAlign = ContentAlignment.MiddleLeft;
        downloadAmount.AccessibleName = "المبلغ";
        downloadAmount.Dock = DockStyle.Fill;
        downloadHeader.Controls.Add(lblDownloadAmount, 0, 1);
        downloadHeader.Controls.Add(downloadAmount, 1, 1);
        downloadAmount.ReadOnly = true;
        downloadSource.Items.Add("إذن توريد مخزني");
        tabDownload.Controls.Add(downloadHeader);
        totalsLayout.Dock = DockStyle.Fill;
        totalsLayout.ColumnCount = 6;
        totalsLayout.RowCount = 1;
        totalsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        lblTotalAfterTax.Text = "الإجمالي بعد الضريبة";
        lblTotalAfterTax.Dock = DockStyle.Fill;
        lblTotalAfterTax.TextAlign = ContentAlignment.MiddleLeft;
        txtTotalAfterTax.AccessibleName = "الإجمالي بعد الضريبة";
        txtTotalAfterTax.Dock = DockStyle.Fill;
        txtTotalAfterTax.ReadOnly = true;
        totalsLayout.Controls.Add(lblTotalAfterTax, 0, 0);
        totalsLayout.Controls.Add(txtTotalAfterTax, 1, 0);
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        lblTotalGrand.Text = "الإجمالي الكلي";
        lblTotalGrand.Dock = DockStyle.Fill;
        lblTotalGrand.TextAlign = ContentAlignment.MiddleLeft;
        txtTotalGrand.AccessibleName = "الإجمالي الكلي";
        txtTotalGrand.Dock = DockStyle.Fill;
        txtTotalGrand.ReadOnly = true;
        totalsLayout.Controls.Add(lblTotalGrand, 2, 0);
        totalsLayout.Controls.Add(txtTotalGrand, 3, 0);
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
        totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        lblTotalQuantity.Text = "إجمالي الكميات";
        lblTotalQuantity.Dock = DockStyle.Fill;
        lblTotalQuantity.TextAlign = ContentAlignment.MiddleLeft;
        txtTotalQuantity.AccessibleName = "إجمالي الكميات";
        txtTotalQuantity.Dock = DockStyle.Fill;
        txtTotalQuantity.ReadOnly = true;
        totalsLayout.Controls.Add(lblTotalQuantity, 4, 0);
        totalsLayout.Controls.Add(txtTotalQuantity, 5, 0);
        ResumeLayout(false);
    }
}
