using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcInventoryTransferLookup
{
    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private TableLayoutPanel bodyLayout = null!;
    private TableLayoutPanel searchLayout = null!;
    private Label lblFind = null!;
    private TextBox fieldFind = null!;
    private DataGridView gridLookup = null!;
    private TableLayoutPanel actionsLayout = null!;
    private Button btnFind = null!;
    private Button btnOK = null!;
    private Button btnCancel = null!;
    private Panel auditFooter = null!;
    private AuditMetadataControl standardAuditMetadata = null!;
    private DataGridViewTextBoxColumn colTransferNumber = null!;
    private DataGridViewTextBoxColumn colTransferType = null!;
    private DataGridViewTextBoxColumn colTransferDate = null!;
    private DataGridViewTextBoxColumn colWarehouseNumber = null!;
    private DataGridViewTextBoxColumn colWarehouseName = null!;
    private DataGridViewTextBoxColumn colDescription = null!;
    private DataGridViewTextBoxColumn colBranchNumber = null!;
    private DataGridViewTextBoxColumn colReference = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        bodyLayout = new TableLayoutPanel();
        bodyLayout.Name = "bodyLayout";
        searchLayout = new TableLayoutPanel();
        searchLayout.Name = "searchLayout";
        lblFind = new Label();
        lblFind.Name = "lblFind";
        fieldFind = new TextBox();
        fieldFind.Name = "fieldFind";
        gridLookup = new DataGridView();
        gridLookup.Name = "gridLookup";
        actionsLayout = new TableLayoutPanel();
        actionsLayout.Name = "actionsLayout";
        btnFind = new Button();
        btnFind.Name = "btnFind";
        btnOK = new Button();
        btnOK.Name = "btnOK";
        btnCancel = new Button();
        btnCancel.Name = "btnCancel";
        auditFooter = new Panel();
        auditFooter.Name = "auditFooter";
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        colTransferNumber = new DataGridViewTextBoxColumn();
        colTransferNumber.Name = "colTransferNumber";
        colTransferType = new DataGridViewTextBoxColumn();
        colTransferType.Name = "colTransferType";
        colTransferDate = new DataGridViewTextBoxColumn();
        colTransferDate.Name = "colTransferDate";
        colWarehouseNumber = new DataGridViewTextBoxColumn();
        colWarehouseNumber.Name = "colWarehouseNumber";
        colWarehouseName = new DataGridViewTextBoxColumn();
        colWarehouseName.Name = "colWarehouseName";
        colDescription = new DataGridViewTextBoxColumn();
        colDescription.Name = "colDescription";
        colBranchNumber = new DataGridViewTextBoxColumn();
        colBranchNumber.Name = "colBranchNumber";
        colReference = new DataGridViewTextBoxColumn();
        colReference.Name = "colReference";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = Padding.Empty;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.BackColor = Color.FromArgb(23, 50, 78);
        lblTitle.ForeColor = Color.White;
        commandBar.Dock = DockStyle.Fill;
        commandBar.Margin = Padding.Empty;
        bodyLayout.Dock = DockStyle.Fill;
        bodyLayout.ColumnCount = 1;
        bodyLayout.RowCount = 3;
        bodyLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
        searchLayout.Dock = DockStyle.Fill;
        searchLayout.ColumnCount = 4;
        searchLayout.RowCount = 1;
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 70F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 180F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchLayout.Padding = new Padding(6);
        lblFind.Text = "Find";
        lblFind.Dock = DockStyle.Fill;
        lblFind.TextAlign = ContentAlignment.MiddleCenter;
        fieldFind.Dock = DockStyle.Fill;
        fieldFind.AccessibleName = "Find";
        fieldFind.ReadOnly = true;
        searchLayout.Controls.Add(lblFind, 1, 0);
        searchLayout.Controls.Add(fieldFind, 2, 0);
        gridLookup.Dock = DockStyle.Fill;
        gridLookup.ReadOnly = true;
        gridLookup.AllowUserToAddRows = false;
        gridLookup.AllowUserToDeleteRows = false;
        gridLookup.AutoGenerateColumns = false;
        gridLookup.RowHeadersVisible = false;
        gridLookup.BackgroundColor = Color.White;
        gridLookup.ColumnHeadersHeight = 34;
        gridLookup.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridLookup.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        colTransferNumber.HeaderText = "رقم التحويل";
        colTransferNumber.Width = 130;
        colTransferNumber.ReadOnly = true;
        colTransferNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colTransferType.HeaderText = "نوع التحويل";
        colTransferType.Width = 120;
        colTransferType.ReadOnly = true;
        colTransferType.SortMode = DataGridViewColumnSortMode.NotSortable;
        colTransferDate.HeaderText = "تاريخ التحويل";
        colTransferDate.Width = 140;
        colTransferDate.ReadOnly = true;
        colTransferDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        colWarehouseNumber.HeaderText = "رقم المخزن";
        colWarehouseNumber.Width = 110;
        colWarehouseNumber.ReadOnly = true;
        colWarehouseNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colWarehouseName.HeaderText = "اسم المخزن";
        colWarehouseName.Width = 200;
        colWarehouseName.ReadOnly = true;
        colWarehouseName.SortMode = DataGridViewColumnSortMode.NotSortable;
        colDescription.HeaderText = "البيان";
        colDescription.Width = 220;
        colDescription.ReadOnly = true;
        colDescription.SortMode = DataGridViewColumnSortMode.NotSortable;
        colBranchNumber.HeaderText = "رقم الفرع";
        colBranchNumber.Width = 100;
        colBranchNumber.ReadOnly = true;
        colBranchNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colReference.HeaderText = "رقم المرجع";
        colReference.Width = 130;
        colReference.ReadOnly = true;
        colReference.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridLookup.Columns.AddRange(new DataGridViewColumn[] { colTransferNumber, colTransferType, colTransferDate, colWarehouseNumber, colWarehouseName, colDescription, colBranchNumber, colReference });
        actionsLayout.Dock = DockStyle.Fill;
        actionsLayout.ColumnCount = 3;
        actionsLayout.RowCount = 1;
        actionsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        actionsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        actionsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        btnFind.Text = "Find";
        btnFind.Enabled = false;
        btnFind.Anchor = AnchorStyles.Right;
        btnOK.Text = "OK";
        btnOK.Enabled = false;
        btnOK.Anchor = AnchorStyles.None;
        btnCancel.Text = "Cancel";
        btnCancel.Anchor = AnchorStyles.Left;
        actionsLayout.Controls.Add(btnFind, 0, 0);
        actionsLayout.Controls.Add(btnOK, 1, 0);
        actionsLayout.Controls.Add(btnCancel, 2, 0);
        bodyLayout.Controls.Add(searchLayout, 0, 0);
        bodyLayout.Controls.Add(gridLookup, 0, 1);
        bodyLayout.Controls.Add(actionsLayout, 0, 2);
        auditFooter.Dock = DockStyle.Fill;
        auditFooter.Margin = Padding.Empty;
        standardAuditMetadata.Dock = DockStyle.Fill;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.Profile = AuditMetadataProfile.Standard;
        auditFooter.Controls.Add(standardAuditMetadata);
        mainLayout.Controls.Add(lblTitle, 0, 0);
        mainLayout.Controls.Add(commandBar, 0, 1);
        mainLayout.Controls.Add(bodyLayout, 0, 2);
        mainLayout.Controls.Add(auditFooter, 0, 3);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 9F);
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1180, 720);
        MinimumSize = new Size(1000, 600);
        Controls.Add(mainLayout);
        actionsLayout.Visible = true;
        lblTitle.Text = "التحويلات المخزنية / Warehouse Transfer";
        Name = "UcInventoryTransferLookup";
        Text = "التحويلات المخزنية / Warehouse Transfer";
        gridLookup.AccessibleName = "التحويلات المخزنية / Warehouse Transfer";
        ResumeLayout(false);
    }
}
