using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcInventoryStocktakeReport
{
    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private Panel reportScroll = null!;
    private TableLayoutPanel bodyLayout = null!;
    private TableLayoutPanel printLayout = null!;
    private TableLayoutPanel filterLayout = null!;
    private Panel auditFooter = null!;
    private AuditMetadataControl standardAuditMetadata = null!;
    private Label lblStatus = null!;
    private CheckBox chkAnnual = null!;
    private CheckBox chkUncountedItems = null!;
    private CheckBox chkHideMatching = null!;
    private TabControl reportTabs = null!;
    private TabPage tabReportType = null!;
    private TableLayoutPanel detailLayout = null!;
    private Label lblHeaderVisibility = null!;
    private ComboBox fieldHeaderVisibility = null!;
    private Label lblPrintDestination = null!;
    private ComboBox fieldPrintDestination = null!;
    private Label lblCopies = null!;
    private NumericUpDown fieldCopies = null!;
    private Label lblLanguage = null!;
    private ComboBox fieldLanguage = null!;
    private Label lblPrintTemplate = null!;
    private ComboBox fieldPrintTemplate = null!;
    private Label lblReportTitle = null!;
    private TextBox fieldReportTitle = null!;
    private Label lblReportSubtitle = null!;
    private TextBox fieldReportSubtitle = null!;
    private Label lblBranchFrom = null!;
    private ComboBox fieldBranchFrom = null!;
    private Label lblBranchTo = null!;
    private ComboBox fieldBranchTo = null!;
    private Label lblUser = null!;
    private ComboBox fieldUser = null!;
    private Label lblType = null!;
    private ComboBox fieldType = null!;
    private Label lblNumberFrom = null!;
    private TextBox fieldNumberFrom = null!;
    private Label lblNumberTo = null!;
    private TextBox fieldNumberTo = null!;
    private Label lblStocktakeTypeFrom = null!;
    private ComboBox fieldStocktakeTypeFrom = null!;
    private Label lblStocktakeTypeTo = null!;
    private ComboBox fieldStocktakeTypeTo = null!;
    private Label lblGroupFrom = null!;
    private TextBox fieldGroupFrom = null!;
    private Label lblGroupTo = null!;
    private TextBox fieldGroupTo = null!;
    private Label lblSubGroupFrom = null!;
    private TextBox fieldSubGroupFrom = null!;
    private Label lblSubGroupTo = null!;
    private TextBox fieldSubGroupTo = null!;
    private Label lblSubSubGroupFrom = null!;
    private TextBox fieldSubSubGroupFrom = null!;
    private Label lblSubSubGroupTo = null!;
    private TextBox fieldSubSubGroupTo = null!;
    private Label lblAuxiliaryGroupFrom = null!;
    private TextBox fieldAuxiliaryGroupFrom = null!;
    private Label lblAuxiliaryGroupTo = null!;
    private TextBox fieldAuxiliaryGroupTo = null!;
    private Label lblItemFrom = null!;
    private TextBox fieldItemFrom = null!;
    private Label lblItemTo = null!;
    private TextBox fieldItemTo = null!;
    private Label lblWarehouseFrom = null!;
    private TextBox fieldWarehouseFrom = null!;
    private Label lblWarehouseTo = null!;
    private TextBox fieldWarehouseTo = null!;
    private Label lblComparisonType = null!;
    private ComboBox fieldComparisonType = null!;
    private Label lblReportType = null!;
    private ComboBox fieldReportType = null!;
    private Label lblQuantityOperator = null!;
    private ComboBox fieldQuantityOperator = null!;
    private Label lblReportName = null!;
    private ComboBox fieldReportName = null!;
    private Label lblCountQuantity = null!;
    private TextBox fieldCountQuantity = null!;
    private Label lblValuation = null!;
    private ComboBox fieldValuation = null!;
    private Label lblDisplayMethod = null!;
    private ComboBox fieldDisplayMethod = null!;
    private Label lblPriceNumber = null!;
    private TextBox fieldPriceNumber = null!;
    private Label lblPriceName = null!;
    private TextBox fieldPriceName = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        reportScroll = new Panel();
        reportScroll.Name = "reportScroll";
        bodyLayout = new TableLayoutPanel();
        bodyLayout.Name = "bodyLayout";
        printLayout = new TableLayoutPanel();
        printLayout.Name = "printLayout";
        filterLayout = new TableLayoutPanel();
        filterLayout.Name = "filterLayout";
        auditFooter = new Panel();
        auditFooter.Name = "auditFooter";
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        lblStatus = new Label();
        lblStatus.Name = "lblStatus";
        chkAnnual = new CheckBox();
        chkAnnual.Name = "chkAnnual";
        chkUncountedItems = new CheckBox();
        chkUncountedItems.Name = "chkUncountedItems";
        chkHideMatching = new CheckBox();
        chkHideMatching.Name = "chkHideMatching";
        reportTabs = new TabControl();
        reportTabs.Name = "reportTabs";
        tabReportType = new TabPage();
        tabReportType.Name = "tabReportType";
        detailLayout = new TableLayoutPanel();
        detailLayout.Name = "detailLayout";
        lblHeaderVisibility = new Label();
        lblHeaderVisibility.Name = "lblHeaderVisibility";
        fieldHeaderVisibility = new ComboBox();
        fieldHeaderVisibility.Name = "fieldHeaderVisibility";
        lblPrintDestination = new Label();
        lblPrintDestination.Name = "lblPrintDestination";
        fieldPrintDestination = new ComboBox();
        fieldPrintDestination.Name = "fieldPrintDestination";
        lblCopies = new Label();
        lblCopies.Name = "lblCopies";
        fieldCopies = new NumericUpDown();
        fieldCopies.Name = "fieldCopies";
        lblLanguage = new Label();
        lblLanguage.Name = "lblLanguage";
        fieldLanguage = new ComboBox();
        fieldLanguage.Name = "fieldLanguage";
        lblPrintTemplate = new Label();
        lblPrintTemplate.Name = "lblPrintTemplate";
        fieldPrintTemplate = new ComboBox();
        fieldPrintTemplate.Name = "fieldPrintTemplate";
        lblReportTitle = new Label();
        lblReportTitle.Name = "lblReportTitle";
        fieldReportTitle = new TextBox();
        fieldReportTitle.Name = "fieldReportTitle";
        lblReportSubtitle = new Label();
        lblReportSubtitle.Name = "lblReportSubtitle";
        fieldReportSubtitle = new TextBox();
        fieldReportSubtitle.Name = "fieldReportSubtitle";
        lblBranchFrom = new Label();
        lblBranchFrom.Name = "lblBranchFrom";
        fieldBranchFrom = new ComboBox();
        fieldBranchFrom.Name = "fieldBranchFrom";
        lblBranchTo = new Label();
        lblBranchTo.Name = "lblBranchTo";
        fieldBranchTo = new ComboBox();
        fieldBranchTo.Name = "fieldBranchTo";
        lblUser = new Label();
        lblUser.Name = "lblUser";
        fieldUser = new ComboBox();
        fieldUser.Name = "fieldUser";
        lblType = new Label();
        lblType.Name = "lblType";
        fieldType = new ComboBox();
        fieldType.Name = "fieldType";
        lblNumberFrom = new Label();
        lblNumberFrom.Name = "lblNumberFrom";
        fieldNumberFrom = new TextBox();
        fieldNumberFrom.Name = "fieldNumberFrom";
        lblNumberTo = new Label();
        lblNumberTo.Name = "lblNumberTo";
        fieldNumberTo = new TextBox();
        fieldNumberTo.Name = "fieldNumberTo";
        lblStocktakeTypeFrom = new Label();
        lblStocktakeTypeFrom.Name = "lblStocktakeTypeFrom";
        fieldStocktakeTypeFrom = new ComboBox();
        fieldStocktakeTypeFrom.Name = "fieldStocktakeTypeFrom";
        lblStocktakeTypeTo = new Label();
        lblStocktakeTypeTo.Name = "lblStocktakeTypeTo";
        fieldStocktakeTypeTo = new ComboBox();
        fieldStocktakeTypeTo.Name = "fieldStocktakeTypeTo";
        lblGroupFrom = new Label();
        lblGroupFrom.Name = "lblGroupFrom";
        fieldGroupFrom = new TextBox();
        fieldGroupFrom.Name = "fieldGroupFrom";
        lblGroupTo = new Label();
        lblGroupTo.Name = "lblGroupTo";
        fieldGroupTo = new TextBox();
        fieldGroupTo.Name = "fieldGroupTo";
        lblSubGroupFrom = new Label();
        lblSubGroupFrom.Name = "lblSubGroupFrom";
        fieldSubGroupFrom = new TextBox();
        fieldSubGroupFrom.Name = "fieldSubGroupFrom";
        lblSubGroupTo = new Label();
        lblSubGroupTo.Name = "lblSubGroupTo";
        fieldSubGroupTo = new TextBox();
        fieldSubGroupTo.Name = "fieldSubGroupTo";
        lblSubSubGroupFrom = new Label();
        lblSubSubGroupFrom.Name = "lblSubSubGroupFrom";
        fieldSubSubGroupFrom = new TextBox();
        fieldSubSubGroupFrom.Name = "fieldSubSubGroupFrom";
        lblSubSubGroupTo = new Label();
        lblSubSubGroupTo.Name = "lblSubSubGroupTo";
        fieldSubSubGroupTo = new TextBox();
        fieldSubSubGroupTo.Name = "fieldSubSubGroupTo";
        lblAuxiliaryGroupFrom = new Label();
        lblAuxiliaryGroupFrom.Name = "lblAuxiliaryGroupFrom";
        fieldAuxiliaryGroupFrom = new TextBox();
        fieldAuxiliaryGroupFrom.Name = "fieldAuxiliaryGroupFrom";
        lblAuxiliaryGroupTo = new Label();
        lblAuxiliaryGroupTo.Name = "lblAuxiliaryGroupTo";
        fieldAuxiliaryGroupTo = new TextBox();
        fieldAuxiliaryGroupTo.Name = "fieldAuxiliaryGroupTo";
        lblItemFrom = new Label();
        lblItemFrom.Name = "lblItemFrom";
        fieldItemFrom = new TextBox();
        fieldItemFrom.Name = "fieldItemFrom";
        lblItemTo = new Label();
        lblItemTo.Name = "lblItemTo";
        fieldItemTo = new TextBox();
        fieldItemTo.Name = "fieldItemTo";
        lblWarehouseFrom = new Label();
        lblWarehouseFrom.Name = "lblWarehouseFrom";
        fieldWarehouseFrom = new TextBox();
        fieldWarehouseFrom.Name = "fieldWarehouseFrom";
        lblWarehouseTo = new Label();
        lblWarehouseTo.Name = "lblWarehouseTo";
        fieldWarehouseTo = new TextBox();
        fieldWarehouseTo.Name = "fieldWarehouseTo";
        lblComparisonType = new Label();
        lblComparisonType.Name = "lblComparisonType";
        fieldComparisonType = new ComboBox();
        fieldComparisonType.Name = "fieldComparisonType";
        lblReportType = new Label();
        lblReportType.Name = "lblReportType";
        fieldReportType = new ComboBox();
        fieldReportType.Name = "fieldReportType";
        lblQuantityOperator = new Label();
        lblQuantityOperator.Name = "lblQuantityOperator";
        fieldQuantityOperator = new ComboBox();
        fieldQuantityOperator.Name = "fieldQuantityOperator";
        lblReportName = new Label();
        lblReportName.Name = "lblReportName";
        fieldReportName = new ComboBox();
        fieldReportName.Name = "fieldReportName";
        lblCountQuantity = new Label();
        lblCountQuantity.Name = "lblCountQuantity";
        fieldCountQuantity = new TextBox();
        fieldCountQuantity.Name = "fieldCountQuantity";
        lblValuation = new Label();
        lblValuation.Name = "lblValuation";
        fieldValuation = new ComboBox();
        fieldValuation.Name = "fieldValuation";
        lblDisplayMethod = new Label();
        lblDisplayMethod.Name = "lblDisplayMethod";
        fieldDisplayMethod = new ComboBox();
        fieldDisplayMethod.Name = "fieldDisplayMethod";
        lblPriceNumber = new Label();
        lblPriceNumber.Name = "lblPriceNumber";
        fieldPriceNumber = new TextBox();
        fieldPriceNumber.Name = "fieldPriceNumber";
        lblPriceName = new Label();
        lblPriceName.Name = "lblPriceName";
        fieldPriceName = new TextBox();
        fieldPriceName.Name = "fieldPriceName";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = Padding.Empty;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 5;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.BackColor = Color.FromArgb(23, 50, 78);
        lblTitle.ForeColor = Color.White;
        commandBar.Dock = DockStyle.Fill;
        commandBar.Margin = Padding.Empty;
        reportScroll.Dock = DockStyle.Fill;
        reportScroll.AutoScroll = true;
        reportScroll.Margin = Padding.Empty;
        bodyLayout.Dock = DockStyle.Top;
        bodyLayout.AutoSize = true;
        bodyLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        bodyLayout.ColumnCount = 1;
        bodyLayout.RowCount = 3;
        bodyLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 132F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 552F));
        printLayout.Dock = DockStyle.Fill;
        printLayout.Margin = Padding.Empty;
        printLayout.Padding = new Padding(8, 3, 8, 3);
        printLayout.BackColor = Color.FromArgb(238, 234, 248);
        printLayout.ColumnCount = 10;
        printLayout.RowCount = 1;
        printLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 84F));
        printLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        printLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 84F));
        printLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        printLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 84F));
        printLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        printLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 84F));
        printLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        printLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 84F));
        printLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        printLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        filterLayout.Dock = DockStyle.Fill;
        filterLayout.Padding = new Padding(20, 10, 20, 10);
        filterLayout.Margin = Padding.Empty;
        filterLayout.ColumnCount = 4;
        filterLayout.RowCount = 4;
        filterLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
        filterLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        filterLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 125F));
        filterLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        filterLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        filterLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        filterLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        filterLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        lblHeaderVisibility.Text = "ظهور الترويسة";
        lblHeaderVisibility.Dock = DockStyle.Fill;
        lblHeaderVisibility.TextAlign = ContentAlignment.MiddleLeft;
        fieldHeaderVisibility.AccessibleName = "ظهور الترويسة";
        fieldHeaderVisibility.Dock = DockStyle.Fill;
        fieldHeaderVisibility.Margin = new Padding(3, 2, 3, 2);
        printLayout.Controls.Add(lblHeaderVisibility, 0, 0);
        printLayout.Controls.Add(fieldHeaderVisibility, 1, 0);
        fieldHeaderVisibility.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldHeaderVisibility.Enabled = false;
        lblPrintDestination.Text = "وجهة الطباعة";
        lblPrintDestination.Dock = DockStyle.Fill;
        lblPrintDestination.TextAlign = ContentAlignment.MiddleLeft;
        fieldPrintDestination.AccessibleName = "وجهة الطباعة";
        fieldPrintDestination.Dock = DockStyle.Fill;
        fieldPrintDestination.Margin = new Padding(3, 2, 3, 2);
        printLayout.Controls.Add(lblPrintDestination, 2, 0);
        printLayout.Controls.Add(fieldPrintDestination, 3, 0);
        fieldPrintDestination.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldPrintDestination.Enabled = false;
        lblCopies.Text = "عدد النسخ";
        lblCopies.Dock = DockStyle.Fill;
        lblCopies.TextAlign = ContentAlignment.MiddleLeft;
        fieldCopies.AccessibleName = "عدد النسخ";
        fieldCopies.Dock = DockStyle.Fill;
        fieldCopies.Margin = new Padding(3, 2, 3, 2);
        printLayout.Controls.Add(lblCopies, 4, 0);
        printLayout.Controls.Add(fieldCopies, 5, 0);
        fieldCopies.Minimum = 1;
        fieldCopies.Maximum = 999;
        fieldCopies.Value = 1;
        lblLanguage.Text = "اللغة";
        lblLanguage.Dock = DockStyle.Fill;
        lblLanguage.TextAlign = ContentAlignment.MiddleLeft;
        fieldLanguage.AccessibleName = "اللغة";
        fieldLanguage.Dock = DockStyle.Fill;
        fieldLanguage.Margin = new Padding(3, 2, 3, 2);
        printLayout.Controls.Add(lblLanguage, 6, 0);
        printLayout.Controls.Add(fieldLanguage, 7, 0);
        fieldLanguage.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldLanguage.Enabled = false;
        lblPrintTemplate.Text = "نموذج الطباعة";
        lblPrintTemplate.Dock = DockStyle.Fill;
        lblPrintTemplate.TextAlign = ContentAlignment.MiddleLeft;
        fieldPrintTemplate.AccessibleName = "نموذج الطباعة";
        fieldPrintTemplate.Dock = DockStyle.Fill;
        fieldPrintTemplate.Margin = new Padding(3, 2, 3, 2);
        printLayout.Controls.Add(lblPrintTemplate, 8, 0);
        printLayout.Controls.Add(fieldPrintTemplate, 9, 0);
        fieldPrintTemplate.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldPrintTemplate.Enabled = false;
        lblReportTitle.Text = "عنوان التقرير";
        lblReportTitle.Dock = DockStyle.Fill;
        lblReportTitle.TextAlign = ContentAlignment.MiddleLeft;
        fieldReportTitle.AccessibleName = "عنوان التقرير";
        fieldReportTitle.Dock = DockStyle.Fill;
        fieldReportTitle.Margin = new Padding(3, 2, 3, 2);
        filterLayout.Controls.Add(lblReportTitle, 0, 0);
        filterLayout.Controls.Add(fieldReportTitle, 1, 0);
        filterLayout.SetColumnSpan(fieldReportTitle, 3);
        lblReportSubtitle.Text = "تذييل التقرير";
        lblReportSubtitle.Dock = DockStyle.Fill;
        lblReportSubtitle.TextAlign = ContentAlignment.MiddleLeft;
        fieldReportSubtitle.AccessibleName = "تذييل التقرير";
        fieldReportSubtitle.Dock = DockStyle.Fill;
        fieldReportSubtitle.Margin = new Padding(3, 2, 3, 2);
        filterLayout.Controls.Add(lblReportSubtitle, 0, 1);
        filterLayout.Controls.Add(fieldReportSubtitle, 1, 1);
        filterLayout.SetColumnSpan(fieldReportSubtitle, 3);
        lblBranchFrom.Text = "من الفرع";
        lblBranchFrom.Dock = DockStyle.Fill;
        lblBranchFrom.TextAlign = ContentAlignment.MiddleLeft;
        fieldBranchFrom.AccessibleName = "من الفرع";
        fieldBranchFrom.Dock = DockStyle.Fill;
        fieldBranchFrom.Margin = new Padding(3, 2, 3, 2);
        filterLayout.Controls.Add(lblBranchFrom, 0, 2);
        filterLayout.Controls.Add(fieldBranchFrom, 1, 2);
        fieldBranchFrom.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldBranchFrom.Enabled = false;
        lblBranchTo.Text = "إلى";
        lblBranchTo.Dock = DockStyle.Fill;
        lblBranchTo.TextAlign = ContentAlignment.MiddleLeft;
        fieldBranchTo.AccessibleName = "إلى الفرع";
        fieldBranchTo.Dock = DockStyle.Fill;
        fieldBranchTo.Margin = new Padding(3, 2, 3, 2);
        filterLayout.Controls.Add(lblBranchTo, 2, 2);
        filterLayout.Controls.Add(fieldBranchTo, 3, 2);
        fieldBranchTo.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldBranchTo.Enabled = false;
        lblUser.Text = "رقم المستخدم";
        lblUser.Dock = DockStyle.Fill;
        lblUser.TextAlign = ContentAlignment.MiddleLeft;
        fieldUser.AccessibleName = "رقم المستخدم";
        fieldUser.Dock = DockStyle.Fill;
        fieldUser.Margin = new Padding(3, 2, 3, 2);
        filterLayout.Controls.Add(lblUser, 0, 3);
        filterLayout.Controls.Add(fieldUser, 1, 3);
        filterLayout.SetColumnSpan(fieldUser, 3);
        fieldUser.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldUser.Enabled = false;
        lblType.Text = "النوع";
        lblType.Dock = DockStyle.Fill;
        lblType.TextAlign = ContentAlignment.MiddleLeft;
        fieldType.AccessibleName = "النوع";
        fieldType.Dock = DockStyle.Fill;
        fieldType.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblType, 0, 0);
        detailLayout.Controls.Add(fieldType, 1, 0);
        detailLayout.SetColumnSpan(fieldType, 3);
        fieldType.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldType.Enabled = false;
        lblNumberFrom.Text = "من رقم";
        lblNumberFrom.Dock = DockStyle.Fill;
        lblNumberFrom.TextAlign = ContentAlignment.MiddleLeft;
        fieldNumberFrom.AccessibleName = "من رقم";
        fieldNumberFrom.Dock = DockStyle.Fill;
        fieldNumberFrom.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblNumberFrom, 0, 1);
        detailLayout.Controls.Add(fieldNumberFrom, 1, 1);
        lblNumberTo.Text = "إلى";
        lblNumberTo.Dock = DockStyle.Fill;
        lblNumberTo.TextAlign = ContentAlignment.MiddleLeft;
        fieldNumberTo.AccessibleName = "إلى من رقم";
        fieldNumberTo.Dock = DockStyle.Fill;
        fieldNumberTo.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblNumberTo, 2, 1);
        detailLayout.Controls.Add(fieldNumberTo, 3, 1);
        lblStocktakeTypeFrom.Text = "نوع الجرد";
        lblStocktakeTypeFrom.Dock = DockStyle.Fill;
        lblStocktakeTypeFrom.TextAlign = ContentAlignment.MiddleLeft;
        fieldStocktakeTypeFrom.AccessibleName = "نوع الجرد";
        fieldStocktakeTypeFrom.Dock = DockStyle.Fill;
        fieldStocktakeTypeFrom.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblStocktakeTypeFrom, 0, 2);
        detailLayout.Controls.Add(fieldStocktakeTypeFrom, 1, 2);
        fieldStocktakeTypeFrom.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldStocktakeTypeFrom.Enabled = false;
        lblStocktakeTypeTo.Text = "إلى";
        lblStocktakeTypeTo.Dock = DockStyle.Fill;
        lblStocktakeTypeTo.TextAlign = ContentAlignment.MiddleLeft;
        fieldStocktakeTypeTo.AccessibleName = "إلى نوع الجرد";
        fieldStocktakeTypeTo.Dock = DockStyle.Fill;
        fieldStocktakeTypeTo.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblStocktakeTypeTo, 2, 2);
        detailLayout.Controls.Add(fieldStocktakeTypeTo, 3, 2);
        fieldStocktakeTypeTo.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldStocktakeTypeTo.Enabled = false;
        lblGroupFrom.Text = "من المجموعة رقم";
        lblGroupFrom.Dock = DockStyle.Fill;
        lblGroupFrom.TextAlign = ContentAlignment.MiddleLeft;
        fieldGroupFrom.AccessibleName = "من المجموعة رقم";
        fieldGroupFrom.Dock = DockStyle.Fill;
        fieldGroupFrom.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblGroupFrom, 0, 3);
        detailLayout.Controls.Add(fieldGroupFrom, 1, 3);
        lblGroupTo.Text = "إلى";
        lblGroupTo.Dock = DockStyle.Fill;
        lblGroupTo.TextAlign = ContentAlignment.MiddleLeft;
        fieldGroupTo.AccessibleName = "إلى من المجموعة رقم";
        fieldGroupTo.Dock = DockStyle.Fill;
        fieldGroupTo.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblGroupTo, 2, 3);
        detailLayout.Controls.Add(fieldGroupTo, 3, 3);
        lblSubGroupFrom.Text = "من م. الفرعية";
        lblSubGroupFrom.Dock = DockStyle.Fill;
        lblSubGroupFrom.TextAlign = ContentAlignment.MiddleLeft;
        fieldSubGroupFrom.AccessibleName = "من م. الفرعية";
        fieldSubGroupFrom.Dock = DockStyle.Fill;
        fieldSubGroupFrom.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblSubGroupFrom, 0, 4);
        detailLayout.Controls.Add(fieldSubGroupFrom, 1, 4);
        lblSubGroupTo.Text = "إلى";
        lblSubGroupTo.Dock = DockStyle.Fill;
        lblSubGroupTo.TextAlign = ContentAlignment.MiddleLeft;
        fieldSubGroupTo.AccessibleName = "إلى من م. الفرعية";
        fieldSubGroupTo.Dock = DockStyle.Fill;
        fieldSubGroupTo.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblSubGroupTo, 2, 4);
        detailLayout.Controls.Add(fieldSubGroupTo, 3, 4);
        lblSubSubGroupFrom.Text = "من م. تحت الفرعية";
        lblSubSubGroupFrom.Dock = DockStyle.Fill;
        lblSubSubGroupFrom.TextAlign = ContentAlignment.MiddleLeft;
        fieldSubSubGroupFrom.AccessibleName = "من م. تحت الفرعية";
        fieldSubSubGroupFrom.Dock = DockStyle.Fill;
        fieldSubSubGroupFrom.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblSubSubGroupFrom, 0, 5);
        detailLayout.Controls.Add(fieldSubSubGroupFrom, 1, 5);
        lblSubSubGroupTo.Text = "إلى";
        lblSubSubGroupTo.Dock = DockStyle.Fill;
        lblSubSubGroupTo.TextAlign = ContentAlignment.MiddleLeft;
        fieldSubSubGroupTo.AccessibleName = "إلى من م. تحت الفرعية";
        fieldSubSubGroupTo.Dock = DockStyle.Fill;
        fieldSubSubGroupTo.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblSubSubGroupTo, 2, 5);
        detailLayout.Controls.Add(fieldSubSubGroupTo, 3, 5);
        lblAuxiliaryGroupFrom.Text = "من م. المساعدة";
        lblAuxiliaryGroupFrom.Dock = DockStyle.Fill;
        lblAuxiliaryGroupFrom.TextAlign = ContentAlignment.MiddleLeft;
        fieldAuxiliaryGroupFrom.AccessibleName = "من م. المساعدة";
        fieldAuxiliaryGroupFrom.Dock = DockStyle.Fill;
        fieldAuxiliaryGroupFrom.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblAuxiliaryGroupFrom, 0, 6);
        detailLayout.Controls.Add(fieldAuxiliaryGroupFrom, 1, 6);
        lblAuxiliaryGroupTo.Text = "إلى";
        lblAuxiliaryGroupTo.Dock = DockStyle.Fill;
        lblAuxiliaryGroupTo.TextAlign = ContentAlignment.MiddleLeft;
        fieldAuxiliaryGroupTo.AccessibleName = "إلى من م. المساعدة";
        fieldAuxiliaryGroupTo.Dock = DockStyle.Fill;
        fieldAuxiliaryGroupTo.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblAuxiliaryGroupTo, 2, 6);
        detailLayout.Controls.Add(fieldAuxiliaryGroupTo, 3, 6);
        lblItemFrom.Text = "من الصنف رقم";
        lblItemFrom.Dock = DockStyle.Fill;
        lblItemFrom.TextAlign = ContentAlignment.MiddleLeft;
        fieldItemFrom.AccessibleName = "من الصنف رقم";
        fieldItemFrom.Dock = DockStyle.Fill;
        fieldItemFrom.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblItemFrom, 0, 7);
        detailLayout.Controls.Add(fieldItemFrom, 1, 7);
        lblItemTo.Text = "إلى";
        lblItemTo.Dock = DockStyle.Fill;
        lblItemTo.TextAlign = ContentAlignment.MiddleLeft;
        fieldItemTo.AccessibleName = "إلى من الصنف رقم";
        fieldItemTo.Dock = DockStyle.Fill;
        fieldItemTo.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblItemTo, 2, 7);
        detailLayout.Controls.Add(fieldItemTo, 3, 7);
        lblWarehouseFrom.Text = "من المخزن رقم";
        lblWarehouseFrom.Dock = DockStyle.Fill;
        lblWarehouseFrom.TextAlign = ContentAlignment.MiddleLeft;
        fieldWarehouseFrom.AccessibleName = "من المخزن رقم";
        fieldWarehouseFrom.Dock = DockStyle.Fill;
        fieldWarehouseFrom.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblWarehouseFrom, 0, 8);
        detailLayout.Controls.Add(fieldWarehouseFrom, 1, 8);
        lblWarehouseTo.Text = "إلى";
        lblWarehouseTo.Dock = DockStyle.Fill;
        lblWarehouseTo.TextAlign = ContentAlignment.MiddleLeft;
        fieldWarehouseTo.AccessibleName = "إلى من المخزن رقم";
        fieldWarehouseTo.Dock = DockStyle.Fill;
        fieldWarehouseTo.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblWarehouseTo, 2, 8);
        detailLayout.Controls.Add(fieldWarehouseTo, 3, 8);
        lblComparisonType.Text = "نوع المقارنة";
        lblComparisonType.Dock = DockStyle.Fill;
        lblComparisonType.TextAlign = ContentAlignment.MiddleLeft;
        fieldComparisonType.AccessibleName = "نوع المقارنة";
        fieldComparisonType.Dock = DockStyle.Fill;
        fieldComparisonType.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblComparisonType, 0, 9);
        detailLayout.Controls.Add(fieldComparisonType, 1, 9);
        detailLayout.SetColumnSpan(fieldComparisonType, 3);
        fieldComparisonType.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldComparisonType.Enabled = false;
        lblReportType.Text = "نوع التقرير";
        lblReportType.Dock = DockStyle.Fill;
        lblReportType.TextAlign = ContentAlignment.MiddleLeft;
        fieldReportType.AccessibleName = "نوع التقرير";
        fieldReportType.Dock = DockStyle.Fill;
        fieldReportType.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblReportType, 0, 12);
        detailLayout.Controls.Add(fieldReportType, 1, 12);
        fieldReportType.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldReportType.Enabled = false;
        lblQuantityOperator.Text = "كمية الجرد";
        lblQuantityOperator.Dock = DockStyle.Fill;
        lblQuantityOperator.TextAlign = ContentAlignment.MiddleLeft;
        fieldQuantityOperator.AccessibleName = "كمية الجرد";
        fieldQuantityOperator.Dock = DockStyle.Fill;
        fieldQuantityOperator.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblQuantityOperator, 2, 12);
        detailLayout.Controls.Add(fieldQuantityOperator, 3, 12);
        fieldQuantityOperator.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldQuantityOperator.Enabled = false;
        lblReportName.Text = "اسم التقرير";
        lblReportName.Dock = DockStyle.Fill;
        lblReportName.TextAlign = ContentAlignment.MiddleLeft;
        fieldReportName.AccessibleName = "اسم التقرير";
        fieldReportName.Dock = DockStyle.Fill;
        fieldReportName.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblReportName, 0, 13);
        detailLayout.Controls.Add(fieldReportName, 1, 13);
        fieldReportName.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldReportName.Enabled = false;
        lblCountQuantity.Text = "كمية الجرد";
        lblCountQuantity.Dock = DockStyle.Fill;
        lblCountQuantity.TextAlign = ContentAlignment.MiddleLeft;
        fieldCountQuantity.AccessibleName = "كمية الجرد";
        fieldCountQuantity.Dock = DockStyle.Fill;
        fieldCountQuantity.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblCountQuantity, 2, 13);
        detailLayout.Controls.Add(fieldCountQuantity, 3, 13);
        lblValuation.Text = "التقييم حسب";
        lblValuation.Dock = DockStyle.Fill;
        lblValuation.TextAlign = ContentAlignment.MiddleLeft;
        fieldValuation.AccessibleName = "التقييم حسب";
        fieldValuation.Dock = DockStyle.Fill;
        fieldValuation.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblValuation, 0, 14);
        detailLayout.Controls.Add(fieldValuation, 1, 14);
        fieldValuation.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldValuation.Enabled = false;
        lblDisplayMethod.Text = "طريقة العرض";
        lblDisplayMethod.Dock = DockStyle.Fill;
        lblDisplayMethod.TextAlign = ContentAlignment.MiddleLeft;
        fieldDisplayMethod.AccessibleName = "طريقة العرض";
        fieldDisplayMethod.Dock = DockStyle.Fill;
        fieldDisplayMethod.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblDisplayMethod, 2, 14);
        detailLayout.Controls.Add(fieldDisplayMethod, 3, 14);
        fieldDisplayMethod.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldDisplayMethod.Enabled = false;
        lblPriceNumber.Text = "التسعيرة";
        lblPriceNumber.Dock = DockStyle.Fill;
        lblPriceNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldPriceNumber.AccessibleName = "التسعيرة";
        fieldPriceNumber.Dock = DockStyle.Fill;
        fieldPriceNumber.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblPriceNumber, 0, 15);
        detailLayout.Controls.Add(fieldPriceNumber, 1, 15);
        lblPriceName.Text = "اسم التسعيرة";
        lblPriceName.Dock = DockStyle.Fill;
        lblPriceName.TextAlign = ContentAlignment.MiddleLeft;
        fieldPriceName.AccessibleName = "اسم التسعيرة";
        fieldPriceName.Dock = DockStyle.Fill;
        fieldPriceName.Margin = new Padding(3, 2, 3, 2);
        detailLayout.Controls.Add(lblPriceName, 2, 15);
        detailLayout.Controls.Add(fieldPriceName, 3, 15);
        chkAnnual.Text = "جرد سنوي";
        chkAnnual.Dock = DockStyle.Fill;
        detailLayout.Controls.Add(chkAnnual, 1, 10);
        detailLayout.SetColumnSpan(chkAnnual, 3);
        chkUncountedItems.Text = "عرض الأصناف غير مجرودة";
        chkUncountedItems.Dock = DockStyle.Fill;
        detailLayout.Controls.Add(chkUncountedItems, 1, 11);
        detailLayout.SetColumnSpan(chkUncountedItems, 3);
        chkHideMatching.Text = "عدم عرض الأصناف المطابقة";
        chkHideMatching.Dock = DockStyle.Fill;
        detailLayout.Controls.Add(chkHideMatching, 1, 16);
        detailLayout.SetColumnSpan(chkHideMatching, 3);
        bodyLayout.Controls.Add(printLayout, 0, 0);
        bodyLayout.Controls.Add(filterLayout, 0, 1);
        bodyLayout.Controls.Add(reportTabs, 0, 2);
        reportScroll.Controls.Add(bodyLayout);
        auditFooter.Dock = DockStyle.Fill;
        auditFooter.Margin = Padding.Empty;
        standardAuditMetadata.Dock = DockStyle.Fill;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.Profile = AuditMetadataProfile.Standard;
        auditFooter.Controls.Add(standardAuditMetadata);
        lblStatus.Text = "حدّد نطاق البيانات وخيارات التقرير.";
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.TextAlign = ContentAlignment.MiddleLeft;
        mainLayout.Controls.Add(lblTitle, 0, 0);
        mainLayout.Controls.Add(commandBar, 0, 1);
        mainLayout.Controls.Add(reportScroll, 0, 2);
        mainLayout.Controls.Add(auditFooter, 0, 3);
        mainLayout.Controls.Add(lblStatus, 0, 4);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 9F);
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1180, 820);
        MinimumSize = new Size(1000, 600);
        Controls.Add(mainLayout);
        lblTitle.Text = "تقارير الجرد";
        Name = "UcInventoryStocktakeReport";
        Text = "تقارير الجرد";
        Tag = "INV:STOCKTAKE-REPORT";
        reportTabs.Dock = DockStyle.Fill;
        reportTabs.RightToLeftLayout = true;
        tabReportType.Text = "نوع التقرير";
        reportTabs.Controls.Add(tabReportType);
        detailLayout.Dock = DockStyle.Fill;
        detailLayout.Padding = new Padding(20, 10, 20, 10);
        detailLayout.Margin = Padding.Empty;
        detailLayout.ColumnCount = 4;
        detailLayout.RowCount = 18;
        detailLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
        detailLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        detailLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 125F));
        detailLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        tabReportType.Controls.Add(detailLayout);
        fieldType.Items.Add("الجرد اليدوي");
        fieldStocktakeTypeFrom.Items.Add("جرد يدوي");
        fieldStocktakeTypeTo.Items.Add("جرد يدوي");
        fieldComparisonType.Items.Add("الكمية المتوفرة إلى تاريخ الجرد");
        fieldReportType.Items.Add("زائد وناقص الجرد");
        fieldReportName.Items.Add("رقم الصنف والمخزن");
        fieldValuation.Items.Add("التكلفة");
        fieldDisplayMethod.Items.Add("رقم الصنف");
        ResumeLayout(false);
    }
}
