using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcInventoryMaterialRequest
{
    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private TabControl tabs = null!;
    private TabPage tabMain = null!;
    private TableLayoutPanel documentLayout = null!;
    private TableLayoutPanel headerLayout = null!;
    private FlowLayoutPanel actionsLayout = null!;
    private CheckBox chkStopped = null!;
    private CheckBox chkUsed = null!;
    private CheckBox chkRepeatLoading = null!;
    private TabPage tabDownload = null!;
    private TableLayoutPanel downloadLayout = null!;
    private Label lblSourceDocument = null!;
    private TextBox fieldSourceDocument = null!;
    private Label lblLoadSource = null!;
    private ComboBox fieldLoadSource = null!;
    private Label lblLoadDocumentNumber = null!;
    private TextBox fieldLoadDocumentNumber = null!;
    private Button btnLoadItems = null!;
    private DataGridView gridItems = null!;
    private Panel auditFooter = null!;
    private AuditMetadataControl standardAuditMetadata = null!;
    private Label lblBranch = null!;
    private ComboBox fieldBranch = null!;
    private Label lblRequestType = null!;
    private ComboBox fieldRequestType = null!;
    private Label lblRequestNumber = null!;
    private TextBox fieldRequestNumber = null!;
    private Label lblDate = null!;
    private TextBox fieldDate = null!;
    private Label lblRequestOrigin = null!;
    private TextBox fieldRequestOrigin = null!;
    private Label lblReference = null!;
    private TextBox fieldReference = null!;
    private Label lblPurpose = null!;
    private TextBox fieldPurpose = null!;
    private Label lblWarehouse = null!;
    private TextBox fieldWarehouse = null!;
    private Label lblSourceWarehouse = null!;
    private TextBox fieldSourceWarehouse = null!;
    private Label lblWarehouseName = null!;
    private TextBox fieldWarehouseName = null!;
    private Label lblSourceWarehouseName = null!;
    private TextBox fieldSourceWarehouseName = null!;
    private Label lblCostCenter = null!;
    private ComboBox fieldCostCenter = null!;
    private Label lblDepartment = null!;
    private ComboBox fieldDepartment = null!;
    private Label lblCustomer = null!;
    private ComboBox fieldCustomer = null!;
    private Label lblProject = null!;
    private TextBox fieldProject = null!;
    private Label lblProjectName = null!;
    private TextBox fieldProjectName = null!;
    private Label lblReservationNumber = null!;
    private TextBox fieldReservationNumber = null!;
    private Label lblApprovalState = null!;
    private ComboBox fieldApprovalState = null!;
    private DataGridViewTextBoxColumn colSequence = null!;
    private DataGridViewButtonColumn colLookup = null!;
    private DataGridViewTextBoxColumn colItemNumber = null!;
    private DataGridViewTextBoxColumn colItemName = null!;
    private DataGridViewTextBoxColumn colUnit = null!;
    private DataGridViewTextBoxColumn colPackSize = null!;
    private DataGridViewTextBoxColumn colExpiryDate = null!;
    private DataGridViewTextBoxColumn colQuantity = null!;
    private DataGridViewTextBoxColumn colApprovedQuantity = null!;
    private DataGridViewTextBoxColumn colGrantedQuantity = null!;
    private DataGridViewComboBoxColumn colReserveQuantity = null!;
    private DataGridViewTextBoxColumn colReservedQuantity = null!;
    private DataGridViewTextBoxColumn colUntilDate = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        tabs = new TabControl();
        tabs.Name = "tabs";
        tabMain = new TabPage();
        tabMain.Name = "tabMain";
        documentLayout = new TableLayoutPanel();
        documentLayout.Name = "documentLayout";
        headerLayout = new TableLayoutPanel();
        headerLayout.Name = "headerLayout";
        actionsLayout = new FlowLayoutPanel();
        actionsLayout.Name = "actionsLayout";
        chkStopped = new CheckBox();
        chkStopped.Name = "chkStopped";
        chkUsed = new CheckBox();
        chkUsed.Name = "chkUsed";
        chkRepeatLoading = new CheckBox();
        chkRepeatLoading.Name = "chkRepeatLoading";
        tabDownload = new TabPage();
        tabDownload.Name = "tabDownload";
        downloadLayout = new TableLayoutPanel();
        downloadLayout.Name = "downloadLayout";
        lblSourceDocument = new Label();
        lblSourceDocument.Name = "lblSourceDocument";
        fieldSourceDocument = new TextBox();
        fieldSourceDocument.Name = "fieldSourceDocument";
        lblLoadSource = new Label();
        lblLoadSource.Name = "lblLoadSource";
        fieldLoadSource = new ComboBox();
        fieldLoadSource.Name = "fieldLoadSource";
        lblLoadDocumentNumber = new Label();
        lblLoadDocumentNumber.Name = "lblLoadDocumentNumber";
        fieldLoadDocumentNumber = new TextBox();
        fieldLoadDocumentNumber.Name = "fieldLoadDocumentNumber";
        btnLoadItems = new Button();
        btnLoadItems.Name = "btnLoadItems";
        gridItems = new DataGridView();
        gridItems.Name = "gridItems";
        auditFooter = new Panel();
        auditFooter.Name = "auditFooter";
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        lblBranch = new Label();
        lblBranch.Name = "lblBranch";
        fieldBranch = new ComboBox();
        fieldBranch.Name = "fieldBranch";
        lblRequestType = new Label();
        lblRequestType.Name = "lblRequestType";
        fieldRequestType = new ComboBox();
        fieldRequestType.Name = "fieldRequestType";
        lblRequestNumber = new Label();
        lblRequestNumber.Name = "lblRequestNumber";
        fieldRequestNumber = new TextBox();
        fieldRequestNumber.Name = "fieldRequestNumber";
        lblDate = new Label();
        lblDate.Name = "lblDate";
        fieldDate = new TextBox();
        fieldDate.Name = "fieldDate";
        lblRequestOrigin = new Label();
        lblRequestOrigin.Name = "lblRequestOrigin";
        fieldRequestOrigin = new TextBox();
        fieldRequestOrigin.Name = "fieldRequestOrigin";
        lblReference = new Label();
        lblReference.Name = "lblReference";
        fieldReference = new TextBox();
        fieldReference.Name = "fieldReference";
        lblPurpose = new Label();
        lblPurpose.Name = "lblPurpose";
        fieldPurpose = new TextBox();
        fieldPurpose.Name = "fieldPurpose";
        lblWarehouse = new Label();
        lblWarehouse.Name = "lblWarehouse";
        fieldWarehouse = new TextBox();
        fieldWarehouse.Name = "fieldWarehouse";
        lblSourceWarehouse = new Label();
        lblSourceWarehouse.Name = "lblSourceWarehouse";
        fieldSourceWarehouse = new TextBox();
        fieldSourceWarehouse.Name = "fieldSourceWarehouse";
        lblWarehouseName = new Label();
        lblWarehouseName.Name = "lblWarehouseName";
        fieldWarehouseName = new TextBox();
        fieldWarehouseName.Name = "fieldWarehouseName";
        lblSourceWarehouseName = new Label();
        lblSourceWarehouseName.Name = "lblSourceWarehouseName";
        fieldSourceWarehouseName = new TextBox();
        fieldSourceWarehouseName.Name = "fieldSourceWarehouseName";
        lblCostCenter = new Label();
        lblCostCenter.Name = "lblCostCenter";
        fieldCostCenter = new ComboBox();
        fieldCostCenter.Name = "fieldCostCenter";
        lblDepartment = new Label();
        lblDepartment.Name = "lblDepartment";
        fieldDepartment = new ComboBox();
        fieldDepartment.Name = "fieldDepartment";
        lblCustomer = new Label();
        lblCustomer.Name = "lblCustomer";
        fieldCustomer = new ComboBox();
        fieldCustomer.Name = "fieldCustomer";
        lblProject = new Label();
        lblProject.Name = "lblProject";
        fieldProject = new TextBox();
        fieldProject.Name = "fieldProject";
        lblProjectName = new Label();
        lblProjectName.Name = "lblProjectName";
        fieldProjectName = new TextBox();
        fieldProjectName.Name = "fieldProjectName";
        lblReservationNumber = new Label();
        lblReservationNumber.Name = "lblReservationNumber";
        fieldReservationNumber = new TextBox();
        fieldReservationNumber.Name = "fieldReservationNumber";
        lblApprovalState = new Label();
        lblApprovalState.Name = "lblApprovalState";
        fieldApprovalState = new ComboBox();
        fieldApprovalState.Name = "fieldApprovalState";
        colSequence = new DataGridViewTextBoxColumn();
        colSequence.Name = "colSequence";
        colLookup = new DataGridViewButtonColumn();
        colLookup.Name = "colLookup";
        colItemNumber = new DataGridViewTextBoxColumn();
        colItemNumber.Name = "colItemNumber";
        colItemName = new DataGridViewTextBoxColumn();
        colItemName.Name = "colItemName";
        colUnit = new DataGridViewTextBoxColumn();
        colUnit.Name = "colUnit";
        colPackSize = new DataGridViewTextBoxColumn();
        colPackSize.Name = "colPackSize";
        colExpiryDate = new DataGridViewTextBoxColumn();
        colExpiryDate.Name = "colExpiryDate";
        colQuantity = new DataGridViewTextBoxColumn();
        colQuantity.Name = "colQuantity";
        colApprovedQuantity = new DataGridViewTextBoxColumn();
        colApprovedQuantity.Name = "colApprovedQuantity";
        colGrantedQuantity = new DataGridViewTextBoxColumn();
        colGrantedQuantity.Name = "colGrantedQuantity";
        colReserveQuantity = new DataGridViewComboBoxColumn();
        colReserveQuantity.Name = "colReserveQuantity";
        colReservedQuantity = new DataGridViewTextBoxColumn();
        colReservedQuantity.Name = "colReservedQuantity";
        colUntilDate = new DataGridViewTextBoxColumn();
        colUntilDate.Name = "colUntilDate";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = Padding.Empty;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.BackColor = Color.FromArgb(23, 50, 78);
        lblTitle.ForeColor = Color.White;
        commandBar.Dock = DockStyle.Fill;
        commandBar.Margin = Padding.Empty;
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeftLayout = true;
        tabMain.Text = "البيانات الرئيسية";
        tabMain.Padding = Padding.Empty;
        tabs.Controls.Add(tabMain);
        documentLayout.Dock = DockStyle.Fill;
        documentLayout.ColumnCount = 1;
        documentLayout.RowCount = 3;
        documentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 204F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tabMain.Controls.Add(documentLayout);
        headerLayout.Dock = DockStyle.Fill;
        headerLayout.Padding = new Padding(10, 6, 10, 6);
        headerLayout.Margin = Padding.Empty;
        headerLayout.ColumnCount = 6;
        headerLayout.RowCount = 6;
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        lblBranch.Text = "الفرع";
        lblBranch.Dock = DockStyle.Fill;
        lblBranch.TextAlign = ContentAlignment.MiddleLeft;
        fieldBranch.AccessibleName = "الفرع";
        fieldBranch.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblBranch, 0, 0);
        headerLayout.Controls.Add(fieldBranch, 1, 0);
        fieldBranch.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldBranch.Enabled = false;
        lblRequestType.Text = "نوع الطلب";
        lblRequestType.Dock = DockStyle.Fill;
        lblRequestType.TextAlign = ContentAlignment.MiddleLeft;
        fieldRequestType.AccessibleName = "نوع الطلب";
        fieldRequestType.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblRequestType, 2, 0);
        headerLayout.Controls.Add(fieldRequestType, 3, 0);
        fieldRequestType.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldRequestType.Enabled = false;
        lblRequestNumber.Text = "رقم الطلب";
        lblRequestNumber.Dock = DockStyle.Fill;
        lblRequestNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldRequestNumber.AccessibleName = "رقم الطلب";
        fieldRequestNumber.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblRequestNumber, 4, 0);
        headerLayout.Controls.Add(fieldRequestNumber, 5, 0);
        fieldRequestNumber.ReadOnly = true;
        lblDate.Text = "تاريخ الطلب";
        lblDate.Dock = DockStyle.Fill;
        lblDate.TextAlign = ContentAlignment.MiddleLeft;
        fieldDate.AccessibleName = "تاريخ الطلب";
        fieldDate.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDate, 0, 1);
        headerLayout.Controls.Add(fieldDate, 1, 1);
        fieldDate.ReadOnly = true;
        lblRequestOrigin.Text = "جهة الطلب";
        lblRequestOrigin.Dock = DockStyle.Fill;
        lblRequestOrigin.TextAlign = ContentAlignment.MiddleLeft;
        fieldRequestOrigin.AccessibleName = "جهة الطلب";
        fieldRequestOrigin.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblRequestOrigin, 2, 1);
        headerLayout.Controls.Add(fieldRequestOrigin, 3, 1);
        fieldRequestOrigin.ReadOnly = true;
        lblReference.Text = "رقم المرجع";
        lblReference.Dock = DockStyle.Fill;
        lblReference.TextAlign = ContentAlignment.MiddleLeft;
        fieldReference.AccessibleName = "رقم المرجع";
        fieldReference.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblReference, 4, 1);
        headerLayout.Controls.Add(fieldReference, 5, 1);
        fieldReference.ReadOnly = true;
        lblPurpose.Text = "الغرض من الطلب";
        lblPurpose.Dock = DockStyle.Fill;
        lblPurpose.TextAlign = ContentAlignment.MiddleLeft;
        fieldPurpose.AccessibleName = "الغرض من الطلب";
        fieldPurpose.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblPurpose, 0, 2);
        headerLayout.Controls.Add(fieldPurpose, 1, 2);
        fieldPurpose.ReadOnly = true;
        lblWarehouse.Text = "رقم المخزن";
        lblWarehouse.Dock = DockStyle.Fill;
        lblWarehouse.TextAlign = ContentAlignment.MiddleLeft;
        fieldWarehouse.AccessibleName = "رقم المخزن";
        fieldWarehouse.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblWarehouse, 2, 2);
        headerLayout.Controls.Add(fieldWarehouse, 3, 2);
        fieldWarehouse.ReadOnly = true;
        lblSourceWarehouse.Text = "المخزن المطلوب منه";
        lblSourceWarehouse.Dock = DockStyle.Fill;
        lblSourceWarehouse.TextAlign = ContentAlignment.MiddleLeft;
        fieldSourceWarehouse.AccessibleName = "المخزن المطلوب منه";
        fieldSourceWarehouse.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblSourceWarehouse, 4, 2);
        headerLayout.Controls.Add(fieldSourceWarehouse, 5, 2);
        fieldSourceWarehouse.ReadOnly = true;
        lblWarehouseName.Text = "اسم المخزن";
        lblWarehouseName.Dock = DockStyle.Fill;
        lblWarehouseName.TextAlign = ContentAlignment.MiddleLeft;
        fieldWarehouseName.AccessibleName = "اسم المخزن";
        fieldWarehouseName.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblWarehouseName, 0, 3);
        headerLayout.Controls.Add(fieldWarehouseName, 1, 3);
        fieldWarehouseName.ReadOnly = true;
        lblSourceWarehouseName.Text = "اسم المخزن المطلوب منه";
        lblSourceWarehouseName.Dock = DockStyle.Fill;
        lblSourceWarehouseName.TextAlign = ContentAlignment.MiddleLeft;
        fieldSourceWarehouseName.AccessibleName = "اسم المخزن المطلوب منه";
        fieldSourceWarehouseName.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblSourceWarehouseName, 2, 3);
        headerLayout.Controls.Add(fieldSourceWarehouseName, 3, 3);
        fieldSourceWarehouseName.ReadOnly = true;
        lblCostCenter.Text = "مركز التكلفة";
        lblCostCenter.Dock = DockStyle.Fill;
        lblCostCenter.TextAlign = ContentAlignment.MiddleLeft;
        fieldCostCenter.AccessibleName = "مركز التكلفة";
        fieldCostCenter.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblCostCenter, 4, 3);
        headerLayout.Controls.Add(fieldCostCenter, 5, 3);
        fieldCostCenter.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldCostCenter.Enabled = false;
        lblDepartment.Text = "الإدارة";
        lblDepartment.Dock = DockStyle.Fill;
        lblDepartment.TextAlign = ContentAlignment.MiddleLeft;
        fieldDepartment.AccessibleName = "الإدارة";
        fieldDepartment.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDepartment, 0, 4);
        headerLayout.Controls.Add(fieldDepartment, 1, 4);
        fieldDepartment.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldDepartment.Enabled = false;
        lblCustomer.Text = "العميل";
        lblCustomer.Dock = DockStyle.Fill;
        lblCustomer.TextAlign = ContentAlignment.MiddleLeft;
        fieldCustomer.AccessibleName = "العميل";
        fieldCustomer.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblCustomer, 2, 4);
        headerLayout.Controls.Add(fieldCustomer, 3, 4);
        fieldCustomer.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldCustomer.Enabled = false;
        lblProject.Text = "رقم المشروع";
        lblProject.Dock = DockStyle.Fill;
        lblProject.TextAlign = ContentAlignment.MiddleLeft;
        fieldProject.AccessibleName = "رقم المشروع";
        fieldProject.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblProject, 4, 4);
        headerLayout.Controls.Add(fieldProject, 5, 4);
        fieldProject.ReadOnly = true;
        lblProjectName.Text = "اسم المشروع";
        lblProjectName.Dock = DockStyle.Fill;
        lblProjectName.TextAlign = ContentAlignment.MiddleLeft;
        fieldProjectName.AccessibleName = "اسم المشروع";
        fieldProjectName.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblProjectName, 0, 5);
        headerLayout.Controls.Add(fieldProjectName, 1, 5);
        fieldProjectName.ReadOnly = true;
        lblReservationNumber.Text = "رقم الحجز";
        lblReservationNumber.Dock = DockStyle.Fill;
        lblReservationNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldReservationNumber.AccessibleName = "رقم الحجز";
        fieldReservationNumber.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblReservationNumber, 2, 5);
        headerLayout.Controls.Add(fieldReservationNumber, 3, 5);
        fieldReservationNumber.ReadOnly = true;
        lblApprovalState.Text = "حالة الاعتماد";
        lblApprovalState.Dock = DockStyle.Fill;
        lblApprovalState.TextAlign = ContentAlignment.MiddleLeft;
        fieldApprovalState.AccessibleName = "حالة الاعتماد";
        fieldApprovalState.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblApprovalState, 4, 5);
        headerLayout.Controls.Add(fieldApprovalState, 5, 5);
        fieldApprovalState.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldApprovalState.Enabled = false;
        actionsLayout.Dock = DockStyle.Fill;
        actionsLayout.FlowDirection = FlowDirection.RightToLeft;
        actionsLayout.WrapContents = false;
        actionsLayout.Margin = Padding.Empty;
        chkStopped.Text = "موقف";
        chkStopped.AutoSize = true;
        chkStopped.Enabled = false;
        actionsLayout.Controls.Add(chkStopped);
        chkUsed.Text = "مستخدم";
        chkUsed.AutoSize = true;
        chkUsed.Enabled = false;
        actionsLayout.Controls.Add(chkUsed);
        chkRepeatLoading.Text = "إنزال الطلب المخزني أكثر من مرة";
        chkRepeatLoading.AutoSize = true;
        chkRepeatLoading.Enabled = false;
        actionsLayout.Controls.Add(chkRepeatLoading);
        gridItems.Dock = DockStyle.Fill;
        gridItems.AccessibleName = "أصناف طلب صرف/تحويل مواد";
        gridItems.ReadOnly = true;
        gridItems.AllowUserToAddRows = false;
        gridItems.AllowUserToDeleteRows = false;
        gridItems.AutoGenerateColumns = false;
        gridItems.RowHeadersVisible = false;
        gridItems.BackgroundColor = Color.White;
        gridItems.ColumnHeadersHeight = 34;
        gridItems.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridItems.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        colSequence.HeaderText = "م";
        colSequence.Width = 40;
        colSequence.ReadOnly = true;
        colSequence.SortMode = DataGridViewColumnSortMode.NotSortable;
        colLookup.HeaderText = "";
        colLookup.Width = 30;
        colLookup.ReadOnly = true;
        colLookup.SortMode = DataGridViewColumnSortMode.NotSortable;
        colLookup.Text = "…";
        colLookup.UseColumnTextForButtonValue = true;
        colItemNumber.HeaderText = "رقم الصنف";
        colItemNumber.Width = 130;
        colItemNumber.ReadOnly = true;
        colItemNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colItemName.HeaderText = "اسم الصنف";
        colItemName.Width = 225;
        colItemName.ReadOnly = true;
        colItemName.SortMode = DataGridViewColumnSortMode.NotSortable;
        colUnit.HeaderText = "الوحدة";
        colUnit.Width = 75;
        colUnit.ReadOnly = true;
        colUnit.SortMode = DataGridViewColumnSortMode.NotSortable;
        colPackSize.HeaderText = "الشد";
        colPackSize.Width = 65;
        colPackSize.ReadOnly = true;
        colPackSize.SortMode = DataGridViewColumnSortMode.NotSortable;
        colExpiryDate.HeaderText = "تاريخ الانتهاء";
        colExpiryDate.Width = 115;
        colExpiryDate.ReadOnly = true;
        colExpiryDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        colQuantity.HeaderText = "الكمية";
        colQuantity.Width = 85;
        colQuantity.ReadOnly = true;
        colQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        colApprovedQuantity.HeaderText = "كمية معتمدة";
        colApprovedQuantity.Width = 105;
        colApprovedQuantity.ReadOnly = true;
        colApprovedQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        colGrantedQuantity.HeaderText = "الكمية الممنوحة";
        colGrantedQuantity.Width = 110;
        colGrantedQuantity.ReadOnly = true;
        colGrantedQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        colReserveQuantity.HeaderText = "حجز الكميات";
        colReserveQuantity.Width = 110;
        colReserveQuantity.ReadOnly = true;
        colReserveQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        colReservedQuantity.HeaderText = "الكمية المحجوزة";
        colReservedQuantity.Width = 110;
        colReservedQuantity.ReadOnly = true;
        colReservedQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        colUntilDate.HeaderText = "إلى تاريخ";
        colUntilDate.Width = 115;
        colUntilDate.ReadOnly = true;
        colUntilDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.AddRange(new DataGridViewColumn[] { colSequence, colLookup, colItemNumber, colItemName, colUnit, colPackSize, colExpiryDate, colQuantity, colApprovedQuantity, colGrantedQuantity, colReserveQuantity, colReservedQuantity, colUntilDate });
        documentLayout.Controls.Add(headerLayout, 0, 0);
        documentLayout.Controls.Add(actionsLayout, 0, 1);
        documentLayout.Controls.Add(gridItems, 0, 2);
        auditFooter.Dock = DockStyle.Fill;
        auditFooter.Margin = Padding.Empty;
        standardAuditMetadata.Dock = DockStyle.Fill;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.Profile = AuditMetadataProfile.Standard;
        auditFooter.Controls.Add(standardAuditMetadata);
        mainLayout.Controls.Add(lblTitle, 0, 0);
        mainLayout.Controls.Add(commandBar, 0, 1);
        mainLayout.Controls.Add(tabs, 0, 2);
        mainLayout.Controls.Add(auditFooter, 0, 3);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 9F);
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1180, 720);
        MinimumSize = new Size(1000, 600);
        Controls.Add(mainLayout);
        lblTitle.Text = "طلب صرف/تحويل مواد";
        Name = "UcInventoryMaterialRequest";
        Text = "طلب صرف/تحويل مواد";
        Tag = "INV:MATERIAL-REQUEST";
        fieldRequestType.Items.Add("طلب تحويل مخزني");
        fieldApprovalState.Items.Add("غير معتمد");
        colReserveQuantity.Items.AddRange(new object[] { "نعم", "لا" });
        tabDownload.Text = "إنزال البيانات";
        tabs.Controls.Add(tabDownload);
        downloadLayout.Dock = DockStyle.Fill;
        downloadLayout.Padding = new Padding(12);
        downloadLayout.ColumnCount = 5;
        downloadLayout.RowCount = 3;
        downloadLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 145F));
        downloadLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 60F));
        downloadLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 115F));
        downloadLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 40F));
        downloadLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 125F));
        downloadLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
        downloadLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
        downloadLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        lblLoadSource.Text = "إنزال البيانات من";
        lblLoadSource.Dock = DockStyle.Fill;
        lblLoadSource.TextAlign = ContentAlignment.MiddleLeft;
        fieldLoadSource.AccessibleName = "إنزال البيانات من";
        fieldLoadSource.Dock = DockStyle.Fill;
        fieldLoadSource.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldLoadSource.Items.Add("أمر توريد مخزني");
        fieldLoadSource.Enabled = false;
        lblLoadDocumentNumber.Text = "رقم المستند";
        lblLoadDocumentNumber.Dock = DockStyle.Fill;
        lblLoadDocumentNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldLoadDocumentNumber.AccessibleName = "رقم المستند";
        fieldLoadDocumentNumber.Dock = DockStyle.Fill;
        fieldLoadDocumentNumber.ReadOnly = true;
        lblSourceDocument.Text = "رقم الوثيقة المرجع";
        lblSourceDocument.Dock = DockStyle.Fill;
        lblSourceDocument.TextAlign = ContentAlignment.MiddleLeft;
        fieldSourceDocument.AccessibleName = "رقم الوثيقة المرجع";
        fieldSourceDocument.Dock = DockStyle.Fill;
        fieldSourceDocument.ReadOnly = true;
        btnLoadItems.Text = "إنزال الأصناف";
        btnLoadItems.Dock = DockStyle.Fill;
        btnLoadItems.Enabled = false;
        downloadLayout.Controls.Add(lblLoadSource, 0, 0);
        downloadLayout.Controls.Add(fieldLoadSource, 1, 0);
        downloadLayout.Controls.Add(lblLoadDocumentNumber, 2, 0);
        downloadLayout.Controls.Add(fieldLoadDocumentNumber, 3, 0);
        downloadLayout.Controls.Add(btnLoadItems, 4, 0);
        downloadLayout.Controls.Add(lblSourceDocument, 0, 1);
        downloadLayout.Controls.Add(fieldSourceDocument, 1, 1);
        tabDownload.Controls.Add(downloadLayout);
        ResumeLayout(false);
    }
}
