using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcInventoryManualStocktake
{
    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private TabControl tabs = null!;
    private TabPage tabMain = null!;
    private TableLayoutPanel documentLayout = null!;
    private TableLayoutPanel headerLayout = null!;
    private FlowLayoutPanel actionsLayout = null!;
    private CheckBox chkAnnual = null!;
    private Button btnLoadMachineCount = null!;
    private DataGridView gridItems = null!;
    private Panel auditFooter = null!;
    private AuditMetadataControl standardAuditMetadata = null!;
    private Label lblBranch = null!;
    private ComboBox fieldBranch = null!;
    private Label lblStocktakeType = null!;
    private ComboBox fieldStocktakeType = null!;
    private Label lblStocktakeNumber = null!;
    private TextBox fieldStocktakeNumber = null!;
    private Label lblDate = null!;
    private TextBox fieldDate = null!;
    private Label lblDescription = null!;
    private TextBox fieldDescription = null!;
    private Label lblDefaultWarehouse = null!;
    private ComboBox fieldDefaultWarehouse = null!;
    private Label lblDefaultQuantity = null!;
    private TextBox fieldDefaultQuantity = null!;
    private Label lblReference = null!;
    private TextBox fieldReference = null!;
    private DataGridViewTextBoxColumn colSequence = null!;
    private DataGridViewButtonColumn colLookup = null!;
    private DataGridViewTextBoxColumn colItemNumber = null!;
    private DataGridViewTextBoxColumn colItemName = null!;
    private DataGridViewTextBoxColumn colUnit = null!;
    private DataGridViewTextBoxColumn colWarehouse = null!;
    private DataGridViewTextBoxColumn colExpiryDate = null!;
    private DataGridViewTextBoxColumn colPackSize = null!;
    private DataGridViewTextBoxColumn colStocktakeQuantity = null!;
    private DataGridViewTextBoxColumn colBarcode = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        tabs = new TabControl();
        tabs.Name = "tabs";
        tabMain = new TabPage();
        tabMain.Name = "tabMain";
        documentLayout = new TableLayoutPanel();
        documentLayout.Name = "documentLayout";
        headerLayout = new TableLayoutPanel();
        headerLayout.Name = "headerLayout";
        actionsLayout = new FlowLayoutPanel();
        actionsLayout.Name = "actionsLayout";
        chkAnnual = new CheckBox();
        chkAnnual.Name = "chkAnnual";
        btnLoadMachineCount = new Button();
        btnLoadMachineCount.Name = "btnLoadMachineCount";
        gridItems = new DataGridView();
        gridItems.Name = "gridItems";
        auditFooter = new Panel();
        auditFooter.Name = "auditFooter";
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        lblBranch = new Label();
        lblBranch.Name = "lblBranch";
        fieldBranch = new ComboBox();
        fieldBranch.Name = "fieldBranch";
        lblStocktakeType = new Label();
        lblStocktakeType.Name = "lblStocktakeType";
        fieldStocktakeType = new ComboBox();
        fieldStocktakeType.Name = "fieldStocktakeType";
        lblStocktakeNumber = new Label();
        lblStocktakeNumber.Name = "lblStocktakeNumber";
        fieldStocktakeNumber = new TextBox();
        fieldStocktakeNumber.Name = "fieldStocktakeNumber";
        lblDate = new Label();
        lblDate.Name = "lblDate";
        fieldDate = new TextBox();
        fieldDate.Name = "fieldDate";
        lblDescription = new Label();
        lblDescription.Name = "lblDescription";
        fieldDescription = new TextBox();
        fieldDescription.Name = "fieldDescription";
        lblDefaultWarehouse = new Label();
        lblDefaultWarehouse.Name = "lblDefaultWarehouse";
        fieldDefaultWarehouse = new ComboBox();
        fieldDefaultWarehouse.Name = "fieldDefaultWarehouse";
        lblDefaultQuantity = new Label();
        lblDefaultQuantity.Name = "lblDefaultQuantity";
        fieldDefaultQuantity = new TextBox();
        fieldDefaultQuantity.Name = "fieldDefaultQuantity";
        lblReference = new Label();
        lblReference.Name = "lblReference";
        fieldReference = new TextBox();
        fieldReference.Name = "fieldReference";
        colSequence = new DataGridViewTextBoxColumn();
        colSequence.Name = "colSequence";
        colLookup = new DataGridViewButtonColumn();
        colLookup.Name = "colLookup";
        colItemNumber = new DataGridViewTextBoxColumn();
        colItemNumber.Name = "colItemNumber";
        colItemName = new DataGridViewTextBoxColumn();
        colItemName.Name = "colItemName";
        colUnit = new DataGridViewTextBoxColumn();
        colUnit.Name = "colUnit";
        colWarehouse = new DataGridViewTextBoxColumn();
        colWarehouse.Name = "colWarehouse";
        colExpiryDate = new DataGridViewTextBoxColumn();
        colExpiryDate.Name = "colExpiryDate";
        colPackSize = new DataGridViewTextBoxColumn();
        colPackSize.Name = "colPackSize";
        colStocktakeQuantity = new DataGridViewTextBoxColumn();
        colStocktakeQuantity.Name = "colStocktakeQuantity";
        colBarcode = new DataGridViewTextBoxColumn();
        colBarcode.Name = "colBarcode";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = Padding.Empty;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.BackColor = Color.FromArgb(23, 50, 78);
        lblTitle.ForeColor = Color.White;
        commandBar.Dock = DockStyle.Fill;
        commandBar.Margin = Padding.Empty;
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeftLayout = true;
        tabMain.Text = "البيانات الرئيسية";
        tabMain.Padding = Padding.Empty;
        tabs.Controls.Add(tabMain);
        documentLayout.Dock = DockStyle.Fill;
        documentLayout.ColumnCount = 1;
        documentLayout.RowCount = 3;
        documentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 108F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tabMain.Controls.Add(documentLayout);
        headerLayout.Dock = DockStyle.Fill;
        headerLayout.Padding = new Padding(10, 6, 10, 6);
        headerLayout.Margin = Padding.Empty;
        headerLayout.ColumnCount = 6;
        headerLayout.RowCount = 3;
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 110F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 110F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 110F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        lblBranch.Text = "الفرع";
        lblBranch.Dock = DockStyle.Fill;
        lblBranch.TextAlign = ContentAlignment.MiddleLeft;
        fieldBranch.AccessibleName = "الفرع";
        fieldBranch.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblBranch, 0, 0);
        headerLayout.Controls.Add(fieldBranch, 1, 0);
        fieldBranch.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldBranch.Enabled = false;
        lblStocktakeType.Text = "نوع الجرد";
        lblStocktakeType.Dock = DockStyle.Fill;
        lblStocktakeType.TextAlign = ContentAlignment.MiddleLeft;
        fieldStocktakeType.AccessibleName = "نوع الجرد";
        fieldStocktakeType.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblStocktakeType, 2, 0);
        headerLayout.Controls.Add(fieldStocktakeType, 3, 0);
        fieldStocktakeType.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldStocktakeType.Enabled = false;
        lblStocktakeNumber.Text = "رقم الجرد";
        lblStocktakeNumber.Dock = DockStyle.Fill;
        lblStocktakeNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldStocktakeNumber.AccessibleName = "رقم الجرد";
        fieldStocktakeNumber.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblStocktakeNumber, 4, 0);
        headerLayout.Controls.Add(fieldStocktakeNumber, 5, 0);
        fieldStocktakeNumber.ReadOnly = true;
        lblDate.Text = "تاريخ الجرد";
        lblDate.Dock = DockStyle.Fill;
        lblDate.TextAlign = ContentAlignment.MiddleLeft;
        fieldDate.AccessibleName = "تاريخ الجرد";
        fieldDate.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDate, 0, 1);
        headerLayout.Controls.Add(fieldDate, 1, 1);
        fieldDate.ReadOnly = true;
        lblDescription.Text = "البيان";
        lblDescription.Dock = DockStyle.Fill;
        lblDescription.TextAlign = ContentAlignment.MiddleLeft;
        fieldDescription.AccessibleName = "البيان";
        fieldDescription.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDescription, 2, 1);
        headerLayout.Controls.Add(fieldDescription, 3, 1);
        fieldDescription.ReadOnly = true;
        lblDefaultWarehouse.Text = "المخزن الافتراضي";
        lblDefaultWarehouse.Dock = DockStyle.Fill;
        lblDefaultWarehouse.TextAlign = ContentAlignment.MiddleLeft;
        fieldDefaultWarehouse.AccessibleName = "المخزن الافتراضي";
        fieldDefaultWarehouse.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDefaultWarehouse, 4, 1);
        headerLayout.Controls.Add(fieldDefaultWarehouse, 5, 1);
        fieldDefaultWarehouse.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldDefaultWarehouse.Enabled = false;
        lblDefaultQuantity.Text = "الكمية الافتراضية";
        lblDefaultQuantity.Dock = DockStyle.Fill;
        lblDefaultQuantity.TextAlign = ContentAlignment.MiddleLeft;
        fieldDefaultQuantity.AccessibleName = "الكمية الافتراضية";
        fieldDefaultQuantity.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDefaultQuantity, 0, 2);
        headerLayout.Controls.Add(fieldDefaultQuantity, 1, 2);
        fieldDefaultQuantity.ReadOnly = true;
        lblReference.Text = "رقم المرجع";
        lblReference.Dock = DockStyle.Fill;
        lblReference.TextAlign = ContentAlignment.MiddleLeft;
        fieldReference.AccessibleName = "رقم المرجع";
        fieldReference.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblReference, 2, 2);
        headerLayout.Controls.Add(fieldReference, 3, 2);
        fieldReference.ReadOnly = true;
        chkAnnual.Text = "جرد سنوي";
        chkAnnual.AccessibleName = "جرد سنوي";
        chkAnnual.Dock = DockStyle.Fill;
        chkAnnual.Enabled = false;
        headerLayout.Controls.Add(chkAnnual, 4, 2);
        headerLayout.SetColumnSpan(chkAnnual, 2);
        actionsLayout.Dock = DockStyle.Fill;
        actionsLayout.FlowDirection = FlowDirection.RightToLeft;
        actionsLayout.WrapContents = false;
        actionsLayout.Margin = Padding.Empty;
        btnLoadMachineCount.Text = "إنزال من جرد الآلات";
        btnLoadMachineCount.AccessibleName = "إنزال من جرد الآلات";
        btnLoadMachineCount.AutoSize = true;
        btnLoadMachineCount.Enabled = false;
        actionsLayout.Controls.Add(btnLoadMachineCount);
        gridItems.Dock = DockStyle.Fill;
        gridItems.AccessibleName = "أصناف الجرد اليدوي";
        gridItems.ReadOnly = true;
        gridItems.AllowUserToAddRows = false;
        gridItems.AllowUserToDeleteRows = false;
        gridItems.AutoGenerateColumns = false;
        gridItems.RowHeadersVisible = false;
        gridItems.BackgroundColor = Color.White;
        gridItems.ColumnHeadersHeight = 34;
        gridItems.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridItems.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        colSequence.HeaderText = "م";
        colSequence.Width = 45;
        colSequence.ReadOnly = true;
        colSequence.SortMode = DataGridViewColumnSortMode.NotSortable;
        colLookup.HeaderText = "";
        colLookup.Width = 35;
        colLookup.ReadOnly = true;
        colLookup.SortMode = DataGridViewColumnSortMode.NotSortable;
        colLookup.Text = "…";
        colLookup.UseColumnTextForButtonValue = true;
        colItemNumber.HeaderText = "رقم الصنف";
        colItemNumber.Width = 125;
        colItemNumber.ReadOnly = true;
        colItemNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colItemName.HeaderText = "اسم الصنف";
        colItemName.Width = 240;
        colItemName.ReadOnly = true;
        colItemName.SortMode = DataGridViewColumnSortMode.NotSortable;
        colUnit.HeaderText = "الوحدة";
        colUnit.Width = 85;
        colUnit.ReadOnly = true;
        colUnit.SortMode = DataGridViewColumnSortMode.NotSortable;
        colWarehouse.HeaderText = "المخزن";
        colWarehouse.Width = 90;
        colWarehouse.ReadOnly = true;
        colWarehouse.SortMode = DataGridViewColumnSortMode.NotSortable;
        colExpiryDate.HeaderText = "تاريخ الانتهاء";
        colExpiryDate.Width = 125;
        colExpiryDate.ReadOnly = true;
        colExpiryDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        colPackSize.HeaderText = "الشد";
        colPackSize.Width = 80;
        colPackSize.ReadOnly = true;
        colPackSize.SortMode = DataGridViewColumnSortMode.NotSortable;
        colStocktakeQuantity.HeaderText = "كمية الجرد";
        colStocktakeQuantity.Width = 125;
        colStocktakeQuantity.ReadOnly = true;
        colStocktakeQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        colBarcode.HeaderText = "رقم الباركود";
        colBarcode.Width = 160;
        colBarcode.ReadOnly = true;
        colBarcode.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.AddRange(new DataGridViewColumn[] { colSequence, colLookup, colItemNumber, colItemName, colUnit, colWarehouse, colExpiryDate, colPackSize, colStocktakeQuantity, colBarcode });
        documentLayout.Controls.Add(headerLayout, 0, 0);
        documentLayout.Controls.Add(actionsLayout, 0, 1);
        documentLayout.Controls.Add(gridItems, 0, 2);
        auditFooter.Dock = DockStyle.Fill;
        auditFooter.Margin = Padding.Empty;
        standardAuditMetadata.Dock = DockStyle.Fill;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.Profile = AuditMetadataProfile.Standard;
        auditFooter.Controls.Add(standardAuditMetadata);
        mainLayout.Controls.Add(lblTitle, 0, 0);
        mainLayout.Controls.Add(commandBar, 0, 1);
        mainLayout.Controls.Add(tabs, 0, 2);
        mainLayout.Controls.Add(auditFooter, 0, 3);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 9F);
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1180, 720);
        MinimumSize = new Size(1000, 600);
        Controls.Add(mainLayout);
        lblTitle.Text = "الجرد اليدوي";
        Name = "UcInventoryManualStocktake";
        Text = "الجرد اليدوي";
        Tag = "INV:MANUAL-STOCKTAKE";
        ResumeLayout(false);
    }
}
