using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcPurchaseRequest
{
    private TableLayoutPanel mainLayout = null!;
    private TableLayoutPanel headerLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private DataGridView gridItems = null!;
    private DataGridViewButtonColumn colLookup = null!;
    private Panel auditFooter = null!;
    private AuditMetadataControl standardAuditMetadata = null!;
    private Label lblOperationStatus = null!;
    private CheckBox chkUsed = null!;
    private CheckBox chkStopped = null!;
    private CheckBox chkAutoSynchronization = null!;
    private Button btnAutomaticRequest = null!;
    private Button btnAdvancedOptions = null!;
    private Label lblBranch = null!;
    private ComboBox fieldBranch = null!;
    private Label lblRequestNumber = null!;
    private TextBox fieldRequestNumber = null!;
    private Label lblApproval = null!;
    private ComboBox fieldApproval = null!;
    private Label lblType = null!;
    private ComboBox fieldType = null!;
    private Label lblRequestDate = null!;
    private TextBox fieldRequestDate = null!;
    private Label lblCostCenter = null!;
    private ComboBox fieldCostCenter = null!;
    private Label lblDepartment = null!;
    private ComboBox fieldDepartment = null!;
    private Label lblRequestOrigin = null!;
    private TextBox fieldRequestOrigin = null!;
    private Label lblSourceNumber = null!;
    private TextBox fieldSourceNumber = null!;
    private Label lblUnitLevel = null!;
    private ComboBox fieldUnitLevel = null!;
    private Label lblDownloadSource = null!;
    private ComboBox fieldDownloadSource = null!;
    private Label lblReference = null!;
    private TextBox fieldReference = null!;
    private Label lblRequiredDate = null!;
    private TextBox fieldRequiredDate = null!;
    private Label lblDescription = null!;
    private TextBox fieldDescription = null!;
    private Label lblCurrency = null!;
    private ComboBox fieldCurrency = null!;
    private Label lblSupplierNumber = null!;
    private TextBox fieldSupplierNumber = null!;
    private Label lblSupplierName = null!;
    private TextBox fieldSupplierName = null!;
    private DataGridViewTextBoxColumn colSequence = null!;
    private DataGridViewTextBoxColumn colItemNumber = null!;
    private DataGridViewTextBoxColumn colItemName = null!;
    private DataGridViewTextBoxColumn colUnit = null!;
    private DataGridViewTextBoxColumn colWarehouse = null!;
    private DataGridViewTextBoxColumn colExpiryDate = null!;
    private DataGridViewTextBoxColumn colAvailableQuantity = null!;
    private DataGridViewTextBoxColumn colRequestedQuantity = null!;
    private DataGridViewTextBoxColumn colExpectedDeliveryDate = null!;
    private DataGridViewTextBoxColumn colWarehouseAvailableQuantity = null!;
    private DataGridViewTextBoxColumn colInTransitQuantity = null!;
    private DataGridViewTextBoxColumn colFulfilledRequestQuantity = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        headerLayout = new TableLayoutPanel();
        headerLayout.Name = "headerLayout";
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        gridItems = new DataGridView();
        gridItems.Name = "gridItems";
        colLookup = new DataGridViewButtonColumn();
        colLookup.Name = "colLookup";
        auditFooter = new Panel();
        auditFooter.Name = "auditFooter";
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        lblOperationStatus = new Label();
        lblOperationStatus.Name = "lblOperationStatus";
        chkUsed = new CheckBox();
        chkUsed.Name = "chkUsed";
        chkStopped = new CheckBox();
        chkStopped.Name = "chkStopped";
        chkAutoSynchronization = new CheckBox();
        chkAutoSynchronization.Name = "chkAutoSynchronization";
        btnAutomaticRequest = new Button();
        btnAutomaticRequest.Name = "btnAutomaticRequest";
        btnAdvancedOptions = new Button();
        btnAdvancedOptions.Name = "btnAdvancedOptions";
        lblBranch = new Label();
        lblBranch.Name = "lblBranch";
        fieldBranch = new ComboBox();
        fieldBranch.Name = "fieldBranch";
        lblRequestNumber = new Label();
        lblRequestNumber.Name = "lblRequestNumber";
        fieldRequestNumber = new TextBox();
        fieldRequestNumber.Name = "fieldRequestNumber";
        lblApproval = new Label();
        lblApproval.Name = "lblApproval";
        fieldApproval = new ComboBox();
        fieldApproval.Name = "fieldApproval";
        lblType = new Label();
        lblType.Name = "lblType";
        fieldType = new ComboBox();
        fieldType.Name = "fieldType";
        lblRequestDate = new Label();
        lblRequestDate.Name = "lblRequestDate";
        fieldRequestDate = new TextBox();
        fieldRequestDate.Name = "fieldRequestDate";
        lblCostCenter = new Label();
        lblCostCenter.Name = "lblCostCenter";
        fieldCostCenter = new ComboBox();
        fieldCostCenter.Name = "fieldCostCenter";
        lblDepartment = new Label();
        lblDepartment.Name = "lblDepartment";
        fieldDepartment = new ComboBox();
        fieldDepartment.Name = "fieldDepartment";
        lblRequestOrigin = new Label();
        lblRequestOrigin.Name = "lblRequestOrigin";
        fieldRequestOrigin = new TextBox();
        fieldRequestOrigin.Name = "fieldRequestOrigin";
        lblSourceNumber = new Label();
        lblSourceNumber.Name = "lblSourceNumber";
        fieldSourceNumber = new TextBox();
        fieldSourceNumber.Name = "fieldSourceNumber";
        lblUnitLevel = new Label();
        lblUnitLevel.Name = "lblUnitLevel";
        fieldUnitLevel = new ComboBox();
        fieldUnitLevel.Name = "fieldUnitLevel";
        lblDownloadSource = new Label();
        lblDownloadSource.Name = "lblDownloadSource";
        fieldDownloadSource = new ComboBox();
        fieldDownloadSource.Name = "fieldDownloadSource";
        lblReference = new Label();
        lblReference.Name = "lblReference";
        fieldReference = new TextBox();
        fieldReference.Name = "fieldReference";
        lblRequiredDate = new Label();
        lblRequiredDate.Name = "lblRequiredDate";
        fieldRequiredDate = new TextBox();
        fieldRequiredDate.Name = "fieldRequiredDate";
        lblDescription = new Label();
        lblDescription.Name = "lblDescription";
        fieldDescription = new TextBox();
        fieldDescription.Name = "fieldDescription";
        lblCurrency = new Label();
        lblCurrency.Name = "lblCurrency";
        fieldCurrency = new ComboBox();
        fieldCurrency.Name = "fieldCurrency";
        lblSupplierNumber = new Label();
        lblSupplierNumber.Name = "lblSupplierNumber";
        fieldSupplierNumber = new TextBox();
        fieldSupplierNumber.Name = "fieldSupplierNumber";
        lblSupplierName = new Label();
        lblSupplierName.Name = "lblSupplierName";
        fieldSupplierName = new TextBox();
        fieldSupplierName.Name = "fieldSupplierName";
        colSequence = new DataGridViewTextBoxColumn();
        colSequence.Name = "colSequence";
        colItemNumber = new DataGridViewTextBoxColumn();
        colItemNumber.Name = "colItemNumber";
        colItemName = new DataGridViewTextBoxColumn();
        colItemName.Name = "colItemName";
        colUnit = new DataGridViewTextBoxColumn();
        colUnit.Name = "colUnit";
        colWarehouse = new DataGridViewTextBoxColumn();
        colWarehouse.Name = "colWarehouse";
        colExpiryDate = new DataGridViewTextBoxColumn();
        colExpiryDate.Name = "colExpiryDate";
        colAvailableQuantity = new DataGridViewTextBoxColumn();
        colAvailableQuantity.Name = "colAvailableQuantity";
        colRequestedQuantity = new DataGridViewTextBoxColumn();
        colRequestedQuantity.Name = "colRequestedQuantity";
        colExpectedDeliveryDate = new DataGridViewTextBoxColumn();
        colExpectedDeliveryDate.Name = "colExpectedDeliveryDate";
        colWarehouseAvailableQuantity = new DataGridViewTextBoxColumn();
        colWarehouseAvailableQuantity.Name = "colWarehouseAvailableQuantity";
        colInTransitQuantity = new DataGridViewTextBoxColumn();
        colInTransitQuantity.Name = "colInTransitQuantity";
        colFulfilledRequestQuantity = new DataGridViewTextBoxColumn();
        colFulfilledRequestQuantity.Name = "colFulfilledRequestQuantity";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = Padding.Empty;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 6;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 250F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        lblTitle.Text = "طلبات الشراء";
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.BackColor = Color.FromArgb(23, 50, 78);
        lblTitle.ForeColor = Color.White;
        commandBar.Dock = DockStyle.Fill;
        commandBar.Margin = Padding.Empty;
        headerLayout.Dock = DockStyle.Fill;
        headerLayout.Margin = Padding.Empty;
        headerLayout.Padding = new Padding(12, 5, 12, 5);
        headerLayout.ColumnCount = 6;
        headerLayout.RowCount = 8;
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 112F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 112F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 112F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        lblBranch.Text = "رقم الفرع";
        lblBranch.Dock = DockStyle.Fill;
        lblBranch.TextAlign = ContentAlignment.MiddleLeft;
        fieldBranch.AccessibleName = "رقم الفرع";
        fieldBranch.Dock = DockStyle.Fill;
        fieldBranch.TabStop = false;
        fieldBranch.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldBranch.Enabled = false;
        headerLayout.Controls.Add(lblBranch, 0, 0);
        headerLayout.Controls.Add(fieldBranch, 1, 0);
        lblRequestNumber.Text = "رقم الطلب";
        lblRequestNumber.Dock = DockStyle.Fill;
        lblRequestNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldRequestNumber.AccessibleName = "رقم الطلب";
        fieldRequestNumber.Dock = DockStyle.Fill;
        fieldRequestNumber.TabStop = false;
        fieldRequestNumber.ReadOnly = true;
        headerLayout.Controls.Add(lblRequestNumber, 2, 0);
        headerLayout.Controls.Add(fieldRequestNumber, 3, 0);
        lblApproval.Text = "حالة الاعتماد";
        lblApproval.Dock = DockStyle.Fill;
        lblApproval.TextAlign = ContentAlignment.MiddleLeft;
        fieldApproval.AccessibleName = "حالة الاعتماد";
        fieldApproval.Dock = DockStyle.Fill;
        fieldApproval.TabStop = false;
        fieldApproval.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldApproval.Enabled = false;
        headerLayout.Controls.Add(lblApproval, 4, 0);
        headerLayout.Controls.Add(fieldApproval, 5, 0);
        lblType.Text = "النوع";
        lblType.Dock = DockStyle.Fill;
        lblType.TextAlign = ContentAlignment.MiddleLeft;
        fieldType.AccessibleName = "النوع";
        fieldType.Dock = DockStyle.Fill;
        fieldType.TabStop = false;
        fieldType.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldType.Enabled = false;
        headerLayout.Controls.Add(lblType, 0, 1);
        headerLayout.Controls.Add(fieldType, 1, 1);
        lblRequestDate.Text = "تاريخ الطلب";
        lblRequestDate.Dock = DockStyle.Fill;
        lblRequestDate.TextAlign = ContentAlignment.MiddleLeft;
        fieldRequestDate.AccessibleName = "تاريخ الطلب";
        fieldRequestDate.Dock = DockStyle.Fill;
        fieldRequestDate.TabStop = false;
        fieldRequestDate.ReadOnly = true;
        headerLayout.Controls.Add(lblRequestDate, 4, 1);
        headerLayout.Controls.Add(fieldRequestDate, 5, 1);
        lblCostCenter.Text = "مركز التكلفة";
        lblCostCenter.Dock = DockStyle.Fill;
        lblCostCenter.TextAlign = ContentAlignment.MiddleLeft;
        fieldCostCenter.AccessibleName = "مركز التكلفة";
        fieldCostCenter.Dock = DockStyle.Fill;
        fieldCostCenter.TabStop = false;
        fieldCostCenter.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldCostCenter.Enabled = false;
        headerLayout.Controls.Add(lblCostCenter, 0, 2);
        headerLayout.Controls.Add(fieldCostCenter, 1, 2);
        lblDepartment.Text = "الإدارة";
        lblDepartment.Dock = DockStyle.Fill;
        lblDepartment.TextAlign = ContentAlignment.MiddleLeft;
        fieldDepartment.AccessibleName = "الإدارة";
        fieldDepartment.Dock = DockStyle.Fill;
        fieldDepartment.TabStop = false;
        fieldDepartment.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldDepartment.Enabled = false;
        headerLayout.Controls.Add(lblDepartment, 4, 2);
        headerLayout.Controls.Add(fieldDepartment, 5, 2);
        lblRequestOrigin.Text = "جهة الطلب";
        lblRequestOrigin.Dock = DockStyle.Fill;
        lblRequestOrigin.TextAlign = ContentAlignment.MiddleLeft;
        fieldRequestOrigin.AccessibleName = "جهة الطلب";
        fieldRequestOrigin.Dock = DockStyle.Fill;
        fieldRequestOrigin.TabStop = false;
        fieldRequestOrigin.ReadOnly = true;
        headerLayout.Controls.Add(lblRequestOrigin, 0, 3);
        headerLayout.Controls.Add(fieldRequestOrigin, 1, 3);
        lblSourceNumber.Text = "الرقم";
        lblSourceNumber.Dock = DockStyle.Fill;
        lblSourceNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldSourceNumber.AccessibleName = "الرقم";
        fieldSourceNumber.Dock = DockStyle.Fill;
        fieldSourceNumber.TabStop = false;
        fieldSourceNumber.ReadOnly = true;
        headerLayout.Controls.Add(lblSourceNumber, 2, 3);
        headerLayout.Controls.Add(fieldSourceNumber, 3, 3);
        lblUnitLevel.Text = "مستوى الوحدة";
        lblUnitLevel.Dock = DockStyle.Fill;
        lblUnitLevel.TextAlign = ContentAlignment.MiddleLeft;
        fieldUnitLevel.AccessibleName = "مستوى الوحدة";
        fieldUnitLevel.Dock = DockStyle.Fill;
        fieldUnitLevel.TabStop = false;
        fieldUnitLevel.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldUnitLevel.Enabled = false;
        headerLayout.Controls.Add(lblUnitLevel, 4, 3);
        headerLayout.Controls.Add(fieldUnitLevel, 5, 3);
        lblDownloadSource.Text = "إنزال البيانات من";
        lblDownloadSource.Dock = DockStyle.Fill;
        lblDownloadSource.TextAlign = ContentAlignment.MiddleLeft;
        fieldDownloadSource.AccessibleName = "إنزال البيانات من";
        fieldDownloadSource.Dock = DockStyle.Fill;
        fieldDownloadSource.TabStop = false;
        fieldDownloadSource.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldDownloadSource.Enabled = false;
        headerLayout.Controls.Add(lblDownloadSource, 0, 4);
        headerLayout.Controls.Add(fieldDownloadSource, 1, 4);
        lblReference.Text = "رقم المرجع";
        lblReference.Dock = DockStyle.Fill;
        lblReference.TextAlign = ContentAlignment.MiddleLeft;
        fieldReference.AccessibleName = "رقم المرجع";
        fieldReference.Dock = DockStyle.Fill;
        fieldReference.TabStop = false;
        fieldReference.ReadOnly = true;
        headerLayout.Controls.Add(lblReference, 2, 4);
        headerLayout.Controls.Add(fieldReference, 3, 4);
        lblRequiredDate.Text = "تاريخ توفير الطلب";
        lblRequiredDate.Dock = DockStyle.Fill;
        lblRequiredDate.TextAlign = ContentAlignment.MiddleLeft;
        fieldRequiredDate.AccessibleName = "تاريخ توفير الطلب";
        fieldRequiredDate.Dock = DockStyle.Fill;
        fieldRequiredDate.TabStop = false;
        fieldRequiredDate.ReadOnly = true;
        headerLayout.Controls.Add(lblRequiredDate, 4, 4);
        headerLayout.Controls.Add(fieldRequiredDate, 5, 4);
        lblDescription.Text = "البيان";
        lblDescription.Dock = DockStyle.Fill;
        lblDescription.TextAlign = ContentAlignment.MiddleLeft;
        fieldDescription.AccessibleName = "البيان";
        fieldDescription.Dock = DockStyle.Fill;
        fieldDescription.TabStop = false;
        fieldDescription.ReadOnly = true;
        headerLayout.Controls.Add(lblDescription, 0, 5);
        headerLayout.Controls.Add(fieldDescription, 1, 5);
        lblCurrency.Text = "العملة";
        lblCurrency.Dock = DockStyle.Fill;
        lblCurrency.TextAlign = ContentAlignment.MiddleLeft;
        fieldCurrency.AccessibleName = "العملة";
        fieldCurrency.Dock = DockStyle.Fill;
        fieldCurrency.TabStop = false;
        fieldCurrency.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldCurrency.Enabled = false;
        headerLayout.Controls.Add(lblCurrency, 2, 5);
        headerLayout.Controls.Add(fieldCurrency, 3, 5);
        lblSupplierNumber.Text = "رقم المورد";
        lblSupplierNumber.Dock = DockStyle.Fill;
        lblSupplierNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldSupplierNumber.AccessibleName = "رقم المورد";
        fieldSupplierNumber.Dock = DockStyle.Fill;
        fieldSupplierNumber.TabStop = false;
        fieldSupplierNumber.ReadOnly = true;
        headerLayout.Controls.Add(lblSupplierNumber, 0, 6);
        headerLayout.Controls.Add(fieldSupplierNumber, 1, 6);
        lblSupplierName.Text = "اسم المورد";
        lblSupplierName.Dock = DockStyle.Fill;
        lblSupplierName.TextAlign = ContentAlignment.MiddleLeft;
        fieldSupplierName.AccessibleName = "اسم المورد";
        fieldSupplierName.Dock = DockStyle.Fill;
        fieldSupplierName.TabStop = false;
        fieldSupplierName.ReadOnly = true;
        headerLayout.Controls.Add(lblSupplierName, 2, 6);
        headerLayout.Controls.Add(fieldSupplierName, 3, 6);
        chkUsed.Text = "مستخدم";
        chkUsed.Dock = DockStyle.Fill;
        chkUsed.Enabled = false;
        headerLayout.Controls.Add(chkUsed, 2, 1);
        chkStopped.Text = "موقف";
        chkStopped.Dock = DockStyle.Fill;
        chkStopped.Enabled = false;
        headerLayout.Controls.Add(chkStopped, 3, 1);
        chkAutoSynchronization.Text = "استخدام المزامنة الآلية بين العميل والمورد";
        chkAutoSynchronization.Dock = DockStyle.Fill;
        chkAutoSynchronization.Enabled = false;
        headerLayout.Controls.Add(chkAutoSynchronization, 2, 7);
        headerLayout.SetColumnSpan(chkAutoSynchronization, 4);
        btnAutomaticRequest.Text = "طلب شراء آلي";
        btnAutomaticRequest.Dock = DockStyle.Fill;
        btnAutomaticRequest.Enabled = false;
        headerLayout.Controls.Add(btnAutomaticRequest, 0, 7);
        headerLayout.SetColumnSpan(btnAutomaticRequest, 2);
        btnAdvancedOptions.Text = "خيارات متقدمة";
        btnAdvancedOptions.Dock = DockStyle.Fill;
        btnAdvancedOptions.Enabled = false;
        headerLayout.Controls.Add(btnAdvancedOptions, 2, 2);
        headerLayout.SetColumnSpan(btnAdvancedOptions, 2);
        gridItems.Dock = DockStyle.Fill;
        gridItems.AutoGenerateColumns = false;
        gridItems.ReadOnly = true;
        gridItems.AllowUserToAddRows = false;
        gridItems.AllowUserToDeleteRows = false;
        gridItems.AllowUserToOrderColumns = false;
        gridItems.RowHeadersVisible = false;
        gridItems.BackgroundColor = Color.White;
        gridItems.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        gridItems.ColumnHeadersHeight = 50;
        gridItems.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridItems.AccessibleName = "أصناف طلب الشراء";
        colLookup.HeaderText = "";
        colLookup.Text = "...";
        colLookup.UseColumnTextForButtonValue = true;
        colLookup.Width = 25;
        colLookup.MinimumWidth = 25;
        colLookup.AutoSizeMode = DataGridViewAutoSizeColumnMode.None;
        colLookup.ReadOnly = true;
        gridItems.Columns.Add(colLookup);
        colSequence.Name = "Sequence";
        colSequence.HeaderText = "م";
        colSequence.Width = 35;
        colSequence.MinimumWidth = 35;
        colSequence.ReadOnly = true;
        colSequence.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.Add(colSequence);
        colItemNumber.Name = "ItemNumber";
        colItemNumber.HeaderText = "رقم الصنف";
        colItemNumber.Width = 110;
        colItemNumber.MinimumWidth = 60;
        colItemNumber.ReadOnly = true;
        colItemNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.Add(colItemNumber);
        colItemName.Name = "ItemName";
        colItemName.HeaderText = "اسم الصنف";
        colItemName.Width = 190;
        colItemName.MinimumWidth = 60;
        colItemName.ReadOnly = true;
        colItemName.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.Add(colItemName);
        colUnit.Name = "Unit";
        colUnit.HeaderText = "الوحدة";
        colUnit.Width = 60;
        colUnit.MinimumWidth = 60;
        colUnit.ReadOnly = true;
        colUnit.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.Add(colUnit);
        colWarehouse.Name = "Warehouse";
        colWarehouse.HeaderText = "المخزن";
        colWarehouse.Width = 65;
        colWarehouse.MinimumWidth = 60;
        colWarehouse.ReadOnly = true;
        colWarehouse.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.Add(colWarehouse);
        colExpiryDate.Name = "ExpiryDate";
        colExpiryDate.HeaderText = "تاريخ الانتهاء";
        colExpiryDate.Width = 100;
        colExpiryDate.MinimumWidth = 60;
        colExpiryDate.ReadOnly = true;
        colExpiryDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.Add(colExpiryDate);
        colAvailableQuantity.Name = "AvailableQuantity";
        colAvailableQuantity.HeaderText = "الكمية المتوفرة";
        colAvailableQuantity.Width = 90;
        colAvailableQuantity.MinimumWidth = 60;
        colAvailableQuantity.ReadOnly = true;
        colAvailableQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.Add(colAvailableQuantity);
        colRequestedQuantity.Name = "RequestedQuantity";
        colRequestedQuantity.HeaderText = "الكمية المطلوبة";
        colRequestedQuantity.Width = 90;
        colRequestedQuantity.MinimumWidth = 60;
        colRequestedQuantity.ReadOnly = true;
        colRequestedQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.Add(colRequestedQuantity);
        colExpectedDeliveryDate.Name = "ExpectedDeliveryDate";
        colExpectedDeliveryDate.HeaderText = "تاريخ التسليم المتوقع";
        colExpectedDeliveryDate.Width = 110;
        colExpectedDeliveryDate.MinimumWidth = 60;
        colExpectedDeliveryDate.ReadOnly = true;
        colExpectedDeliveryDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.Add(colExpectedDeliveryDate);
        colWarehouseAvailableQuantity.Name = "WarehouseAvailableQuantity";
        colWarehouseAvailableQuantity.HeaderText = "الكمية المتوفرة للمخزن";
        colWarehouseAvailableQuantity.Width = 120;
        colWarehouseAvailableQuantity.MinimumWidth = 60;
        colWarehouseAvailableQuantity.ReadOnly = true;
        colWarehouseAvailableQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.Add(colWarehouseAvailableQuantity);
        colInTransitQuantity.Name = "InTransitQuantity";
        colInTransitQuantity.HeaderText = "الكمية في الطريق";
        colInTransitQuantity.Width = 100;
        colInTransitQuantity.MinimumWidth = 60;
        colInTransitQuantity.ReadOnly = true;
        colInTransitQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.Add(colInTransitQuantity);
        colFulfilledRequestQuantity.Name = "FulfilledRequestQuantity";
        colFulfilledRequestQuantity.HeaderText = "ك. الطلب المنفذة";
        colFulfilledRequestQuantity.Width = 100;
        colFulfilledRequestQuantity.MinimumWidth = 60;
        colFulfilledRequestQuantity.ReadOnly = true;
        colFulfilledRequestQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.Add(colFulfilledRequestQuantity);
        auditFooter.Dock = DockStyle.Fill;
        auditFooter.Margin = Padding.Empty;
        standardAuditMetadata.Dock = DockStyle.Fill;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.Profile = AuditMetadataProfile.Standard;
        auditFooter.Controls.Add(standardAuditMetadata);
        lblOperationStatus.Text = "الحفظ والطلب الآلي واختيار الأصناف وخيارات الإنزال غير متاحة حاليًا.";
        lblOperationStatus.Dock = DockStyle.Fill;
        lblOperationStatus.TextAlign = ContentAlignment.MiddleLeft;
        mainLayout.Controls.Add(lblTitle, 0, 0);
        mainLayout.Controls.Add(commandBar, 0, 1);
        mainLayout.Controls.Add(headerLayout, 0, 2);
        mainLayout.Controls.Add(gridItems, 0, 3);
        mainLayout.Controls.Add(auditFooter, 0, 4);
        mainLayout.Controls.Add(lblOperationStatus, 0, 5);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 9F);
        RightToLeft = RightToLeft.Yes;
        Name = "UcPurchaseRequest";
        Text = "طلبات الشراء";
        Tag = "PUR:REQUEST";
        Size = new Size(1180, 720);
        MinimumSize = new Size(1000, 600);
        Controls.Add(mainLayout);
        ResumeLayout(false);
    }
}

