using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcPurchaseComparisonNomination
{
    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private TabControl tabs = null!;
    private TabPage tabMain = null!;
    private TableLayoutPanel documentLayout = null!;
    private TableLayoutPanel headerLayout = null!;
    private FlowLayoutPanel actionsLayout = null!;
    private CheckBox chkUsed = null!;
    private Button btnQuotationLookup = null!;
    private DataGridView gridItems = null!;
    private Panel auditFooter = null!;
    private AuditMetadataControl standardAuditMetadata = null!;
    private Label lblBranch = null!;
    private ComboBox fieldBranch = null!;
    private Label lblDocumentNumber = null!;
    private TextBox fieldDocumentNumber = null!;
    private Label lblDate = null!;
    private TextBox fieldDate = null!;
    private Label lblCurrency = null!;
    private ComboBox fieldCurrency = null!;
    private Label lblComparisonType = null!;
    private ComboBox fieldComparisonType = null!;
    private Label lblLoadFrom = null!;
    private ComboBox fieldLoadFrom = null!;
    private Label lblNumber = null!;
    private TextBox fieldNumber = null!;
    private Label lblReference = null!;
    private TextBox fieldReference = null!;
    private Label lblDescription = null!;
    private TextBox fieldDescription = null!;
    private Label lblCostCenter = null!;
    private ComboBox fieldCostCenter = null!;
    private Label lblApprovalState = null!;
    private ComboBox fieldApprovalState = null!;
    private Label lblPaymentMethod = null!;
    private ComboBox fieldPaymentMethod = null!;
    private Label lblCreditPeriod = null!;
    private TextBox fieldCreditPeriod = null!;
    private Label lblDeliveryDays = null!;
    private TextBox fieldDeliveryDays = null!;
    private DataGridViewTextBoxColumn colSequence = null!;
    private DataGridViewTextBoxColumn colItemNumber = null!;
    private DataGridViewTextBoxColumn colItemName = null!;
    private DataGridViewTextBoxColumn colUnit = null!;
    private DataGridViewTextBoxColumn colQuantity = null!;
    private DataGridViewTextBoxColumn colPrice = null!;
    private DataGridViewTextBoxColumn colDiscountPercent = null!;
    private DataGridViewTextBoxColumn colDiscount = null!;
    private DataGridViewTextBoxColumn colNet = null!;
    private DataGridViewCheckBoxColumn colApproved = null!;
    private DataGridViewTextBoxColumn colSupplierNumber = null!;
    private DataGridViewTextBoxColumn colSupplierName = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        tabs = new TabControl();
        tabs.Name = "tabs";
        tabMain = new TabPage();
        tabMain.Name = "tabMain";
        documentLayout = new TableLayoutPanel();
        documentLayout.Name = "documentLayout";
        headerLayout = new TableLayoutPanel();
        headerLayout.Name = "headerLayout";
        actionsLayout = new FlowLayoutPanel();
        actionsLayout.Name = "actionsLayout";
        chkUsed = new CheckBox();
        chkUsed.Name = "chkUsed";
        btnQuotationLookup = new Button();
        btnQuotationLookup.Name = "btnQuotationLookup";
        gridItems = new DataGridView();
        gridItems.Name = "gridItems";
        auditFooter = new Panel();
        auditFooter.Name = "auditFooter";
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        lblBranch = new Label();
        lblBranch.Name = "lblBranch";
        fieldBranch = new ComboBox();
        fieldBranch.Name = "fieldBranch";
        lblDocumentNumber = new Label();
        lblDocumentNumber.Name = "lblDocumentNumber";
        fieldDocumentNumber = new TextBox();
        fieldDocumentNumber.Name = "fieldDocumentNumber";
        lblDate = new Label();
        lblDate.Name = "lblDate";
        fieldDate = new TextBox();
        fieldDate.Name = "fieldDate";
        lblCurrency = new Label();
        lblCurrency.Name = "lblCurrency";
        fieldCurrency = new ComboBox();
        fieldCurrency.Name = "fieldCurrency";
        lblComparisonType = new Label();
        lblComparisonType.Name = "lblComparisonType";
        fieldComparisonType = new ComboBox();
        fieldComparisonType.Name = "fieldComparisonType";
        lblLoadFrom = new Label();
        lblLoadFrom.Name = "lblLoadFrom";
        fieldLoadFrom = new ComboBox();
        fieldLoadFrom.Name = "fieldLoadFrom";
        lblNumber = new Label();
        lblNumber.Name = "lblNumber";
        fieldNumber = new TextBox();
        fieldNumber.Name = "fieldNumber";
        lblReference = new Label();
        lblReference.Name = "lblReference";
        fieldReference = new TextBox();
        fieldReference.Name = "fieldReference";
        lblDescription = new Label();
        lblDescription.Name = "lblDescription";
        fieldDescription = new TextBox();
        fieldDescription.Name = "fieldDescription";
        lblCostCenter = new Label();
        lblCostCenter.Name = "lblCostCenter";
        fieldCostCenter = new ComboBox();
        fieldCostCenter.Name = "fieldCostCenter";
        lblApprovalState = new Label();
        lblApprovalState.Name = "lblApprovalState";
        fieldApprovalState = new ComboBox();
        fieldApprovalState.Name = "fieldApprovalState";
        lblPaymentMethod = new Label();
        lblPaymentMethod.Name = "lblPaymentMethod";
        fieldPaymentMethod = new ComboBox();
        fieldPaymentMethod.Name = "fieldPaymentMethod";
        lblCreditPeriod = new Label();
        lblCreditPeriod.Name = "lblCreditPeriod";
        fieldCreditPeriod = new TextBox();
        fieldCreditPeriod.Name = "fieldCreditPeriod";
        lblDeliveryDays = new Label();
        lblDeliveryDays.Name = "lblDeliveryDays";
        fieldDeliveryDays = new TextBox();
        fieldDeliveryDays.Name = "fieldDeliveryDays";
        colSequence = new DataGridViewTextBoxColumn();
        colSequence.Name = "colSequence";
        colItemNumber = new DataGridViewTextBoxColumn();
        colItemNumber.Name = "colItemNumber";
        colItemName = new DataGridViewTextBoxColumn();
        colItemName.Name = "colItemName";
        colUnit = new DataGridViewTextBoxColumn();
        colUnit.Name = "colUnit";
        colQuantity = new DataGridViewTextBoxColumn();
        colQuantity.Name = "colQuantity";
        colPrice = new DataGridViewTextBoxColumn();
        colPrice.Name = "colPrice";
        colDiscountPercent = new DataGridViewTextBoxColumn();
        colDiscountPercent.Name = "colDiscountPercent";
        colDiscount = new DataGridViewTextBoxColumn();
        colDiscount.Name = "colDiscount";
        colNet = new DataGridViewTextBoxColumn();
        colNet.Name = "colNet";
        colApproved = new DataGridViewCheckBoxColumn();
        colApproved.Name = "colApproved";
        colSupplierNumber = new DataGridViewTextBoxColumn();
        colSupplierNumber.Name = "colSupplierNumber";
        colSupplierName = new DataGridViewTextBoxColumn();
        colSupplierName.Name = "colSupplierName";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = Padding.Empty;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.BackColor = Color.FromArgb(23, 50, 78);
        lblTitle.ForeColor = Color.White;
        commandBar.Dock = DockStyle.Fill;
        commandBar.Margin = Padding.Empty;
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeftLayout = true;
        tabMain.Text = "البيانات الرئيسية";
        tabMain.Padding = Padding.Empty;
        tabs.Controls.Add(tabMain);
        documentLayout.Dock = DockStyle.Fill;
        documentLayout.ColumnCount = 1;
        documentLayout.RowCount = 3;
        documentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 172F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        documentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tabMain.Controls.Add(documentLayout);
        headerLayout.Dock = DockStyle.Fill;
        headerLayout.Padding = new Padding(10, 6, 10, 6);
        headerLayout.Margin = Padding.Empty;
        headerLayout.ColumnCount = 6;
        headerLayout.RowCount = 5;
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 145F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 145F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 145F));
        headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        lblBranch.Text = "رقم الفرع";
        lblBranch.Dock = DockStyle.Fill;
        lblBranch.TextAlign = ContentAlignment.MiddleLeft;
        fieldBranch.AccessibleName = "رقم الفرع";
        fieldBranch.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblBranch, 0, 0);
        headerLayout.Controls.Add(fieldBranch, 1, 0);
        fieldBranch.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldBranch.Enabled = false;
        lblDocumentNumber.Text = "رقم الوثيقة";
        lblDocumentNumber.Dock = DockStyle.Fill;
        lblDocumentNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldDocumentNumber.AccessibleName = "رقم الوثيقة";
        fieldDocumentNumber.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDocumentNumber, 2, 0);
        headerLayout.Controls.Add(fieldDocumentNumber, 3, 0);
        fieldDocumentNumber.ReadOnly = true;
        lblDate.Text = "التاريخ";
        lblDate.Dock = DockStyle.Fill;
        lblDate.TextAlign = ContentAlignment.MiddleLeft;
        fieldDate.AccessibleName = "التاريخ";
        fieldDate.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDate, 4, 0);
        headerLayout.Controls.Add(fieldDate, 5, 0);
        fieldDate.ReadOnly = true;
        lblCurrency.Text = "العملة";
        lblCurrency.Dock = DockStyle.Fill;
        lblCurrency.TextAlign = ContentAlignment.MiddleLeft;
        fieldCurrency.AccessibleName = "العملة";
        fieldCurrency.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblCurrency, 0, 1);
        headerLayout.Controls.Add(fieldCurrency, 1, 1);
        fieldCurrency.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldCurrency.Enabled = false;
        lblComparisonType.Text = "نوع المقارنة";
        lblComparisonType.Dock = DockStyle.Fill;
        lblComparisonType.TextAlign = ContentAlignment.MiddleLeft;
        fieldComparisonType.AccessibleName = "نوع المقارنة";
        fieldComparisonType.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblComparisonType, 2, 1);
        headerLayout.Controls.Add(fieldComparisonType, 3, 1);
        fieldComparisonType.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldComparisonType.Enabled = false;
        lblLoadFrom.Text = "إنزال البيانات من";
        lblLoadFrom.Dock = DockStyle.Fill;
        lblLoadFrom.TextAlign = ContentAlignment.MiddleLeft;
        fieldLoadFrom.AccessibleName = "إنزال البيانات من";
        fieldLoadFrom.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblLoadFrom, 4, 1);
        headerLayout.Controls.Add(fieldLoadFrom, 5, 1);
        fieldLoadFrom.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldLoadFrom.Enabled = false;
        lblNumber.Text = "الرقم";
        lblNumber.Dock = DockStyle.Fill;
        lblNumber.TextAlign = ContentAlignment.MiddleLeft;
        fieldNumber.AccessibleName = "الرقم";
        fieldNumber.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblNumber, 0, 2);
        headerLayout.Controls.Add(fieldNumber, 1, 2);
        fieldNumber.ReadOnly = true;
        lblReference.Text = "رقم المرجع";
        lblReference.Dock = DockStyle.Fill;
        lblReference.TextAlign = ContentAlignment.MiddleLeft;
        fieldReference.AccessibleName = "رقم المرجع";
        fieldReference.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblReference, 2, 2);
        headerLayout.Controls.Add(fieldReference, 3, 2);
        fieldReference.ReadOnly = true;
        lblDescription.Text = "البيان";
        lblDescription.Dock = DockStyle.Fill;
        lblDescription.TextAlign = ContentAlignment.MiddleLeft;
        fieldDescription.AccessibleName = "البيان";
        fieldDescription.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDescription, 4, 2);
        headerLayout.Controls.Add(fieldDescription, 5, 2);
        fieldDescription.ReadOnly = true;
        lblCostCenter.Text = "رقم المركز";
        lblCostCenter.Dock = DockStyle.Fill;
        lblCostCenter.TextAlign = ContentAlignment.MiddleLeft;
        fieldCostCenter.AccessibleName = "رقم المركز";
        fieldCostCenter.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblCostCenter, 0, 3);
        headerLayout.Controls.Add(fieldCostCenter, 1, 3);
        fieldCostCenter.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldCostCenter.Enabled = false;
        lblApprovalState.Text = "حالة الاعتماد";
        lblApprovalState.Dock = DockStyle.Fill;
        lblApprovalState.TextAlign = ContentAlignment.MiddleLeft;
        fieldApprovalState.AccessibleName = "حالة الاعتماد";
        fieldApprovalState.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblApprovalState, 2, 3);
        headerLayout.Controls.Add(fieldApprovalState, 3, 3);
        fieldApprovalState.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldApprovalState.Enabled = false;
        lblPaymentMethod.Text = "طريقة الدفع";
        lblPaymentMethod.Dock = DockStyle.Fill;
        lblPaymentMethod.TextAlign = ContentAlignment.MiddleLeft;
        fieldPaymentMethod.AccessibleName = "طريقة الدفع";
        fieldPaymentMethod.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblPaymentMethod, 4, 3);
        headerLayout.Controls.Add(fieldPaymentMethod, 5, 3);
        fieldPaymentMethod.DropDownStyle = ComboBoxStyle.DropDownList;
        fieldPaymentMethod.Enabled = false;
        lblCreditPeriod.Text = "فترة الائتمان";
        lblCreditPeriod.Dock = DockStyle.Fill;
        lblCreditPeriod.TextAlign = ContentAlignment.MiddleLeft;
        fieldCreditPeriod.AccessibleName = "فترة الائتمان";
        fieldCreditPeriod.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblCreditPeriod, 0, 4);
        headerLayout.Controls.Add(fieldCreditPeriod, 1, 4);
        fieldCreditPeriod.ReadOnly = true;
        lblDeliveryDays.Text = "مدة التسليم بالأيام";
        lblDeliveryDays.Dock = DockStyle.Fill;
        lblDeliveryDays.TextAlign = ContentAlignment.MiddleLeft;
        fieldDeliveryDays.AccessibleName = "مدة التسليم بالأيام";
        fieldDeliveryDays.Dock = DockStyle.Fill;
        headerLayout.Controls.Add(lblDeliveryDays, 2, 4);
        headerLayout.Controls.Add(fieldDeliveryDays, 3, 4);
        fieldDeliveryDays.ReadOnly = true;
        actionsLayout.Dock = DockStyle.Fill;
        actionsLayout.FlowDirection = FlowDirection.RightToLeft;
        actionsLayout.WrapContents = false;
        actionsLayout.Margin = Padding.Empty;
        chkUsed.Text = "مستخدم";
        chkUsed.AutoSize = true;
        chkUsed.Enabled = false;
        actionsLayout.Controls.Add(chkUsed);
        btnQuotationLookup.Text = "✓";
        btnQuotationLookup.AccessibleName = "عروض الأسعار";
        btnQuotationLookup.Enabled = false;
        btnQuotationLookup.AutoSize = true;
        btnQuotationLookup.Visible = false;
        fieldLoadFrom.Items.Add("المقارنة الفنية لعروض الشراء");
        fieldComparisonType.Items.Add("أقل سعر");
        fieldApprovalState.Items.Add("غير معتمد");
        gridItems.Dock = DockStyle.Fill;
        gridItems.AccessibleName = "ترشيح المقارنة الفنية لعروض الشراء";
        gridItems.ReadOnly = true;
        gridItems.AllowUserToAddRows = false;
        gridItems.AllowUserToDeleteRows = false;
        gridItems.AutoGenerateColumns = false;
        gridItems.RowHeadersVisible = false;
        gridItems.BackgroundColor = Color.White;
        gridItems.ColumnHeadersHeight = 34;
        gridItems.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridItems.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        colSequence.HeaderText = "م";
        colSequence.Width = 45;
        colSequence.ReadOnly = true;
        colSequence.SortMode = DataGridViewColumnSortMode.NotSortable;
        colItemNumber.HeaderText = "رقم الصنف";
        colItemNumber.Width = 140;
        colItemNumber.ReadOnly = true;
        colItemNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colItemName.HeaderText = "اسم الصنف";
        colItemName.Width = 250;
        colItemName.ReadOnly = true;
        colItemName.SortMode = DataGridViewColumnSortMode.NotSortable;
        colUnit.HeaderText = "الوحدة";
        colUnit.Width = 80;
        colUnit.ReadOnly = true;
        colUnit.SortMode = DataGridViewColumnSortMode.NotSortable;
        colQuantity.HeaderText = "الكمية";
        colQuantity.Width = 100;
        colQuantity.ReadOnly = true;
        colQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
        colPrice.HeaderText = "السعر";
        colPrice.Width = 100;
        colPrice.ReadOnly = true;
        colPrice.SortMode = DataGridViewColumnSortMode.NotSortable;
        colDiscountPercent.HeaderText = "الخصم%";
        colDiscountPercent.Width = 90;
        colDiscountPercent.ReadOnly = true;
        colDiscountPercent.SortMode = DataGridViewColumnSortMode.NotSortable;
        colDiscount.HeaderText = "الخصم";
        colDiscount.Width = 100;
        colDiscount.ReadOnly = true;
        colDiscount.SortMode = DataGridViewColumnSortMode.NotSortable;
        colNet.HeaderText = "الصافي";
        colNet.Width = 110;
        colNet.ReadOnly = true;
        colNet.SortMode = DataGridViewColumnSortMode.NotSortable;
        colApproved.HeaderText = "اعتماد";
        colApproved.Width = 65;
        colApproved.ReadOnly = true;
        colApproved.SortMode = DataGridViewColumnSortMode.NotSortable;
        colSupplierNumber.HeaderText = "رقم المورد";
        colSupplierNumber.Width = 115;
        colSupplierNumber.ReadOnly = true;
        colSupplierNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colSupplierName.HeaderText = "اسم المورد";
        colSupplierName.Width = 220;
        colSupplierName.ReadOnly = true;
        colSupplierName.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridItems.Columns.AddRange(new DataGridViewColumn[] { colSequence, colItemNumber, colItemName, colUnit, colQuantity, colPrice, colDiscountPercent, colDiscount, colNet, colApproved, colSupplierNumber, colSupplierName });
        documentLayout.Controls.Add(headerLayout, 0, 0);
        documentLayout.Controls.Add(actionsLayout, 0, 1);
        documentLayout.Controls.Add(gridItems, 0, 2);
        auditFooter.Dock = DockStyle.Fill;
        auditFooter.Margin = Padding.Empty;
        standardAuditMetadata.Dock = DockStyle.Fill;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.Profile = AuditMetadataProfile.Standard;
        auditFooter.Controls.Add(standardAuditMetadata);
        mainLayout.Controls.Add(lblTitle, 0, 0);
        mainLayout.Controls.Add(commandBar, 0, 1);
        mainLayout.Controls.Add(tabs, 0, 2);
        mainLayout.Controls.Add(auditFooter, 0, 3);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 9F);
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1180, 720);
        MinimumSize = new Size(1000, 600);
        Controls.Add(mainLayout);
        lblTitle.Text = "ترشيح المقارنة الفنية لعروض الشراء";
        Name = "UcPurchaseComparisonNomination";
        Text = "ترشيح المقارنة الفنية لعروض الشراء";
        Tag = "PUR:COMPARISON-NOMINATION";
        ResumeLayout(false);
    }
}
