using TransportERP.Desktop.CoreUI;
namespace TransportERP.EmptyForms;
partial class UcPurchaseQuotationSelector
{
    private TableLayoutPanel mainLayout = null!;
    private Label lblTitle = null!;
    private StandardCommandBar commandBar = null!;
    private TableLayoutPanel bodyLayout = null!;
    private TableLayoutPanel searchLayout = null!;
    private Label lblFind = null!;
    private TextBox fieldFind = null!;
    private DataGridView gridLookup = null!;
    private TableLayoutPanel actionsLayout = null!;
    private Button btnLoad = null!;
    private CheckBox chkAutomatic = null!;
    private TableLayoutPanel filtersLayout = null!;
    private TextBox fieldFilterQuotationNumber = null!;
    private TextBox fieldFilterQuotationDate = null!;
    private TextBox fieldFilterSupplierName = null!;
    private TextBox fieldFilterBranchNumber = null!;
    private TextBox fieldFilterDescription = null!;
    private Panel auditFooter = null!;
    private AuditMetadataControl standardAuditMetadata = null!;
    private DataGridViewCheckBoxColumn colSelected = null!;
    private DataGridViewTextBoxColumn colQuotationNumber = null!;
    private DataGridViewTextBoxColumn colQuotationDate = null!;
    private DataGridViewTextBoxColumn colSupplierName = null!;
    private DataGridViewTextBoxColumn colBranchNumber = null!;
    private DataGridViewTextBoxColumn colDescription = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        mainLayout = new TableLayoutPanel();
        mainLayout.Name = "mainLayout";
        lblTitle = new Label();
        lblTitle.Name = "lblTitle";
        commandBar = new StandardCommandBar();
        commandBar.Name = "commandBar";
        bodyLayout = new TableLayoutPanel();
        bodyLayout.Name = "bodyLayout";
        searchLayout = new TableLayoutPanel();
        searchLayout.Name = "searchLayout";
        lblFind = new Label();
        lblFind.Name = "lblFind";
        fieldFind = new TextBox();
        fieldFind.Name = "fieldFind";
        gridLookup = new DataGridView();
        gridLookup.Name = "gridLookup";
        actionsLayout = new TableLayoutPanel();
        actionsLayout.Name = "actionsLayout";
        btnLoad = new Button();
        btnLoad.Name = "btnLoad";
        chkAutomatic = new CheckBox();
        chkAutomatic.Name = "chkAutomatic";
        filtersLayout = new TableLayoutPanel();
        filtersLayout.Name = "filtersLayout";
        fieldFilterQuotationNumber = new TextBox();
        fieldFilterQuotationNumber.Name = "fieldFilterQuotationNumber";
        fieldFilterQuotationDate = new TextBox();
        fieldFilterQuotationDate.Name = "fieldFilterQuotationDate";
        fieldFilterSupplierName = new TextBox();
        fieldFilterSupplierName.Name = "fieldFilterSupplierName";
        fieldFilterBranchNumber = new TextBox();
        fieldFilterBranchNumber.Name = "fieldFilterBranchNumber";
        fieldFilterDescription = new TextBox();
        fieldFilterDescription.Name = "fieldFilterDescription";
        auditFooter = new Panel();
        auditFooter.Name = "auditFooter";
        standardAuditMetadata = new AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        colSelected = new DataGridViewCheckBoxColumn();
        colSelected.Name = "colSelected";
        colQuotationNumber = new DataGridViewTextBoxColumn();
        colQuotationNumber.Name = "colQuotationNumber";
        colQuotationDate = new DataGridViewTextBoxColumn();
        colQuotationDate.Name = "colQuotationDate";
        colSupplierName = new DataGridViewTextBoxColumn();
        colSupplierName.Name = "colSupplierName";
        colBranchNumber = new DataGridViewTextBoxColumn();
        colBranchNumber.Name = "colBranchNumber";
        colDescription = new DataGridViewTextBoxColumn();
        colDescription.Name = "colDescription";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Margin = Padding.Empty;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 4;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.BackColor = Color.FromArgb(23, 50, 78);
        lblTitle.ForeColor = Color.White;
        commandBar.Dock = DockStyle.Fill;
        commandBar.Margin = Padding.Empty;
        bodyLayout.Dock = DockStyle.Fill;
        bodyLayout.ColumnCount = 1;
        bodyLayout.RowCount = 4;
        bodyLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 64F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        bodyLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
        searchLayout.Dock = DockStyle.Fill;
        searchLayout.ColumnCount = 4;
        searchLayout.RowCount = 2;
        searchLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        searchLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 70F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 180F));
        searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        searchLayout.Padding = new Padding(6);
        lblFind.Text = "بحث";
        lblFind.Dock = DockStyle.Fill;
        lblFind.TextAlign = ContentAlignment.MiddleCenter;
        fieldFind.Dock = DockStyle.Fill;
        fieldFind.AccessibleName = "بحث";
        fieldFind.ReadOnly = true;
        searchLayout.Controls.Add(lblFind, 1, 0);
        searchLayout.Controls.Add(fieldFind, 2, 0);
        chkAutomatic.Text = "تلقائي";
        chkAutomatic.AutoSize = true;
        chkAutomatic.Enabled = false;
        searchLayout.Controls.Add(chkAutomatic, 1, 1);
        searchLayout.SetColumnSpan(chkAutomatic, 2);
        filtersLayout.Dock = DockStyle.Fill;
        filtersLayout.ColumnCount = 7;
        filtersLayout.RowCount = 1;
        gridLookup.Dock = DockStyle.Fill;
        gridLookup.ReadOnly = true;
        gridLookup.AllowUserToAddRows = false;
        gridLookup.AllowUserToDeleteRows = false;
        gridLookup.AutoGenerateColumns = false;
        gridLookup.RowHeadersVisible = false;
        gridLookup.BackgroundColor = Color.White;
        gridLookup.ColumnHeadersHeight = 34;
        gridLookup.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridLookup.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        colSelected.HeaderText = "";
        colSelected.Width = 34;
        colSelected.ReadOnly = true;
        colSelected.SortMode = DataGridViewColumnSortMode.NotSortable;
        colQuotationNumber.HeaderText = "رقم عرض السعر";
        colQuotationNumber.Width = 130;
        colQuotationNumber.ReadOnly = true;
        colQuotationNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colQuotationDate.HeaderText = "تاريخ عرض السعر";
        colQuotationDate.Width = 140;
        colQuotationDate.ReadOnly = true;
        colQuotationDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        colSupplierName.HeaderText = "اسم المورد";
        colSupplierName.Width = 210;
        colSupplierName.ReadOnly = true;
        colSupplierName.SortMode = DataGridViewColumnSortMode.NotSortable;
        colBranchNumber.HeaderText = "رقم الفرع";
        colBranchNumber.Width = 100;
        colBranchNumber.ReadOnly = true;
        colBranchNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colDescription.HeaderText = "البيان";
        colDescription.Width = 260;
        colDescription.ReadOnly = true;
        colDescription.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridLookup.Columns.AddRange(new DataGridViewColumn[] { colSelected, colQuotationNumber, colQuotationDate, colSupplierName, colBranchNumber, colDescription });
        actionsLayout.Dock = DockStyle.Fill;
        actionsLayout.ColumnCount = 3;
        actionsLayout.RowCount = 1;
        actionsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        actionsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        actionsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
        btnLoad.Text = "↧";
        btnLoad.AccessibleName = "إنزال البيانات";
        btnLoad.Enabled = false;
        btnLoad.Anchor = AnchorStyles.Right;
        actionsLayout.Controls.Add(btnLoad, 0, 0);
        bodyLayout.Controls.Add(searchLayout, 0, 0);
        bodyLayout.Controls.Add(filtersLayout, 0, 1);
        bodyLayout.Controls.Add(gridLookup, 0, 2);
        bodyLayout.Controls.Add(actionsLayout, 0, 3);
        auditFooter.Dock = DockStyle.Fill;
        auditFooter.Margin = Padding.Empty;
        standardAuditMetadata.Dock = DockStyle.Fill;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.Profile = AuditMetadataProfile.Standard;
        auditFooter.Controls.Add(standardAuditMetadata);
        mainLayout.Controls.Add(lblTitle, 0, 0);
        mainLayout.Controls.Add(commandBar, 0, 1);
        mainLayout.Controls.Add(bodyLayout, 0, 2);
        mainLayout.Controls.Add(auditFooter, 0, 3);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 9F);
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1180, 720);
        MinimumSize = new Size(1000, 600);
        Controls.Add(mainLayout);
        actionsLayout.Visible = true;
        lblTitle.Text = "عروض الأسعار";
        Name = "UcPurchaseQuotationSelector";
        Text = "عروض الأسعار";
        gridLookup.AccessibleName = "عروض الأسعار";
        ResumeLayout(false);
        filtersLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 34F));
        filtersLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 130F));
        fieldFilterQuotationNumber.AccessibleName = "بحث رقم عرض السعر";
        fieldFilterQuotationNumber.ReadOnly = true;
        fieldFilterQuotationNumber.Dock = DockStyle.Fill;
        filtersLayout.Controls.Add(fieldFilterQuotationNumber, 1, 0);
        filtersLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
        fieldFilterQuotationDate.AccessibleName = "بحث تاريخ عرض السعر";
        fieldFilterQuotationDate.ReadOnly = true;
        fieldFilterQuotationDate.Dock = DockStyle.Fill;
        filtersLayout.Controls.Add(fieldFilterQuotationDate, 2, 0);
        filtersLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 210F));
        fieldFilterSupplierName.AccessibleName = "بحث اسم المورد";
        fieldFilterSupplierName.ReadOnly = true;
        fieldFilterSupplierName.Dock = DockStyle.Fill;
        filtersLayout.Controls.Add(fieldFilterSupplierName, 3, 0);
        filtersLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 100F));
        fieldFilterBranchNumber.AccessibleName = "بحث رقم الفرع";
        fieldFilterBranchNumber.ReadOnly = true;
        fieldFilterBranchNumber.Dock = DockStyle.Fill;
        filtersLayout.Controls.Add(fieldFilterBranchNumber, 4, 0);
        filtersLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 260F));
        fieldFilterDescription.AccessibleName = "بحث البيان";
        fieldFilterDescription.ReadOnly = true;
        fieldFilterDescription.Dock = DockStyle.Fill;
        filtersLayout.Controls.Add(fieldFilterDescription, 5, 0);
        filtersLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
    }
}
