<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TransportERP\TransportERP.Domain.csproj" />
    <ProjectReference Include="..\TransportERP.Contracts\TransportERP.Contracts.csproj" />
  </ItemGroup>

</Project>
