namespace TransportERP.Desktop.Forms.Setup.General;

partial class FrmNumberingSettings
{
    private System.ComponentModel.IContainer? components = null;
    private System.Windows.Forms.TableLayoutPanel tlpRoot;
    private System.Windows.Forms.Panel pnlScreenHeader;
    private System.Windows.Forms.Label lblScreenCode;
    private System.Windows.Forms.Label lblScreenTitle;
    private System.Windows.Forms.Label lblBreadcrumb;
    private System.Windows.Forms.FlowLayoutPanel flpToolbar;
    private System.Windows.Forms.TableLayoutPanel tlpMainData;
    private System.Windows.Forms.ComboBox cmbScopeCompany;
        private System.Windows.Forms.ComboBox cmbScopeBranch;
        private System.Windows.Forms.ComboBox cmbScopeFiscalYear;
    private System.Windows.Forms.TableLayoutPanel tlpFunctionalScope;
    private System.Windows.Forms.TableLayoutPanel tlpSearchFilters;
    private System.Windows.Forms.TextBox txtSearch;
    private System.Windows.Forms.ComboBox cmbFilterStatus;
    private System.Windows.Forms.Button btnSearch;
    private System.Windows.Forms.Button btnClearFilters;
    private System.Windows.Forms.Panel pnlRecordsGrid;
    private System.Windows.Forms.DataGridView dgvRecords;
    private System.Windows.Forms.FlowLayoutPanel flpPagination;
    private System.Windows.Forms.Button btnFirst;
    private System.Windows.Forms.Button btnPrevious;
    private System.Windows.Forms.Label lblPageNumber;
    private System.Windows.Forms.Button btnNext;
    private System.Windows.Forms.Button btnLast;
    private System.Windows.Forms.ComboBox cmbPageSize;
    private System.Windows.Forms.Label lblTotalRecords;
    private System.Windows.Forms.TableLayoutPanel tlpAuditInfo;
    private System.Windows.Forms.FlowLayoutPanel flpUsageCounters;
    private System.Windows.Forms.Panel pnlEditCount;
    private System.Windows.Forms.Panel pnlPrintCount;
    private System.Windows.Forms.TabControl tabScreen;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.TabPage tabPage3;
        private System.Windows.Forms.TabPage tabPage4;
        private System.Windows.Forms.TabPage tabPage5;
    private System.Windows.Forms.ComboBox cmbDocumentType;
    private System.Windows.Forms.ComboBox cmbCompany;
    private System.Windows.Forms.ComboBox cmbBranch;
    private System.Windows.Forms.ComboBox cmbFiscalYear;
    private System.Windows.Forms.TextBox txtPrefix;
    private System.Windows.Forms.TextBox txtSuffix;
    private System.Windows.Forms.NumericUpDown nudDigits;
    private System.Windows.Forms.TextBox txtCurrentNumber;
    private System.Windows.Forms.NumericUpDown nudRangeStart;
    private System.Windows.Forms.NumericUpDown nudRangeEnd;
    private System.Windows.Forms.ComboBox cmbResetPattern;
    private System.Windows.Forms.ComboBox cmbNumberingMode;
    private System.Windows.Forms.ComboBox cmbPolicyStatus;
    private System.Windows.Forms.RichTextBox rtbCounterChangeReason;

    protected override void Dispose(bool disposing)
    {
        if (disposing && components != null) components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        tlpRoot = new System.Windows.Forms.TableLayoutPanel();
        pnlScreenHeader = new System.Windows.Forms.Panel();
        lblScreenCode = new System.Windows.Forms.Label();
        lblScreenTitle = new System.Windows.Forms.Label();
        lblBreadcrumb = new System.Windows.Forms.Label();
        flpToolbar = new System.Windows.Forms.FlowLayoutPanel();
        tlpMainData = new System.Windows.Forms.TableLayoutPanel();
        tlpFunctionalScope = new System.Windows.Forms.TableLayoutPanel();
        tlpSearchFilters = new System.Windows.Forms.TableLayoutPanel();
        txtSearch = new System.Windows.Forms.TextBox();
        cmbFilterStatus = new System.Windows.Forms.ComboBox();
        btnSearch = new System.Windows.Forms.Button();
        btnClearFilters = new System.Windows.Forms.Button();
        pnlRecordsGrid = new System.Windows.Forms.Panel();
        dgvRecords = new System.Windows.Forms.DataGridView();
        flpPagination = new System.Windows.Forms.FlowLayoutPanel();
        btnFirst = new System.Windows.Forms.Button(); btnPrevious = new System.Windows.Forms.Button(); lblPageNumber = new System.Windows.Forms.Label(); btnNext = new System.Windows.Forms.Button(); btnLast = new System.Windows.Forms.Button(); cmbPageSize = new System.Windows.Forms.ComboBox(); lblTotalRecords = new System.Windows.Forms.Label();
        tlpAuditInfo = new System.Windows.Forms.TableLayoutPanel();
        flpUsageCounters = new System.Windows.Forms.FlowLayoutPanel();
        pnlEditCount = new System.Windows.Forms.Panel(); pnlPrintCount = new System.Windows.Forms.Panel();
        cmbDocumentType = new System.Windows.Forms.ComboBox();
            cmbDocumentType.Name = "cmbDocumentType"; cmbDocumentType.Dock = System.Windows.Forms.DockStyle.Fill; cmbDocumentType.RightToLeft = System.Windows.Forms.RightToLeft.Yes; cmbDocumentType.Margin = new System.Windows.Forms.Padding(8, 4, 12, 4);
            cmbCompany = new System.Windows.Forms.ComboBox();
            cmbCompany.Name = "cmbCompany"; cmbCompany.Dock = System.Windows.Forms.DockStyle.Fill; cmbCompany.RightToLeft = System.Windows.Forms.RightToLeft.Yes; cmbCompany.Margin = new System.Windows.Forms.Padding(8, 4, 12, 4);
            cmbBranch = new System.Windows.Forms.ComboBox();
            cmbBranch.Name = "cmbBranch"; cmbBranch.Dock = System.Windows.Forms.DockStyle.Fill; cmbBranch.RightToLeft = System.Windows.Forms.RightToLeft.Yes; cmbBranch.Margin = new System.Windows.Forms.Padding(8, 4, 12, 4);
            cmbFiscalYear = new System.Windows.Forms.ComboBox();
            cmbFiscalYear.Name = "cmbFiscalYear"; cmbFiscalYear.Dock = System.Windows.Forms.DockStyle.Fill; cmbFiscalYear.RightToLeft = System.Windows.Forms.RightToLeft.Yes; cmbFiscalYear.Margin = new System.Windows.Forms.Padding(8, 4, 12, 4);
            txtPrefix = new System.Windows.Forms.TextBox();
            txtPrefix.Name = "txtPrefix"; txtPrefix.Dock = System.Windows.Forms.DockStyle.Fill; txtPrefix.RightToLeft = System.Windows.Forms.RightToLeft.Yes; txtPrefix.Margin = new System.Windows.Forms.Padding(8, 4, 12, 4);
            txtSuffix = new System.Windows.Forms.TextBox();
            txtSuffix.Name = "txtSuffix"; txtSuffix.Dock = System.Windows.Forms.DockStyle.Fill; txtSuffix.RightToLeft = System.Windows.Forms.RightToLeft.Yes; txtSuffix.Margin = new System.Windows.Forms.Padding(8, 4, 12, 4);
            nudDigits = new System.Windows.Forms.NumericUpDown();
            nudDigits.Name = "nudDigits"; nudDigits.Dock = System.Windows.Forms.DockStyle.Fill; nudDigits.RightToLeft = System.Windows.Forms.RightToLeft.Yes; nudDigits.Margin = new System.Windows.Forms.Padding(8, 4, 12, 4);
            nudDigits.DecimalPlaces = 2; nudDigits.Maximum = 100000000;
            txtCurrentNumber = new System.Windows.Forms.TextBox();
            txtCurrentNumber.Name = "txtCurrentNumber"; txtCurrentNumber.Dock = System.Windows.Forms.DockStyle.Fill; txtCurrentNumber.RightToLeft = System.Windows.Forms.RightToLeft.Yes; txtCurrentNumber.Margin = new System.Windows.Forms.Padding(8, 4, 12, 4);
            nudRangeStart = new System.Windows.Forms.NumericUpDown();
            nudRangeStart.Name = "nudRangeStart"; nudRangeStart.Dock = System.Windows.Forms.DockStyle.Fill; nudRangeStart.RightToLeft = System.Windows.Forms.RightToLeft.Yes; nudRangeStart.Margin = new System.Windows.Forms.Padding(8, 4, 12, 4);
            nudRangeStart.DecimalPlaces = 2; nudRangeStart.Maximum = 100000000;
            nudRangeEnd = new System.Windows.Forms.NumericUpDown();
            nudRangeEnd.Name = "nudRangeEnd"; nudRangeEnd.Dock = System.Windows.Forms.DockStyle.Fill; nudRangeEnd.RightToLeft = System.Windows.Forms.RightToLeft.Yes; nudRangeEnd.Margin = new System.Windows.Forms.Padding(8, 4, 12, 4);
            nudRangeEnd.DecimalPlaces = 2; nudRangeEnd.Maximum = 100000000;
            cmbResetPattern = new System.Windows.Forms.ComboBox();
            cmbResetPattern.Name = "cmbResetPattern"; cmbResetPattern.Dock = System.Windows.Forms.DockStyle.Fill; cmbResetPattern.RightToLeft = System.Windows.Forms.RightToLeft.Yes; cmbResetPattern.Margin = new System.Windows.Forms.Padding(8, 4, 12, 4);
            cmbNumberingMode = new System.Windows.Forms.ComboBox();
            cmbNumberingMode.Name = "cmbNumberingMode"; cmbNumberingMode.Dock = System.Windows.Forms.DockStyle.Fill; cmbNumberingMode.RightToLeft = System.Windows.Forms.RightToLeft.Yes; cmbNumberingMode.Margin = new System.Windows.Forms.Padding(8, 4, 12, 4);
            cmbPolicyStatus = new System.Windows.Forms.ComboBox();
            cmbPolicyStatus.Name = "cmbPolicyStatus"; cmbPolicyStatus.Dock = System.Windows.Forms.DockStyle.Fill; cmbPolicyStatus.RightToLeft = System.Windows.Forms.RightToLeft.Yes; cmbPolicyStatus.Margin = new System.Windows.Forms.Padding(8, 4, 12, 4);
            rtbCounterChangeReason = new System.Windows.Forms.RichTextBox();
            rtbCounterChangeReason.Name = "rtbCounterChangeReason"; rtbCounterChangeReason.Dock = System.Windows.Forms.DockStyle.Fill; rtbCounterChangeReason.RightToLeft = System.Windows.Forms.RightToLeft.Yes; rtbCounterChangeReason.Margin = new System.Windows.Forms.Padding(8, 4, 12, 4);
            rtbCounterChangeReason.Height = 54;
        cmbScopeCompany = new System.Windows.Forms.ComboBox();
            cmbScopeCompany.Name="cmbScopeCompany"; cmbScopeCompany.Dock=System.Windows.Forms.DockStyle.Fill; cmbScopeCompany.RightToLeft=System.Windows.Forms.RightToLeft.Yes;
            cmbScopeBranch = new System.Windows.Forms.ComboBox();
            cmbScopeBranch.Name="cmbScopeBranch"; cmbScopeBranch.Dock=System.Windows.Forms.DockStyle.Fill; cmbScopeBranch.RightToLeft=System.Windows.Forms.RightToLeft.Yes;
            cmbScopeFiscalYear = new System.Windows.Forms.ComboBox();
            cmbScopeFiscalYear.Name="cmbScopeFiscalYear"; cmbScopeFiscalYear.Dock=System.Windows.Forms.DockStyle.Fill; cmbScopeFiscalYear.RightToLeft=System.Windows.Forms.RightToLeft.Yes;
        SuspendLayout();
        tlpRoot.Name="tlpRoot"; tlpRoot.Dock=System.Windows.Forms.DockStyle.Fill; tlpRoot.ColumnCount=1; tlpRoot.RowCount=10; tlpRoot.RightToLeft=System.Windows.Forms.RightToLeft.Yes; tlpRoot.BackColor=System.Drawing.Color.FromArgb(249,250,251); tlpRoot.Padding=new System.Windows.Forms.Padding(16);
        tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute,72));
        tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute,56));
        tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute,360));
        tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute,60));
        tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute,70));
        tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent,100));
        tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute,48));
        tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute,66));
        tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute,44));
        pnlScreenHeader.Name="pnlScreenHeader"; pnlScreenHeader.Dock=System.Windows.Forms.DockStyle.Fill; pnlScreenHeader.BackColor=System.Drawing.Color.White; pnlScreenHeader.Padding=new System.Windows.Forms.Padding(16,8,16,8); pnlScreenHeader.RightToLeft=System.Windows.Forms.RightToLeft.Yes;
        lblScreenCode.Name="lblScreenCode"; lblScreenCode.Text="GEN-014"; lblScreenCode.AutoSize=true; lblScreenCode.Font=new System.Drawing.Font("Segoe UI",11F,System.Drawing.FontStyle.Bold); lblScreenCode.ForeColor=System.Drawing.Color.FromArgb(46,116,181); lblScreenCode.Location=new System.Drawing.Point(0,8);
        lblScreenTitle.Name="lblScreenTitle"; lblScreenTitle.Text="الترقيم العام"; lblScreenTitle.AutoSize=true; lblScreenTitle.Font=new System.Drawing.Font("Segoe UI",20F,System.Drawing.FontStyle.Bold); lblScreenTitle.ForeColor=System.Drawing.Color.FromArgb(31,41,55); lblScreenTitle.Location=new System.Drawing.Point(0,27);
        lblBreadcrumb.Name="lblBreadcrumb"; lblBreadcrumb.Text="التهيئة العامة / الترقيم العام"; lblBreadcrumb.AutoSize=true; lblBreadcrumb.Font=new System.Drawing.Font("Segoe UI",11F); lblBreadcrumb.ForeColor=System.Drawing.Color.Gray; lblBreadcrumb.Location=new System.Drawing.Point(0,49);
        pnlScreenHeader.Controls.Add(lblScreenCode); pnlScreenHeader.Controls.Add(lblScreenTitle); pnlScreenHeader.Controls.Add(lblBreadcrumb);
        flpToolbar.Name="flpToolbar"; flpToolbar.Dock=System.Windows.Forms.DockStyle.Fill; flpToolbar.RightToLeft=System.Windows.Forms.RightToLeft.Yes; flpToolbar.FlowDirection=System.Windows.Forms.FlowDirection.RightToLeft; flpToolbar.WrapContents=false; flpToolbar.Padding=new System.Windows.Forms.Padding(8,10,8,10); flpToolbar.BackColor=System.Drawing.Color.White;
        AddToolbarButton("btnNew","جديد"); AddToolbarButton("btnSave","حفظ"); AddToolbarButton("btnEdit","تعديل"); AddToolbarButton("btnStop","إيقاف"); AddToolbarButton("btnDelete","حذف"); AddToolbarButton("btnPrint","طباعة"); AddToolbarButton("btnExport","تصدير"); AddToolbarButton("btnCancel","إلغاء"); AddToolbarButton("btnMore","المزيد");
        tlpMainData.Name="tlpMainData"; tlpMainData.Dock=System.Windows.Forms.DockStyle.Fill; tlpMainData.RightToLeft=System.Windows.Forms.RightToLeft.Yes; tlpMainData.ColumnCount=4; tlpMainData.RowCount=7; tlpMainData.Padding=new System.Windows.Forms.Padding(16); tlpMainData.BackColor=System.Drawing.Color.White; tlpMainData.AutoScroll=true;
        tlpMainData.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent,15)); tlpMainData.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent,35)); tlpMainData.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent,15)); tlpMainData.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent,35));
        for(int i=0;i<7;i++) tlpMainData.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute,44));
        AddField(tlpMainData, "نوع المستند", cmbDocumentType, 0);
            AddField(tlpMainData, "الشركة", cmbCompany, 1);
            AddField(tlpMainData, "الفرع", cmbBranch, 2);
            AddField(tlpMainData, "السنة", cmbFiscalYear, 3);
            AddField(tlpMainData, "البادئة", txtPrefix, 4);
            AddField(tlpMainData, "اللاحقة", txtSuffix, 5);
            AddField(tlpMainData, "عدد الخانات", nudDigits, 6);
            AddField(tlpMainData, "الرقم الحالي", txtCurrentNumber, 7);
            AddField(tlpMainData, "بداية النطاق", nudRangeStart, 8);
            AddField(tlpMainData, "نهاية النطاق", nudRangeEnd, 9);
            AddField(tlpMainData, "نمط التصفير", cmbResetPattern, 10);
            AddField(tlpMainData, "مركزي/فرعي", cmbNumberingMode, 11);
            AddField(tlpMainData, "حالة السياسة", cmbPolicyStatus, 12);
            AddField(tlpMainData, "سبب تعديل العداد", rtbCounterChangeReason, 13);
        tlpFunctionalScope.Name="tlpFunctionalScope"; tlpFunctionalScope.Dock=System.Windows.Forms.DockStyle.Fill; tlpFunctionalScope.RightToLeft=System.Windows.Forms.RightToLeft.Yes; tlpFunctionalScope.ColumnCount=6; tlpFunctionalScope.Padding=new System.Windows.Forms.Padding(16,8,16,8); tlpFunctionalScope.BackColor=System.Drawing.Color.White; cmbScopeCompany = new System.Windows.Forms.ComboBox();
            cmbScopeCompany.Name="cmbScopeCompany"; cmbScopeCompany.Dock=System.Windows.Forms.DockStyle.Fill; cmbScopeCompany.RightToLeft=System.Windows.Forms.RightToLeft.Yes;
            cmbScopeBranch = new System.Windows.Forms.ComboBox();
            cmbScopeBranch.Name="cmbScopeBranch"; cmbScopeBranch.Dock=System.Windows.Forms.DockStyle.Fill; cmbScopeBranch.RightToLeft=System.Windows.Forms.RightToLeft.Yes;
            cmbScopeFiscalYear = new System.Windows.Forms.ComboBox();
            cmbScopeFiscalYear.Name="cmbScopeFiscalYear"; cmbScopeFiscalYear.Dock=System.Windows.Forms.DockStyle.Fill; cmbScopeFiscalYear.RightToLeft=System.Windows.Forms.RightToLeft.Yes;
        AddScopeField(tlpFunctionalScope, "الشركة المستهدفة", cmbScopeCompany, 0);
            AddScopeField(tlpFunctionalScope, "الفرع المستهدف", cmbScopeBranch, 1);
            AddScopeField(tlpFunctionalScope, "السنة المستهدفة", cmbScopeFiscalYear, 2);
        tlpSearchFilters.Name="tlpSearchFilters"; tlpSearchFilters.Dock=System.Windows.Forms.DockStyle.Fill; tlpSearchFilters.RightToLeft=System.Windows.Forms.RightToLeft.Yes; tlpSearchFilters.ColumnCount=4; tlpSearchFilters.Padding=new System.Windows.Forms.Padding(16); tlpSearchFilters.BackColor=System.Drawing.Color.White;
        txtSearch.Name="txtSearch"; txtSearch.PlaceholderText="بحث"; txtSearch.Dock=System.Windows.Forms.DockStyle.Fill; txtSearch.RightToLeft=System.Windows.Forms.RightToLeft.Yes;
        cmbFilterStatus.Name="cmbFilterStatus"; cmbFilterStatus.Dock=System.Windows.Forms.DockStyle.Fill; cmbFilterStatus.RightToLeft=System.Windows.Forms.RightToLeft.Yes;
        ConfigureButton(btnSearch,"btnSearch","بحث"); ConfigureButton(btnClearFilters,"btnClearFilters","مسح");
        tlpSearchFilters.Controls.Add(txtSearch,0,0); tlpSearchFilters.Controls.Add(cmbFilterStatus,1,0); tlpSearchFilters.Controls.Add(btnSearch,2,0); tlpSearchFilters.Controls.Add(btnClearFilters,3,0);
        pnlRecordsGrid.Name="pnlRecordsGrid"; pnlRecordsGrid.Dock=System.Windows.Forms.DockStyle.Fill; pnlRecordsGrid.BackColor=System.Drawing.Color.White; pnlRecordsGrid.RightToLeft=System.Windows.Forms.RightToLeft.Yes;
        dgvRecords.Name="dgvRecords"; dgvRecords.Dock=System.Windows.Forms.DockStyle.Fill; dgvRecords.RightToLeft=System.Windows.Forms.RightToLeft.Yes; dgvRecords.SelectionMode=System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect; dgvRecords.MultiSelect=false; dgvRecords.AllowUserToAddRows=false; dgvRecords.AllowUserToDeleteRows=false; dgvRecords.AllowUserToResizeRows=false; dgvRecords.AutoGenerateColumns=false; dgvRecords.BackgroundColor=System.Drawing.Color.White;
        dgvRecords.Columns.Add(new System.Windows.Forms.DataGridViewTextBoxColumn { Name = "col1", HeaderText = "نوع المستند", ReadOnly = true });
        dgvRecords.Columns.Add(new System.Windows.Forms.DataGridViewTextBoxColumn { Name = "col2", HeaderText = "الشركة", ReadOnly = true });
        dgvRecords.Columns.Add(new System.Windows.Forms.DataGridViewTextBoxColumn { Name = "col3", HeaderText = "الفرع", ReadOnly = true });
        dgvRecords.Columns.Add(new System.Windows.Forms.DataGridViewTextBoxColumn { Name = "col4", HeaderText = "السنة", ReadOnly = true });
        dgvRecords.Columns.Add(new System.Windows.Forms.DataGridViewTextBoxColumn { Name = "col5", HeaderText = "البادئة", ReadOnly = true });
        dgvRecords.Columns.Add(new System.Windows.Forms.DataGridViewTextBoxColumn { Name = "col6", HeaderText = "الرقم الحالي", ReadOnly = true });
        dgvRecords.Columns.Add(new System.Windows.Forms.DataGridViewTextBoxColumn { Name = "col7", HeaderText = "الحالة", ReadOnly = true });
        pnlRecordsGrid.Controls.Add(dgvRecords);
        flpPagination.Name="flpPagination"; flpPagination.Dock=System.Windows.Forms.DockStyle.Fill; flpPagination.RightToLeft=System.Windows.Forms.RightToLeft.Yes; flpPagination.FlowDirection=System.Windows.Forms.FlowDirection.RightToLeft; flpPagination.WrapContents=false; flpPagination.Padding=new System.Windows.Forms.Padding(8); flpPagination.BackColor=System.Drawing.Color.White;
        ConfigureButton(btnFirst,"btnFirst","الأول"); ConfigureButton(btnPrevious,"btnPrevious","السابق"); lblPageNumber.Name="lblPageNumber"; lblPageNumber.Text="1"; lblPageNumber.AutoSize=false; lblPageNumber.Size=new System.Drawing.Size(52,36); lblPageNumber.TextAlign=System.Drawing.ContentAlignment.MiddleCenter; ConfigureButton(btnNext,"btnNext","التالي"); ConfigureButton(btnLast,"btnLast","الأخير"); cmbPageSize.Name="cmbPageSize"; cmbPageSize.Size=new System.Drawing.Size(90,36); lblTotalRecords.Name="lblTotalRecords"; lblTotalRecords.Text="إجمالي السجلات: 0"; lblTotalRecords.AutoSize=true; flpPagination.Controls.AddRange(new System.Windows.Forms.Control[]{btnFirst,btnPrevious,lblPageNumber,btnNext,btnLast,cmbPageSize,lblTotalRecords});
        tlpAuditInfo.Name="tlpAuditInfo"; tlpAuditInfo.Dock=System.Windows.Forms.DockStyle.Fill; tlpAuditInfo.RightToLeft=System.Windows.Forms.RightToLeft.Yes; tlpAuditInfo.ColumnCount=4; tlpAuditInfo.BackColor=System.Drawing.Color.FromArgb(243,244,246); tlpAuditInfo.Padding=new System.Windows.Forms.Padding(16);
        AddAuditField("أنشئ بواسطة","—",0); AddAuditField("تاريخ الإنشاء","—",1); AddAuditField("آخر تعديل بواسطة","—",2); AddAuditField("تاريخ التعديل","—",3);
        flpUsageCounters.Name="flpUsageCounters"; flpUsageCounters.Dock=System.Windows.Forms.DockStyle.Fill; flpUsageCounters.RightToLeft=System.Windows.Forms.RightToLeft.Yes; flpUsageCounters.FlowDirection=System.Windows.Forms.FlowDirection.RightToLeft; flpUsageCounters.Padding=new System.Windows.Forms.Padding(8); flpUsageCounters.BackColor=System.Drawing.Color.White; pnlEditCount.Name="pnlEditCount"; pnlEditCount.Size=new System.Drawing.Size(150,28); pnlEditCount.BorderStyle=System.Windows.Forms.BorderStyle.FixedSingle; pnlEditCount.Controls.Add(new System.Windows.Forms.Label { Text="عدد مرات التعديل: 0", Dock=System.Windows.Forms.DockStyle.Fill, TextAlign=System.Drawing.ContentAlignment.MiddleCenter }); pnlPrintCount.Name="pnlPrintCount"; pnlPrintCount.Size=new System.Drawing.Size(150,28); pnlPrintCount.BorderStyle=System.Windows.Forms.BorderStyle.FixedSingle; pnlPrintCount.Controls.Add(new System.Windows.Forms.Label { Text="عدد مرات الطباعة: 0", Dock=System.Windows.Forms.DockStyle.Fill, TextAlign=System.Drawing.ContentAlignment.MiddleCenter }); flpUsageCounters.Controls.Add(pnlEditCount); flpUsageCounters.Controls.Add(pnlPrintCount);
        tabScreen = new System.Windows.Forms.TabControl(); tabScreen.Name = "tabScreen"; tabScreen.Dock = System.Windows.Forms.DockStyle.Top; tabScreen.Height = 360; tabScreen.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            tabPage1=new System.Windows.Forms.TabPage(); tabPage1.Name="tabPage1"; tabPage1.Text="البيانات الرئيسية"; tabPage1.RightToLeft=System.Windows.Forms.RightToLeft.Yes;
            tabPage2=new System.Windows.Forms.TabPage(); tabPage2.Name="tabPage2"; tabPage2.Text="نطاق الترقيم"; tabPage2.RightToLeft=System.Windows.Forms.RightToLeft.Yes;
            tabPage3=new System.Windows.Forms.TabPage(); tabPage3.Name="tabPage3"; tabPage3.Text="قواعد التصفير"; tabPage3.RightToLeft=System.Windows.Forms.RightToLeft.Yes;
            tabPage4=new System.Windows.Forms.TabPage(); tabPage4.Name="tabPage4"; tabPage4.Text="التعديلات والاستثناءات"; tabPage4.RightToLeft=System.Windows.Forms.RightToLeft.Yes;
            tabPage5=new System.Windows.Forms.TabPage(); tabPage5.Name="tabPage5"; tabPage5.Text="سجل العمليات"; tabPage5.RightToLeft=System.Windows.Forms.RightToLeft.Yes;
            tabScreen.TabPages.Add(tabPage1);
            tabScreen.TabPages.Add(tabPage2);
            tabScreen.TabPages.Add(tabPage3);
            tabScreen.TabPages.Add(tabPage4);
            tabScreen.TabPages.Add(tabPage5);
            tabPage1.Controls.Add(tlpMainData);
        tlpRoot.Controls.Add(pnlScreenHeader,0,0); tlpRoot.Controls.Add(flpToolbar,0,1); tlpRoot.Controls.Add(tabScreen,0,2); tlpRoot.Controls.Add(tlpFunctionalScope,0,3); tlpRoot.Controls.Add(tlpSearchFilters,0,4); tlpRoot.Controls.Add(pnlRecordsGrid,0,5); tlpRoot.Controls.Add(flpPagination,0,6); tlpRoot.Controls.Add(tlpAuditInfo,0,7); tlpRoot.Controls.Add(flpUsageCounters,0,8);
        AutoScaleMode=System.Windows.Forms.AutoScaleMode.Font; BackColor=System.Drawing.Color.FromArgb(249,250,251); ClientSize=new System.Drawing.Size(1280,900); Controls.Add(tlpRoot); Font=new System.Drawing.Font("Segoe UI",10F); MinimumSize=new System.Drawing.Size(1180,780); Name="FrmNumberingSettings"; RightToLeft=System.Windows.Forms.RightToLeft.Yes; RightToLeftLayout=true; StartPosition=System.Windows.Forms.FormStartPosition.CenterScreen; Text="GEN-014 — الترقيم العام";
        ResumeLayout(false);
    }
    private void AddToolbarButton(string name, string text) { var button=new System.Windows.Forms.Button(); ConfigureButton(button,name,text); flpToolbar.Controls.Add(button); }
    private static void ConfigureButton(System.Windows.Forms.Button button,string name,string text) { button.Name=name; button.Text=text; button.Size=new System.Drawing.Size(82,36); button.FlatStyle=System.Windows.Forms.FlatStyle.Flat; button.Margin=new System.Windows.Forms.Padding(4,0,4,0); button.RightToLeft=System.Windows.Forms.RightToLeft.Yes; }
    private static void AddField(System.Windows.Forms.TableLayoutPanel panel,string title,System.Windows.Forms.Control control,int index) { int row=index/2, column=(index%2)*2; var label=new System.Windows.Forms.Label { Name="lbl"+control.Name.Substring(3)+"Title", Text=title, Dock=System.Windows.Forms.DockStyle.Fill, TextAlign=System.Drawing.ContentAlignment.MiddleRight, Font=new System.Drawing.Font("Segoe UI",10F,System.Drawing.FontStyle.Bold) }; panel.Controls.Add(label,column,row); panel.Controls.Add(control,column+1,row); }
    private static void AddScopeField(System.Windows.Forms.TableLayoutPanel panel,string title,System.Windows.Forms.Control control,int index) { var label=new System.Windows.Forms.Label { Text=title, Dock=System.Windows.Forms.DockStyle.Fill, TextAlign=System.Drawing.ContentAlignment.MiddleRight }; panel.Controls.Add(label,index*2,0); panel.Controls.Add(control,index*2+1,0); }
    private void AddAuditField(string title,string value,int column) { var label=new System.Windows.Forms.Label { Text=title+"\r\n"+value, Dock=System.Windows.Forms.DockStyle.Fill, TextAlign=System.Drawing.ContentAlignment.MiddleRight, Font=new System.Drawing.Font("Segoe UI",9F) }; tlpAuditInfo.Controls.Add(label,column,0); }
}