using System.Text.Json;
using TransportERP.Contracts.Core;
using TransportERP.Contracts.Geo;
using TransportERP.Contracts.Org;
using TransportERP.Domain.Org;

namespace TransportERP.Application.Org;

public enum OrgResource { Currencies, ExchangeRates, Companies, Branches, FiscalYears, NumberSequences, Languages, SettingOverrides }
public interface IOrgRepository
{
    Task<OrgEntity?> FindAsync(OrgResource resource, Guid id, CancellationToken ct);
    Task<bool> CodeExistsAsync(OrgResource resource, string code, Guid? exceptId, Guid? companyId, CancellationToken ct);
    Task<PagedResponse<OrgDto>> ListAsync(OrgResource resource, PagedQueryRequest query, OperationContext context, CancellationToken ct);
    Task AddAsync(OrgEntity entity, CancellationToken ct); Task SaveAsync(CancellationToken ct);
    Task<NumberReservation?> FindReservationAsync(Guid sequenceId, string idempotencyKey, CancellationToken ct);
    Task AddReservationAsync(NumberReservation reservation, CancellationToken ct);
}
public interface IOrgService
{
    Task<PagedResponse<OrgDto>> ListAsync(OrgResource r, PagedQueryRequest q, OperationContext c, CancellationToken ct);
    Task<OrgDto?> GetAsync(OrgResource r, Guid id, OperationContext c, CancellationToken ct);
    Task<OrgDto> CreateAsync(OrgResource r, OrgWriteRequest request, OperationContext c, CancellationToken ct);
    Task<OrgDto?> UpdateAsync(OrgResource r, Guid id, OrgWriteRequest request, OperationContext c, CancellationToken ct);
    Task<OrgDto?> DisableAsync(OrgResource r, Guid id, OrgLifecycleRequest request, OperationContext c, CancellationToken ct);
    Task<OrgDto?> TransitionFiscalYearAsync(Guid id, string transition, FiscalYearTransitionRequest request, OperationContext c, CancellationToken ct);
    Task<NumberReservationDto> ReserveNumberAsync(NumberReservationRequest request, OperationContext c, CancellationToken ct);
}
public sealed class OrgService(IOrgRepository repository, IBusinessAuditWriter audit) : IOrgService
{
    public Task<PagedResponse<OrgDto>> ListAsync(OrgResource r, PagedQueryRequest q, OperationContext c, CancellationToken ct) { c.EnsureComplete(); ValidatePage(q); return repository.ListAsync(r,q,c,ct); }
    public async Task<OrgDto?> GetAsync(OrgResource r, Guid id, OperationContext c, CancellationToken ct) { c.EnsureComplete(); var x=await repository.FindAsync(r,id,ct); return x is null ? null : ToDto(x); }
    public async Task<OrgDto> CreateAsync(OrgResource r, OrgWriteRequest req, OperationContext c, CancellationToken ct)
    {
        c.EnsureComplete(); var x=Create(r,req); Validate(r,x); await EnsureUnique(r,x,null,ct); x.Id=Guid.CreateVersion7(); await repository.AddAsync(x,ct); await WriteAudit(x,"Create",null,c,null,ct); await repository.SaveAsync(ct); return ToDto(x);
    }
    public async Task<OrgDto?> UpdateAsync(OrgResource r, Guid id, OrgWriteRequest req, OperationContext c, CancellationToken ct)
    {
        c.EnsureComplete(); var x=await repository.FindAsync(r,id,ct); if(x is null)return null; if(req.ExpectedVersion!=x.Version) throw new InvalidOperationException("CONCURRENCY_CONFLICT"); var before=JsonSerializer.SerializeToElement(ToDto(x)); Apply(r,x,req); Validate(r,x); await EnsureUnique(r,x,id,ct); x.Version++; x.UpdatedAtUtc=DateTime.UtcNow; await WriteAudit(x,"Update",before,c,null,ct); await repository.SaveAsync(ct); return ToDto(x);
    }
    public async Task<OrgDto?> DisableAsync(OrgResource r, Guid id, OrgLifecycleRequest req, OperationContext c, CancellationToken ct)
    {
        c.EnsureComplete(); if(string.IsNullOrWhiteSpace(req.Reason))throw new ArgumentException("Reason is required."); var x=await repository.FindAsync(r,id,ct); if(x is null)return null; if(x.Version!=req.ExpectedVersion)throw new InvalidOperationException("CONCURRENCY_CONFLICT"); var before=JsonSerializer.SerializeToElement(ToDto(x)); x.IsActive=false; x.Version++; x.UpdatedAtUtc=DateTime.UtcNow; await WriteAudit(x,"Disable",before,c,req.Reason,ct); await repository.SaveAsync(ct); return ToDto(x);
    }
    public async Task<OrgDto?> TransitionFiscalYearAsync(Guid id,string transition,FiscalYearTransitionRequest req,OperationContext c,CancellationToken ct)
    { c.EnsureComplete(); var x=await repository.FindAsync(OrgResource.FiscalYears,id,ct) as FiscalYear; if(x is null)return null; if(x.Version!=req.ExpectedVersion)throw new InvalidOperationException("CONCURRENCY_CONFLICT"); var target=transition.ToLowerInvariant() switch { "open"=>FiscalYearStatus.Open, "close"=>FiscalYearStatus.Closed, _=>throw new InvalidOperationException("STATE_TRANSITION_INVALID") }; if((target==FiscalYearStatus.Open&&x.Status!=FiscalYearStatus.Draft)||(target==FiscalYearStatus.Closed&&x.Status!=FiscalYearStatus.Open))throw new InvalidOperationException("STATE_TRANSITION_INVALID"); var before=JsonSerializer.SerializeToElement(ToDto(x)); x.Status=target;x.Version++;x.UpdatedAtUtc=DateTime.UtcNow; await WriteAudit(x,target.ToString(),before,c,req.Reason,ct);await repository.SaveAsync(ct);return ToDto(x); }
    public async Task<NumberReservationDto> ReserveNumberAsync(NumberReservationRequest req,OperationContext c,CancellationToken ct)
    { c.EnsureComplete(); if(string.IsNullOrWhiteSpace(req.IdempotencyKey))throw new ArgumentException("IdempotencyKey is required."); var existing=await repository.FindReservationAsync(req.SequenceId,req.IdempotencyKey,ct);if(existing is not null)return ToReservation(existing); var sequence=await repository.FindAsync(OrgResource.NumberSequences,req.SequenceId,ct) as NumberSequence ?? throw new KeyNotFoundException("NOT_FOUND");if(!sequence.IsActive)throw new InvalidOperationException("NUMBER_SEQUENCE_INACTIVE"); var next=checked(sequence.LastNumber+1); sequence.LastNumber=next;sequence.Version++;sequence.UpdatedAtUtc=DateTime.UtcNow; var reservation=new NumberReservation { Id=Guid.CreateVersion7(),SequenceId=sequence.Id,NumberValue=next,RenderedNumber=$"{sequence.Prefix}{next}",IdempotencyKey=req.IdempotencyKey,Reason=req.Reason};await repository.AddReservationAsync(reservation,ct);await WriteAudit(sequence,"ReserveNumber",JsonSerializer.SerializeToElement(ToDto(sequence)),c,req.Reason,ct);await repository.SaveAsync(ct);return ToReservation(reservation); }
    private async Task EnsureUnique(OrgResource r,OrgEntity x,Guid? except,CancellationToken ct){Guid? company=x switch { Company=>null,Branch b=>b.CompanyId,ExchangeRate e=>e.CompanyId,FiscalYear y=>y.CompanyId,_=>null};if(await repository.CodeExistsAsync(r,Code(x),except,company,ct))throw new InvalidOperationException("DUPLICATE_NUMBER");}
    private static string Code(OrgEntity x)=>x switch { Currency v=>v.Code,Company v=>v.Code,Branch v=>v.Code,FiscalYear v=>v.Code,NumberSequence v=>v.Code,Language v=>v.LanguageCode,ExchangeRate v=>$"{v.BaseCurrencyId:N}:{v.QuoteCurrencyId:N}:{v.EffectiveFrom:yyyyMMdd}",SettingOverride v=>$"{v.DefinitionId:N}:{v.ScopeType}:{v.ScopeId:N}",_=>throw new ArgumentOutOfRangeException()};
    private static void ValidatePage(PagedQueryRequest q){if(q.Page<1||q.PageSize is <1 or >200)throw new ArgumentOutOfRangeException(nameof(q));}
    private static void Validate(OrgResource r,OrgEntity x){if(string.IsNullOrWhiteSpace(Code(x))||Code(x).Length>200)throw new ArgumentException("Code is required.");if(x is Currency c&&(c.Code.Length!=3||c.DecimalPlaces>10))throw new ArgumentException("Currency code must be ISO-like and decimal places valid.");if(x is ExchangeRate e&&(e.Rate<=0||e.MinimumRate<=0||e.MaximumRate<e.MinimumRate||e.Rate<e.MinimumRate||e.Rate>e.MaximumRate||e.BaseCurrencyId==e.QuoteCurrencyId||e.EffectiveTo<e.EffectiveFrom))throw new ArgumentException("Invalid exchange rate.");if(x is FiscalYear y&&y.EndDate<y.StartDate)throw new ArgumentException("Fiscal year end must not precede start.");if(x is Language l&&l.Direction is not ("RTL" or "LTR"))throw new ArgumentException("Language direction must be RTL or LTR.");}
    private static OrgEntity Create(OrgResource r,OrgWriteRequest q)=>r switch { OrgResource.Currencies=>new Currency{Code=q.Code,ArabicName=q.ArabicName,EnglishName=q.EnglishName,Symbol=V(q,"Symbol"),DecimalPlaces=byte.Parse(V(q,"DecimalPlaces")??"2")},OrgResource.Companies=>new Company{Code=q.Code,ArabicName=q.ArabicName,EnglishName=q.EnglishName,LegalName=V(q,"LegalName")??q.ArabicName,BaseCurrencyId=G(q,"BaseCurrencyId"),TaxNumber=V(q,"TaxNumber"),LogoUri=V(q,"LogoUri"),Notes=V(q,"Notes")},OrgResource.Branches=>new Branch{Code=q.Code,ArabicName=q.ArabicName,EnglishName=q.EnglishName,CompanyId=G(q,"CompanyId"),TimeZone=V(q,"TimeZone"),Notes=V(q,"Notes")},OrgResource.ExchangeRates=>new ExchangeRate{CompanyId=G(q,"CompanyId"),BaseCurrencyId=G(q,"BaseCurrencyId"),QuoteCurrencyId=G(q,"QuoteCurrencyId"),Rate=D(q,"Rate"),MinimumRate=D(q,"MinimumRate"),MaximumRate=D(q,"MaximumRate"),EffectiveFrom=DateOnly.Parse(V(q,"EffectiveFrom")!),EffectiveTo=DateOnly.TryParse(V(q,"EffectiveTo"),out var to)?to:null,Source=V(q,"Source")??"Manual"},OrgResource.FiscalYears=>new FiscalYear{Code=q.Code,CompanyId=G(q,"CompanyId"),StartDate=DateOnly.Parse(V(q,"StartDate")!),EndDate=DateOnly.Parse(V(q,"EndDate")!)},OrgResource.NumberSequences=>new NumberSequence{Code=q.Code,ArabicName=q.ArabicName,EnglishName=q.EnglishName,ScopeType=V(q,"ScopeType")??"Company",DocumentType=V(q,"DocumentType"),CompanyId=GO(q,"CompanyId"),BranchId=GO(q,"BranchId"),FiscalYearId=GO(q,"FiscalYearId"),Prefix=V(q,"Prefix"),ResetPolicy=V(q,"ResetPolicy")},OrgResource.Languages=>new Language{LanguageCode=q.Code,ArabicName=q.ArabicName,EnglishName=q.EnglishName,Direction=V(q,"Direction")??"RTL"},OrgResource.SettingOverrides=>new SettingOverride{DefinitionId=G(q,"DefinitionId"),ScopeType=V(q,"ScopeType")??"Global",ScopeId=GO(q,"ScopeId"),TypedValue=V(q,"TypedValue")??throw new ArgumentException("TypedValue is required.")},_=>throw new ArgumentOutOfRangeException(nameof(r))};
    private static void Apply(OrgResource r,OrgEntity x,OrgWriteRequest q){var replacement=Create(r,q);foreach(var p in x.GetType().GetProperties().Where(p=>p.CanWrite&&p.Name is not ("Id" or "Version" or "CreatedAtUtc" or "UpdatedAtUtc" or "IsActive")))p.SetValue(x,p.GetValue(replacement));}
    private async Task WriteAudit(OrgEntity x,string action,JsonElement? before,OperationContext c,string? reason,CancellationToken ct){var e=new BusinessAuditEvent(Guid.CreateVersion7(),c.UserId,DateTimeOffset.UtcNow,c.CompanyId,c.BranchId,x.GetType().Name,x.Id,action,c.CorrelationId,reason,before,JsonSerializer.SerializeToElement(ToDto(x)));e.EnsureComplete();await audit.AppendAsync(e,ct);}
    private static OrgDto ToDto(OrgEntity x){var v=x.GetType().GetProperties().Where(p=>p.Name is not ("Id" or "IsActive" or "Version" or "CreatedAtUtc" or "UpdatedAtUtc" or "Code" or "ArabicName" or "EnglishName" or "LanguageCode")).ToDictionary(p=>p.Name,p=>p.GetValue(x)?.ToString());return x switch { Currency a=>new(a.Id,a.Code,a.ArabicName,a.EnglishName,a.IsActive,a.Version,v),Company a=>new(a.Id,a.Code,a.ArabicName,a.EnglishName,a.IsActive,a.Version,v),Branch a=>new(a.Id,a.Code,a.ArabicName,a.EnglishName,a.IsActive,a.Version,v),ExchangeRate a=>new(a.Id,Code(a),"سعر صرف",a.Source,a.IsActive,a.Version,v),FiscalYear a=>new(a.Id,a.Code,a.Code,a.Code,a.IsActive,a.Version,v),NumberSequence a=>new(a.Id,a.Code,a.ArabicName,a.EnglishName,a.IsActive,a.Version,v),Language a=>new(a.Id,a.LanguageCode,a.ArabicName,a.EnglishName,a.IsActive,a.Version,v),SettingOverride a=>new(a.Id,Code(a),"","",a.IsActive,a.Version,v),_=>throw new ArgumentOutOfRangeException()};}
    private static NumberReservationDto ToReservation(NumberReservation x)=>new(x.Id,x.SequenceId,x.NumberValue,x.RenderedNumber,x.State.ToString()); private static string? V(OrgWriteRequest q,string k)=>q.Values.TryGetValue(k,out var v)?v:null;private static Guid G(OrgWriteRequest q,string k)=>Guid.Parse(V(q,k)??throw new ArgumentException($"{k} is required."));private static Guid? GO(OrgWriteRequest q,string k)=>Guid.TryParse(V(q,k),out var g)?g:null;private static decimal D(OrgWriteRequest q,string k)=>decimal.Parse(V(q,k)??throw new ArgumentException($"{k} is required."));
}
