namespace TransportERP.Desktop.Waybills;

partial class UcItemRelease
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandView = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandSave = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandClose = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private System.ComponentModel.IContainer? components;
    private Panel pnlHeader = null!;
    private FlowLayoutPanel pnlToolbar = null!;
    private Label lblTitle = null!;
    private Panel pnlContent = null!;
    private TextBox _waybill = null!;
    private Label lblWaybill = null!;
    private TextBox _item = null!;
    private Label lblItem = null!;
    private TextBox _original = null!;
    private Label lblOriginal = null!;
    private TextBox _released = null!;
    private Label lblReleased = null!;
    private TextBox _remaining = null!;
    private Label lblRemaining = null!;
    private TextBox _holdStatus = null!;
    private Label lblHoldstatus = null!;
    private NumericUpDown _releaseQty = null!;
    private Label lblReleaseqty = null!;
    private TableLayoutPanel tlpFields = null!;
    private Button btnRelease = null!;
    private Label _message = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandView = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandSave = new Button();
        standardCommandPrint = new Button();
        standardCommandClose = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        components = new System.ComponentModel.Container();
        pnlHeader = new Panel();
        pnlToolbar = new FlowLayoutPanel();
        lblTitle = new Label();
        pnlContent = new Panel();
        _waybill = new TextBox();
        lblWaybill = new Label();
        _item = new TextBox();
        lblItem = new Label();
        _original = new TextBox();
        lblOriginal = new Label();
        _released = new TextBox();
        lblReleased = new Label();
        _remaining = new TextBox();
        lblRemaining = new Label();
        _holdStatus = new TextBox();
        lblHoldstatus = new Label();
        _releaseQty = new NumericUpDown();
        lblReleaseqty = new Label();
        tlpFields = new TableLayoutPanel();
        btnRelease = new Button();
        _message = new Label();
        SuspendLayout();
        pnlHeader.SuspendLayout();
        pnlToolbar.SuspendLayout();
        pnlContent.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)_releaseQty).BeginInit();
        tlpFields.SuspendLayout();
        pnlHeader.Name = "pnlHeader";
        pnlHeader.Dock = DockStyle.Top;
        pnlHeader.AutoSize = true;
        pnlHeader.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlHeader.MinimumSize = new Size(0, 48);
        pnlHeader.BackColor = Color.FromArgb(224, 224, 224);
        pnlToolbar.Name = "pnlToolbar";
        pnlToolbar.Dock = DockStyle.Top;
        pnlToolbar.AutoSize = true;
        pnlToolbar.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        pnlToolbar.WrapContents = true;
        pnlToolbar.Padding = new Padding(5);
        pnlToolbar.FlowDirection = FlowDirection.LeftToRight;
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "إطلاق كميات الأصناف — SHP-015";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Top;
        lblTitle.TextAlign = ContentAlignment.MiddleRight;
        lblTitle.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
        pnlContent.Name = "pnlContent";
        pnlContent.Dock = DockStyle.Fill;
        pnlContent.AutoScroll = true;
        pnlContent.BackColor = Color.LightCyan;
        _waybill.Name = "_waybill";
        _waybill.ReadOnly = true;
        _waybill.Size = new Size(280, 27);
        lblWaybill.Name = "lblWaybill";
        lblWaybill.Text = "البوليصة";
        lblWaybill.AutoSize = true;
        lblWaybill.Dock = DockStyle.Fill;
        lblWaybill.TextAlign = ContentAlignment.MiddleRight;
        _item.Name = "_item";
        _item.ReadOnly = true;
        _item.Size = new Size(280, 27);
        lblItem.Name = "lblItem";
        lblItem.Text = "الصنف";
        lblItem.AutoSize = true;
        lblItem.Dock = DockStyle.Fill;
        lblItem.TextAlign = ContentAlignment.MiddleRight;
        _original.Name = "_original";
        _original.ReadOnly = true;
        _original.Size = new Size(280, 27);
        lblOriginal.Name = "lblOriginal";
        lblOriginal.Text = "الكمية الأصلية";
        lblOriginal.AutoSize = true;
        lblOriginal.Dock = DockStyle.Fill;
        lblOriginal.TextAlign = ContentAlignment.MiddleRight;
        _released.Name = "_released";
        _released.ReadOnly = true;
        _released.Size = new Size(280, 27);
        lblReleased.Name = "lblReleased";
        lblReleased.Text = "المطلق";
        lblReleased.AutoSize = true;
        lblReleased.Dock = DockStyle.Fill;
        lblReleased.TextAlign = ContentAlignment.MiddleRight;
        _remaining.Name = "_remaining";
        _remaining.ReadOnly = true;
        _remaining.Size = new Size(280, 27);
        lblRemaining.Name = "lblRemaining";
        lblRemaining.Text = "المتبقي للإطلاق";
        lblRemaining.AutoSize = true;
        lblRemaining.Dock = DockStyle.Fill;
        lblRemaining.TextAlign = ContentAlignment.MiddleRight;
        _holdStatus.Name = "_holdStatus";
        _holdStatus.ReadOnly = true;
        _holdStatus.Size = new Size(280, 27);
        lblHoldstatus.Name = "lblHoldstatus";
        lblHoldstatus.Text = "حالة الحجز";
        lblHoldstatus.AutoSize = true;
        lblHoldstatus.Dock = DockStyle.Fill;
        lblHoldstatus.TextAlign = ContentAlignment.MiddleRight;
        _releaseQty.Name = "_releaseQty";
        _releaseQty.DecimalPlaces = 3;
        _releaseQty.Minimum = 0m;
        _releaseQty.Maximum = 1000000000m;
        _releaseQty.ThousandsSeparator = true;
        _releaseQty.Size = new Size(180, 27);
        lblReleaseqty.Name = "lblReleaseqty";
        lblReleaseqty.Text = "كمية الإطلاق";
        lblReleaseqty.AutoSize = true;
        lblReleaseqty.Dock = DockStyle.Fill;
        lblReleaseqty.TextAlign = ContentAlignment.MiddleRight;
        tlpFields.Name = "tlpFields";
        tlpFields.Dock = DockStyle.Top;
        tlpFields.AutoSize = true;
        tlpFields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        tlpFields.ColumnCount = 2;
        tlpFields.RowCount = 7;
        tlpFields.Padding = new Padding(8);
        btnRelease.Name = "btnRelease";
        btnRelease.Text = "إطلاق كمية";
        btnRelease.AutoSize = true;
        btnRelease.MinimumSize = new Size(70, 30);
        btnRelease.Dock = DockStyle.None;
        btnRelease.Margin = new Padding(4);
        _message.Name = "_message";
        _message.AutoSize = true;
        _message.Dock = DockStyle.Bottom;
        _message.Padding = new Padding(8);
        _message.TextAlign = ContentAlignment.MiddleRight;
        tlpFields.Controls.Add(lblWaybill, 0, 0);
        tlpFields.Controls.Add(_waybill, 1, 0);
        tlpFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        _waybill.Dock = DockStyle.Fill;
        _waybill.Margin = new Padding(3);
        tlpFields.Controls.Add(lblItem, 0, 1);
        tlpFields.Controls.Add(_item, 1, 1);
        tlpFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        _item.Dock = DockStyle.Fill;
        _item.Margin = new Padding(3);
        tlpFields.Controls.Add(lblOriginal, 0, 2);
        tlpFields.Controls.Add(_original, 1, 2);
        tlpFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        _original.Dock = DockStyle.Fill;
        _original.Margin = new Padding(3);
        tlpFields.Controls.Add(lblReleased, 0, 3);
        tlpFields.Controls.Add(_released, 1, 3);
        tlpFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        _released.Dock = DockStyle.Fill;
        _released.Margin = new Padding(3);
        tlpFields.Controls.Add(lblRemaining, 0, 4);
        tlpFields.Controls.Add(_remaining, 1, 4);
        tlpFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        _remaining.Dock = DockStyle.Fill;
        _remaining.Margin = new Padding(3);
        tlpFields.Controls.Add(lblHoldstatus, 0, 5);
        tlpFields.Controls.Add(_holdStatus, 1, 5);
        tlpFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        _holdStatus.Dock = DockStyle.Fill;
        _holdStatus.Margin = new Padding(3);
        tlpFields.Controls.Add(lblReleaseqty, 0, 6);
        tlpFields.Controls.Add(_releaseQty, 1, 6);
        tlpFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        _releaseQty.Dock = DockStyle.Fill;
        _releaseQty.Margin = new Padding(3);
        tlpFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 180F));
        tlpFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlToolbar.Controls.Add(btnRelease);
        btnRelease.Click += btnRelease_Click;
        pnlContent.Controls.Add(tlpFields);
        pnlHeader.Controls.Add(designerCommandBar);
        pnlHeader.Controls.Add(lblTitle);
        Controls.Add(pnlContent);
        Controls.Add(_message);
        Controls.Add(pnlHeader);
        AutoScaleDimensions = new SizeF(120F, 120F);
        AutoScaleMode = AutoScaleMode.Dpi;
        RightToLeft = RightToLeft.Yes;
        BackColor = Color.FromArgb(248, 250, 252);
        Name = "UcItemRelease";
        Text = "إطلاق كميات الأصناف — SHP-015";
        Size = new Size(760, 520);
        pnlHeader.ResumeLayout(false);
        pnlHeader.PerformLayout();
        pnlToolbar.ResumeLayout(false);
        pnlToolbar.PerformLayout();
        pnlContent.ResumeLayout(false);
        pnlContent.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)_releaseQty).EndInit();
        tlpFields.ResumeLayout(false);
        tlpFields.PerformLayout();
        ResumeLayout(false);
        PerformLayout();
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.Controls.Add(pnlToolbar);
        pnlToolbar.Dock = DockStyle.Fill;
        pnlToolbar.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        pnlToolbar.Name = "pnlToolbar";
        pnlToolbar.Dock = DockStyle.Fill;
        pnlToolbar.AutoSize = false;
        pnlToolbar.WrapContents = false;
        pnlToolbar.FlowDirection = FlowDirection.RightToLeft;
        pnlToolbar.RightToLeft = RightToLeft.No;
        pnlToolbar.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 44;
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = false;
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = false;
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = false;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = false;
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandView.Name = "standardCommandView";
        standardCommandView.Enabled = false;
        standardCommandView.Visible = true;
        standardCommandView.AccessibleName = "عرض";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = false;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = false;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = false;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = false;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandSave.Name = "standardCommandSave";
        standardCommandSave.Enabled = false;
        standardCommandSave.Visible = false;
        standardCommandSave.AccessibleName = "حفظ";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandClose.Name = "standardCommandClose";
        standardCommandClose.Enabled = false;
        standardCommandClose.Visible = true;
        standardCommandClose.AccessibleName = "إغلاق";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = true;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = true;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandAdd.AutoSize = false;
        standardCommandAdd.Dock = DockStyle.None;
        standardCommandAdd.MinimumSize = Size.Empty;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandAdd.Text = "";
        pnlToolbar.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.AutoSize = false;
        standardCommandEdit.Dock = DockStyle.None;
        standardCommandEdit.MinimumSize = Size.Empty;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandEdit.Text = "";
        pnlToolbar.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        pnlToolbar.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.AutoSize = false;
        standardCommandCancel.Dock = DockStyle.None;
        standardCommandCancel.MinimumSize = Size.Empty;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandCancel.Text = "";
        pnlToolbar.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        standardCommandView.AutoSize = false;
        standardCommandView.Dock = DockStyle.None;
        standardCommandView.MinimumSize = Size.Empty;
        standardCommandView.Size = new Size(26, 24);
        standardCommandView.Margin = new Padding(1);
        standardCommandView.FlatStyle = FlatStyle.Flat;
        standardCommandView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        standardCommandView.Text = "";
        pnlToolbar.Controls.Add(standardCommandView);
        designerCommandBar.SetCommandRole(standardCommandView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        pnlToolbar.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        pnlToolbar.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        pnlToolbar.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        pnlToolbar.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        standardCommandSave.AutoSize = false;
        standardCommandSave.Dock = DockStyle.None;
        standardCommandSave.MinimumSize = Size.Empty;
        standardCommandSave.Size = new Size(26, 24);
        standardCommandSave.Margin = new Padding(1);
        standardCommandSave.FlatStyle = FlatStyle.Flat;
        standardCommandSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        standardCommandSave.Text = "";
        pnlToolbar.Controls.Add(standardCommandSave);
        designerCommandBar.SetCommandRole(standardCommandSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        pnlToolbar.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        standardCommandClose.AutoSize = false;
        standardCommandClose.Dock = DockStyle.None;
        standardCommandClose.MinimumSize = Size.Empty;
        standardCommandClose.Size = new Size(26, 24);
        standardCommandClose.Margin = new Padding(1);
        standardCommandClose.FlatStyle = FlatStyle.Flat;
        standardCommandClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        standardCommandClose.Text = "";
        designerCloseHost.Controls.Add(standardCommandClose);
        standardCommandClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(standardCommandClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        pnlToolbar.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        pnlToolbar.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        pnlToolbar.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        pnlToolbar.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}
}
