namespace TransportERP.Desktop.Waybills;

partial class UcWaybillDraft
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandView = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private System.ComponentModel.IContainer? components;
    private TextBox _draftNo = null!;
    private TextBox _officialNo = null!;
    private TextBox _status = null!;
    private DataGridView _parties = null!;
    private DataGridView _items = null!;
    private Label _validation = null!;
    private FlowLayoutPanel pnlToolbar = null!;
    private TableLayoutPanel summary = null!;
    private TabControl tabs = null!;
    private Panel footer = null!;
    private TableLayoutPanel headerFields = null!;
    private Button btnNew = null!;
    private Button btnSave = null!;
    private Button btnSubmit = null!;
    private Button btnCancel = null!;
    private Button btnClose = null!;
    private Label lblDraftNo = null!;
    private Label lblOfficialNo = null!;
    private Label lblStatus = null!;
    private Label lblMeasurements = null!;
    private TabPage tpHeader = null!;
    private TabPage tpParties = null!;
    private TabPage tpItems = null!;
    private TabPage tpMeasurements = null!;
    private Label lblBranch = null!;
    private TextBox Branch = null!;
    private Label lblWaybillDateTime = null!;
    private TextBox WaybillDateTime = null!;
    private Label lblOrigin = null!;
    private TextBox Origin = null!;
    private Label lblDestination = null!;
    private TextBox Destination = null!;
    private Label lblCurrency = null!;
    private TextBox Currency = null!;
    private Label lblExchangeRate = null!;
    private TextBox ExchangeRate = null!;
    private Label lblServiceType = null!;
    private TextBox ServiceType = null!;
    private Label lblPriority = null!;
    private TextBox Priority = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCloseHost = new Panel();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandView = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandPrint = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        _draftNo = new TextBox();
        _officialNo = new TextBox();
        _status = new TextBox();
        _parties = new DataGridView();
        _items = new DataGridView();
        _validation = new Label();
        pnlToolbar = new FlowLayoutPanel();
        summary = new TableLayoutPanel();
        tabs = new TabControl();
        footer = new Panel();
        headerFields = new TableLayoutPanel();
        btnNew = new Button();
        btnSave = new Button();
        btnSubmit = new Button();
        btnCancel = new Button();
        btnClose = new Button();
        lblDraftNo = new Label();
        lblOfficialNo = new Label();
        lblStatus = new Label();
        lblMeasurements = new Label();
        tpHeader = new TabPage();
        tpParties = new TabPage();
        tpItems = new TabPage();
        tpMeasurements = new TabPage();
        lblBranch = new Label();
        Branch = new TextBox();
        lblWaybillDateTime = new Label();
        WaybillDateTime = new TextBox();
        lblOrigin = new Label();
        Origin = new TextBox();
        lblDestination = new Label();
        Destination = new TextBox();
        lblCurrency = new Label();
        Currency = new TextBox();
        lblExchangeRate = new Label();
        ExchangeRate = new TextBox();
        lblServiceType = new Label();
        ServiceType = new TextBox();
        lblPriority = new Label();
        Priority = new TextBox();
        SuspendLayout();
        _draftNo.Name = "_draftNo";
        _officialNo.Name = "_officialNo";
        _status.Name = "_status";
        ((System.ComponentModel.ISupportInitialize)_parties).BeginInit();
        _parties.Name = "_parties";
        ((System.ComponentModel.ISupportInitialize)_items).BeginInit();
        _items.Name = "_items";
        _validation.Name = "_validation";
        pnlToolbar.SuspendLayout();
        pnlToolbar.Name = "pnlToolbar";
        summary.SuspendLayout();
        summary.Name = "summary";
        tabs.SuspendLayout();
        tabs.Name = "tabs";
        footer.SuspendLayout();
        footer.Name = "footer";
        headerFields.SuspendLayout();
        headerFields.Name = "headerFields";
        btnNew.Name = "btnNew";
        btnSave.Name = "btnSave";
        btnSubmit.Name = "btnSubmit";
        btnCancel.Name = "btnCancel";
        btnClose.Name = "btnClose";
        lblDraftNo.Name = "lblDraftNo";
        lblOfficialNo.Name = "lblOfficialNo";
        lblStatus.Name = "lblStatus";
        lblMeasurements.Name = "lblMeasurements";
        tpHeader.SuspendLayout();
        tpHeader.Name = "tpHeader";
        tpParties.SuspendLayout();
        tpParties.Name = "tpParties";
        tpItems.SuspendLayout();
        tpItems.Name = "tpItems";
        tpMeasurements.SuspendLayout();
        tpMeasurements.Name = "tpMeasurements";
        lblBranch.Name = "lblBranch";
        Branch.Name = "Branch";
        lblWaybillDateTime.Name = "lblWaybillDateTime";
        WaybillDateTime.Name = "WaybillDateTime";
        lblOrigin.Name = "lblOrigin";
        Origin.Name = "Origin";
        lblDestination.Name = "lblDestination";
        Destination.Name = "Destination";
        lblCurrency.Name = "lblCurrency";
        Currency.Name = "Currency";
        lblExchangeRate.Name = "lblExchangeRate";
        ExchangeRate.Name = "ExchangeRate";
        lblServiceType.Name = "lblServiceType";
        ServiceType.Name = "ServiceType";
        lblPriority.Name = "lblPriority";
        Priority.Name = "Priority";
        Text = "البوليصة — SHP-005";
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1000, 680);
        pnlToolbar.Dock = DockStyle.Top;
        pnlToolbar.FlowDirection = FlowDirection.RightToLeft;
        pnlToolbar.Height = 48;
        pnlToolbar.Padding = new Padding(8);
        btnNew.Text = "جديد";
        btnNew.AutoSize = true;
        btnNew.Click += BtnNew_Click;

        btnSave.Text = "حفظ مسودة";
        btnSave.AutoSize = true;
        btnSave.Click += BtnSave_Click;

        btnSubmit.Text = "إرسال للاعتماد";
        btnSubmit.AutoSize = true;
        btnSubmit.Click += BtnSubmit_Click;
        pnlToolbar.Controls.Add(btnSubmit);
        btnCancel.Text = "إلغاء";
        btnCancel.AutoSize = true;
        btnCancel.Click += BtnCancel_Click;

        btnClose.Text = "إغلاق";
        btnClose.AutoSize = true;
        btnClose.Click += BtnClose_Click;

        summary.Dock = DockStyle.Top;
        summary.Height = 78;
        summary.ColumnCount = 6;
        summary.RowCount = 1;
        summary.Padding = new Padding(8);
        summary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.66F));
        summary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.66F));
        summary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.66F));
        summary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.66F));
        summary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.66F));
        summary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.66F));
        lblDraftNo.Text = "رقم المسودة";
        lblDraftNo.AutoSize = true;
        lblDraftNo.Anchor = AnchorStyles.Right;
        _draftNo.ReadOnly = true;
        _draftNo.Dock = DockStyle.Fill;
        summary.Controls.Add(lblDraftNo, 0, 0);
        summary.Controls.Add(_draftNo, 1, 0);
        lblOfficialNo.Text = "رقم البوليصة";
        lblOfficialNo.AutoSize = true;
        lblOfficialNo.Anchor = AnchorStyles.Right;
        _officialNo.ReadOnly = true;
        _officialNo.Dock = DockStyle.Fill;
        summary.Controls.Add(lblOfficialNo, 2, 0);
        summary.Controls.Add(_officialNo, 3, 0);
        lblStatus.Text = "الحالة";
        lblStatus.AutoSize = true;
        lblStatus.Anchor = AnchorStyles.Right;
        _status.ReadOnly = true;
        _status.Dock = DockStyle.Fill;
        summary.Controls.Add(lblStatus, 4, 0);
        summary.Controls.Add(_status, 5, 0);
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeft = RightToLeft.Yes;
        tabs.RightToLeftLayout = true;
        tpHeader.Text = "SHP-005 — البيانات الأساسية";
        tpHeader.RightToLeft = RightToLeft.Yes;
        tabs.Controls.Add(tpHeader);
        tpParties.Text = "SHP-006 — المرسل والمستلم والدافع";
        tpParties.RightToLeft = RightToLeft.Yes;
        tabs.Controls.Add(tpParties);
        tpItems.Text = "SHP-007 — الأصناف";
        tpItems.RightToLeft = RightToLeft.Yes;
        tabs.Controls.Add(tpItems);
        tpMeasurements.Text = "SHP-008 — الأوزان والأبعاد والقيم";
        tpMeasurements.RightToLeft = RightToLeft.Yes;
        tabs.Controls.Add(tpMeasurements);
        headerFields.Dock = DockStyle.Top;
        headerFields.AutoSize = true;
        headerFields.ColumnCount = 4;
        headerFields.RowCount = 8;
        headerFields.Padding = new Padding(12);
        lblBranch.Text = "الفرع *";
        lblBranch.AutoSize = true;
        lblBranch.Anchor = AnchorStyles.Right;
        Branch.Width = 280;
        Branch.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        headerFields.Controls.Add(lblBranch, 0, 0);
        headerFields.Controls.Add(Branch, 1, 0);
        lblWaybillDateTime.Text = "تاريخ البوليصة *";
        lblWaybillDateTime.AutoSize = true;
        lblWaybillDateTime.Anchor = AnchorStyles.Right;
        WaybillDateTime.Width = 280;
        WaybillDateTime.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        headerFields.Controls.Add(lblWaybillDateTime, 2, 1);
        headerFields.Controls.Add(WaybillDateTime, 3, 1);
        lblOrigin.Text = "المنشأ *";
        lblOrigin.AutoSize = true;
        lblOrigin.Anchor = AnchorStyles.Right;
        Origin.Width = 280;
        Origin.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        headerFields.Controls.Add(lblOrigin, 0, 2);
        headerFields.Controls.Add(Origin, 1, 2);
        lblDestination.Text = "الوجهة *";
        lblDestination.AutoSize = true;
        lblDestination.Anchor = AnchorStyles.Right;
        Destination.Width = 280;
        Destination.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        headerFields.Controls.Add(lblDestination, 2, 3);
        headerFields.Controls.Add(Destination, 3, 3);
        lblCurrency.Text = "العملة *";
        lblCurrency.AutoSize = true;
        lblCurrency.Anchor = AnchorStyles.Right;
        Currency.Width = 280;
        Currency.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        headerFields.Controls.Add(lblCurrency, 0, 4);
        headerFields.Controls.Add(Currency, 1, 4);
        lblExchangeRate.Text = "سعر الصرف *";
        lblExchangeRate.AutoSize = true;
        lblExchangeRate.Anchor = AnchorStyles.Right;
        ExchangeRate.Width = 280;
        ExchangeRate.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        headerFields.Controls.Add(lblExchangeRate, 2, 5);
        headerFields.Controls.Add(ExchangeRate, 3, 5);
        lblServiceType.Text = "نوع الخدمة";
        lblServiceType.AutoSize = true;
        lblServiceType.Anchor = AnchorStyles.Right;
        ServiceType.Width = 280;
        ServiceType.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        headerFields.Controls.Add(lblServiceType, 0, 6);
        headerFields.Controls.Add(ServiceType, 1, 6);
        lblPriority.Text = "الأولوية";
        lblPriority.AutoSize = true;
        lblPriority.Anchor = AnchorStyles.Right;
        Priority.Width = 280;
        Priority.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        headerFields.Controls.Add(lblPriority, 2, 7);
        headerFields.Controls.Add(Priority, 3, 7);
        tpHeader.Controls.Add(headerFields);
        _parties.AllowUserToAddRows = false;
        _parties.AllowUserToDeleteRows = false;
        _parties.AutoGenerateColumns = true;
        _parties.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
        _parties.ReadOnly = true;
        _parties.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        _parties.MultiSelect = false;
        _parties.RightToLeft = RightToLeft.Yes;
        _parties.Dock = DockStyle.Fill;
        tpParties.Controls.Add(_parties);
        _items.AllowUserToAddRows = false;
        _items.AllowUserToDeleteRows = false;
        _items.AutoGenerateColumns = true;
        _items.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
        _items.ReadOnly = true;
        _items.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        _items.MultiSelect = false;
        _items.RightToLeft = RightToLeft.Yes;
        _items.Dock = DockStyle.Fill;
        tpItems.Controls.Add(_items);
        lblMeasurements.Dock = DockStyle.Top;
        lblMeasurements.AutoSize = true;
        lblMeasurements.Padding = new Padding(12);
        lblMeasurements.Text = "الوزن والطول والعرض والارتفاع والقيمة المعلنة تُحرر داخل سطر الصنف، ولا تقبل قيماً سالبة.";
        tpMeasurements.Controls.Add(lblMeasurements);
        footer.Dock = DockStyle.Bottom;
        footer.Height = 48;
        footer.Padding = new Padding(8);
        _validation.AutoSize = true;
        _validation.Dock = DockStyle.Right;
        footer.Controls.Add(_validation);
        Controls.Add(tabs);
        Controls.Add(footer);
        Controls.Add(summary);
        Controls.Add(designerCommandBar);
        AutoScaleMode = AutoScaleMode.None;
        Name = "UcWaybillDraft";
        tpMeasurements.ResumeLayout(false);
        tpMeasurements.PerformLayout();
        tpItems.ResumeLayout(false);
        tpItems.PerformLayout();
        tpParties.ResumeLayout(false);
        tpParties.PerformLayout();
        tpHeader.ResumeLayout(false);
        tpHeader.PerformLayout();
        headerFields.ResumeLayout(false);
        headerFields.PerformLayout();
        footer.ResumeLayout(false);
        footer.PerformLayout();
        tabs.ResumeLayout(false);
        tabs.PerformLayout();
        summary.ResumeLayout(false);
        summary.PerformLayout();
        pnlToolbar.ResumeLayout(false);
        pnlToolbar.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)_items).EndInit();
        ((System.ComponentModel.ISupportInitialize)_parties).EndInit();
        ResumeLayout(false);
        PerformLayout();
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.Controls.Add(pnlToolbar);
        pnlToolbar.Dock = DockStyle.Fill;
        pnlToolbar.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        pnlToolbar.Name = "pnlToolbar";
        pnlToolbar.Dock = DockStyle.Fill;
        pnlToolbar.AutoSize = false;
        pnlToolbar.WrapContents = false;
        pnlToolbar.FlowDirection = FlowDirection.RightToLeft;
        pnlToolbar.RightToLeft = RightToLeft.No;
        pnlToolbar.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 44;
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = true;
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandView.Name = "standardCommandView";
        standardCommandView.Enabled = false;
        standardCommandView.Visible = true;
        standardCommandView.AccessibleName = "عرض";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        btnNew.AutoSize = false;
        btnNew.Dock = DockStyle.None;
        btnNew.MinimumSize = Size.Empty;
        btnNew.Size = new Size(26, 24);
        btnNew.Margin = new Padding(1);
        btnNew.FlatStyle = FlatStyle.Flat;
        btnNew.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnNew.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        btnNew.Text = "";
        pnlToolbar.Controls.Add(btnNew);
        designerCommandBar.SetCommandRole(btnNew, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.AutoSize = false;
        standardCommandEdit.Dock = DockStyle.None;
        standardCommandEdit.MinimumSize = Size.Empty;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandEdit.Text = "";
        pnlToolbar.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        pnlToolbar.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        btnCancel.AutoSize = false;
        btnCancel.Dock = DockStyle.None;
        btnCancel.MinimumSize = Size.Empty;
        btnCancel.Size = new Size(26, 24);
        btnCancel.Margin = new Padding(1);
        btnCancel.FlatStyle = FlatStyle.Flat;
        btnCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        btnCancel.Text = "";
        pnlToolbar.Controls.Add(btnCancel);
        designerCommandBar.SetCommandRole(btnCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        standardCommandView.AutoSize = false;
        standardCommandView.Dock = DockStyle.None;
        standardCommandView.MinimumSize = Size.Empty;
        standardCommandView.Size = new Size(26, 24);
        standardCommandView.Margin = new Padding(1);
        standardCommandView.FlatStyle = FlatStyle.Flat;
        standardCommandView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        standardCommandView.Text = "";
        pnlToolbar.Controls.Add(standardCommandView);
        designerCommandBar.SetCommandRole(standardCommandView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        pnlToolbar.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        pnlToolbar.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        pnlToolbar.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        pnlToolbar.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        btnSave.AutoSize = false;
        btnSave.Dock = DockStyle.None;
        btnSave.MinimumSize = Size.Empty;
        btnSave.Size = new Size(26, 24);
        btnSave.Margin = new Padding(1);
        btnSave.FlatStyle = FlatStyle.Flat;
        btnSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        btnSave.Text = "";
        pnlToolbar.Controls.Add(btnSave);
        designerCommandBar.SetCommandRole(btnSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        pnlToolbar.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        btnClose.AutoSize = false;
        btnClose.Dock = DockStyle.None;
        btnClose.MinimumSize = Size.Empty;
        btnClose.Size = new Size(26, 24);
        btnClose.Margin = new Padding(1);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        btnClose.Text = "";
        designerCloseHost.Controls.Add(btnClose);
        btnClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        pnlToolbar.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        pnlToolbar.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        pnlToolbar.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        pnlToolbar.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}
}
