using System.ComponentModel;
namespace TransportERP.Desktop;
partial class ReceiptConfigurationDialog
{
    private ComboBox treatment = null!;
    private Label labeltreatment = null!;
    private ComboBox receivable = null!;
    private Label labelreceivable = null!;
    private ComboBox rounding = null!;
    private Label labelrounding = null!;
    private ComboBox sequence = null!;
    private Label labelsequence = null!;
    private ComboBox defaultCurrency = null!;
    private Label labeldefaultCurrency = null!;
    private ComboBox centerSource = null!;
    private Label labelcenterSource = null!;
    private ComboBox defaultCenter = null!;
    private Label labeldefaultCenter = null!;
    private ComboBox projectSource = null!;
    private Label labelprojectSource = null!;
    private ComboBox activitySource = null!;
    private Label labelactivitySource = null!;
    private ComboBox postingDimension = null!;
    private Label labelpostingDimension = null!;
    private TableLayoutPanel layoutRoot = null!;
    private TabControl tabs = null!;
    private TabPage destinationPage = null!;
    private TabPage typePage = null!;
    private TabPage collectorPage = null!;
    private TabPage salespersonPage = null!;
    private DataGridView destinationGrid = null!;
    private DataGridView typeGrid = null!;
    private DataGridViewTextBoxColumn colDestinationLabel = null!;
    private DataGridViewComboBoxColumn colDestinationKind = null!;
    private DataGridViewComboBoxColumn colDestinationAccount = null!;
    private DataGridViewTextBoxColumn colTypeLabel = null!;
    private DataGridViewCheckBoxColumn colRequiresWaybill = null!;
    private CheckedListBox collectors = null!;
    private CheckedListBox salespeople = null!;
    private FlowLayoutPanel bottom = null!;
    private Button save = null!;
    private Label policyNotice = null!;
    private void InitializeComponent()
    {
        treatment = new ComboBox();
        labeltreatment = new Label();
        receivable = new ComboBox();
        labelreceivable = new Label();
        rounding = new ComboBox();
        labelrounding = new Label();
        sequence = new ComboBox();
        labelsequence = new Label();
        defaultCurrency = new ComboBox();
        labeldefaultCurrency = new Label();
        centerSource = new ComboBox();
        labelcenterSource = new Label();
        defaultCenter = new ComboBox();
        labeldefaultCenter = new Label();
        projectSource = new ComboBox();
        labelprojectSource = new Label();
        activitySource = new ComboBox();
        labelactivitySource = new Label();
        postingDimension = new ComboBox();
        labelpostingDimension = new Label();
        layoutRoot = new TableLayoutPanel();
        tabs = new TabControl();
        destinationPage = new TabPage();
        typePage = new TabPage();
        collectorPage = new TabPage();
        salespersonPage = new TabPage();
        destinationGrid = new DataGridView();
        typeGrid = new DataGridView();
        colDestinationLabel = new DataGridViewTextBoxColumn();
        colDestinationKind = new DataGridViewComboBoxColumn();
        colDestinationAccount = new DataGridViewComboBoxColumn();
        colTypeLabel = new DataGridViewTextBoxColumn();
        colRequiresWaybill = new DataGridViewCheckBoxColumn();
        collectors = new CheckedListBox();
        salespeople = new CheckedListBox();
        bottom = new FlowLayoutPanel();
        save = new Button();
        policyNotice = new Label();
        SuspendLayout();
        layoutRoot.SuspendLayout();
        tabs.SuspendLayout();
        ((ISupportInitialize)destinationGrid).BeginInit();
        ((ISupportInitialize)typeGrid).BeginInit();
        Text = "إعدادات سند القبض — الشركة الحالية";
        Width = 1000;
        Height = 750;
        MinimumSize = new Size(900,700);
        AutoScaleMode = AutoScaleMode.Font;
        Font = new Font("Segoe UI",10F);
        BackColor = Color.FromArgb(248,250,252);
        RightToLeft = RightToLeft.Yes;
        RightToLeftLayout = true;
        StartPosition = FormStartPosition.CenterParent;
        Name = "ReceiptConfigurationDialog";
        layoutRoot.Name = "layoutRoot";
        layoutRoot.Dock = DockStyle.Fill;
        layoutRoot.ColumnCount = 2;
        layoutRoot.RowCount = 12;
        layoutRoot.Padding = new Padding(4);
        layoutRoot.Margin = new Padding(0);
        layoutRoot.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,210F));
        layoutRoot.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute,32F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute,65F));
        treatment.Name = "treatment";
        treatment.DropDownStyle = ComboBoxStyle.DropDownList;
        treatment.Dock = DockStyle.Fill;
        labeltreatment.Name = "labeltreatment";
        labeltreatment.Text = "معالجة الشيك";
        labeltreatment.Dock = DockStyle.Fill;
        labeltreatment.TextAlign = ContentAlignment.MiddleLeft;
        layoutRoot.Controls.Add(labeltreatment,0,0);
        layoutRoot.Controls.Add(treatment,1,0);
        receivable.Name = "receivable";
        receivable.DropDownStyle = ComboBoxStyle.DropDownList;
        receivable.Dock = DockStyle.Fill;
        labelreceivable.Name = "labelreceivable";
        labelreceivable.Text = "حساب أوراق القبض";
        labelreceivable.Dock = DockStyle.Fill;
        labelreceivable.TextAlign = ContentAlignment.MiddleLeft;
        layoutRoot.Controls.Add(labelreceivable,0,1);
        layoutRoot.Controls.Add(receivable,1,1);
        rounding.Name = "rounding";
        rounding.DropDownStyle = ComboBoxStyle.DropDownList;
        rounding.Dock = DockStyle.Fill;
        labelrounding.Name = "labelrounding";
        labelrounding.Text = "التقريب للعملة الأساسية";
        labelrounding.Dock = DockStyle.Fill;
        labelrounding.TextAlign = ContentAlignment.MiddleLeft;
        layoutRoot.Controls.Add(labelrounding,0,2);
        layoutRoot.Controls.Add(rounding,1,2);
        sequence.Name = "sequence";
        sequence.DropDownStyle = ComboBoxStyle.DropDownList;
        sequence.Dock = DockStyle.Fill;
        labelsequence.Name = "labelsequence";
        labelsequence.Text = "تسلسل ترقيم القبض";
        labelsequence.Dock = DockStyle.Fill;
        labelsequence.TextAlign = ContentAlignment.MiddleLeft;
        layoutRoot.Controls.Add(labelsequence,0,3);
        layoutRoot.Controls.Add(sequence,1,3);
        defaultCurrency.Name = "defaultCurrency";
        defaultCurrency.DropDownStyle = ComboBoxStyle.DropDownList;
        defaultCurrency.Dock = DockStyle.Fill;
        labeldefaultCurrency.Name = "labeldefaultCurrency";
        labeldefaultCurrency.Text = "العملة الافتراضية للسند";
        labeldefaultCurrency.Dock = DockStyle.Fill;
        labeldefaultCurrency.TextAlign = ContentAlignment.MiddleLeft;
        layoutRoot.Controls.Add(labeldefaultCurrency,0,4);
        layoutRoot.Controls.Add(defaultCurrency,1,4);
        centerSource.Name = "centerSource";
        centerSource.DropDownStyle = ComboBoxStyle.DropDownList;
        centerSource.Dock = DockStyle.Fill;
        labelcenterSource.Name = "labelcenterSource";
        labelcenterSource.Text = "مصدر مراكز التكلفة";
        labelcenterSource.Dock = DockStyle.Fill;
        labelcenterSource.TextAlign = ContentAlignment.MiddleLeft;
        layoutRoot.Controls.Add(labelcenterSource,0,5);
        layoutRoot.Controls.Add(centerSource,1,5);
        defaultCenter.Name = "defaultCenter";
        defaultCenter.DropDownStyle = ComboBoxStyle.DropDownList;
        defaultCenter.Dock = DockStyle.Fill;
        labeldefaultCenter.Name = "labeldefaultCenter";
        labeldefaultCenter.Text = "مركز التكلفة الافتراضي";
        labeldefaultCenter.Dock = DockStyle.Fill;
        labeldefaultCenter.TextAlign = ContentAlignment.MiddleLeft;
        layoutRoot.Controls.Add(labeldefaultCenter,0,6);
        layoutRoot.Controls.Add(defaultCenter,1,6);
        projectSource.Name = "projectSource";
        projectSource.DropDownStyle = ComboBoxStyle.DropDownList;
        projectSource.Dock = DockStyle.Fill;
        labelprojectSource.Name = "labelprojectSource";
        labelprojectSource.Text = "مصدر المشروعات";
        labelprojectSource.Dock = DockStyle.Fill;
        labelprojectSource.TextAlign = ContentAlignment.MiddleLeft;
        layoutRoot.Controls.Add(labelprojectSource,0,7);
        layoutRoot.Controls.Add(projectSource,1,7);
        activitySource.Name = "activitySource";
        activitySource.DropDownStyle = ComboBoxStyle.DropDownList;
        activitySource.Dock = DockStyle.Fill;
        labelactivitySource.Name = "labelactivitySource";
        labelactivitySource.Text = "مصدر الأنشطة";
        labelactivitySource.Dock = DockStyle.Fill;
        labelactivitySource.TextAlign = ContentAlignment.MiddleLeft;
        layoutRoot.Controls.Add(labelactivitySource,0,8);
        layoutRoot.Controls.Add(activitySource,1,8);
        postingDimension.Name = "postingDimension";
        postingDimension.DropDownStyle = ComboBoxStyle.DropDownList;
        postingDimension.Dock = DockStyle.Fill;
        labelpostingDimension.Name = "labelpostingDimension";
        labelpostingDimension.Text = "البعد المرحّل (واحد فقط)";
        labelpostingDimension.Dock = DockStyle.Fill;
        labelpostingDimension.TextAlign = ContentAlignment.MiddleLeft;
        layoutRoot.Controls.Add(labelpostingDimension,0,9);
        layoutRoot.Controls.Add(postingDimension,1,9);
        centerSource.SelectedIndexChanged += centerSource_SelectedIndexChanged;
        tabs.Name = "tabs";
        tabs.Dock = DockStyle.Fill;
        tabs.RightToLeft = RightToLeft.Yes;
        tabs.RightToLeftLayout = true;
        layoutRoot.Controls.Add(tabs,0,10);
        layoutRoot.SetColumnSpan(tabs,2);
        tabs.Controls.Add(destinationPage);
        tabs.Controls.Add(typePage);
        tabs.Controls.Add(collectorPage);
        tabs.Controls.Add(salespersonPage);
        destinationPage.Name = "destinationPage";
        destinationPage.Text = "وجهات القبض وحساباتها";
        destinationPage.Controls.Add(destinationGrid);
        typePage.Name = "typePage";
        typePage.Text = "أنواع السند";
        typePage.Controls.Add(typeGrid);
        collectorPage.Name = "collectorPage";
        collectorPage.Text = "المحصلون المسموحون";
        collectorPage.Controls.Add(collectors);
        salespersonPage.Name = "salespersonPage";
        salespersonPage.Text = "المندوبون المسموحون";
        salespersonPage.Controls.Add(salespeople);
        destinationGrid.Name = "destinationGrid";
        destinationGrid.Dock = DockStyle.Fill;
        destinationGrid.AutoGenerateColumns = false;
        destinationGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        destinationGrid.Columns.AddRange(colDestinationLabel,colDestinationKind,colDestinationAccount);
        destinationGrid.DataError += grid_DataError;
        colDestinationLabel.Name = "colDestinationLabel";
        colDestinationLabel.DataPropertyName = "Label";
        colDestinationLabel.HeaderText = "اسم وجهة القبض";
        colDestinationKind.Name = "colDestinationKind";
        colDestinationKind.DataPropertyName = "Kind";
        colDestinationKind.HeaderText = "النوع";
        colDestinationKind.ValueMember = "Id";
        colDestinationKind.DisplayMember = "Label";
        colDestinationAccount.Name = "colDestinationAccount";
        colDestinationAccount.DataPropertyName = "AccountId";
        colDestinationAccount.HeaderText = "الحساب المحاسبي";
        colDestinationAccount.ValueMember = "Id";
        colDestinationAccount.DisplayMember = "Label";
        typeGrid.Name = "typeGrid";
        typeGrid.Dock = DockStyle.Fill;
        typeGrid.AutoGenerateColumns = false;
        typeGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        typeGrid.Columns.AddRange(colTypeLabel,colRequiresWaybill);
        typeGrid.DataError += grid_DataError;
        colTypeLabel.Name = "colTypeLabel";
        colTypeLabel.DataPropertyName = "Label";
        colTypeLabel.HeaderText = "اسم نوع السند";
        colRequiresWaybill.Name = "colRequiresWaybill";
        colRequiresWaybill.DataPropertyName = "RequiresWaybill";
        colRequiresWaybill.HeaderText = "قبض بوليصة — رقم البوليصة إلزامي";
        collectors.Name = "collectors";
        collectors.Dock = DockStyle.Fill;
        collectors.CheckOnClick = true;
        salespeople.Name = "salespeople";
        salespeople.Dock = DockStyle.Fill;
        salespeople.CheckOnClick = true;
        bottom.Name = "bottom";
        bottom.Dock = DockStyle.Fill;
        bottom.FlowDirection = FlowDirection.RightToLeft;
        save.Name = "save";
        save.Text = "حفظ الإعدادات";
        save.AutoSize = true;
        save.Click += save_Click;
        policyNotice.Name = "policyNotice";
        policyNotice.AutoSize = true;
        policyNotice.Text = "سعر رأس السند: وحدة من عملة السند = السعر بالعملة الأساسية.\nسياسة السند المرحّل محفوظة؛ تحصيل أوراق القبض اللاحق عملية منفصلة.";
        bottom.Controls.Add(save);
        bottom.Controls.Add(policyNotice);
        layoutRoot.Controls.Add(bottom,0,11);
        layoutRoot.SetColumnSpan(bottom,2);
        Controls.Add(layoutRoot);
        ((ISupportInitialize)destinationGrid).EndInit();
        ((ISupportInitialize)typeGrid).EndInit();
        tabs.ResumeLayout(false);
        layoutRoot.ResumeLayout(false);
        ResumeLayout(false);
    }
}
