#nullable enable
namespace TransportERP.Desktop.Forms.SystemSettings.General;

partial class FrmAccountingImportPreview
{
    private System.ComponentModel.IContainer? components;
    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private FlowLayoutPanel commandFlow = null!;
    private Button btnClose = null!;
    private Button btnImport = null!;
    private TableLayoutPanel importLayout = null!;
    private TableLayoutPanel pathLayout = null!;
    private Label lblFilePath = null!;
    private TextBox txtFilePath = null!;
    private Button btnBrowse = null!;
    private Button btnReadFile = null!;
    private Label lblOrder = null!;
    private Label lblNotes = null!;
    private DataGridView previewGrid = null!;
    private Panel referenceFooter = null!;
    private DataGridViewTextBoxColumn colRow = null!;
    private DataGridViewTextBoxColumn colAccount = null!;
    private DataGridViewTextBoxColumn colCurrency = null!;
    private DataGridViewTextBoxColumn colNameLocal = null!;
    private DataGridViewTextBoxColumn colNameForeign = null!;
    private DataGridViewTextBoxColumn colParent = null!;
    private DataGridViewTextBoxColumn colLevel = null!;
    private DataGridViewTextBoxColumn colKind = null!;
    private DataGridViewTextBoxColumn colReport = null!;
    private DataGridViewTextBoxColumn colGroup = null!;
    private DataGridViewTextBoxColumn colNature = null!;
    private DataGridViewTextBoxColumn colAccountType = null!;
    private DataGridViewTextBoxColumn colAnalysis = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        SuspendLayout();
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        commandFlow = new FlowLayoutPanel();
        btnClose = new Button();
        btnImport = new Button();
        importLayout = new TableLayoutPanel();
        pathLayout = new TableLayoutPanel();
        lblFilePath = new Label();
        txtFilePath = new TextBox();
        btnBrowse = new Button();
        btnReadFile = new Button();
        lblOrder = new Label();
        lblNotes = new Label();
        previewGrid = new DataGridView();
        referenceFooter = new Panel();
        colRow = new DataGridViewTextBoxColumn();
        colAccount = new DataGridViewTextBoxColumn();
        colCurrency = new DataGridViewTextBoxColumn();
        colNameLocal = new DataGridViewTextBoxColumn();
        colNameForeign = new DataGridViewTextBoxColumn();
        colParent = new DataGridViewTextBoxColumn();
        colLevel = new DataGridViewTextBoxColumn();
        colKind = new DataGridViewTextBoxColumn();
        colReport = new DataGridViewTextBoxColumn();
        colGroup = new DataGridViewTextBoxColumn();
        colNature = new DataGridViewTextBoxColumn();
        colAccountType = new DataGridViewTextBoxColumn();
        colAnalysis = new DataGridViewTextBoxColumn();
        ((System.ComponentModel.ISupportInitialize)previewGrid).BeginInit();
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.Height = 40;
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        commandFlow.Name = "commandFlow";
        commandFlow.Dock = DockStyle.Fill;
        commandFlow.FlowDirection = FlowDirection.RightToLeft;
        commandFlow.RightToLeft = RightToLeft.No;
        commandFlow.Padding = new Padding(3);
        commandFlow.WrapContents = false;
        btnClose.Name = "btnClose";
        btnClose.AccessibleName = "إغلاق";
        btnClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        btnClose.Size = new Size(30, 28);
        btnClose.Click += btnClose_Click;
        btnImport.Name = "btnImport";
        btnImport.AccessibleName = "استيراد";
        btnImport.Text = "استيراد";
        btnImport.Size = new Size(90, 28);
        btnImport.Enabled = false;
        commandFlow.Controls.Add(btnClose);
        commandFlow.Controls.Add(btnImport);
        designerCommandBar.Controls.Add(commandFlow);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        designerCommandBar.SetCommandRole(btnImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        importLayout.Name = "importLayout";
        importLayout.Dock = DockStyle.Fill;
        importLayout.Padding = new Padding(12);
        importLayout.ColumnCount = 1;
        importLayout.RowCount = 4;
        importLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        importLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        importLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        importLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        importLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        pathLayout.Name = "pathLayout";
        pathLayout.Dock = DockStyle.Fill;
        pathLayout.ColumnCount = 3;
        pathLayout.RowCount = 2;
        pathLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 55F));
        pathLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 45F));
        pathLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 165F));
        pathLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pathLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 38F));
        lblFilePath.Name = "lblFilePath";
        lblFilePath.Text = "مسار برنامج الإكسل";
        lblFilePath.Dock = DockStyle.Fill;
        lblFilePath.TextAlign = ContentAlignment.MiddleRight;
        txtFilePath.Name = "txtFilePath";
        txtFilePath.Dock = DockStyle.Fill;
        txtFilePath.ReadOnly = true;
        txtFilePath.RightToLeft = RightToLeft.No;
        txtFilePath.BackColor = Color.White;
        txtFilePath.Margin = new Padding(3, 10, 3, 3);
        btnBrowse.Name = "btnBrowse";
        btnBrowse.Text = "…";
        btnBrowse.Dock = DockStyle.Fill;
        btnBrowse.Enabled = false;
        pathLayout.Controls.Add(lblFilePath, 0, 0);
        pathLayout.Controls.Add(txtFilePath, 1, 0);
        pathLayout.Controls.Add(btnBrowse, 2, 0);
        btnReadFile.Name = "btnReadFile";
        btnReadFile.Text = "استيراد من ملف إكسل";
        btnReadFile.Anchor = AnchorStyles.None;
        btnReadFile.AutoSize = true;
        btnReadFile.MinimumSize = new Size(180, 28);
        btnReadFile.Enabled = false;
        pathLayout.Controls.Add(btnReadFile, 1, 1);
        lblOrder.Name = "lblOrder";
        lblOrder.Text = "ترتيب الملف: رقم الحساب - العملة - اسم الحساب - الاسم الأجنبي - الحساب الرئيسي - المستوى - النوع - نوع التقرير - المجموعة - طبيعة الحساب - نوع الحساب - تحليل الحساب";
        lblOrder.ForeColor = Color.Firebrick;
        lblOrder.Dock = DockStyle.Fill;
        lblOrder.AutoSize = true;
        lblOrder.Padding = new Padding(6);
        lblNotes.Name = "lblNotes";
        lblNotes.Text = "معاينة قالب الاستيراد. قراءة الملف والاستيراد غير متاحين حاليًا.";
        lblNotes.Dock = DockStyle.Fill;
        lblNotes.AutoSize = true;
        lblNotes.Padding = new Padding(6, 4, 6, 12);
        previewGrid.Name = "previewGrid";
        previewGrid.Dock = DockStyle.Fill;
        previewGrid.BackgroundColor = Color.White;
        previewGrid.GridColor = Color.Silver;
        previewGrid.ReadOnly = true;
        previewGrid.AllowUserToAddRows = false;
        previewGrid.AllowUserToDeleteRows = false;
        previewGrid.AllowUserToOrderColumns = false;
        previewGrid.RowHeadersVisible = false;
        previewGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        previewGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.EnableResizing;
        previewGrid.ColumnHeadersHeight = 42;
        previewGrid.RowTemplate.Height = 24;
        previewGrid.EnableHeadersVisualStyles = false;
        previewGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(239, 239, 239);
        previewGrid.ColumnHeadersDefaultCellStyle.WrapMode = DataGridViewTriState.True;
        previewGrid.Paint += previewGrid_Paint;
        colRow.Name = "colRow";
        colRow.HeaderText = "م";
        colRow.FillWeight = 25;
        colAccount.Name = "colAccount";
        colAccount.HeaderText = "رقم الحساب";
        colAccount.FillWeight = 75;
        colCurrency.Name = "colCurrency";
        colCurrency.HeaderText = "العملة";
        colCurrency.FillWeight = 55;
        colNameLocal.Name = "colNameLocal";
        colNameLocal.HeaderText = "اسم الحساب";
        colNameLocal.FillWeight = 140;
        colNameForeign.Name = "colNameForeign";
        colNameForeign.HeaderText = "الاسم الأجنبي";
        colNameForeign.FillWeight = 130;
        colParent.Name = "colParent";
        colParent.HeaderText = "الحساب الرئيسي";
        colLevel.Name = "colLevel";
        colLevel.HeaderText = "المستوى";
        colLevel.FillWeight = 80;
        colLevel.MinimumWidth = 72;
        colKind.Name = "colKind";
        colKind.HeaderText = "النوع";
        colKind.FillWeight = 55;
        colReport.Name = "colReport";
        colReport.HeaderText = "نوع التقرير";
        colGroup.Name = "colGroup";
        colGroup.HeaderText = "المجموعة";
        colNature.Name = "colNature";
        colNature.HeaderText = "طبيعة الحساب";
        colAccountType.Name = "colAccountType";
        colAccountType.HeaderText = "نوع الحساب";
        colAnalysis.Name = "colAnalysis";
        colAnalysis.HeaderText = "تحليل الحساب";
        previewGrid.Columns.AddRange(new DataGridViewColumn[] { colRow, colAccount, colCurrency, colNameLocal, colNameForeign, colParent, colLevel, colKind, colReport, colGroup, colNature, colAccountType, colAnalysis });
        referenceFooter.Name = "referenceFooter";
        referenceFooter.Dock = DockStyle.Bottom;
        referenceFooter.Height = 34;
        referenceFooter.BackColor = Color.FromArgb(227, 224, 255);
        importLayout.Controls.Add(pathLayout, 0, 0);
        importLayout.Controls.Add(lblOrder, 0, 1);
        importLayout.Controls.Add(lblNotes, 0, 2);
        importLayout.Controls.Add(previewGrid, 0, 3);
        Controls.Add(importLayout);
        Controls.Add(designerCommandBar);
        Controls.Add(referenceFooter);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Tahoma", 9F);
        RightToLeft = RightToLeft.Yes;
        RightToLeftLayout = true;
        Name = "FrmAccountingImportPreview";
        Text = "دليل الحسابات - استيراد من ملف إكسل";
        ClientSize = new Size(1100, 650);
        MinimumSize = new Size(850, 500);
        StartPosition = FormStartPosition.CenterParent;
        ShowInTaskbar = false;
        ((System.ComponentModel.ISupportInitialize)previewGrid).EndInit();
        ResumeLayout(true);
    }
}
