namespace TransportERP.Desktop.Forms.SystemSettings.General;

partial class FrmAvailableCurrencies
{
    private System.ComponentModel.IContainer components = null!;
    private TableLayoutPanel layout = null!;
    private TableLayoutPanel searchPanel = null!;
    private TableLayoutPanel footer = null!;
    private Label lblFind = null!;
    private Label lblStatus = null!;
    private TextBox txtSearch = null!;
    private DataGridView currencies = null!;
    private DataGridViewTextBoxColumn colCurrencyName = null!;
    private DataGridViewTextBoxColumn colSymbol = null!;
    private DataGridViewTextBoxColumn colFraction = null!;
    private DataGridViewTextBoxColumn colLocal = null!;
    private DataGridViewTextBoxColumn colRate = null!;
    private Button btnFind = null!;
    private Button btnAccept = null!;
    private Button btnCancel = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        layout = new TableLayoutPanel();
        searchPanel = new TableLayoutPanel();
        footer = new TableLayoutPanel();
        lblFind = new Label();
        lblStatus = new Label();
        txtSearch = new TextBox();
        currencies = new DataGridView();
        colCurrencyName = new DataGridViewTextBoxColumn();
        colSymbol = new DataGridViewTextBoxColumn();
        colFraction = new DataGridViewTextBoxColumn();
        colLocal = new DataGridViewTextBoxColumn();
        colRate = new DataGridViewTextBoxColumn();
        btnFind = new Button();
        btnAccept = new Button();
        btnCancel = new Button();
        SuspendLayout();
        layout.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)currencies).BeginInit();
        layout.Name = "layout";
        layout.Dock = DockStyle.Fill;
        layout.Padding = new Padding(10);
        layout.ColumnCount = 1;
        layout.RowCount = 4;
        layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
        layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
        searchPanel.Name = "searchPanel";
        searchPanel.Dock = DockStyle.Fill;
        searchPanel.ColumnCount = 4;
        searchPanel.RowCount = 1;
        searchPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        searchPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 30F));
        searchPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 60F));
        searchPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 40F));
        searchPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 30F));
        lblFind.Name = "lblFind";
        lblFind.Text = "Find";
        lblFind.Dock = DockStyle.Fill;
        lblFind.TextAlign = ContentAlignment.MiddleCenter;
        txtSearch.Name = "txtSearch";
        txtSearch.AccessibleName = "البحث عن عملة";
        txtSearch.Dock = DockStyle.Fill;
        txtSearch.BackColor = Color.White;
        searchPanel.Controls.Add(lblFind, 1, 0);
        searchPanel.Controls.Add(txtSearch, 2, 0);
        currencies.Name = "currencies";
        currencies.AccessibleName = "العملات المتوفرة";
        currencies.Dock = DockStyle.Fill;
        currencies.ReadOnly = true;
        currencies.AllowUserToAddRows = false;
        currencies.AllowUserToDeleteRows = false;
        currencies.AllowUserToOrderColumns = false;
        currencies.AutoGenerateColumns = false;
        currencies.BackgroundColor = Color.White;
        currencies.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        currencies.ColumnHeadersHeight = 30;
        currencies.RowHeadersWidth = 24;
        currencies.MultiSelect = false;
        currencies.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        currencies.DefaultCellStyle.SelectionBackColor = Color.Black;
        currencies.DefaultCellStyle.SelectionForeColor = Color.White;
        colCurrencyName.Name = "colCurrencyName";
        colCurrencyName.HeaderText = "اسم العملة";
        colCurrencyName.FillWeight = 160F;
        colCurrencyName.MinimumWidth = 130;
        colSymbol.Name = "colSymbol";
        colSymbol.HeaderText = "رمز العملة";
        colSymbol.MinimumWidth = 90;
        colFraction.Name = "colFraction";
        colFraction.HeaderText = "الفكة";
        colFraction.MinimumWidth = 70;
        colLocal.Name = "colLocal";
        colLocal.HeaderText = "عملة محلية";
        colLocal.MinimumWidth = 90;
        colRate.Name = "colRate";
        colRate.HeaderText = "سعر التحويل";
        colRate.MinimumWidth = 95;
        currencies.Columns.AddRange(colCurrencyName, colSymbol, colFraction, colLocal, colRate);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "قائمة العملات غير مرتبطة بمصدر بيانات بعد.";
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.TextAlign = ContentAlignment.MiddleRight;
        lblStatus.ForeColor = Color.DimGray;
        footer.Name = "footer";
        footer.Dock = DockStyle.Fill;
        footer.ColumnCount = 5;
        footer.RowCount = 1;
        footer.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        footer.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 75F));
        footer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        footer.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 75F));
        footer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        footer.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 75F));
        btnFind.Name = "btnFind";
        btnFind.Text = "Find";
        btnFind.Dock = DockStyle.Fill;
        btnFind.Click += find_Click;
        btnAccept.Name = "btnAccept";
        btnAccept.Text = "OK";
        btnAccept.Dock = DockStyle.Fill;
        btnAccept.Enabled = false;
        btnAccept.AccessibleDescription = "يتطلب الاختيار عملة من مصدر البيانات المرتبط.";
        btnCancel.Name = "btnCancel";
        btnCancel.Text = "Cancel";
        btnCancel.Dock = DockStyle.Fill;
        btnCancel.DialogResult = DialogResult.Cancel;
        footer.Controls.Add(btnFind, 0, 0);
        footer.Controls.Add(btnAccept, 2, 0);
        footer.Controls.Add(btnCancel, 4, 0);
        layout.Controls.Add(searchPanel, 0, 0);
        layout.Controls.Add(currencies, 0, 1);
        layout.Controls.Add(lblStatus, 0, 2);
        layout.Controls.Add(footer, 0, 3);
        Controls.Add(layout);
        Name = "FrmAvailableCurrencies";
        Text = "العملات المتوفرة";
        ClientSize = new Size(680, 430);
        MinimumSize = new Size(620, 380);
        Font = new Font("Tahoma", 9F);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        RightToLeft = RightToLeft.Yes;
        RightToLeftLayout = true;
        StartPosition = FormStartPosition.CenterParent;
        MinimizeBox = false;
        MaximizeBox = false;
        ShowInTaskbar = false;
        AcceptButton = btnFind;
        CancelButton = btnCancel;
        ((System.ComponentModel.ISupportInitialize)currencies).EndInit();
        layout.ResumeLayout(false);
        ResumeLayout(false);
    }
}
