#nullable enable

using TransportERP.Desktop.CoreUI;

namespace TransportERP.Desktop.Forms.SystemSettings.General;

partial class UcPrintSettings
{
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;

    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private FlowLayoutPanel designerCommandFlow = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandView = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private System.ComponentModel.IContainer? components;
    private Panel pnlHeader = null!; private Label lblTitle = null!; private Label lblSubtitle = null!;
    private TableLayoutPanel tlpContent = null!;
    private GroupBox grpPrinter = null!; private TableLayoutPanel tlpPrinter = null!;
    private Label lblPrinter = null!; private ComboBox cboPrinter = null!; private Label lblPaperSize = null!; private ComboBox cboPaperSize = null!; private Label lblOrientation = null!; private ComboBox cboOrientation = null!; private Label lblCopies = null!; private NumericUpDown nudCopies = null!;
    private GroupBox grpMargins = null!; private TableLayoutPanel tlpMargins = null!;
    private Label lblTopMargin = null!; private NumericUpDown nudTopMargin = null!; private Label lblBottomMargin = null!; private NumericUpDown nudBottomMargin = null!; private Label lblRightMargin = null!; private NumericUpDown nudRightMargin = null!; private Label lblLeftMargin = null!; private NumericUpDown nudLeftMargin = null!;
    private GroupBox grpBranding = null!; private TableLayoutPanel tlpBranding = null!;
    private PictureBox picCompanyLogo = null!; private Button btnChooseLogo = null!; private Label lblHeaderText = null!; private TextBox txtHeaderText = null!; private Label lblFooterText = null!; private TextBox txtFooterText = null!;
    private GroupBox grpPreview = null!; private TableLayoutPanel tlpPreview = null!;
    private CheckBox chkShowPreview = null!; private CheckBox chkCompanyInfo = null!; private CheckBox chkBranchInfo = null!; private CheckBox chkUserInfo = null!; private CheckBox chkPrintLogo = null!; private Panel pnlPreviewSurface = null!; private Label lblPreviewSurface = null!;
    private Panel pnlActions = null!; private FlowLayoutPanel flpActions = null!; private Button btnTestPrint = null!; private Button btnReset = null!; private Button btnSave = null!; private Button btnClose = null!;

    protected override void Dispose(bool disposing) { if (disposing && components is not null) components.Dispose(); base.Dispose(disposing); }

    private void InitializeComponent()
    {
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        designerCommandFlow = new FlowLayoutPanel();
        designerCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandView = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandPrint = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        components = new System.ComponentModel.Container();
        pnlHeader = new Panel(); lblSubtitle = new Label(); lblTitle = new Label(); tlpContent = new TableLayoutPanel();
        grpPrinter = new GroupBox(); tlpPrinter = new TableLayoutPanel(); lblPrinter = new Label(); cboPrinter = new ComboBox(); lblPaperSize = new Label(); cboPaperSize = new ComboBox(); lblOrientation = new Label(); cboOrientation = new ComboBox(); lblCopies = new Label(); nudCopies = new NumericUpDown();
        grpMargins = new GroupBox(); tlpMargins = new TableLayoutPanel(); lblTopMargin = new Label(); nudTopMargin = new NumericUpDown(); lblBottomMargin = new Label(); nudBottomMargin = new NumericUpDown(); lblRightMargin = new Label(); nudRightMargin = new NumericUpDown(); lblLeftMargin = new Label(); nudLeftMargin = new NumericUpDown();
        grpBranding = new GroupBox(); tlpBranding = new TableLayoutPanel(); picCompanyLogo = new PictureBox(); btnChooseLogo = new Button(); lblHeaderText = new Label(); txtHeaderText = new TextBox(); lblFooterText = new Label(); txtFooterText = new TextBox();
        grpPreview = new GroupBox(); tlpPreview = new TableLayoutPanel(); chkShowPreview = new CheckBox(); chkCompanyInfo = new CheckBox(); chkBranchInfo = new CheckBox(); chkUserInfo = new CheckBox(); chkPrintLogo = new CheckBox(); pnlPreviewSurface = new Panel(); lblPreviewSurface = new Label();
        pnlActions = new Panel(); flpActions = new FlowLayoutPanel(); btnTestPrint = new Button(); btnReset = new Button(); btnSave = new Button(); btnClose = new Button();
        pnlHeader.SuspendLayout(); tlpContent.SuspendLayout(); grpPrinter.SuspendLayout(); tlpPrinter.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)nudCopies).BeginInit(); grpMargins.SuspendLayout(); tlpMargins.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)nudTopMargin).BeginInit(); ((System.ComponentModel.ISupportInitialize)nudBottomMargin).BeginInit(); ((System.ComponentModel.ISupportInitialize)nudRightMargin).BeginInit(); ((System.ComponentModel.ISupportInitialize)nudLeftMargin).BeginInit(); grpBranding.SuspendLayout(); tlpBranding.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)picCompanyLogo).BeginInit(); grpPreview.SuspendLayout(); tlpPreview.SuspendLayout(); pnlPreviewSurface.SuspendLayout(); pnlActions.SuspendLayout(); flpActions.SuspendLayout(); SuspendLayout();

        pnlHeader.Controls.Add(lblSubtitle); pnlHeader.Controls.Add(lblTitle); pnlHeader.Dock = DockStyle.Top; pnlHeader.Name = "pnlHeader"; pnlHeader.TabIndex = 0;
        lblSubtitle.Dock = DockStyle.Fill; lblSubtitle.Name = "lblSubtitle"; lblSubtitle.Text = "الطابعة والورق والهوامش والهوية وخيارات بيانات الشركة والفرع والمستخدم.";
        lblTitle.Dock = DockStyle.Top; lblTitle.Height = 40; lblTitle.Name = "lblTitle"; lblTitle.Text = "إعدادات الطباعة";

        tlpContent.ColumnCount = 2; tlpContent.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 52F)); tlpContent.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 48F)); tlpContent.Controls.Add(grpPrinter, 0, 0); tlpContent.Controls.Add(grpMargins, 1, 0); tlpContent.Controls.Add(grpBranding, 0, 1); tlpContent.Controls.Add(grpPreview, 1, 1); tlpContent.Dock = DockStyle.Fill; tlpContent.Name = "tlpContent"; tlpContent.Padding = UiDesignTokens.FormPadding; tlpContent.RowCount = 2; tlpContent.RowStyles.Add(new RowStyle(SizeType.Percent, 45F)); tlpContent.RowStyles.Add(new RowStyle(SizeType.Percent, 55F)); tlpContent.TabIndex = 1;

        grpPrinter.Controls.Add(tlpPrinter); grpPrinter.Dock = DockStyle.Fill; grpPrinter.Name = "grpPrinter"; grpPrinter.TabIndex = 0; grpPrinter.Text = "الطابعة والورق";
        tlpPrinter.ColumnCount = 2; tlpPrinter.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 145F)); tlpPrinter.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F)); tlpPrinter.Controls.Add(lblPrinter, 0, 0); tlpPrinter.Controls.Add(cboPrinter, 1, 0); tlpPrinter.Controls.Add(lblPaperSize, 0, 1); tlpPrinter.Controls.Add(cboPaperSize, 1, 1); tlpPrinter.Controls.Add(lblOrientation, 0, 2); tlpPrinter.Controls.Add(cboOrientation, 1, 2); tlpPrinter.Controls.Add(lblCopies, 0, 3); tlpPrinter.Controls.Add(nudCopies, 1, 3); tlpPrinter.Dock = DockStyle.Fill; tlpPrinter.Name = "tlpPrinter"; tlpPrinter.RowCount = 4; tlpPrinter.RowStyles.Add(new RowStyle(SizeType.Percent, 25F)); tlpPrinter.RowStyles.Add(new RowStyle(SizeType.Percent, 25F)); tlpPrinter.RowStyles.Add(new RowStyle(SizeType.Percent, 25F)); tlpPrinter.RowStyles.Add(new RowStyle(SizeType.Percent, 25F));
        lblPrinter.Dock = DockStyle.Fill; lblPrinter.Name = "lblPrinter"; lblPrinter.Text = "الطابعة *"; cboPrinter.Dock = DockStyle.Fill; cboPrinter.DropDownStyle = ComboBoxStyle.DropDownList; cboPrinter.Name = "cboPrinter"; cboPrinter.TabIndex = 0;
        lblPaperSize.Dock = DockStyle.Fill; lblPaperSize.Name = "lblPaperSize"; lblPaperSize.Text = "حجم الورق *"; cboPaperSize.Dock = DockStyle.Fill; cboPaperSize.DropDownStyle = ComboBoxStyle.DropDownList; cboPaperSize.Items.AddRange(new object[] { "A4", "A5", "Letter" }); cboPaperSize.Name = "cboPaperSize"; cboPaperSize.TabIndex = 1;
        lblOrientation.Dock = DockStyle.Fill; lblOrientation.Name = "lblOrientation"; lblOrientation.Text = "الاتجاه"; cboOrientation.Dock = DockStyle.Fill; cboOrientation.DropDownStyle = ComboBoxStyle.DropDownList; cboOrientation.Items.AddRange(new object[] { "عمودي", "أفقي" }); cboOrientation.Name = "cboOrientation"; cboOrientation.TabIndex = 2;
        lblCopies.Dock = DockStyle.Fill; lblCopies.Name = "lblCopies"; lblCopies.Text = "عدد النسخ"; nudCopies.Dock = DockStyle.Fill; nudCopies.Maximum = 20; nudCopies.Minimum = 1; nudCopies.Name = "nudCopies"; nudCopies.TabIndex = 3; nudCopies.Value = 1;

        grpMargins.Controls.Add(tlpMargins); grpMargins.Dock = DockStyle.Fill; grpMargins.Name = "grpMargins"; grpMargins.TabIndex = 1; grpMargins.Text = "الهوامش";
        tlpMargins.ColumnCount = 2; tlpMargins.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 135F)); tlpMargins.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F)); tlpMargins.Controls.Add(lblTopMargin, 0, 0); tlpMargins.Controls.Add(nudTopMargin, 1, 0); tlpMargins.Controls.Add(lblBottomMargin, 0, 1); tlpMargins.Controls.Add(nudBottomMargin, 1, 1); tlpMargins.Controls.Add(lblRightMargin, 0, 2); tlpMargins.Controls.Add(nudRightMargin, 1, 2); tlpMargins.Controls.Add(lblLeftMargin, 0, 3); tlpMargins.Controls.Add(nudLeftMargin, 1, 3); tlpMargins.Dock = DockStyle.Fill; tlpMargins.Name = "tlpMargins"; tlpMargins.RowCount = 4; tlpMargins.RowStyles.Add(new RowStyle(SizeType.Percent, 25F)); tlpMargins.RowStyles.Add(new RowStyle(SizeType.Percent, 25F)); tlpMargins.RowStyles.Add(new RowStyle(SizeType.Percent, 25F)); tlpMargins.RowStyles.Add(new RowStyle(SizeType.Percent, 25F));
        lblTopMargin.Dock = DockStyle.Fill; lblTopMargin.Name = "lblTopMargin"; lblTopMargin.Text = "العلوي"; nudTopMargin.DecimalPlaces = 1; nudTopMargin.Dock = DockStyle.Fill; nudTopMargin.Maximum = 100; nudTopMargin.Name = "nudTopMargin"; nudTopMargin.TabIndex = 0;
        lblBottomMargin.Dock = DockStyle.Fill; lblBottomMargin.Name = "lblBottomMargin"; lblBottomMargin.Text = "السفلي"; nudBottomMargin.DecimalPlaces = 1; nudBottomMargin.Dock = DockStyle.Fill; nudBottomMargin.Maximum = 100; nudBottomMargin.Name = "nudBottomMargin"; nudBottomMargin.TabIndex = 1;
        lblRightMargin.Dock = DockStyle.Fill; lblRightMargin.Name = "lblRightMargin"; lblRightMargin.Text = "الأيمن"; nudRightMargin.DecimalPlaces = 1; nudRightMargin.Dock = DockStyle.Fill; nudRightMargin.Maximum = 100; nudRightMargin.Name = "nudRightMargin"; nudRightMargin.TabIndex = 2;
        lblLeftMargin.Dock = DockStyle.Fill; lblLeftMargin.Name = "lblLeftMargin"; lblLeftMargin.Text = "الأيسر"; nudLeftMargin.DecimalPlaces = 1; nudLeftMargin.Dock = DockStyle.Fill; nudLeftMargin.Maximum = 100; nudLeftMargin.Name = "nudLeftMargin"; nudLeftMargin.TabIndex = 3;

        grpBranding.Controls.Add(tlpBranding); grpBranding.Dock = DockStyle.Fill; grpBranding.Name = "grpBranding"; grpBranding.TabIndex = 2; grpBranding.Text = "الشعار ورأس وتذييل المستند";
        tlpBranding.ColumnCount = 3; tlpBranding.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 130F)); tlpBranding.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F)); tlpBranding.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120F)); tlpBranding.Controls.Add(picCompanyLogo, 0, 0); tlpBranding.SetRowSpan(picCompanyLogo, 3); tlpBranding.Controls.Add(btnChooseLogo, 2, 0); tlpBranding.Controls.Add(lblHeaderText, 0, 3); tlpBranding.Controls.Add(txtHeaderText, 1, 3); tlpBranding.SetColumnSpan(txtHeaderText, 2); tlpBranding.Controls.Add(lblFooterText, 0, 4); tlpBranding.Controls.Add(txtFooterText, 1, 4); tlpBranding.SetColumnSpan(txtFooterText, 2); tlpBranding.Dock = DockStyle.Fill; tlpBranding.Name = "tlpBranding"; tlpBranding.RowCount = 5; tlpBranding.RowStyles.Add(new RowStyle(SizeType.Absolute, 45F)); tlpBranding.RowStyles.Add(new RowStyle(SizeType.Absolute, 45F)); tlpBranding.RowStyles.Add(new RowStyle(SizeType.Absolute, 45F)); tlpBranding.RowStyles.Add(new RowStyle(SizeType.Percent, 50F)); tlpBranding.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        picCompanyLogo.BackColor = UiDesignTokens.ReadOnly; picCompanyLogo.BorderStyle = BorderStyle.FixedSingle; picCompanyLogo.Dock = DockStyle.Fill; picCompanyLogo.Name = "picCompanyLogo"; picCompanyLogo.SizeMode = PictureBoxSizeMode.Zoom; picCompanyLogo.TabIndex = 0; picCompanyLogo.TabStop = false;
        btnChooseLogo.Dock = DockStyle.Fill; btnChooseLogo.Name = "btnChooseLogo"; btnChooseLogo.TabIndex = 1; btnChooseLogo.Text = "اختيار شعار";
        lblHeaderText.Dock = DockStyle.Fill; lblHeaderText.Name = "lblHeaderText"; lblHeaderText.Text = "نص الرأس"; txtHeaderText.Dock = DockStyle.Fill; txtHeaderText.Multiline = true; txtHeaderText.Name = "txtHeaderText"; txtHeaderText.TabIndex = 2;
        lblFooterText.Dock = DockStyle.Fill; lblFooterText.Name = "lblFooterText"; lblFooterText.Text = "نص التذييل"; txtFooterText.Dock = DockStyle.Fill; txtFooterText.Multiline = true; txtFooterText.Name = "txtFooterText"; txtFooterText.TabIndex = 3;

        grpPreview.Controls.Add(tlpPreview); grpPreview.Dock = DockStyle.Fill; grpPreview.Name = "grpPreview"; grpPreview.TabIndex = 3; grpPreview.Text = "المعاينة وخيارات المعلومات";
        tlpPreview.ColumnCount = 2; tlpPreview.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 45F)); tlpPreview.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 55F)); tlpPreview.Controls.Add(chkShowPreview, 0, 0); tlpPreview.Controls.Add(chkCompanyInfo, 0, 1); tlpPreview.Controls.Add(chkBranchInfo, 0, 2); tlpPreview.Controls.Add(chkUserInfo, 0, 3); tlpPreview.Controls.Add(chkPrintLogo, 0, 4); tlpPreview.Controls.Add(pnlPreviewSurface, 1, 0); tlpPreview.SetRowSpan(pnlPreviewSurface, 5); tlpPreview.Dock = DockStyle.Fill; tlpPreview.Name = "tlpPreview"; tlpPreview.RowCount = 5; tlpPreview.RowStyles.Add(new RowStyle(SizeType.Percent, 20F)); tlpPreview.RowStyles.Add(new RowStyle(SizeType.Percent, 20F)); tlpPreview.RowStyles.Add(new RowStyle(SizeType.Percent, 20F)); tlpPreview.RowStyles.Add(new RowStyle(SizeType.Percent, 20F)); tlpPreview.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
        chkShowPreview.AutoSize = true; chkShowPreview.Checked = true; chkShowPreview.Name = "chkShowPreview"; chkShowPreview.TabIndex = 0; chkShowPreview.Text = "عرض المعاينة قبل الطباعة";
        chkCompanyInfo.AutoSize = true; chkCompanyInfo.Checked = true; chkCompanyInfo.Name = "chkCompanyInfo"; chkCompanyInfo.TabIndex = 1; chkCompanyInfo.Text = "إظهار معلومات الشركة";
        chkBranchInfo.AutoSize = true; chkBranchInfo.Checked = true; chkBranchInfo.Name = "chkBranchInfo"; chkBranchInfo.TabIndex = 2; chkBranchInfo.Text = "إظهار معلومات الفرع";
        chkUserInfo.AutoSize = true; chkUserInfo.Checked = true; chkUserInfo.Name = "chkUserInfo"; chkUserInfo.TabIndex = 3; chkUserInfo.Text = "إظهار اسم المستخدم";
        chkPrintLogo.AutoSize = true; chkPrintLogo.Checked = true; chkPrintLogo.Name = "chkPrintLogo"; chkPrintLogo.TabIndex = 4; chkPrintLogo.Text = "طباعة شعار الشركة";
        pnlPreviewSurface.BackColor = Color.White; pnlPreviewSurface.BorderStyle = BorderStyle.FixedSingle; pnlPreviewSurface.Controls.Add(lblPreviewSurface); pnlPreviewSurface.Dock = DockStyle.Fill; pnlPreviewSurface.Name = "pnlPreviewSurface"; pnlPreviewSurface.Padding = new Padding(UiDesignTokens.Space12);
        lblPreviewSurface.Dock = DockStyle.Fill; lblPreviewSurface.Name = "lblPreviewSurface"; lblPreviewSurface.Text = "معاينة تصميمية للصفحة\r\nA4 — عمودي"; lblPreviewSurface.TextAlign = ContentAlignment.MiddleCenter;

        pnlActions.Controls.Add(flpActions); pnlActions.Dock = DockStyle.Bottom; pnlActions.Height = 64; pnlActions.Name = "pnlActions"; pnlActions.Padding = new Padding(UiDesignTokens.Space16, UiDesignTokens.Space8, UiDesignTokens.Space16, UiDesignTokens.Space8); pnlActions.TabIndex = 2;
        flpActions.Controls.Add(btnSave); flpActions.Controls.Add(btnReset); flpActions.Controls.Add(btnTestPrint); flpActions.Controls.Add(btnClose); flpActions.Dock = DockStyle.Fill; flpActions.FlowDirection = FlowDirection.LeftToRight; flpActions.Name = "flpActions"; flpActions.WrapContents = false;
        btnTestPrint.Name = "btnTestPrint"; btnTestPrint.TabIndex = 2; btnTestPrint.Text = "طباعة تجريبية"; btnReset.Name = "btnReset"; btnReset.TabIndex = 1; btnReset.Text = "استعادة الافتراضي"; btnSave.Name = "btnSave"; btnSave.TabIndex = 0; btnSave.Text = "حفظ"; btnClose.Name = "btnClose"; btnClose.TabIndex = 3; btnClose.Text = "إغلاق";

        AutoScaleDimensions = new SizeF(7F, 15F); AutoScaleMode = AutoScaleMode.None; Size = new Size(1240, 800); Controls.Add(tlpContent); Controls.Add(designerCommandBar); Controls.Add(pnlHeader); Name = "UcPrintSettings"; Text = "إعدادات الطباعة";
        pnlHeader.ResumeLayout(false); tlpContent.ResumeLayout(false); grpPrinter.ResumeLayout(false); tlpPrinter.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)nudCopies).EndInit(); grpMargins.ResumeLayout(false); tlpMargins.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)nudTopMargin).EndInit(); ((System.ComponentModel.ISupportInitialize)nudBottomMargin).EndInit(); ((System.ComponentModel.ISupportInitialize)nudRightMargin).EndInit(); ((System.ComponentModel.ISupportInitialize)nudLeftMargin).EndInit(); grpBranding.ResumeLayout(false); tlpBranding.ResumeLayout(false); tlpBranding.PerformLayout(); ((System.ComponentModel.ISupportInitialize)picCompanyLogo).EndInit(); grpPreview.ResumeLayout(false); tlpPreview.ResumeLayout(false); tlpPreview.PerformLayout(); pnlPreviewSurface.ResumeLayout(false); pnlActions.ResumeLayout(false); flpActions.ResumeLayout(false); ResumeLayout(false);
    
        // Explicit Designer-owned command catalog.
        designerCommandBar.Dock = DockStyle.Bottom;
        designerCommandBar.TabIndex = 2;
        designerCommandBar.Controls.Add(pnlActions);
        pnlActions.Dock = DockStyle.Fill;
        pnlActions.Margin = Padding.Empty;
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.Controls.Add(designerCommandFlow);
        designerCommandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        designerCommandFlow.Name = "designerCommandFlow";
        designerCommandFlow.Dock = DockStyle.Fill;
        designerCommandFlow.AutoSize = false;
        designerCommandFlow.WrapContents = false;
        designerCommandFlow.FlowDirection = FlowDirection.RightToLeft;
        designerCommandFlow.RightToLeft = RightToLeft.No;
        designerCommandFlow.Padding = new Padding(2);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Height = 30;
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = false;
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = true;
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = false;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandView.Name = "standardCommandView";
        standardCommandView.Enabled = false;
        standardCommandView.Visible = false;
        standardCommandView.AccessibleName = "عرض";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = false;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = false;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = false;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = false;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandAdd.AutoSize = false;
        standardCommandAdd.Dock = DockStyle.None;
        standardCommandAdd.MinimumSize = Size.Empty;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandAdd.Text = "";
        designerCommandFlow.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.AutoSize = false;
        standardCommandEdit.Dock = DockStyle.None;
        standardCommandEdit.MinimumSize = Size.Empty;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandEdit.Text = "";
        designerCommandFlow.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        designerCommandFlow.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.AutoSize = false;
        standardCommandCancel.Dock = DockStyle.None;
        standardCommandCancel.MinimumSize = Size.Empty;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandCancel.Text = "";
        designerCommandFlow.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        standardCommandView.AutoSize = false;
        standardCommandView.Dock = DockStyle.None;
        standardCommandView.MinimumSize = Size.Empty;
        standardCommandView.Size = new Size(26, 24);
        standardCommandView.Margin = new Padding(1);
        standardCommandView.FlatStyle = FlatStyle.Flat;
        standardCommandView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        standardCommandView.Text = "";
        designerCommandFlow.Controls.Add(standardCommandView);
        designerCommandBar.SetCommandRole(standardCommandView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        designerCommandFlow.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        designerCommandFlow.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        designerCommandFlow.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        designerCommandFlow.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        btnSave.AutoSize = false;
        btnSave.Dock = DockStyle.None;
        btnSave.MinimumSize = Size.Empty;
        btnSave.Size = new Size(26, 24);
        btnSave.Margin = new Padding(1);
        btnSave.FlatStyle = FlatStyle.Flat;
        btnSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        btnSave.Text = "";
        designerCommandFlow.Controls.Add(btnSave);
        designerCommandBar.SetCommandRole(btnSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        designerCommandFlow.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        btnClose.AutoSize = false;
        btnClose.Dock = DockStyle.None;
        btnClose.MinimumSize = Size.Empty;
        btnClose.Size = new Size(26, 24);
        btnClose.Margin = new Padding(1);
        btnClose.FlatStyle = FlatStyle.Flat;
        btnClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        btnClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        btnClose.Text = "";
        designerCloseHost.Controls.Add(btnClose);
        btnClose.Location = new Point(1, 1);
        designerCommandBar.SetCommandRole(btnClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        designerCommandFlow.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        designerCommandFlow.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        designerCommandFlow.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        designerCommandFlow.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
        designerCommandFlow.Controls.Add(btnTestPrint);
        designerCommandFlow.Controls.Add(btnReset);
    
        // Shared audit presentation; original sources remain owned by this screen.
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
}
}
