namespace TransportERP.Desktop.Forms.SystemSettings.General;
partial class UcAccountingChartData
{
    private TableLayoutPanel accountIdentityLayout = null!;
    private TableLayoutPanel accountBodyLayout = null!;
    private TableLayoutPanel accountRightFields = null!;
    private TableLayoutPanel accountLeftFields = null!;
    private DataGridView currencyPreview = null!;
    private DataGridViewTextBoxColumn colCurrencyCodePreview = null!;
    private DataGridViewTextBoxColumn colCurrencyNamePreview = null!;
    private DataGridViewCheckBoxColumn colCurrencyStoppedPreview = null!;
    private TableLayoutPanel accountDetailsGroup = null!;
    private Label lblAccountDetailsHeader = null!;
    private TableLayoutPanel accountTreeLayout = null!;
    private Label lblAccountTreeHeader = null!;
    private TreeView accountTree = null!;
    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private FlowLayoutPanel standardCommandFlow = null!;
    private Panel standardCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandView = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandSave = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandClose = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel layout = null!;
    private TableLayoutPanel fields = null!;
    private Label lblTitle = null!;
    private Label lblStatus = null!;
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;
    private Label lbltxtParentAccount = null!;
    private TextBox txtParentAccount = null!;
    private Label lbltxtAccountNumber = null!;
    private TextBox txtAccountNumber = null!;
    private Label lbltxtNameLocal = null!;
    private TextBox txtNameLocal = null!;
    private Label lbltxtNameForeign = null!;
    private TextBox txtNameForeign = null!;
    private Label lblcboClassification = null!;
    private ComboBox cboClassification = null!;
    private Label lbltxtRank = null!;
    private TextBox txtRank = null!;
    private Label lblcboAccountType = null!;
    private ComboBox cboAccountType = null!;
    private Label lblcboNature = null!;
    private ComboBox cboNature = null!;
    private Label lblcboGroup = null!;
    private ComboBox cboGroup = null!;
    private Label lblcboReport = null!;
    private ComboBox cboReport = null!;
    private Label lblcboAnalyticalType = null!;
    private ComboBox cboAnalyticalType = null!;
    private Label lbltxtLastReconciliation = null!;
    private TextBox txtLastReconciliation = null!;
    private Label lblcboCashFlow = null!;
    private ComboBox cboCashFlow = null!;
    private Label lblcboAnalysis = null!;
    private ComboBox cboAnalysis = null!;
    private Label lblcboCenters = null!;
    private ComboBox cboCenters = null!;
    private Label lblcboProjects = null!;
    private ComboBox cboProjects = null!;
    private Label lblcboActivities = null!;
    private ComboBox cboActivities = null!;
    private Label lblchkFavorite = null!;
    private CheckBox chkFavorite = null!;
    private Label lblchkProduction = null!;
    private CheckBox chkProduction = null!;
    private Label lblchkWithholding = null!;
    private CheckBox chkWithholding = null!;
    private Label lbllstCurrencies = null!;
    private CheckedListBox lstCurrencies = null!;
    private Label lblcboFxClearingAccount = null!;
    private ComboBox cboFxClearingAccount = null!;
    private Label lblchkStopped = null!;
    private CheckBox chkStopped = null!;
    private TableLayoutPanel pnlbtnOpeningRequest = null!;
    private Button btnOpeningRequest = null!;
    private GroupBox grpbtnOpeningRequest = null!;
    private ListBox lstbtnOpeningRequest = null!;
    private Label noticebtnOpeningRequest = null!;
    private TableLayoutPanel pnlbtnSelectCenters = null!;
    private Button btnSelectCenters = null!;
    private GroupBox grpbtnSelectCenters = null!;
    private CheckedListBox lstbtnSelectCenters = null!;
    private Label noticebtnSelectCenters = null!;
    private TableLayoutPanel pnlbtnSelectProjects = null!;
    private Button btnSelectProjects = null!;
    private GroupBox grpbtnSelectProjects = null!;
    private CheckedListBox lstbtnSelectProjects = null!;
    private Label noticebtnSelectProjects = null!;
    private TableLayoutPanel pnlbtnSelectActivities = null!;
    private Button btnSelectActivities = null!;
    private GroupBox grpbtnSelectActivities = null!;
    private CheckedListBox lstbtnSelectActivities = null!;
    private Label noticebtnSelectActivities = null!;
    private Button btnPermissions = null!;
    private Button btnDistribution = null!;
    private Button toolbar_btnOpeningRequest = null!;
    private Button toolbar_btnSelectCenters = null!;
    private Button toolbar_btnSelectProjects = null!;
    private Button toolbar_btnSelectActivities = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        standardCommandFlow = new FlowLayoutPanel();
        standardCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandView = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandSave = new Button();
        standardCommandPrint = new Button();
        standardCommandClose = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.Size = new Size(1000, 44);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Margin = Padding.Empty;
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        standardCommandFlow.Name = "pnlToolbar";
        standardCommandFlow.Dock = DockStyle.Fill;
        standardCommandFlow.FlowDirection = FlowDirection.RightToLeft;
        standardCommandFlow.RightToLeft = RightToLeft.No;
        standardCommandFlow.WrapContents = false;
        standardCommandFlow.Padding = new Padding(2);
        standardCloseHost.Name = "standardCloseHost";
        standardCloseHost.Dock = DockStyle.Left;
        standardCloseHost.Width = 28;
        designerCommandBar.Controls.Add(standardCommandFlow);
        designerCommandBar.Controls.Add(standardCloseHost);
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = true;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.TabIndex = 0;
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandFlow.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = true;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.TabIndex = 1;
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandFlow.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.TabIndex = 2;
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandFlow.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.TabIndex = 3;
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandFlow.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        standardCommandView.Name = "standardCommandView";
        standardCommandView.AccessibleName = "عرض";
        standardCommandView.Enabled = false;
        standardCommandView.Visible = true;
        standardCommandView.Size = new Size(26, 24);
        standardCommandView.Margin = new Padding(1);
        standardCommandView.FlatStyle = FlatStyle.Flat;
        standardCommandView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandView.TabIndex = 4;
        standardCommandView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        standardCommandFlow.Controls.Add(standardCommandView);
        designerCommandBar.SetCommandRole(standardCommandView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.TabIndex = 5;
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandFlow.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.AccessibleName = "التالي";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.TabIndex = 6;
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandFlow.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.TabIndex = 7;
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandFlow.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.TabIndex = 8;
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFlow.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        standardCommandSave.Name = "btnSave";
        standardCommandSave.AccessibleName = "حفظ";
        standardCommandSave.Enabled = false;
        standardCommandSave.Visible = true;
        standardCommandSave.Size = new Size(26, 24);
        standardCommandSave.Margin = new Padding(1);
        standardCommandSave.FlatStyle = FlatStyle.Flat;
        standardCommandSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandSave.TabIndex = 9;
        standardCommandSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        standardCommandFlow.Controls.Add(standardCommandSave);
        designerCommandBar.SetCommandRole(standardCommandSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.TabIndex = 10;
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandFlow.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        standardCommandClose.Name = "standardCommandClose";
        standardCommandClose.AccessibleName = "إغلاق";
        standardCommandClose.Enabled = false;
        standardCommandClose.Visible = true;
        standardCommandClose.Size = new Size(26, 24);
        standardCommandClose.Margin = new Padding(1);
        standardCommandClose.FlatStyle = FlatStyle.Flat;
        standardCommandClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandClose.TabIndex = 11;
        standardCommandClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        standardCloseHost.Controls.Add(standardCommandClose);
        designerCommandBar.SetCommandRole(standardCommandClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.TabIndex = 12;
        standardCommandRefresh.Text = "تحديث";
        standardCommandFlow.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.TabIndex = 13;
        standardCommandImport.Text = "استيراد";
        standardCommandFlow.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.TabIndex = 14;
        standardCommandExport.Text = "تصدير";
        standardCommandFlow.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.TabIndex = 15;
        standardCommandHelp.Text = "مساعدة";
        standardCommandFlow.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
        standardCommandClose.Location = new Point(1, 1);
        standardCommandSave.AccessibleDescription = "الحفظ غير متاح؛ لم تُربط الشاشة بخدمة بيانات.";
        Controls.Add(designerCommandBar);

        layout = new TableLayoutPanel();
        fields = new TableLayoutPanel();
        lblTitle = new Label();
        lblStatus = new Label();
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        layout.SuspendLayout();
        fields.SuspendLayout();
        layout.Name = "layout";
        layout.Dock = DockStyle.Top;
        layout.AutoSize = true;
        layout.ColumnCount = 1;
        layout.RowCount = 4;
        layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "دليل الحسابات";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Font = new Font("Segoe UI", 16F);
        lblTitle.TextAlign = ContentAlignment.MiddleRight;
        lblTitle.BackColor = Color.FromArgb(192, 192, 255);
        lblTitle.Padding = new Padding(12);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "معاينة إدخال مؤقتة — الحفظ والترقيم التلقائي والقوائم غير متاحة؛ القيم لا تُطبّق على النظام.";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.TextAlign = ContentAlignment.MiddleRight;
        lblStatus.Padding = new Padding(8);
        fields.Name = "fields";
        fields.Dock = DockStyle.Top;
        fields.AutoSize = true;
        fields.ColumnCount = 2;
        fields.RowCount = 2;
        fields.Enabled = false;
        fields.TabIndex = 1;
        lbltxtParentAccount = new Label();
        lbltxtParentAccount.Name = "lbltxtParentAccount";
        lbltxtParentAccount.Text = "الحساب الرئيسي";
        lbltxtParentAccount.AutoSize = true;
        lbltxtParentAccount.Dock = DockStyle.Fill;
        lbltxtParentAccount.TextAlign = ContentAlignment.MiddleRight;
        lbltxtParentAccount.Margin = new Padding(6, 8, 6, 8);
        txtParentAccount = new TextBox();
        txtParentAccount.Name = "txtParentAccount";
        txtParentAccount.AccessibleName = "الحساب الرئيسي";
        txtParentAccount.Dock = DockStyle.Fill;
        txtParentAccount.TabIndex = 0;
        txtParentAccount.Margin = new Padding(6, 8, 6, 8);
        lbltxtAccountNumber = new Label();
        lbltxtAccountNumber.Name = "lbltxtAccountNumber";
        lbltxtAccountNumber.Text = "رقم الحساب";
        lbltxtAccountNumber.AutoSize = true;
        lbltxtAccountNumber.Dock = DockStyle.Fill;
        lbltxtAccountNumber.TextAlign = ContentAlignment.MiddleRight;
        lbltxtAccountNumber.Margin = new Padding(6, 8, 6, 8);
        txtAccountNumber = new TextBox();
        txtAccountNumber.Name = "txtAccountNumber";
        txtAccountNumber.AccessibleName = "رقم الحساب";
        txtAccountNumber.Dock = DockStyle.Fill;
        txtAccountNumber.TabIndex = 1;
        txtAccountNumber.Margin = new Padding(6, 8, 6, 8);
        lbltxtNameLocal = new Label();
        lbltxtNameLocal.Name = "lbltxtNameLocal";
        lbltxtNameLocal.Text = "اسم الحساب (محلي)";
        lbltxtNameLocal.AutoSize = true;
        lbltxtNameLocal.Dock = DockStyle.Fill;
        lbltxtNameLocal.TextAlign = ContentAlignment.MiddleRight;
        lbltxtNameLocal.Margin = new Padding(6, 8, 6, 8);
        txtNameLocal = new TextBox();
        txtNameLocal.Name = "txtNameLocal";
        txtNameLocal.AccessibleName = "اسم الحساب (محلي)";
        txtNameLocal.Dock = DockStyle.Fill;
        txtNameLocal.TabIndex = 2;
        txtNameLocal.Margin = new Padding(6, 8, 6, 8);
        lbltxtNameForeign = new Label();
        lbltxtNameForeign.Name = "lbltxtNameForeign";
        lbltxtNameForeign.Text = "اسم الحساب (أجنبي)";
        lbltxtNameForeign.AutoSize = true;
        lbltxtNameForeign.Dock = DockStyle.Fill;
        lbltxtNameForeign.TextAlign = ContentAlignment.MiddleRight;
        lbltxtNameForeign.Margin = new Padding(6, 8, 6, 8);
        txtNameForeign = new TextBox();
        txtNameForeign.Name = "txtNameForeign";
        txtNameForeign.AccessibleName = "اسم الحساب (أجنبي)";
        txtNameForeign.Dock = DockStyle.Fill;
        txtNameForeign.TabIndex = 3;
        txtNameForeign.Margin = new Padding(6, 8, 6, 8);
        txtNameForeign.RightToLeft = RightToLeft.No;
        txtNameForeign.TextAlign = HorizontalAlignment.Left;
        lblcboClassification = new Label();
        lblcboClassification.Name = "lblcboClassification";
        lblcboClassification.Text = "تصنيف الحساب";
        lblcboClassification.AutoSize = true;
        lblcboClassification.Dock = DockStyle.Fill;
        lblcboClassification.TextAlign = ContentAlignment.MiddleRight;
        lblcboClassification.Margin = new Padding(6, 8, 6, 8);
        cboClassification = new ComboBox();
        cboClassification.Name = "cboClassification";
        cboClassification.AccessibleName = "تصنيف الحساب";
        cboClassification.Dock = DockStyle.Fill;
        cboClassification.TabIndex = 4;
        cboClassification.Margin = new Padding(6, 8, 6, 8);
        cboClassification.DropDownStyle = ComboBoxStyle.DropDownList;
        cboClassification.Enabled = false;
        cboClassification.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        lbltxtRank = new Label();
        lbltxtRank.Name = "lbltxtRank";
        lbltxtRank.Text = "الرتبة";
        lbltxtRank.AutoSize = true;
        lbltxtRank.Dock = DockStyle.Fill;
        lbltxtRank.TextAlign = ContentAlignment.MiddleRight;
        lbltxtRank.Margin = new Padding(6, 8, 6, 8);
        txtRank = new TextBox();
        txtRank.Name = "txtRank";
        txtRank.AccessibleName = "الرتبة";
        txtRank.Dock = DockStyle.Fill;
        txtRank.TabIndex = 5;
        txtRank.Margin = new Padding(6, 8, 6, 8);
        txtRank.ReadOnly = true;
        txtRank.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        lblcboAccountType = new Label();
        lblcboAccountType.Name = "lblcboAccountType";
        lblcboAccountType.Text = "نوع الحساب";
        lblcboAccountType.AutoSize = true;
        lblcboAccountType.Dock = DockStyle.Fill;
        lblcboAccountType.TextAlign = ContentAlignment.MiddleRight;
        lblcboAccountType.Margin = new Padding(6, 8, 6, 8);
        cboAccountType = new ComboBox();
        cboAccountType.Name = "cboAccountType";
        cboAccountType.AccessibleName = "نوع الحساب";
        cboAccountType.Dock = DockStyle.Fill;
        cboAccountType.TabIndex = 6;
        cboAccountType.Margin = new Padding(6, 8, 6, 8);
        cboAccountType.DropDownStyle = ComboBoxStyle.DropDownList;
        cboAccountType.Enabled = false;
        cboAccountType.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        lblcboNature = new Label();
        lblcboNature.Name = "lblcboNature";
        lblcboNature.Text = "طبيعة الحساب";
        lblcboNature.AutoSize = true;
        lblcboNature.Dock = DockStyle.Fill;
        lblcboNature.TextAlign = ContentAlignment.MiddleRight;
        lblcboNature.Margin = new Padding(6, 8, 6, 8);
        cboNature = new ComboBox();
        cboNature.Name = "cboNature";
        cboNature.AccessibleName = "طبيعة الحساب";
        cboNature.Dock = DockStyle.Fill;
        cboNature.TabIndex = 7;
        cboNature.Margin = new Padding(6, 8, 6, 8);
        cboNature.DropDownStyle = ComboBoxStyle.DropDownList;
        cboNature.Items.AddRange(new object[] { "مدين", "دائن" });
        lblcboGroup = new Label();
        lblcboGroup.Name = "lblcboGroup";
        lblcboGroup.Text = "مجموعة الحسابات";
        lblcboGroup.AutoSize = true;
        lblcboGroup.Dock = DockStyle.Fill;
        lblcboGroup.TextAlign = ContentAlignment.MiddleRight;
        lblcboGroup.Margin = new Padding(6, 8, 6, 8);
        cboGroup = new ComboBox();
        cboGroup.Name = "cboGroup";
        cboGroup.AccessibleName = "مجموعة الحسابات";
        cboGroup.Dock = DockStyle.Fill;
        cboGroup.TabIndex = 8;
        cboGroup.Margin = new Padding(6, 8, 6, 8);
        cboGroup.DropDownStyle = ComboBoxStyle.DropDownList;
        cboGroup.Enabled = false;
        cboGroup.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        lblcboReport = new Label();
        lblcboReport.Name = "lblcboReport";
        lblcboReport.Text = "نوع التقرير";
        lblcboReport.AutoSize = true;
        lblcboReport.Dock = DockStyle.Fill;
        lblcboReport.TextAlign = ContentAlignment.MiddleRight;
        lblcboReport.Margin = new Padding(6, 8, 6, 8);
        cboReport = new ComboBox();
        cboReport.Name = "cboReport";
        cboReport.AccessibleName = "نوع التقرير";
        cboReport.Dock = DockStyle.Fill;
        cboReport.TabIndex = 9;
        cboReport.Margin = new Padding(6, 8, 6, 8);
        cboReport.DropDownStyle = ComboBoxStyle.DropDownList;
        cboReport.Items.AddRange(new object[] { "ميزانية عمومية", "أرباح وخسائر" });
        lblcboAnalyticalType = new Label();
        lblcboAnalyticalType.Name = "lblcboAnalyticalType";
        lblcboAnalyticalType.Text = "نوع الحساب التحليلي";
        lblcboAnalyticalType.AutoSize = true;
        lblcboAnalyticalType.Dock = DockStyle.Fill;
        lblcboAnalyticalType.TextAlign = ContentAlignment.MiddleRight;
        lblcboAnalyticalType.Margin = new Padding(6, 8, 6, 8);
        cboAnalyticalType = new ComboBox();
        cboAnalyticalType.Name = "cboAnalyticalType";
        cboAnalyticalType.AccessibleName = "نوع الحساب التحليلي";
        cboAnalyticalType.Dock = DockStyle.Fill;
        cboAnalyticalType.TabIndex = 10;
        cboAnalyticalType.Margin = new Padding(6, 8, 6, 8);
        cboAnalyticalType.DropDownStyle = ComboBoxStyle.DropDownList;
        cboAnalyticalType.Enabled = false;
        cboAnalyticalType.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        lbltxtLastReconciliation = new Label();
        lbltxtLastReconciliation.Name = "lbltxtLastReconciliation";
        lbltxtLastReconciliation.Text = "تاريخ آخر مطابقة";
        lbltxtLastReconciliation.AutoSize = true;
        lbltxtLastReconciliation.Dock = DockStyle.Fill;
        lbltxtLastReconciliation.TextAlign = ContentAlignment.MiddleRight;
        lbltxtLastReconciliation.Margin = new Padding(6, 8, 6, 8);
        txtLastReconciliation = new TextBox();
        txtLastReconciliation.Name = "txtLastReconciliation";
        txtLastReconciliation.AccessibleName = "تاريخ آخر مطابقة";
        txtLastReconciliation.Dock = DockStyle.Fill;
        txtLastReconciliation.TabIndex = 11;
        txtLastReconciliation.Margin = new Padding(6, 8, 6, 8);
        txtLastReconciliation.ReadOnly = true;
        txtLastReconciliation.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        lblcboCashFlow = new Label();
        lblcboCashFlow.Name = "lblcboCashFlow";
        lblcboCashFlow.Text = "نوع التدفق";
        lblcboCashFlow.AutoSize = true;
        lblcboCashFlow.Dock = DockStyle.Fill;
        lblcboCashFlow.TextAlign = ContentAlignment.MiddleRight;
        lblcboCashFlow.Margin = new Padding(6, 8, 6, 8);
        cboCashFlow = new ComboBox();
        cboCashFlow.Name = "cboCashFlow";
        cboCashFlow.AccessibleName = "نوع التدفق";
        cboCashFlow.Dock = DockStyle.Fill;
        cboCashFlow.TabIndex = 12;
        cboCashFlow.Margin = new Padding(6, 8, 6, 8);
        cboCashFlow.DropDownStyle = ComboBoxStyle.DropDownList;
        cboCashFlow.Items.AddRange(new object[] { "تشغيلي", "استثماري", "تمويلي" });
        lblcboAnalysis = new Label();
        lblcboAnalysis.Name = "lblcboAnalysis";
        lblcboAnalysis.Text = "تحليل الحساب";
        lblcboAnalysis.AutoSize = true;
        lblcboAnalysis.Dock = DockStyle.Fill;
        lblcboAnalysis.TextAlign = ContentAlignment.MiddleRight;
        lblcboAnalysis.Margin = new Padding(6, 8, 6, 8);
        cboAnalysis = new ComboBox();
        cboAnalysis.Name = "cboAnalysis";
        cboAnalysis.AccessibleName = "تحليل الحساب";
        cboAnalysis.Dock = DockStyle.Fill;
        cboAnalysis.TabIndex = 13;
        cboAnalysis.Margin = new Padding(6, 8, 6, 8);
        cboAnalysis.DropDownStyle = ComboBoxStyle.DropDownList;
        cboAnalysis.Enabled = false;
        cboAnalysis.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        lblcboCenters = new Label();
        lblcboCenters.Name = "lblcboCenters";
        lblcboCenters.Text = "استخدام المراكز";
        lblcboCenters.AutoSize = true;
        lblcboCenters.Dock = DockStyle.Fill;
        lblcboCenters.TextAlign = ContentAlignment.MiddleRight;
        lblcboCenters.Margin = new Padding(6, 8, 6, 8);
        cboCenters = new ComboBox();
        cboCenters.Name = "cboCenters";
        cboCenters.AccessibleName = "استخدام المراكز";
        cboCenters.Dock = DockStyle.Fill;
        cboCenters.TabIndex = 14;
        cboCenters.Margin = new Padding(6, 8, 6, 8);
        cboCenters.DropDownStyle = ComboBoxStyle.DropDownList;
        cboCenters.Items.AddRange(new object[] { "غير مستخدم", "اختياري", "إجباري" });
        lblcboProjects = new Label();
        lblcboProjects.Name = "lblcboProjects";
        lblcboProjects.Text = "استخدام المشاريع";
        lblcboProjects.AutoSize = true;
        lblcboProjects.Dock = DockStyle.Fill;
        lblcboProjects.TextAlign = ContentAlignment.MiddleRight;
        lblcboProjects.Margin = new Padding(6, 8, 6, 8);
        cboProjects = new ComboBox();
        cboProjects.Name = "cboProjects";
        cboProjects.AccessibleName = "استخدام المشاريع";
        cboProjects.Dock = DockStyle.Fill;
        cboProjects.TabIndex = 15;
        cboProjects.Margin = new Padding(6, 8, 6, 8);
        cboProjects.DropDownStyle = ComboBoxStyle.DropDownList;
        cboProjects.Items.AddRange(new object[] { "غير مستخدم", "اختياري", "إجباري" });
        lblcboActivities = new Label();
        lblcboActivities.Name = "lblcboActivities";
        lblcboActivities.Text = "استخدام الأنشطة";
        lblcboActivities.AutoSize = true;
        lblcboActivities.Dock = DockStyle.Fill;
        lblcboActivities.TextAlign = ContentAlignment.MiddleRight;
        lblcboActivities.Margin = new Padding(6, 8, 6, 8);
        cboActivities = new ComboBox();
        cboActivities.Name = "cboActivities";
        cboActivities.AccessibleName = "استخدام الأنشطة";
        cboActivities.Dock = DockStyle.Fill;
        cboActivities.TabIndex = 16;
        cboActivities.Margin = new Padding(6, 8, 6, 8);
        cboActivities.DropDownStyle = ComboBoxStyle.DropDownList;
        cboActivities.Items.AddRange(new object[] { "غير مستخدم", "اختياري", "إجباري" });
        lblchkFavorite = new Label();
        lblchkFavorite.Name = "lblchkFavorite";
        lblchkFavorite.Text = "الحسابات المفضلة";
        lblchkFavorite.AutoSize = true;
        lblchkFavorite.Dock = DockStyle.Fill;
        lblchkFavorite.TextAlign = ContentAlignment.MiddleRight;
        lblchkFavorite.Margin = new Padding(6, 8, 6, 8);
        chkFavorite = new CheckBox();
        chkFavorite.Name = "chkFavorite";
        chkFavorite.AccessibleName = "الحسابات المفضلة";
        chkFavorite.Dock = DockStyle.Fill;
        chkFavorite.TabIndex = 17;
        chkFavorite.Margin = new Padding(6, 8, 6, 8);
        chkFavorite.AutoSize = true;
        lblchkProduction = new Label();
        lblchkProduction.Name = "lblchkProduction";
        lblchkProduction.Text = "الربط مع نظام الإنتاج";
        lblchkProduction.AutoSize = true;
        lblchkProduction.Dock = DockStyle.Fill;
        lblchkProduction.TextAlign = ContentAlignment.MiddleRight;
        lblchkProduction.Margin = new Padding(6, 8, 6, 8);
        chkProduction = new CheckBox();
        chkProduction.Name = "chkProduction";
        chkProduction.AccessibleName = "الربط مع نظام الإنتاج";
        chkProduction.Dock = DockStyle.Fill;
        chkProduction.TabIndex = 18;
        chkProduction.Margin = new Padding(6, 8, 6, 8);
        chkProduction.AutoSize = true;
        lblchkWithholding = new Label();
        lblchkWithholding.Name = "lblchkWithholding";
        lblchkWithholding.Text = "استخدام خصم الضريبة من المصدر";
        lblchkWithholding.AutoSize = true;
        lblchkWithholding.Dock = DockStyle.Fill;
        lblchkWithholding.TextAlign = ContentAlignment.MiddleRight;
        lblchkWithholding.Margin = new Padding(6, 8, 6, 8);
        chkWithholding = new CheckBox();
        chkWithholding.Name = "chkWithholding";
        chkWithholding.AccessibleName = "استخدام خصم الضريبة من المصدر";
        chkWithholding.Dock = DockStyle.Fill;
        chkWithholding.TabIndex = 19;
        chkWithholding.Margin = new Padding(6, 8, 6, 8);
        chkWithholding.AutoSize = true;
        lbllstCurrencies = new Label();
        lbllstCurrencies.Name = "lbllstCurrencies";
        lbllstCurrencies.Text = "العملات";
        lbllstCurrencies.AutoSize = true;
        lbllstCurrencies.Dock = DockStyle.Fill;
        lbllstCurrencies.TextAlign = ContentAlignment.MiddleRight;
        lbllstCurrencies.Margin = new Padding(6, 8, 6, 8);
        lstCurrencies = new CheckedListBox();
        lstCurrencies.Name = "lstCurrencies";
        lstCurrencies.AccessibleName = "العملات";
        lstCurrencies.Dock = DockStyle.Fill;
        lstCurrencies.TabIndex = 20;
        lstCurrencies.Margin = new Padding(6, 8, 6, 8);
        lstCurrencies.Enabled = false;
        lstCurrencies.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        lstCurrencies.CheckOnClick = true;
        lstCurrencies.IntegralHeight = false;
        lstCurrencies.MinimumSize = new Size(0, 88);
        lblcboFxClearingAccount = new Label();
        lblcboFxClearingAccount.Name = "lblcboFxClearingAccount";
        lblcboFxClearingAccount.Text = "الحساب الوسيط لفروق العملة";
        lblcboFxClearingAccount.AutoSize = true;
        lblcboFxClearingAccount.Dock = DockStyle.Fill;
        lblcboFxClearingAccount.TextAlign = ContentAlignment.MiddleRight;
        lblcboFxClearingAccount.Margin = new Padding(6, 8, 6, 8);
        cboFxClearingAccount = new ComboBox();
        cboFxClearingAccount.Name = "cboFxClearingAccount";
        cboFxClearingAccount.AccessibleName = "الحساب الوسيط لفروق العملة";
        cboFxClearingAccount.Dock = DockStyle.Fill;
        cboFxClearingAccount.TabIndex = 21;
        cboFxClearingAccount.Margin = new Padding(6, 8, 6, 8);
        cboFxClearingAccount.DropDownStyle = ComboBoxStyle.DropDownList;
        cboFxClearingAccount.Enabled = false;
        cboFxClearingAccount.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        lblchkStopped = new Label();
        lblchkStopped.Name = "lblchkStopped";
        lblchkStopped.Text = "موقف";
        lblchkStopped.AutoSize = true;
        lblchkStopped.Dock = DockStyle.Fill;
        lblchkStopped.TextAlign = ContentAlignment.MiddleRight;
        lblchkStopped.Margin = new Padding(6, 8, 6, 8);
        chkStopped = new CheckBox();
        chkStopped.Name = "chkStopped";
        chkStopped.AccessibleName = "موقف";
        chkStopped.Dock = DockStyle.Fill;
        chkStopped.TabIndex = 22;
        chkStopped.Margin = new Padding(6, 8, 6, 8);
        chkStopped.AutoSize = true;
        standardCommandAdd.Name = "btnAdd";
        standardCommandAdd.Enabled = true;
        standardCommandAdd.Click += draftAction_Click;
        standardCommandSave.Name = "btnSave";
        standardCommandSave.Enabled = false;
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        layout.Controls.Add(lblTitle, 0, 0);
        layout.Controls.Add(lblStatus, 0, 1);
        layout.Controls.Add(designerCommandBar, 0, 2);
        layout.Controls.Add(fields, 0, 3);
        Controls.Add(layout);


        Name = "UcAccountingChartData";
        Text = "دليل الحسابات";
        Size = new Size(1000, 640);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        RightToLeft = RightToLeft.Yes;
        fields.ResumeLayout(true);
        layout.ResumeLayout(true);
        ResumeLayout(true);
        pnlbtnOpeningRequest = new TableLayoutPanel();
        btnOpeningRequest = new Button();
        grpbtnOpeningRequest = new GroupBox();
        lstbtnOpeningRequest = new ListBox();
        noticebtnOpeningRequest = new Label();
        pnlbtnOpeningRequest.Name = "pnlbtnOpeningRequest";
        pnlbtnOpeningRequest.Dock = DockStyle.Top;
        pnlbtnOpeningRequest.AutoSize = true;
        pnlbtnOpeningRequest.ColumnCount = 2;
        pnlbtnOpeningRequest.RowCount = 2;
        pnlbtnOpeningRequest.Margin = new Padding(6, 8, 6, 8);
        pnlbtnOpeningRequest.RightToLeft = RightToLeft.Yes;
        pnlbtnOpeningRequest.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlbtnOpeningRequest.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
        pnlbtnOpeningRequest.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        pnlbtnOpeningRequest.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        txtAccountNumber.Margin = Padding.Empty;
        pnlbtnOpeningRequest.Controls.Add(txtAccountNumber, 0, 0);
        btnOpeningRequest.Name = "btnOpeningRequest";
        btnOpeningRequest.Text = "F5";
        btnOpeningRequest.AccessibleName = "طلب فتح حساب (F5)";
        btnOpeningRequest.AutoSize = true;
        btnOpeningRequest.MinimumSize = new Size(36, 30);
        btnOpeningRequest.Margin = new Padding(4, 0, 0, 0);
        btnOpeningRequest.AccessibleDescription = "طلب فتح حساب (F5) — عرض قائمة فارغة؛ مصدر البيانات غير مرتبط.";
        btnOpeningRequest.Click += btnOpeningRequest_Click;
        pnlbtnOpeningRequest.Controls.Add(btnOpeningRequest, 1, 0);
        grpbtnOpeningRequest.Name = "grpbtnOpeningRequest";
        grpbtnOpeningRequest.Text = "طلب فتح حساب (F5)";
        grpbtnOpeningRequest.Dock = DockStyle.Top;
        grpbtnOpeningRequest.Height = 190;
        grpbtnOpeningRequest.MinimumSize = new Size(0, 190);
        grpbtnOpeningRequest.Padding = new Padding(8, 24, 8, 8);
        grpbtnOpeningRequest.Visible = false;
        lstbtnOpeningRequest.Name = "lstbtnOpeningRequest";
        lstbtnOpeningRequest.AccessibleName = "طلب فتح حساب (F5)";
        lstbtnOpeningRequest.Enabled = false;
        lstbtnOpeningRequest.Dock = DockStyle.Fill;
        lstbtnOpeningRequest.IntegralHeight = false;
        grpbtnOpeningRequest.Controls.Add(lstbtnOpeningRequest);
        noticebtnOpeningRequest.Text = "القائمة غير مرتبطة ببيانات؛ لا توجد سجلات للاختيار.";
        noticebtnOpeningRequest.AutoSize = true;
        noticebtnOpeningRequest.Dock = DockStyle.Bottom;
        noticebtnOpeningRequest.Padding = new Padding(4);
        noticebtnOpeningRequest.MaximumSize = new Size(550, 0);
        grpbtnOpeningRequest.Controls.Add(noticebtnOpeningRequest);
        pnlbtnOpeningRequest.Controls.Add(grpbtnOpeningRequest, 0, 1);
        pnlbtnOpeningRequest.SetColumnSpan(grpbtnOpeningRequest, 2);
        pnlbtnSelectCenters = new TableLayoutPanel();
        btnSelectCenters = new Button();
        grpbtnSelectCenters = new GroupBox();
        lstbtnSelectCenters = new CheckedListBox();
        noticebtnSelectCenters = new Label();
        pnlbtnSelectCenters.Name = "pnlbtnSelectCenters";
        pnlbtnSelectCenters.Dock = DockStyle.Top;
        pnlbtnSelectCenters.AutoSize = true;
        pnlbtnSelectCenters.ColumnCount = 2;
        pnlbtnSelectCenters.RowCount = 2;
        pnlbtnSelectCenters.Margin = new Padding(6, 8, 6, 8);
        pnlbtnSelectCenters.RightToLeft = RightToLeft.Yes;
        pnlbtnSelectCenters.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlbtnSelectCenters.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
        pnlbtnSelectCenters.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        pnlbtnSelectCenters.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        cboCenters.Margin = Padding.Empty;
        pnlbtnSelectCenters.Controls.Add(cboCenters, 0, 0);
        btnSelectCenters.Name = "btnSelectCenters";
        btnSelectCenters.Text = "…";
        btnSelectCenters.AccessibleName = "مراكز التكلفة";
        btnSelectCenters.AutoSize = true;
        btnSelectCenters.MinimumSize = new Size(36, 30);
        btnSelectCenters.Margin = new Padding(4, 0, 0, 0);
        btnSelectCenters.AccessibleDescription = "مراكز التكلفة — عرض قائمة فارغة؛ مصدر البيانات غير مرتبط.";
        btnSelectCenters.Click += btnSelectCenters_Click;
        pnlbtnSelectCenters.Controls.Add(btnSelectCenters, 1, 0);
        grpbtnSelectCenters.Name = "grpbtnSelectCenters";
        grpbtnSelectCenters.Text = "مراكز التكلفة";
        grpbtnSelectCenters.Dock = DockStyle.Top;
        grpbtnSelectCenters.Height = 190;
        grpbtnSelectCenters.MinimumSize = new Size(0, 190);
        grpbtnSelectCenters.Padding = new Padding(8, 24, 8, 8);
        grpbtnSelectCenters.Visible = false;
        lstbtnSelectCenters.Name = "lstbtnSelectCenters";
        lstbtnSelectCenters.AccessibleName = "مراكز التكلفة";
        lstbtnSelectCenters.Enabled = false;
        lstbtnSelectCenters.Dock = DockStyle.Fill;
        lstbtnSelectCenters.IntegralHeight = false;
        lstbtnSelectCenters.CheckOnClick = true;
        grpbtnSelectCenters.Controls.Add(lstbtnSelectCenters);
        noticebtnSelectCenters.Text = "القائمة غير مرتبطة ببيانات؛ لا توجد سجلات للاختيار.";
        noticebtnSelectCenters.AutoSize = true;
        noticebtnSelectCenters.Dock = DockStyle.Bottom;
        noticebtnSelectCenters.Padding = new Padding(4);
        noticebtnSelectCenters.MaximumSize = new Size(550, 0);
        grpbtnSelectCenters.Controls.Add(noticebtnSelectCenters);
        pnlbtnSelectCenters.Controls.Add(grpbtnSelectCenters, 0, 1);
        pnlbtnSelectCenters.SetColumnSpan(grpbtnSelectCenters, 2);
        pnlbtnSelectProjects = new TableLayoutPanel();
        btnSelectProjects = new Button();
        grpbtnSelectProjects = new GroupBox();
        lstbtnSelectProjects = new CheckedListBox();
        noticebtnSelectProjects = new Label();
        pnlbtnSelectProjects.Name = "pnlbtnSelectProjects";
        pnlbtnSelectProjects.Dock = DockStyle.Top;
        pnlbtnSelectProjects.AutoSize = true;
        pnlbtnSelectProjects.ColumnCount = 2;
        pnlbtnSelectProjects.RowCount = 2;
        pnlbtnSelectProjects.Margin = new Padding(6, 8, 6, 8);
        pnlbtnSelectProjects.RightToLeft = RightToLeft.Yes;
        pnlbtnSelectProjects.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlbtnSelectProjects.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
        pnlbtnSelectProjects.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        pnlbtnSelectProjects.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        cboProjects.Margin = Padding.Empty;
        pnlbtnSelectProjects.Controls.Add(cboProjects, 0, 0);
        btnSelectProjects.Name = "btnSelectProjects";
        btnSelectProjects.Text = "…";
        btnSelectProjects.AccessibleName = "المشاريع";
        btnSelectProjects.AutoSize = true;
        btnSelectProjects.MinimumSize = new Size(36, 30);
        btnSelectProjects.Margin = new Padding(4, 0, 0, 0);
        btnSelectProjects.AccessibleDescription = "المشاريع — عرض قائمة فارغة؛ مصدر البيانات غير مرتبط.";
        btnSelectProjects.Click += btnSelectProjects_Click;
        pnlbtnSelectProjects.Controls.Add(btnSelectProjects, 1, 0);
        grpbtnSelectProjects.Name = "grpbtnSelectProjects";
        grpbtnSelectProjects.Text = "المشاريع";
        grpbtnSelectProjects.Dock = DockStyle.Top;
        grpbtnSelectProjects.Height = 190;
        grpbtnSelectProjects.MinimumSize = new Size(0, 190);
        grpbtnSelectProjects.Padding = new Padding(8, 24, 8, 8);
        grpbtnSelectProjects.Visible = false;
        lstbtnSelectProjects.Name = "lstbtnSelectProjects";
        lstbtnSelectProjects.AccessibleName = "المشاريع";
        lstbtnSelectProjects.Enabled = false;
        lstbtnSelectProjects.Dock = DockStyle.Fill;
        lstbtnSelectProjects.IntegralHeight = false;
        lstbtnSelectProjects.CheckOnClick = true;
        grpbtnSelectProjects.Controls.Add(lstbtnSelectProjects);
        noticebtnSelectProjects.Text = "القائمة غير مرتبطة ببيانات؛ لا توجد سجلات للاختيار.";
        noticebtnSelectProjects.AutoSize = true;
        noticebtnSelectProjects.Dock = DockStyle.Bottom;
        noticebtnSelectProjects.Padding = new Padding(4);
        noticebtnSelectProjects.MaximumSize = new Size(550, 0);
        grpbtnSelectProjects.Controls.Add(noticebtnSelectProjects);
        pnlbtnSelectProjects.Controls.Add(grpbtnSelectProjects, 0, 1);
        pnlbtnSelectProjects.SetColumnSpan(grpbtnSelectProjects, 2);
        pnlbtnSelectActivities = new TableLayoutPanel();
        btnSelectActivities = new Button();
        grpbtnSelectActivities = new GroupBox();
        lstbtnSelectActivities = new CheckedListBox();
        noticebtnSelectActivities = new Label();
        pnlbtnSelectActivities.Name = "pnlbtnSelectActivities";
        pnlbtnSelectActivities.Dock = DockStyle.Top;
        pnlbtnSelectActivities.AutoSize = true;
        pnlbtnSelectActivities.ColumnCount = 2;
        pnlbtnSelectActivities.RowCount = 2;
        pnlbtnSelectActivities.Margin = new Padding(6, 8, 6, 8);
        pnlbtnSelectActivities.RightToLeft = RightToLeft.Yes;
        pnlbtnSelectActivities.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlbtnSelectActivities.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
        pnlbtnSelectActivities.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        pnlbtnSelectActivities.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        cboActivities.Margin = Padding.Empty;
        pnlbtnSelectActivities.Controls.Add(cboActivities, 0, 0);
        btnSelectActivities.Name = "btnSelectActivities";
        btnSelectActivities.Text = "…";
        btnSelectActivities.AccessibleName = "الأنشطة";
        btnSelectActivities.AutoSize = true;
        btnSelectActivities.MinimumSize = new Size(36, 30);
        btnSelectActivities.Margin = new Padding(4, 0, 0, 0);
        btnSelectActivities.AccessibleDescription = "الأنشطة — عرض قائمة فارغة؛ مصدر البيانات غير مرتبط.";
        btnSelectActivities.Click += btnSelectActivities_Click;
        pnlbtnSelectActivities.Controls.Add(btnSelectActivities, 1, 0);
        grpbtnSelectActivities.Name = "grpbtnSelectActivities";
        grpbtnSelectActivities.Text = "الأنشطة";
        grpbtnSelectActivities.Dock = DockStyle.Top;
        grpbtnSelectActivities.Height = 190;
        grpbtnSelectActivities.MinimumSize = new Size(0, 190);
        grpbtnSelectActivities.Padding = new Padding(8, 24, 8, 8);
        grpbtnSelectActivities.Visible = false;
        lstbtnSelectActivities.Name = "lstbtnSelectActivities";
        lstbtnSelectActivities.AccessibleName = "الأنشطة";
        lstbtnSelectActivities.Enabled = false;
        lstbtnSelectActivities.Dock = DockStyle.Fill;
        lstbtnSelectActivities.IntegralHeight = false;
        lstbtnSelectActivities.CheckOnClick = true;
        grpbtnSelectActivities.Controls.Add(lstbtnSelectActivities);
        noticebtnSelectActivities.Text = "القائمة غير مرتبطة ببيانات؛ لا توجد سجلات للاختيار.";
        noticebtnSelectActivities.AutoSize = true;
        noticebtnSelectActivities.Dock = DockStyle.Bottom;
        noticebtnSelectActivities.Padding = new Padding(4);
        noticebtnSelectActivities.MaximumSize = new Size(550, 0);
        grpbtnSelectActivities.Controls.Add(noticebtnSelectActivities);
        pnlbtnSelectActivities.Controls.Add(grpbtnSelectActivities, 0, 1);
        pnlbtnSelectActivities.SetColumnSpan(grpbtnSelectActivities, 2);

        btnPermissions = new Button();
        btnDistribution = new Button();
        toolbar_btnOpeningRequest = new Button();
        toolbar_btnSelectCenters = new Button();
        toolbar_btnSelectProjects = new Button();
        toolbar_btnSelectActivities = new Button();
        standardCommandAdd.Visible = true;
        standardCommandEdit.Visible = true;
        standardCommandDelete.Visible = true;
        standardCommandCancel.Visible = true;
        standardCommandView.Visible = true;
        standardCommandLast.Visible = true;
        standardCommandNext.Visible = true;
        standardCommandPrevious.Visible = true;
        standardCommandFirst.Visible = true;
        standardCommandSave.Visible = true;
        standardCommandPrint.Visible = true;
        standardCommandClose.Visible = true;
        standardCommandRefresh.Visible = false;
        standardCommandImport.Visible = false;
        standardCommandExport.Visible = false;
        standardCommandHelp.Visible = false;
        btnPermissions.Name = "btnPermissions";
        btnPermissions.Text = "الصلاحيات";
        btnPermissions.AutoSize = true;
        btnPermissions.Enabled = false;
        standardCommandFlow.Controls.Add(btnPermissions);
        standardCommandImport.Visible = true;
        standardCommandImport.Name = "btnImportExcel";
        standardCommandImport.Text = "استيراد من ملف أكسل";
        standardCommandImport.AutoSize = true;
        standardCommandImport.Enabled = false;
        btnDistribution.Name = "btnDistribution";
        btnDistribution.Text = "التوزيع";
        btnDistribution.AutoSize = true;
        btnDistribution.Enabled = false;
        standardCommandFlow.Controls.Add(btnDistribution);
        toolbar_btnOpeningRequest.Name = "toolbar_btnOpeningRequest";
        toolbar_btnOpeningRequest.Text = "طلب فتح حساب (F5)";
        toolbar_btnOpeningRequest.AutoSize = true;
        toolbar_btnOpeningRequest.Enabled = false;
        standardCommandFlow.Controls.Add(toolbar_btnOpeningRequest);
        toolbar_btnSelectCenters.Name = "toolbar_btnSelectCenters";
        toolbar_btnSelectCenters.Text = "مراكز التكلفة";
        toolbar_btnSelectCenters.AutoSize = true;
        toolbar_btnSelectCenters.Enabled = false;
        standardCommandFlow.Controls.Add(toolbar_btnSelectCenters);
        toolbar_btnSelectProjects.Name = "toolbar_btnSelectProjects";
        toolbar_btnSelectProjects.Text = "المشاريع";
        toolbar_btnSelectProjects.AutoSize = true;
        toolbar_btnSelectProjects.Enabled = false;
        standardCommandFlow.Controls.Add(toolbar_btnSelectProjects);
        toolbar_btnSelectActivities.Name = "toolbar_btnSelectActivities";
        toolbar_btnSelectActivities.Text = "الأنشطة";
        toolbar_btnSelectActivities.AutoSize = true;
        toolbar_btnSelectActivities.Enabled = false;
        standardCommandFlow.Controls.Add(toolbar_btnSelectActivities);
    

        // PDF 22–26, 28 and 30: separate identity header, account details and left account tree.
        // The empty tree follows PDF30; no account records or lookup IDs are fabricated.
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 76F));
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 24F));
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountIdentityLayout = new TableLayoutPanel();
        accountIdentityLayout.Name = "accountIdentityLayout";
        accountIdentityLayout.Dock = DockStyle.Top;
        accountIdentityLayout.AutoSize = true;
        accountIdentityLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        accountIdentityLayout.Margin = new Padding(3);
        accountIdentityLayout.ColumnCount = 4;
        accountIdentityLayout.RowCount = 3;
        accountIdentityLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 18F));
        accountIdentityLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        accountIdentityLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 18F));
        accountIdentityLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        accountIdentityLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountIdentityLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountIdentityLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountIdentityLayout.Controls.Add(lbltxtParentAccount, 0, 0);
        accountIdentityLayout.Controls.Add(txtParentAccount, 1, 0);
        lbltxtParentAccount.Margin = new Padding(3, 2, 3, 2);
        txtParentAccount.Margin = new Padding(3, 2, 3, 2);
        accountIdentityLayout.Controls.Add(lbltxtAccountNumber, 2, 0);
        accountIdentityLayout.Controls.Add(pnlbtnOpeningRequest, 3, 0);
        lbltxtAccountNumber.Margin = new Padding(3, 2, 3, 2);
        pnlbtnOpeningRequest.Margin = new Padding(3, 2, 3, 2);
        accountIdentityLayout.Controls.Add(lbltxtNameLocal, 0, 1);
        accountIdentityLayout.Controls.Add(txtNameLocal, 1, 1);
        lbltxtNameLocal.Margin = new Padding(3, 2, 3, 2);
        txtNameLocal.Margin = new Padding(3, 2, 3, 2);
        accountIdentityLayout.SetColumnSpan(txtNameLocal, 3);
        accountIdentityLayout.Controls.Add(lbltxtNameForeign, 0, 2);
        accountIdentityLayout.Controls.Add(txtNameForeign, 1, 2);
        lbltxtNameForeign.Margin = new Padding(3, 2, 3, 2);
        txtNameForeign.Margin = new Padding(3, 2, 3, 2);
        accountIdentityLayout.SetColumnSpan(txtNameForeign, 3);
        accountBodyLayout = new TableLayoutPanel();
        accountBodyLayout.Name = "accountBodyLayout";
        accountBodyLayout.Dock = DockStyle.Top;
        accountBodyLayout.AutoSize = true;
        accountBodyLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        accountBodyLayout.Margin = new Padding(3);
        accountBodyLayout.ColumnCount = 2;
        accountBodyLayout.RowCount = 1;
        accountBodyLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 55F));
        accountBodyLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 45F));
        accountBodyLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountRightFields = new TableLayoutPanel();
        accountRightFields.Name = "accountRightFields";
        accountRightFields.Dock = DockStyle.Top;
        accountRightFields.AutoSize = true;
        accountRightFields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        accountRightFields.Margin = new Padding(3);
        accountRightFields.ColumnCount = 2;
        accountRightFields.RowCount = 12;
        accountRightFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 42F));
        accountRightFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 58F));
        accountRightFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountRightFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountRightFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountRightFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountRightFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountRightFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountRightFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountRightFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountRightFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountRightFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountRightFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountRightFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountRightFields.Controls.Add(lblcboClassification, 0, 0);
        accountRightFields.Controls.Add(cboClassification, 1, 0);
        lblcboClassification.Margin = new Padding(3, 2, 3, 2);
        cboClassification.Margin = new Padding(3, 2, 3, 2);
        accountRightFields.Controls.Add(lblcboAccountType, 0, 1);
        accountRightFields.Controls.Add(cboAccountType, 1, 1);
        lblcboAccountType.Margin = new Padding(3, 2, 3, 2);
        cboAccountType.Margin = new Padding(3, 2, 3, 2);
        accountRightFields.Controls.Add(lblcboGroup, 0, 2);
        accountRightFields.Controls.Add(cboGroup, 1, 2);
        lblcboGroup.Margin = new Padding(3, 2, 3, 2);
        cboGroup.Margin = new Padding(3, 2, 3, 2);
        accountRightFields.Controls.Add(lblcboAnalyticalType, 0, 3);
        accountRightFields.Controls.Add(cboAnalyticalType, 1, 3);
        lblcboAnalyticalType.Margin = new Padding(3, 2, 3, 2);
        cboAnalyticalType.Margin = new Padding(3, 2, 3, 2);
        accountRightFields.Controls.Add(lblcboCashFlow, 0, 4);
        accountRightFields.Controls.Add(cboCashFlow, 1, 4);
        lblcboCashFlow.Margin = new Padding(3, 2, 3, 2);
        cboCashFlow.Margin = new Padding(3, 2, 3, 2);
        accountRightFields.Controls.Add(lblcboCenters, 0, 5);
        accountRightFields.Controls.Add(pnlbtnSelectCenters, 1, 5);
        lblcboCenters.Margin = new Padding(3, 2, 3, 2);
        pnlbtnSelectCenters.Margin = new Padding(3, 2, 3, 2);
        accountRightFields.Controls.Add(lblcboProjects, 0, 6);
        accountRightFields.Controls.Add(pnlbtnSelectProjects, 1, 6);
        lblcboProjects.Margin = new Padding(3, 2, 3, 2);
        pnlbtnSelectProjects.Margin = new Padding(3, 2, 3, 2);
        accountRightFields.Controls.Add(lblcboActivities, 0, 7);
        accountRightFields.Controls.Add(pnlbtnSelectActivities, 1, 7);
        lblcboActivities.Margin = new Padding(3, 2, 3, 2);
        pnlbtnSelectActivities.Margin = new Padding(3, 2, 3, 2);
        accountRightFields.Controls.Add(lblchkFavorite, 0, 8);
        accountRightFields.Controls.Add(chkFavorite, 1, 8);
        lblchkFavorite.Margin = new Padding(3, 2, 3, 2);
        chkFavorite.Margin = new Padding(3, 2, 3, 2);
        accountRightFields.Controls.Add(lblchkProduction, 0, 9);
        accountRightFields.Controls.Add(chkProduction, 1, 9);
        lblchkProduction.Margin = new Padding(3, 2, 3, 2);
        chkProduction.Margin = new Padding(3, 2, 3, 2);
        accountRightFields.Controls.Add(lblchkWithholding, 0, 10);
        accountRightFields.Controls.Add(chkWithholding, 1, 10);
        lblchkWithholding.Margin = new Padding(3, 2, 3, 2);
        chkWithholding.Margin = new Padding(3, 2, 3, 2);
        accountRightFields.Controls.Add(lblchkStopped, 0, 11);
        accountRightFields.Controls.Add(chkStopped, 1, 11);
        lblchkStopped.Margin = new Padding(3, 2, 3, 2);
        chkStopped.Margin = new Padding(3, 2, 3, 2);
        accountLeftFields = new TableLayoutPanel();
        accountLeftFields.Name = "accountLeftFields";
        accountLeftFields.Dock = DockStyle.Top;
        accountLeftFields.AutoSize = true;
        accountLeftFields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        accountLeftFields.Margin = new Padding(3);
        accountLeftFields.ColumnCount = 2;
        accountLeftFields.RowCount = 8;
        accountLeftFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 44F));
        accountLeftFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 56F));
        accountLeftFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountLeftFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountLeftFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountLeftFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountLeftFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountLeftFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountLeftFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountLeftFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountLeftFields.Controls.Add(lbltxtRank, 0, 0);
        accountLeftFields.Controls.Add(txtRank, 1, 0);
        lbltxtRank.Margin = new Padding(3, 2, 3, 2);
        txtRank.Margin = new Padding(3, 2, 3, 2);
        accountLeftFields.Controls.Add(lblcboNature, 0, 1);
        accountLeftFields.Controls.Add(cboNature, 1, 1);
        lblcboNature.Margin = new Padding(3, 2, 3, 2);
        cboNature.Margin = new Padding(3, 2, 3, 2);
        accountLeftFields.Controls.Add(lblcboReport, 0, 2);
        accountLeftFields.Controls.Add(cboReport, 1, 2);
        lblcboReport.Margin = new Padding(3, 2, 3, 2);
        cboReport.Margin = new Padding(3, 2, 3, 2);
        accountLeftFields.Controls.Add(lbltxtLastReconciliation, 0, 3);
        accountLeftFields.Controls.Add(txtLastReconciliation, 1, 3);
        lbltxtLastReconciliation.Margin = new Padding(3, 2, 3, 2);
        txtLastReconciliation.Margin = new Padding(3, 2, 3, 2);
        accountLeftFields.Controls.Add(lblcboAnalysis, 0, 4);
        accountLeftFields.Controls.Add(cboAnalysis, 1, 4);
        lblcboAnalysis.Margin = new Padding(3, 2, 3, 2);
        cboAnalysis.Margin = new Padding(3, 2, 3, 2);
        accountLeftFields.Controls.Add(lblcboFxClearingAccount, 0, 5);
        accountLeftFields.Controls.Add(cboFxClearingAccount, 1, 5);
        lblcboFxClearingAccount.Margin = new Padding(3, 2, 3, 2);
        cboFxClearingAccount.Margin = new Padding(3, 2, 3, 2);
        accountLeftFields.Controls.Add(lbllstCurrencies, 0, 6);
        accountLeftFields.SetColumnSpan(lbllstCurrencies, 2);
        accountLeftFields.Controls.Add(lstCurrencies, 0, 7);
        accountLeftFields.SetColumnSpan(lstCurrencies, 2);
        lstCurrencies.Visible = false;
        currencyPreview = new DataGridView();
        colCurrencyCodePreview = new DataGridViewTextBoxColumn();
        colCurrencyNamePreview = new DataGridViewTextBoxColumn();
        colCurrencyStoppedPreview = new DataGridViewCheckBoxColumn();
        currencyPreview.Name = "currencyPreview";
        currencyPreview.AccessibleDescription = "قائمة العملات غير مرتبطة ببيانات في هذه المعاينة.";
        currencyPreview.Dock = DockStyle.Fill;
        currencyPreview.MinimumSize = new Size(0, 120);
        currencyPreview.ReadOnly = true;
        currencyPreview.Enabled = false;
        currencyPreview.AllowUserToAddRows = false;
        currencyPreview.AllowUserToDeleteRows = false;
        currencyPreview.RowHeadersVisible = false;
        currencyPreview.BackgroundColor = Color.White;
        currencyPreview.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        currencyPreview.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.EnableResizing;
        currencyPreview.ColumnHeadersHeight = 38;
        colCurrencyCodePreview.Name = "colCurrencyCodePreview";
        colCurrencyCodePreview.HeaderText = "رمز العملة";
        colCurrencyCodePreview.FillWeight = 30;
        colCurrencyNamePreview.Name = "colCurrencyNamePreview";
        colCurrencyNamePreview.HeaderText = "اسم العملة";
        colCurrencyNamePreview.FillWeight = 55;
        colCurrencyStoppedPreview.Name = "colCurrencyStoppedPreview";
        colCurrencyStoppedPreview.HeaderText = "توقف";
        colCurrencyStoppedPreview.FillWeight = 20;
        currencyPreview.Columns.AddRange(new DataGridViewColumn[] { colCurrencyCodePreview, colCurrencyNamePreview, colCurrencyStoppedPreview });
        accountLeftFields.RowCount = 9;
        accountLeftFields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountLeftFields.Controls.Add(currencyPreview, 0, 8);
        accountLeftFields.SetColumnSpan(currencyPreview, 2);
        accountBodyLayout.Controls.Add(accountRightFields, 0, 0);
        accountBodyLayout.Controls.Add(accountLeftFields, 1, 0);
        accountDetailsGroup = new TableLayoutPanel();
        accountDetailsGroup.Name = "accountDetailsGroup";
        accountDetailsGroup.Dock = DockStyle.Top;
        accountDetailsGroup.AutoSize = true;
        accountDetailsGroup.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        accountDetailsGroup.Margin = new Padding(3);
        accountDetailsGroup.ColumnCount = 1;
        accountDetailsGroup.RowCount = 2;
        accountDetailsGroup.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        accountDetailsGroup.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountDetailsGroup.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        lblAccountDetailsHeader = new Label();
        lblAccountDetailsHeader.Name = "lblAccountDetailsHeader";
        lblAccountDetailsHeader.Text = "الدليل المحاسبي";
        lblAccountDetailsHeader.AutoSize = true;
        lblAccountDetailsHeader.Dock = DockStyle.Fill;
        lblAccountDetailsHeader.TextAlign = ContentAlignment.MiddleRight;
        accountDetailsGroup.Controls.Add(lblAccountDetailsHeader, 0, 0);
        accountDetailsGroup.Controls.Add(accountBodyLayout, 0, 1);
        accountTreeLayout = new TableLayoutPanel();
        accountTreeLayout.Name = "accountTreeLayout";
        accountTreeLayout.Dock = DockStyle.Top;
        accountTreeLayout.AutoSize = true;
        accountTreeLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        accountTreeLayout.Margin = new Padding(3);
        accountTreeLayout.ColumnCount = 1;
        accountTreeLayout.RowCount = 2;
        accountTreeLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        accountTreeLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountTreeLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        accountTreeLayout.AutoSize = false;
        accountTreeLayout.Dock = DockStyle.Fill;
        accountTreeLayout.MinimumSize = new Size(150, 460);
        accountTreeLayout.RowStyles.Clear();
        accountTreeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
        accountTreeLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        lblAccountTreeHeader = new Label();
        lblAccountTreeHeader.Name = "lblAccountTreeHeader";
        lblAccountTreeHeader.Text = "الحسابات";
        lblAccountTreeHeader.Dock = DockStyle.Fill;
        lblAccountTreeHeader.TextAlign = ContentAlignment.MiddleCenter;
        lblAccountTreeHeader.BorderStyle = BorderStyle.FixedSingle;
        accountTree = new TreeView();
        accountTree.Name = "accountTree";
        accountTree.Dock = DockStyle.Fill;
        accountTree.Enabled = false;
        accountTree.RightToLeft = RightToLeft.Yes;
        accountTree.RightToLeftLayout = true;
        accountTree.HideSelection = false;
        accountTree.AccessibleDescription = "شجرة الحسابات غير مرتبطة بمصدر الحسابات في هذه المعاينة؛ لا توجد بيانات افتراضية.";
        accountTreeLayout.Controls.Add(lblAccountTreeHeader, 0, 0);
        accountTreeLayout.Controls.Add(accountTree, 0, 1);
        fields.Controls.Add(accountIdentityLayout, 0, 0);
        fields.Controls.Add(accountDetailsGroup, 0, 1);
        fields.Controls.Add(accountTreeLayout, 1, 0);
        fields.SetRowSpan(accountTreeLayout, 2);
        standardCommandImport.Enabled = true;
        standardCommandImport.Click += standardCommandImport_Click;
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
    }
}
