namespace TransportERP.Desktop.Forms.SystemSettings.General;
partial class UcActivityData
{
    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private FlowLayoutPanel standardCommandFlow = null!;
    private Panel standardCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandView = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandSave = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandClose = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel layout = null!;
    private TableLayoutPanel fields = null!;
    private Label lblTitle = null!;
    private Label lblStatus = null!;
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;
    private Label lbltxtActivityNumber = null!;
    private TextBox txtActivityNumber = null!;
    private Label lbltxtParentActivity = null!;
    private TextBox txtParentActivity = null!;
    private Label lbltxtNameLocal = null!;
    private TextBox txtNameLocal = null!;
    private Label lbltxtNameForeign = null!;
    private TextBox txtNameForeign = null!;
    private Label lbltxtRank = null!;
    private TextBox txtRank = null!;
    private Label lblcboActivityType = null!;
    private ComboBox cboActivityType = null!;
    private Label lblcboActivityGroup = null!;
    private ComboBox cboActivityGroup = null!;
    private Label lblchkStopped = null!;
    private CheckBox chkStopped = null!;
    private Label lbltxtStopReason = null!;
    private TextBox txtStopReason = null!;
    private Label lbltxtStoppedAt = null!;
    private TextBox txtStoppedAt = null!;
    private TabControl tabsAdditionalFields = null!;
    private TabPage tabAdditionalFields = null!;
    private Button btnLinkProject = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        standardCommandFlow = new FlowLayoutPanel();
        standardCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandView = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandSave = new Button();
        standardCommandPrint = new Button();
        standardCommandClose = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.Size = new Size(1000, 44);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Margin = Padding.Empty;
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        standardCommandFlow.Name = "pnlToolbar";
        standardCommandFlow.Dock = DockStyle.Fill;
        standardCommandFlow.FlowDirection = FlowDirection.RightToLeft;
        standardCommandFlow.RightToLeft = RightToLeft.No;
        standardCommandFlow.WrapContents = false;
        standardCommandFlow.Padding = new Padding(2);
        standardCloseHost.Name = "standardCloseHost";
        standardCloseHost.Dock = DockStyle.Left;
        standardCloseHost.Width = 28;
        designerCommandBar.Controls.Add(standardCommandFlow);
        designerCommandBar.Controls.Add(standardCloseHost);
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = true;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.TabIndex = 0;
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandFlow.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = true;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.TabIndex = 1;
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandFlow.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.TabIndex = 2;
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandFlow.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.TabIndex = 3;
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandFlow.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        standardCommandView.Name = "standardCommandView";
        standardCommandView.AccessibleName = "عرض";
        standardCommandView.Enabled = false;
        standardCommandView.Visible = true;
        standardCommandView.Size = new Size(26, 24);
        standardCommandView.Margin = new Padding(1);
        standardCommandView.FlatStyle = FlatStyle.Flat;
        standardCommandView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandView.TabIndex = 4;
        standardCommandView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        standardCommandFlow.Controls.Add(standardCommandView);
        designerCommandBar.SetCommandRole(standardCommandView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.TabIndex = 5;
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandFlow.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.AccessibleName = "التالي";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.TabIndex = 6;
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandFlow.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.TabIndex = 7;
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandFlow.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.TabIndex = 8;
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFlow.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        standardCommandSave.Name = "btnSave";
        standardCommandSave.AccessibleName = "حفظ";
        standardCommandSave.Enabled = false;
        standardCommandSave.Visible = true;
        standardCommandSave.Size = new Size(26, 24);
        standardCommandSave.Margin = new Padding(1);
        standardCommandSave.FlatStyle = FlatStyle.Flat;
        standardCommandSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandSave.TabIndex = 9;
        standardCommandSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        standardCommandFlow.Controls.Add(standardCommandSave);
        designerCommandBar.SetCommandRole(standardCommandSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.TabIndex = 10;
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandFlow.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        standardCommandClose.Name = "standardCommandClose";
        standardCommandClose.AccessibleName = "إغلاق";
        standardCommandClose.Enabled = false;
        standardCommandClose.Visible = true;
        standardCommandClose.Size = new Size(26, 24);
        standardCommandClose.Margin = new Padding(1);
        standardCommandClose.FlatStyle = FlatStyle.Flat;
        standardCommandClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandClose.TabIndex = 11;
        standardCommandClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        standardCloseHost.Controls.Add(standardCommandClose);
        designerCommandBar.SetCommandRole(standardCommandClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.TabIndex = 12;
        standardCommandRefresh.Text = "تحديث";
        standardCommandFlow.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.TabIndex = 13;
        standardCommandImport.Text = "استيراد";
        standardCommandFlow.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.TabIndex = 14;
        standardCommandExport.Text = "تصدير";
        standardCommandFlow.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.TabIndex = 15;
        standardCommandHelp.Text = "مساعدة";
        standardCommandFlow.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
        standardCommandClose.Location = new Point(1, 1);
        standardCommandSave.AccessibleDescription = "الحفظ غير متاح؛ لم تُربط الشاشة بخدمة بيانات.";
        Controls.Add(designerCommandBar);

        layout = new TableLayoutPanel();
        fields = new TableLayoutPanel();
        lblTitle = new Label();
        lblStatus = new Label();
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        layout.SuspendLayout();
        fields.SuspendLayout();
        layout.Name = "layout";
        layout.Dock = DockStyle.Top;
        layout.AutoSize = true;
        layout.ColumnCount = 1;
        layout.RowCount = 4;
        layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "بيانات الأنشطة";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Font = new Font("Segoe UI", 16F);
        lblTitle.TextAlign = ContentAlignment.MiddleRight;
        lblTitle.BackColor = Color.FromArgb(192, 192, 255);
        lblTitle.Padding = new Padding(12);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "معاينة إدخال مؤقتة — الحفظ والترقيم التلقائي والقوائم غير متاحة؛ القيم لا تُطبّق على النظام.";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.TextAlign = ContentAlignment.MiddleRight;
        lblStatus.Padding = new Padding(8);
        fields.Name = "fields";
        fields.Dock = DockStyle.Top;
        fields.AutoSize = true;
        fields.ColumnCount = 2;
        fields.RowCount = 10;
        fields.Enabled = false;
        fields.TabIndex = 1;
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
        lbltxtActivityNumber = new Label();
        lbltxtActivityNumber.Name = "lbltxtActivityNumber";
        lbltxtActivityNumber.Text = "رقم النشاط";
        lbltxtActivityNumber.AutoSize = true;
        lbltxtActivityNumber.Dock = DockStyle.Fill;
        lbltxtActivityNumber.TextAlign = ContentAlignment.MiddleRight;
        lbltxtActivityNumber.Margin = new Padding(6, 8, 6, 8);
        txtActivityNumber = new TextBox();
        txtActivityNumber.Name = "txtActivityNumber";
        txtActivityNumber.AccessibleName = "رقم النشاط";
        txtActivityNumber.Dock = DockStyle.Fill;
        txtActivityNumber.TabIndex = 0;
        txtActivityNumber.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtActivityNumber, 0, 0);
        fields.Controls.Add(txtActivityNumber, 1, 0);
        lbltxtParentActivity = new Label();
        lbltxtParentActivity.Name = "lbltxtParentActivity";
        lbltxtParentActivity.Text = "النشاط الرئيسي";
        lbltxtParentActivity.AutoSize = true;
        lbltxtParentActivity.Dock = DockStyle.Fill;
        lbltxtParentActivity.TextAlign = ContentAlignment.MiddleRight;
        lbltxtParentActivity.Margin = new Padding(6, 8, 6, 8);
        txtParentActivity = new TextBox();
        txtParentActivity.Name = "txtParentActivity";
        txtParentActivity.AccessibleName = "النشاط الرئيسي";
        txtParentActivity.Dock = DockStyle.Fill;
        txtParentActivity.TabIndex = 1;
        txtParentActivity.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtParentActivity, 0, 1);
        fields.Controls.Add(txtParentActivity, 1, 1);
        lbltxtNameLocal = new Label();
        lbltxtNameLocal.Name = "lbltxtNameLocal";
        lbltxtNameLocal.Text = "اسم النشاط (محلي)";
        lbltxtNameLocal.AutoSize = true;
        lbltxtNameLocal.Dock = DockStyle.Fill;
        lbltxtNameLocal.TextAlign = ContentAlignment.MiddleRight;
        lbltxtNameLocal.Margin = new Padding(6, 8, 6, 8);
        txtNameLocal = new TextBox();
        txtNameLocal.Name = "txtNameLocal";
        txtNameLocal.AccessibleName = "اسم النشاط (محلي)";
        txtNameLocal.Dock = DockStyle.Fill;
        txtNameLocal.TabIndex = 2;
        txtNameLocal.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtNameLocal, 0, 2);
        fields.Controls.Add(txtNameLocal, 1, 2);
        lbltxtNameForeign = new Label();
        lbltxtNameForeign.Name = "lbltxtNameForeign";
        lbltxtNameForeign.Text = "اسم النشاط (أجنبي)";
        lbltxtNameForeign.AutoSize = true;
        lbltxtNameForeign.Dock = DockStyle.Fill;
        lbltxtNameForeign.TextAlign = ContentAlignment.MiddleRight;
        lbltxtNameForeign.Margin = new Padding(6, 8, 6, 8);
        txtNameForeign = new TextBox();
        txtNameForeign.Name = "txtNameForeign";
        txtNameForeign.AccessibleName = "اسم النشاط (أجنبي)";
        txtNameForeign.Dock = DockStyle.Fill;
        txtNameForeign.TabIndex = 3;
        txtNameForeign.Margin = new Padding(6, 8, 6, 8);
        txtNameForeign.RightToLeft = RightToLeft.No;
        txtNameForeign.TextAlign = HorizontalAlignment.Left;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtNameForeign, 0, 3);
        fields.Controls.Add(txtNameForeign, 1, 3);
        lbltxtRank = new Label();
        lbltxtRank.Name = "lbltxtRank";
        lbltxtRank.Text = "الرتبة";
        lbltxtRank.AutoSize = true;
        lbltxtRank.Dock = DockStyle.Fill;
        lbltxtRank.TextAlign = ContentAlignment.MiddleRight;
        lbltxtRank.Margin = new Padding(6, 8, 6, 8);
        txtRank = new TextBox();
        txtRank.Name = "txtRank";
        txtRank.AccessibleName = "الرتبة";
        txtRank.Dock = DockStyle.Fill;
        txtRank.TabIndex = 4;
        txtRank.Margin = new Padding(6, 8, 6, 8);
        txtRank.ReadOnly = true;
        txtRank.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtRank, 0, 4);
        fields.Controls.Add(txtRank, 1, 4);
        lblcboActivityType = new Label();
        lblcboActivityType.Name = "lblcboActivityType";
        lblcboActivityType.Text = "نوع النشاط";
        lblcboActivityType.AutoSize = true;
        lblcboActivityType.Dock = DockStyle.Fill;
        lblcboActivityType.TextAlign = ContentAlignment.MiddleRight;
        lblcboActivityType.Margin = new Padding(6, 8, 6, 8);
        cboActivityType = new ComboBox();
        cboActivityType.Name = "cboActivityType";
        cboActivityType.AccessibleName = "نوع النشاط";
        cboActivityType.Dock = DockStyle.Fill;
        cboActivityType.TabIndex = 5;
        cboActivityType.Margin = new Padding(6, 8, 6, 8);
        cboActivityType.DropDownStyle = ComboBoxStyle.DropDownList;
        cboActivityType.Enabled = false;
        cboActivityType.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboActivityType, 0, 5);
        fields.Controls.Add(cboActivityType, 1, 5);
        lblcboActivityGroup = new Label();
        lblcboActivityGroup.Name = "lblcboActivityGroup";
        lblcboActivityGroup.Text = "مجموعة الأنشطة";
        lblcboActivityGroup.AutoSize = true;
        lblcboActivityGroup.Dock = DockStyle.Fill;
        lblcboActivityGroup.TextAlign = ContentAlignment.MiddleRight;
        lblcboActivityGroup.Margin = new Padding(6, 8, 6, 8);
        cboActivityGroup = new ComboBox();
        cboActivityGroup.Name = "cboActivityGroup";
        cboActivityGroup.AccessibleName = "مجموعة الأنشطة";
        cboActivityGroup.Dock = DockStyle.Fill;
        cboActivityGroup.TabIndex = 6;
        cboActivityGroup.Margin = new Padding(6, 8, 6, 8);
        cboActivityGroup.DropDownStyle = ComboBoxStyle.DropDownList;
        cboActivityGroup.Enabled = false;
        cboActivityGroup.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboActivityGroup, 0, 6);
        fields.Controls.Add(cboActivityGroup, 1, 6);
        lblchkStopped = new Label();
        lblchkStopped.Name = "lblchkStopped";
        lblchkStopped.Text = "موقف";
        lblchkStopped.AutoSize = true;
        lblchkStopped.Dock = DockStyle.Fill;
        lblchkStopped.TextAlign = ContentAlignment.MiddleRight;
        lblchkStopped.Margin = new Padding(6, 8, 6, 8);
        chkStopped = new CheckBox();
        chkStopped.Name = "chkStopped";
        chkStopped.AccessibleName = "موقف";
        chkStopped.Dock = DockStyle.Fill;
        chkStopped.TabIndex = 7;
        chkStopped.Margin = new Padding(6, 8, 6, 8);
        chkStopped.AutoSize = true;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblchkStopped, 0, 7);
        fields.Controls.Add(chkStopped, 1, 7);
        lbltxtStopReason = new Label();
        lbltxtStopReason.Name = "lbltxtStopReason";
        lbltxtStopReason.Text = "سبب الإيقاف";
        lbltxtStopReason.AutoSize = true;
        lbltxtStopReason.Dock = DockStyle.Fill;
        lbltxtStopReason.TextAlign = ContentAlignment.MiddleRight;
        lbltxtStopReason.Margin = new Padding(6, 8, 6, 8);
        txtStopReason = new TextBox();
        txtStopReason.Name = "txtStopReason";
        txtStopReason.AccessibleName = "سبب الإيقاف";
        txtStopReason.Dock = DockStyle.Fill;
        txtStopReason.TabIndex = 8;
        txtStopReason.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtStopReason, 0, 8);
        fields.Controls.Add(txtStopReason, 1, 8);
        lbltxtStoppedAt = new Label();
        lbltxtStoppedAt.Name = "lbltxtStoppedAt";
        lbltxtStoppedAt.Text = "تاريخ الإيقاف";
        lbltxtStoppedAt.AutoSize = true;
        lbltxtStoppedAt.Dock = DockStyle.Fill;
        lbltxtStoppedAt.TextAlign = ContentAlignment.MiddleRight;
        lbltxtStoppedAt.Margin = new Padding(6, 8, 6, 8);
        txtStoppedAt = new TextBox();
        txtStoppedAt.Name = "txtStoppedAt";
        txtStoppedAt.AccessibleName = "تاريخ الإيقاف";
        txtStoppedAt.Dock = DockStyle.Fill;
        txtStoppedAt.TabIndex = 9;
        txtStoppedAt.Margin = new Padding(6, 8, 6, 8);
        txtStoppedAt.ReadOnly = true;
        txtStoppedAt.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtStoppedAt, 0, 9);
        fields.Controls.Add(txtStoppedAt, 1, 9);
        standardCommandAdd.Name = "btnAdd";
        standardCommandAdd.Enabled = true;
        standardCommandAdd.Click += draftAction_Click;
        standardCommandSave.Name = "btnSave";
        standardCommandSave.Enabled = false;
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        layout.Controls.Add(lblTitle, 0, 0);
        layout.Controls.Add(lblStatus, 0, 1);
        layout.Controls.Add(designerCommandBar, 0, 2);
        layout.Controls.Add(fields, 0, 3);
        Controls.Add(layout);


        Name = "UcActivityData";
        Text = "بيانات الأنشطة";
        Size = new Size(1000, 640);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        RightToLeft = RightToLeft.Yes;
        fields.ResumeLayout(true);
        layout.ResumeLayout(true);
        ResumeLayout(true);
        tabsAdditionalFields = new TabControl();
        tabAdditionalFields = new TabPage();
        tabsAdditionalFields.Name = "tabsAdditionalFields";
        tabsAdditionalFields.Dock = DockStyle.Fill;
        tabsAdditionalFields.Height = 180;
        tabsAdditionalFields.MinimumSize = new Size(0, 180);
        tabsAdditionalFields.RightToLeft = RightToLeft.Yes;
        tabsAdditionalFields.RightToLeftLayout = true;
        tabAdditionalFields.Name = "tabAdditionalFields";
        tabAdditionalFields.Text = "حقول إضافية";
        tabAdditionalFields.AccessibleDescription = "الحقول قابلة للتهيئة؛ لم تُربط بيانات تعريفها بعد.";
        tabsAdditionalFields.TabPages.Add(tabAdditionalFields);
        layout.RowCount = 5;
        layout.Controls.Add(tabsAdditionalFields, 0, 4);

        btnLinkProject = new Button();
        standardCommandAdd.Visible = true;
        standardCommandEdit.Visible = true;
        standardCommandDelete.Visible = true;
        standardCommandCancel.Visible = true;
        standardCommandView.Visible = true;
        standardCommandLast.Visible = true;
        standardCommandNext.Visible = true;
        standardCommandPrevious.Visible = true;
        standardCommandFirst.Visible = true;
        standardCommandSave.Visible = true;
        standardCommandPrint.Visible = true;
        standardCommandClose.Visible = true;
        standardCommandRefresh.Visible = false;
        standardCommandImport.Visible = false;
        standardCommandExport.Visible = false;
        standardCommandHelp.Visible = false;
        btnLinkProject.Name = "btnLinkProject";
        btnLinkProject.Text = "ربط النشاط بالمشروع";
        btnLinkProject.AutoSize = true;
        btnLinkProject.Enabled = false;
        btnLinkProject.Visible = false;
        btnLinkProject.AccessibleDescription = "يتطلب تفعيل ربط المشاريع بالأنشطة؛ الإعداد غير مرتبط بعد.";
        standardCommandFlow.Controls.Add(btnLinkProject);
        standardCommandImport.Visible = true;
        standardCommandImport.Name = "btnImportExcel";
        standardCommandImport.Text = "الاستيراد من الإكسل";
        standardCommandImport.AutoSize = true;
        standardCommandImport.Enabled = false;
        standardCommandImport.AccessibleDescription = "استيراد دليل الأنشطة غير متاح؛ لم تُربط خدمة الاستيراد.";
    

        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
    }
}
