namespace TransportERP.Desktop.Forms.SystemSettings.General;
partial class UcAreaData
{
    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private FlowLayoutPanel standardCommandFlow = null!;
    private Panel standardCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandView = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandSave = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandClose = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel layout = null!;
    private TableLayoutPanel fields = null!;
    private Label lblTitle = null!;
    private Label lblStatus = null!;
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;
    private Label lbltxtAreaNumber = null!;
    private TextBox txtAreaNumber = null!;
    private Label lbltxtAreaNameLocal = null!;
    private TextBox txtAreaNameLocal = null!;
    private Label lbltxtAreaNameForeign = null!;
    private TextBox txtAreaNameForeign = null!;
    private Label lblcboCityNumber = null!;
    private ComboBox cboCityNumber = null!;
    private Label lblchkSubCity = null!;
    private CheckBox chkSubCity = null!;
    private DataGridView gridStatistics = null!;
    private DataGridViewTextBoxColumn gridStatistics_colDocumentNumber = null!;
    private DataGridViewTextBoxColumn gridStatistics_colCurrency = null!;
    private DataGridViewTextBoxColumn gridStatistics_colAmount = null!;
    private GroupBox grpgridStatistics = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        standardCommandFlow = new FlowLayoutPanel();
        standardCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandView = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandSave = new Button();
        standardCommandPrint = new Button();
        standardCommandClose = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.Size = new Size(1000, 44);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Margin = Padding.Empty;
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        standardCommandFlow.Name = "pnlToolbar";
        standardCommandFlow.Dock = DockStyle.Fill;
        standardCommandFlow.FlowDirection = FlowDirection.RightToLeft;
        standardCommandFlow.RightToLeft = RightToLeft.No;
        standardCommandFlow.WrapContents = false;
        standardCommandFlow.Padding = new Padding(2);
        standardCloseHost.Name = "standardCloseHost";
        standardCloseHost.Dock = DockStyle.Left;
        standardCloseHost.Width = 28;
        designerCommandBar.Controls.Add(standardCommandFlow);
        designerCommandBar.Controls.Add(standardCloseHost);
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = true;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.TabIndex = 0;
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandFlow.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = true;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.TabIndex = 1;
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandFlow.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.TabIndex = 2;
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandFlow.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.TabIndex = 3;
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandFlow.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        standardCommandView.Name = "standardCommandView";
        standardCommandView.AccessibleName = "عرض";
        standardCommandView.Enabled = false;
        standardCommandView.Visible = true;
        standardCommandView.Size = new Size(26, 24);
        standardCommandView.Margin = new Padding(1);
        standardCommandView.FlatStyle = FlatStyle.Flat;
        standardCommandView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandView.TabIndex = 4;
        standardCommandView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        standardCommandFlow.Controls.Add(standardCommandView);
        designerCommandBar.SetCommandRole(standardCommandView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.TabIndex = 5;
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandFlow.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.AccessibleName = "التالي";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.TabIndex = 6;
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandFlow.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.TabIndex = 7;
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandFlow.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.TabIndex = 8;
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFlow.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        standardCommandSave.Name = "btnSave";
        standardCommandSave.AccessibleName = "حفظ";
        standardCommandSave.Enabled = false;
        standardCommandSave.Visible = true;
        standardCommandSave.Size = new Size(26, 24);
        standardCommandSave.Margin = new Padding(1);
        standardCommandSave.FlatStyle = FlatStyle.Flat;
        standardCommandSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandSave.TabIndex = 9;
        standardCommandSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        standardCommandFlow.Controls.Add(standardCommandSave);
        designerCommandBar.SetCommandRole(standardCommandSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.TabIndex = 10;
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandFlow.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        standardCommandClose.Name = "standardCommandClose";
        standardCommandClose.AccessibleName = "إغلاق";
        standardCommandClose.Enabled = false;
        standardCommandClose.Visible = true;
        standardCommandClose.Size = new Size(26, 24);
        standardCommandClose.Margin = new Padding(1);
        standardCommandClose.FlatStyle = FlatStyle.Flat;
        standardCommandClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandClose.TabIndex = 11;
        standardCommandClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        standardCloseHost.Controls.Add(standardCommandClose);
        designerCommandBar.SetCommandRole(standardCommandClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.TabIndex = 12;
        standardCommandRefresh.Text = "تحديث";
        standardCommandFlow.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.TabIndex = 13;
        standardCommandImport.Text = "استيراد";
        standardCommandFlow.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.TabIndex = 14;
        standardCommandExport.Text = "تصدير";
        standardCommandFlow.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.TabIndex = 15;
        standardCommandHelp.Text = "مساعدة";
        standardCommandFlow.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
        standardCommandClose.Location = new Point(1, 1);
        standardCommandSave.AccessibleDescription = "الحفظ غير متاح؛ لم تُربط الشاشة بخدمة بيانات.";
        Controls.Add(designerCommandBar);

        layout = new TableLayoutPanel();
        fields = new TableLayoutPanel();
        lblTitle = new Label();
        lblStatus = new Label();
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        layout.SuspendLayout();
        fields.SuspendLayout();
        layout.Name = "layout";
        layout.Dock = DockStyle.Top;
        layout.AutoSize = true;
        layout.ColumnCount = 1;
        layout.RowCount = 5;
        layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "بيانات المناطق";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Font = new Font("Segoe UI", 16F);
        lblTitle.TextAlign = ContentAlignment.MiddleRight;
        lblTitle.BackColor = Color.FromArgb(192, 192, 255);
        lblTitle.Padding = new Padding(12);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "معاينة إدخال مؤقتة — الحفظ والترقيم التلقائي والقوائم غير متاحة؛ القيم لا تُطبّق على النظام.";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.TextAlign = ContentAlignment.MiddleRight;
        lblStatus.Padding = new Padding(8);
        fields.Name = "fields";
        fields.Dock = DockStyle.Top;
        fields.AutoSize = true;
        fields.ColumnCount = 2;
        fields.RowCount = 5;
        fields.Enabled = false;
        fields.TabIndex = 1;
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
        lbltxtAreaNumber = new Label();
        lbltxtAreaNumber.Name = "lbltxtAreaNumber";
        lbltxtAreaNumber.Text = "رقم المنطقة";
        lbltxtAreaNumber.AutoSize = true;
        lbltxtAreaNumber.Dock = DockStyle.Fill;
        lbltxtAreaNumber.TextAlign = ContentAlignment.MiddleRight;
        lbltxtAreaNumber.Margin = new Padding(6, 8, 6, 8);
        txtAreaNumber = new TextBox();
        txtAreaNumber.BackColor = Color.White;
        txtAreaNumber.Name = "txtAreaNumber";
        txtAreaNumber.AccessibleName = "رقم المنطقة";
        txtAreaNumber.Dock = DockStyle.Fill;
        txtAreaNumber.TabIndex = 0;
        txtAreaNumber.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtAreaNumber, 0, 0);
        fields.Controls.Add(txtAreaNumber, 1, 0);
        lbltxtAreaNameLocal = new Label();
        lbltxtAreaNameLocal.Name = "lbltxtAreaNameLocal";
        lbltxtAreaNameLocal.Text = "اسم المنطقة (محلي)";
        lbltxtAreaNameLocal.AutoSize = true;
        lbltxtAreaNameLocal.Dock = DockStyle.Fill;
        lbltxtAreaNameLocal.TextAlign = ContentAlignment.MiddleRight;
        lbltxtAreaNameLocal.Margin = new Padding(6, 8, 6, 8);
        txtAreaNameLocal = new TextBox();
        txtAreaNameLocal.BackColor = Color.White;
        txtAreaNameLocal.Name = "txtAreaNameLocal";
        txtAreaNameLocal.AccessibleName = "اسم المنطقة (محلي)";
        txtAreaNameLocal.Dock = DockStyle.Fill;
        txtAreaNameLocal.TabIndex = 1;
        txtAreaNameLocal.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtAreaNameLocal, 0, 1);
        fields.Controls.Add(txtAreaNameLocal, 1, 1);
        lbltxtAreaNameForeign = new Label();
        lbltxtAreaNameForeign.Name = "lbltxtAreaNameForeign";
        lbltxtAreaNameForeign.Text = "اسم المنطقة (أجنبي)";
        lbltxtAreaNameForeign.AutoSize = true;
        lbltxtAreaNameForeign.Dock = DockStyle.Fill;
        lbltxtAreaNameForeign.TextAlign = ContentAlignment.MiddleRight;
        lbltxtAreaNameForeign.Margin = new Padding(6, 8, 6, 8);
        txtAreaNameForeign = new TextBox();
        txtAreaNameForeign.BackColor = Color.White;
        txtAreaNameForeign.Name = "txtAreaNameForeign";
        txtAreaNameForeign.AccessibleName = "اسم المنطقة (أجنبي)";
        txtAreaNameForeign.Dock = DockStyle.Fill;
        txtAreaNameForeign.TabIndex = 2;
        txtAreaNameForeign.Margin = new Padding(6, 8, 6, 8);
        txtAreaNameForeign.RightToLeft = RightToLeft.No;
        txtAreaNameForeign.TextAlign = HorizontalAlignment.Left;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtAreaNameForeign, 0, 2);
        fields.Controls.Add(txtAreaNameForeign, 1, 2);
        lblcboCityNumber = new Label();
        lblcboCityNumber.Name = "lblcboCityNumber";
        lblcboCityNumber.Text = "رقم المدينة";
        lblcboCityNumber.AutoSize = true;
        lblcboCityNumber.Dock = DockStyle.Fill;
        lblcboCityNumber.TextAlign = ContentAlignment.MiddleRight;
        lblcboCityNumber.Margin = new Padding(6, 8, 6, 8);
        cboCityNumber = new ComboBox();
        cboCityNumber.Name = "cboCityNumber";
        cboCityNumber.AccessibleName = "رقم المدينة";
        cboCityNumber.Dock = DockStyle.Fill;
        cboCityNumber.TabIndex = 3;
        cboCityNumber.Margin = new Padding(6, 8, 6, 8);
        cboCityNumber.DropDownStyle = ComboBoxStyle.DropDownList;
        cboCityNumber.Enabled = false;
        cboCityNumber.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboCityNumber, 0, 3);
        fields.Controls.Add(cboCityNumber, 1, 3);
        lblchkSubCity = new Label();
        lblchkSubCity.Name = "lblchkSubCity";
        lblchkSubCity.Text = "مدينة فرعية";
        lblchkSubCity.AutoSize = true;
        lblchkSubCity.Dock = DockStyle.Fill;
        lblchkSubCity.TextAlign = ContentAlignment.MiddleRight;
        lblchkSubCity.Margin = new Padding(6, 8, 6, 8);
        chkSubCity = new CheckBox();
        chkSubCity.Name = "chkSubCity";
        chkSubCity.AccessibleName = "مدينة فرعية";
        chkSubCity.Dock = DockStyle.Fill;
        chkSubCity.TabIndex = 4;
        chkSubCity.Margin = new Padding(6, 8, 6, 8);
        chkSubCity.AutoSize = true;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblchkSubCity, 0, 4);
        fields.Controls.Add(chkSubCity, 1, 4);
        gridStatistics = new DataGridView();
        ((System.ComponentModel.ISupportInitialize)gridStatistics).BeginInit();
        gridStatistics.Name = "gridStatistics";
        gridStatistics.AccessibleName = "البيانات الإحصائية";
        gridStatistics.Dock = DockStyle.Fill;
        gridStatistics.Height = 220;
        gridStatistics.MinimumSize = new Size(0, 220);
        gridStatistics.AutoGenerateColumns = false;
        gridStatistics.ReadOnly = true;
        gridStatistics.AllowUserToAddRows = false;
        gridStatistics.AllowUserToDeleteRows = false;
        gridStatistics.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        gridStatistics.RowHeadersVisible = false;
        gridStatistics.Enabled = true;
        gridStatistics.TabIndex = 2;
        gridStatistics.CurrentCellDirtyStateChanged += grid_CurrentCellDirtyStateChanged;
        gridStatistics_colDocumentNumber = new DataGridViewTextBoxColumn();
        gridStatistics_colDocumentNumber.Name = "colDocumentNumber";
        gridStatistics_colDocumentNumber.HeaderText = "رقم الوثيقة";
        gridStatistics_colDocumentNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridStatistics_colCurrency = new DataGridViewTextBoxColumn();
        gridStatistics_colCurrency.Name = "colCurrency";
        gridStatistics_colCurrency.HeaderText = "العملة";
        gridStatistics_colCurrency.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridStatistics_colAmount = new DataGridViewTextBoxColumn();
        gridStatistics_colAmount.Name = "colAmount";
        gridStatistics_colAmount.HeaderText = "المبلغ";
        gridStatistics_colAmount.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridStatistics.Columns.AddRange(gridStatistics_colDocumentNumber, gridStatistics_colCurrency, gridStatistics_colAmount);
        grpgridStatistics = new GroupBox();
        grpgridStatistics.Name = "grpgridStatistics";
        grpgridStatistics.Text = "البيانات الإحصائية";
        grpgridStatistics.Dock = DockStyle.Fill;
        grpgridStatistics.Height = 260;
        grpgridStatistics.MinimumSize = new Size(0, 260);
        grpgridStatistics.Padding = new Padding(8, 28, 8, 8);
        grpgridStatistics.Controls.Add(gridStatistics);
        layout.Controls.Add(grpgridStatistics, 0, 4);
        ((System.ComponentModel.ISupportInitialize)gridStatistics).EndInit();
        standardCommandAdd.Name = "btnAdd";
        standardCommandAdd.Enabled = true;
        standardCommandAdd.Click += draftAction_Click;
        standardCommandSave.Name = "btnSave";
        standardCommandSave.Enabled = false;
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        layout.Controls.Add(lblTitle, 0, 0);
        layout.Controls.Add(lblStatus, 0, 1);
        layout.Controls.Add(designerCommandBar, 0, 2);
        layout.Controls.Add(fields, 0, 3);
        Controls.Add(layout);


        Name = "UcAreaData";
        Text = "بيانات المناطق";
        Size = new Size(1000, 640);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        RightToLeft = RightToLeft.Yes;
        fields.ResumeLayout(true);
        layout.ResumeLayout(true);
        ResumeLayout(true);
        standardAuditMetadata.Profile = TransportERP.Desktop.CoreUI.AuditMetadataProfile.ModificationOnly;
        standardAuditMetadata.Size = new Size(800, 36);

        standardCommandAdd.Visible = true;
        standardCommandEdit.Visible = true;
        standardCommandDelete.Visible = true;
        standardCommandCancel.Visible = true;
        standardCommandView.Visible = true;
        standardCommandLast.Visible = true;
        standardCommandNext.Visible = true;
        standardCommandPrevious.Visible = true;
        standardCommandFirst.Visible = true;
        standardCommandSave.Visible = true;
        standardCommandPrint.Visible = true;
        standardCommandClose.Visible = true;
        standardCommandRefresh.Visible = false;
        standardCommandImport.Visible = false;
        standardCommandExport.Visible = false;
        standardCommandHelp.Visible = false;
    

        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
    }
}
