namespace TransportERP.Desktop.Forms.SystemSettings.General;
partial class UcCashFlowAccountLinks
{
    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private FlowLayoutPanel standardCommandFlow = null!;
    private Panel standardCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandView = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandSave = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandClose = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel layout = null!;
    private TableLayoutPanel fields = null!;
    private Label lblTitle = null!;
    private Label lblStatus = null!;
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;
    private Label lblchkUpdateChart = null!;
    private CheckBox chkUpdateChart = null!;
    private TabControl tabsSetup = null!;
    private DataGridView gridAnalysisFlow = null!;
    private DataGridViewTextBoxColumn gridAnalysisFlow_colAnalysis = null!;
    private DataGridViewTextBoxColumn gridAnalysisFlow_colTypeNameLocal = null!;
    private DataGridViewTextBoxColumn gridAnalysisFlow_colTypeNameForeign = null!;
    private DataGridViewTextBoxColumn gridAnalysisFlow_colLevel = null!;
    private DataGridViewTextBoxColumn gridAnalysisFlow_colAccountType = null!;
    private DataGridViewTextBoxColumn gridAnalysisFlow_colAnalyticalType = null!;
    private DataGridViewComboBoxColumn gridAnalysisFlow_colFlowType = null!;
    private TabPage tabgridAnalysisFlow = null!;
    private DataGridView gridAccountAnalysis = null!;
    private DataGridViewTextBoxColumn gridAccountAnalysis_colAccountNumber = null!;
    private DataGridViewTextBoxColumn gridAccountAnalysis_colAccountName = null!;
    private DataGridViewComboBoxColumn gridAccountAnalysis_colAnalysis = null!;
    private DataGridViewTextBoxColumn gridAccountAnalysis_colFlowType = null!;
    private TabPage tabgridAccountAnalysis = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        standardCommandFlow = new FlowLayoutPanel();
        standardCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandView = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandSave = new Button();
        standardCommandPrint = new Button();
        standardCommandClose = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.Size = new Size(1000, 44);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Margin = Padding.Empty;
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        standardCommandFlow.Name = "pnlToolbar";
        standardCommandFlow.Dock = DockStyle.Fill;
        standardCommandFlow.FlowDirection = FlowDirection.RightToLeft;
        standardCommandFlow.RightToLeft = RightToLeft.No;
        standardCommandFlow.WrapContents = false;
        standardCommandFlow.Padding = new Padding(2);
        standardCloseHost.Name = "standardCloseHost";
        standardCloseHost.Dock = DockStyle.Left;
        standardCloseHost.Width = 28;
        designerCommandBar.Controls.Add(standardCommandFlow);
        designerCommandBar.Controls.Add(standardCloseHost);
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = true;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.TabIndex = 0;
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandFlow.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = true;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.TabIndex = 1;
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandFlow.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.TabIndex = 2;
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandFlow.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.TabIndex = 3;
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandFlow.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        standardCommandView.Name = "standardCommandView";
        standardCommandView.AccessibleName = "عرض";
        standardCommandView.Enabled = false;
        standardCommandView.Visible = true;
        standardCommandView.Size = new Size(26, 24);
        standardCommandView.Margin = new Padding(1);
        standardCommandView.FlatStyle = FlatStyle.Flat;
        standardCommandView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandView.TabIndex = 4;
        standardCommandView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        standardCommandFlow.Controls.Add(standardCommandView);
        designerCommandBar.SetCommandRole(standardCommandView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.TabIndex = 5;
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandFlow.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.AccessibleName = "التالي";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.TabIndex = 6;
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandFlow.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.TabIndex = 7;
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandFlow.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.TabIndex = 8;
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFlow.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        standardCommandSave.Name = "btnSave";
        standardCommandSave.AccessibleName = "حفظ";
        standardCommandSave.Enabled = false;
        standardCommandSave.Visible = true;
        standardCommandSave.Size = new Size(26, 24);
        standardCommandSave.Margin = new Padding(1);
        standardCommandSave.FlatStyle = FlatStyle.Flat;
        standardCommandSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandSave.TabIndex = 9;
        standardCommandSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        standardCommandFlow.Controls.Add(standardCommandSave);
        designerCommandBar.SetCommandRole(standardCommandSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.TabIndex = 10;
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandFlow.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        standardCommandClose.Name = "standardCommandClose";
        standardCommandClose.AccessibleName = "إغلاق";
        standardCommandClose.Enabled = false;
        standardCommandClose.Visible = true;
        standardCommandClose.Size = new Size(26, 24);
        standardCommandClose.Margin = new Padding(1);
        standardCommandClose.FlatStyle = FlatStyle.Flat;
        standardCommandClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandClose.TabIndex = 11;
        standardCommandClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        standardCloseHost.Controls.Add(standardCommandClose);
        designerCommandBar.SetCommandRole(standardCommandClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.TabIndex = 12;
        standardCommandRefresh.Text = "تحديث";
        standardCommandFlow.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.TabIndex = 13;
        standardCommandImport.Text = "استيراد";
        standardCommandFlow.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.TabIndex = 14;
        standardCommandExport.Text = "تصدير";
        standardCommandFlow.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.TabIndex = 15;
        standardCommandHelp.Text = "مساعدة";
        standardCommandFlow.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
        standardCommandClose.Location = new Point(1, 1);
        standardCommandSave.AccessibleDescription = "الحفظ غير متاح؛ لم تُربط الشاشة بخدمة بيانات.";
        Controls.Add(designerCommandBar);

        layout = new TableLayoutPanel();
        fields = new TableLayoutPanel();
        lblTitle = new Label();
        lblStatus = new Label();
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        layout.SuspendLayout();
        fields.SuspendLayout();
        layout.Name = "layout";
        layout.Dock = DockStyle.Top;
        layout.AutoSize = true;
        layout.ColumnCount = 1;
        layout.RowCount = 5;
        layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "ربط التدفقات النقدية مع تحليل الحسابات";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Font = new Font("Segoe UI", 16F);
        lblTitle.TextAlign = ContentAlignment.MiddleRight;
        lblTitle.BackColor = Color.FromArgb(192, 192, 255);
        lblTitle.Padding = new Padding(12);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "معاينة إدخال مؤقتة — الحفظ والترقيم التلقائي والقوائم غير متاحة؛ القيم لا تُطبّق على النظام.";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.TextAlign = ContentAlignment.MiddleRight;
        lblStatus.Padding = new Padding(8);
        fields.Name = "fields";
        fields.Dock = DockStyle.Top;
        fields.AutoSize = true;
        fields.ColumnCount = 2;
        fields.RowCount = 1;
        fields.Enabled = false;
        fields.TabIndex = 1;
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
        lblchkUpdateChart = new Label();
        lblchkUpdateChart.Name = "lblchkUpdateChart";
        lblchkUpdateChart.Text = "تحديث دليل الحسابات";
        lblchkUpdateChart.AutoSize = true;
        lblchkUpdateChart.Dock = DockStyle.Fill;
        lblchkUpdateChart.TextAlign = ContentAlignment.MiddleRight;
        lblchkUpdateChart.Margin = new Padding(6, 8, 6, 8);
        chkUpdateChart = new CheckBox();
        chkUpdateChart.Name = "chkUpdateChart";
        chkUpdateChart.AccessibleName = "تحديث دليل الحسابات";
        chkUpdateChart.Dock = DockStyle.Fill;
        chkUpdateChart.TabIndex = 0;
        chkUpdateChart.Margin = new Padding(6, 8, 6, 8);
        chkUpdateChart.AutoSize = true;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblchkUpdateChart, 0, 0);
        fields.Controls.Add(chkUpdateChart, 1, 0);
        tabsSetup = new TabControl();
        tabsSetup.Name = "tabsSetup";
        tabsSetup.Dock = DockStyle.Fill;
        tabsSetup.Height = 340;
        tabsSetup.MinimumSize = new Size(0, 340);
        tabsSetup.RightToLeft = RightToLeft.Yes;
        tabsSetup.RightToLeftLayout = true;
        tabsSetup.TabIndex = 2;
        layout.Controls.Add(tabsSetup, 0, 4);
        gridAnalysisFlow = new DataGridView();
        ((System.ComponentModel.ISupportInitialize)gridAnalysisFlow).BeginInit();
        gridAnalysisFlow.Name = "gridAnalysisFlow";
        gridAnalysisFlow.AccessibleName = "ربط الحساب بنوع التدفق";
        gridAnalysisFlow.Dock = DockStyle.Fill;
        gridAnalysisFlow.Height = 220;
        gridAnalysisFlow.MinimumSize = new Size(0, 220);
        gridAnalysisFlow.AutoGenerateColumns = false;
        gridAnalysisFlow.ReadOnly = false;
        gridAnalysisFlow.AllowUserToAddRows = false;
        gridAnalysisFlow.AllowUserToDeleteRows = false;
        gridAnalysisFlow.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        gridAnalysisFlow.RowHeadersVisible = false;
        gridAnalysisFlow.Enabled = false;
        gridAnalysisFlow.TabIndex = 2;
        gridAnalysisFlow.CurrentCellDirtyStateChanged += grid_CurrentCellDirtyStateChanged;
        gridAnalysisFlow_colAnalysis = new DataGridViewTextBoxColumn();
        gridAnalysisFlow_colAnalysis.Name = "colAnalysis";
        gridAnalysisFlow_colAnalysis.HeaderText = "تحليل الحسابات";
        gridAnalysisFlow_colAnalysis.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridAnalysisFlow_colAnalysis.ReadOnly = true;
        gridAnalysisFlow_colTypeNameLocal = new DataGridViewTextBoxColumn();
        gridAnalysisFlow_colTypeNameLocal.Name = "colTypeNameLocal";
        gridAnalysisFlow_colTypeNameLocal.HeaderText = "اسم النوع (محلي)";
        gridAnalysisFlow_colTypeNameLocal.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridAnalysisFlow_colTypeNameLocal.ReadOnly = true;
        gridAnalysisFlow_colTypeNameForeign = new DataGridViewTextBoxColumn();
        gridAnalysisFlow_colTypeNameForeign.Name = "colTypeNameForeign";
        gridAnalysisFlow_colTypeNameForeign.HeaderText = "اسم النوع (أجنبي)";
        gridAnalysisFlow_colTypeNameForeign.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridAnalysisFlow_colTypeNameForeign.ReadOnly = true;
        gridAnalysisFlow_colLevel = new DataGridViewTextBoxColumn();
        gridAnalysisFlow_colLevel.Name = "colLevel";
        gridAnalysisFlow_colLevel.HeaderText = "المستوى";
        gridAnalysisFlow_colLevel.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridAnalysisFlow_colLevel.ReadOnly = true;
        gridAnalysisFlow_colAccountType = new DataGridViewTextBoxColumn();
        gridAnalysisFlow_colAccountType.Name = "colAccountType";
        gridAnalysisFlow_colAccountType.HeaderText = "نوع الحساب";
        gridAnalysisFlow_colAccountType.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridAnalysisFlow_colAccountType.ReadOnly = true;
        gridAnalysisFlow_colAnalyticalType = new DataGridViewTextBoxColumn();
        gridAnalysisFlow_colAnalyticalType.Name = "colAnalyticalType";
        gridAnalysisFlow_colAnalyticalType.HeaderText = "نوع الحساب التحليلي";
        gridAnalysisFlow_colAnalyticalType.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridAnalysisFlow_colAnalyticalType.ReadOnly = true;
        gridAnalysisFlow_colFlowType = new DataGridViewComboBoxColumn();
        gridAnalysisFlow_colFlowType.Name = "colFlowType";
        gridAnalysisFlow_colFlowType.HeaderText = "نوع التدفق";
        gridAnalysisFlow_colFlowType.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridAnalysisFlow_colFlowType.DisplayStyle = DataGridViewComboBoxDisplayStyle.DropDownButton;
        gridAnalysisFlow_colFlowType.Items.AddRange(new object[] { "تشغيلي", "استثماري", "تمويلي" });
        gridAnalysisFlow.Columns.AddRange(gridAnalysisFlow_colAnalysis, gridAnalysisFlow_colTypeNameLocal, gridAnalysisFlow_colTypeNameForeign, gridAnalysisFlow_colLevel, gridAnalysisFlow_colAccountType, gridAnalysisFlow_colAnalyticalType, gridAnalysisFlow_colFlowType);
        tabgridAnalysisFlow = new TabPage();
        tabgridAnalysisFlow.Name = "tabgridAnalysisFlow";
        tabgridAnalysisFlow.Text = "ربط الحساب بنوع التدفق";
        tabgridAnalysisFlow.Controls.Add(gridAnalysisFlow);
        tabsSetup.TabPages.Add(tabgridAnalysisFlow);
        ((System.ComponentModel.ISupportInitialize)gridAnalysisFlow).EndInit();
        gridAccountAnalysis = new DataGridView();
        ((System.ComponentModel.ISupportInitialize)gridAccountAnalysis).BeginInit();
        gridAccountAnalysis.Name = "gridAccountAnalysis";
        gridAccountAnalysis.AccessibleName = "ربط الحسابات بتحليل الحساب";
        gridAccountAnalysis.Dock = DockStyle.Fill;
        gridAccountAnalysis.Height = 220;
        gridAccountAnalysis.MinimumSize = new Size(0, 220);
        gridAccountAnalysis.AutoGenerateColumns = false;
        gridAccountAnalysis.ReadOnly = false;
        gridAccountAnalysis.AllowUserToAddRows = false;
        gridAccountAnalysis.AllowUserToDeleteRows = false;
        gridAccountAnalysis.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        gridAccountAnalysis.RowHeadersVisible = false;
        gridAccountAnalysis.Enabled = false;
        gridAccountAnalysis.TabIndex = 2;
        gridAccountAnalysis.CurrentCellDirtyStateChanged += grid_CurrentCellDirtyStateChanged;
        gridAccountAnalysis_colAccountNumber = new DataGridViewTextBoxColumn();
        gridAccountAnalysis_colAccountNumber.Name = "colAccountNumber";
        gridAccountAnalysis_colAccountNumber.HeaderText = "رقم الحسابات";
        gridAccountAnalysis_colAccountNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridAccountAnalysis_colAccountNumber.ReadOnly = true;
        gridAccountAnalysis_colAccountName = new DataGridViewTextBoxColumn();
        gridAccountAnalysis_colAccountName.Name = "colAccountName";
        gridAccountAnalysis_colAccountName.HeaderText = "اسم الحسابات";
        gridAccountAnalysis_colAccountName.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridAccountAnalysis_colAccountName.ReadOnly = true;
        gridAccountAnalysis_colAnalysis = new DataGridViewComboBoxColumn();
        gridAccountAnalysis_colAnalysis.Name = "colAnalysis";
        gridAccountAnalysis_colAnalysis.HeaderText = "تحليل الحسابات";
        gridAccountAnalysis_colAnalysis.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridAccountAnalysis_colAnalysis.ReadOnly = true;
        gridAccountAnalysis_colAnalysis.DisplayStyle = DataGridViewComboBoxDisplayStyle.Nothing;
        gridAccountAnalysis_colAnalysis.ToolTipText = "القائمة غير مرتبطة ببيانات بعد.";
        gridAccountAnalysis_colFlowType = new DataGridViewTextBoxColumn();
        gridAccountAnalysis_colFlowType.Name = "colFlowType";
        gridAccountAnalysis_colFlowType.HeaderText = "نوع التدفق";
        gridAccountAnalysis_colFlowType.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridAccountAnalysis_colFlowType.ReadOnly = true;
        gridAccountAnalysis.Columns.AddRange(gridAccountAnalysis_colAccountNumber, gridAccountAnalysis_colAccountName, gridAccountAnalysis_colAnalysis, gridAccountAnalysis_colFlowType);
        tabgridAccountAnalysis = new TabPage();
        tabgridAccountAnalysis.Name = "tabgridAccountAnalysis";
        tabgridAccountAnalysis.Text = "ربط الحسابات بتحليل الحساب";
        tabgridAccountAnalysis.Controls.Add(gridAccountAnalysis);
        tabsSetup.TabPages.Add(tabgridAccountAnalysis);
        ((System.ComponentModel.ISupportInitialize)gridAccountAnalysis).EndInit();
        standardCommandEdit.Name = "btnEdit";
        standardCommandEdit.Enabled = true;
        standardCommandEdit.Click += draftAction_Click;
        standardCommandSave.Name = "btnSave";
        standardCommandSave.Enabled = false;
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        layout.Controls.Add(lblTitle, 0, 0);
        layout.Controls.Add(lblStatus, 0, 1);
        layout.Controls.Add(designerCommandBar, 0, 2);
        layout.Controls.Add(fields, 0, 3);
        Controls.Add(layout);


        Name = "UcCashFlowAccountLinks";
        Text = "ربط التدفقات النقدية مع تحليل الحسابات";
        Size = new Size(1000, 640);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        RightToLeft = RightToLeft.Yes;
        fields.ResumeLayout(true);
        layout.ResumeLayout(true);
        ResumeLayout(true);
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
    }
}
