namespace TransportERP.Desktop.Forms.SystemSettings.General;
partial class UcChartSetup
{
    private FlowLayoutPanel designerCommandFlow = null!;
    private Panel designerCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandView = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandSave = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandClose = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;
    private TableLayoutPanel referenceLayout = null!;
    private TabControl tabsSetup = null!;
    private TransportERP.Desktop.CoreUI.DesignerCommandBar commandBar = null!;
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;
    private Label lblTitle = null!;
    private Label lblStatus = null!;
    private TabPage tabgridAccountTypes = null!;
    private TableLayoutPanel canvasAccountTypes = null!;
    private TableLayoutPanel frameAccountTypes = null!;
    private DataGridView gridAccountTypes = null!;
    private DataGridViewTextBoxColumn colTypeNumber = null!;
    private DataGridViewTextBoxColumn colTypeNameLocal = null!;
    private DataGridViewTextBoxColumn colTypeNameForeign = null!;
    private DataGridViewCheckBoxColumn colAffectedByTransactions = null!;
    private TabPage tabgridAccountGroups = null!;
    private TableLayoutPanel canvasAccountGroups = null!;
    private TableLayoutPanel frameAccountGroups = null!;
    private DataGridView gridAccountGroups = null!;
    private DataGridViewTextBoxColumn colGroupNumber = null!;
    private ReferenceLookupTextColumn colGroupNameLocal = null!;
    private DataGridViewTextBoxColumn colGroupNameForeign = null!;
    private TabPage tabgridAccountClassifications = null!;
    private TableLayoutPanel canvasAccountClassifications = null!;
    private TableLayoutPanel frameAccountClassifications = null!;
    private DataGridView gridAccountClassifications = null!;
    private DataGridViewTextBoxColumn colClassificationNumber = null!;
    private ReferenceLookupTextColumn colClassificationNameLocal = null!;
    private DataGridViewTextBoxColumn colClassificationNameForeign = null!;
    private TabPage tabgridReportTypes = null!;
    private TableLayoutPanel canvasReportTypes = null!;
    private TableLayoutPanel frameReportTypes = null!;
    private DataGridView gridReportTypes = null!;
    private DataGridViewTextBoxColumn colReportTypeNumber = null!;
    private DataGridViewTextBoxColumn colReportTypeNameLocal = null!;
    private DataGridViewTextBoxColumn colReportTypeNameForeign = null!;
    private DataGridViewCheckBoxColumn colBalanceSheet = null!;
    private void InitializeComponent()
    {
        designerCommandFlow = new FlowLayoutPanel();
        designerCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandView = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandSave = new Button();
        standardCommandPrint = new Button();
        standardCommandClose = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        referenceLayout = new TableLayoutPanel();
        tabsSetup = new TabControl();
        commandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        lblTitle = new Label();
        lblStatus = new Label();
        tabgridAccountTypes = new TabPage();
        canvasAccountTypes = new TableLayoutPanel();
        frameAccountTypes = new TableLayoutPanel();
        gridAccountTypes = new DataGridView();
        colTypeNumber = new DataGridViewTextBoxColumn();
        colTypeNameLocal = new DataGridViewTextBoxColumn();
        colTypeNameForeign = new DataGridViewTextBoxColumn();
        colAffectedByTransactions = new DataGridViewCheckBoxColumn();
        tabgridAccountGroups = new TabPage();
        canvasAccountGroups = new TableLayoutPanel();
        frameAccountGroups = new TableLayoutPanel();
        gridAccountGroups = new DataGridView();
        colGroupNumber = new DataGridViewTextBoxColumn();
        colGroupNameLocal = new ReferenceLookupTextColumn();
        colGroupNameForeign = new DataGridViewTextBoxColumn();
        tabgridAccountClassifications = new TabPage();
        canvasAccountClassifications = new TableLayoutPanel();
        frameAccountClassifications = new TableLayoutPanel();
        gridAccountClassifications = new DataGridView();
        colClassificationNumber = new DataGridViewTextBoxColumn();
        colClassificationNameLocal = new ReferenceLookupTextColumn();
        colClassificationNameForeign = new DataGridViewTextBoxColumn();
        tabgridReportTypes = new TabPage();
        canvasReportTypes = new TableLayoutPanel();
        frameReportTypes = new TableLayoutPanel();
        gridReportTypes = new DataGridView();
        colReportTypeNumber = new DataGridViewTextBoxColumn();
        colReportTypeNameLocal = new DataGridViewTextBoxColumn();
        colReportTypeNameForeign = new DataGridViewTextBoxColumn();
        colBalanceSheet = new DataGridViewCheckBoxColumn();
        SuspendLayout();
        referenceLayout.Name = "layout";
        referenceLayout.Dock = DockStyle.Fill;
        referenceLayout.Margin = Padding.Empty;
        referenceLayout.ColumnCount = 1;
        referenceLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        referenceLayout.RowCount = 4;
        referenceLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        referenceLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        referenceLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        referenceLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        referenceLayout.Controls.Add(lblTitle, 0, 0);
        referenceLayout.Controls.Add(commandBar, 0, 1);
        referenceLayout.Controls.Add(tabsSetup, 0, 2);
        referenceLayout.Controls.Add(lblStatus, 0, 3);
        tabsSetup.Name = "tabsSetup";
        tabsSetup.Dock = DockStyle.Fill;
        tabsSetup.Margin = Padding.Empty;
        tabsSetup.RightToLeft = RightToLeft.Yes;
        tabsSetup.RightToLeftLayout = true;
        tabsSetup.Controls.Add(tabgridAccountTypes);
        tabgridAccountTypes.Name = "tabgridAccountTypes";
        tabgridAccountTypes.Text = "أنواع الحسابات";
        tabgridAccountTypes.BackColor = Color.FromArgb(244,244,244);
        tabgridAccountTypes.Controls.Add(canvasAccountTypes);
        canvasAccountTypes.Name = "canvasAccountTypes";
        canvasAccountTypes.Dock = DockStyle.Fill;
        canvasAccountTypes.RightToLeft = RightToLeft.No;
        canvasAccountTypes.Margin = Padding.Empty;
        canvasAccountTypes.ColumnCount = 3;
        canvasAccountTypes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 6F));
        canvasAccountTypes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 91F));
        canvasAccountTypes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 3F));
        canvasAccountTypes.RowCount = 3;
        canvasAccountTypes.RowStyles.Add(new RowStyle(SizeType.Percent, 18F));
        canvasAccountTypes.RowStyles.Add(new RowStyle(SizeType.Percent, 44F));
        canvasAccountTypes.RowStyles.Add(new RowStyle(SizeType.Percent, 38F));
        canvasAccountTypes.Controls.Add(frameAccountTypes, 1, 1);
        frameAccountTypes.Name = "frameAccountTypes";
        frameAccountTypes.Dock = DockStyle.Fill;
        frameAccountTypes.BorderStyle = BorderStyle.FixedSingle;
        frameAccountTypes.Margin = Padding.Empty;
        frameAccountTypes.ColumnCount = 3;
        frameAccountTypes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 10F));
        frameAccountTypes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 86F));
        frameAccountTypes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 4F));
        frameAccountTypes.RowCount = 3;
        frameAccountTypes.RowStyles.Add(new RowStyle(SizeType.Percent, 18F));
        frameAccountTypes.RowStyles.Add(new RowStyle(SizeType.Percent, 65F));
        frameAccountTypes.RowStyles.Add(new RowStyle(SizeType.Percent, 17F));
        frameAccountTypes.Controls.Add(gridAccountTypes, 1, 1);
        gridAccountTypes.Name = "gridAccountTypes";
        gridAccountTypes.AccessibleName = "أنواع الحسابات";
        gridAccountTypes.Dock = DockStyle.Fill;
        gridAccountTypes.Margin = Padding.Empty;
        gridAccountTypes.RightToLeft = RightToLeft.Yes;
        gridAccountTypes.Enabled = false;
        gridAccountTypes.AutoGenerateColumns = false;
        gridAccountTypes.AllowUserToAddRows = true;
        gridAccountTypes.AllowUserToDeleteRows = false;
        gridAccountTypes.RowHeadersVisible = false;
        gridAccountTypes.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        gridAccountTypes.BackgroundColor = Color.FromArgb(244,244,244);
        gridAccountTypes.BorderStyle = BorderStyle.None;
        gridAccountTypes.GridColor = Color.FromArgb(176,176,176);
        gridAccountTypes.EnableHeadersVisualStyles = false;
        gridAccountTypes.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(244,244,244);
        gridAccountTypes.ColumnHeadersDefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleCenter;
        gridAccountTypes.DefaultCellStyle.SelectionBackColor = Color.FromArgb(216,255,255);
        gridAccountTypes.DefaultCellStyle.SelectionForeColor = Color.Black;
        gridAccountTypes.ColumnHeadersHeight = 36;
        gridAccountTypes.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridAccountTypes.RowTemplate.Height = 22;
        gridAccountTypes.CurrentCellDirtyStateChanged += grid_CurrentCellDirtyStateChanged;
        gridAccountTypes.Paint += grid_EmptyRulingPaint;
        gridAccountTypes.Columns.AddRange(colTypeNumber, colTypeNameLocal, colTypeNameForeign, colAffectedByTransactions);
        colTypeNumber.Name = "colTypeNumber";
        colTypeNumber.HeaderText = "الرقم";
        colTypeNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colTypeNumber.FillWeight = 12F;
        colTypeNumber.DefaultCellStyle.BackColor = Color.FromArgb(255,255,225);
        colTypeNameLocal.Name = "colTypeNameLocal";
        colTypeNameLocal.HeaderText = "اسم النوع";
        colTypeNameLocal.SortMode = DataGridViewColumnSortMode.NotSortable;
        colTypeNameLocal.FillWeight = 40F;
        colTypeNameLocal.DefaultCellStyle.BackColor = Color.FromArgb(255,255,225);
        colTypeNameForeign.Name = "colTypeNameForeign";
        colTypeNameForeign.HeaderText = "الاسم الأجنبي";
        colTypeNameForeign.SortMode = DataGridViewColumnSortMode.NotSortable;
        colTypeNameForeign.FillWeight = 40F;
        colTypeNameForeign.DefaultCellStyle.BackColor = Color.White;
        colTypeNameForeign.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleLeft;
        colAffectedByTransactions.Name = "colAffectedByTransactions";
        colAffectedByTransactions.HeaderText = "يتأثر بالعمليات";
        colAffectedByTransactions.SortMode = DataGridViewColumnSortMode.NotSortable;
        colAffectedByTransactions.FillWeight = 14F;
        tabsSetup.Controls.Add(tabgridAccountGroups);
        tabgridAccountGroups.Name = "tabgridAccountGroups";
        tabgridAccountGroups.Text = "مجموعات الحسابات";
        tabgridAccountGroups.BackColor = Color.FromArgb(244,244,244);
        tabgridAccountGroups.Controls.Add(canvasAccountGroups);
        canvasAccountGroups.Name = "canvasAccountGroups";
        canvasAccountGroups.Dock = DockStyle.Fill;
        canvasAccountGroups.RightToLeft = RightToLeft.No;
        canvasAccountGroups.Margin = Padding.Empty;
        canvasAccountGroups.ColumnCount = 3;
        canvasAccountGroups.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 6F));
        canvasAccountGroups.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 91F));
        canvasAccountGroups.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 3F));
        canvasAccountGroups.RowCount = 3;
        canvasAccountGroups.RowStyles.Add(new RowStyle(SizeType.Percent, 18F));
        canvasAccountGroups.RowStyles.Add(new RowStyle(SizeType.Percent, 44F));
        canvasAccountGroups.RowStyles.Add(new RowStyle(SizeType.Percent, 38F));
        canvasAccountGroups.Controls.Add(frameAccountGroups, 1, 1);
        frameAccountGroups.Name = "frameAccountGroups";
        frameAccountGroups.Dock = DockStyle.Fill;
        frameAccountGroups.BorderStyle = BorderStyle.FixedSingle;
        frameAccountGroups.Margin = Padding.Empty;
        frameAccountGroups.ColumnCount = 3;
        frameAccountGroups.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 10F));
        frameAccountGroups.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 86F));
        frameAccountGroups.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 4F));
        frameAccountGroups.RowCount = 3;
        frameAccountGroups.RowStyles.Add(new RowStyle(SizeType.Percent, 18F));
        frameAccountGroups.RowStyles.Add(new RowStyle(SizeType.Percent, 65F));
        frameAccountGroups.RowStyles.Add(new RowStyle(SizeType.Percent, 17F));
        frameAccountGroups.Controls.Add(gridAccountGroups, 1, 1);
        gridAccountGroups.Name = "gridAccountGroups";
        gridAccountGroups.AccessibleName = "مجموعات الحسابات";
        gridAccountGroups.Dock = DockStyle.Fill;
        gridAccountGroups.Margin = Padding.Empty;
        gridAccountGroups.RightToLeft = RightToLeft.Yes;
        gridAccountGroups.Enabled = false;
        gridAccountGroups.AutoGenerateColumns = false;
        gridAccountGroups.AllowUserToAddRows = true;
        gridAccountGroups.AllowUserToDeleteRows = false;
        gridAccountGroups.RowHeadersVisible = false;
        gridAccountGroups.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        gridAccountGroups.BackgroundColor = Color.FromArgb(244,244,244);
        gridAccountGroups.BorderStyle = BorderStyle.None;
        gridAccountGroups.GridColor = Color.FromArgb(176,176,176);
        gridAccountGroups.EnableHeadersVisualStyles = false;
        gridAccountGroups.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(244,244,244);
        gridAccountGroups.ColumnHeadersDefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleCenter;
        gridAccountGroups.DefaultCellStyle.SelectionBackColor = Color.FromArgb(216,255,255);
        gridAccountGroups.DefaultCellStyle.SelectionForeColor = Color.Black;
        gridAccountGroups.ColumnHeadersHeight = 36;
        gridAccountGroups.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridAccountGroups.RowTemplate.Height = 22;
        gridAccountGroups.CurrentCellDirtyStateChanged += grid_CurrentCellDirtyStateChanged;
        gridAccountGroups.Paint += grid_EmptyRulingPaint;
        gridAccountGroups.Columns.AddRange(colGroupNumber, colGroupNameLocal, colGroupNameForeign);
        colGroupNumber.Name = "colGroupNumber";
        colGroupNumber.HeaderText = "الرقم";
        colGroupNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colGroupNumber.FillWeight = 12F;
        colGroupNumber.DefaultCellStyle.BackColor = Color.FromArgb(255,255,225);
        colGroupNameLocal.Name = "colGroupNameLocal";
        colGroupNameLocal.HeaderText = "اسم المجموعة";
        colGroupNameLocal.SortMode = DataGridViewColumnSortMode.NotSortable;
        colGroupNameLocal.FillWeight = 40F;
        colGroupNameLocal.DefaultCellStyle.BackColor = Color.FromArgb(255,255,225);
        colGroupNameForeign.Name = "colGroupNameForeign";
        colGroupNameForeign.HeaderText = "الاسم الأجنبي";
        colGroupNameForeign.SortMode = DataGridViewColumnSortMode.NotSortable;
        colGroupNameForeign.FillWeight = 40F;
        colGroupNameForeign.DefaultCellStyle.BackColor = Color.White;
        colGroupNameForeign.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleLeft;
        tabsSetup.Controls.Add(tabgridAccountClassifications);
        tabgridAccountClassifications.Name = "tabgridAccountClassifications";
        tabgridAccountClassifications.Text = "تصنيف الحسابات";
        tabgridAccountClassifications.BackColor = Color.FromArgb(244,244,244);
        tabgridAccountClassifications.Controls.Add(canvasAccountClassifications);
        canvasAccountClassifications.Name = "canvasAccountClassifications";
        canvasAccountClassifications.Dock = DockStyle.Fill;
        canvasAccountClassifications.RightToLeft = RightToLeft.No;
        canvasAccountClassifications.Margin = Padding.Empty;
        canvasAccountClassifications.ColumnCount = 3;
        canvasAccountClassifications.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 6F));
        canvasAccountClassifications.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 91F));
        canvasAccountClassifications.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 3F));
        canvasAccountClassifications.RowCount = 3;
        canvasAccountClassifications.RowStyles.Add(new RowStyle(SizeType.Percent, 18F));
        canvasAccountClassifications.RowStyles.Add(new RowStyle(SizeType.Percent, 44F));
        canvasAccountClassifications.RowStyles.Add(new RowStyle(SizeType.Percent, 38F));
        canvasAccountClassifications.Controls.Add(frameAccountClassifications, 1, 1);
        frameAccountClassifications.Name = "frameAccountClassifications";
        frameAccountClassifications.Dock = DockStyle.Fill;
        frameAccountClassifications.BorderStyle = BorderStyle.FixedSingle;
        frameAccountClassifications.Margin = Padding.Empty;
        frameAccountClassifications.ColumnCount = 3;
        frameAccountClassifications.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 10F));
        frameAccountClassifications.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 86F));
        frameAccountClassifications.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 4F));
        frameAccountClassifications.RowCount = 3;
        frameAccountClassifications.RowStyles.Add(new RowStyle(SizeType.Percent, 18F));
        frameAccountClassifications.RowStyles.Add(new RowStyle(SizeType.Percent, 65F));
        frameAccountClassifications.RowStyles.Add(new RowStyle(SizeType.Percent, 17F));
        frameAccountClassifications.Controls.Add(gridAccountClassifications, 1, 1);
        gridAccountClassifications.Name = "gridAccountClassifications";
        gridAccountClassifications.AccessibleName = "تصنيف الحسابات";
        gridAccountClassifications.Dock = DockStyle.Fill;
        gridAccountClassifications.Margin = Padding.Empty;
        gridAccountClassifications.RightToLeft = RightToLeft.Yes;
        gridAccountClassifications.Enabled = false;
        gridAccountClassifications.AutoGenerateColumns = false;
        gridAccountClassifications.AllowUserToAddRows = true;
        gridAccountClassifications.AllowUserToDeleteRows = false;
        gridAccountClassifications.RowHeadersVisible = false;
        gridAccountClassifications.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        gridAccountClassifications.BackgroundColor = Color.FromArgb(244,244,244);
        gridAccountClassifications.BorderStyle = BorderStyle.None;
        gridAccountClassifications.GridColor = Color.FromArgb(176,176,176);
        gridAccountClassifications.EnableHeadersVisualStyles = false;
        gridAccountClassifications.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(244,244,244);
        gridAccountClassifications.ColumnHeadersDefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleCenter;
        gridAccountClassifications.DefaultCellStyle.SelectionBackColor = Color.FromArgb(216,255,255);
        gridAccountClassifications.DefaultCellStyle.SelectionForeColor = Color.Black;
        gridAccountClassifications.ColumnHeadersHeight = 36;
        gridAccountClassifications.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridAccountClassifications.RowTemplate.Height = 22;
        gridAccountClassifications.CurrentCellDirtyStateChanged += grid_CurrentCellDirtyStateChanged;
        gridAccountClassifications.Paint += grid_EmptyRulingPaint;
        gridAccountClassifications.Columns.AddRange(colClassificationNumber, colClassificationNameLocal, colClassificationNameForeign);
        colClassificationNumber.Name = "colClassificationNumber";
        colClassificationNumber.HeaderText = "الرقم";
        colClassificationNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colClassificationNumber.FillWeight = 12F;
        colClassificationNumber.DefaultCellStyle.BackColor = Color.FromArgb(255,255,225);
        colClassificationNameLocal.Name = "colClassificationNameLocal";
        colClassificationNameLocal.HeaderText = "اسم التصنيف";
        colClassificationNameLocal.SortMode = DataGridViewColumnSortMode.NotSortable;
        colClassificationNameLocal.FillWeight = 40F;
        colClassificationNameLocal.DefaultCellStyle.BackColor = Color.FromArgb(255,255,225);
        colClassificationNameForeign.Name = "colClassificationNameForeign";
        colClassificationNameForeign.HeaderText = "الاسم الأجنبي";
        colClassificationNameForeign.SortMode = DataGridViewColumnSortMode.NotSortable;
        colClassificationNameForeign.FillWeight = 40F;
        colClassificationNameForeign.DefaultCellStyle.BackColor = Color.White;
        colClassificationNameForeign.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleLeft;
        tabsSetup.Controls.Add(tabgridReportTypes);
        tabgridReportTypes.Name = "tabgridReportTypes";
        tabgridReportTypes.Text = "أنواع تقارير الحسابات";
        tabgridReportTypes.BackColor = Color.FromArgb(244,244,244);
        tabgridReportTypes.Controls.Add(canvasReportTypes);
        canvasReportTypes.Name = "canvasReportTypes";
        canvasReportTypes.Dock = DockStyle.Fill;
        canvasReportTypes.RightToLeft = RightToLeft.No;
        canvasReportTypes.Margin = Padding.Empty;
        canvasReportTypes.ColumnCount = 3;
        canvasReportTypes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 6F));
        canvasReportTypes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 91F));
        canvasReportTypes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 3F));
        canvasReportTypes.RowCount = 3;
        canvasReportTypes.RowStyles.Add(new RowStyle(SizeType.Percent, 18F));
        canvasReportTypes.RowStyles.Add(new RowStyle(SizeType.Percent, 44F));
        canvasReportTypes.RowStyles.Add(new RowStyle(SizeType.Percent, 38F));
        canvasReportTypes.Controls.Add(frameReportTypes, 1, 1);
        frameReportTypes.Name = "frameReportTypes";
        frameReportTypes.Dock = DockStyle.Fill;
        frameReportTypes.BorderStyle = BorderStyle.FixedSingle;
        frameReportTypes.Margin = Padding.Empty;
        frameReportTypes.ColumnCount = 3;
        frameReportTypes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 10F));
        frameReportTypes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 86F));
        frameReportTypes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 4F));
        frameReportTypes.RowCount = 3;
        frameReportTypes.RowStyles.Add(new RowStyle(SizeType.Percent, 18F));
        frameReportTypes.RowStyles.Add(new RowStyle(SizeType.Percent, 65F));
        frameReportTypes.RowStyles.Add(new RowStyle(SizeType.Percent, 17F));
        frameReportTypes.Controls.Add(gridReportTypes, 1, 1);
        gridReportTypes.Name = "gridReportTypes";
        gridReportTypes.AccessibleName = "أنواع تقارير الحسابات";
        gridReportTypes.Dock = DockStyle.Fill;
        gridReportTypes.Margin = Padding.Empty;
        gridReportTypes.RightToLeft = RightToLeft.Yes;
        gridReportTypes.Enabled = false;
        gridReportTypes.AutoGenerateColumns = false;
        gridReportTypes.AllowUserToAddRows = true;
        gridReportTypes.AllowUserToDeleteRows = false;
        gridReportTypes.RowHeadersVisible = false;
        gridReportTypes.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        gridReportTypes.BackgroundColor = Color.FromArgb(244,244,244);
        gridReportTypes.BorderStyle = BorderStyle.None;
        gridReportTypes.GridColor = Color.FromArgb(176,176,176);
        gridReportTypes.EnableHeadersVisualStyles = false;
        gridReportTypes.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(244,244,244);
        gridReportTypes.ColumnHeadersDefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleCenter;
        gridReportTypes.DefaultCellStyle.SelectionBackColor = Color.FromArgb(216,255,255);
        gridReportTypes.DefaultCellStyle.SelectionForeColor = Color.Black;
        gridReportTypes.ColumnHeadersHeight = 36;
        gridReportTypes.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        gridReportTypes.RowTemplate.Height = 22;
        gridReportTypes.CurrentCellDirtyStateChanged += grid_CurrentCellDirtyStateChanged;
        gridReportTypes.Paint += grid_EmptyRulingPaint;
        gridReportTypes.Columns.AddRange(colReportTypeNumber, colReportTypeNameLocal, colReportTypeNameForeign, colBalanceSheet);
        colReportTypeNumber.Name = "colReportTypeNumber";
        colReportTypeNumber.HeaderText = "الرقم";
        colReportTypeNumber.SortMode = DataGridViewColumnSortMode.NotSortable;
        colReportTypeNumber.FillWeight = 12F;
        colReportTypeNumber.DefaultCellStyle.BackColor = Color.FromArgb(255,255,225);
        colReportTypeNameLocal.Name = "colReportTypeNameLocal";
        colReportTypeNameLocal.HeaderText = "اسم النوع";
        colReportTypeNameLocal.SortMode = DataGridViewColumnSortMode.NotSortable;
        colReportTypeNameLocal.FillWeight = 40F;
        colReportTypeNameLocal.DefaultCellStyle.BackColor = Color.FromArgb(255,255,225);
        colReportTypeNameForeign.Name = "colReportTypeNameForeign";
        colReportTypeNameForeign.HeaderText = "الاسم الأجنبي";
        colReportTypeNameForeign.SortMode = DataGridViewColumnSortMode.NotSortable;
        colReportTypeNameForeign.FillWeight = 40F;
        colReportTypeNameForeign.DefaultCellStyle.BackColor = Color.White;
        colReportTypeNameForeign.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleLeft;
        colBalanceSheet.Name = "colBalanceSheet";
        colBalanceSheet.HeaderText = "الميزانية العمومية";
        colBalanceSheet.SortMode = DataGridViewColumnSortMode.NotSortable;
        colBalanceSheet.FillWeight = 14F;
        gridAccountTypes.CellValueChanged += gridAccountTypes_CellValueChanged;
        commandBar.Name = "standardCommandBar";
        commandBar.Dock = DockStyle.Fill;
        commandBar.MinimumSize = new Size(0,30);
        commandBar.Size = new Size(1000,30);
        commandBar.Margin = Padding.Empty;
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "تهيئة النظام · التهيئة · تهيئة الدليل المحاسبي";
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.AutoSize = true;
        lblTitle.Margin = Padding.Empty;
        lblTitle.Padding = new Padding(3);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "GENS021 — الحفظ والبحث غير متاحين";
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.AutoSize = true;
        lblStatus.Margin = Padding.Empty;
        lblStatus.Padding = new Padding(3);
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Size = new Size(1000,64);
        standardAuditMetadata.Margin = Padding.Empty;
        AutoScaleDimensions = new SizeF(96F,96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        AutoScroll = true;
        Font = new Font("Tahoma",9F);
        BackColor = Color.FromArgb(244,244,244);
        ForeColor = Color.FromArgb(45,45,45);
        Name = "UcChartSetup";
        Text = "تهيئة الدليل المحاسبي";
        RightToLeft = RightToLeft.Yes;
        Dock = DockStyle.Fill;
        Margin = Padding.Empty;
        Padding = new Padding(2);
        Size = new Size(1000,680);
        Controls.Add(referenceLayout);
        Controls.Add(standardAuditMetadata);
        commandBar.Name = "commandBar";
        commandBar.BackColor = Color.FromArgb(239, 239, 239);
        commandBar.BorderStyle = BorderStyle.FixedSingle;
        commandBar.Controls.Add(designerCommandFlow);
        commandBar.Controls.Add(designerCloseHost);
        designerCloseHost.Dock = DockStyle.Left;
        designerCloseHost.Width = 28;
        designerCloseHost.Name = "designerCloseHost";
        designerCommandFlow.Name = "designerCommandFlow";
        designerCommandFlow.Dock = DockStyle.Fill;
        designerCommandFlow.AutoSize = false;
        designerCommandFlow.WrapContents = false;
        designerCommandFlow.FlowDirection = FlowDirection.RightToLeft;
        designerCommandFlow.RightToLeft = RightToLeft.No;
        designerCommandFlow.Padding = new Padding(2);
        commandBar.MinimumSize = new Size(0, 30);
        commandBar.Height = 30;
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = true;
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = true;
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandView.Name = "standardCommandView";
        standardCommandView.Enabled = false;
        standardCommandView.Visible = true;
        standardCommandView.AccessibleName = "عرض";
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.AccessibleName = "التالي";
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandSave.Name = "standardCommandSave";
        standardCommandSave.Enabled = false;
        standardCommandSave.Visible = true;
        standardCommandSave.AccessibleName = "حفظ";
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandClose.Name = "standardCommandClose";
        standardCommandClose.Enabled = false;
        standardCommandClose.Visible = true;
        standardCommandClose.AccessibleName = "إغلاق";
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandAdd.AutoSize = false;
        standardCommandAdd.Dock = DockStyle.None;
        standardCommandAdd.MinimumSize = Size.Empty;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandAdd.Text = "";
        designerCommandFlow.Controls.Add(standardCommandAdd);
        commandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.AutoSize = false;
        standardCommandEdit.Dock = DockStyle.None;
        standardCommandEdit.MinimumSize = Size.Empty;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandEdit.Text = "";
        designerCommandFlow.Controls.Add(standardCommandEdit);
        commandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.AutoSize = false;
        standardCommandDelete.Dock = DockStyle.None;
        standardCommandDelete.MinimumSize = Size.Empty;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandDelete.Text = "";
        designerCommandFlow.Controls.Add(standardCommandDelete);
        commandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.AutoSize = false;
        standardCommandCancel.Dock = DockStyle.None;
        standardCommandCancel.MinimumSize = Size.Empty;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandCancel.Text = "";
        designerCommandFlow.Controls.Add(standardCommandCancel);
        commandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        standardCommandView.AutoSize = false;
        standardCommandView.Dock = DockStyle.None;
        standardCommandView.MinimumSize = Size.Empty;
        standardCommandView.Size = new Size(26, 24);
        standardCommandView.Margin = new Padding(1);
        standardCommandView.FlatStyle = FlatStyle.Flat;
        standardCommandView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        standardCommandView.Text = "";
        designerCommandFlow.Controls.Add(standardCommandView);
        commandBar.SetCommandRole(standardCommandView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.AutoSize = false;
        standardCommandLast.Dock = DockStyle.None;
        standardCommandLast.MinimumSize = Size.Empty;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandLast.Text = "";
        designerCommandFlow.Controls.Add(standardCommandLast);
        commandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.AutoSize = false;
        standardCommandNext.Dock = DockStyle.None;
        standardCommandNext.MinimumSize = Size.Empty;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandNext.Text = "";
        designerCommandFlow.Controls.Add(standardCommandNext);
        commandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.AutoSize = false;
        standardCommandPrevious.Dock = DockStyle.None;
        standardCommandPrevious.MinimumSize = Size.Empty;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandPrevious.Text = "";
        designerCommandFlow.Controls.Add(standardCommandPrevious);
        commandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.AutoSize = false;
        standardCommandFirst.Dock = DockStyle.None;
        standardCommandFirst.MinimumSize = Size.Empty;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFirst.Text = "";
        designerCommandFlow.Controls.Add(standardCommandFirst);
        commandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        standardCommandSave.AutoSize = false;
        standardCommandSave.Dock = DockStyle.None;
        standardCommandSave.MinimumSize = Size.Empty;
        standardCommandSave.Size = new Size(26, 24);
        standardCommandSave.Margin = new Padding(1);
        standardCommandSave.FlatStyle = FlatStyle.Flat;
        standardCommandSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        standardCommandSave.Text = "";
        designerCommandFlow.Controls.Add(standardCommandSave);
        commandBar.SetCommandRole(standardCommandSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.AutoSize = false;
        standardCommandPrint.Dock = DockStyle.None;
        standardCommandPrint.MinimumSize = Size.Empty;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandPrint.Text = "";
        designerCommandFlow.Controls.Add(standardCommandPrint);
        commandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        standardCommandClose.AutoSize = false;
        standardCommandClose.Dock = DockStyle.None;
        standardCommandClose.MinimumSize = Size.Empty;
        standardCommandClose.Size = new Size(26, 24);
        standardCommandClose.Margin = new Padding(1);
        standardCommandClose.FlatStyle = FlatStyle.Flat;
        standardCommandClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        standardCommandClose.Text = "";
        designerCloseHost.Controls.Add(standardCommandClose);
        standardCommandClose.Location = new Point(1, 1);
        commandBar.SetCommandRole(standardCommandClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.AutoSize = false;
        standardCommandRefresh.Dock = DockStyle.None;
        standardCommandRefresh.MinimumSize = Size.Empty;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.Text = "تحديث";
        designerCommandFlow.Controls.Add(standardCommandRefresh);
        commandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.AutoSize = false;
        standardCommandImport.Dock = DockStyle.None;
        standardCommandImport.MinimumSize = Size.Empty;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.Text = "استيراد";
        designerCommandFlow.Controls.Add(standardCommandImport);
        commandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.AutoSize = false;
        standardCommandExport.Dock = DockStyle.None;
        standardCommandExport.MinimumSize = Size.Empty;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.Text = "تصدير";
        designerCommandFlow.Controls.Add(standardCommandExport);
        commandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.AutoSize = false;
        standardCommandHelp.Dock = DockStyle.None;
        standardCommandHelp.MinimumSize = Size.Empty;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.Text = "مساعدة";
        designerCommandFlow.Controls.Add(standardCommandHelp);
        commandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
        ResumeLayout(false);
    }
}
