namespace TransportERP.Desktop.Forms.SystemSettings.General;
partial class UcCompanyData
{
    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private FlowLayoutPanel standardCommandFlow = null!;
    private Panel standardCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandView = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandSave = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandClose = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel layout = null!;
    private TableLayoutPanel fields = null!;
    private Label lblTitle = null!;
    private Label lblStatus = null!;
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;
    private Label lblcboCountry = null!;
    private ComboBox cboCountry = null!;
    private Label lblchkMain = null!;
    private CheckBox chkMain = null!;
    private Label lbltxtCompanyNumber = null!;
    private TextBox txtCompanyNumber = null!;
    private Label lblcboMainCompany = null!;
    private ComboBox cboMainCompany = null!;
    private Label lbltxtNameLocal = null!;
    private TextBox txtNameLocal = null!;
    private Label lbltxtNameForeign = null!;
    private TextBox txtNameForeign = null!;
    private Label lbltxtShortLocal = null!;
    private TextBox txtShortLocal = null!;
    private Label lbltxtShortForeign = null!;
    private TextBox txtShortForeign = null!;
    private Label lblcboGroup = null!;
    private ComboBox cboGroup = null!;
    private Label lblchkTaxGroup = null!;
    private CheckBox chkTaxGroup = null!;
    private Label lbltxtTaxCurrency = null!;
    private TextBox txtTaxCurrency = null!;
    private Label lbltxtTaxRegistration = null!;
    private TextBox txtTaxRegistration = null!;
    private TabControl tabsFields = null!;
    private TabPage sectionPage0 = null!;
    private TableLayoutPanel sectionFields0 = null!;
    private TabPage sectionPage1 = null!;
    private TableLayoutPanel sectionFields1 = null!;
    private TabPage sectionPage2 = null!;
    private TableLayoutPanel sectionFields2 = null!;
    private GroupBox grpLogo = null!;
    private PictureBox picLogo = null!;
    private Button btnAddLogo = null!;
    private Panel logoFieldsHost = null!;
    private Label sectionNotice1 = null!;
    private Label sectionNotice2 = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        standardCommandFlow = new FlowLayoutPanel();
        standardCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandView = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandSave = new Button();
        standardCommandPrint = new Button();
        standardCommandClose = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.Size = new Size(1000, 44);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Margin = Padding.Empty;
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        standardCommandFlow.Name = "pnlToolbar";
        standardCommandFlow.Dock = DockStyle.Fill;
        standardCommandFlow.FlowDirection = FlowDirection.RightToLeft;
        standardCommandFlow.RightToLeft = RightToLeft.No;
        standardCommandFlow.WrapContents = false;
        standardCommandFlow.Padding = new Padding(2);
        standardCloseHost.Name = "standardCloseHost";
        standardCloseHost.Dock = DockStyle.Left;
        standardCloseHost.Width = 28;
        designerCommandBar.Controls.Add(standardCommandFlow);
        designerCommandBar.Controls.Add(standardCloseHost);
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = true;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.TabIndex = 0;
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandFlow.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = true;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.TabIndex = 1;
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandFlow.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.TabIndex = 2;
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandFlow.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.TabIndex = 3;
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandFlow.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        standardCommandView.Name = "standardCommandView";
        standardCommandView.AccessibleName = "عرض";
        standardCommandView.Enabled = false;
        standardCommandView.Visible = true;
        standardCommandView.Size = new Size(26, 24);
        standardCommandView.Margin = new Padding(1);
        standardCommandView.FlatStyle = FlatStyle.Flat;
        standardCommandView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandView.TabIndex = 4;
        standardCommandView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        standardCommandFlow.Controls.Add(standardCommandView);
        designerCommandBar.SetCommandRole(standardCommandView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.TabIndex = 5;
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandFlow.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.AccessibleName = "التالي";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.TabIndex = 6;
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandFlow.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.TabIndex = 7;
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandFlow.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.TabIndex = 8;
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFlow.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        standardCommandSave.Name = "btnSave";
        standardCommandSave.AccessibleName = "حفظ";
        standardCommandSave.Enabled = false;
        standardCommandSave.Visible = true;
        standardCommandSave.Size = new Size(26, 24);
        standardCommandSave.Margin = new Padding(1);
        standardCommandSave.FlatStyle = FlatStyle.Flat;
        standardCommandSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandSave.TabIndex = 9;
        standardCommandSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        standardCommandFlow.Controls.Add(standardCommandSave);
        designerCommandBar.SetCommandRole(standardCommandSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.TabIndex = 10;
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandFlow.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        standardCommandClose.Name = "standardCommandClose";
        standardCommandClose.AccessibleName = "إغلاق";
        standardCommandClose.Enabled = false;
        standardCommandClose.Visible = true;
        standardCommandClose.Size = new Size(26, 24);
        standardCommandClose.Margin = new Padding(1);
        standardCommandClose.FlatStyle = FlatStyle.Flat;
        standardCommandClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandClose.TabIndex = 11;
        standardCommandClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        standardCloseHost.Controls.Add(standardCommandClose);
        designerCommandBar.SetCommandRole(standardCommandClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.TabIndex = 12;
        standardCommandRefresh.Text = "تحديث";
        standardCommandFlow.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.TabIndex = 13;
        standardCommandImport.Text = "استيراد";
        standardCommandFlow.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.TabIndex = 14;
        standardCommandExport.Text = "تصدير";
        standardCommandFlow.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.TabIndex = 15;
        standardCommandHelp.Text = "مساعدة";
        standardCommandFlow.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
        standardCommandClose.Location = new Point(1, 1);
        standardCommandSave.AccessibleDescription = "الحفظ غير متاح؛ لم تُربط الشاشة بخدمة بيانات.";
        Controls.Add(designerCommandBar);

        layout = new TableLayoutPanel();
        fields = new TableLayoutPanel();
        lblTitle = new Label();
        lblStatus = new Label();
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        layout.SuspendLayout();
        fields.SuspendLayout();
        layout.Name = "layout";
        layout.Dock = DockStyle.Top;
        layout.AutoSize = true;
        layout.ColumnCount = 1;
        layout.RowCount = 4;
        layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "بيانات الشركات";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Font = new Font("Segoe UI", 16F);
        lblTitle.TextAlign = ContentAlignment.MiddleRight;
        lblTitle.BackColor = Color.FromArgb(192, 192, 255);
        lblTitle.Padding = new Padding(12);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "معاينة إدخال مؤقتة — الحفظ والترقيم التلقائي والقوائم غير متاحة؛ القيم لا تُطبّق على النظام.";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.TextAlign = ContentAlignment.MiddleRight;
        lblStatus.Padding = new Padding(8);
        fields.Name = "fields";
        fields.Dock = DockStyle.Top;
        fields.AutoSize = true;
        fields.ColumnCount = 2;
        fields.RowCount = 12;
        fields.Enabled = false;
        fields.TabIndex = 1;
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
        lblcboCountry = new Label();
        lblcboCountry.Name = "lblcboCountry";
        lblcboCountry.Text = "رقم الدولة";
        lblcboCountry.AutoSize = true;
        lblcboCountry.Dock = DockStyle.Fill;
        lblcboCountry.TextAlign = ContentAlignment.MiddleRight;
        lblcboCountry.Margin = new Padding(6, 8, 6, 8);
        cboCountry = new ComboBox();
        cboCountry.Name = "cboCountry";
        cboCountry.AccessibleName = "رقم الدولة";
        cboCountry.Dock = DockStyle.Fill;
        cboCountry.TabIndex = 0;
        cboCountry.Margin = new Padding(6, 8, 6, 8);
        cboCountry.DropDownStyle = ComboBoxStyle.DropDownList;
        cboCountry.Enabled = false;
        cboCountry.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboCountry, 0, 0);
        fields.Controls.Add(cboCountry, 1, 0);
        lblchkMain = new Label();
        lblchkMain.Name = "lblchkMain";
        lblchkMain.Text = "رئيسي";
        lblchkMain.AutoSize = true;
        lblchkMain.Dock = DockStyle.Fill;
        lblchkMain.TextAlign = ContentAlignment.MiddleRight;
        lblchkMain.Margin = new Padding(6, 8, 6, 8);
        chkMain = new CheckBox();
        chkMain.Name = "chkMain";
        chkMain.AccessibleName = "رئيسي";
        chkMain.Dock = DockStyle.Fill;
        chkMain.TabIndex = 1;
        chkMain.Margin = new Padding(6, 8, 6, 8);
        chkMain.AutoSize = true;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblchkMain, 0, 1);
        fields.Controls.Add(chkMain, 1, 1);
        lbltxtCompanyNumber = new Label();
        lbltxtCompanyNumber.Name = "lbltxtCompanyNumber";
        lbltxtCompanyNumber.Text = "رقم الشركة";
        lbltxtCompanyNumber.AutoSize = true;
        lbltxtCompanyNumber.Dock = DockStyle.Fill;
        lbltxtCompanyNumber.TextAlign = ContentAlignment.MiddleRight;
        lbltxtCompanyNumber.Margin = new Padding(6, 8, 6, 8);
        txtCompanyNumber = new TextBox();
        txtCompanyNumber.BackColor = Color.White;
        txtCompanyNumber.Name = "txtCompanyNumber";
        txtCompanyNumber.AccessibleName = "رقم الشركة";
        txtCompanyNumber.Dock = DockStyle.Fill;
        txtCompanyNumber.TabIndex = 2;
        txtCompanyNumber.Margin = new Padding(6, 8, 6, 8);
        txtCompanyNumber.ReadOnly = true;
        txtCompanyNumber.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtCompanyNumber, 0, 2);
        fields.Controls.Add(txtCompanyNumber, 1, 2);
        lblcboMainCompany = new Label();
        lblcboMainCompany.Name = "lblcboMainCompany";
        lblcboMainCompany.Text = "رقم الشركة الرئيسية";
        lblcboMainCompany.AutoSize = true;
        lblcboMainCompany.Dock = DockStyle.Fill;
        lblcboMainCompany.TextAlign = ContentAlignment.MiddleRight;
        lblcboMainCompany.Margin = new Padding(6, 8, 6, 8);
        cboMainCompany = new ComboBox();
        cboMainCompany.Name = "cboMainCompany";
        cboMainCompany.AccessibleName = "رقم الشركة الرئيسية";
        cboMainCompany.Dock = DockStyle.Fill;
        cboMainCompany.TabIndex = 3;
        cboMainCompany.Margin = new Padding(6, 8, 6, 8);
        cboMainCompany.DropDownStyle = ComboBoxStyle.DropDownList;
        cboMainCompany.Enabled = false;
        cboMainCompany.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboMainCompany, 0, 3);
        fields.Controls.Add(cboMainCompany, 1, 3);
        lbltxtNameLocal = new Label();
        lbltxtNameLocal.Name = "lbltxtNameLocal";
        lbltxtNameLocal.Text = "اسم الشركة (محلي)";
        lbltxtNameLocal.AutoSize = true;
        lbltxtNameLocal.Dock = DockStyle.Fill;
        lbltxtNameLocal.TextAlign = ContentAlignment.MiddleRight;
        lbltxtNameLocal.Margin = new Padding(6, 8, 6, 8);
        txtNameLocal = new TextBox();
        txtNameLocal.BackColor = Color.White;
        txtNameLocal.Name = "txtNameLocal";
        txtNameLocal.AccessibleName = "اسم الشركة (محلي)";
        txtNameLocal.Dock = DockStyle.Fill;
        txtNameLocal.TabIndex = 4;
        txtNameLocal.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtNameLocal, 0, 4);
        fields.Controls.Add(txtNameLocal, 1, 4);
        lbltxtNameForeign = new Label();
        lbltxtNameForeign.Name = "lbltxtNameForeign";
        lbltxtNameForeign.Text = "اسم الشركة (أجنبي)";
        lbltxtNameForeign.AutoSize = true;
        lbltxtNameForeign.Dock = DockStyle.Fill;
        lbltxtNameForeign.TextAlign = ContentAlignment.MiddleRight;
        lbltxtNameForeign.Margin = new Padding(6, 8, 6, 8);
        txtNameForeign = new TextBox();
        txtNameForeign.BackColor = Color.White;
        txtNameForeign.Name = "txtNameForeign";
        txtNameForeign.AccessibleName = "اسم الشركة (أجنبي)";
        txtNameForeign.Dock = DockStyle.Fill;
        txtNameForeign.TabIndex = 5;
        txtNameForeign.Margin = new Padding(6, 8, 6, 8);
        txtNameForeign.RightToLeft = RightToLeft.No;
        txtNameForeign.TextAlign = HorizontalAlignment.Left;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtNameForeign, 0, 5);
        fields.Controls.Add(txtNameForeign, 1, 5);
        lbltxtShortLocal = new Label();
        lbltxtShortLocal.Name = "lbltxtShortLocal";
        lbltxtShortLocal.Text = "الاسم المختصر (محلي)";
        lbltxtShortLocal.AutoSize = true;
        lbltxtShortLocal.Dock = DockStyle.Fill;
        lbltxtShortLocal.TextAlign = ContentAlignment.MiddleRight;
        lbltxtShortLocal.Margin = new Padding(6, 8, 6, 8);
        txtShortLocal = new TextBox();
        txtShortLocal.BackColor = Color.White;
        txtShortLocal.Name = "txtShortLocal";
        txtShortLocal.AccessibleName = "الاسم المختصر (محلي)";
        txtShortLocal.Dock = DockStyle.Fill;
        txtShortLocal.TabIndex = 6;
        txtShortLocal.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtShortLocal, 0, 6);
        fields.Controls.Add(txtShortLocal, 1, 6);
        lbltxtShortForeign = new Label();
        lbltxtShortForeign.Name = "lbltxtShortForeign";
        lbltxtShortForeign.Text = "الاسم المختصر (أجنبي)";
        lbltxtShortForeign.AutoSize = true;
        lbltxtShortForeign.Dock = DockStyle.Fill;
        lbltxtShortForeign.TextAlign = ContentAlignment.MiddleRight;
        lbltxtShortForeign.Margin = new Padding(6, 8, 6, 8);
        txtShortForeign = new TextBox();
        txtShortForeign.BackColor = Color.White;
        txtShortForeign.Name = "txtShortForeign";
        txtShortForeign.AccessibleName = "الاسم المختصر (أجنبي)";
        txtShortForeign.Dock = DockStyle.Fill;
        txtShortForeign.TabIndex = 7;
        txtShortForeign.Margin = new Padding(6, 8, 6, 8);
        txtShortForeign.RightToLeft = RightToLeft.No;
        txtShortForeign.TextAlign = HorizontalAlignment.Left;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtShortForeign, 0, 7);
        fields.Controls.Add(txtShortForeign, 1, 7);
        lblcboGroup = new Label();
        lblcboGroup.Name = "lblcboGroup";
        lblcboGroup.Text = "رقم المجموعة";
        lblcboGroup.AutoSize = true;
        lblcboGroup.Dock = DockStyle.Fill;
        lblcboGroup.TextAlign = ContentAlignment.MiddleRight;
        lblcboGroup.Margin = new Padding(6, 8, 6, 8);
        cboGroup = new ComboBox();
        cboGroup.Name = "cboGroup";
        cboGroup.AccessibleName = "رقم المجموعة";
        cboGroup.Dock = DockStyle.Fill;
        cboGroup.TabIndex = 8;
        cboGroup.Margin = new Padding(6, 8, 6, 8);
        cboGroup.DropDownStyle = ComboBoxStyle.DropDownList;
        cboGroup.Enabled = false;
        cboGroup.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboGroup, 0, 8);
        fields.Controls.Add(cboGroup, 1, 8);
        lblchkTaxGroup = new Label();
        lblchkTaxGroup.Name = "lblchkTaxGroup";
        lblchkTaxGroup.Text = "مجموعة ضريبية";
        lblchkTaxGroup.AutoSize = true;
        lblchkTaxGroup.Dock = DockStyle.Fill;
        lblchkTaxGroup.TextAlign = ContentAlignment.MiddleRight;
        lblchkTaxGroup.Margin = new Padding(6, 8, 6, 8);
        chkTaxGroup = new CheckBox();
        chkTaxGroup.Name = "chkTaxGroup";
        chkTaxGroup.AccessibleName = "مجموعة ضريبية";
        chkTaxGroup.Dock = DockStyle.Fill;
        chkTaxGroup.TabIndex = 9;
        chkTaxGroup.Margin = new Padding(6, 8, 6, 8);
        chkTaxGroup.AutoSize = true;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblchkTaxGroup, 0, 9);
        fields.Controls.Add(chkTaxGroup, 1, 9);
        lbltxtTaxCurrency = new Label();
        lbltxtTaxCurrency.Name = "lbltxtTaxCurrency";
        lbltxtTaxCurrency.Text = "عملة الضريبة";
        lbltxtTaxCurrency.AutoSize = true;
        lbltxtTaxCurrency.Dock = DockStyle.Fill;
        lbltxtTaxCurrency.TextAlign = ContentAlignment.MiddleRight;
        lbltxtTaxCurrency.Margin = new Padding(6, 8, 6, 8);
        txtTaxCurrency = new TextBox();
        txtTaxCurrency.BackColor = Color.White;
        txtTaxCurrency.Name = "txtTaxCurrency";
        txtTaxCurrency.AccessibleName = "عملة الضريبة";
        txtTaxCurrency.Dock = DockStyle.Fill;
        txtTaxCurrency.TabIndex = 10;
        txtTaxCurrency.Margin = new Padding(6, 8, 6, 8);
        txtTaxCurrency.ReadOnly = true;
        txtTaxCurrency.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtTaxCurrency, 0, 10);
        fields.Controls.Add(txtTaxCurrency, 1, 10);
        lbltxtTaxRegistration = new Label();
        lbltxtTaxRegistration.Name = "lbltxtTaxRegistration";
        lbltxtTaxRegistration.Text = "رقم التسجيل الضريبي";
        lbltxtTaxRegistration.AutoSize = true;
        lbltxtTaxRegistration.Dock = DockStyle.Fill;
        lbltxtTaxRegistration.TextAlign = ContentAlignment.MiddleRight;
        lbltxtTaxRegistration.Margin = new Padding(6, 8, 6, 8);
        txtTaxRegistration = new TextBox();
        txtTaxRegistration.BackColor = Color.White;
        txtTaxRegistration.Name = "txtTaxRegistration";
        txtTaxRegistration.AccessibleName = "رقم التسجيل الضريبي";
        txtTaxRegistration.Dock = DockStyle.Fill;
        txtTaxRegistration.TabIndex = 11;
        txtTaxRegistration.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtTaxRegistration, 0, 11);
        fields.Controls.Add(txtTaxRegistration, 1, 11);
        standardCommandAdd.Name = "btnAdd";
        standardCommandAdd.Enabled = true;
        standardCommandAdd.Click += draftAction_Click;
        standardCommandSave.Name = "btnSave";
        standardCommandSave.Enabled = false;
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        layout.Controls.Add(lblTitle, 0, 0);
        layout.Controls.Add(lblStatus, 0, 1);
        layout.Controls.Add(designerCommandBar, 0, 2);
        layout.Controls.Add(fields, 0, 3);
        Controls.Add(layout);


        Name = "UcCompanyData";
        Text = "بيانات الشركات";
        Size = new Size(1000, 640);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        RightToLeft = RightToLeft.Yes;
        fields.ResumeLayout(true);
        layout.ResumeLayout(true);
        ResumeLayout(true);
        tabsFields = new TabControl();
        tabsFields.Name = "tabsFields";
        tabsFields.Dock = DockStyle.Fill;
        tabsFields.MinimumSize = new Size(0, 520);
        tabsFields.Height = 520;
        tabsFields.RightToLeftLayout = true;
        sectionPage0 = new TabPage();
        sectionFields0 = new TableLayoutPanel();
        sectionPage0.Text = "البيانات الرئيسية";
        sectionPage0.AutoScroll = true;
        sectionFields0.Dock = DockStyle.Top;
        sectionFields0.AutoSize = true;
        sectionFields0.ColumnCount = 2;
        sectionFields0.RowCount = 12;
        sectionFields0.Enabled = false;
        sectionFields0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        sectionFields0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lblcboCountry, 0, 6);
        sectionFields0.Controls.Add(cboCountry, 1, 6);
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lblchkMain, 0, 7);
        sectionFields0.Controls.Add(chkMain, 1, 7);
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lbltxtCompanyNumber, 0, 0);
        sectionFields0.Controls.Add(txtCompanyNumber, 1, 0);
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lblcboMainCompany, 0, 8);
        sectionFields0.Controls.Add(cboMainCompany, 1, 8);
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lbltxtNameLocal, 0, 1);
        sectionFields0.Controls.Add(txtNameLocal, 1, 1);
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lbltxtNameForeign, 0, 2);
        sectionFields0.Controls.Add(txtNameForeign, 1, 2);
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lbltxtShortLocal, 0, 3);
        sectionFields0.Controls.Add(txtShortLocal, 1, 3);
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lbltxtShortForeign, 0, 4);
        sectionFields0.Controls.Add(txtShortForeign, 1, 4);
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lblcboGroup, 0, 5);
        sectionFields0.Controls.Add(cboGroup, 1, 5);
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lblchkTaxGroup, 0, 9);
        sectionFields0.Controls.Add(chkTaxGroup, 1, 9);
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lbltxtTaxCurrency, 0, 10);
        sectionFields0.Controls.Add(txtTaxCurrency, 1, 10);
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lbltxtTaxRegistration, 0, 11);
        sectionFields0.Controls.Add(txtTaxRegistration, 1, 11);
        sectionPage0.Controls.Add(sectionFields0);
        tabsFields.TabPages.Add(sectionPage0);
        sectionPage1 = new TabPage();
        sectionFields1 = new TableLayoutPanel();
        sectionPage1.Text = "الربط مع";
        sectionPage1.AutoScroll = true;
        sectionFields1.Dock = DockStyle.Top;
        sectionFields1.AutoSize = true;
        sectionFields1.ColumnCount = 2;
        sectionFields1.RowCount = 0;
        sectionFields1.Enabled = false;
        sectionFields1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        sectionFields1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
        sectionPage1.Controls.Add(sectionFields1);
        tabsFields.TabPages.Add(sectionPage1);
        sectionPage2 = new TabPage();
        sectionFields2 = new TableLayoutPanel();
        sectionPage2.Text = "إعدادات الفاتورة الإلكترونية";
        sectionPage2.AutoScroll = true;
        sectionFields2.Dock = DockStyle.Top;
        sectionFields2.AutoSize = true;
        sectionFields2.ColumnCount = 2;
        sectionFields2.RowCount = 0;
        sectionFields2.Enabled = false;
        sectionFields2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        sectionFields2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
        sectionPage2.Controls.Add(sectionFields2);
        tabsFields.TabPages.Add(sectionPage2);
        fields.Visible = false;
        layout.RowCount = 5;
        layout.Controls.Add(tabsFields, 0, 4);
        grpLogo = new GroupBox();
        picLogo = new PictureBox();
        btnAddLogo = new Button();
        logoFieldsHost = new Panel();
        grpLogo.Name = "grpLogo";
        grpLogo.Text = "شعار الشركة";
        grpLogo.Dock = DockStyle.Left;
        grpLogo.Width = 190;
        grpLogo.Padding = new Padding(10, 28, 10, 10);
        picLogo.Name = "picLogo";
        picLogo.Dock = DockStyle.Top;
        picLogo.Height = 150;
        picLogo.BorderStyle = BorderStyle.FixedSingle;
        picLogo.SizeMode = PictureBoxSizeMode.Zoom;
        picLogo.AccessibleName = "شعار الشركة";
        btnAddLogo.Name = "btnAddLogo";
        btnAddLogo.Text = "إضافة";
        btnAddLogo.Dock = DockStyle.Bottom;
        btnAddLogo.Height = 35;
        btnAddLogo.Enabled = false;
        btnAddLogo.AccessibleDescription = "استيراد الشعار غير مرتبط.";
        grpLogo.Controls.Add(picLogo);
        grpLogo.Controls.Add(btnAddLogo);
        logoFieldsHost.Dock = DockStyle.Fill;
        logoFieldsHost.AutoScroll = true;
        logoFieldsHost.Controls.Add(sectionFields0);
        sectionPage0.Controls.Add(logoFieldsHost);
        sectionPage0.Controls.Add(grpLogo);
        sectionNotice1 = new Label();
        sectionNotice1.Text = "تفاصيل حقول هذا التبويب غير موضحة في النص المتاح.";
        sectionNotice1.AutoSize = true;
        sectionNotice1.Dock = DockStyle.Top;
        sectionNotice1.Padding = new Padding(12);
        sectionNotice1.MaximumSize = new Size(700, 0);
        sectionPage1.Controls.Add(sectionNotice1);
        sectionNotice2 = new Label();
        sectionNotice2.Text = "إعدادات الفاتورة الإلكترونية غير مرتبطة؛ تفاصيل حقولها غير موضحة في النص المتاح.";
        sectionNotice2.AutoSize = true;
        sectionNotice2.Dock = DockStyle.Top;
        sectionNotice2.Padding = new Padding(12);
        sectionNotice2.MaximumSize = new Size(700, 0);
        sectionPage2.Controls.Add(sectionNotice2);

        standardCommandAdd.Visible = true;
        standardCommandEdit.Visible = true;
        standardCommandDelete.Visible = true;
        standardCommandCancel.Visible = true;
        standardCommandView.Visible = true;
        standardCommandLast.Visible = true;
        standardCommandNext.Visible = true;
        standardCommandPrevious.Visible = true;
        standardCommandFirst.Visible = true;
        standardCommandSave.Visible = true;
        standardCommandPrint.Visible = true;
        standardCommandClose.Visible = true;
        standardCommandRefresh.Visible = false;
        standardCommandImport.Visible = false;
        standardCommandExport.Visible = false;
        standardCommandHelp.Visible = false;
    

        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
    }
}
