namespace TransportERP.Desktop.Forms.SystemSettings.General;
partial class UcCountryData
{
    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private FlowLayoutPanel standardCommandFlow = null!;
    private Panel standardCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandView = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandSave = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandClose = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel layout = null!;
    private TableLayoutPanel fields = null!;
    private Label lblTitle = null!;
    private Label lblStatus = null!;
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;
    private Label lblcboCountryNumber = null!;
    private ComboBox cboCountryNumber = null!;
    private Label lbltxtCountryNameLocal = null!;
    private TextBox txtCountryNameLocal = null!;
    private Label lbltxtCountryNameForeign = null!;
    private TextBox txtCountryNameForeign = null!;
    private Label lblcboCountryShortName = null!;
    private ComboBox cboCountryShortName = null!;
    private Label lbltxtLocalCurrency = null!;
    private TextBox txtLocalCurrency = null!;
    private Label lbltxtContinent = null!;
    private TextBox txtContinent = null!;
    private Label lbltxtForeignShortName = null!;
    private TextBox txtForeignShortName = null!;
    private Label lbltxtDialingCode = null!;
    private TextBox txtDialingCode = null!;
    private Label lbltxtLanguage = null!;
    private TextBox txtLanguage = null!;
    private Label lbltxtCountryCode = null!;
    private TextBox txtCountryCode = null!;
    private Label lbltxtNationality = null!;
    private TextBox txtNationality = null!;
    private Label lblcboRegionNumber = null!;
    private ComboBox cboRegionNumber = null!;
    private Label lblchkBlockTransactions = null!;
    private CheckBox chkBlockTransactions = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        standardCommandFlow = new FlowLayoutPanel();
        standardCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandView = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandSave = new Button();
        standardCommandPrint = new Button();
        standardCommandClose = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.Size = new Size(1000, 44);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Margin = Padding.Empty;
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        standardCommandFlow.Name = "pnlToolbar";
        standardCommandFlow.Dock = DockStyle.Fill;
        standardCommandFlow.FlowDirection = FlowDirection.RightToLeft;
        standardCommandFlow.RightToLeft = RightToLeft.No;
        standardCommandFlow.WrapContents = false;
        standardCommandFlow.Padding = new Padding(2);
        standardCloseHost.Name = "standardCloseHost";
        standardCloseHost.Dock = DockStyle.Left;
        standardCloseHost.Width = 28;
        designerCommandBar.Controls.Add(standardCommandFlow);
        designerCommandBar.Controls.Add(standardCloseHost);
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = true;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.TabIndex = 0;
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandFlow.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = true;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.TabIndex = 1;
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandFlow.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.TabIndex = 2;
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandFlow.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.TabIndex = 3;
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandFlow.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        standardCommandView.Name = "standardCommandView";
        standardCommandView.AccessibleName = "عرض";
        standardCommandView.Enabled = false;
        standardCommandView.Visible = true;
        standardCommandView.Size = new Size(26, 24);
        standardCommandView.Margin = new Padding(1);
        standardCommandView.FlatStyle = FlatStyle.Flat;
        standardCommandView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandView.TabIndex = 4;
        standardCommandView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        standardCommandFlow.Controls.Add(standardCommandView);
        designerCommandBar.SetCommandRole(standardCommandView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.TabIndex = 5;
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandFlow.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.AccessibleName = "التالي";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.TabIndex = 6;
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandFlow.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.TabIndex = 7;
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandFlow.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.TabIndex = 8;
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFlow.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        standardCommandSave.Name = "btnSave";
        standardCommandSave.AccessibleName = "حفظ";
        standardCommandSave.Enabled = false;
        standardCommandSave.Visible = true;
        standardCommandSave.Size = new Size(26, 24);
        standardCommandSave.Margin = new Padding(1);
        standardCommandSave.FlatStyle = FlatStyle.Flat;
        standardCommandSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandSave.TabIndex = 9;
        standardCommandSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        standardCommandFlow.Controls.Add(standardCommandSave);
        designerCommandBar.SetCommandRole(standardCommandSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.TabIndex = 10;
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandFlow.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        standardCommandClose.Name = "standardCommandClose";
        standardCommandClose.AccessibleName = "إغلاق";
        standardCommandClose.Enabled = false;
        standardCommandClose.Visible = true;
        standardCommandClose.Size = new Size(26, 24);
        standardCommandClose.Margin = new Padding(1);
        standardCommandClose.FlatStyle = FlatStyle.Flat;
        standardCommandClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandClose.TabIndex = 11;
        standardCommandClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        standardCloseHost.Controls.Add(standardCommandClose);
        designerCommandBar.SetCommandRole(standardCommandClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.TabIndex = 12;
        standardCommandRefresh.Text = "تحديث";
        standardCommandFlow.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.TabIndex = 13;
        standardCommandImport.Text = "استيراد";
        standardCommandFlow.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.TabIndex = 14;
        standardCommandExport.Text = "تصدير";
        standardCommandFlow.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.TabIndex = 15;
        standardCommandHelp.Text = "مساعدة";
        standardCommandFlow.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
        standardCommandClose.Location = new Point(1, 1);
        standardCommandSave.AccessibleDescription = "الحفظ غير متاح؛ لم تُربط الشاشة بخدمة بيانات.";
        Controls.Add(designerCommandBar);

        layout = new TableLayoutPanel();
        fields = new TableLayoutPanel();
        lblTitle = new Label();
        lblStatus = new Label();
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        layout.SuspendLayout();
        fields.SuspendLayout();
        layout.Name = "layout";
        layout.Dock = DockStyle.Top;
        layout.AutoSize = true;
        layout.ColumnCount = 1;
        layout.RowCount = 4;
        layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "بيانات الدول";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Font = new Font("Segoe UI", 16F);
        lblTitle.TextAlign = ContentAlignment.MiddleRight;
        lblTitle.BackColor = Color.FromArgb(192, 192, 255);
        lblTitle.Padding = new Padding(12);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "معاينة إدخال مؤقتة — الحفظ والترقيم التلقائي والقوائم غير متاحة؛ القيم لا تُطبّق على النظام.";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.TextAlign = ContentAlignment.MiddleRight;
        lblStatus.Padding = new Padding(8);
        fields.Name = "fields";
        fields.Dock = DockStyle.Top;
        fields.AutoSize = true;
        fields.ColumnCount = 2;
        fields.RowCount = 13;
        fields.Enabled = false;
        fields.TabIndex = 1;
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
        lblcboCountryNumber = new Label();
        lblcboCountryNumber.Name = "lblcboCountryNumber";
        lblcboCountryNumber.Text = "رقم الدولة";
        lblcboCountryNumber.AutoSize = true;
        lblcboCountryNumber.Dock = DockStyle.Fill;
        lblcboCountryNumber.TextAlign = ContentAlignment.MiddleRight;
        lblcboCountryNumber.Margin = new Padding(6, 8, 6, 8);
        cboCountryNumber = new ComboBox();
        cboCountryNumber.Name = "cboCountryNumber";
        cboCountryNumber.AccessibleName = "رقم الدولة";
        cboCountryNumber.Dock = DockStyle.Fill;
        cboCountryNumber.TabIndex = 0;
        cboCountryNumber.Margin = new Padding(6, 8, 6, 8);
        cboCountryNumber.DropDownStyle = ComboBoxStyle.DropDownList;
        cboCountryNumber.Enabled = false;
        cboCountryNumber.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboCountryNumber, 0, 0);
        fields.Controls.Add(cboCountryNumber, 1, 0);
        lbltxtCountryNameLocal = new Label();
        lbltxtCountryNameLocal.Name = "lbltxtCountryNameLocal";
        lbltxtCountryNameLocal.Text = "اسم الدولة (محلي)";
        lbltxtCountryNameLocal.AutoSize = true;
        lbltxtCountryNameLocal.Dock = DockStyle.Fill;
        lbltxtCountryNameLocal.TextAlign = ContentAlignment.MiddleRight;
        lbltxtCountryNameLocal.Margin = new Padding(6, 8, 6, 8);
        txtCountryNameLocal = new TextBox();
        txtCountryNameLocal.BackColor = Color.White;
        txtCountryNameLocal.Name = "txtCountryNameLocal";
        txtCountryNameLocal.AccessibleName = "اسم الدولة (محلي)";
        txtCountryNameLocal.Dock = DockStyle.Fill;
        txtCountryNameLocal.TabIndex = 1;
        txtCountryNameLocal.Margin = new Padding(6, 8, 6, 8);
        txtCountryNameLocal.ReadOnly = true;
        txtCountryNameLocal.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtCountryNameLocal, 0, 1);
        fields.Controls.Add(txtCountryNameLocal, 1, 1);
        lbltxtCountryNameForeign = new Label();
        lbltxtCountryNameForeign.Name = "lbltxtCountryNameForeign";
        lbltxtCountryNameForeign.Text = "اسم الدولة (أجنبي)";
        lbltxtCountryNameForeign.AutoSize = true;
        lbltxtCountryNameForeign.Dock = DockStyle.Fill;
        lbltxtCountryNameForeign.TextAlign = ContentAlignment.MiddleRight;
        lbltxtCountryNameForeign.Margin = new Padding(6, 8, 6, 8);
        txtCountryNameForeign = new TextBox();
        txtCountryNameForeign.BackColor = Color.White;
        txtCountryNameForeign.Name = "txtCountryNameForeign";
        txtCountryNameForeign.AccessibleName = "اسم الدولة (أجنبي)";
        txtCountryNameForeign.Dock = DockStyle.Fill;
        txtCountryNameForeign.TabIndex = 2;
        txtCountryNameForeign.Margin = new Padding(6, 8, 6, 8);
        txtCountryNameForeign.ReadOnly = true;
        txtCountryNameForeign.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtCountryNameForeign, 0, 2);
        fields.Controls.Add(txtCountryNameForeign, 1, 2);
        lblcboCountryShortName = new Label();
        lblcboCountryShortName.Name = "lblcboCountryShortName";
        lblcboCountryShortName.Text = "مختصر اسم الدولة";
        lblcboCountryShortName.AutoSize = true;
        lblcboCountryShortName.Dock = DockStyle.Fill;
        lblcboCountryShortName.TextAlign = ContentAlignment.MiddleRight;
        lblcboCountryShortName.Margin = new Padding(6, 8, 6, 8);
        cboCountryShortName = new ComboBox();
        cboCountryShortName.Name = "cboCountryShortName";
        cboCountryShortName.AccessibleName = "مختصر اسم الدولة";
        cboCountryShortName.Dock = DockStyle.Fill;
        cboCountryShortName.TabIndex = 3;
        cboCountryShortName.Margin = new Padding(6, 8, 6, 8);
        cboCountryShortName.DropDownStyle = ComboBoxStyle.DropDownList;
        cboCountryShortName.Enabled = false;
        cboCountryShortName.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboCountryShortName, 0, 3);
        fields.Controls.Add(cboCountryShortName, 1, 3);
        lbltxtLocalCurrency = new Label();
        lbltxtLocalCurrency.Name = "lbltxtLocalCurrency";
        lbltxtLocalCurrency.Text = "العملة المحلية";
        lbltxtLocalCurrency.AutoSize = true;
        lbltxtLocalCurrency.Dock = DockStyle.Fill;
        lbltxtLocalCurrency.TextAlign = ContentAlignment.MiddleRight;
        lbltxtLocalCurrency.Margin = new Padding(6, 8, 6, 8);
        txtLocalCurrency = new TextBox();
        txtLocalCurrency.BackColor = Color.White;
        txtLocalCurrency.Name = "txtLocalCurrency";
        txtLocalCurrency.AccessibleName = "العملة المحلية";
        txtLocalCurrency.Dock = DockStyle.Fill;
        txtLocalCurrency.TabIndex = 4;
        txtLocalCurrency.Margin = new Padding(6, 8, 6, 8);
        txtLocalCurrency.ReadOnly = true;
        txtLocalCurrency.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtLocalCurrency, 0, 4);
        fields.Controls.Add(txtLocalCurrency, 1, 4);
        lbltxtContinent = new Label();
        lbltxtContinent.Name = "lbltxtContinent";
        lbltxtContinent.Text = "القارة";
        lbltxtContinent.AutoSize = true;
        lbltxtContinent.Dock = DockStyle.Fill;
        lbltxtContinent.TextAlign = ContentAlignment.MiddleRight;
        lbltxtContinent.Margin = new Padding(6, 8, 6, 8);
        txtContinent = new TextBox();
        txtContinent.BackColor = Color.White;
        txtContinent.Name = "txtContinent";
        txtContinent.AccessibleName = "القارة";
        txtContinent.Dock = DockStyle.Fill;
        txtContinent.TabIndex = 5;
        txtContinent.Margin = new Padding(6, 8, 6, 8);
        txtContinent.ReadOnly = true;
        txtContinent.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtContinent, 0, 5);
        fields.Controls.Add(txtContinent, 1, 5);
        lbltxtForeignShortName = new Label();
        lbltxtForeignShortName.Name = "lbltxtForeignShortName";
        lbltxtForeignShortName.Text = "الاسم المختصر أجنبي";
        lbltxtForeignShortName.AutoSize = true;
        lbltxtForeignShortName.Dock = DockStyle.Fill;
        lbltxtForeignShortName.TextAlign = ContentAlignment.MiddleRight;
        lbltxtForeignShortName.Margin = new Padding(6, 8, 6, 8);
        txtForeignShortName = new TextBox();
        txtForeignShortName.BackColor = Color.White;
        txtForeignShortName.Name = "txtForeignShortName";
        txtForeignShortName.AccessibleName = "الاسم المختصر أجنبي";
        txtForeignShortName.Dock = DockStyle.Fill;
        txtForeignShortName.TabIndex = 6;
        txtForeignShortName.Margin = new Padding(6, 8, 6, 8);
        txtForeignShortName.ReadOnly = true;
        txtForeignShortName.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtForeignShortName, 0, 6);
        fields.Controls.Add(txtForeignShortName, 1, 6);
        lbltxtDialingCode = new Label();
        lbltxtDialingCode.Name = "lbltxtDialingCode";
        lbltxtDialingCode.Text = "المفتاح";
        lbltxtDialingCode.AutoSize = true;
        lbltxtDialingCode.Dock = DockStyle.Fill;
        lbltxtDialingCode.TextAlign = ContentAlignment.MiddleRight;
        lbltxtDialingCode.Margin = new Padding(6, 8, 6, 8);
        txtDialingCode = new TextBox();
        txtDialingCode.BackColor = Color.White;
        txtDialingCode.Name = "txtDialingCode";
        txtDialingCode.AccessibleName = "المفتاح";
        txtDialingCode.Dock = DockStyle.Fill;
        txtDialingCode.TabIndex = 7;
        txtDialingCode.Margin = new Padding(6, 8, 6, 8);
        txtDialingCode.ReadOnly = true;
        txtDialingCode.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtDialingCode, 0, 7);
        fields.Controls.Add(txtDialingCode, 1, 7);
        lbltxtLanguage = new Label();
        lbltxtLanguage.Name = "lbltxtLanguage";
        lbltxtLanguage.Text = "اللغة";
        lbltxtLanguage.AutoSize = true;
        lbltxtLanguage.Dock = DockStyle.Fill;
        lbltxtLanguage.TextAlign = ContentAlignment.MiddleRight;
        lbltxtLanguage.Margin = new Padding(6, 8, 6, 8);
        txtLanguage = new TextBox();
        txtLanguage.BackColor = Color.White;
        txtLanguage.Name = "txtLanguage";
        txtLanguage.AccessibleName = "اللغة";
        txtLanguage.Dock = DockStyle.Fill;
        txtLanguage.TabIndex = 8;
        txtLanguage.Margin = new Padding(6, 8, 6, 8);
        txtLanguage.ReadOnly = true;
        txtLanguage.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtLanguage, 0, 8);
        fields.Controls.Add(txtLanguage, 1, 8);
        lbltxtCountryCode = new Label();
        lbltxtCountryCode.Name = "lbltxtCountryCode";
        lbltxtCountryCode.Text = "كود الدولة";
        lbltxtCountryCode.AutoSize = true;
        lbltxtCountryCode.Dock = DockStyle.Fill;
        lbltxtCountryCode.TextAlign = ContentAlignment.MiddleRight;
        lbltxtCountryCode.Margin = new Padding(6, 8, 6, 8);
        txtCountryCode = new TextBox();
        txtCountryCode.BackColor = Color.White;
        txtCountryCode.Name = "txtCountryCode";
        txtCountryCode.AccessibleName = "كود الدولة";
        txtCountryCode.Dock = DockStyle.Fill;
        txtCountryCode.TabIndex = 9;
        txtCountryCode.Margin = new Padding(6, 8, 6, 8);
        txtCountryCode.ReadOnly = true;
        txtCountryCode.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtCountryCode, 0, 9);
        fields.Controls.Add(txtCountryCode, 1, 9);
        lbltxtNationality = new Label();
        lbltxtNationality.Name = "lbltxtNationality";
        lbltxtNationality.Text = "الجنسية";
        lbltxtNationality.AutoSize = true;
        lbltxtNationality.Dock = DockStyle.Fill;
        lbltxtNationality.TextAlign = ContentAlignment.MiddleRight;
        lbltxtNationality.Margin = new Padding(6, 8, 6, 8);
        txtNationality = new TextBox();
        txtNationality.BackColor = Color.White;
        txtNationality.Name = "txtNationality";
        txtNationality.AccessibleName = "الجنسية";
        txtNationality.Dock = DockStyle.Fill;
        txtNationality.TabIndex = 10;
        txtNationality.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtNationality, 0, 10);
        fields.Controls.Add(txtNationality, 1, 10);
        lblcboRegionNumber = new Label();
        lblcboRegionNumber.Name = "lblcboRegionNumber";
        lblcboRegionNumber.Text = "رقم الإقليم";
        lblcboRegionNumber.AutoSize = true;
        lblcboRegionNumber.Dock = DockStyle.Fill;
        lblcboRegionNumber.TextAlign = ContentAlignment.MiddleRight;
        lblcboRegionNumber.Margin = new Padding(6, 8, 6, 8);
        cboRegionNumber = new ComboBox();
        cboRegionNumber.Name = "cboRegionNumber";
        cboRegionNumber.AccessibleName = "رقم الإقليم";
        cboRegionNumber.Dock = DockStyle.Fill;
        cboRegionNumber.TabIndex = 11;
        cboRegionNumber.Margin = new Padding(6, 8, 6, 8);
        cboRegionNumber.DropDownStyle = ComboBoxStyle.DropDownList;
        cboRegionNumber.Enabled = false;
        cboRegionNumber.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboRegionNumber, 0, 11);
        fields.Controls.Add(cboRegionNumber, 1, 11);
        lblchkBlockTransactions = new Label();
        lblchkBlockTransactions.Name = "lblchkBlockTransactions";
        lblchkBlockTransactions.Text = "حضر التعامل";
        lblchkBlockTransactions.AutoSize = true;
        lblchkBlockTransactions.Dock = DockStyle.Fill;
        lblchkBlockTransactions.TextAlign = ContentAlignment.MiddleRight;
        lblchkBlockTransactions.Margin = new Padding(6, 8, 6, 8);
        chkBlockTransactions = new CheckBox();
        chkBlockTransactions.Name = "chkBlockTransactions";
        chkBlockTransactions.AccessibleName = "حضر التعامل";
        chkBlockTransactions.Dock = DockStyle.Fill;
        chkBlockTransactions.TabIndex = 12;
        chkBlockTransactions.Margin = new Padding(6, 8, 6, 8);
        chkBlockTransactions.AutoSize = true;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblchkBlockTransactions, 0, 12);
        fields.Controls.Add(chkBlockTransactions, 1, 12);
        standardCommandAdd.Name = "btnAdd";
        standardCommandAdd.Enabled = true;
        standardCommandAdd.Click += draftAction_Click;
        standardCommandSave.Name = "btnSave";
        standardCommandSave.Enabled = false;
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        layout.Controls.Add(lblTitle, 0, 0);
        layout.Controls.Add(lblStatus, 0, 1);
        layout.Controls.Add(designerCommandBar, 0, 2);
        layout.Controls.Add(fields, 0, 3);
        Controls.Add(layout);


        Name = "UcCountryData";
        Text = "بيانات الدول";
        Size = new Size(1000, 640);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        RightToLeft = RightToLeft.Yes;
        fields.ResumeLayout(true);
        layout.ResumeLayout(true);
        ResumeLayout(true);

        standardCommandAdd.Visible = true;
        standardCommandEdit.Visible = true;
        standardCommandDelete.Visible = true;
        standardCommandCancel.Visible = true;
        standardCommandView.Visible = true;
        standardCommandLast.Visible = true;
        standardCommandNext.Visible = true;
        standardCommandPrevious.Visible = true;
        standardCommandFirst.Visible = true;
        standardCommandSave.Visible = true;
        standardCommandPrint.Visible = true;
        standardCommandClose.Visible = true;
        standardCommandRefresh.Visible = false;
        standardCommandImport.Visible = false;
        standardCommandExport.Visible = false;
        standardCommandHelp.Visible = false;
    

        fields.SuspendLayout();
        fields.ColumnStyles.Clear();
        fields.RowStyles.Clear();
        fields.ColumnCount = 4;
        fields.RowCount = 8;
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 18F));
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 18F));
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Clear();
        fields.Controls.Add(lblcboCountryNumber, 0, 0);
        fields.Controls.Add(cboCountryNumber, 1, 0);
        fields.Controls.Add(lbltxtCountryNameLocal, 0, 1);
        fields.Controls.Add(txtCountryNameLocal, 1, 1);
        fields.SetColumnSpan(txtCountryNameLocal, 3);
        fields.Controls.Add(lbltxtCountryNameForeign, 0, 2);
        fields.Controls.Add(txtCountryNameForeign, 1, 2);
        fields.SetColumnSpan(txtCountryNameForeign, 3);
        fields.Controls.Add(lblcboCountryShortName, 0, 3);
        fields.Controls.Add(cboCountryShortName, 1, 3);
        fields.Controls.Add(lbltxtLocalCurrency, 2, 3);
        fields.Controls.Add(txtLocalCurrency, 3, 3);
        fields.Controls.Add(lbltxtContinent, 0, 4);
        fields.Controls.Add(txtContinent, 1, 4);
        fields.Controls.Add(lblcboRegionNumber, 2, 4);
        fields.Controls.Add(cboRegionNumber, 3, 4);
        fields.Controls.Add(lbltxtNationality, 0, 5);
        fields.Controls.Add(txtNationality, 1, 5);
        fields.Controls.Add(lbltxtForeignShortName, 2, 5);
        fields.Controls.Add(txtForeignShortName, 3, 5);
        fields.Controls.Add(lbltxtDialingCode, 0, 6);
        fields.Controls.Add(txtDialingCode, 1, 6);
        fields.Controls.Add(lblchkBlockTransactions, 2, 6);
        fields.Controls.Add(chkBlockTransactions, 3, 6);
        fields.Controls.Add(lbltxtLanguage, 0, 7);
        fields.Controls.Add(txtLanguage, 1, 7);
        fields.Controls.Add(lbltxtCountryCode, 2, 7);
        fields.Controls.Add(txtCountryCode, 3, 7);
        fields.ResumeLayout(true);
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
    }
}
