namespace TransportERP.Desktop.Forms.SystemSettings.General;
partial class UcCostCenterData
{
    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private FlowLayoutPanel standardCommandFlow = null!;
    private Panel standardCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandView = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandSave = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandClose = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel layout = null!;
    private TableLayoutPanel fields = null!;
    private Label lblTitle = null!;
    private Label lblStatus = null!;
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;
    private Label lbltxtCenterNumber = null!;
    private TextBox txtCenterNumber = null!;
    private Label lbltxtParentCenter = null!;
    private TextBox txtParentCenter = null!;
    private Label lbltxtNameLocal = null!;
    private TextBox txtNameLocal = null!;
    private Label lbltxtNameForeign = null!;
    private TextBox txtNameForeign = null!;
    private Label lbltxtRank = null!;
    private TextBox txtRank = null!;
    private Label lbltxtSequence = null!;
    private TextBox txtSequence = null!;
    private Label lblcboCenterType = null!;
    private ComboBox cboCenterType = null!;
    private Label lblcboCenterGroup = null!;
    private ComboBox cboCenterGroup = null!;
    private Label lblchkStopSales = null!;
    private CheckBox chkStopSales = null!;
    private Label lblchkStopped = null!;
    private CheckBox chkStopped = null!;
    private Label lbltxtStopReason = null!;
    private TextBox txtStopReason = null!;
    private Label lbltxtStoppedAt = null!;
    private TextBox txtStoppedAt = null!;
    private Label lblcboUseProjects = null!;
    private ComboBox cboUseProjects = null!;
    private TabControl tabsFields = null!;
    private TabPage sectionPage0 = null!;
    private TableLayoutPanel sectionFields0 = null!;
    private TabPage sectionPage1 = null!;
    private TableLayoutPanel sectionFields1 = null!;
    private TabPage sectionPage2 = null!;
    private TableLayoutPanel sectionFields2 = null!;
    private TableLayoutPanel pnlbtnSelectProjects = null!;
    private Button btnSelectProjects = null!;
    private GroupBox grpbtnSelectProjects = null!;
    private CheckedListBox lstbtnSelectProjects = null!;
    private Label projectsNotice = null!;
    private Label sectionNotice2 = null!;
    private Button toolbar_btnSelectProjects = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        standardCommandFlow = new FlowLayoutPanel();
        standardCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandView = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandSave = new Button();
        standardCommandPrint = new Button();
        standardCommandClose = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.Size = new Size(1000, 44);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Margin = Padding.Empty;
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        standardCommandFlow.Name = "pnlToolbar";
        standardCommandFlow.Dock = DockStyle.Fill;
        standardCommandFlow.FlowDirection = FlowDirection.RightToLeft;
        standardCommandFlow.RightToLeft = RightToLeft.No;
        standardCommandFlow.WrapContents = false;
        standardCommandFlow.Padding = new Padding(2);
        standardCloseHost.Name = "standardCloseHost";
        standardCloseHost.Dock = DockStyle.Left;
        standardCloseHost.Width = 28;
        designerCommandBar.Controls.Add(standardCommandFlow);
        designerCommandBar.Controls.Add(standardCloseHost);
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = true;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.TabIndex = 0;
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandFlow.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = true;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.TabIndex = 1;
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandFlow.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.TabIndex = 2;
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandFlow.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.TabIndex = 3;
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandFlow.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        standardCommandView.Name = "standardCommandView";
        standardCommandView.AccessibleName = "عرض";
        standardCommandView.Enabled = false;
        standardCommandView.Visible = true;
        standardCommandView.Size = new Size(26, 24);
        standardCommandView.Margin = new Padding(1);
        standardCommandView.FlatStyle = FlatStyle.Flat;
        standardCommandView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandView.TabIndex = 4;
        standardCommandView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        standardCommandFlow.Controls.Add(standardCommandView);
        designerCommandBar.SetCommandRole(standardCommandView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.TabIndex = 5;
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandFlow.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.AccessibleName = "التالي";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.TabIndex = 6;
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandFlow.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.TabIndex = 7;
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandFlow.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.TabIndex = 8;
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFlow.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        standardCommandSave.Name = "btnSave";
        standardCommandSave.AccessibleName = "حفظ";
        standardCommandSave.Enabled = false;
        standardCommandSave.Visible = true;
        standardCommandSave.Size = new Size(26, 24);
        standardCommandSave.Margin = new Padding(1);
        standardCommandSave.FlatStyle = FlatStyle.Flat;
        standardCommandSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandSave.TabIndex = 9;
        standardCommandSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        standardCommandFlow.Controls.Add(standardCommandSave);
        designerCommandBar.SetCommandRole(standardCommandSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.TabIndex = 10;
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandFlow.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        standardCommandClose.Name = "standardCommandClose";
        standardCommandClose.AccessibleName = "إغلاق";
        standardCommandClose.Enabled = false;
        standardCommandClose.Visible = true;
        standardCommandClose.Size = new Size(26, 24);
        standardCommandClose.Margin = new Padding(1);
        standardCommandClose.FlatStyle = FlatStyle.Flat;
        standardCommandClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandClose.TabIndex = 11;
        standardCommandClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        standardCloseHost.Controls.Add(standardCommandClose);
        designerCommandBar.SetCommandRole(standardCommandClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.TabIndex = 12;
        standardCommandRefresh.Text = "تحديث";
        standardCommandFlow.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.TabIndex = 13;
        standardCommandImport.Text = "استيراد";
        standardCommandFlow.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.TabIndex = 14;
        standardCommandExport.Text = "تصدير";
        standardCommandFlow.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.TabIndex = 15;
        standardCommandHelp.Text = "مساعدة";
        standardCommandFlow.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
        standardCommandClose.Location = new Point(1, 1);
        standardCommandSave.AccessibleDescription = "الحفظ غير متاح؛ لم تُربط الشاشة بخدمة بيانات.";
        Controls.Add(designerCommandBar);

        layout = new TableLayoutPanel();
        fields = new TableLayoutPanel();
        lblTitle = new Label();
        lblStatus = new Label();
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        layout.SuspendLayout();
        fields.SuspendLayout();
        layout.Name = "layout";
        layout.Dock = DockStyle.Top;
        layout.AutoSize = true;
        layout.ColumnCount = 1;
        layout.RowCount = 4;
        layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "مراكز التكلفة";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Font = new Font("Segoe UI", 16F);
        lblTitle.TextAlign = ContentAlignment.MiddleRight;
        lblTitle.BackColor = Color.FromArgb(192, 192, 255);
        lblTitle.Padding = new Padding(12);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "معاينة إدخال مؤقتة — الحفظ والترقيم التلقائي والقوائم غير متاحة؛ القيم لا تُطبّق على النظام.";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.TextAlign = ContentAlignment.MiddleRight;
        lblStatus.Padding = new Padding(8);
        fields.Name = "fields";
        fields.Dock = DockStyle.Top;
        fields.AutoSize = true;
        fields.ColumnCount = 2;
        fields.RowCount = 13;
        fields.Enabled = false;
        fields.TabIndex = 1;
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
        lbltxtCenterNumber = new Label();
        lbltxtCenterNumber.Name = "lbltxtCenterNumber";
        lbltxtCenterNumber.Text = "رقم مركز التكلفة";
        lbltxtCenterNumber.AutoSize = true;
        lbltxtCenterNumber.Dock = DockStyle.Fill;
        lbltxtCenterNumber.TextAlign = ContentAlignment.MiddleRight;
        lbltxtCenterNumber.Margin = new Padding(6, 8, 6, 8);
        txtCenterNumber = new TextBox();
        txtCenterNumber.BackColor = Color.White;
        txtCenterNumber.Name = "txtCenterNumber";
        txtCenterNumber.AccessibleName = "رقم مركز التكلفة";
        txtCenterNumber.Dock = DockStyle.Fill;
        txtCenterNumber.TabIndex = 0;
        txtCenterNumber.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtCenterNumber, 0, 0);
        fields.Controls.Add(txtCenterNumber, 1, 0);
        lbltxtParentCenter = new Label();
        lbltxtParentCenter.Name = "lbltxtParentCenter";
        lbltxtParentCenter.Text = "المركز الرئيسي";
        lbltxtParentCenter.AutoSize = true;
        lbltxtParentCenter.Dock = DockStyle.Fill;
        lbltxtParentCenter.TextAlign = ContentAlignment.MiddleRight;
        lbltxtParentCenter.Margin = new Padding(6, 8, 6, 8);
        txtParentCenter = new TextBox();
        txtParentCenter.BackColor = Color.White;
        txtParentCenter.Name = "txtParentCenter";
        txtParentCenter.AccessibleName = "المركز الرئيسي";
        txtParentCenter.Dock = DockStyle.Fill;
        txtParentCenter.TabIndex = 1;
        txtParentCenter.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtParentCenter, 0, 1);
        fields.Controls.Add(txtParentCenter, 1, 1);
        lbltxtNameLocal = new Label();
        lbltxtNameLocal.Name = "lbltxtNameLocal";
        lbltxtNameLocal.Text = "اسم المركز (محلي)";
        lbltxtNameLocal.AutoSize = true;
        lbltxtNameLocal.Dock = DockStyle.Fill;
        lbltxtNameLocal.TextAlign = ContentAlignment.MiddleRight;
        lbltxtNameLocal.Margin = new Padding(6, 8, 6, 8);
        txtNameLocal = new TextBox();
        txtNameLocal.BackColor = Color.White;
        txtNameLocal.Name = "txtNameLocal";
        txtNameLocal.AccessibleName = "اسم المركز (محلي)";
        txtNameLocal.Dock = DockStyle.Fill;
        txtNameLocal.TabIndex = 2;
        txtNameLocal.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtNameLocal, 0, 2);
        fields.Controls.Add(txtNameLocal, 1, 2);
        lbltxtNameForeign = new Label();
        lbltxtNameForeign.Name = "lbltxtNameForeign";
        lbltxtNameForeign.Text = "اسم المركز (أجنبي)";
        lbltxtNameForeign.AutoSize = true;
        lbltxtNameForeign.Dock = DockStyle.Fill;
        lbltxtNameForeign.TextAlign = ContentAlignment.MiddleRight;
        lbltxtNameForeign.Margin = new Padding(6, 8, 6, 8);
        txtNameForeign = new TextBox();
        txtNameForeign.BackColor = Color.White;
        txtNameForeign.Name = "txtNameForeign";
        txtNameForeign.AccessibleName = "اسم المركز (أجنبي)";
        txtNameForeign.Dock = DockStyle.Fill;
        txtNameForeign.TabIndex = 3;
        txtNameForeign.Margin = new Padding(6, 8, 6, 8);
        txtNameForeign.RightToLeft = RightToLeft.No;
        txtNameForeign.TextAlign = HorizontalAlignment.Left;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtNameForeign, 0, 3);
        fields.Controls.Add(txtNameForeign, 1, 3);
        lbltxtRank = new Label();
        lbltxtRank.Name = "lbltxtRank";
        lbltxtRank.Text = "الرتبة";
        lbltxtRank.AutoSize = true;
        lbltxtRank.Dock = DockStyle.Fill;
        lbltxtRank.TextAlign = ContentAlignment.MiddleRight;
        lbltxtRank.Margin = new Padding(6, 8, 6, 8);
        txtRank = new TextBox();
        txtRank.BackColor = Color.White;
        txtRank.Name = "txtRank";
        txtRank.AccessibleName = "الرتبة";
        txtRank.Dock = DockStyle.Fill;
        txtRank.TabIndex = 4;
        txtRank.Margin = new Padding(6, 8, 6, 8);
        txtRank.ReadOnly = true;
        txtRank.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtRank, 0, 4);
        fields.Controls.Add(txtRank, 1, 4);
        lbltxtSequence = new Label();
        lbltxtSequence.Name = "lbltxtSequence";
        lbltxtSequence.Text = "التسلسل";
        lbltxtSequence.AutoSize = true;
        lbltxtSequence.Dock = DockStyle.Fill;
        lbltxtSequence.TextAlign = ContentAlignment.MiddleRight;
        lbltxtSequence.Margin = new Padding(6, 8, 6, 8);
        txtSequence = new TextBox();
        txtSequence.BackColor = Color.White;
        txtSequence.Name = "txtSequence";
        txtSequence.AccessibleName = "التسلسل";
        txtSequence.Dock = DockStyle.Fill;
        txtSequence.TabIndex = 5;
        txtSequence.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtSequence, 0, 5);
        fields.Controls.Add(txtSequence, 1, 5);
        lblcboCenterType = new Label();
        lblcboCenterType.Name = "lblcboCenterType";
        lblcboCenterType.Text = "نوع المركز";
        lblcboCenterType.AutoSize = true;
        lblcboCenterType.Dock = DockStyle.Fill;
        lblcboCenterType.TextAlign = ContentAlignment.MiddleRight;
        lblcboCenterType.Margin = new Padding(6, 8, 6, 8);
        cboCenterType = new ComboBox();
        cboCenterType.Name = "cboCenterType";
        cboCenterType.AccessibleName = "نوع المركز";
        cboCenterType.Dock = DockStyle.Fill;
        cboCenterType.TabIndex = 6;
        cboCenterType.Margin = new Padding(6, 8, 6, 8);
        cboCenterType.DropDownStyle = ComboBoxStyle.DropDownList;
        cboCenterType.Enabled = false;
        cboCenterType.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboCenterType, 0, 6);
        fields.Controls.Add(cboCenterType, 1, 6);
        lblcboCenterGroup = new Label();
        lblcboCenterGroup.Name = "lblcboCenterGroup";
        lblcboCenterGroup.Text = "مجموعة المراكز";
        lblcboCenterGroup.AutoSize = true;
        lblcboCenterGroup.Dock = DockStyle.Fill;
        lblcboCenterGroup.TextAlign = ContentAlignment.MiddleRight;
        lblcboCenterGroup.Margin = new Padding(6, 8, 6, 8);
        cboCenterGroup = new ComboBox();
        cboCenterGroup.Name = "cboCenterGroup";
        cboCenterGroup.AccessibleName = "مجموعة المراكز";
        cboCenterGroup.Dock = DockStyle.Fill;
        cboCenterGroup.TabIndex = 7;
        cboCenterGroup.Margin = new Padding(6, 8, 6, 8);
        cboCenterGroup.DropDownStyle = ComboBoxStyle.DropDownList;
        cboCenterGroup.Enabled = false;
        cboCenterGroup.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboCenterGroup, 0, 7);
        fields.Controls.Add(cboCenterGroup, 1, 7);
        lblchkStopSales = new Label();
        lblchkStopSales.Name = "lblchkStopSales";
        lblchkStopSales.Text = "توقيف المبيعات";
        lblchkStopSales.AutoSize = true;
        lblchkStopSales.Dock = DockStyle.Fill;
        lblchkStopSales.TextAlign = ContentAlignment.MiddleRight;
        lblchkStopSales.Margin = new Padding(6, 8, 6, 8);
        chkStopSales = new CheckBox();
        chkStopSales.Name = "chkStopSales";
        chkStopSales.AccessibleName = "توقيف المبيعات";
        chkStopSales.Dock = DockStyle.Fill;
        chkStopSales.TabIndex = 8;
        chkStopSales.Margin = new Padding(6, 8, 6, 8);
        chkStopSales.AutoSize = true;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblchkStopSales, 0, 8);
        fields.Controls.Add(chkStopSales, 1, 8);
        lblchkStopped = new Label();
        lblchkStopped.Name = "lblchkStopped";
        lblchkStopped.Text = "موقف";
        lblchkStopped.AutoSize = true;
        lblchkStopped.Dock = DockStyle.Fill;
        lblchkStopped.TextAlign = ContentAlignment.MiddleRight;
        lblchkStopped.Margin = new Padding(6, 8, 6, 8);
        chkStopped = new CheckBox();
        chkStopped.Name = "chkStopped";
        chkStopped.AccessibleName = "موقف";
        chkStopped.Dock = DockStyle.Fill;
        chkStopped.TabIndex = 9;
        chkStopped.Margin = new Padding(6, 8, 6, 8);
        chkStopped.AutoSize = true;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblchkStopped, 0, 9);
        fields.Controls.Add(chkStopped, 1, 9);
        lbltxtStopReason = new Label();
        lbltxtStopReason.Name = "lbltxtStopReason";
        lbltxtStopReason.Text = "سبب الإيقاف";
        lbltxtStopReason.AutoSize = true;
        lbltxtStopReason.Dock = DockStyle.Fill;
        lbltxtStopReason.TextAlign = ContentAlignment.MiddleRight;
        lbltxtStopReason.Margin = new Padding(6, 8, 6, 8);
        txtStopReason = new TextBox();
        txtStopReason.BackColor = Color.White;
        txtStopReason.Name = "txtStopReason";
        txtStopReason.AccessibleName = "سبب الإيقاف";
        txtStopReason.Dock = DockStyle.Fill;
        txtStopReason.TabIndex = 10;
        txtStopReason.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtStopReason, 0, 10);
        fields.Controls.Add(txtStopReason, 1, 10);
        lbltxtStoppedAt = new Label();
        lbltxtStoppedAt.Name = "lbltxtStoppedAt";
        lbltxtStoppedAt.Text = "تاريخ الإيقاف";
        lbltxtStoppedAt.AutoSize = true;
        lbltxtStoppedAt.Dock = DockStyle.Fill;
        lbltxtStoppedAt.TextAlign = ContentAlignment.MiddleRight;
        lbltxtStoppedAt.Margin = new Padding(6, 8, 6, 8);
        txtStoppedAt = new TextBox();
        txtStoppedAt.BackColor = Color.White;
        txtStoppedAt.Name = "txtStoppedAt";
        txtStoppedAt.AccessibleName = "تاريخ الإيقاف";
        txtStoppedAt.Dock = DockStyle.Fill;
        txtStoppedAt.TabIndex = 11;
        txtStoppedAt.Margin = new Padding(6, 8, 6, 8);
        txtStoppedAt.ReadOnly = true;
        txtStoppedAt.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtStoppedAt, 0, 11);
        fields.Controls.Add(txtStoppedAt, 1, 11);
        lblcboUseProjects = new Label();
        lblcboUseProjects.Name = "lblcboUseProjects";
        lblcboUseProjects.Text = "استخدام المشاريع";
        lblcboUseProjects.AutoSize = true;
        lblcboUseProjects.Dock = DockStyle.Fill;
        lblcboUseProjects.TextAlign = ContentAlignment.MiddleRight;
        lblcboUseProjects.Margin = new Padding(6, 8, 6, 8);
        cboUseProjects = new ComboBox();
        cboUseProjects.Name = "cboUseProjects";
        cboUseProjects.AccessibleName = "استخدام المشاريع";
        cboUseProjects.Dock = DockStyle.Fill;
        cboUseProjects.TabIndex = 12;
        cboUseProjects.Margin = new Padding(6, 8, 6, 8);
        cboUseProjects.DropDownStyle = ComboBoxStyle.DropDownList;
        cboUseProjects.Items.AddRange(new object[] { "غير مستخدم", "اختياري", "إجباري" });
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboUseProjects, 0, 12);
        fields.Controls.Add(cboUseProjects, 1, 12);
        standardCommandAdd.Name = "btnAdd";
        standardCommandAdd.Enabled = true;
        standardCommandAdd.Click += draftAction_Click;
        standardCommandSave.Name = "btnSave";
        standardCommandSave.Enabled = false;
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        layout.Controls.Add(lblTitle, 0, 0);
        layout.Controls.Add(lblStatus, 0, 1);
        layout.Controls.Add(designerCommandBar, 0, 2);
        layout.Controls.Add(fields, 0, 3);
        Controls.Add(layout);


        Name = "UcCostCenterData";
        Text = "مراكز التكلفة";
        Size = new Size(1000, 640);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        RightToLeft = RightToLeft.Yes;
        fields.ResumeLayout(true);
        layout.ResumeLayout(true);
        ResumeLayout(true);
        tabsFields = new TabControl();
        tabsFields.Name = "tabsFields";
        tabsFields.Dock = DockStyle.Fill;
        tabsFields.MinimumSize = new Size(0, 520);
        tabsFields.Height = 520;
        tabsFields.RightToLeftLayout = true;
        sectionPage0 = new TabPage();
        sectionFields0 = new TableLayoutPanel();
        sectionPage0.Text = "البيانات الأساسية";
        sectionPage0.AutoScroll = true;
        sectionFields0.Dock = DockStyle.Top;
        sectionFields0.AutoSize = true;
        sectionFields0.ColumnCount = 2;
        sectionFields0.RowCount = 4;
        sectionFields0.Enabled = false;
        sectionFields0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        sectionFields0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lbltxtCenterNumber, 0, 0);
        sectionFields0.Controls.Add(txtCenterNumber, 1, 0);
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lbltxtParentCenter, 0, 1);
        sectionFields0.Controls.Add(txtParentCenter, 1, 1);
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lbltxtNameLocal, 0, 2);
        sectionFields0.Controls.Add(txtNameLocal, 1, 2);
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lbltxtNameForeign, 0, 3);
        sectionFields0.Controls.Add(txtNameForeign, 1, 3);
        sectionPage0.Controls.Add(sectionFields0);
        tabsFields.TabPages.Add(sectionPage0);
        sectionPage1 = new TabPage();
        sectionFields1 = new TableLayoutPanel();
        sectionPage1.Text = "مراكز التكلفة";
        sectionPage1.AutoScroll = true;
        sectionFields1.Dock = DockStyle.Top;
        sectionFields1.AutoSize = true;
        sectionFields1.ColumnCount = 2;
        sectionFields1.RowCount = 9;
        sectionFields1.Enabled = false;
        sectionFields1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        sectionFields1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lbltxtRank, 0, 0);
        sectionFields1.Controls.Add(txtRank, 1, 0);
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lbltxtSequence, 0, 1);
        sectionFields1.Controls.Add(txtSequence, 1, 1);
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lblcboCenterType, 0, 2);
        sectionFields1.Controls.Add(cboCenterType, 1, 2);
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lblcboCenterGroup, 0, 3);
        sectionFields1.Controls.Add(cboCenterGroup, 1, 3);
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lblchkStopSales, 0, 4);
        sectionFields1.Controls.Add(chkStopSales, 1, 4);
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lblchkStopped, 0, 5);
        sectionFields1.Controls.Add(chkStopped, 1, 5);
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lbltxtStopReason, 0, 6);
        sectionFields1.Controls.Add(txtStopReason, 1, 6);
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lbltxtStoppedAt, 0, 7);
        sectionFields1.Controls.Add(txtStoppedAt, 1, 7);
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lblcboUseProjects, 0, 8);
        sectionFields1.Controls.Add(cboUseProjects, 1, 8);
        sectionPage1.Controls.Add(sectionFields1);
        tabsFields.TabPages.Add(sectionPage1);
        sectionPage2 = new TabPage();
        sectionFields2 = new TableLayoutPanel();
        sectionPage2.Text = "حقول إضافية";
        sectionPage2.AutoScroll = true;
        sectionFields2.Dock = DockStyle.Top;
        sectionFields2.AutoSize = true;
        sectionFields2.ColumnCount = 2;
        sectionFields2.RowCount = 0;
        sectionFields2.Enabled = false;
        sectionFields2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        sectionFields2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
        sectionPage2.Controls.Add(sectionFields2);
        tabsFields.TabPages.Add(sectionPage2);
        fields.Visible = false;
        layout.RowCount = 5;
        layout.Controls.Add(tabsFields, 0, 4);
        pnlbtnSelectProjects = new TableLayoutPanel();
        btnSelectProjects = new Button();
        grpbtnSelectProjects = new GroupBox();
        lstbtnSelectProjects = new CheckedListBox();
        projectsNotice = new Label();
        pnlbtnSelectProjects.Name = "pnlbtnSelectProjects";
        pnlbtnSelectProjects.Dock = DockStyle.Top;
        pnlbtnSelectProjects.AutoSize = true;
        pnlbtnSelectProjects.ColumnCount = 2;
        pnlbtnSelectProjects.RowCount = 2;
        pnlbtnSelectProjects.Margin = cboUseProjects.Margin;
        pnlbtnSelectProjects.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pnlbtnSelectProjects.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
        pnlbtnSelectProjects.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        pnlbtnSelectProjects.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        cboUseProjects.Margin = Padding.Empty;
        pnlbtnSelectProjects.Controls.Add(cboUseProjects, 0, 0);
        btnSelectProjects.Name = "btnSelectProjects";
        btnSelectProjects.Text = "…";
        btnSelectProjects.AccessibleName = "المشاريع";
        btnSelectProjects.AutoSize = true;
        btnSelectProjects.MinimumSize = new Size(36, 30);
        btnSelectProjects.Margin = new Padding(4, 0, 0, 0);
        btnSelectProjects.AccessibleDescription = "المشاريع — عرض قائمة فارغة؛ مصدر البيانات غير مرتبط.";
        pnlbtnSelectProjects.Controls.Add(btnSelectProjects, 1, 0);
        grpbtnSelectProjects.Name = "grpbtnSelectProjects";
        grpbtnSelectProjects.Text = "المشاريع";
        grpbtnSelectProjects.Dock = DockStyle.Top;
        grpbtnSelectProjects.Height = 190;
        grpbtnSelectProjects.MinimumSize = new Size(0, 190);
        grpbtnSelectProjects.Padding = new Padding(8, 24, 8, 8);
        grpbtnSelectProjects.Visible = false;
        lstbtnSelectProjects.Name = "lstbtnSelectProjects";
        lstbtnSelectProjects.AccessibleName = "المشاريع";
        lstbtnSelectProjects.CheckOnClick = true;
        lstbtnSelectProjects.IntegralHeight = false;
        lstbtnSelectProjects.Enabled = false;
        lstbtnSelectProjects.Dock = DockStyle.Fill;
        grpbtnSelectProjects.Controls.Add(lstbtnSelectProjects);
        projectsNotice.Text = "القائمة غير مرتبطة ببيانات؛ لا توجد سجلات للاختيار.";
        projectsNotice.AutoSize = true;
        projectsNotice.Dock = DockStyle.Bottom;
        projectsNotice.Padding = new Padding(4);
        projectsNotice.MaximumSize = new Size(550, 0);
        grpbtnSelectProjects.Controls.Add(projectsNotice);
        pnlbtnSelectProjects.Controls.Add(grpbtnSelectProjects, 0, 1);
        pnlbtnSelectProjects.SetColumnSpan(grpbtnSelectProjects, 2);
        sectionFields1.Controls.Add(pnlbtnSelectProjects, 1, 8);
        sectionNotice2 = new Label();
        sectionNotice2.Text = "تظهر هنا الحقول المعرّفة في التهيئة بعد ربطها؛ أسماء وعدد الحقول غير محددين في النص.";
        sectionNotice2.AutoSize = true;
        sectionNotice2.Dock = DockStyle.Top;
        sectionNotice2.Padding = new Padding(12);
        sectionNotice2.MaximumSize = new Size(700, 0);
        sectionPage2.Controls.Add(sectionNotice2);

        toolbar_btnSelectProjects = new Button();
        standardCommandAdd.Visible = true;
        standardCommandEdit.Visible = true;
        standardCommandDelete.Visible = true;
        standardCommandCancel.Visible = true;
        standardCommandView.Visible = true;
        standardCommandLast.Visible = true;
        standardCommandNext.Visible = true;
        standardCommandPrevious.Visible = true;
        standardCommandFirst.Visible = true;
        standardCommandSave.Visible = true;
        standardCommandPrint.Visible = true;
        standardCommandClose.Visible = true;
        standardCommandRefresh.Visible = false;
        standardCommandImport.Visible = false;
        standardCommandExport.Visible = false;
        standardCommandHelp.Visible = false;
        standardCommandImport.Visible = true;
        standardCommandImport.Name = "btnImportExcel";
        standardCommandImport.Text = "الاستيراد من أكسل";
        standardCommandImport.AutoSize = true;
        standardCommandImport.Enabled = false;
        standardCommandImport.AccessibleDescription = "خدمة الاستيراد غير مرتبطة.";
        toolbar_btnSelectProjects.Name = "toolbar_btnSelectProjects";
        toolbar_btnSelectProjects.Text = "المشاريع";
        toolbar_btnSelectProjects.AutoSize = true;
        toolbar_btnSelectProjects.Enabled = false;
        standardCommandFlow.Controls.Add(toolbar_btnSelectProjects);
    

        sectionFields0.SuspendLayout();
        sectionFields0.ColumnStyles.Clear();
        sectionFields0.RowStyles.Clear();
        sectionFields0.ColumnCount = 4;
        sectionFields0.RowCount = 3;
        sectionFields0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 18F));
        sectionFields0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        sectionFields0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 18F));
        sectionFields0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Clear();
        sectionFields0.Controls.Add(lbltxtCenterNumber, 0, 0);
        sectionFields0.Controls.Add(txtCenterNumber, 1, 0);
        sectionFields0.Controls.Add(lbltxtParentCenter, 2, 0);
        sectionFields0.Controls.Add(txtParentCenter, 3, 0);
        sectionFields0.Controls.Add(lbltxtNameLocal, 0, 1);
        sectionFields0.Controls.Add(txtNameLocal, 1, 1);
        sectionFields0.SetColumnSpan(txtNameLocal, 3);
        sectionFields0.Controls.Add(lbltxtNameForeign, 0, 2);
        sectionFields0.Controls.Add(txtNameForeign, 1, 2);
        sectionFields0.SetColumnSpan(txtNameForeign, 3);
        sectionFields0.ResumeLayout(true);
        sectionFields1.SuspendLayout();
        sectionFields1.ColumnStyles.Clear();
        sectionFields1.RowStyles.Clear();
        sectionFields1.ColumnCount = 4;
        sectionFields1.RowCount = 6;
        sectionFields1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 18F));
        sectionFields1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        sectionFields1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 18F));
        sectionFields1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Clear();
        sectionFields1.Controls.Add(lbltxtRank, 0, 0);
        sectionFields1.Controls.Add(txtRank, 1, 0);
        sectionFields1.Controls.Add(lbltxtSequence, 2, 0);
        sectionFields1.Controls.Add(txtSequence, 3, 0);
        sectionFields1.Controls.Add(lblcboCenterType, 0, 1);
        sectionFields1.Controls.Add(cboCenterType, 1, 1);
        sectionFields1.Controls.Add(lblcboCenterGroup, 2, 1);
        sectionFields1.Controls.Add(cboCenterGroup, 3, 1);
        sectionFields1.Controls.Add(lblchkStopped, 0, 2);
        sectionFields1.Controls.Add(chkStopped, 1, 2);
        sectionFields1.Controls.Add(lbltxtStoppedAt, 2, 2);
        sectionFields1.Controls.Add(txtStoppedAt, 3, 2);
        sectionFields1.Controls.Add(lbltxtStopReason, 0, 3);
        sectionFields1.Controls.Add(txtStopReason, 1, 3);
        sectionFields1.SetColumnSpan(txtStopReason, 3);
        sectionFields1.Controls.Add(lblchkStopSales, 0, 4);
        sectionFields1.Controls.Add(chkStopSales, 1, 4);
        sectionFields1.Controls.Add(lblcboUseProjects, 0, 5);
        sectionFields1.Controls.Add(pnlbtnSelectProjects, 1, 5);
        sectionFields1.SetColumnSpan(pnlbtnSelectProjects, 3);
        sectionFields1.ResumeLayout(true);
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
    }
}
