using System.Drawing;
using System.Windows.Forms;

namespace TransportERP.Desktop.Forms.SystemSettings.General;

partial class UcCurrencyManagement
{
    private System.ComponentModel.IContainer? components;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        mainLayout = new TableLayoutPanel();
        pnlActions = new FlowLayoutPanel();
        btnNew = new Button();
        btnSave = new Button();
        btnEdit = new Button();
        btnDelete = new Button();
        btnRefresh = new Button();
        btnClose = new Button();
        lblPreview = new Label();
        tabMain = new TabControl();
        tabCurrencies = new TabPage();
        Currencies = new TableLayoutPanel();
        CurrenciesFields = new TableLayoutPanel();
        lbltxtCurrencyCode = new Label();
        txtCurrencyCode = new TextBox();
        lbltxtCurrencyNameAr = new Label();
        txtCurrencyNameAr = new TextBox();
        lbltxtCurrencyNameEn = new Label();
        txtCurrencyNameEn = new TextBox();
        lbltxtCurrencySymbol = new Label();
        txtCurrencySymbol = new TextBox();
        lblnudDecimalPlaces = new Label();
        nudDecimalPlaces = new NumericUpDown();
        lblchkCurrencyActive = new Label();
        chkCurrencyActive = new CheckBox();
        dgvCurrencies = new DataGridView();
        dgvCurrenciesColCode = new DataGridViewTextBoxColumn();
        dgvCurrenciesColNameAr = new DataGridViewTextBoxColumn();
        dgvCurrenciesColNameEn = new DataGridViewTextBoxColumn();
        dgvCurrenciesColSymbol = new DataGridViewTextBoxColumn();
        dgvCurrenciesColDecimals = new DataGridViewTextBoxColumn();
        dgvCurrenciesColActive = new DataGridViewTextBoxColumn();
        tabCurrencyRoles = new TabPage();
        rolesLayout = new TableLayoutPanel();
        CurrencyRoles = new TableLayoutPanel();
        lblcmbCompany = new Label();
        cmbCompany = new ComboBox();
        lblcmbAccountingCurrency = new Label();
        cmbAccountingCurrency = new ComboBox();
        lblcmbReportingCurrency = new Label();
        cmbReportingCurrency = new ComboBox();
        lblcmbDefaultTransactionCurrency = new Label();
        cmbDefaultTransactionCurrency = new ComboBox();
        SettingValue__SET_CUR_001 = new CheckedListBox();
        grpAllowedCurrencies = new GroupBox();
        tpNotes = new TabPage();
        txtNotes = new TextBox();
        ((System.ComponentModel.ISupportInitialize)dgvCurrencies).BeginInit();
        ((System.ComponentModel.ISupportInitialize)nudDecimalPlaces).BeginInit();
        mainLayout.SuspendLayout();
        pnlActions.SuspendLayout();
        tabMain.SuspendLayout();
        tabCurrencies.SuspendLayout();
        Currencies.SuspendLayout();
        CurrenciesFields.SuspendLayout();
        tabCurrencyRoles.SuspendLayout();
        rolesLayout.SuspendLayout();
        CurrencyRoles.SuspendLayout();
        grpAllowedCurrencies.SuspendLayout();
        tpNotes.SuspendLayout();
        SuspendLayout();
        mainLayout.Name = "mainLayout";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 3;
        mainLayout.Padding = new Padding(12);
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
        pnlActions.Name = "pnlActions";
        pnlActions.Dock = DockStyle.Fill;
        pnlActions.WrapContents = false;
        pnlActions.AutoScroll = true;
        pnlActions.FlowDirection = FlowDirection.LeftToRight;
        btnNew.Name = "btnNew";
        btnNew.Text = "جديد";
        btnNew.Size = new Size(112, 36);
        btnNew.Margin = new Padding(4);
        btnNew.Enabled = false;
        btnNew.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnNew);
        btnSave.Name = "btnSave";
        btnSave.Text = "حفظ";
        btnSave.Size = new Size(112, 36);
        btnSave.Margin = new Padding(4);
        btnSave.Enabled = false;
        btnSave.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnSave);
        btnEdit.Name = "btnEdit";
        btnEdit.Text = "تعديل";
        btnEdit.Size = new Size(112, 36);
        btnEdit.Margin = new Padding(4);
        btnEdit.Enabled = false;
        btnEdit.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnEdit);
        btnDelete.Name = "btnDelete";
        btnDelete.Text = "حذف";
        btnDelete.Size = new Size(112, 36);
        btnDelete.Margin = new Padding(4);
        btnDelete.Enabled = false;
        btnDelete.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnDelete);
        btnRefresh.Name = "btnRefresh";
        btnRefresh.Text = "تحديث";
        btnRefresh.Size = new Size(112, 36);
        btnRefresh.Margin = new Padding(4);
        btnRefresh.Enabled = false;
        btnRefresh.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnRefresh);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.Size = new Size(112, 36);
        btnClose.Margin = new Padding(4);
        btnClose.Enabled = true;
        btnClose.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnClose);
        btnClose.Click += BtnClose_Click;
        lblPreview.Name = "lblPreview";
        lblPreview.Text = "وضع المعاينة — التغييرات غير محفوظة";
        lblPreview.Dock = DockStyle.Fill;
        lblPreview.TextAlign = ContentAlignment.MiddleLeft;
        lblPreview.ForeColor = Color.DimGray;
        mainLayout.Controls.Add(pnlActions, 0, 0);
        mainLayout.Controls.Add(lblPreview, 0, 2);
        tabMain.Name = "tabMain";
        tabMain.Dock = DockStyle.Fill;
        tabMain.RightToLeftLayout = true;
        tabMain.SizeMode = TabSizeMode.Normal;
        mainLayout.Controls.Add(tabMain, 0, 1);
        tabCurrencies.Name = "tabCurrencies";
        tabCurrencies.Text = "تعريف العملات";
        tabCurrencies.Padding = new Padding(12);
        tabCurrencies.AutoScroll = true;
        tabCurrencies.BackColor = Color.White;
        tabMain.TabPages.Add(tabCurrencies);
        Currencies.Name = "Currencies";
        Currencies.Dock = DockStyle.Fill;
        Currencies.ColumnCount = 1;
        Currencies.RowCount = 2;
        Currencies.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        Currencies.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        Currencies.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        CurrenciesFields.Name = "CurrenciesFields";
        CurrenciesFields.Dock = DockStyle.Top;
        CurrenciesFields.AutoSize = true;
        CurrenciesFields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        CurrenciesFields.ColumnCount = 4;
        CurrenciesFields.RowCount = 3;
        CurrenciesFields.Padding = new Padding(4);
        CurrenciesFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        CurrenciesFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        CurrenciesFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        CurrenciesFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        CurrenciesFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        CurrenciesFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        CurrenciesFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        lbltxtCurrencyCode.Name = "lbltxtCurrencyCode";
        lbltxtCurrencyCode.Text = "رمز العملة *";
        lbltxtCurrencyCode.Dock = DockStyle.Fill;
        lbltxtCurrencyCode.TextAlign = ContentAlignment.MiddleLeft;
        lbltxtCurrencyCode.AutoSize = false;
        lbltxtCurrencyCode.TabStop = false;
        txtCurrencyCode.Name = "txtCurrencyCode";
        txtCurrencyCode.Dock = DockStyle.Fill;
        txtCurrencyCode.Margin = new Padding(6, 10, 12, 10);
        txtCurrencyCode.TabIndex = 0;
        txtCurrencyCode.AccessibleName = "رمز العملة";
        txtCurrencyCode.BackColor = Color.FromArgb(255, 250, 205);
        txtCurrencyCode.MaxLength = 12;
        txtCurrencyCode.CharacterCasing = CharacterCasing.Upper;
        CurrenciesFields.Controls.Add(lbltxtCurrencyCode, 0, 0);
        CurrenciesFields.Controls.Add(txtCurrencyCode, 1, 0);
        lbltxtCurrencyNameAr.Name = "lbltxtCurrencyNameAr";
        lbltxtCurrencyNameAr.Text = "اسم العملة بالعربي *";
        lbltxtCurrencyNameAr.Dock = DockStyle.Fill;
        lbltxtCurrencyNameAr.TextAlign = ContentAlignment.MiddleLeft;
        lbltxtCurrencyNameAr.AutoSize = false;
        lbltxtCurrencyNameAr.TabStop = false;
        txtCurrencyNameAr.Name = "txtCurrencyNameAr";
        txtCurrencyNameAr.Dock = DockStyle.Fill;
        txtCurrencyNameAr.Margin = new Padding(6, 10, 12, 10);
        txtCurrencyNameAr.TabIndex = 1;
        txtCurrencyNameAr.AccessibleName = "اسم العملة بالعربي";
        txtCurrencyNameAr.BackColor = Color.FromArgb(255, 250, 205);
        txtCurrencyNameAr.MaxLength = 100;
        CurrenciesFields.Controls.Add(lbltxtCurrencyNameAr, 2, 0);
        CurrenciesFields.Controls.Add(txtCurrencyNameAr, 3, 0);
        lbltxtCurrencyNameEn.Name = "lbltxtCurrencyNameEn";
        lbltxtCurrencyNameEn.Text = "اسم العملة بالإنجليزي";
        lbltxtCurrencyNameEn.Dock = DockStyle.Fill;
        lbltxtCurrencyNameEn.TextAlign = ContentAlignment.MiddleLeft;
        lbltxtCurrencyNameEn.AutoSize = false;
        lbltxtCurrencyNameEn.TabStop = false;
        txtCurrencyNameEn.Name = "txtCurrencyNameEn";
        txtCurrencyNameEn.Dock = DockStyle.Fill;
        txtCurrencyNameEn.Margin = new Padding(6, 10, 12, 10);
        txtCurrencyNameEn.TabIndex = 2;
        txtCurrencyNameEn.AccessibleName = "اسم العملة بالإنجليزي";
        txtCurrencyNameEn.MaxLength = 100;
        CurrenciesFields.Controls.Add(lbltxtCurrencyNameEn, 0, 1);
        CurrenciesFields.Controls.Add(txtCurrencyNameEn, 1, 1);
        lbltxtCurrencySymbol.Name = "lbltxtCurrencySymbol";
        lbltxtCurrencySymbol.Text = "رمز العرض";
        lbltxtCurrencySymbol.Dock = DockStyle.Fill;
        lbltxtCurrencySymbol.TextAlign = ContentAlignment.MiddleLeft;
        lbltxtCurrencySymbol.AutoSize = false;
        lbltxtCurrencySymbol.TabStop = false;
        txtCurrencySymbol.Name = "txtCurrencySymbol";
        txtCurrencySymbol.Dock = DockStyle.Fill;
        txtCurrencySymbol.Margin = new Padding(6, 10, 12, 10);
        txtCurrencySymbol.TabIndex = 3;
        txtCurrencySymbol.AccessibleName = "رمز العرض";
        txtCurrencySymbol.MaxLength = 12;
        CurrenciesFields.Controls.Add(lbltxtCurrencySymbol, 2, 1);
        CurrenciesFields.Controls.Add(txtCurrencySymbol, 3, 1);
        lblnudDecimalPlaces.Name = "lblnudDecimalPlaces";
        lblnudDecimalPlaces.Text = "المنازل العشرية *";
        lblnudDecimalPlaces.Dock = DockStyle.Fill;
        lblnudDecimalPlaces.TextAlign = ContentAlignment.MiddleLeft;
        lblnudDecimalPlaces.AutoSize = false;
        lblnudDecimalPlaces.TabStop = false;
        nudDecimalPlaces.Name = "nudDecimalPlaces";
        nudDecimalPlaces.Dock = DockStyle.Fill;
        nudDecimalPlaces.Margin = new Padding(6, 10, 12, 10);
        nudDecimalPlaces.TabIndex = 4;
        nudDecimalPlaces.AccessibleName = "المنازل العشرية";
        nudDecimalPlaces.BackColor = Color.FromArgb(255, 250, 205);
        nudDecimalPlaces.Minimum = 0M;
        nudDecimalPlaces.Maximum = 6M;
        nudDecimalPlaces.DecimalPlaces = 0;
        nudDecimalPlaces.Value = 2M;
        CurrenciesFields.Controls.Add(lblnudDecimalPlaces, 0, 2);
        CurrenciesFields.Controls.Add(nudDecimalPlaces, 1, 2);
        lblchkCurrencyActive.Name = "lblchkCurrencyActive";
        lblchkCurrencyActive.Text = "نشطة";
        lblchkCurrencyActive.Dock = DockStyle.Fill;
        lblchkCurrencyActive.TextAlign = ContentAlignment.MiddleLeft;
        lblchkCurrencyActive.AutoSize = false;
        lblchkCurrencyActive.TabStop = false;
        chkCurrencyActive.Name = "chkCurrencyActive";
        chkCurrencyActive.Dock = DockStyle.None;
        chkCurrencyActive.Margin = new Padding(6, 10, 12, 10);
        chkCurrencyActive.TabIndex = 5;
        chkCurrencyActive.AccessibleName = "نشطة";
        chkCurrencyActive.Text = "نشطة";
        chkCurrencyActive.AutoSize = true;
        CurrenciesFields.Controls.Add(lblchkCurrencyActive, 2, 2);
        CurrenciesFields.Controls.Add(chkCurrencyActive, 3, 2);
        Currencies.Controls.Add(CurrenciesFields);
        Currencies.SetCellPosition(CurrenciesFields, new TableLayoutPanelCellPosition(0, 0));
        dgvCurrencies.Name = "dgvCurrencies";
        dgvCurrencies.Dock = DockStyle.Fill;
        dgvCurrencies.BackgroundColor = Color.White;
        dgvCurrencies.BorderStyle = BorderStyle.FixedSingle;
        dgvCurrencies.AutoGenerateColumns = false;
        dgvCurrencies.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        dgvCurrencies.AllowUserToAddRows = false;
        dgvCurrencies.AllowUserToDeleteRows = false;
        dgvCurrencies.ReadOnly = true;
        dgvCurrencies.RowHeadersVisible = false;
        dgvCurrencies.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvCurrencies.MultiSelect = false;
        dgvCurrencies.MinimumSize = new Size(0, 160);
        dgvCurrencies.AccessibleName = "قائمة البيانات — لم يتم تحميل بيانات";
        dgvCurrenciesColCode.Name = "dgvCurrenciesColCode";
        dgvCurrenciesColCode.HeaderText = "رمز العملة";
        dgvCurrenciesColCode.MinimumWidth = 90;
        dgvCurrenciesColCode.FillWeight = 100F;
        dgvCurrenciesColCode.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvCurrencies.Columns.Add(dgvCurrenciesColCode);
        dgvCurrenciesColNameAr.Name = "dgvCurrenciesColNameAr";
        dgvCurrenciesColNameAr.HeaderText = "الاسم العربي";
        dgvCurrenciesColNameAr.MinimumWidth = 90;
        dgvCurrenciesColNameAr.FillWeight = 100F;
        dgvCurrenciesColNameAr.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvCurrencies.Columns.Add(dgvCurrenciesColNameAr);
        dgvCurrenciesColNameEn.Name = "dgvCurrenciesColNameEn";
        dgvCurrenciesColNameEn.HeaderText = "الاسم الإنجليزي";
        dgvCurrenciesColNameEn.MinimumWidth = 90;
        dgvCurrenciesColNameEn.FillWeight = 100F;
        dgvCurrenciesColNameEn.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvCurrencies.Columns.Add(dgvCurrenciesColNameEn);
        dgvCurrenciesColSymbol.Name = "dgvCurrenciesColSymbol";
        dgvCurrenciesColSymbol.HeaderText = "رمز العرض";
        dgvCurrenciesColSymbol.MinimumWidth = 90;
        dgvCurrenciesColSymbol.FillWeight = 100F;
        dgvCurrenciesColSymbol.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvCurrencies.Columns.Add(dgvCurrenciesColSymbol);
        dgvCurrenciesColDecimals.Name = "dgvCurrenciesColDecimals";
        dgvCurrenciesColDecimals.HeaderText = "المنازل العشرية";
        dgvCurrenciesColDecimals.MinimumWidth = 90;
        dgvCurrenciesColDecimals.FillWeight = 100F;
        dgvCurrenciesColDecimals.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvCurrencies.Columns.Add(dgvCurrenciesColDecimals);
        dgvCurrenciesColActive.Name = "dgvCurrenciesColActive";
        dgvCurrenciesColActive.HeaderText = "الحالة";
        dgvCurrenciesColActive.MinimumWidth = 90;
        dgvCurrenciesColActive.FillWeight = 100F;
        dgvCurrenciesColActive.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvCurrencies.Columns.Add(dgvCurrenciesColActive);
        Currencies.Controls.Add(dgvCurrencies);
        Currencies.SetCellPosition(dgvCurrencies, new TableLayoutPanelCellPosition(0, 1));
        tabCurrencies.Controls.Add(Currencies);
        tabCurrencyRoles.Name = "tabCurrencyRoles";
        tabCurrencyRoles.Text = "إعدادات عملات الشركة";
        tabCurrencyRoles.Padding = new Padding(12);
        tabCurrencyRoles.AutoScroll = true;
        tabCurrencyRoles.BackColor = Color.White;
        tabMain.TabPages.Add(tabCurrencyRoles);
        rolesLayout.Name = "rolesLayout";
        rolesLayout.Dock = DockStyle.Top;
        rolesLayout.AutoSize = true;
        rolesLayout.ColumnCount = 1;
        rolesLayout.RowCount = 2;
        rolesLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        rolesLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        rolesLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 180F));
        tabCurrencyRoles.Controls.Add(rolesLayout);
        CurrencyRoles.Name = "CurrencyRoles";
        CurrencyRoles.Dock = DockStyle.Top;
        CurrencyRoles.AutoSize = true;
        CurrencyRoles.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        CurrencyRoles.ColumnCount = 4;
        CurrencyRoles.RowCount = 2;
        CurrencyRoles.Padding = new Padding(4);
        CurrencyRoles.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        CurrencyRoles.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        CurrencyRoles.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        CurrencyRoles.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        CurrencyRoles.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        CurrencyRoles.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        lblcmbCompany.Name = "lblcmbCompany";
        lblcmbCompany.Text = "الشركة *";
        lblcmbCompany.Dock = DockStyle.Fill;
        lblcmbCompany.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbCompany.AutoSize = false;
        lblcmbCompany.TabStop = false;
        cmbCompany.Name = "cmbCompany";
        cmbCompany.Dock = DockStyle.Fill;
        cmbCompany.Margin = new Padding(6, 10, 12, 10);
        cmbCompany.TabIndex = 0;
        cmbCompany.AccessibleName = "الشركة";
        cmbCompany.BackColor = Color.FromArgb(255, 250, 205);
        cmbCompany.DropDownStyle = ComboBoxStyle.DropDownList;
        CurrencyRoles.Controls.Add(lblcmbCompany, 0, 0);
        CurrencyRoles.Controls.Add(cmbCompany, 1, 0);
        lblcmbAccountingCurrency.Name = "lblcmbAccountingCurrency";
        lblcmbAccountingCurrency.Text = "العملة المحاسبية *";
        lblcmbAccountingCurrency.Dock = DockStyle.Fill;
        lblcmbAccountingCurrency.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbAccountingCurrency.AutoSize = false;
        lblcmbAccountingCurrency.TabStop = false;
        cmbAccountingCurrency.Name = "cmbAccountingCurrency";
        cmbAccountingCurrency.Dock = DockStyle.Fill;
        cmbAccountingCurrency.Margin = new Padding(6, 10, 12, 10);
        cmbAccountingCurrency.TabIndex = 1;
        cmbAccountingCurrency.AccessibleName = "العملة المحاسبية";
        cmbAccountingCurrency.BackColor = Color.FromArgb(255, 250, 205);
        cmbAccountingCurrency.DropDownStyle = ComboBoxStyle.DropDownList;
        CurrencyRoles.Controls.Add(lblcmbAccountingCurrency, 2, 0);
        CurrencyRoles.Controls.Add(cmbAccountingCurrency, 3, 0);
        lblcmbReportingCurrency.Name = "lblcmbReportingCurrency";
        lblcmbReportingCurrency.Text = "عملة التقارير";
        lblcmbReportingCurrency.Dock = DockStyle.Fill;
        lblcmbReportingCurrency.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbReportingCurrency.AutoSize = false;
        lblcmbReportingCurrency.TabStop = false;
        cmbReportingCurrency.Name = "cmbReportingCurrency";
        cmbReportingCurrency.Dock = DockStyle.Fill;
        cmbReportingCurrency.Margin = new Padding(6, 10, 12, 10);
        cmbReportingCurrency.TabIndex = 2;
        cmbReportingCurrency.AccessibleName = "عملة التقارير";
        cmbReportingCurrency.DropDownStyle = ComboBoxStyle.DropDownList;
        CurrencyRoles.Controls.Add(lblcmbReportingCurrency, 0, 1);
        CurrencyRoles.Controls.Add(cmbReportingCurrency, 1, 1);
        lblcmbDefaultTransactionCurrency.Name = "lblcmbDefaultTransactionCurrency";
        lblcmbDefaultTransactionCurrency.Text = "عملة المعاملة الافتراضية";
        lblcmbDefaultTransactionCurrency.Dock = DockStyle.Fill;
        lblcmbDefaultTransactionCurrency.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbDefaultTransactionCurrency.AutoSize = false;
        lblcmbDefaultTransactionCurrency.TabStop = false;
        cmbDefaultTransactionCurrency.Name = "cmbDefaultTransactionCurrency";
        cmbDefaultTransactionCurrency.Dock = DockStyle.Fill;
        cmbDefaultTransactionCurrency.Margin = new Padding(6, 10, 12, 10);
        cmbDefaultTransactionCurrency.TabIndex = 3;
        cmbDefaultTransactionCurrency.AccessibleName = "عملة المعاملة الافتراضية";
        cmbDefaultTransactionCurrency.DropDownStyle = ComboBoxStyle.DropDownList;
        CurrencyRoles.Controls.Add(lblcmbDefaultTransactionCurrency, 2, 1);
        CurrencyRoles.Controls.Add(cmbDefaultTransactionCurrency, 3, 1);
        rolesLayout.Controls.Add(CurrencyRoles);
        SettingValue__SET_CUR_001.Name = "SettingValue__SET_CUR_001";
        SettingValue__SET_CUR_001.Dock = DockStyle.Fill;
        SettingValue__SET_CUR_001.CheckOnClick = true;
        SettingValue__SET_CUR_001.IntegralHeight = false;
        SettingValue__SET_CUR_001.AccessibleName = "العملات المسموح بها للشركة";
        SettingValue__SET_CUR_001.Items.AddRange(new object[] { "YER", "SAR", "USD" });
        grpAllowedCurrencies.Name = "grpAllowedCurrencies";
        grpAllowedCurrencies.Text = "العملات المسموح بها للشركة";
        grpAllowedCurrencies.Dock = DockStyle.Fill;
        grpAllowedCurrencies.Padding = new Padding(12);
        grpAllowedCurrencies.Controls.Add(SettingValue__SET_CUR_001);
        rolesLayout.SetCellPosition(CurrencyRoles, new TableLayoutPanelCellPosition(0, 0));
        rolesLayout.Controls.Add(grpAllowedCurrencies, 0, 1);
        tpNotes.Name = "tpNotes";
        tpNotes.Text = "الملاحظات";
        tpNotes.Padding = new Padding(12);
        tpNotes.AutoScroll = true;
        tpNotes.BackColor = Color.White;
        tabMain.TabPages.Add(tpNotes);
        txtNotes.Name = "txtNotes";
        txtNotes.Dock = DockStyle.Fill;
        txtNotes.Multiline = true;
        txtNotes.ScrollBars = ScrollBars.Vertical;
        txtNotes.MaxLength = 4000;
        txtNotes.AccessibleName = "الملاحظات";
        tpNotes.Controls.Add(txtNotes);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 10F);
        BackColor = Color.White;
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1120, 720);
        MinimumSize = new Size(936, 600);
        Name = "UcCurrencyManagement";
        Text = "إدارة العملات";
        Tag = "02.04.02";
        Controls.Add(mainLayout);
        tpNotes.ResumeLayout(false);
        tpNotes.PerformLayout();
        grpAllowedCurrencies.ResumeLayout(false);
        grpAllowedCurrencies.PerformLayout();
        CurrencyRoles.ResumeLayout(false);
        CurrencyRoles.PerformLayout();
        rolesLayout.ResumeLayout(false);
        rolesLayout.PerformLayout();
        tabCurrencyRoles.ResumeLayout(false);
        tabCurrencyRoles.PerformLayout();
        CurrenciesFields.ResumeLayout(false);
        CurrenciesFields.PerformLayout();
        Currencies.ResumeLayout(false);
        Currencies.PerformLayout();
        tabCurrencies.ResumeLayout(false);
        tabCurrencies.PerformLayout();
        tabMain.ResumeLayout(false);
        tabMain.PerformLayout();
        pnlActions.ResumeLayout(false);
        pnlActions.PerformLayout();
        mainLayout.ResumeLayout(false);
        mainLayout.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)nudDecimalPlaces).EndInit();
        ((System.ComponentModel.ISupportInitialize)dgvCurrencies).EndInit();
        ResumeLayout(false);
    }

    private TableLayoutPanel mainLayout = null!;
    private FlowLayoutPanel pnlActions = null!;
    private Button btnNew = null!;
    private Button btnSave = null!;
    private Button btnEdit = null!;
    private Button btnDelete = null!;
    private Button btnRefresh = null!;
    private Button btnClose = null!;
    private Label lblPreview = null!;
    private TabControl tabMain = null!;
    private TabPage tabCurrencies = null!;
    private TableLayoutPanel Currencies = null!;
    private TableLayoutPanel CurrenciesFields = null!;
    private Label lbltxtCurrencyCode = null!;
    private TextBox txtCurrencyCode = null!;
    private Label lbltxtCurrencyNameAr = null!;
    private TextBox txtCurrencyNameAr = null!;
    private Label lbltxtCurrencyNameEn = null!;
    private TextBox txtCurrencyNameEn = null!;
    private Label lbltxtCurrencySymbol = null!;
    private TextBox txtCurrencySymbol = null!;
    private Label lblnudDecimalPlaces = null!;
    private NumericUpDown nudDecimalPlaces = null!;
    private Label lblchkCurrencyActive = null!;
    private CheckBox chkCurrencyActive = null!;
    private DataGridView dgvCurrencies = null!;
    private DataGridViewTextBoxColumn dgvCurrenciesColCode = null!;
    private DataGridViewTextBoxColumn dgvCurrenciesColNameAr = null!;
    private DataGridViewTextBoxColumn dgvCurrenciesColNameEn = null!;
    private DataGridViewTextBoxColumn dgvCurrenciesColSymbol = null!;
    private DataGridViewTextBoxColumn dgvCurrenciesColDecimals = null!;
    private DataGridViewTextBoxColumn dgvCurrenciesColActive = null!;
    private TabPage tabCurrencyRoles = null!;
    private TableLayoutPanel rolesLayout = null!;
    private TableLayoutPanel CurrencyRoles = null!;
    private Label lblcmbCompany = null!;
    private ComboBox cmbCompany = null!;
    private Label lblcmbAccountingCurrency = null!;
    private ComboBox cmbAccountingCurrency = null!;
    private Label lblcmbReportingCurrency = null!;
    private ComboBox cmbReportingCurrency = null!;
    private Label lblcmbDefaultTransactionCurrency = null!;
    private ComboBox cmbDefaultTransactionCurrency = null!;
    private CheckedListBox SettingValue__SET_CUR_001 = null!;
    private GroupBox grpAllowedCurrencies = null!;
    private TabPage tpNotes = null!;
    private TextBox txtNotes = null!;
}
