using System.Drawing;
using System.Windows.Forms;

namespace TransportERP.Desktop.Forms.SystemSettings.General;

partial class UcExchangeRates
{
    private System.ComponentModel.IContainer? components;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        mainLayout = new TableLayoutPanel();
        pnlActions = new FlowLayoutPanel();
        btnNew = new Button();
        btnSave = new Button();
        btnEdit = new Button();
        btnDelete = new Button();
        btnRefresh = new Button();
        btnClose = new Button();
        lblPreview = new Label();
        tabMain = new TabControl();
        tpRates = new TabPage();
        Rates = new TableLayoutPanel();
        RatesFields = new TableLayoutPanel();
        lblcmbCompany = new Label();
        cmbCompany = new ComboBox();
        lblcmbBranch = new Label();
        cmbBranch = new ComboBox();
        lblcmbFromCurrency = new Label();
        cmbFromCurrency = new ComboBox();
        lblcmbToCurrency = new Label();
        cmbToCurrency = new ComboBox();
        lblcmbRateType = new Label();
        cmbRateType = new ComboBox();
        lbldtpRateDate = new Label();
        dtpRateDate = new DateTimePicker();
        lblnudExchangeRate = new Label();
        nudExchangeRate = new NumericUpDown();
        lblcmbRateSource = new Label();
        cmbRateSource = new ComboBox();
        dgvRates = new DataGridView();
        dgvRatesColFrom = new DataGridViewTextBoxColumn();
        dgvRatesColTo = new DataGridViewTextBoxColumn();
        dgvRatesColType = new DataGridViewTextBoxColumn();
        dgvRatesColDate = new DataGridViewTextBoxColumn();
        dgvRatesColValue = new DataGridViewTextBoxColumn();
        dgvRatesColBranch = new DataGridViewTextBoxColumn();
        lblRateConvention = new Label();
        tpNotes = new TabPage();
        txtNotes = new TextBox();
        ((System.ComponentModel.ISupportInitialize)dgvRates).BeginInit();
        ((System.ComponentModel.ISupportInitialize)nudExchangeRate).BeginInit();
        mainLayout.SuspendLayout();
        pnlActions.SuspendLayout();
        tabMain.SuspendLayout();
        tpRates.SuspendLayout();
        Rates.SuspendLayout();
        RatesFields.SuspendLayout();
        tpNotes.SuspendLayout();
        SuspendLayout();
        mainLayout.Name = "mainLayout";
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.ColumnCount = 1;
        mainLayout.RowCount = 3;
        mainLayout.Padding = new Padding(12);
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
        pnlActions.Name = "pnlActions";
        pnlActions.Dock = DockStyle.Fill;
        pnlActions.WrapContents = false;
        pnlActions.AutoScroll = true;
        pnlActions.FlowDirection = FlowDirection.LeftToRight;
        btnNew.Name = "btnNew";
        btnNew.Text = "جديد";
        btnNew.Size = new Size(112, 36);
        btnNew.Margin = new Padding(4);
        btnNew.Enabled = false;
        btnNew.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnNew);
        btnSave.Name = "btnSave";
        btnSave.Text = "حفظ";
        btnSave.Size = new Size(112, 36);
        btnSave.Margin = new Padding(4);
        btnSave.Enabled = false;
        btnSave.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnSave);
        btnEdit.Name = "btnEdit";
        btnEdit.Text = "تعديل";
        btnEdit.Size = new Size(112, 36);
        btnEdit.Margin = new Padding(4);
        btnEdit.Enabled = false;
        btnEdit.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnEdit);
        btnDelete.Name = "btnDelete";
        btnDelete.Text = "حذف";
        btnDelete.Size = new Size(112, 36);
        btnDelete.Margin = new Padding(4);
        btnDelete.Enabled = false;
        btnDelete.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnDelete);
        btnRefresh.Name = "btnRefresh";
        btnRefresh.Text = "تحديث";
        btnRefresh.Size = new Size(112, 36);
        btnRefresh.Margin = new Padding(4);
        btnRefresh.Enabled = false;
        btnRefresh.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnRefresh);
        btnClose.Name = "btnClose";
        btnClose.Text = "إغلاق";
        btnClose.Size = new Size(112, 36);
        btnClose.Margin = new Padding(4);
        btnClose.Enabled = true;
        btnClose.UseVisualStyleBackColor = true;
        pnlActions.Controls.Add(btnClose);
        btnClose.Click += BtnClose_Click;
        lblPreview.Name = "lblPreview";
        lblPreview.Text = "وضع المعاينة — التغييرات غير محفوظة";
        lblPreview.Dock = DockStyle.Fill;
        lblPreview.TextAlign = ContentAlignment.MiddleLeft;
        lblPreview.ForeColor = Color.DimGray;
        mainLayout.Controls.Add(pnlActions, 0, 0);
        mainLayout.Controls.Add(lblPreview, 0, 2);
        tabMain.Name = "tabMain";
        tabMain.Dock = DockStyle.Fill;
        tabMain.RightToLeftLayout = true;
        tabMain.SizeMode = TabSizeMode.Normal;
        mainLayout.Controls.Add(tabMain, 0, 1);
        tpRates.Name = "tpRates";
        tpRates.Text = "أسعار الصرف";
        tpRates.Padding = new Padding(12);
        tpRates.AutoScroll = true;
        tpRates.BackColor = Color.White;
        tabMain.TabPages.Add(tpRates);
        Rates.Name = "Rates";
        Rates.Dock = DockStyle.Fill;
        Rates.ColumnCount = 1;
        Rates.RowCount = 2;
        Rates.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        Rates.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        Rates.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        RatesFields.Name = "RatesFields";
        RatesFields.Dock = DockStyle.Top;
        RatesFields.AutoSize = true;
        RatesFields.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        RatesFields.ColumnCount = 4;
        RatesFields.RowCount = 4;
        RatesFields.Padding = new Padding(4);
        RatesFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        RatesFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        RatesFields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        RatesFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50.0F));
        RatesFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        RatesFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        RatesFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        RatesFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
        lblcmbCompany.Name = "lblcmbCompany";
        lblcmbCompany.Text = "الشركة *";
        lblcmbCompany.Dock = DockStyle.Fill;
        lblcmbCompany.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbCompany.AutoSize = false;
        lblcmbCompany.TabStop = false;
        cmbCompany.Name = "cmbCompany";
        cmbCompany.Dock = DockStyle.Fill;
        cmbCompany.Margin = new Padding(6, 10, 12, 10);
        cmbCompany.TabIndex = 0;
        cmbCompany.AccessibleName = "الشركة";
        cmbCompany.BackColor = Color.FromArgb(255, 250, 205);
        cmbCompany.DropDownStyle = ComboBoxStyle.DropDownList;
        RatesFields.Controls.Add(lblcmbCompany, 0, 0);
        RatesFields.Controls.Add(cmbCompany, 1, 0);
        lblcmbBranch.Name = "lblcmbBranch";
        lblcmbBranch.Text = "نطاق الفرع";
        lblcmbBranch.Dock = DockStyle.Fill;
        lblcmbBranch.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbBranch.AutoSize = false;
        lblcmbBranch.TabStop = false;
        cmbBranch.Name = "cmbBranch";
        cmbBranch.Dock = DockStyle.Fill;
        cmbBranch.Margin = new Padding(6, 10, 12, 10);
        cmbBranch.TabIndex = 1;
        cmbBranch.AccessibleName = "نطاق الفرع";
        cmbBranch.DropDownStyle = ComboBoxStyle.DropDownList;
        RatesFields.Controls.Add(lblcmbBranch, 2, 0);
        RatesFields.Controls.Add(cmbBranch, 3, 0);
        lblcmbFromCurrency.Name = "lblcmbFromCurrency";
        lblcmbFromCurrency.Text = "من عملة *";
        lblcmbFromCurrency.Dock = DockStyle.Fill;
        lblcmbFromCurrency.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbFromCurrency.AutoSize = false;
        lblcmbFromCurrency.TabStop = false;
        cmbFromCurrency.Name = "cmbFromCurrency";
        cmbFromCurrency.Dock = DockStyle.Fill;
        cmbFromCurrency.Margin = new Padding(6, 10, 12, 10);
        cmbFromCurrency.TabIndex = 2;
        cmbFromCurrency.AccessibleName = "من عملة";
        cmbFromCurrency.BackColor = Color.FromArgb(255, 250, 205);
        cmbFromCurrency.DropDownStyle = ComboBoxStyle.DropDownList;
        RatesFields.Controls.Add(lblcmbFromCurrency, 0, 1);
        RatesFields.Controls.Add(cmbFromCurrency, 1, 1);
        lblcmbToCurrency.Name = "lblcmbToCurrency";
        lblcmbToCurrency.Text = "إلى عملة *";
        lblcmbToCurrency.Dock = DockStyle.Fill;
        lblcmbToCurrency.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbToCurrency.AutoSize = false;
        lblcmbToCurrency.TabStop = false;
        cmbToCurrency.Name = "cmbToCurrency";
        cmbToCurrency.Dock = DockStyle.Fill;
        cmbToCurrency.Margin = new Padding(6, 10, 12, 10);
        cmbToCurrency.TabIndex = 3;
        cmbToCurrency.AccessibleName = "إلى عملة";
        cmbToCurrency.BackColor = Color.FromArgb(255, 250, 205);
        cmbToCurrency.DropDownStyle = ComboBoxStyle.DropDownList;
        RatesFields.Controls.Add(lblcmbToCurrency, 2, 1);
        RatesFields.Controls.Add(cmbToCurrency, 3, 1);
        lblcmbRateType.Name = "lblcmbRateType";
        lblcmbRateType.Text = "نوع السعر *";
        lblcmbRateType.Dock = DockStyle.Fill;
        lblcmbRateType.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbRateType.AutoSize = false;
        lblcmbRateType.TabStop = false;
        cmbRateType.Name = "cmbRateType";
        cmbRateType.Dock = DockStyle.Fill;
        cmbRateType.Margin = new Padding(6, 10, 12, 10);
        cmbRateType.TabIndex = 4;
        cmbRateType.AccessibleName = "نوع السعر";
        cmbRateType.BackColor = Color.FromArgb(255, 250, 205);
        cmbRateType.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbRateType.Items.AddRange(new object[] { "تشغيلي", "محاسبي" });
        RatesFields.Controls.Add(lblcmbRateType, 0, 2);
        RatesFields.Controls.Add(cmbRateType, 1, 2);
        lbldtpRateDate.Name = "lbldtpRateDate";
        lbldtpRateDate.Text = "تاريخ السريان *";
        lbldtpRateDate.Dock = DockStyle.Fill;
        lbldtpRateDate.TextAlign = ContentAlignment.MiddleLeft;
        lbldtpRateDate.AutoSize = false;
        lbldtpRateDate.TabStop = false;
        dtpRateDate.Name = "dtpRateDate";
        dtpRateDate.Dock = DockStyle.Fill;
        dtpRateDate.Margin = new Padding(6, 10, 12, 10);
        dtpRateDate.TabIndex = 5;
        dtpRateDate.AccessibleName = "تاريخ السريان";
        dtpRateDate.BackColor = Color.FromArgb(255, 250, 205);
        dtpRateDate.Format = DateTimePickerFormat.Custom;
        dtpRateDate.CustomFormat = "yyyy/MM/dd";
        dtpRateDate.ShowCheckBox = true;
        dtpRateDate.Checked = false;
        RatesFields.Controls.Add(lbldtpRateDate, 2, 2);
        RatesFields.Controls.Add(dtpRateDate, 3, 2);
        lblnudExchangeRate.Name = "lblnudExchangeRate";
        lblnudExchangeRate.Text = "سعر الصرف *";
        lblnudExchangeRate.Dock = DockStyle.Fill;
        lblnudExchangeRate.TextAlign = ContentAlignment.MiddleLeft;
        lblnudExchangeRate.AutoSize = false;
        lblnudExchangeRate.TabStop = false;
        nudExchangeRate.Name = "nudExchangeRate";
        nudExchangeRate.Dock = DockStyle.Fill;
        nudExchangeRate.Margin = new Padding(6, 10, 12, 10);
        nudExchangeRate.TabIndex = 6;
        nudExchangeRate.AccessibleName = "سعر الصرف";
        nudExchangeRate.BackColor = Color.FromArgb(255, 250, 205);
        nudExchangeRate.Minimum = 0.00000001M;
        nudExchangeRate.Maximum = 999999999M;
        nudExchangeRate.DecimalPlaces = 8;
        nudExchangeRate.Value = 1M;
        RatesFields.Controls.Add(lblnudExchangeRate, 0, 3);
        RatesFields.Controls.Add(nudExchangeRate, 1, 3);
        lblcmbRateSource.Name = "lblcmbRateSource";
        lblcmbRateSource.Text = "مصدر سعر الصرف *";
        lblcmbRateSource.Dock = DockStyle.Fill;
        lblcmbRateSource.TextAlign = ContentAlignment.MiddleLeft;
        lblcmbRateSource.AutoSize = false;
        lblcmbRateSource.TabStop = false;
        cmbRateSource.Name = "cmbRateSource";
        cmbRateSource.Dock = DockStyle.Fill;
        cmbRateSource.Margin = new Padding(6, 10, 12, 10);
        cmbRateSource.TabIndex = 7;
        cmbRateSource.AccessibleName = "مصدر سعر الصرف";
        cmbRateSource.BackColor = Color.FromArgb(255, 250, 205);
        cmbRateSource.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbRateSource.Items.AddRange(new object[] { "إدخال يدوي مخول", "مزود أسعار" });
        RatesFields.Controls.Add(lblcmbRateSource, 2, 3);
        RatesFields.Controls.Add(cmbRateSource, 3, 3);
        Rates.Controls.Add(RatesFields);
        Rates.SetCellPosition(RatesFields, new TableLayoutPanelCellPosition(0, 0));
        dgvRates.Name = "dgvRates";
        dgvRates.Dock = DockStyle.Fill;
        dgvRates.BackgroundColor = Color.White;
        dgvRates.BorderStyle = BorderStyle.FixedSingle;
        dgvRates.AutoGenerateColumns = false;
        dgvRates.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        dgvRates.AllowUserToAddRows = false;
        dgvRates.AllowUserToDeleteRows = false;
        dgvRates.ReadOnly = true;
        dgvRates.RowHeadersVisible = false;
        dgvRates.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvRates.MultiSelect = false;
        dgvRates.MinimumSize = new Size(0, 160);
        dgvRates.AccessibleName = "قائمة البيانات — لم يتم تحميل بيانات";
        dgvRatesColFrom.Name = "dgvRatesColFrom";
        dgvRatesColFrom.HeaderText = "من عملة";
        dgvRatesColFrom.MinimumWidth = 90;
        dgvRatesColFrom.FillWeight = 100F;
        dgvRatesColFrom.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRates.Columns.Add(dgvRatesColFrom);
        dgvRatesColTo.Name = "dgvRatesColTo";
        dgvRatesColTo.HeaderText = "إلى عملة";
        dgvRatesColTo.MinimumWidth = 90;
        dgvRatesColTo.FillWeight = 100F;
        dgvRatesColTo.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRates.Columns.Add(dgvRatesColTo);
        dgvRatesColType.Name = "dgvRatesColType";
        dgvRatesColType.HeaderText = "نوع السعر";
        dgvRatesColType.MinimumWidth = 90;
        dgvRatesColType.FillWeight = 100F;
        dgvRatesColType.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRates.Columns.Add(dgvRatesColType);
        dgvRatesColDate.Name = "dgvRatesColDate";
        dgvRatesColDate.HeaderText = "تاريخ السريان";
        dgvRatesColDate.MinimumWidth = 90;
        dgvRatesColDate.FillWeight = 100F;
        dgvRatesColDate.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRates.Columns.Add(dgvRatesColDate);
        dgvRatesColValue.Name = "dgvRatesColValue";
        dgvRatesColValue.HeaderText = "سعر الصرف";
        dgvRatesColValue.MinimumWidth = 90;
        dgvRatesColValue.FillWeight = 100F;
        dgvRatesColValue.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRates.Columns.Add(dgvRatesColValue);
        dgvRatesColBranch.Name = "dgvRatesColBranch";
        dgvRatesColBranch.HeaderText = "نطاق الفرع";
        dgvRatesColBranch.MinimumWidth = 90;
        dgvRatesColBranch.FillWeight = 100F;
        dgvRatesColBranch.SortMode = DataGridViewColumnSortMode.NotSortable;
        dgvRates.Columns.Add(dgvRatesColBranch);
        Rates.Controls.Add(dgvRates);
        Rates.SetCellPosition(dgvRates, new TableLayoutPanelCellPosition(0, 1));
        tpRates.Controls.Add(Rates);
        lblRateConvention.Name = "lblRateConvention";
        lblRateConvention.Text = "الاتجاه: وحدة واحدة من العملة المصدر = سعر الصرف من العملة الهدف";
        lblRateConvention.Dock = DockStyle.Bottom;
        lblRateConvention.Height = 32;
        lblRateConvention.TextAlign = ContentAlignment.MiddleLeft;
        tpRates.Controls.Add(lblRateConvention);
        tpNotes.Name = "tpNotes";
        tpNotes.Text = "الملاحظات";
        tpNotes.Padding = new Padding(12);
        tpNotes.AutoScroll = true;
        tpNotes.BackColor = Color.White;
        tabMain.TabPages.Add(tpNotes);
        txtNotes.Name = "txtNotes";
        txtNotes.Dock = DockStyle.Fill;
        txtNotes.Multiline = true;
        txtNotes.ScrollBars = ScrollBars.Vertical;
        txtNotes.MaxLength = 4000;
        txtNotes.AccessibleName = "الملاحظات";
        tpNotes.Controls.Add(txtNotes);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Segoe UI", 10F);
        BackColor = Color.White;
        RightToLeft = RightToLeft.Yes;
        Size = new Size(1120, 720);
        MinimumSize = new Size(936, 600);
        Name = "UcExchangeRates";
        Text = "أسعار الصرف";
        Tag = "02.04.03";
        Controls.Add(mainLayout);
        tpNotes.ResumeLayout(false);
        tpNotes.PerformLayout();
        RatesFields.ResumeLayout(false);
        RatesFields.PerformLayout();
        Rates.ResumeLayout(false);
        Rates.PerformLayout();
        tpRates.ResumeLayout(false);
        tpRates.PerformLayout();
        tabMain.ResumeLayout(false);
        tabMain.PerformLayout();
        pnlActions.ResumeLayout(false);
        pnlActions.PerformLayout();
        mainLayout.ResumeLayout(false);
        mainLayout.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)nudExchangeRate).EndInit();
        ((System.ComponentModel.ISupportInitialize)dgvRates).EndInit();
        ResumeLayout(false);
    }

    private TableLayoutPanel mainLayout = null!;
    private FlowLayoutPanel pnlActions = null!;
    private Button btnNew = null!;
    private Button btnSave = null!;
    private Button btnEdit = null!;
    private Button btnDelete = null!;
    private Button btnRefresh = null!;
    private Button btnClose = null!;
    private Label lblPreview = null!;
    private TabControl tabMain = null!;
    private TabPage tpRates = null!;
    private TableLayoutPanel Rates = null!;
    private TableLayoutPanel RatesFields = null!;
    private Label lblcmbCompany = null!;
    private ComboBox cmbCompany = null!;
    private Label lblcmbBranch = null!;
    private ComboBox cmbBranch = null!;
    private Label lblcmbFromCurrency = null!;
    private ComboBox cmbFromCurrency = null!;
    private Label lblcmbToCurrency = null!;
    private ComboBox cmbToCurrency = null!;
    private Label lblcmbRateType = null!;
    private ComboBox cmbRateType = null!;
    private Label lbldtpRateDate = null!;
    private DateTimePicker dtpRateDate = null!;
    private Label lblnudExchangeRate = null!;
    private NumericUpDown nudExchangeRate = null!;
    private Label lblcmbRateSource = null!;
    private ComboBox cmbRateSource = null!;
    private DataGridView dgvRates = null!;
    private DataGridViewTextBoxColumn dgvRatesColFrom = null!;
    private DataGridViewTextBoxColumn dgvRatesColTo = null!;
    private DataGridViewTextBoxColumn dgvRatesColType = null!;
    private DataGridViewTextBoxColumn dgvRatesColDate = null!;
    private DataGridViewTextBoxColumn dgvRatesColValue = null!;
    private DataGridViewTextBoxColumn dgvRatesColBranch = null!;
    private Label lblRateConvention = null!;
    private TabPage tpNotes = null!;
    private TextBox txtNotes = null!;
}
