namespace TransportERP.Desktop.Forms.SystemSettings.General;
partial class UcProjectData
{
    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private FlowLayoutPanel standardCommandFlow = null!;
    private Panel standardCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandView = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandSave = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandClose = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel layout = null!;
    private TableLayoutPanel fields = null!;
    private Label lblTitle = null!;
    private Label lblStatus = null!;
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;
    private Label lbltxtProjectNumber = null!;
    private TextBox txtProjectNumber = null!;
    private Label lbltxtParentProject = null!;
    private TextBox txtParentProject = null!;
    private Label lbltxtNameLocal = null!;
    private TextBox txtNameLocal = null!;
    private Label lbltxtNameForeign = null!;
    private TextBox txtNameForeign = null!;
    private Label lbltxtRank = null!;
    private TextBox txtRank = null!;
    private Label lblcboProjectType = null!;
    private ComboBox cboProjectType = null!;
    private Label lblcboProjectGroup = null!;
    private ComboBox cboProjectGroup = null!;
    private Label lbltxtStartDate = null!;
    private TextBox txtStartDate = null!;
    private Label lbltxtEndDate = null!;
    private TextBox txtEndDate = null!;
    private Label lbltxtAddress = null!;
    private TextBox txtAddress = null!;
    private Label lblchkStopped = null!;
    private CheckBox chkStopped = null!;
    private Label lbltxtStopReason = null!;
    private TextBox txtStopReason = null!;
    private Label lbltxtStoppedAt = null!;
    private TextBox txtStoppedAt = null!;
    private Label lblcboCurrency = null!;
    private ComboBox cboCurrency = null!;
    private Label lbltxtExchangeRate = null!;
    private TextBox txtExchangeRate = null!;
    private Label lbltxtEstimatedValue = null!;
    private TextBox txtEstimatedValue = null!;
    private Label lblcboProjectPolicy = null!;
    private ComboBox cboProjectPolicy = null!;
    private Label lbltxtProjectStatus = null!;
    private TextBox txtProjectStatus = null!;
    private Label lbltxtTenderDate = null!;
    private TextBox txtTenderDate = null!;
    private Label lbltxtContractDate = null!;
    private TextBox txtContractDate = null!;
    private Label lblcboCostPreparation = null!;
    private ComboBox cboCostPreparation = null!;
    private Label lblcboCountry = null!;
    private ComboBox cboCountry = null!;
    private Label lblcboGovernorate = null!;
    private ComboBox cboGovernorate = null!;
    private Label lblcboCity = null!;
    private ComboBox cboCity = null!;
    private Label lblcboArea = null!;
    private ComboBox cboArea = null!;
    private Label lblcboProjectManager = null!;
    private ComboBox cboProjectManager = null!;
    private Label lblcboGeneralConsultant = null!;
    private ComboBox cboGeneralConsultant = null!;
    private Label lblcboSpecialistConsultant = null!;
    private ComboBox cboSpecialistConsultant = null!;
    private Label lbltxtNotes = null!;
    private TextBox txtNotes = null!;
    private TabControl tabsFields = null!;
    private TabPage sectionPage0 = null!;
    private TableLayoutPanel sectionFields0 = null!;
    private TabPage sectionPage1 = null!;
    private TableLayoutPanel sectionFields1 = null!;
    private TabPage sectionPage2 = null!;
    private TableLayoutPanel sectionFields2 = null!;
    private Button btnUseCenters = null!;
    private Button btnUseActivities = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        standardCommandFlow = new FlowLayoutPanel();
        standardCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandView = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandSave = new Button();
        standardCommandPrint = new Button();
        standardCommandClose = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.Size = new Size(1000, 44);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Margin = Padding.Empty;
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        standardCommandFlow.Name = "pnlToolbar";
        standardCommandFlow.Dock = DockStyle.Fill;
        standardCommandFlow.FlowDirection = FlowDirection.RightToLeft;
        standardCommandFlow.RightToLeft = RightToLeft.No;
        standardCommandFlow.WrapContents = false;
        standardCommandFlow.Padding = new Padding(2);
        standardCloseHost.Name = "standardCloseHost";
        standardCloseHost.Dock = DockStyle.Left;
        standardCloseHost.Width = 28;
        designerCommandBar.Controls.Add(standardCommandFlow);
        designerCommandBar.Controls.Add(standardCloseHost);
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = true;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.TabIndex = 0;
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandFlow.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = true;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.TabIndex = 1;
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandFlow.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.TabIndex = 2;
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandFlow.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.TabIndex = 3;
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandFlow.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        standardCommandView.Name = "standardCommandView";
        standardCommandView.AccessibleName = "عرض";
        standardCommandView.Enabled = false;
        standardCommandView.Visible = true;
        standardCommandView.Size = new Size(26, 24);
        standardCommandView.Margin = new Padding(1);
        standardCommandView.FlatStyle = FlatStyle.Flat;
        standardCommandView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandView.TabIndex = 4;
        standardCommandView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        standardCommandFlow.Controls.Add(standardCommandView);
        designerCommandBar.SetCommandRole(standardCommandView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.TabIndex = 5;
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandFlow.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.AccessibleName = "التالي";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.TabIndex = 6;
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandFlow.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.TabIndex = 7;
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandFlow.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.TabIndex = 8;
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFlow.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        standardCommandSave.Name = "btnSave";
        standardCommandSave.AccessibleName = "حفظ";
        standardCommandSave.Enabled = false;
        standardCommandSave.Visible = true;
        standardCommandSave.Size = new Size(26, 24);
        standardCommandSave.Margin = new Padding(1);
        standardCommandSave.FlatStyle = FlatStyle.Flat;
        standardCommandSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandSave.TabIndex = 9;
        standardCommandSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        standardCommandFlow.Controls.Add(standardCommandSave);
        designerCommandBar.SetCommandRole(standardCommandSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.TabIndex = 10;
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandFlow.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        standardCommandClose.Name = "standardCommandClose";
        standardCommandClose.AccessibleName = "إغلاق";
        standardCommandClose.Enabled = false;
        standardCommandClose.Visible = true;
        standardCommandClose.Size = new Size(26, 24);
        standardCommandClose.Margin = new Padding(1);
        standardCommandClose.FlatStyle = FlatStyle.Flat;
        standardCommandClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandClose.TabIndex = 11;
        standardCommandClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        standardCloseHost.Controls.Add(standardCommandClose);
        designerCommandBar.SetCommandRole(standardCommandClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.TabIndex = 12;
        standardCommandRefresh.Text = "تحديث";
        standardCommandFlow.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.TabIndex = 13;
        standardCommandImport.Text = "استيراد";
        standardCommandFlow.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.TabIndex = 14;
        standardCommandExport.Text = "تصدير";
        standardCommandFlow.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.TabIndex = 15;
        standardCommandHelp.Text = "مساعدة";
        standardCommandFlow.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
        standardCommandClose.Location = new Point(1, 1);
        standardCommandSave.AccessibleDescription = "الحفظ غير متاح؛ لم تُربط الشاشة بخدمة بيانات.";
        Controls.Add(designerCommandBar);

        layout = new TableLayoutPanel();
        fields = new TableLayoutPanel();
        lblTitle = new Label();
        lblStatus = new Label();
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        layout.SuspendLayout();
        fields.SuspendLayout();
        layout.Name = "layout";
        layout.Dock = DockStyle.Top;
        layout.AutoSize = true;
        layout.ColumnCount = 1;
        layout.RowCount = 4;
        layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "بيانات المشاريع";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Font = new Font("Segoe UI", 16F);
        lblTitle.TextAlign = ContentAlignment.MiddleRight;
        lblTitle.BackColor = Color.FromArgb(192, 192, 255);
        lblTitle.Padding = new Padding(12);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "معاينة إدخال مؤقتة — الحفظ والترقيم التلقائي والقوائم غير متاحة؛ القيم لا تُطبّق على النظام.";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.TextAlign = ContentAlignment.MiddleRight;
        lblStatus.Padding = new Padding(8);
        fields.Name = "fields";
        fields.Dock = DockStyle.Top;
        fields.AutoSize = true;
        fields.ColumnCount = 2;
        fields.RowCount = 29;
        fields.Enabled = false;
        fields.TabIndex = 1;
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
        lbltxtProjectNumber = new Label();
        lbltxtProjectNumber.Name = "lbltxtProjectNumber";
        lbltxtProjectNumber.Text = "رقم المشروع";
        lbltxtProjectNumber.AutoSize = true;
        lbltxtProjectNumber.Dock = DockStyle.Fill;
        lbltxtProjectNumber.TextAlign = ContentAlignment.MiddleRight;
        lbltxtProjectNumber.Margin = new Padding(6, 8, 6, 8);
        txtProjectNumber = new TextBox();
        txtProjectNumber.Name = "txtProjectNumber";
        txtProjectNumber.AccessibleName = "رقم المشروع";
        txtProjectNumber.Dock = DockStyle.Fill;
        txtProjectNumber.TabIndex = 0;
        txtProjectNumber.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtProjectNumber, 0, 0);
        fields.Controls.Add(txtProjectNumber, 1, 0);
        lbltxtParentProject = new Label();
        lbltxtParentProject.Name = "lbltxtParentProject";
        lbltxtParentProject.Text = "المشروع الرئيسي";
        lbltxtParentProject.AutoSize = true;
        lbltxtParentProject.Dock = DockStyle.Fill;
        lbltxtParentProject.TextAlign = ContentAlignment.MiddleRight;
        lbltxtParentProject.Margin = new Padding(6, 8, 6, 8);
        txtParentProject = new TextBox();
        txtParentProject.Name = "txtParentProject";
        txtParentProject.AccessibleName = "المشروع الرئيسي";
        txtParentProject.Dock = DockStyle.Fill;
        txtParentProject.TabIndex = 1;
        txtParentProject.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtParentProject, 0, 1);
        fields.Controls.Add(txtParentProject, 1, 1);
        lbltxtNameLocal = new Label();
        lbltxtNameLocal.Name = "lbltxtNameLocal";
        lbltxtNameLocal.Text = "اسم المشروع (محلي)";
        lbltxtNameLocal.AutoSize = true;
        lbltxtNameLocal.Dock = DockStyle.Fill;
        lbltxtNameLocal.TextAlign = ContentAlignment.MiddleRight;
        lbltxtNameLocal.Margin = new Padding(6, 8, 6, 8);
        txtNameLocal = new TextBox();
        txtNameLocal.Name = "txtNameLocal";
        txtNameLocal.AccessibleName = "اسم المشروع (محلي)";
        txtNameLocal.Dock = DockStyle.Fill;
        txtNameLocal.TabIndex = 2;
        txtNameLocal.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtNameLocal, 0, 2);
        fields.Controls.Add(txtNameLocal, 1, 2);
        lbltxtNameForeign = new Label();
        lbltxtNameForeign.Name = "lbltxtNameForeign";
        lbltxtNameForeign.Text = "اسم المشروع (أجنبي)";
        lbltxtNameForeign.AutoSize = true;
        lbltxtNameForeign.Dock = DockStyle.Fill;
        lbltxtNameForeign.TextAlign = ContentAlignment.MiddleRight;
        lbltxtNameForeign.Margin = new Padding(6, 8, 6, 8);
        txtNameForeign = new TextBox();
        txtNameForeign.Name = "txtNameForeign";
        txtNameForeign.AccessibleName = "اسم المشروع (أجنبي)";
        txtNameForeign.Dock = DockStyle.Fill;
        txtNameForeign.TabIndex = 3;
        txtNameForeign.Margin = new Padding(6, 8, 6, 8);
        txtNameForeign.RightToLeft = RightToLeft.No;
        txtNameForeign.TextAlign = HorizontalAlignment.Left;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtNameForeign, 0, 3);
        fields.Controls.Add(txtNameForeign, 1, 3);
        lbltxtRank = new Label();
        lbltxtRank.Name = "lbltxtRank";
        lbltxtRank.Text = "الرتبة";
        lbltxtRank.AutoSize = true;
        lbltxtRank.Dock = DockStyle.Fill;
        lbltxtRank.TextAlign = ContentAlignment.MiddleRight;
        lbltxtRank.Margin = new Padding(6, 8, 6, 8);
        txtRank = new TextBox();
        txtRank.Name = "txtRank";
        txtRank.AccessibleName = "الرتبة";
        txtRank.Dock = DockStyle.Fill;
        txtRank.TabIndex = 4;
        txtRank.Margin = new Padding(6, 8, 6, 8);
        txtRank.ReadOnly = true;
        txtRank.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtRank, 0, 4);
        fields.Controls.Add(txtRank, 1, 4);
        lblcboProjectType = new Label();
        lblcboProjectType.Name = "lblcboProjectType";
        lblcboProjectType.Text = "نوع المشروع";
        lblcboProjectType.AutoSize = true;
        lblcboProjectType.Dock = DockStyle.Fill;
        lblcboProjectType.TextAlign = ContentAlignment.MiddleRight;
        lblcboProjectType.Margin = new Padding(6, 8, 6, 8);
        cboProjectType = new ComboBox();
        cboProjectType.Name = "cboProjectType";
        cboProjectType.AccessibleName = "نوع المشروع";
        cboProjectType.Dock = DockStyle.Fill;
        cboProjectType.TabIndex = 5;
        cboProjectType.Margin = new Padding(6, 8, 6, 8);
        cboProjectType.DropDownStyle = ComboBoxStyle.DropDownList;
        cboProjectType.Enabled = false;
        cboProjectType.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboProjectType, 0, 5);
        fields.Controls.Add(cboProjectType, 1, 5);
        lblcboProjectGroup = new Label();
        lblcboProjectGroup.Name = "lblcboProjectGroup";
        lblcboProjectGroup.Text = "مجموعة المشاريع";
        lblcboProjectGroup.AutoSize = true;
        lblcboProjectGroup.Dock = DockStyle.Fill;
        lblcboProjectGroup.TextAlign = ContentAlignment.MiddleRight;
        lblcboProjectGroup.Margin = new Padding(6, 8, 6, 8);
        cboProjectGroup = new ComboBox();
        cboProjectGroup.Name = "cboProjectGroup";
        cboProjectGroup.AccessibleName = "مجموعة المشاريع";
        cboProjectGroup.Dock = DockStyle.Fill;
        cboProjectGroup.TabIndex = 6;
        cboProjectGroup.Margin = new Padding(6, 8, 6, 8);
        cboProjectGroup.DropDownStyle = ComboBoxStyle.DropDownList;
        cboProjectGroup.Enabled = false;
        cboProjectGroup.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboProjectGroup, 0, 6);
        fields.Controls.Add(cboProjectGroup, 1, 6);
        lbltxtStartDate = new Label();
        lbltxtStartDate.Name = "lbltxtStartDate";
        lbltxtStartDate.Text = "تاريخ البداية";
        lbltxtStartDate.AutoSize = true;
        lbltxtStartDate.Dock = DockStyle.Fill;
        lbltxtStartDate.TextAlign = ContentAlignment.MiddleRight;
        lbltxtStartDate.Margin = new Padding(6, 8, 6, 8);
        txtStartDate = new TextBox();
        txtStartDate.Name = "txtStartDate";
        txtStartDate.AccessibleName = "تاريخ البداية";
        txtStartDate.Dock = DockStyle.Fill;
        txtStartDate.TabIndex = 7;
        txtStartDate.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtStartDate, 0, 7);
        fields.Controls.Add(txtStartDate, 1, 7);
        lbltxtEndDate = new Label();
        lbltxtEndDate.Name = "lbltxtEndDate";
        lbltxtEndDate.Text = "تاريخ النهاية";
        lbltxtEndDate.AutoSize = true;
        lbltxtEndDate.Dock = DockStyle.Fill;
        lbltxtEndDate.TextAlign = ContentAlignment.MiddleRight;
        lbltxtEndDate.Margin = new Padding(6, 8, 6, 8);
        txtEndDate = new TextBox();
        txtEndDate.Name = "txtEndDate";
        txtEndDate.AccessibleName = "تاريخ النهاية";
        txtEndDate.Dock = DockStyle.Fill;
        txtEndDate.TabIndex = 8;
        txtEndDate.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtEndDate, 0, 8);
        fields.Controls.Add(txtEndDate, 1, 8);
        lbltxtAddress = new Label();
        lbltxtAddress.Name = "lbltxtAddress";
        lbltxtAddress.Text = "العنوان";
        lbltxtAddress.AutoSize = true;
        lbltxtAddress.Dock = DockStyle.Fill;
        lbltxtAddress.TextAlign = ContentAlignment.MiddleRight;
        lbltxtAddress.Margin = new Padding(6, 8, 6, 8);
        txtAddress = new TextBox();
        txtAddress.Name = "txtAddress";
        txtAddress.AccessibleName = "العنوان";
        txtAddress.Dock = DockStyle.Fill;
        txtAddress.TabIndex = 9;
        txtAddress.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtAddress, 0, 9);
        fields.Controls.Add(txtAddress, 1, 9);
        lblchkStopped = new Label();
        lblchkStopped.Name = "lblchkStopped";
        lblchkStopped.Text = "موقف";
        lblchkStopped.AutoSize = true;
        lblchkStopped.Dock = DockStyle.Fill;
        lblchkStopped.TextAlign = ContentAlignment.MiddleRight;
        lblchkStopped.Margin = new Padding(6, 8, 6, 8);
        chkStopped = new CheckBox();
        chkStopped.Name = "chkStopped";
        chkStopped.AccessibleName = "موقف";
        chkStopped.Dock = DockStyle.Fill;
        chkStopped.TabIndex = 10;
        chkStopped.Margin = new Padding(6, 8, 6, 8);
        chkStopped.AutoSize = true;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblchkStopped, 0, 10);
        fields.Controls.Add(chkStopped, 1, 10);
        lbltxtStopReason = new Label();
        lbltxtStopReason.Name = "lbltxtStopReason";
        lbltxtStopReason.Text = "سبب الإيقاف";
        lbltxtStopReason.AutoSize = true;
        lbltxtStopReason.Dock = DockStyle.Fill;
        lbltxtStopReason.TextAlign = ContentAlignment.MiddleRight;
        lbltxtStopReason.Margin = new Padding(6, 8, 6, 8);
        txtStopReason = new TextBox();
        txtStopReason.Name = "txtStopReason";
        txtStopReason.AccessibleName = "سبب الإيقاف";
        txtStopReason.Dock = DockStyle.Fill;
        txtStopReason.TabIndex = 11;
        txtStopReason.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtStopReason, 0, 11);
        fields.Controls.Add(txtStopReason, 1, 11);
        lbltxtStoppedAt = new Label();
        lbltxtStoppedAt.Name = "lbltxtStoppedAt";
        lbltxtStoppedAt.Text = "تاريخ الإيقاف";
        lbltxtStoppedAt.AutoSize = true;
        lbltxtStoppedAt.Dock = DockStyle.Fill;
        lbltxtStoppedAt.TextAlign = ContentAlignment.MiddleRight;
        lbltxtStoppedAt.Margin = new Padding(6, 8, 6, 8);
        txtStoppedAt = new TextBox();
        txtStoppedAt.Name = "txtStoppedAt";
        txtStoppedAt.AccessibleName = "تاريخ الإيقاف";
        txtStoppedAt.Dock = DockStyle.Fill;
        txtStoppedAt.TabIndex = 12;
        txtStoppedAt.Margin = new Padding(6, 8, 6, 8);
        txtStoppedAt.ReadOnly = true;
        txtStoppedAt.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtStoppedAt, 0, 12);
        fields.Controls.Add(txtStoppedAt, 1, 12);
        lblcboCurrency = new Label();
        lblcboCurrency.Name = "lblcboCurrency";
        lblcboCurrency.Text = "العملة";
        lblcboCurrency.AutoSize = true;
        lblcboCurrency.Dock = DockStyle.Fill;
        lblcboCurrency.TextAlign = ContentAlignment.MiddleRight;
        lblcboCurrency.Margin = new Padding(6, 8, 6, 8);
        cboCurrency = new ComboBox();
        cboCurrency.Name = "cboCurrency";
        cboCurrency.AccessibleName = "العملة";
        cboCurrency.Dock = DockStyle.Fill;
        cboCurrency.TabIndex = 13;
        cboCurrency.Margin = new Padding(6, 8, 6, 8);
        cboCurrency.DropDownStyle = ComboBoxStyle.DropDownList;
        cboCurrency.Enabled = false;
        cboCurrency.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboCurrency, 0, 13);
        fields.Controls.Add(cboCurrency, 1, 13);
        lbltxtExchangeRate = new Label();
        lbltxtExchangeRate.Name = "lbltxtExchangeRate";
        lbltxtExchangeRate.Text = "سعر التحويل";
        lbltxtExchangeRate.AutoSize = true;
        lbltxtExchangeRate.Dock = DockStyle.Fill;
        lbltxtExchangeRate.TextAlign = ContentAlignment.MiddleRight;
        lbltxtExchangeRate.Margin = new Padding(6, 8, 6, 8);
        txtExchangeRate = new TextBox();
        txtExchangeRate.Name = "txtExchangeRate";
        txtExchangeRate.AccessibleName = "سعر التحويل";
        txtExchangeRate.Dock = DockStyle.Fill;
        txtExchangeRate.TabIndex = 14;
        txtExchangeRate.Margin = new Padding(6, 8, 6, 8);
        txtExchangeRate.ReadOnly = true;
        txtExchangeRate.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtExchangeRate, 0, 14);
        fields.Controls.Add(txtExchangeRate, 1, 14);
        lbltxtEstimatedValue = new Label();
        lbltxtEstimatedValue.Name = "lbltxtEstimatedValue";
        lbltxtEstimatedValue.Text = "قيمة المشروع التقديرية";
        lbltxtEstimatedValue.AutoSize = true;
        lbltxtEstimatedValue.Dock = DockStyle.Fill;
        lbltxtEstimatedValue.TextAlign = ContentAlignment.MiddleRight;
        lbltxtEstimatedValue.Margin = new Padding(6, 8, 6, 8);
        txtEstimatedValue = new TextBox();
        txtEstimatedValue.Name = "txtEstimatedValue";
        txtEstimatedValue.AccessibleName = "قيمة المشروع التقديرية";
        txtEstimatedValue.Dock = DockStyle.Fill;
        txtEstimatedValue.TabIndex = 15;
        txtEstimatedValue.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtEstimatedValue, 0, 15);
        fields.Controls.Add(txtEstimatedValue, 1, 15);
        lblcboProjectPolicy = new Label();
        lblcboProjectPolicy.Name = "lblcboProjectPolicy";
        lblcboProjectPolicy.Text = "رقم سياسة المشروع";
        lblcboProjectPolicy.AutoSize = true;
        lblcboProjectPolicy.Dock = DockStyle.Fill;
        lblcboProjectPolicy.TextAlign = ContentAlignment.MiddleRight;
        lblcboProjectPolicy.Margin = new Padding(6, 8, 6, 8);
        cboProjectPolicy = new ComboBox();
        cboProjectPolicy.Name = "cboProjectPolicy";
        cboProjectPolicy.AccessibleName = "رقم سياسة المشروع";
        cboProjectPolicy.Dock = DockStyle.Fill;
        cboProjectPolicy.TabIndex = 16;
        cboProjectPolicy.Margin = new Padding(6, 8, 6, 8);
        cboProjectPolicy.DropDownStyle = ComboBoxStyle.DropDownList;
        cboProjectPolicy.Enabled = false;
        cboProjectPolicy.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboProjectPolicy, 0, 16);
        fields.Controls.Add(cboProjectPolicy, 1, 16);
        lbltxtProjectStatus = new Label();
        lbltxtProjectStatus.Name = "lbltxtProjectStatus";
        lbltxtProjectStatus.Text = "حالة المشروع";
        lbltxtProjectStatus.AutoSize = true;
        lbltxtProjectStatus.Dock = DockStyle.Fill;
        lbltxtProjectStatus.TextAlign = ContentAlignment.MiddleRight;
        lbltxtProjectStatus.Margin = new Padding(6, 8, 6, 8);
        txtProjectStatus = new TextBox();
        txtProjectStatus.Name = "txtProjectStatus";
        txtProjectStatus.AccessibleName = "حالة المشروع";
        txtProjectStatus.Dock = DockStyle.Fill;
        txtProjectStatus.TabIndex = 17;
        txtProjectStatus.Margin = new Padding(6, 8, 6, 8);
        txtProjectStatus.ReadOnly = true;
        txtProjectStatus.AccessibleDescription = "قيمة تلقائية؛ تظهر بعد ربط القوائم بخدمة البيانات.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtProjectStatus, 0, 17);
        fields.Controls.Add(txtProjectStatus, 1, 17);
        lbltxtTenderDate = new Label();
        lbltxtTenderDate.Name = "lbltxtTenderDate";
        lbltxtTenderDate.Text = "التاريخ المفترض للمناقصة";
        lbltxtTenderDate.AutoSize = true;
        lbltxtTenderDate.Dock = DockStyle.Fill;
        lbltxtTenderDate.TextAlign = ContentAlignment.MiddleRight;
        lbltxtTenderDate.Margin = new Padding(6, 8, 6, 8);
        txtTenderDate = new TextBox();
        txtTenderDate.Name = "txtTenderDate";
        txtTenderDate.AccessibleName = "التاريخ المفترض للمناقصة";
        txtTenderDate.Dock = DockStyle.Fill;
        txtTenderDate.TabIndex = 18;
        txtTenderDate.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtTenderDate, 0, 18);
        fields.Controls.Add(txtTenderDate, 1, 18);
        lbltxtContractDate = new Label();
        lbltxtContractDate.Name = "lbltxtContractDate";
        lbltxtContractDate.Text = "التاريخ المفترض للعقد";
        lbltxtContractDate.AutoSize = true;
        lbltxtContractDate.Dock = DockStyle.Fill;
        lbltxtContractDate.TextAlign = ContentAlignment.MiddleRight;
        lbltxtContractDate.Margin = new Padding(6, 8, 6, 8);
        txtContractDate = new TextBox();
        txtContractDate.Name = "txtContractDate";
        txtContractDate.AccessibleName = "التاريخ المفترض للعقد";
        txtContractDate.Dock = DockStyle.Fill;
        txtContractDate.TabIndex = 19;
        txtContractDate.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtContractDate, 0, 19);
        fields.Controls.Add(txtContractDate, 1, 19);
        lblcboCostPreparation = new Label();
        lblcboCostPreparation.Name = "lblcboCostPreparation";
        lblcboCostPreparation.Text = "إعداد التكاليف";
        lblcboCostPreparation.AutoSize = true;
        lblcboCostPreparation.Dock = DockStyle.Fill;
        lblcboCostPreparation.TextAlign = ContentAlignment.MiddleRight;
        lblcboCostPreparation.Margin = new Padding(6, 8, 6, 8);
        cboCostPreparation = new ComboBox();
        cboCostPreparation.Name = "cboCostPreparation";
        cboCostPreparation.AccessibleName = "إعداد التكاليف";
        cboCostPreparation.Dock = DockStyle.Fill;
        cboCostPreparation.TabIndex = 20;
        cboCostPreparation.Margin = new Padding(6, 8, 6, 8);
        cboCostPreparation.DropDownStyle = ComboBoxStyle.DropDownList;
        cboCostPreparation.Items.AddRange(new object[] { "وحيد", "متعدد" });
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboCostPreparation, 0, 20);
        fields.Controls.Add(cboCostPreparation, 1, 20);
        lblcboCountry = new Label();
        lblcboCountry.Name = "lblcboCountry";
        lblcboCountry.Text = "الدولة";
        lblcboCountry.AutoSize = true;
        lblcboCountry.Dock = DockStyle.Fill;
        lblcboCountry.TextAlign = ContentAlignment.MiddleRight;
        lblcboCountry.Margin = new Padding(6, 8, 6, 8);
        cboCountry = new ComboBox();
        cboCountry.Name = "cboCountry";
        cboCountry.AccessibleName = "الدولة";
        cboCountry.Dock = DockStyle.Fill;
        cboCountry.TabIndex = 21;
        cboCountry.Margin = new Padding(6, 8, 6, 8);
        cboCountry.DropDownStyle = ComboBoxStyle.DropDownList;
        cboCountry.Enabled = false;
        cboCountry.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboCountry, 0, 21);
        fields.Controls.Add(cboCountry, 1, 21);
        lblcboGovernorate = new Label();
        lblcboGovernorate.Name = "lblcboGovernorate";
        lblcboGovernorate.Text = "المحافظة";
        lblcboGovernorate.AutoSize = true;
        lblcboGovernorate.Dock = DockStyle.Fill;
        lblcboGovernorate.TextAlign = ContentAlignment.MiddleRight;
        lblcboGovernorate.Margin = new Padding(6, 8, 6, 8);
        cboGovernorate = new ComboBox();
        cboGovernorate.Name = "cboGovernorate";
        cboGovernorate.AccessibleName = "المحافظة";
        cboGovernorate.Dock = DockStyle.Fill;
        cboGovernorate.TabIndex = 22;
        cboGovernorate.Margin = new Padding(6, 8, 6, 8);
        cboGovernorate.DropDownStyle = ComboBoxStyle.DropDownList;
        cboGovernorate.Enabled = false;
        cboGovernorate.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboGovernorate, 0, 22);
        fields.Controls.Add(cboGovernorate, 1, 22);
        lblcboCity = new Label();
        lblcboCity.Name = "lblcboCity";
        lblcboCity.Text = "المدينة";
        lblcboCity.AutoSize = true;
        lblcboCity.Dock = DockStyle.Fill;
        lblcboCity.TextAlign = ContentAlignment.MiddleRight;
        lblcboCity.Margin = new Padding(6, 8, 6, 8);
        cboCity = new ComboBox();
        cboCity.Name = "cboCity";
        cboCity.AccessibleName = "المدينة";
        cboCity.Dock = DockStyle.Fill;
        cboCity.TabIndex = 23;
        cboCity.Margin = new Padding(6, 8, 6, 8);
        cboCity.DropDownStyle = ComboBoxStyle.DropDownList;
        cboCity.Enabled = false;
        cboCity.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboCity, 0, 23);
        fields.Controls.Add(cboCity, 1, 23);
        lblcboArea = new Label();
        lblcboArea.Name = "lblcboArea";
        lblcboArea.Text = "المنطقة";
        lblcboArea.AutoSize = true;
        lblcboArea.Dock = DockStyle.Fill;
        lblcboArea.TextAlign = ContentAlignment.MiddleRight;
        lblcboArea.Margin = new Padding(6, 8, 6, 8);
        cboArea = new ComboBox();
        cboArea.Name = "cboArea";
        cboArea.AccessibleName = "المنطقة";
        cboArea.Dock = DockStyle.Fill;
        cboArea.TabIndex = 24;
        cboArea.Margin = new Padding(6, 8, 6, 8);
        cboArea.DropDownStyle = ComboBoxStyle.DropDownList;
        cboArea.Enabled = false;
        cboArea.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboArea, 0, 24);
        fields.Controls.Add(cboArea, 1, 24);
        lblcboProjectManager = new Label();
        lblcboProjectManager.Name = "lblcboProjectManager";
        lblcboProjectManager.Text = "مدير المشروع";
        lblcboProjectManager.AutoSize = true;
        lblcboProjectManager.Dock = DockStyle.Fill;
        lblcboProjectManager.TextAlign = ContentAlignment.MiddleRight;
        lblcboProjectManager.Margin = new Padding(6, 8, 6, 8);
        cboProjectManager = new ComboBox();
        cboProjectManager.Name = "cboProjectManager";
        cboProjectManager.AccessibleName = "مدير المشروع";
        cboProjectManager.Dock = DockStyle.Fill;
        cboProjectManager.TabIndex = 25;
        cboProjectManager.Margin = new Padding(6, 8, 6, 8);
        cboProjectManager.DropDownStyle = ComboBoxStyle.DropDownList;
        cboProjectManager.Enabled = false;
        cboProjectManager.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboProjectManager, 0, 25);
        fields.Controls.Add(cboProjectManager, 1, 25);
        lblcboGeneralConsultant = new Label();
        lblcboGeneralConsultant.Name = "lblcboGeneralConsultant";
        lblcboGeneralConsultant.Text = "الاستشاري العام";
        lblcboGeneralConsultant.AutoSize = true;
        lblcboGeneralConsultant.Dock = DockStyle.Fill;
        lblcboGeneralConsultant.TextAlign = ContentAlignment.MiddleRight;
        lblcboGeneralConsultant.Margin = new Padding(6, 8, 6, 8);
        cboGeneralConsultant = new ComboBox();
        cboGeneralConsultant.Name = "cboGeneralConsultant";
        cboGeneralConsultant.AccessibleName = "الاستشاري العام";
        cboGeneralConsultant.Dock = DockStyle.Fill;
        cboGeneralConsultant.TabIndex = 26;
        cboGeneralConsultant.Margin = new Padding(6, 8, 6, 8);
        cboGeneralConsultant.DropDownStyle = ComboBoxStyle.DropDownList;
        cboGeneralConsultant.Enabled = false;
        cboGeneralConsultant.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboGeneralConsultant, 0, 26);
        fields.Controls.Add(cboGeneralConsultant, 1, 26);
        lblcboSpecialistConsultant = new Label();
        lblcboSpecialistConsultant.Name = "lblcboSpecialistConsultant";
        lblcboSpecialistConsultant.Text = "استشاري أعمال متخصصة";
        lblcboSpecialistConsultant.AutoSize = true;
        lblcboSpecialistConsultant.Dock = DockStyle.Fill;
        lblcboSpecialistConsultant.TextAlign = ContentAlignment.MiddleRight;
        lblcboSpecialistConsultant.Margin = new Padding(6, 8, 6, 8);
        cboSpecialistConsultant = new ComboBox();
        cboSpecialistConsultant.Name = "cboSpecialistConsultant";
        cboSpecialistConsultant.AccessibleName = "استشاري أعمال متخصصة";
        cboSpecialistConsultant.Dock = DockStyle.Fill;
        cboSpecialistConsultant.TabIndex = 27;
        cboSpecialistConsultant.Margin = new Padding(6, 8, 6, 8);
        cboSpecialistConsultant.DropDownStyle = ComboBoxStyle.DropDownList;
        cboSpecialistConsultant.Enabled = false;
        cboSpecialistConsultant.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboSpecialistConsultant, 0, 27);
        fields.Controls.Add(cboSpecialistConsultant, 1, 27);
        lbltxtNotes = new Label();
        lbltxtNotes.Name = "lbltxtNotes";
        lbltxtNotes.Text = "ملاحظات";
        lbltxtNotes.AutoSize = true;
        lbltxtNotes.Dock = DockStyle.Fill;
        lbltxtNotes.TextAlign = ContentAlignment.MiddleRight;
        lbltxtNotes.Margin = new Padding(6, 8, 6, 8);
        txtNotes = new TextBox();
        txtNotes.Name = "txtNotes";
        txtNotes.AccessibleName = "ملاحظات";
        txtNotes.Dock = DockStyle.Fill;
        txtNotes.TabIndex = 28;
        txtNotes.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtNotes, 0, 28);
        fields.Controls.Add(txtNotes, 1, 28);
        standardCommandAdd.Name = "btnAdd";
        standardCommandAdd.Enabled = true;
        standardCommandAdd.Click += draftAction_Click;
        standardCommandSave.Name = "btnSave";
        standardCommandSave.Enabled = false;
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        layout.Controls.Add(lblTitle, 0, 0);
        layout.Controls.Add(lblStatus, 0, 1);
        layout.Controls.Add(designerCommandBar, 0, 2);
        layout.Controls.Add(fields, 0, 3);
        Controls.Add(layout);


        Name = "UcProjectData";
        Text = "بيانات المشاريع";
        Size = new Size(1000, 640);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        RightToLeft = RightToLeft.Yes;
        fields.ResumeLayout(true);
        layout.ResumeLayout(true);
        ResumeLayout(true);
        tabsFields = new TabControl();
        tabsFields.Name = "tabsFields";
        tabsFields.Dock = DockStyle.Fill;
        tabsFields.Height = 520;
        tabsFields.MinimumSize = new Size(0, 520);
        tabsFields.RightToLeft = RightToLeft.Yes;
        tabsFields.RightToLeftLayout = true;
        sectionPage0 = new TabPage();
        sectionFields0 = new TableLayoutPanel();
        sectionPage0.Text = "البيانات الأساسية";
        sectionPage0.AutoScroll = true;
        sectionFields0.Dock = DockStyle.Top;
        sectionFields0.AutoSize = true;
        sectionFields0.ColumnCount = 2;
        sectionFields0.RowCount = 4;
        sectionFields0.Enabled = false;
        sectionFields0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        sectionFields0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lbltxtProjectNumber, 0, 0);
        sectionFields0.Controls.Add(txtProjectNumber, 1, 0);
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lbltxtParentProject, 0, 1);
        sectionFields0.Controls.Add(txtParentProject, 1, 1);
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lbltxtNameLocal, 0, 2);
        sectionFields0.Controls.Add(txtNameLocal, 1, 2);
        sectionFields0.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields0.Controls.Add(lbltxtNameForeign, 0, 3);
        sectionFields0.Controls.Add(txtNameForeign, 1, 3);
        sectionPage0.Controls.Add(sectionFields0);
        tabsFields.TabPages.Add(sectionPage0);
        sectionPage1 = new TabPage();
        sectionFields1 = new TableLayoutPanel();
        sectionPage1.Text = "البيانات الرئيسية";
        sectionPage1.AutoScroll = true;
        sectionFields1.Dock = DockStyle.Top;
        sectionFields1.AutoSize = true;
        sectionFields1.ColumnCount = 2;
        sectionFields1.RowCount = 9;
        sectionFields1.Enabled = false;
        sectionFields1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        sectionFields1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lbltxtRank, 0, 0);
        sectionFields1.Controls.Add(txtRank, 1, 0);
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lblcboProjectType, 0, 1);
        sectionFields1.Controls.Add(cboProjectType, 1, 1);
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lblcboProjectGroup, 0, 2);
        sectionFields1.Controls.Add(cboProjectGroup, 1, 2);
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lbltxtStartDate, 0, 3);
        sectionFields1.Controls.Add(txtStartDate, 1, 3);
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lbltxtEndDate, 0, 4);
        sectionFields1.Controls.Add(txtEndDate, 1, 4);
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lbltxtAddress, 0, 5);
        sectionFields1.Controls.Add(txtAddress, 1, 5);
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lblchkStopped, 0, 6);
        sectionFields1.Controls.Add(chkStopped, 1, 6);
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lbltxtStopReason, 0, 7);
        sectionFields1.Controls.Add(txtStopReason, 1, 7);
        sectionFields1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields1.Controls.Add(lbltxtStoppedAt, 0, 8);
        sectionFields1.Controls.Add(txtStoppedAt, 1, 8);
        sectionPage1.Controls.Add(sectionFields1);
        tabsFields.TabPages.Add(sectionPage1);
        sectionPage2 = new TabPage();
        sectionFields2 = new TableLayoutPanel();
        sectionPage2.Text = "بيانات المشاريع";
        sectionPage2.AutoScroll = true;
        sectionFields2.Dock = DockStyle.Top;
        sectionFields2.AutoSize = true;
        sectionFields2.ColumnCount = 2;
        sectionFields2.RowCount = 16;
        sectionFields2.Enabled = false;
        sectionFields2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        sectionFields2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
        sectionFields2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields2.Controls.Add(lblcboCurrency, 0, 0);
        sectionFields2.Controls.Add(cboCurrency, 1, 0);
        sectionFields2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields2.Controls.Add(lbltxtExchangeRate, 0, 1);
        sectionFields2.Controls.Add(txtExchangeRate, 1, 1);
        sectionFields2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields2.Controls.Add(lbltxtEstimatedValue, 0, 2);
        sectionFields2.Controls.Add(txtEstimatedValue, 1, 2);
        sectionFields2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields2.Controls.Add(lblcboProjectPolicy, 0, 3);
        sectionFields2.Controls.Add(cboProjectPolicy, 1, 3);
        sectionFields2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields2.Controls.Add(lbltxtProjectStatus, 0, 4);
        sectionFields2.Controls.Add(txtProjectStatus, 1, 4);
        sectionFields2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields2.Controls.Add(lbltxtTenderDate, 0, 5);
        sectionFields2.Controls.Add(txtTenderDate, 1, 5);
        sectionFields2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields2.Controls.Add(lbltxtContractDate, 0, 6);
        sectionFields2.Controls.Add(txtContractDate, 1, 6);
        sectionFields2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields2.Controls.Add(lblcboCostPreparation, 0, 7);
        sectionFields2.Controls.Add(cboCostPreparation, 1, 7);
        sectionFields2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields2.Controls.Add(lblcboCountry, 0, 8);
        sectionFields2.Controls.Add(cboCountry, 1, 8);
        sectionFields2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields2.Controls.Add(lblcboGovernorate, 0, 9);
        sectionFields2.Controls.Add(cboGovernorate, 1, 9);
        sectionFields2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields2.Controls.Add(lblcboCity, 0, 10);
        sectionFields2.Controls.Add(cboCity, 1, 10);
        sectionFields2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields2.Controls.Add(lblcboArea, 0, 11);
        sectionFields2.Controls.Add(cboArea, 1, 11);
        sectionFields2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields2.Controls.Add(lblcboProjectManager, 0, 12);
        sectionFields2.Controls.Add(cboProjectManager, 1, 12);
        sectionFields2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields2.Controls.Add(lblcboGeneralConsultant, 0, 13);
        sectionFields2.Controls.Add(cboGeneralConsultant, 1, 13);
        sectionFields2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields2.Controls.Add(lblcboSpecialistConsultant, 0, 14);
        sectionFields2.Controls.Add(cboSpecialistConsultant, 1, 14);
        sectionFields2.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        sectionFields2.Controls.Add(lbltxtNotes, 0, 15);
        sectionFields2.Controls.Add(txtNotes, 1, 15);
        sectionPage2.Controls.Add(sectionFields2);
        tabsFields.TabPages.Add(sectionPage2);
        fields.Visible = false;
        layout.RowCount = 5;
        layout.Controls.Add(tabsFields, 0, 4);

        btnUseCenters = new Button();
        btnUseActivities = new Button();
        standardCommandAdd.Visible = true;
        standardCommandEdit.Visible = true;
        standardCommandDelete.Visible = true;
        standardCommandCancel.Visible = true;
        standardCommandView.Visible = true;
        standardCommandLast.Visible = true;
        standardCommandNext.Visible = true;
        standardCommandPrevious.Visible = true;
        standardCommandFirst.Visible = true;
        standardCommandSave.Visible = true;
        standardCommandPrint.Visible = true;
        standardCommandClose.Visible = true;
        standardCommandRefresh.Visible = false;
        standardCommandImport.Visible = false;
        standardCommandExport.Visible = false;
        standardCommandHelp.Visible = false;
        btnUseCenters.Name = "btnUseCenters";
        btnUseCenters.Text = "استخدام المراكز";
        btnUseCenters.AutoSize = true;
        btnUseCenters.Enabled = false;
        btnUseCenters.Visible = false;
        standardCommandFlow.Controls.Add(btnUseCenters);
        btnUseActivities.Name = "btnUseActivities";
        btnUseActivities.Text = "استخدام الأنشطة";
        btnUseActivities.AutoSize = true;
        btnUseActivities.Enabled = false;
        btnUseActivities.Visible = false;
        standardCommandFlow.Controls.Add(btnUseActivities);
        standardCommandImport.Visible = true;
        standardCommandImport.Name = "btnImportExcel";
        standardCommandImport.Text = "الاستيراد من الإكسل";
        standardCommandImport.AutoSize = true;
        standardCommandImport.Enabled = false;
        standardCommandImport.AccessibleDescription = "خدمة الاستيراد غير مرتبطة.";
    

        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
    }
}
