namespace TransportERP.Desktop.Forms.SystemSettings.General;
partial class UcTaxCalculationMethods
{
    private TransportERP.Desktop.CoreUI.DesignerCommandBar designerCommandBar = null!;
    private FlowLayoutPanel standardCommandFlow = null!;
    private Panel standardCloseHost = null!;
    private Button standardCommandAdd = null!;
    private Button standardCommandEdit = null!;
    private Button standardCommandDelete = null!;
    private Button standardCommandCancel = null!;
    private Button standardCommandView = null!;
    private Button standardCommandLast = null!;
    private Button standardCommandNext = null!;
    private Button standardCommandPrevious = null!;
    private Button standardCommandFirst = null!;
    private Button standardCommandSave = null!;
    private Button standardCommandPrint = null!;
    private Button standardCommandClose = null!;
    private Button standardCommandRefresh = null!;
    private Button standardCommandImport = null!;
    private Button standardCommandExport = null!;
    private Button standardCommandHelp = null!;

    private TableLayoutPanel layout = null!;
    private TableLayoutPanel fields = null!;
    private Label lblTitle = null!;
    private Label lblStatus = null!;
    private TransportERP.Desktop.CoreUI.AuditMetadataControl standardAuditMetadata = null!;
    private Label lblcboCompanyNumber = null!;
    private ComboBox cboCompanyNumber = null!;
    private Label lbltxtMethodNumber = null!;
    private TextBox txtMethodNumber = null!;
    private Label lbltxtNameLocal = null!;
    private TextBox txtNameLocal = null!;
    private Label lbltxtNameForeign = null!;
    private TextBox txtNameForeign = null!;
    private Label lblcboTaxType = null!;
    private ComboBox cboTaxType = null!;
    private Label lblchkDefault = null!;
    private CheckBox chkDefault = null!;
    private Label lblchkExempt = null!;
    private CheckBox chkExempt = null!;
    private Label lblchkTransition = null!;
    private CheckBox chkTransition = null!;
    private Label lblcboTransitionMethod = null!;
    private ComboBox cboTransitionMethod = null!;
    private Label lblchkStopped = null!;
    private CheckBox chkStopped = null!;
    private TabControl tabsSetup = null!;
    private DataGridView gridTaxTypes = null!;
    private DataGridViewComboBoxColumn gridTaxTypes_colTaxType = null!;
    private TabPage tabgridTaxTypes = null!;
    private DataGridView gridBranches = null!;
    private DataGridViewComboBoxColumn gridBranches_colBranch = null!;
    private DataGridViewTextBoxColumn gridBranches_colActivationStart = null!;
    private DataGridViewTextBoxColumn gridBranches_colActivationEnd = null!;
    private DataGridViewCheckBoxColumn gridBranches_colTransition = null!;
    private DataGridViewTextBoxColumn gridBranches_colTransitionStart = null!;
    private DataGridViewTextBoxColumn gridBranches_colTransitionEnd = null!;
    private TabPage tabgridBranches = null!;
    private void InitializeComponent()
    {
        SuspendLayout();
        designerCommandBar = new TransportERP.Desktop.CoreUI.DesignerCommandBar();
        standardCommandFlow = new FlowLayoutPanel();
        standardCloseHost = new Panel();
        standardCommandAdd = new Button();
        standardCommandEdit = new Button();
        standardCommandDelete = new Button();
        standardCommandCancel = new Button();
        standardCommandView = new Button();
        standardCommandLast = new Button();
        standardCommandNext = new Button();
        standardCommandPrevious = new Button();
        standardCommandFirst = new Button();
        standardCommandSave = new Button();
        standardCommandPrint = new Button();
        standardCommandClose = new Button();
        standardCommandRefresh = new Button();
        standardCommandImport = new Button();
        standardCommandExport = new Button();
        standardCommandHelp = new Button();
        designerCommandBar.Name = "designerCommandBar";
        designerCommandBar.Dock = DockStyle.Top;
        designerCommandBar.Size = new Size(1000, 44);
        designerCommandBar.MinimumSize = new Size(0, 30);
        designerCommandBar.Margin = Padding.Empty;
        designerCommandBar.BorderStyle = BorderStyle.FixedSingle;
        designerCommandBar.BackColor = Color.FromArgb(239, 239, 239);
        standardCommandFlow.Name = "pnlToolbar";
        standardCommandFlow.Dock = DockStyle.Fill;
        standardCommandFlow.FlowDirection = FlowDirection.RightToLeft;
        standardCommandFlow.RightToLeft = RightToLeft.No;
        standardCommandFlow.WrapContents = false;
        standardCommandFlow.Padding = new Padding(2);
        standardCloseHost.Name = "standardCloseHost";
        standardCloseHost.Dock = DockStyle.Left;
        standardCloseHost.Width = 28;
        designerCommandBar.Controls.Add(standardCommandFlow);
        designerCommandBar.Controls.Add(standardCloseHost);
        standardCommandAdd.Name = "standardCommandAdd";
        standardCommandAdd.AccessibleName = "إضافة";
        standardCommandAdd.Enabled = false;
        standardCommandAdd.Visible = true;
        standardCommandAdd.Size = new Size(26, 24);
        standardCommandAdd.Margin = new Padding(1);
        standardCommandAdd.FlatStyle = FlatStyle.Flat;
        standardCommandAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandAdd.TabIndex = 0;
        standardCommandAdd.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Add;
        standardCommandFlow.Controls.Add(standardCommandAdd);
        designerCommandBar.SetCommandRole(standardCommandAdd, TransportERP.Desktop.CoreUI.DesignerCommandRole.Add);
        standardCommandEdit.Name = "standardCommandEdit";
        standardCommandEdit.AccessibleName = "تعديل";
        standardCommandEdit.Enabled = false;
        standardCommandEdit.Visible = true;
        standardCommandEdit.Size = new Size(26, 24);
        standardCommandEdit.Margin = new Padding(1);
        standardCommandEdit.FlatStyle = FlatStyle.Flat;
        standardCommandEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandEdit.TabIndex = 1;
        standardCommandEdit.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Edit;
        standardCommandFlow.Controls.Add(standardCommandEdit);
        designerCommandBar.SetCommandRole(standardCommandEdit, TransportERP.Desktop.CoreUI.DesignerCommandRole.Edit);
        standardCommandDelete.Name = "standardCommandDelete";
        standardCommandDelete.AccessibleName = "حذف";
        standardCommandDelete.Enabled = false;
        standardCommandDelete.Visible = true;
        standardCommandDelete.Size = new Size(26, 24);
        standardCommandDelete.Margin = new Padding(1);
        standardCommandDelete.FlatStyle = FlatStyle.Flat;
        standardCommandDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandDelete.TabIndex = 2;
        standardCommandDelete.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Delete;
        standardCommandFlow.Controls.Add(standardCommandDelete);
        designerCommandBar.SetCommandRole(standardCommandDelete, TransportERP.Desktop.CoreUI.DesignerCommandRole.Delete);
        standardCommandCancel.Name = "standardCommandCancel";
        standardCommandCancel.AccessibleName = "تراجع";
        standardCommandCancel.Enabled = false;
        standardCommandCancel.Visible = true;
        standardCommandCancel.Size = new Size(26, 24);
        standardCommandCancel.Margin = new Padding(1);
        standardCommandCancel.FlatStyle = FlatStyle.Flat;
        standardCommandCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandCancel.TabIndex = 3;
        standardCommandCancel.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Cancel;
        standardCommandFlow.Controls.Add(standardCommandCancel);
        designerCommandBar.SetCommandRole(standardCommandCancel, TransportERP.Desktop.CoreUI.DesignerCommandRole.Cancel);
        standardCommandView.Name = "standardCommandView";
        standardCommandView.AccessibleName = "عرض";
        standardCommandView.Enabled = false;
        standardCommandView.Visible = true;
        standardCommandView.Size = new Size(26, 24);
        standardCommandView.Margin = new Padding(1);
        standardCommandView.FlatStyle = FlatStyle.Flat;
        standardCommandView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandView.TabIndex = 4;
        standardCommandView.Image = TransportERP.Desktop.CoreUI.CommandBarImages.View;
        standardCommandFlow.Controls.Add(standardCommandView);
        designerCommandBar.SetCommandRole(standardCommandView, TransportERP.Desktop.CoreUI.DesignerCommandRole.View);
        standardCommandLast.Name = "standardCommandLast";
        standardCommandLast.AccessibleName = "الأخير";
        standardCommandLast.Enabled = false;
        standardCommandLast.Visible = true;
        standardCommandLast.Size = new Size(26, 24);
        standardCommandLast.Margin = new Padding(1);
        standardCommandLast.FlatStyle = FlatStyle.Flat;
        standardCommandLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandLast.TabIndex = 5;
        standardCommandLast.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Last;
        standardCommandFlow.Controls.Add(standardCommandLast);
        designerCommandBar.SetCommandRole(standardCommandLast, TransportERP.Desktop.CoreUI.DesignerCommandRole.Last);
        standardCommandNext.Name = "standardCommandNext";
        standardCommandNext.AccessibleName = "التالي";
        standardCommandNext.Enabled = false;
        standardCommandNext.Visible = true;
        standardCommandNext.Size = new Size(26, 24);
        standardCommandNext.Margin = new Padding(1);
        standardCommandNext.FlatStyle = FlatStyle.Flat;
        standardCommandNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandNext.TabIndex = 6;
        standardCommandNext.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Next;
        standardCommandFlow.Controls.Add(standardCommandNext);
        designerCommandBar.SetCommandRole(standardCommandNext, TransportERP.Desktop.CoreUI.DesignerCommandRole.Next);
        standardCommandPrevious.Name = "standardCommandPrevious";
        standardCommandPrevious.AccessibleName = "السابق";
        standardCommandPrevious.Enabled = false;
        standardCommandPrevious.Visible = true;
        standardCommandPrevious.Size = new Size(26, 24);
        standardCommandPrevious.Margin = new Padding(1);
        standardCommandPrevious.FlatStyle = FlatStyle.Flat;
        standardCommandPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrevious.TabIndex = 7;
        standardCommandPrevious.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Previous;
        standardCommandFlow.Controls.Add(standardCommandPrevious);
        designerCommandBar.SetCommandRole(standardCommandPrevious, TransportERP.Desktop.CoreUI.DesignerCommandRole.Previous);
        standardCommandFirst.Name = "standardCommandFirst";
        standardCommandFirst.AccessibleName = "الأول";
        standardCommandFirst.Enabled = false;
        standardCommandFirst.Visible = true;
        standardCommandFirst.Size = new Size(26, 24);
        standardCommandFirst.Margin = new Padding(1);
        standardCommandFirst.FlatStyle = FlatStyle.Flat;
        standardCommandFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandFirst.TabIndex = 8;
        standardCommandFirst.Image = TransportERP.Desktop.CoreUI.CommandBarImages.First;
        standardCommandFlow.Controls.Add(standardCommandFirst);
        designerCommandBar.SetCommandRole(standardCommandFirst, TransportERP.Desktop.CoreUI.DesignerCommandRole.First);
        standardCommandSave.Name = "btnSave";
        standardCommandSave.AccessibleName = "حفظ";
        standardCommandSave.Enabled = false;
        standardCommandSave.Visible = true;
        standardCommandSave.Size = new Size(26, 24);
        standardCommandSave.Margin = new Padding(1);
        standardCommandSave.FlatStyle = FlatStyle.Flat;
        standardCommandSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandSave.TabIndex = 9;
        standardCommandSave.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Save;
        standardCommandFlow.Controls.Add(standardCommandSave);
        designerCommandBar.SetCommandRole(standardCommandSave, TransportERP.Desktop.CoreUI.DesignerCommandRole.Save);
        standardCommandPrint.Name = "standardCommandPrint";
        standardCommandPrint.AccessibleName = "طباعة";
        standardCommandPrint.Enabled = false;
        standardCommandPrint.Visible = true;
        standardCommandPrint.Size = new Size(26, 24);
        standardCommandPrint.Margin = new Padding(1);
        standardCommandPrint.FlatStyle = FlatStyle.Flat;
        standardCommandPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandPrint.TabIndex = 10;
        standardCommandPrint.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Print;
        standardCommandFlow.Controls.Add(standardCommandPrint);
        designerCommandBar.SetCommandRole(standardCommandPrint, TransportERP.Desktop.CoreUI.DesignerCommandRole.Print);
        standardCommandClose.Name = "standardCommandClose";
        standardCommandClose.AccessibleName = "إغلاق";
        standardCommandClose.Enabled = false;
        standardCommandClose.Visible = true;
        standardCommandClose.Size = new Size(26, 24);
        standardCommandClose.Margin = new Padding(1);
        standardCommandClose.FlatStyle = FlatStyle.Flat;
        standardCommandClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandClose.TabIndex = 11;
        standardCommandClose.Image = TransportERP.Desktop.CoreUI.CommandBarImages.Close;
        standardCloseHost.Controls.Add(standardCommandClose);
        designerCommandBar.SetCommandRole(standardCommandClose, TransportERP.Desktop.CoreUI.DesignerCommandRole.Close);
        standardCommandRefresh.Name = "standardCommandRefresh";
        standardCommandRefresh.AccessibleName = "تحديث";
        standardCommandRefresh.Enabled = false;
        standardCommandRefresh.Visible = false;
        standardCommandRefresh.Size = new Size(26, 24);
        standardCommandRefresh.Margin = new Padding(1);
        standardCommandRefresh.FlatStyle = FlatStyle.Flat;
        standardCommandRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandRefresh.TabIndex = 12;
        standardCommandRefresh.Text = "تحديث";
        standardCommandFlow.Controls.Add(standardCommandRefresh);
        designerCommandBar.SetCommandRole(standardCommandRefresh, TransportERP.Desktop.CoreUI.DesignerCommandRole.Refresh);
        standardCommandImport.Name = "standardCommandImport";
        standardCommandImport.AccessibleName = "استيراد";
        standardCommandImport.Enabled = false;
        standardCommandImport.Visible = false;
        standardCommandImport.Size = new Size(26, 24);
        standardCommandImport.Margin = new Padding(1);
        standardCommandImport.FlatStyle = FlatStyle.Flat;
        standardCommandImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandImport.TabIndex = 13;
        standardCommandImport.Text = "استيراد";
        standardCommandFlow.Controls.Add(standardCommandImport);
        designerCommandBar.SetCommandRole(standardCommandImport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Import);
        standardCommandExport.Name = "standardCommandExport";
        standardCommandExport.AccessibleName = "تصدير";
        standardCommandExport.Enabled = false;
        standardCommandExport.Visible = false;
        standardCommandExport.Size = new Size(26, 24);
        standardCommandExport.Margin = new Padding(1);
        standardCommandExport.FlatStyle = FlatStyle.Flat;
        standardCommandExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandExport.TabIndex = 14;
        standardCommandExport.Text = "تصدير";
        standardCommandFlow.Controls.Add(standardCommandExport);
        designerCommandBar.SetCommandRole(standardCommandExport, TransportERP.Desktop.CoreUI.DesignerCommandRole.Export);
        standardCommandHelp.Name = "standardCommandHelp";
        standardCommandHelp.AccessibleName = "مساعدة";
        standardCommandHelp.Enabled = false;
        standardCommandHelp.Visible = false;
        standardCommandHelp.Size = new Size(26, 24);
        standardCommandHelp.Margin = new Padding(1);
        standardCommandHelp.FlatStyle = FlatStyle.Flat;
        standardCommandHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        standardCommandHelp.TabIndex = 15;
        standardCommandHelp.Text = "مساعدة";
        standardCommandFlow.Controls.Add(standardCommandHelp);
        designerCommandBar.SetCommandRole(standardCommandHelp, TransportERP.Desktop.CoreUI.DesignerCommandRole.Help);
        standardCommandClose.Location = new Point(1, 1);
        standardCommandSave.AccessibleDescription = "الحفظ غير متاح؛ لم تُربط الشاشة بخدمة بيانات.";
        Controls.Add(designerCommandBar);

        layout = new TableLayoutPanel();
        fields = new TableLayoutPanel();
        lblTitle = new Label();
        lblStatus = new Label();
        standardAuditMetadata = new TransportERP.Desktop.CoreUI.AuditMetadataControl();
        layout.SuspendLayout();
        fields.SuspendLayout();
        layout.Name = "layout";
        layout.Dock = DockStyle.Top;
        layout.AutoSize = true;
        layout.ColumnCount = 1;
        layout.RowCount = 5;
        layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        lblTitle.Name = "lblTitle";
        lblTitle.Text = "طرق احتساب الضرائب";
        lblTitle.AutoSize = true;
        lblTitle.Dock = DockStyle.Fill;
        lblTitle.Font = new Font("Segoe UI", 16F);
        lblTitle.TextAlign = ContentAlignment.MiddleRight;
        lblTitle.BackColor = Color.FromArgb(192, 192, 255);
        lblTitle.Padding = new Padding(12);
        lblStatus.Name = "lblStatus";
        lblStatus.Text = "معاينة إدخال مؤقتة — الحفظ والترقيم التلقائي والقوائم غير متاحة؛ القيم لا تُطبّق على النظام.";
        lblStatus.AutoSize = true;
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.TextAlign = ContentAlignment.MiddleRight;
        lblStatus.Padding = new Padding(8);
        fields.Name = "fields";
        fields.Dock = DockStyle.Top;
        fields.AutoSize = true;
        fields.ColumnCount = 2;
        fields.RowCount = 10;
        fields.Enabled = false;
        fields.TabIndex = 1;
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 32F));
        fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
        lblcboCompanyNumber = new Label();
        lblcboCompanyNumber.Name = "lblcboCompanyNumber";
        lblcboCompanyNumber.Text = "رقم الشركة";
        lblcboCompanyNumber.AutoSize = true;
        lblcboCompanyNumber.Dock = DockStyle.Fill;
        lblcboCompanyNumber.TextAlign = ContentAlignment.MiddleRight;
        lblcboCompanyNumber.Margin = new Padding(6, 8, 6, 8);
        cboCompanyNumber = new ComboBox();
        cboCompanyNumber.Name = "cboCompanyNumber";
        cboCompanyNumber.AccessibleName = "رقم الشركة";
        cboCompanyNumber.Dock = DockStyle.Fill;
        cboCompanyNumber.TabIndex = 0;
        cboCompanyNumber.Margin = new Padding(6, 8, 6, 8);
        cboCompanyNumber.DropDownStyle = ComboBoxStyle.DropDownList;
        cboCompanyNumber.Enabled = false;
        cboCompanyNumber.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboCompanyNumber, 0, 0);
        fields.Controls.Add(cboCompanyNumber, 1, 0);
        lbltxtMethodNumber = new Label();
        lbltxtMethodNumber.Name = "lbltxtMethodNumber";
        lbltxtMethodNumber.Text = "رقم الطريقة";
        lbltxtMethodNumber.AutoSize = true;
        lbltxtMethodNumber.Dock = DockStyle.Fill;
        lbltxtMethodNumber.TextAlign = ContentAlignment.MiddleRight;
        lbltxtMethodNumber.Margin = new Padding(6, 8, 6, 8);
        txtMethodNumber = new TextBox();
        txtMethodNumber.Name = "txtMethodNumber";
        txtMethodNumber.AccessibleName = "رقم الطريقة";
        txtMethodNumber.Dock = DockStyle.Fill;
        txtMethodNumber.TabIndex = 1;
        txtMethodNumber.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtMethodNumber, 0, 1);
        fields.Controls.Add(txtMethodNumber, 1, 1);
        lbltxtNameLocal = new Label();
        lbltxtNameLocal.Name = "lbltxtNameLocal";
        lbltxtNameLocal.Text = "الاسم (المحلي)";
        lbltxtNameLocal.AutoSize = true;
        lbltxtNameLocal.Dock = DockStyle.Fill;
        lbltxtNameLocal.TextAlign = ContentAlignment.MiddleRight;
        lbltxtNameLocal.Margin = new Padding(6, 8, 6, 8);
        txtNameLocal = new TextBox();
        txtNameLocal.Name = "txtNameLocal";
        txtNameLocal.AccessibleName = "الاسم (المحلي)";
        txtNameLocal.Dock = DockStyle.Fill;
        txtNameLocal.TabIndex = 2;
        txtNameLocal.Margin = new Padding(6, 8, 6, 8);
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtNameLocal, 0, 2);
        fields.Controls.Add(txtNameLocal, 1, 2);
        lbltxtNameForeign = new Label();
        lbltxtNameForeign.Name = "lbltxtNameForeign";
        lbltxtNameForeign.Text = "الاسم (أجنبي)";
        lbltxtNameForeign.AutoSize = true;
        lbltxtNameForeign.Dock = DockStyle.Fill;
        lbltxtNameForeign.TextAlign = ContentAlignment.MiddleRight;
        lbltxtNameForeign.Margin = new Padding(6, 8, 6, 8);
        txtNameForeign = new TextBox();
        txtNameForeign.Name = "txtNameForeign";
        txtNameForeign.AccessibleName = "الاسم (أجنبي)";
        txtNameForeign.Dock = DockStyle.Fill;
        txtNameForeign.TabIndex = 3;
        txtNameForeign.Margin = new Padding(6, 8, 6, 8);
        txtNameForeign.RightToLeft = RightToLeft.No;
        txtNameForeign.TextAlign = HorizontalAlignment.Left;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lbltxtNameForeign, 0, 3);
        fields.Controls.Add(txtNameForeign, 1, 3);
        lblcboTaxType = new Label();
        lblcboTaxType.Name = "lblcboTaxType";
        lblcboTaxType.Text = "نوع الضريبة";
        lblcboTaxType.AutoSize = true;
        lblcboTaxType.Dock = DockStyle.Fill;
        lblcboTaxType.TextAlign = ContentAlignment.MiddleRight;
        lblcboTaxType.Margin = new Padding(6, 8, 6, 8);
        cboTaxType = new ComboBox();
        cboTaxType.Name = "cboTaxType";
        cboTaxType.AccessibleName = "نوع الضريبة";
        cboTaxType.Dock = DockStyle.Fill;
        cboTaxType.TabIndex = 4;
        cboTaxType.Margin = new Padding(6, 8, 6, 8);
        cboTaxType.DropDownStyle = ComboBoxStyle.DropDownList;
        cboTaxType.Items.AddRange(new object[] { "النسبة الأساسية", "تصدير", "مجموعة ضريبية", "عقود معفية", "ليس عليه ضريبية", "ضريبة صفرية", "خارج النطاق", "معفي" });
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboTaxType, 0, 4);
        fields.Controls.Add(cboTaxType, 1, 4);
        lblchkDefault = new Label();
        lblchkDefault.Name = "lblchkDefault";
        lblchkDefault.Text = "الافتراضي";
        lblchkDefault.AutoSize = true;
        lblchkDefault.Dock = DockStyle.Fill;
        lblchkDefault.TextAlign = ContentAlignment.MiddleRight;
        lblchkDefault.Margin = new Padding(6, 8, 6, 8);
        chkDefault = new CheckBox();
        chkDefault.Name = "chkDefault";
        chkDefault.AccessibleName = "الافتراضي";
        chkDefault.Dock = DockStyle.Fill;
        chkDefault.TabIndex = 5;
        chkDefault.Margin = new Padding(6, 8, 6, 8);
        chkDefault.AutoSize = true;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblchkDefault, 0, 5);
        fields.Controls.Add(chkDefault, 1, 5);
        lblchkExempt = new Label();
        lblchkExempt.Name = "lblchkExempt";
        lblchkExempt.Text = "معفي";
        lblchkExempt.AutoSize = true;
        lblchkExempt.Dock = DockStyle.Fill;
        lblchkExempt.TextAlign = ContentAlignment.MiddleRight;
        lblchkExempt.Margin = new Padding(6, 8, 6, 8);
        chkExempt = new CheckBox();
        chkExempt.Name = "chkExempt";
        chkExempt.AccessibleName = "معفي";
        chkExempt.Dock = DockStyle.Fill;
        chkExempt.TabIndex = 6;
        chkExempt.Margin = new Padding(6, 8, 6, 8);
        chkExempt.AutoSize = true;
        chkExempt.AutoCheck = false;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblchkExempt, 0, 6);
        fields.Controls.Add(chkExempt, 1, 6);
        lblchkTransition = new Label();
        lblchkTransition.Name = "lblchkTransition";
        lblchkTransition.Text = "له فترة انتقالية";
        lblchkTransition.AutoSize = true;
        lblchkTransition.Dock = DockStyle.Fill;
        lblchkTransition.TextAlign = ContentAlignment.MiddleRight;
        lblchkTransition.Margin = new Padding(6, 8, 6, 8);
        chkTransition = new CheckBox();
        chkTransition.Name = "chkTransition";
        chkTransition.AccessibleName = "له فترة انتقالية";
        chkTransition.Dock = DockStyle.Fill;
        chkTransition.TabIndex = 7;
        chkTransition.Margin = new Padding(6, 8, 6, 8);
        chkTransition.AutoSize = true;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblchkTransition, 0, 7);
        fields.Controls.Add(chkTransition, 1, 7);
        lblcboTransitionMethod = new Label();
        lblcboTransitionMethod.Name = "lblcboTransitionMethod";
        lblcboTransitionMethod.Text = "رقم طريقة احتساب الضريبة للفترة الانتقالية";
        lblcboTransitionMethod.AutoSize = true;
        lblcboTransitionMethod.Dock = DockStyle.Fill;
        lblcboTransitionMethod.TextAlign = ContentAlignment.MiddleRight;
        lblcboTransitionMethod.Margin = new Padding(6, 8, 6, 8);
        cboTransitionMethod = new ComboBox();
        cboTransitionMethod.Name = "cboTransitionMethod";
        cboTransitionMethod.AccessibleName = "رقم طريقة احتساب الضريبة للفترة الانتقالية";
        cboTransitionMethod.Dock = DockStyle.Fill;
        cboTransitionMethod.TabIndex = 8;
        cboTransitionMethod.Margin = new Padding(6, 8, 6, 8);
        cboTransitionMethod.DropDownStyle = ComboBoxStyle.DropDownList;
        cboTransitionMethod.Enabled = false;
        cboTransitionMethod.AccessibleDescription = "القائمة غير مرتبطة ببيانات بعد.";
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblcboTransitionMethod, 0, 8);
        fields.Controls.Add(cboTransitionMethod, 1, 8);
        lblchkStopped = new Label();
        lblchkStopped.Name = "lblchkStopped";
        lblchkStopped.Text = "موقف";
        lblchkStopped.AutoSize = true;
        lblchkStopped.Dock = DockStyle.Fill;
        lblchkStopped.TextAlign = ContentAlignment.MiddleRight;
        lblchkStopped.Margin = new Padding(6, 8, 6, 8);
        chkStopped = new CheckBox();
        chkStopped.Name = "chkStopped";
        chkStopped.AccessibleName = "موقف";
        chkStopped.Dock = DockStyle.Fill;
        chkStopped.TabIndex = 9;
        chkStopped.Margin = new Padding(6, 8, 6, 8);
        chkStopped.AutoSize = true;
        fields.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        fields.Controls.Add(lblchkStopped, 0, 9);
        fields.Controls.Add(chkStopped, 1, 9);
        tabsSetup = new TabControl();
        tabsSetup.Name = "tabsSetup";
        tabsSetup.Dock = DockStyle.Fill;
        tabsSetup.Height = 340;
        tabsSetup.MinimumSize = new Size(0, 340);
        tabsSetup.RightToLeft = RightToLeft.Yes;
        tabsSetup.RightToLeftLayout = true;
        tabsSetup.TabIndex = 2;
        layout.Controls.Add(tabsSetup, 0, 4);
        gridTaxTypes = new DataGridView();
        ((System.ComponentModel.ISupportInitialize)gridTaxTypes).BeginInit();
        gridTaxTypes.Name = "gridTaxTypes";
        gridTaxTypes.AccessibleName = "أنواع الضرائب";
        gridTaxTypes.Dock = DockStyle.Fill;
        gridTaxTypes.Height = 220;
        gridTaxTypes.MinimumSize = new Size(0, 220);
        gridTaxTypes.AutoGenerateColumns = false;
        gridTaxTypes.ReadOnly = false;
        gridTaxTypes.AllowUserToAddRows = true;
        gridTaxTypes.AllowUserToDeleteRows = false;
        gridTaxTypes.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        gridTaxTypes.RowHeadersVisible = false;
        gridTaxTypes.Enabled = false;
        gridTaxTypes.TabIndex = 2;
        gridTaxTypes.CurrentCellDirtyStateChanged += grid_CurrentCellDirtyStateChanged;
        gridTaxTypes_colTaxType = new DataGridViewComboBoxColumn();
        gridTaxTypes_colTaxType.Name = "colTaxType";
        gridTaxTypes_colTaxType.HeaderText = "نوع الضريبة";
        gridTaxTypes_colTaxType.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridTaxTypes_colTaxType.ReadOnly = true;
        gridTaxTypes_colTaxType.DisplayStyle = DataGridViewComboBoxDisplayStyle.Nothing;
        gridTaxTypes_colTaxType.ToolTipText = "القائمة غير مرتبطة ببيانات بعد.";
        gridTaxTypes.Columns.AddRange(gridTaxTypes_colTaxType);
        tabgridTaxTypes = new TabPage();
        tabgridTaxTypes.Name = "tabgridTaxTypes";
        tabgridTaxTypes.Text = "أنواع الضرائب";
        tabgridTaxTypes.Controls.Add(gridTaxTypes);
        tabsSetup.TabPages.Add(tabgridTaxTypes);
        ((System.ComponentModel.ISupportInitialize)gridTaxTypes).EndInit();
        gridBranches = new DataGridView();
        ((System.ComponentModel.ISupportInitialize)gridBranches).BeginInit();
        gridBranches.Name = "gridBranches";
        gridBranches.AccessibleName = "الفروع";
        gridBranches.Dock = DockStyle.Fill;
        gridBranches.Height = 220;
        gridBranches.MinimumSize = new Size(0, 220);
        gridBranches.AutoGenerateColumns = false;
        gridBranches.ReadOnly = false;
        gridBranches.AllowUserToAddRows = true;
        gridBranches.AllowUserToDeleteRows = false;
        gridBranches.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        gridBranches.RowHeadersVisible = false;
        gridBranches.Enabled = false;
        gridBranches.TabIndex = 2;
        gridBranches.CurrentCellDirtyStateChanged += grid_CurrentCellDirtyStateChanged;
        gridBranches_colBranch = new DataGridViewComboBoxColumn();
        gridBranches_colBranch.Name = "colBranch";
        gridBranches_colBranch.HeaderText = "الفروع";
        gridBranches_colBranch.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridBranches_colBranch.ReadOnly = true;
        gridBranches_colBranch.DisplayStyle = DataGridViewComboBoxDisplayStyle.Nothing;
        gridBranches_colBranch.ToolTipText = "القائمة غير مرتبطة ببيانات بعد.";
        gridBranches_colActivationStart = new DataGridViewTextBoxColumn();
        gridBranches_colActivationStart.Name = "colActivationStart";
        gridBranches_colActivationStart.HeaderText = "تاريخ بداية تفعيل العمل بالطريقة";
        gridBranches_colActivationStart.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridBranches_colActivationEnd = new DataGridViewTextBoxColumn();
        gridBranches_colActivationEnd.Name = "colActivationEnd";
        gridBranches_colActivationEnd.HeaderText = "تاريخ الانتهاء";
        gridBranches_colActivationEnd.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridBranches_colTransition = new DataGridViewCheckBoxColumn();
        gridBranches_colTransition.Name = "colTransition";
        gridBranches_colTransition.HeaderText = "له فترة انتقالية";
        gridBranches_colTransition.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridBranches_colTransitionStart = new DataGridViewTextBoxColumn();
        gridBranches_colTransitionStart.Name = "colTransitionStart";
        gridBranches_colTransitionStart.HeaderText = "تاريخ بداية الفترة الانتقالية";
        gridBranches_colTransitionStart.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridBranches_colTransitionEnd = new DataGridViewTextBoxColumn();
        gridBranches_colTransitionEnd.Name = "colTransitionEnd";
        gridBranches_colTransitionEnd.HeaderText = "تاريخ نهاية الفترة الانتقالية";
        gridBranches_colTransitionEnd.SortMode = DataGridViewColumnSortMode.NotSortable;
        gridBranches.Columns.AddRange(gridBranches_colBranch, gridBranches_colActivationStart, gridBranches_colActivationEnd, gridBranches_colTransition, gridBranches_colTransitionStart, gridBranches_colTransitionEnd);
        tabgridBranches = new TabPage();
        tabgridBranches.Name = "tabgridBranches";
        tabgridBranches.Text = "الفروع";
        tabgridBranches.Controls.Add(gridBranches);
        tabsSetup.TabPages.Add(tabgridBranches);
        ((System.ComponentModel.ISupportInitialize)gridBranches).EndInit();
        standardCommandAdd.Name = "btnAdd";
        standardCommandAdd.Enabled = true;
        standardCommandAdd.Click += draftAction_Click;
        standardCommandSave.Name = "btnSave";
        standardCommandSave.Enabled = false;
        standardAuditMetadata.Name = "standardAuditMetadata";
        standardAuditMetadata.Dock = DockStyle.Bottom;
        standardAuditMetadata.Margin = Padding.Empty;
        standardAuditMetadata.TabStop = false;
        standardAuditMetadata.Size = new Size(800, 64);
        layout.Controls.Add(lblTitle, 0, 0);
        layout.Controls.Add(lblStatus, 0, 1);
        layout.Controls.Add(designerCommandBar, 0, 2);
        layout.Controls.Add(fields, 0, 3);
        Controls.Add(layout);


        Name = "UcTaxCalculationMethods";
        Text = "طرق احتساب الضرائب";
        Size = new Size(1000, 640);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        RightToLeft = RightToLeft.Yes;
        fields.ResumeLayout(true);
        layout.ResumeLayout(true);
        ResumeLayout(true);
        Controls.Add(standardAuditMetadata);
        standardAuditMetadata.SendToBack();
    }
}
