using TransportERP.Desktop.CoreUI;
namespace TransportERP.Desktop.Forms.Templates;
partial class CommandBarDesignerSample
{
    private void InitializeComponent()
    {
        commandBar = new DesignerCommandBar();
        commandFlow = new FlowLayoutPanel();
        closeHost = new Panel();
        cmdAdd = new Button();
        cmdEdit = new Button();
        cmdDelete = new Button();
        cmdCancel = new Button();
        cmdView = new Button();
        cmdLast = new Button();
        cmdNext = new Button();
        cmdPrevious = new Button();
        cmdFirst = new Button();
        cmdSave = new Button();
        cmdPrint = new Button();
        cmdClose = new Button();
        cmdRefresh = new Button();
        cmdImport = new Button();
        cmdExport = new Button();
        cmdHelp = new Button();
        SuspendLayout();
        commandBar.SuspendLayout();
        commandFlow.SuspendLayout();
        commandBar.Name = "commandBar";
        commandBar.Dock = DockStyle.Top;
        commandBar.Size = new Size(900, 48);
        commandBar.BorderStyle = BorderStyle.FixedSingle;
        commandBar.BackColor = Color.FromArgb(239, 239, 239);
        commandFlow.Name = "commandFlow";
        commandFlow.Dock = DockStyle.Fill;
        commandFlow.FlowDirection = FlowDirection.RightToLeft;
        commandFlow.RightToLeft = RightToLeft.No;
        commandFlow.WrapContents = false;
        commandFlow.AutoScroll = true;
        closeHost.Name = "closeHost";
        closeHost.Dock = DockStyle.Left;
        closeHost.Width = 28;
        cmdAdd.Name = "cmdAdd";
        cmdAdd.AccessibleName = "إضافة";
        cmdAdd.Size = new Size(26, 24);
        cmdAdd.Margin = new Padding(1);
        cmdAdd.FlatStyle = FlatStyle.Flat;
        cmdAdd.Enabled = true;
        cmdAdd.Visible = true;
        cmdAdd.TabIndex = 0;
        cmdAdd.Image = CommandBarImages.Add;
        commandFlow.Controls.Add(cmdAdd);
        commandBar.SetCommandRole(cmdAdd, DesignerCommandRole.Add);
        cmdEdit.Name = "cmdEdit";
        cmdEdit.AccessibleName = "تعديل";
        cmdEdit.Size = new Size(26, 24);
        cmdEdit.Margin = new Padding(1);
        cmdEdit.FlatStyle = FlatStyle.Flat;
        cmdEdit.Enabled = false;
        cmdEdit.Visible = true;
        cmdEdit.TabIndex = 1;
        cmdEdit.Image = CommandBarImages.Edit;
        commandFlow.Controls.Add(cmdEdit);
        commandBar.SetCommandRole(cmdEdit, DesignerCommandRole.Edit);
        cmdDelete.Name = "cmdDelete";
        cmdDelete.AccessibleName = "حذف";
        cmdDelete.Size = new Size(26, 24);
        cmdDelete.Margin = new Padding(1);
        cmdDelete.FlatStyle = FlatStyle.Flat;
        cmdDelete.Enabled = false;
        cmdDelete.Visible = true;
        cmdDelete.TabIndex = 2;
        cmdDelete.Image = CommandBarImages.Delete;
        commandFlow.Controls.Add(cmdDelete);
        commandBar.SetCommandRole(cmdDelete, DesignerCommandRole.Delete);
        cmdCancel.Name = "cmdCancel";
        cmdCancel.AccessibleName = "تراجع";
        cmdCancel.Size = new Size(26, 24);
        cmdCancel.Margin = new Padding(1);
        cmdCancel.FlatStyle = FlatStyle.Flat;
        cmdCancel.Enabled = false;
        cmdCancel.Visible = true;
        cmdCancel.TabIndex = 3;
        cmdCancel.Image = CommandBarImages.Cancel;
        commandFlow.Controls.Add(cmdCancel);
        commandBar.SetCommandRole(cmdCancel, DesignerCommandRole.Cancel);
        cmdView.Name = "cmdView";
        cmdView.AccessibleName = "عرض / بحث";
        cmdView.Size = new Size(26, 24);
        cmdView.Margin = new Padding(1);
        cmdView.FlatStyle = FlatStyle.Flat;
        cmdView.Enabled = false;
        cmdView.Visible = true;
        cmdView.TabIndex = 4;
        cmdView.Image = CommandBarImages.View;
        commandFlow.Controls.Add(cmdView);
        commandBar.SetCommandRole(cmdView, DesignerCommandRole.View);
        cmdLast.Name = "cmdLast";
        cmdLast.AccessibleName = "آخر سجل";
        cmdLast.Size = new Size(26, 24);
        cmdLast.Margin = new Padding(1);
        cmdLast.FlatStyle = FlatStyle.Flat;
        cmdLast.Enabled = false;
        cmdLast.Visible = true;
        cmdLast.TabIndex = 5;
        cmdLast.Image = CommandBarImages.Last;
        commandFlow.Controls.Add(cmdLast);
        commandBar.SetCommandRole(cmdLast, DesignerCommandRole.Last);
        cmdNext.Name = "cmdNext";
        cmdNext.AccessibleName = "التالي";
        cmdNext.Size = new Size(26, 24);
        cmdNext.Margin = new Padding(1);
        cmdNext.FlatStyle = FlatStyle.Flat;
        cmdNext.Enabled = false;
        cmdNext.Visible = true;
        cmdNext.TabIndex = 6;
        cmdNext.Image = CommandBarImages.Next;
        commandFlow.Controls.Add(cmdNext);
        commandBar.SetCommandRole(cmdNext, DesignerCommandRole.Next);
        cmdPrevious.Name = "cmdPrevious";
        cmdPrevious.AccessibleName = "السابق";
        cmdPrevious.Size = new Size(26, 24);
        cmdPrevious.Margin = new Padding(1);
        cmdPrevious.FlatStyle = FlatStyle.Flat;
        cmdPrevious.Enabled = false;
        cmdPrevious.Visible = true;
        cmdPrevious.TabIndex = 7;
        cmdPrevious.Image = CommandBarImages.Previous;
        commandFlow.Controls.Add(cmdPrevious);
        commandBar.SetCommandRole(cmdPrevious, DesignerCommandRole.Previous);
        cmdFirst.Name = "cmdFirst";
        cmdFirst.AccessibleName = "أول سجل";
        cmdFirst.Size = new Size(26, 24);
        cmdFirst.Margin = new Padding(1);
        cmdFirst.FlatStyle = FlatStyle.Flat;
        cmdFirst.Enabled = false;
        cmdFirst.Visible = true;
        cmdFirst.TabIndex = 8;
        cmdFirst.Image = CommandBarImages.First;
        commandFlow.Controls.Add(cmdFirst);
        commandBar.SetCommandRole(cmdFirst, DesignerCommandRole.First);
        cmdSave.Name = "cmdSave";
        cmdSave.AccessibleName = "حفظ";
        cmdSave.Size = new Size(26, 24);
        cmdSave.Margin = new Padding(1);
        cmdSave.FlatStyle = FlatStyle.Flat;
        cmdSave.Enabled = false;
        cmdSave.Visible = true;
        cmdSave.TabIndex = 9;
        cmdSave.Image = CommandBarImages.Save;
        commandFlow.Controls.Add(cmdSave);
        commandBar.SetCommandRole(cmdSave, DesignerCommandRole.Save);
        cmdPrint.Name = "cmdPrint";
        cmdPrint.AccessibleName = "طباعة";
        cmdPrint.Size = new Size(26, 24);
        cmdPrint.Margin = new Padding(1);
        cmdPrint.FlatStyle = FlatStyle.Flat;
        cmdPrint.Enabled = false;
        cmdPrint.Visible = true;
        cmdPrint.TabIndex = 10;
        cmdPrint.Image = CommandBarImages.Print;
        commandFlow.Controls.Add(cmdPrint);
        commandBar.SetCommandRole(cmdPrint, DesignerCommandRole.Print);
        cmdClose.Name = "cmdClose";
        cmdClose.AccessibleName = "خروج";
        cmdClose.Size = new Size(26, 24);
        cmdClose.Margin = new Padding(1);
        cmdClose.FlatStyle = FlatStyle.Flat;
        cmdClose.Enabled = true;
        cmdClose.Visible = true;
        cmdClose.TabIndex = 11;
        cmdClose.Image = CommandBarImages.Close;
        cmdClose.Location = new Point(1, 1);
        closeHost.Controls.Add(cmdClose);
        commandBar.SetCommandRole(cmdClose, DesignerCommandRole.Close);
        cmdRefresh.Name = "cmdRefresh";
        cmdRefresh.AccessibleName = "تحديث";
        cmdRefresh.Size = new Size(26, 24);
        cmdRefresh.Margin = new Padding(1);
        cmdRefresh.FlatStyle = FlatStyle.Flat;
        cmdRefresh.Enabled = false;
        cmdRefresh.Visible = false;
        cmdRefresh.TabIndex = 12;
        commandFlow.Controls.Add(cmdRefresh);
        commandBar.SetCommandRole(cmdRefresh, DesignerCommandRole.Refresh);
        cmdImport.Name = "cmdImport";
        cmdImport.AccessibleName = "استيراد";
        cmdImport.Size = new Size(26, 24);
        cmdImport.Margin = new Padding(1);
        cmdImport.FlatStyle = FlatStyle.Flat;
        cmdImport.Enabled = false;
        cmdImport.Visible = false;
        cmdImport.TabIndex = 13;
        commandFlow.Controls.Add(cmdImport);
        commandBar.SetCommandRole(cmdImport, DesignerCommandRole.Import);
        cmdExport.Name = "cmdExport";
        cmdExport.AccessibleName = "تصدير";
        cmdExport.Size = new Size(26, 24);
        cmdExport.Margin = new Padding(1);
        cmdExport.FlatStyle = FlatStyle.Flat;
        cmdExport.Enabled = false;
        cmdExport.Visible = false;
        cmdExport.TabIndex = 14;
        commandFlow.Controls.Add(cmdExport);
        commandBar.SetCommandRole(cmdExport, DesignerCommandRole.Export);
        cmdHelp.Name = "cmdHelp";
        cmdHelp.AccessibleName = "مساعدة";
        cmdHelp.Size = new Size(26, 24);
        cmdHelp.Margin = new Padding(1);
        cmdHelp.FlatStyle = FlatStyle.Flat;
        cmdHelp.Enabled = false;
        cmdHelp.Visible = false;
        cmdHelp.TabIndex = 15;
        commandFlow.Controls.Add(cmdHelp);
        commandBar.SetCommandRole(cmdHelp, DesignerCommandRole.Help);
        cmdAdd.Click += AddClicked;
        commandBar.Controls.Add(commandFlow);
        commandBar.Controls.Add(closeHost);
        Controls.Add(commandBar);
        AutoScaleMode = AutoScaleMode.Dpi;
        AutoScaleDimensions = new SizeF(96F, 96F);
        Name = "CommandBarDesignerSample";
        Size = new Size(900, 120);
        commandFlow.ResumeLayout(false);
        commandBar.ResumeLayout(false);
        ResumeLayout(false);
    }
    private DesignerCommandBar commandBar;
    private FlowLayoutPanel commandFlow;
    private Panel closeHost;
    private Button cmdAdd;
    private Button cmdEdit;
    private Button cmdDelete;
    private Button cmdCancel;
    private Button cmdView;
    private Button cmdLast;
    private Button cmdNext;
    private Button cmdPrevious;
    private Button cmdFirst;
    private Button cmdSave;
    private Button cmdPrint;
    private Button cmdClose;
    private Button cmdRefresh;
    private Button cmdImport;
    private Button cmdExport;
    private Button cmdHelp;
}
