#nullable enable

using TransportERP.Desktop.CoreUI;

namespace TransportERP.Desktop.Forms.Templates;

partial class FrmDashboardTemplate
{
    private System.ComponentModel.IContainer? components; private Panel pnlHeader = null!; private Label lblTitle = null!; private Label lblSubtitle = null!; private Panel pnlToolbar = null!; private FlowLayoutPanel flpToolbar = null!; private Button btnRefresh = null!; private Button btnExport = null!; private TableLayoutPanel tlpShell = null!; private Panel pnlNavigation = null!; private Label lblNavigation = null!; private TableLayoutPanel tlpContent = null!; private GroupBox grpSummary = null!; private Panel pnlSummaryPlaceholder = null!; private GroupBox grpActivity = null!; private DataGridView dgvActivity = null!; private StatusStrip statusStrip = null!; private ToolStripStatusLabel lblStatus = null!;
    protected override void Dispose(bool disposing) { if (disposing && components is not null) components.Dispose(); base.Dispose(disposing); }
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container(); pnlHeader = new Panel(); lblSubtitle = new Label(); lblTitle = new Label(); pnlToolbar = new Panel(); flpToolbar = new FlowLayoutPanel(); btnRefresh = new Button(); btnExport = new Button(); tlpShell = new TableLayoutPanel(); pnlNavigation = new Panel(); lblNavigation = new Label(); tlpContent = new TableLayoutPanel(); grpSummary = new GroupBox(); pnlSummaryPlaceholder = new Panel(); grpActivity = new GroupBox(); dgvActivity = new DataGridView(); statusStrip = new StatusStrip(); lblStatus = new ToolStripStatusLabel(); ((System.ComponentModel.ISupportInitialize)dgvActivity).BeginInit();
        pnlHeader.Controls.Add(lblSubtitle); pnlHeader.Controls.Add(lblTitle); pnlHeader.Dock = DockStyle.Top; pnlHeader.Name = "pnlHeader"; lblTitle.Dock = DockStyle.Top; lblTitle.Height = 45; lblTitle.Name = "lblTitle"; lblTitle.Text = "عنوان لوحة التحكم"; lblSubtitle.Dock = DockStyle.Fill; lblSubtitle.Name = "lblSubtitle"; lblSubtitle.Text = "سياق الشركة والفرع والفترة";
        pnlToolbar.Controls.Add(flpToolbar); pnlToolbar.Dock = DockStyle.Top; pnlToolbar.Height = UiDesignTokens.ActionBarHeight; pnlToolbar.Name = "pnlToolbar"; pnlToolbar.Padding = new Padding(4); flpToolbar.Controls.Add(btnRefresh); flpToolbar.Controls.Add(btnExport); flpToolbar.Dock = DockStyle.Fill; flpToolbar.FlowDirection = FlowDirection.RightToLeft; flpToolbar.Name = "flpToolbar"; flpToolbar.WrapContents = false; btnRefresh.Name = "btnRefresh"; btnRefresh.TabIndex = 0; btnRefresh.Text = "تحديث"; btnExport.Name = "btnExport"; btnExport.TabIndex = 1; btnExport.Text = "تصدير";
        tlpShell.ColumnCount = 2; tlpShell.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 240F)); tlpShell.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F)); tlpShell.Controls.Add(pnlNavigation, 0, 0); tlpShell.Controls.Add(tlpContent, 1, 0); tlpShell.Dock = DockStyle.Fill; tlpShell.Name = "tlpShell"; tlpShell.RightToLeft = RightToLeft.Yes; tlpShell.TabIndex = 0;
        pnlNavigation.BackColor = UiDesignTokens.PrimaryStrong; pnlNavigation.Controls.Add(lblNavigation); pnlNavigation.Dock = DockStyle.Fill; pnlNavigation.Name = "pnlNavigation"; pnlNavigation.Padding = new Padding(4); lblNavigation.Dock = DockStyle.Top; lblNavigation.ForeColor = Color.White; lblNavigation.Height = 48; lblNavigation.Name = "lblNavigation"; lblNavigation.Text = "منطقة التنقل"; lblNavigation.TextAlign = ContentAlignment.MiddleRight;
        tlpContent.ColumnCount = 1; tlpContent.Controls.Add(grpSummary, 0, 0); tlpContent.Controls.Add(grpActivity, 0, 1); tlpContent.Dock = DockStyle.Fill; tlpContent.Name = "tlpContent"; tlpContent.Padding = new Padding(4); tlpContent.RowCount = 2; tlpContent.RowStyles.Add(new RowStyle(SizeType.Percent, 42F)); tlpContent.RowStyles.Add(new RowStyle(SizeType.Percent, 58F));
        grpSummary.Controls.Add(pnlSummaryPlaceholder); grpSummary.Dock = DockStyle.Fill; grpSummary.Name = "grpSummary"; grpSummary.Text = "مؤشرات مختصرة"; pnlSummaryPlaceholder.Dock = DockStyle.Fill; pnlSummaryPlaceholder.Name = "pnlSummaryPlaceholder";
        grpActivity.Controls.Add(dgvActivity); grpActivity.Dock = DockStyle.Fill; grpActivity.Name = "grpActivity"; grpActivity.Text = "آخر الأنشطة"; dgvActivity.Dock = DockStyle.Fill; dgvActivity.Name = "dgvActivity"; dgvActivity.TabIndex = 0;
        statusStrip.Items.Add(lblStatus); statusStrip.Name = "statusStrip"; lblStatus.Name = "lblStatus"; lblStatus.Text = "جاهز"; AutoScaleMode = AutoScaleMode.Font; ClientSize = new Size(1280, 800); Controls.Add(tlpShell); Controls.Add(pnlToolbar); Controls.Add(statusStrip); Controls.Add(pnlHeader); Name = "FrmDashboardTemplate"; Text = "Dashboard Template"; SettingsFormStyle.ApplyFormStyle(this, true); SettingsFormStyle.ApplyHeaderStyle(pnlHeader, lblTitle, lblSubtitle); SettingsFormStyle.ApplyNeutralButtonStyle(btnRefresh); SettingsFormStyle.ApplySecondaryButtonStyle(btnExport); SettingsFormStyle.ApplySectionStyle(grpSummary); SettingsFormStyle.ApplySectionStyle(grpActivity); SettingsFormStyle.ApplyGridStyle(dgvActivity); ((System.ComponentModel.ISupportInitialize)dgvActivity).EndInit();
    }
}
