#nullable enable
namespace TransportERP.Desktop.CoreUI;
partial class AuditMetadataControl
{
    private System.ComponentModel.IContainer? components;
    private TableLayoutPanel auditInfoContainer = null!;
    protected override void Dispose(bool disposing) { if (disposing) components?.Dispose(); base.Dispose(disposing); }
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        auditInfoContainer = new TableLayoutPanel();
        SuspendLayout();
        auditInfoContainer.SuspendLayout();
        auditInfoContainer.Name = "auditInfoContainer";
        auditInfoContainer.ColumnCount = 9;
        auditInfoContainer.RowCount = 2;
        auditInfoContainer.Dock = DockStyle.Fill;
        auditInfoContainer.Height = 60;
        auditInfoContainer.MinimumSize = new Size(800, 60);
        auditInfoContainer.Margin = Padding.Empty;
        auditInfoContainer.Padding = new Padding(2);
        auditInfoContainer.BorderStyle = BorderStyle.FixedSingle;
        auditInfoContainer.BackColor = Color.FromArgb(232, 227, 246);
        auditInfoContainer.RightToLeft = RightToLeft.Yes;
        auditInfoContainer.GrowStyle = TableLayoutPanelGrowStyle.FixedSize;
        auditInfoContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 110F));
        auditInfoContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 40F));
        auditInfoContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 31F));
        auditInfoContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 110F));
        auditInfoContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 31F));
        auditInfoContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 110F));
        auditInfoContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 26F));
        auditInfoContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 100F));
        auditInfoContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 12F));
        auditInfoContainer.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        auditInfoContainer.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        auditCaptionCreatedBy = new Label();
        auditCaptionCreatedBy.Name = "auditCaptionCreatedBy";
        auditCaptionCreatedBy.Dock = DockStyle.Fill;
        auditCaptionCreatedBy.AutoSize = false;
        auditCaptionCreatedBy.TabStop = false;
        auditCaptionCreatedBy.Font = new Font("Tahoma", 9F);
        auditCaptionCreatedBy.ForeColor = Color.FromArgb(32, 32, 32);
        auditValueCreatedBy = new TextBox();
        auditValueCreatedBy.Name = "auditValueCreatedBy";
        auditValueCreatedBy.Dock = DockStyle.Fill;
        auditValueCreatedBy.AutoSize = false;
        auditValueCreatedBy.TabStop = false;
        auditValueCreatedBy.Font = new Font("Tahoma", 9F);
        auditValueCreatedBy.ForeColor = Color.FromArgb(32, 32, 32);
        auditCaptionCreatedBy.Text = "مدخل السجل";
        auditCaptionCreatedBy.TextAlign = ContentAlignment.MiddleRight;
        auditCaptionCreatedBy.Margin = new Padding(1);
        auditCaptionCreatedBy.BackColor = Color.Transparent;
        auditValueCreatedBy.ReadOnly = true;
        auditValueCreatedBy.Enabled = true;
        auditValueCreatedBy.AccessibleName = "مدخل السجل";
        auditValueCreatedBy.Margin = new Padding(1, 2, 1, 2);
        auditValueCreatedBy.BackColor = Color.FromArgb(244, 244, 244);
        auditValueCreatedBy.BorderStyle = BorderStyle.FixedSingle;
        auditValueCreatedBy.RightToLeft = RightToLeft.Yes;
        auditValueCreatedBy.TextAlign = HorizontalAlignment.Right;
        auditInfoContainer.Controls.Add(auditCaptionCreatedBy, 0, 0);
        auditInfoContainer.Controls.Add(auditValueCreatedBy, 2, 0);
        auditCaptionUpdatedBy = new Label();
        auditCaptionUpdatedBy.Name = "auditCaptionUpdatedBy";
        auditCaptionUpdatedBy.Dock = DockStyle.Fill;
        auditCaptionUpdatedBy.AutoSize = false;
        auditCaptionUpdatedBy.TabStop = false;
        auditCaptionUpdatedBy.Font = new Font("Tahoma", 9F);
        auditCaptionUpdatedBy.ForeColor = Color.FromArgb(32, 32, 32);
        auditValueUpdatedBy = new TextBox();
        auditValueUpdatedBy.Name = "auditValueUpdatedBy";
        auditValueUpdatedBy.Dock = DockStyle.Fill;
        auditValueUpdatedBy.AutoSize = false;
        auditValueUpdatedBy.TabStop = false;
        auditValueUpdatedBy.Font = new Font("Tahoma", 9F);
        auditValueUpdatedBy.ForeColor = Color.FromArgb(32, 32, 32);
        auditCaptionUpdatedBy.Text = "معدل السجل";
        auditCaptionUpdatedBy.TextAlign = ContentAlignment.MiddleRight;
        auditCaptionUpdatedBy.Margin = new Padding(1);
        auditCaptionUpdatedBy.BackColor = Color.Transparent;
        auditValueUpdatedBy.ReadOnly = true;
        auditValueUpdatedBy.Enabled = true;
        auditValueUpdatedBy.AccessibleName = "معدل السجل";
        auditValueUpdatedBy.Margin = new Padding(1, 2, 1, 2);
        auditValueUpdatedBy.BackColor = Color.FromArgb(244, 244, 244);
        auditValueUpdatedBy.BorderStyle = BorderStyle.FixedSingle;
        auditValueUpdatedBy.RightToLeft = RightToLeft.Yes;
        auditValueUpdatedBy.TextAlign = HorizontalAlignment.Right;
        auditInfoContainer.Controls.Add(auditCaptionUpdatedBy, 0, 1);
        auditInfoContainer.Controls.Add(auditValueUpdatedBy, 2, 1);
        auditCaptionCreatedAt = new Label();
        auditCaptionCreatedAt.Name = "auditCaptionCreatedAt";
        auditCaptionCreatedAt.Dock = DockStyle.Fill;
        auditCaptionCreatedAt.AutoSize = false;
        auditCaptionCreatedAt.TabStop = false;
        auditCaptionCreatedAt.Font = new Font("Tahoma", 9F);
        auditCaptionCreatedAt.ForeColor = Color.FromArgb(32, 32, 32);
        auditValueCreatedAt = new TextBox();
        auditValueCreatedAt.Name = "auditValueCreatedAt";
        auditValueCreatedAt.Dock = DockStyle.Fill;
        auditValueCreatedAt.AutoSize = false;
        auditValueCreatedAt.TabStop = false;
        auditValueCreatedAt.Font = new Font("Tahoma", 9F);
        auditValueCreatedAt.ForeColor = Color.FromArgb(32, 32, 32);
        auditCaptionCreatedAt.Text = "تاريخ الإدخال";
        auditCaptionCreatedAt.TextAlign = ContentAlignment.MiddleRight;
        auditCaptionCreatedAt.Margin = new Padding(1);
        auditCaptionCreatedAt.BackColor = Color.Transparent;
        auditValueCreatedAt.ReadOnly = true;
        auditValueCreatedAt.Enabled = true;
        auditValueCreatedAt.AccessibleName = "تاريخ الإدخال";
        auditValueCreatedAt.Margin = new Padding(1, 2, 1, 2);
        auditValueCreatedAt.BackColor = Color.FromArgb(244, 244, 244);
        auditValueCreatedAt.BorderStyle = BorderStyle.FixedSingle;
        auditValueCreatedAt.RightToLeft = RightToLeft.No;
        auditValueCreatedAt.TextAlign = HorizontalAlignment.Left;
        auditInfoContainer.Controls.Add(auditCaptionCreatedAt, 3, 0);
        auditInfoContainer.Controls.Add(auditValueCreatedAt, 4, 0);
        auditCaptionUpdatedAt = new Label();
        auditCaptionUpdatedAt.Name = "auditCaptionUpdatedAt";
        auditCaptionUpdatedAt.Dock = DockStyle.Fill;
        auditCaptionUpdatedAt.AutoSize = false;
        auditCaptionUpdatedAt.TabStop = false;
        auditCaptionUpdatedAt.Font = new Font("Tahoma", 9F);
        auditCaptionUpdatedAt.ForeColor = Color.FromArgb(32, 32, 32);
        auditValueUpdatedAt = new TextBox();
        auditValueUpdatedAt.Name = "auditValueUpdatedAt";
        auditValueUpdatedAt.Dock = DockStyle.Fill;
        auditValueUpdatedAt.AutoSize = false;
        auditValueUpdatedAt.TabStop = false;
        auditValueUpdatedAt.Font = new Font("Tahoma", 9F);
        auditValueUpdatedAt.ForeColor = Color.FromArgb(32, 32, 32);
        auditCaptionUpdatedAt.Text = "تاريخ آخر تعديل";
        auditCaptionUpdatedAt.TextAlign = ContentAlignment.MiddleRight;
        auditCaptionUpdatedAt.Margin = new Padding(1);
        auditCaptionUpdatedAt.BackColor = Color.Transparent;
        auditValueUpdatedAt.ReadOnly = true;
        auditValueUpdatedAt.Enabled = true;
        auditValueUpdatedAt.AccessibleName = "تاريخ آخر تعديل";
        auditValueUpdatedAt.Margin = new Padding(1, 2, 1, 2);
        auditValueUpdatedAt.BackColor = Color.FromArgb(244, 244, 244);
        auditValueUpdatedAt.BorderStyle = BorderStyle.FixedSingle;
        auditValueUpdatedAt.RightToLeft = RightToLeft.No;
        auditValueUpdatedAt.TextAlign = HorizontalAlignment.Left;
        auditInfoContainer.Controls.Add(auditCaptionUpdatedAt, 3, 1);
        auditInfoContainer.Controls.Add(auditValueUpdatedAt, 4, 1);
        auditCaptionCreatedDevice = new Label();
        auditCaptionCreatedDevice.Name = "auditCaptionCreatedDevice";
        auditCaptionCreatedDevice.Dock = DockStyle.Fill;
        auditCaptionCreatedDevice.AutoSize = false;
        auditCaptionCreatedDevice.TabStop = false;
        auditCaptionCreatedDevice.Font = new Font("Tahoma", 9F);
        auditCaptionCreatedDevice.ForeColor = Color.FromArgb(32, 32, 32);
        auditValueCreatedDevice = new TextBox();
        auditValueCreatedDevice.Name = "auditValueCreatedDevice";
        auditValueCreatedDevice.Dock = DockStyle.Fill;
        auditValueCreatedDevice.AutoSize = false;
        auditValueCreatedDevice.TabStop = false;
        auditValueCreatedDevice.Font = new Font("Tahoma", 9F);
        auditValueCreatedDevice.ForeColor = Color.FromArgb(32, 32, 32);
        auditCaptionCreatedDevice.Text = "الجهاز المدخل";
        auditCaptionCreatedDevice.TextAlign = ContentAlignment.MiddleRight;
        auditCaptionCreatedDevice.Margin = new Padding(1);
        auditCaptionCreatedDevice.BackColor = Color.Transparent;
        auditValueCreatedDevice.ReadOnly = true;
        auditValueCreatedDevice.Enabled = true;
        auditValueCreatedDevice.AccessibleName = "الجهاز المدخل";
        auditValueCreatedDevice.Margin = new Padding(1, 2, 1, 2);
        auditValueCreatedDevice.BackColor = Color.FromArgb(244, 244, 244);
        auditValueCreatedDevice.BorderStyle = BorderStyle.FixedSingle;
        auditValueCreatedDevice.RightToLeft = RightToLeft.No;
        auditValueCreatedDevice.TextAlign = HorizontalAlignment.Left;
        auditInfoContainer.Controls.Add(auditCaptionCreatedDevice, 5, 0);
        auditInfoContainer.Controls.Add(auditValueCreatedDevice, 6, 0);
        auditCaptionUpdatedDevice = new Label();
        auditCaptionUpdatedDevice.Name = "auditCaptionUpdatedDevice";
        auditCaptionUpdatedDevice.Dock = DockStyle.Fill;
        auditCaptionUpdatedDevice.AutoSize = false;
        auditCaptionUpdatedDevice.TabStop = false;
        auditCaptionUpdatedDevice.Font = new Font("Tahoma", 9F);
        auditCaptionUpdatedDevice.ForeColor = Color.FromArgb(32, 32, 32);
        auditValueUpdatedDevice = new TextBox();
        auditValueUpdatedDevice.Name = "auditValueUpdatedDevice";
        auditValueUpdatedDevice.Dock = DockStyle.Fill;
        auditValueUpdatedDevice.AutoSize = false;
        auditValueUpdatedDevice.TabStop = false;
        auditValueUpdatedDevice.Font = new Font("Tahoma", 9F);
        auditValueUpdatedDevice.ForeColor = Color.FromArgb(32, 32, 32);
        auditCaptionUpdatedDevice.Text = "الجهاز المعدل";
        auditCaptionUpdatedDevice.TextAlign = ContentAlignment.MiddleRight;
        auditCaptionUpdatedDevice.Margin = new Padding(1);
        auditCaptionUpdatedDevice.BackColor = Color.Transparent;
        auditValueUpdatedDevice.ReadOnly = true;
        auditValueUpdatedDevice.Enabled = true;
        auditValueUpdatedDevice.AccessibleName = "الجهاز المعدل";
        auditValueUpdatedDevice.Margin = new Padding(1, 2, 1, 2);
        auditValueUpdatedDevice.BackColor = Color.FromArgb(244, 244, 244);
        auditValueUpdatedDevice.BorderStyle = BorderStyle.FixedSingle;
        auditValueUpdatedDevice.RightToLeft = RightToLeft.No;
        auditValueUpdatedDevice.TextAlign = HorizontalAlignment.Left;
        auditInfoContainer.Controls.Add(auditCaptionUpdatedDevice, 5, 1);
        auditInfoContainer.Controls.Add(auditValueUpdatedDevice, 6, 1);
        auditCaptionPrintCount = new Label();
        auditCaptionPrintCount.Name = "auditCaptionPrintCount";
        auditCaptionPrintCount.Dock = DockStyle.Fill;
        auditCaptionPrintCount.AutoSize = false;
        auditCaptionPrintCount.TabStop = false;
        auditCaptionPrintCount.Font = new Font("Tahoma", 9F);
        auditCaptionPrintCount.ForeColor = Color.FromArgb(32, 32, 32);
        auditValuePrintCount = new TextBox();
        auditValuePrintCount.Name = "auditValuePrintCount";
        auditValuePrintCount.Dock = DockStyle.Fill;
        auditValuePrintCount.AutoSize = false;
        auditValuePrintCount.TabStop = false;
        auditValuePrintCount.Font = new Font("Tahoma", 9F);
        auditValuePrintCount.ForeColor = Color.FromArgb(32, 32, 32);
        auditCaptionPrintCount.Text = "مرات الطباعة";
        auditCaptionPrintCount.TextAlign = ContentAlignment.MiddleRight;
        auditCaptionPrintCount.Margin = new Padding(1);
        auditCaptionPrintCount.BackColor = Color.Transparent;
        auditValuePrintCount.ReadOnly = true;
        auditValuePrintCount.Enabled = true;
        auditValuePrintCount.AccessibleName = "مرات الطباعة";
        auditValuePrintCount.Margin = new Padding(1, 2, 1, 2);
        auditValuePrintCount.BackColor = Color.FromArgb(244, 244, 244);
        auditValuePrintCount.BorderStyle = BorderStyle.FixedSingle;
        auditValuePrintCount.RightToLeft = RightToLeft.No;
        auditValuePrintCount.TextAlign = HorizontalAlignment.Center;
        auditInfoContainer.Controls.Add(auditCaptionPrintCount, 7, 0);
        auditInfoContainer.Controls.Add(auditValuePrintCount, 8, 0);
        auditCaptionUpdateCount = new Label();
        auditCaptionUpdateCount.Name = "auditCaptionUpdateCount";
        auditCaptionUpdateCount.Dock = DockStyle.Fill;
        auditCaptionUpdateCount.AutoSize = false;
        auditCaptionUpdateCount.TabStop = false;
        auditCaptionUpdateCount.Font = new Font("Tahoma", 9F);
        auditCaptionUpdateCount.ForeColor = Color.FromArgb(32, 32, 32);
        auditValueUpdateCount = new TextBox();
        auditValueUpdateCount.Name = "auditValueUpdateCount";
        auditValueUpdateCount.Dock = DockStyle.Fill;
        auditValueUpdateCount.AutoSize = false;
        auditValueUpdateCount.TabStop = false;
        auditValueUpdateCount.Font = new Font("Tahoma", 9F);
        auditValueUpdateCount.ForeColor = Color.FromArgb(32, 32, 32);
        auditCaptionUpdateCount.Text = "مرات التعديل";
        auditCaptionUpdateCount.TextAlign = ContentAlignment.MiddleRight;
        auditCaptionUpdateCount.Margin = new Padding(1);
        auditCaptionUpdateCount.BackColor = Color.Transparent;
        auditValueUpdateCount.ReadOnly = true;
        auditValueUpdateCount.Enabled = true;
        auditValueUpdateCount.AccessibleName = "مرات التعديل";
        auditValueUpdateCount.Margin = new Padding(1, 2, 1, 2);
        auditValueUpdateCount.BackColor = Color.FromArgb(244, 244, 244);
        auditValueUpdateCount.BorderStyle = BorderStyle.FixedSingle;
        auditValueUpdateCount.RightToLeft = RightToLeft.No;
        auditValueUpdateCount.TextAlign = HorizontalAlignment.Center;
        auditInfoContainer.Controls.Add(auditCaptionUpdateCount, 7, 1);
        auditInfoContainer.Controls.Add(auditValueUpdateCount, 8, 1);
        auditValueCreatedByCode = new TextBox();
        auditValueCreatedByCode.Name = "auditValueCreatedByCode";
        auditValueCreatedByCode.Dock = DockStyle.Fill;
        auditValueCreatedByCode.ReadOnly = true;
        auditValueCreatedByCode.TabStop = false;
        auditValueCreatedByCode.AutoSize = false;
        auditValueCreatedByCode.Font = new Font("Tahoma", 9F);
        auditValueCreatedByCode.TextAlign = HorizontalAlignment.Center;
        auditValueCreatedByCode.RightToLeft = RightToLeft.No;
        auditValueCreatedByCode.BorderStyle = BorderStyle.FixedSingle;
        auditValueCreatedByCode.Margin = new Padding(1, 2, 0, 2);
        auditValueCreatedByCode.BackColor = Color.FromArgb(244, 244, 244);
        auditInfoContainer.Controls.Add(auditValueCreatedByCode, 1, 0);
        auditValueUpdatedByCode = new TextBox();
        auditValueUpdatedByCode.Name = "auditValueUpdatedByCode";
        auditValueUpdatedByCode.Dock = DockStyle.Fill;
        auditValueUpdatedByCode.ReadOnly = true;
        auditValueUpdatedByCode.TabStop = false;
        auditValueUpdatedByCode.AutoSize = false;
        auditValueUpdatedByCode.Font = new Font("Tahoma", 9F);
        auditValueUpdatedByCode.TextAlign = HorizontalAlignment.Center;
        auditValueUpdatedByCode.RightToLeft = RightToLeft.No;
        auditValueUpdatedByCode.BorderStyle = BorderStyle.FixedSingle;
        auditValueUpdatedByCode.Margin = new Padding(1, 2, 0, 2);
        auditValueUpdatedByCode.BackColor = Color.FromArgb(244, 244, 244);
        auditInfoContainer.Controls.Add(auditValueUpdatedByCode, 1, 1);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        AutoScroll = true;
        Font = new Font("Tahoma", 9F);
        RightToLeft = RightToLeft.Yes;
        Margin = new Padding(1);
        Padding = Padding.Empty;
        MinimumSize = new Size(0, 64);
        Size = new Size(1020, 64);
        TabStop = false;
        Controls.Add(auditInfoContainer);
        auditValueCreatedByCode.Font = new Font("Tahoma", 9F);
        auditValueCreatedByCode.ForeColor = Color.FromArgb(32, 32, 32);
        auditValueUpdatedByCode.Font = new Font("Tahoma", 9F);
        auditValueUpdatedByCode.ForeColor = Color.FromArgb(32, 32, 32);
        auditInfoContainer.ResumeLayout(false);
        ResumeLayout(false);
    }
    private Label auditCaptionCreatedBy = null!;
    private TextBox auditValueCreatedBy = null!;
    private Label auditCaptionUpdatedBy = null!;
    private TextBox auditValueUpdatedBy = null!;
    private Label auditCaptionCreatedAt = null!;
    private TextBox auditValueCreatedAt = null!;
    private Label auditCaptionUpdatedAt = null!;
    private TextBox auditValueUpdatedAt = null!;
    private Label auditCaptionCreatedDevice = null!;
    private TextBox auditValueCreatedDevice = null!;
    private Label auditCaptionUpdatedDevice = null!;
    private TextBox auditValueUpdatedDevice = null!;
    private Label auditCaptionPrintCount = null!;
    private TextBox auditValuePrintCount = null!;
    private Label auditCaptionUpdateCount = null!;
    private TextBox auditValueUpdateCount = null!;
    private TextBox auditValueCreatedByCode = null!;
    private TextBox auditValueUpdatedByCode = null!;
    private (Control Caption, Control Value) CreateReceiptMetadataField(string key, string caption)
    {
        var label = new Label { Name="auditCaption"+key, Text=caption, Dock=DockStyle.Fill,
            AutoSize=false, Margin=new Padding(1), Padding=new Padding(2,0,2,0),
            TextAlign=ContentAlignment.MiddleRight, Font=new Font("Tahoma",9F),
            ForeColor=Color.FromArgb(32,32,32), TabStop=false };
        var value = new TextBox { Name="auditValue"+key, Dock=DockStyle.Fill, ReadOnly=true,
            Enabled=true, TabStop=false, Margin=new Padding(1), Font=new Font("Tahoma",9F),
            BorderStyle=BorderStyle.FixedSingle,
            RightToLeft=key=="LastPrintedAt"?RightToLeft.No:RightToLeft.Yes,
            TextAlign=key=="LastPrintedAt"?HorizontalAlignment.Left:HorizontalAlignment.Right,
            BackColor=Color.FromArgb(244,244,244), ForeColor=Color.FromArgb(32,32,32) };
        return (label,value);
    }
}
