#nullable enable
using System.ComponentModel;
namespace TransportERP.Desktop.CoreUI;
partial class StandardCommandBar
{
    private IContainer? components;
    protected override void Dispose(bool disposing) { if (disposing) components?.Dispose(); base.Dispose(disposing); }
    private void InitializeComponent()
    {
        components = new Container();
        var resources = new ComponentResourceManager(typeof(StandardCommandBar));
        toolTips = new ToolTip(components);
        commandBarContainer = new Panel();
        commandFlow = new FlowLayoutPanel();
        retainedControls = new Panel();
        closeHost = new Panel();
        cmdAdd = new Button();
        cmdEdit = new Button();
        cmdDelete = new Button();
        cmdCancel = new Button();
        cmdView = new Button();
        cmdLast = new Button();
        cmdNext = new Button();
        cmdPrevious = new Button();
        cmdFirst = new Button();
        cmdSave = new Button();
        cmdPrint = new Button();
        cmdClose = new Button();
        cmdRefresh = new Button();
        cmdImport = new Button();
        cmdExport = new Button();
        cmdHelp = new Button();
        SuspendLayout();
        commandBarContainer.SuspendLayout();
        commandFlow.SuspendLayout();
        commandBarContainer.Name = "standardCommandFrame";
        commandBarContainer.Dock = DockStyle.Fill;
        commandBarContainer.BorderStyle = BorderStyle.FixedSingle;
        commandBarContainer.BackColor = Color.FromArgb(239, 239, 239);
        commandBarContainer.Margin = Padding.Empty;
        commandBarContainer.Padding = new Padding(1);
        commandBarContainer.Controls.Add(commandFlow);
        commandBarContainer.Controls.Add(closeHost);
        closeHost.Name = "standardCloseHost";
        closeHost.Dock = DockStyle.Left;
        closeHost.Width = 28;
        commandFlow.Name = "standardCommandFlow";
        commandFlow.Dock = DockStyle.Fill;
        commandFlow.FlowDirection = FlowDirection.RightToLeft;
        commandFlow.RightToLeft = RightToLeft.No;
        commandFlow.WrapContents = false;
        commandFlow.AutoScroll = true;
        commandFlow.Margin = Padding.Empty;
        retainedControls.Name = "retainedCommandComponents";
        retainedControls.Visible = false;
        retainedControls.Size = Size.Empty;
        cmdAdd.Name = "standardAdd";
        cmdAdd.AccessibleName = "إضافة";
        cmdAdd.Text = "";
        cmdAdd.Size = new Size(26, 24);
        cmdAdd.Margin = new Padding(1);
        cmdAdd.FlatStyle = FlatStyle.Flat;
        cmdAdd.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        cmdAdd.Enabled = false;
        cmdAdd.TabIndex = 0;
        cmdAdd.Image = (Image?)resources.GetObject("btnAdd.Image");
        toolTips.SetToolTip(cmdAdd, "إضافة");
        commandFlow.Controls.Add(cmdAdd);
        cmdEdit.Name = "standardEdit";
        cmdEdit.AccessibleName = "تعديل";
        cmdEdit.Text = "";
        cmdEdit.Size = new Size(26, 24);
        cmdEdit.Margin = new Padding(1);
        cmdEdit.FlatStyle = FlatStyle.Flat;
        cmdEdit.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        cmdEdit.Enabled = false;
        cmdEdit.TabIndex = 1;
        cmdEdit.Image = (Image?)resources.GetObject("btnEdit.Image");
        toolTips.SetToolTip(cmdEdit, "تعديل");
        commandFlow.Controls.Add(cmdEdit);
        cmdDelete.Name = "standardDelete";
        cmdDelete.AccessibleName = "حذف";
        cmdDelete.Text = "";
        cmdDelete.Size = new Size(26, 24);
        cmdDelete.Margin = new Padding(1);
        cmdDelete.FlatStyle = FlatStyle.Flat;
        cmdDelete.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        cmdDelete.Enabled = false;
        cmdDelete.TabIndex = 2;
        cmdDelete.Image = (Image?)resources.GetObject("btnDelete.Image");
        toolTips.SetToolTip(cmdDelete, "حذف");
        commandFlow.Controls.Add(cmdDelete);
        cmdCancel.Name = "standardCancel";
        cmdCancel.AccessibleName = "تراجع";
        cmdCancel.Text = "";
        cmdCancel.Size = new Size(26, 24);
        cmdCancel.Margin = new Padding(1);
        cmdCancel.FlatStyle = FlatStyle.Flat;
        cmdCancel.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        cmdCancel.Enabled = false;
        cmdCancel.TabIndex = 3;
        cmdCancel.Image = (Image?)resources.GetObject("btnCancel.Image");
        toolTips.SetToolTip(cmdCancel, "تراجع");
        commandFlow.Controls.Add(cmdCancel);
        cmdView.Name = "standardView";
        cmdView.AccessibleName = "عرض / بحث";
        cmdView.Text = "";
        cmdView.Size = new Size(26, 24);
        cmdView.Margin = new Padding(1);
        cmdView.FlatStyle = FlatStyle.Flat;
        cmdView.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        cmdView.Enabled = false;
        cmdView.TabIndex = 4;
        cmdView.Image = (Image?)resources.GetObject("btnView.Image");
        toolTips.SetToolTip(cmdView, "عرض / بحث");
        commandFlow.Controls.Add(cmdView);
        cmdLast.Name = "standardLast";
        cmdLast.AccessibleName = "آخر سجل";
        cmdLast.Text = "";
        cmdLast.Size = new Size(26, 24);
        cmdLast.Margin = new Padding(1);
        cmdLast.FlatStyle = FlatStyle.Flat;
        cmdLast.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        cmdLast.Enabled = false;
        cmdLast.TabIndex = 5;
        cmdLast.Image = (Image?)resources.GetObject("btnLast.Image");
        toolTips.SetToolTip(cmdLast, "آخر سجل");
        commandFlow.Controls.Add(cmdLast);
        cmdNext.Name = "standardNext";
        cmdNext.AccessibleName = "التالي";
        cmdNext.Text = "";
        cmdNext.Size = new Size(26, 24);
        cmdNext.Margin = new Padding(1);
        cmdNext.FlatStyle = FlatStyle.Flat;
        cmdNext.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        cmdNext.Enabled = false;
        cmdNext.TabIndex = 6;
        cmdNext.Image = (Image?)resources.GetObject("btnNext.Image");
        toolTips.SetToolTip(cmdNext, "التالي");
        commandFlow.Controls.Add(cmdNext);
        cmdPrevious.Name = "standardPrevious";
        cmdPrevious.AccessibleName = "السابق";
        cmdPrevious.Text = "";
        cmdPrevious.Size = new Size(26, 24);
        cmdPrevious.Margin = new Padding(1);
        cmdPrevious.FlatStyle = FlatStyle.Flat;
        cmdPrevious.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        cmdPrevious.Enabled = false;
        cmdPrevious.TabIndex = 7;
        cmdPrevious.Image = (Image?)resources.GetObject("btnPrevious.Image");
        toolTips.SetToolTip(cmdPrevious, "السابق");
        commandFlow.Controls.Add(cmdPrevious);
        cmdFirst.Name = "standardFirst";
        cmdFirst.AccessibleName = "أول سجل";
        cmdFirst.Text = "";
        cmdFirst.Size = new Size(26, 24);
        cmdFirst.Margin = new Padding(1);
        cmdFirst.FlatStyle = FlatStyle.Flat;
        cmdFirst.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        cmdFirst.Enabled = false;
        cmdFirst.TabIndex = 8;
        cmdFirst.Image = (Image?)resources.GetObject("btnFirst.Image");
        toolTips.SetToolTip(cmdFirst, "أول سجل");
        commandFlow.Controls.Add(cmdFirst);
        cmdSave.Name = "standardSave";
        cmdSave.AccessibleName = "حفظ";
        cmdSave.Text = "";
        cmdSave.Size = new Size(26, 24);
        cmdSave.Margin = new Padding(1);
        cmdSave.FlatStyle = FlatStyle.Flat;
        cmdSave.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        cmdSave.Enabled = false;
        cmdSave.TabIndex = 9;
        cmdSave.Image = (Image?)resources.GetObject("btnSave.Image");
        toolTips.SetToolTip(cmdSave, "حفظ");
        commandFlow.Controls.Add(cmdSave);
        cmdPrint.Name = "standardPrint";
        cmdPrint.AccessibleName = "طباعة";
        cmdPrint.Text = "";
        cmdPrint.Size = new Size(26, 24);
        cmdPrint.Margin = new Padding(1);
        cmdPrint.FlatStyle = FlatStyle.Flat;
        cmdPrint.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        cmdPrint.Enabled = false;
        cmdPrint.TabIndex = 10;
        cmdPrint.Image = (Image?)resources.GetObject("btnPrint.Image");
        toolTips.SetToolTip(cmdPrint, "طباعة");
        commandFlow.Controls.Add(cmdPrint);
        cmdClose.Name = "standardClose";
        cmdClose.AccessibleName = "خروج";
        cmdClose.Text = "";
        cmdClose.Size = new Size(26, 24);
        cmdClose.Margin = new Padding(1);
        cmdClose.FlatStyle = FlatStyle.Flat;
        cmdClose.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        cmdClose.Enabled = false;
        cmdClose.TabIndex = 11;
        cmdClose.Image = (Image?)resources.GetObject("btnClose.Image");
        toolTips.SetToolTip(cmdClose, "خروج");
        closeHost.Controls.Add(cmdClose);
        cmdRefresh.Name = "standardRefresh";
        cmdRefresh.AccessibleName = "تحديث";
        cmdRefresh.Text = "";
        cmdRefresh.Size = new Size(26, 24);
        cmdRefresh.Margin = new Padding(1);
        cmdRefresh.FlatStyle = FlatStyle.Flat;
        cmdRefresh.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        cmdRefresh.Enabled = false;
        cmdRefresh.TabIndex = 12;
        cmdRefresh.AccessibleDescription = "Missing icon; command not connected";
        toolTips.SetToolTip(cmdRefresh, "تحديث");
        commandFlow.Controls.Add(cmdRefresh);
        cmdImport.Name = "standardImport";
        cmdImport.AccessibleName = "استيراد";
        cmdImport.Text = "";
        cmdImport.Size = new Size(26, 24);
        cmdImport.Margin = new Padding(1);
        cmdImport.FlatStyle = FlatStyle.Flat;
        cmdImport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        cmdImport.Enabled = false;
        cmdImport.TabIndex = 13;
        cmdImport.AccessibleDescription = "Missing icon; command not connected";
        toolTips.SetToolTip(cmdImport, "استيراد");
        commandFlow.Controls.Add(cmdImport);
        cmdExport.Name = "standardExport";
        cmdExport.AccessibleName = "تصدير";
        cmdExport.Text = "";
        cmdExport.Size = new Size(26, 24);
        cmdExport.Margin = new Padding(1);
        cmdExport.FlatStyle = FlatStyle.Flat;
        cmdExport.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        cmdExport.Enabled = false;
        cmdExport.TabIndex = 14;
        cmdExport.AccessibleDescription = "Missing icon; command not connected";
        toolTips.SetToolTip(cmdExport, "تصدير");
        commandFlow.Controls.Add(cmdExport);
        cmdHelp.Name = "standardHelp";
        cmdHelp.AccessibleName = "مساعدة";
        cmdHelp.Text = "";
        cmdHelp.Size = new Size(26, 24);
        cmdHelp.Margin = new Padding(1);
        cmdHelp.FlatStyle = FlatStyle.Flat;
        cmdHelp.FlatAppearance.BorderColor = Color.FromArgb(163, 163, 163);
        cmdHelp.Enabled = false;
        cmdHelp.TabIndex = 15;
        cmdHelp.AccessibleDescription = "Missing icon; command not connected";
        toolTips.SetToolTip(cmdHelp, "مساعدة");
        commandFlow.Controls.Add(cmdHelp);
        Controls.Add(commandBarContainer);
        Controls.Add(retainedControls);
        Name = "standardCommandBar";
        AutoScaleMode = AutoScaleMode.Dpi;
        AutoScaleDimensions = new SizeF(96F, 96F);
        RightToLeft = RightToLeft.Yes;
        Margin = Padding.Empty;
        Size = new Size(900, 44);
        MinimumSize = new Size(0, 44);
        commandFlow.ResumeLayout(false);
        commandBarContainer.ResumeLayout(false);
        ResumeLayout(false);
    }
    private Panel commandBarContainer = null!;
    private Panel closeHost = null!;
    private FlowLayoutPanel commandFlow = null!;
    private Panel retainedControls = null!;
    private ToolTip toolTips = null!;
    private Button cmdAdd = null!;
    private Button cmdEdit = null!;
    private Button cmdDelete = null!;
    private Button cmdCancel = null!;
    private Button cmdView = null!;
    private Button cmdLast = null!;
    private Button cmdNext = null!;
    private Button cmdPrevious = null!;
    private Button cmdFirst = null!;
    private Button cmdSave = null!;
    private Button cmdPrint = null!;
    private Button cmdClose = null!;
    private Button cmdRefresh = null!;
    private Button cmdImport = null!;
    private Button cmdExport = null!;
    private Button cmdHelp = null!;
}
